// Theory Learning Unit 1: Data Representation and Storage (Exploring IT: Theory Grade 10, 2nd ed)
import { Binary } from 'lucide-react';

export const UNIT = { id: 'T1', number: 1, name: 'Data Representation and Storage', worldId: 'data-representation' };

export const SKILLS = {
  'T1-S1': {
    unit: 'T1',
    name: 'Number systems, bits and bytes',
    description: 'Explain why a computer is a two-state machine and describe decimal, binary and hexadecimal place values, bits and bytes.',
    sections: ['1.1', '1.2'],
  },
  'T1-S2': {
    unit: 'T1',
    name: 'Binary to decimal',
    description: 'Convert a binary number to decimal using powers of 2 and the expanded form.',
    sections: ['1.2.1', '1.2.1.1', '1.2.1.2'],
  },
  'T1-S3': {
    unit: 'T1',
    name: 'Decimal to binary',
    description: 'Convert a decimal number to binary with the repeated division method or the subtraction (alternative) method.',
    sections: ['1.2.2', '1.2.2.1', '1.2.2.2', '1.2.2.3'],
  },
  'T1-S4': {
    unit: 'T1',
    name: 'Decimal to hexadecimal',
    description: 'Use the hex digits 0-9 and A-F and convert decimal to hexadecimal by repeated division by 16.',
    sections: ['1.2.3'],
  },
  'T1-S5': {
    unit: 'T1',
    name: 'Hexadecimal to decimal',
    description: 'Convert a hexadecimal number to decimal using powers of 16.',
    sections: ['1.2.4'],
  },
  'T1-S6': {
    unit: 'T1',
    name: 'Hexadecimal and binary',
    description: 'Convert between hex and binary, both via decimal and directly using groups of 4 bits.',
    sections: ['1.2.5', '1.2.6', '1.2.6.1', '1.2.6.2'],
  },
  'T1-S7': {
    unit: 'T1',
    name: 'Combinations and word size',
    description: 'Calculate the number of combinations in n bits (2 to the power n) and explain word size.',
    sections: ['1.3', '1.3.1'],
  },
  'T1-S8': {
    unit: 'T1',
    name: 'Data storage units',
    description: 'Use bits, bytes, KB, MB, GB, TB, PB and EB as powers of 2 (1 KB = 1024 bytes).',
    sections: ['1.4'],
  },
  'T1-S9': {
    unit: 'T1',
    name: 'Unsigned and signed integer ranges',
    description: 'Work out the smallest and largest unsigned and signed integers that fit in n bits using the summary formulas.',
    sections: ['1.5', '1.5.1', '1.5.1.1', '1.5.1.2', '1.5.2', '1.5.2.1', '1.5.2.2', '1.5.3'],
  },
  'T1-S10': {
    unit: 'T1',
    name: 'Primitive data types',
    description: 'Relate the size in bytes of primitive data types to the range of values they can store.',
    sections: ['1.5.4'],
  },
  'T1-S11': {
    unit: 'T1',
    name: 'Character representation',
    description: 'Describe the 80 x 25 text screen, ASCII and its failings, Unicode, UTF-8 and inserting symbols with Alt codes.',
    sections: ['1.6', '1.6.1', '1.6.2', '1.6.3', '1.6.3.1', '1.6.3.2', '1.6.3.3'],
  },
  'T1-S12': {
    unit: 'T1',
    name: 'Screen data and colour',
    description: 'Calculate screen memory and refresh data, and represent RGB colours in decimal, binary and hex.',
    sections: ['1.7', '1.7.1', '1.7.2'],
  },
  'T1-S13': {
    unit: 'T1',
    name: 'Binary addition',
    description: 'Add binary numbers column by column from the right, carrying 1 when a column adds up to 2 or 3, and recognise overflow when the answer needs more bits.',
    sections: ['Extra'],
  },
  'T1-S14': {
    unit: 'T1',
    name: 'Binary subtraction',
    description: 'Subtract binary numbers column by column from the right, borrowing from the next column when subtracting 1 from 0, and check the answer by adding.',
    sections: ['Extra'],
  },
};

export const SKILL_HINTS = {
  'T1-S1': 'Computer is a two-state machine (0 or 1); decimal is base-10, binary base-2, hex base-16; a bit is a binary digit, a byte is 8 bits; place values are powers of the base starting at power 0 on the right',
  'T1-S2': 'Binary to decimal: multiply each bit by its power of 2 (1, 2, 4, 8, 16, 32, 64, 128) and add, e.g. 1101010 base 2 = 64+32+8+2 = 106',
  'T1-S3': 'Decimal to binary: divide by 2 repeatedly, write remainders, stop at quotient 0, read remainders bottom to top; or subtract the largest powers of 2 (167 = 128+32+4+2+1 = 10100111)',
  'T1-S4': 'Hex digits 0-9 then A=10 to F=15; decimal to hex: divide by 16 and read remainders bottom to top, each remainder is one hex digit (223 = DF)',
  'T1-S5': 'Hex to decimal: multiply each digit by its power of 16 (1, 16, 256, 4096) and add, e.g. ACE = 10x256 + 12x16 + 14 = 2766',
  'T1-S6': 'Because 16 = 2 to the power 4, each hex digit is exactly 4 bits; pad binary on the left with 0s to a multiple of 4, then convert each group (1111011 = 0111 1011 = 7B)',
  'T1-S7': 'n bits give 2 to the power n combinations (4 bits = 16, 8 bits = 256, 16 bits = 65536); word size is the number of bits the processor works with at one time, currently 32 or 64',
  'T1-S8': '8 bits = 1 byte; 1 KB = 2^10 = 1024 bytes; MB = 2^20, GB = 2^30, TB = 2^40, PB = 2^50, EB = 2^60 bytes; small b means bits, capital B means bytes',
  'T1-S9': 'n unsigned bits: 0 to 2^n - 1; n signed bits (first bit is the sign, 1 = negative): -2^(n-1) to 2^(n-1) - 1; 8 bits signed is -128 to 127',
  'T1-S10': 'C++ primitive types: char 1 byte, short 2 bytes (-32768 to 32767), int 4 bytes (-2147483648 to 2147483647), bool 1 byte, float 4 bytes, double 8 bytes; more bits means a bigger range',
  'T1-S11': '80 x 25 text mode screen had 2000 character cells; extended ASCII used 8 bits for 256 characters but was inconsistent and too small; Unicode gives every character a unique number; UTF-8 uses 1 to 4 bytes (octets); Alt+0189 inserts a half symbol',
  'T1-S12': 'Screen memory = width x height x bytes per pixel; per second multiply by refresh rate in Hz; RGB uses 1 byte each for red, green, blue (0-255), 3 bytes per pixel, 2^24 = 16 777 216 colours; white is FFFFFF',
  'T1-S13': 'Binary addition from the right: 0+0=0, 0+1=1, 1+1=10 (write 0, carry 1), 1+1+1=11 (write 1, carry 1); e.g. 1011 + 110 = 10001 (11 + 6 = 17); check by converting to decimal; overflow when the answer needs more bits than are available (11111111 + 1 needs 9 bits); ask for answers as binary digits only, stating whether leading zeros are wanted',
  'T1-S14': 'Binary subtraction from the right: 0-0=0, 1-0=1, 1-1=0, 0-1 needs a borrow: the column becomes 10 - 1 = 1 and the next column loses 1; borrowing across 0s turns them into 1s (10000 - 1 = 1111); e.g. 11001 - 1110 = 1011 (25 - 14 = 11); check by adding the answer to the number taken away; only use a smaller number taken from a larger one',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Binary Bazaar',
  subtitle: 'Unit 1 \u00b7 Data Representation',
  color: 'lime',
  glow: 'ja-glow-lime',
  bg: 'ja-w-data-representation',
  icon: Binary,
  blurb: 'Trade in bits, bytes and hex digits. Crack conversions, add and subtract in binary, size up integer ranges and paint pixels in pure RGB.',
};

export const LEVELS = [
  {
    id: 't1-l1',
    name: 'Bits and Bases',
    subtitle: 'Two-state machines, binary to decimal and back',
    challengeIds: ['t1-c1', 't1-c2', 't1-c3', 't1-c4', 't1-c5', 't1-c6'],
  },
  {
    id: 't1-l2',
    name: 'Carry and Borrow',
    subtitle: 'Binary addition, subtraction, carries and overflow',
    challengeIds: ['t1-c27', 't1-c28', 't1-c29', 't1-c30', 't1-c31', 't1-c32', 't1-c33', 't1-c34'],
  },
  {
    id: 't1-l3',
    name: 'Hex Highway',
    subtitle: 'Decimal, hexadecimal and binary conversions',
    challengeIds: ['t1-c7', 't1-c8', 't1-c9', 't1-c10', 't1-c11', 't1-c12', 't1-c13'],
  },
  {
    id: 't1-l4',
    name: 'Range Rover',
    subtitle: 'Combinations, storage units, integer ranges and data types',
    challengeIds: ['t1-c14', 't1-c15', 't1-c16', 't1-c17', 't1-c18', 't1-c19', 't1-c20'],
  },
  {
    id: 't1-l5',
    name: 'Pixel Palace (Boss)',
    subtitle: 'Characters, colour, screens and a full unit review',
    challengeIds: ['t1-c21', 't1-c22', 't1-c23', 't1-c24', 't1-c25', 't1-c26'],
  },
];

export const CHALLENGES = {
  't1-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why is a computer known as a two-state machine?',
    options: [
      'It can only run two programs at the same time',
      'It stores data on two devices: RAM and the hard drive',
      'It can only understand whether data is a 0 or a 1',
      'It uses both decimal and binary numbers internally',
    ],
    answer: 2,
    hint: 'Think about high and low voltages.',
    explanation: 'High and low voltages are interpreted as 1s and 0s, so a computer only understands two states: 0 or 1.',
    skills: ['T1-S1'],
  },
  't1-c2': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each term to its meaning.',
    pairs: [
      { left: 'Bit', right: 'A binary digit: either a 0 or a 1' },
      { left: 'Byte', right: 'A group of 8 bits' },
      { left: 'Binary', right: 'Base-2 number system using only the digits 0 and 1' },
      { left: 'Hexadecimal', right: 'Base-16 number system using the digits 0-9 and A-F' },
      { left: 'Decimal', right: 'Base-10 number system using the digits 0-9' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'The base tells you how many different digits the system uses.',
    explanation: 'Bit is short for binary digit, a byte is 8 bits, and each number system uses the digits from 0 up to one less than its base.',
    skills: ['T1-S1'],
  },
  't1-c3': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Convert each binary number to decimal (Exercise 1). Type only the decimal number.',
    code: 'Column values: 256 128 64 32 16 8 4 2 1\n\na) 1011\nb) 10111\nc) 101011010',
    rows: [
      { label: 'a) 1011 in decimal', answer: '11' },
      { label: 'b) 10111 in decimal', answer: '23' },
      { label: 'c) 101011010 in decimal', answer: '346' },
    ],
    hint: 'Line the bits up under the column values from the right, then add the column values where there is a 1.',
    explanation: '1011 = 8+2+1 = 11; 10111 = 16+4+2+1 = 23; 101011010 = 256+64+16+8+2 = 346.',
    skills: ['T1-S2'],
  },
  't1-c4': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the steps of the algorithm for converting a decimal number to another base in the correct order.',
    items: [
      'Repeat the previous steps until the quotient is 0',
      'Divide the decimal number by the base required',
      'The answer is the remainders read from bottom to top',
      'Write down the quotient and the remainder',
    ],
    answer: [1, 3, 0, 2],
    hint: 'You cannot read the answer until you have reached a quotient of 0.',
    explanation: 'Divide by the base, record the quotient and remainder, repeat until the quotient is 0, then read the remainders from bottom to top.',
    skills: ['T1-S3'],
  },
  't1-c5': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Convert each decimal number to binary (Exercise 2). Type the bits with no leading zeros.',
    code: '140 / 2 = ?  remainder ?\n...\nRead the remainders from bottom to top.\n\na) 140\nb) 79\nc) 42',
    rows: [
      { label: 'a) 140 in binary', answer: '10001100' },
      { label: 'b) 79 in binary', answer: '1001111' },
      { label: 'c) 42 in binary', answer: '101010' },
    ],
    hint: 'Alternative method: subtract the largest power of 2 that fits (128, 64, 32 ...) and put a 1 in that column.',
    explanation: '140 = 128+8+4 = 10001100; 79 = 64+8+4+2+1 = 1001111; 42 = 32+8+2 = 101010.',
    skills: ['T1-S3'],
  },
  't1-c6': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: 1101010 base 2 = 106 base 10, and if a number is written without a base it is assumed to be base 10.',
    answer: true,
    hint: 'Add 64 + 32 + 8 + 2, and recall the convention for leaving out the base.',
    explanation: '64+32+8+2 = 106, and by convention a number without a subscript base is taken to be decimal.',
    skills: ['T1-S1', 'T1-S2'],
  },
  't1-c7': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Dividing 223 by 16 gives remainders 15 and then 13. Why is the answer 1315 base 16 incorrect?',
    options: [
      'Each hex position can hold only one digit, so 13 and 15 must be written as D and F',
      'The remainders should be read from top to bottom, giving 1513',
      'You must divide by 2 first and then group the remainders',
      'Hexadecimal cannot represent numbers larger than 200',
    ],
    answer: 0,
    hint: 'How many digits fit in one power-of-16 column?',
    explanation: 'Read as 1315 base 16 the value is 4885, not 223. The values 13 and 15 must be single hex digits D and F, so 223 = DF base 16.',
    skills: ['T1-S4'],
  },
  't1-c8': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Convert each decimal number to hexadecimal (Exercise 3 and Check Point 1). Type hex digits in UPPERCASE.',
    code: 'Divide by 16, read remainders bottom to top.\nHex digits: 10=A 11=B 12=C 13=D 14=E 15=F\n\na) 140\nb) 79\nc) 31\nd) 82',
    rows: [
      { label: 'a) 140 in hex', answer: '8C' },
      { label: 'b) 79 in hex', answer: '4F' },
      { label: 'c) 31 in hex', answer: '1F' },
      { label: 'd) 82 in hex', answer: '52' },
    ],
    hint: '140 / 16 = 8 remainder 12. What is the hex digit for 12?',
    explanation: '140 = 8x16 + 12 = 8C; 79 = 4x16 + 15 = 4F; 31 = 1x16 + 15 = 1F; 82 = 5x16 + 2 = 52.',
    skills: ['T1-S4'],
  },
  't1-c9': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Convert each hexadecimal number to decimal (Exercise 4). Type only the decimal number.',
    code: 'Column values: 4096 256 16 1\n\na) ABC\nb) FACE\nc) 10\nd) 76',
    rows: [
      { label: 'a) ABC in decimal', answer: '2748' },
      { label: 'b) FACE in decimal', answer: '64206' },
      { label: 'c) 10 in decimal', answer: '16' },
      { label: 'd) 76 in decimal', answer: '118' },
    ],
    hint: 'Replace letters with their values (A=10 ... F=15) and multiply by the power of 16 for that column.',
    explanation: 'ABC = 10x256 + 11x16 + 12 = 2748; FACE = 15x4096 + 10x256 + 12x16 + 14 = 64206; 10 = 1x16 = 16; 76 = 7x16 + 6 = 118.',
    skills: ['T1-S5'],
  },
  't1-c10': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Any number system uses the digits from 0 to one less than its base. Which digits does a base-5 system use?',
    options: ['0 to 5', '1 to 5', '0 to 9 and A to E', '0 to 4'],
    answer: 3,
    hint: 'Decimal is base-10 and uses 0 to 9.',
    explanation: 'Base-5 uses 5 digits: 0, 1, 2, 3 and 4 (5 - 1 = 4). In the same way hex needs 16 digits, 0 to F.',
    skills: ['T1-S4', 'T1-S5'],
  },
  't1-c11': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Convert each hexadecimal number directly to binary (Exercise 5 and Check Point 1). Write each hex digit as 4 bits, then drop any leading zeros from the final answer.',
    code: 'a) EF\nb) F00\nc) 123',
    rows: [
      { label: 'a) EF in binary', answer: '11101111' },
      { label: 'b) F00 in binary', answer: '111100000000' },
      { label: 'c) 123 in binary', answer: '100100011' },
    ],
    hint: 'E = 1110 and F = 1111. For 123, write 0001 0010 0011 first.',
    explanation: 'EF = 1110 1111; F00 = 1111 0000 0000; 123 = 0001 0010 0011 = 100100011 once the leading zeros are dropped (decimal 291).',
    skills: ['T1-S6'],
  },
  't1-c12': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Convert each binary number directly to hexadecimal (Exercise 5 and Check Point 1). Type hex digits in UPPERCASE.',
    code: 'a) 10101111\nb) 1100001011\nc) 100111101\nd) 1110100101110',
    rows: [
      { label: 'a) 10101111 in hex', answer: 'AF' },
      { label: 'b) 1100001011 in hex', answer: '30B' },
      { label: 'c) 100111101 in hex', answer: '13D' },
      { label: 'd) 1110100101110 in hex', answer: '1D2E' },
    ],
    hint: 'Pad with 0s on the left until the number of bits is a multiple of 4, then split into groups of 4 from the right.',
    explanation: '1010 1111 = AF; 0011 0000 1011 = 30B; 0001 0011 1101 = 13D; 0001 1101 0010 1110 = 1D2E.',
    skills: ['T1-S6'],
  },
  't1-c13': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why does every hexadecimal digit correspond to exactly 4 bits?',
    options: [
      'Because a byte is 4 bits long',
      'Because 16 is 2 to the power 4',
      'Because hex only uses the letters A to F',
      'Because 4 is the word size of most processors',
    ],
    answer: 1,
    hint: 'How many combinations can 4 bits make?',
    explanation: '4 bits give 2^4 = 16 combinations (0000 to 1111), exactly the 16 hex digits 0 to F.',
    skills: ['T1-S6', 'T1-S7'],
  },
  't1-c14': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Write down the number of combinations in each number of bits (Exercise 6 and Check Point 1).',
    code: 'combinations = 2^n\n\na) 7 bits\nb) 9 bits\nc) 10 bits\nd) 16 bits',
    rows: [
      { label: 'a) 7 bits', answer: '128' },
      { label: 'b) 9 bits', answer: '512' },
      { label: 'c) 10 bits', answer: '1024' },
      { label: 'd) 16 bits', answer: '65536' },
    ],
    hint: 'Each extra bit doubles the number of combinations. 8 bits give 256.',
    explanation: '2^7 = 128, 2^9 = 512, 2^10 = 1024 and 2^16 = 65536, because each bit position can be either 0 or 1.',
    skills: ['T1-S7'],
  },
  't1-c15': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'What is word size (word length)?',
    options: [
      'The number of characters a word processor can store in one word',
      'The number of bytes in one kilobyte of memory',
      'The number of bits that the processor can work with at one time',
      'The number of letters in the longest word in the ASCII set',
    ],
    answer: 2,
    hint: 'Bits are grouped together, just like letters are grouped into words.',
    explanation: 'Word size is the number of bits the processor can work with at one time. Current word sizes are 32 or 64 bits.',
    skills: ['T1-S7'],
  },
  't1-c16': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each unit of storage to its size.',
    pairs: [
      { left: '1 Kilobyte (KB)', right: '2^10 bytes = 1024 bytes' },
      { left: '1 Megabyte (MB)', right: '2^20 bytes = 1024 x 1024 bytes' },
      { left: '1 Gigabyte (GB)', right: '2^30 bytes' },
      { left: '1 Terabyte (TB)', right: '2^40 bytes' },
      { left: '1 Byte', right: '8 bits' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Each unit is 1024 (2^10) times bigger than the one before it.',
    explanation: 'Storage units grow in steps of 2^10 = 1024: KB = 2^10, MB = 2^20, GB = 2^30, TB = 2^40 bytes.',
    skills: ['T1-S8'],
  },
  't1-c17': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Complete the Exercise 7 table of integer ranges. Type whole numbers only (use a minus sign for negatives, no spaces or commas).',
    code: '                 Smallest   Largest\n8 signed bits       ?          ?\n16 unsigned bits    0          ?\n16 signed (short)   ?        32767\n32 signed (int)  -2147483648   ?',
    rows: [
      { label: '8 signed bits: smallest', answer: '-128' },
      { label: '8 signed bits: largest', answer: '127' },
      { label: '16 unsigned bits: largest', answer: '65535' },
      { label: '16 signed bits: smallest', answer: '-32768' },
      { label: '32 signed bits: largest', answer: '2147483647' },
    ],
    hint: 'Unsigned: 0 to 2^n - 1. Signed: -2^(n-1) to 2^(n-1) - 1.',
    explanation: '8 signed: -2^7 = -128 to 2^7 - 1 = 127; 16 unsigned: 2^16 - 1 = 65535; 16 signed: -2^15 = -32768; 32 signed: 2^31 - 1 = 2147483647.',
    skills: ['T1-S9', 'T1-S10'],
  },
  't1-c18': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: the largest number that can be stored in 6 signed bits is 63.',
    code: '0 1 1 1 1 1',
    answer: false,
    hint: 'The first bit is used for the sign, so only 5 bits hold the value.',
    explanation: '011111 = 1+2+4+8+16 = 31, which matches 2^(6-1) - 1 = 31. The value 63 is the largest 6-bit unsigned number.',
    skills: ['T1-S9'],
  },
  't1-c19': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'In the C++ primitive data types table, which type is 2 bytes with a signed range of -32768 to 32767?',
    options: ['short int', 'char', 'int', 'float'],
    answer: 0,
    hint: '2 bytes = 16 bits, and -2^15 = -32768.',
    explanation: 'short int uses 2 bytes (16 bits): signed -32768 to 32767, unsigned 0 to 65535. char is 1 byte, int and float are 4 bytes.',
    skills: ['T1-S10'],
  },
  't1-c20': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Arrange these units of storage from smallest to largest.',
    items: ['Gigabyte', 'Byte', 'Petabyte', 'Kilobyte', 'Terabyte', 'Megabyte'],
    answer: [1, 3, 5, 0, 4, 2],
    hint: 'Kilo, Mega, Giga, Tera, Peta: each step is 1024 times bigger.',
    explanation: 'Byte, KB (2^10), MB (2^20), GB (2^30), TB (2^40), PB (2^50). An Exabyte (2^60) would come next.',
    skills: ['T1-S8'],
  },
  't1-c21': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which problem with ASCII and other early encodings does Unicode solve?',
    options: [
      'ASCII screens could not display any letters, only line drawing symbols',
      'ASCII used too many bits, so files were too large',
      'ASCII could only be used on 80 x 25 screens with colour',
      'Encodings were inconsistent, so data moved between computers could be corrupted',
    ],
    answer: 3,
    hint: 'Think about what happens when two computers use different numbers for the same character.',
    explanation: 'Unicode gives every character a unique number on every operating system, device, application and language, so there is no corruption from inconsistent encodings.',
    skills: ['T1-S11'],
  },
  't1-c22': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each character representation term to its description.',
    pairs: [
      { left: 'ASCII', right: 'Early character set using 8 bits per character, extended to 256 characters' },
      { left: 'Unicode', right: 'Standard giving a unique number to every character, no matter the device or language' },
      { left: 'UTF-8', right: 'Uses at least 1 byte and up to 4 bytes per character' },
      { left: 'Octet', right: 'A group of 8 bits (1 byte) in UTF-8' },
      { left: '<Alt>+0189', right: 'Types a half (1/2) symbol using the numeric keypad' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Octo means eight.',
    explanation: 'ASCII used 2^8 = 256 codes; Unicode standardised one number per character; UTF-8 stores characters in 1 to 4 octets; Alt codes use the 4-digit decimal code.',
    skills: ['T1-S11'],
  },
  't1-c23': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'A colour is represented by the RGB values 200, 100 and 50 (Check Point 1). Write each byte as 8 bits (keep leading zeros), then write the whole colour as 6 hex digits in UPPERCASE.',
    code: '        red   green   blue\nbytes   200    100     50\nbits     ?      ?       ?\nhex      ?      ?       ?',
    rows: [
      { label: 'Red in binary (8 bits)', answer: '11001000' },
      { label: 'Green in binary (8 bits)', answer: '01100100' },
      { label: 'Blue in binary (8 bits)', answer: '00110010' },
      { label: 'Total number of bits for the colour', answer: '24' },
      { label: 'Whole colour in hex (6 digits)', answer: 'C86432' },
    ],
    hint: '200 = 128+64+8. Split each byte into two groups of 4 bits to get two hex digits.',
    explanation: '200 = 1100 1000 = C8, 100 = 0110 0100 = 64, 50 = 0011 0010 = 32, so the colour is C86432. It takes 3 bytes = 24 bits.',
    skills: ['T1-S12', 'T1-S3', 'T1-S6'],
  },
  't1-c24': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Calculate the memory needed in bytes. Type whole numbers only (no spaces or commas).',
    code: 'Old text screen: 80 x 25 cells, 1 byte per ASCII character, 60Hz\nModern screen:   1920 x 1080 pixels, 3 bytes per pixel (RGB), 120Hz',
    rows: [
      { label: 'One 80 x 25 screen (bytes)', answer: '2000' },
      { label: 'One second of 80 x 25 screens at 60Hz (bytes)', answer: '120000' },
      { label: 'One 1920 x 1080 screen (bytes)', answer: '6220800' },
      { label: 'One second of 1920 x 1080 at 120Hz (bytes)', answer: '746496000' },
    ],
    hint: 'Bytes per screen = width x height x bytes per cell or pixel. Per second, multiply by the refresh rate.',
    explanation: '80 x 25 x 1 = 2000 bytes, x 60 = 120000 bytes per second. 1920 x 1080 x 3 = 6220800 bytes, x 120 = 746496000 bytes per second.',
    skills: ['T1-S12', 'T1-S8'],
  },
  't1-c25': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: 240, 300, 12 is a valid RGB colour.',
    answer: false,
    hint: 'Each of red, green and blue is stored in one byte.',
    explanation: 'One unsigned byte stores 0 to 255 (2^8 - 1), so 300 cannot be stored as a colour value.',
    skills: ['T1-S12', 'T1-S9'],
  },
  't1-c26': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Check Point 1 asks for the range of 64 signed bits. Which expression gives the largest number?',
    options: ['2^64 - 1', '2^63 - 1', '2^63', '-2^63'],
    answer: 1,
    hint: 'One bit is used for the sign, and 0 is counted among the positive values.',
    explanation: 'For n signed bits the largest is 2^(n-1) - 1 = 2^63 - 1 and the smallest is -2^63. 2^64 - 1 is the largest 64-bit unsigned number.',
    skills: ['T1-S9'],
  },
  't1-c27': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each column sum in binary addition to what you write and carry.',
    pairs: [
      { left: '0 + 0', right: 'Write 0, carry nothing' },
      { left: '0 + 1', right: 'Write 1, carry nothing' },
      { left: '1 + 1', right: 'Write 0, carry 1' },
      { left: '1 + 1 + 1 (with a carry)', right: 'Write 1, carry 1' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'In decimal, 1 + 1 = 2 and 1 + 1 + 1 = 3. Write 2 and 3 in binary.',
    explanation: '1 + 1 = 2, which is 10 in binary: write 0 and carry 1. 1 + 1 + 1 = 3, which is 11 in binary: write 1 and carry 1.',
    skills: ['T1-S13'],
  },
  't1-c28': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Add these binary numbers. Type the answer in binary with no leading zeros.',
    code: 'a)   101 + 10\nb)  1011 + 110\nc) 11011 + 1101\nd)  1111 + 1',
    rows: [
      { label: 'a) 101 + 10', answer: '111' },
      { label: 'b) 1011 + 110', answer: '10001' },
      { label: 'c) 11011 + 1101', answer: '101000' },
      { label: 'd) 1111 + 1', answer: '10000' },
    ],
    hint: 'Line the numbers up on the right and work from right to left. Remember the carries.',
    explanation: 'Check in decimal: a) 5 + 2 = 7 = 111. b) 11 + 6 = 17 = 10001. c) 27 + 13 = 40 = 101000. d) 15 + 1 = 16 = 10000: every column carries.',
    skills: ['T1-S13'],
  },
  't1-c29': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Add the two bytes, then check your answer in decimal. Type the binary answer as 8 bits.',
    code: '   01101101\n+  00110110\n   --------\n   ????????',
    rows: [
      { label: 'Binary answer (8 bits)', answer: '10100011' },
      { label: '01101101 in decimal', answer: '109' },
      { label: '00110110 in decimal', answer: '54' },
      { label: 'Answer in decimal', answer: '163' },
    ],
    hint: 'Columns from the right: 1+0, 0+1, 1+1, 1+0+carry ...',
    explanation: '01101101 = 64+32+8+4+1 = 109 and 00110110 = 32+16+4+2 = 54. 109 + 54 = 163 = 128+32+2+1 = 10100011.',
    skills: ['T1-S13', 'T1-S2'],
  },
  't1-c30': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: 11111111 + 00000001 fits in one byte.',
    answer: false,
    hint: '11111111 is the largest unsigned byte. What is 255 + 1?',
    explanation: 'The answer is 100000000 (256), which needs 9 bits. One byte only holds 0 to 255, so the final carry is lost. This is called overflow.',
    skills: ['T1-S13', 'T1-S9'],
  },
  't1-c31': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each column in binary subtraction to its result.',
    pairs: [
      { left: '0 - 0', right: '0' },
      { left: '1 - 0', right: '1' },
      { left: '1 - 1', right: '0, nothing borrowed' },
      { left: '0 - 1', right: '1, after borrowing from the next column' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'You cannot take 1 from 0 without borrowing. A borrowed 1 is worth 2 in this column.',
    explanation: 'For 0 - 1, borrow 1 from the column on the left. It is worth 2 here, so the column becomes 10 - 1 = 1, and the column on the left is reduced by 1.',
    skills: ['T1-S14'],
  },
  't1-c32': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Subtract these binary numbers. Type the answer in binary with no leading zeros.',
    code: 'a)   110 - 11\nb)  1010 - 101\nc) 10000 - 1\nd) 11001 - 1110',
    rows: [
      { label: 'a) 110 - 11', answer: '11' },
      { label: 'b) 1010 - 101', answer: '101' },
      { label: 'c) 10000 - 1', answer: '1111' },
      { label: 'd) 11001 - 1110', answer: '1011' },
    ],
    hint: 'Work from right to left. When you take 1 from 0, borrow from the next column that has a 1.',
    explanation: 'Check in decimal: a) 6 - 3 = 3 = 11. b) 10 - 5 = 5 = 101. c) 16 - 1 = 15 = 1111: the borrow turns every 0 into 1. d) 25 - 14 = 11 = 1011.',
    skills: ['T1-S14'],
  },
  't1-c33': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why is 1000 - 1 equal to 111 in binary?',
    options: [
      'The 1 is borrowed from the left, so every 0 it passes becomes 1 and the leading 1 becomes 0',
      'Subtracting 1 always flips every bit of the number',
      'Binary subtraction ignores the leftmost bit',
      'The rightmost 0 becomes 1 and the other bits stay the same',
    ],
    answer: 0,
    hint: 'Check in decimal: 8 - 1 = 7.',
    explanation: 'The rightmost column needs a borrow, but the next columns are 0, so the borrow comes from the leading 1. That 1 becomes 0 and each 0 on the way becomes 1: 0111 = 7.',
    skills: ['T1-S14'],
  },
  't1-c34': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Subtract, then check by adding. Type the subtraction answer as 8 bits and the check in binary with no leading zeros.',
    code: '   10110100\n-  01011011\n   --------\n   ????????\n\nCheck: answer + 01011011 = ?',
    rows: [
      { label: 'Answer (8 bits)', answer: '01011001' },
      { label: 'Answer in decimal', answer: '89' },
      { label: 'Check: answer + 01011011', answer: '10110100' },
    ],
    hint: '10110100 = 180 and 01011011 = 91.',
    explanation: '180 - 91 = 89 = 64+16+8+1 = 01011001. Adding 01011001 + 01011011 gives 10110100 (180) again, which proves the subtraction is correct.',
    skills: ['T1-S14', 'T1-S13'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Understand how a computer represents and stores numbers, characters and colours using bits, and convert between decimal, binary and hexadecimal.',
  outcomes: [
    'By the end you can explain why a computer is a two-state machine and define a bit and a byte.',
    'By the end you can convert between binary and decimal in both directions.',
    'By the end you can add and subtract binary numbers, using carries and borrows, and recognise overflow.',
    'By the end you can convert between decimal and hexadecimal in both directions.',
    'By the end you can convert between hexadecimal and binary, via decimal and directly using groups of 4 bits.',
    'By the end you can calculate the number of combinations in n bits and explain word size.',
    'By the end you can use the units of data storage from bytes to exabytes.',
    'By the end you can calculate the smallest and largest unsigned and signed integers in n bits.',
    'By the end you can relate primitive data types to their size and range.',
    'By the end you can describe ASCII, Unicode and UTF-8 and insert symbols with Alt codes.',
    'By the end you can calculate screen memory and represent RGB colours in decimal, binary and hex.',
  ],
  topics: [
    {
      id: 'T1-T1',
      title: 'From abacus to bits: number systems',
      sections: ['1.1', '1.2'],
      skills: ['T1-S1'],
      explanation: [
        'The abacus and Morse code worked in their day but could not succeed in an electronic computer: neither could be stored unless written down, both were operated mechanically (slow), and Morse code used a different number of dots and dashes for each letter.',
        'Modern computers use a digital, electronic coding method: high and low voltages, in groups of specific sizes, are interpreted as 0s and 1s.',
        'A computer is known as a two-state machine because it can only understand whether data is a 0 or a 1.',
        'We use the decimal number system (base-10), probably because we have ten fingers. Binary (base-2) uses 0s and 1s, and its relative hexadecimal (base-16) is used in many computer contexts.',
        'Place values are powers of the base: decimal columns are 10^0 = 1, 10^1 = 10, 10^2 = 100 ...; binary columns are 2^0 = 1, 2^1 = 2, 2^2 = 4 ... up to 2^8 = 256. Anything to the power 0 is 1.',
      ],
      vocabulary: [
        { term: 'Two-state machine', definition: 'A computer, because it can only understand whether data is a 0 or a 1.' },
        { term: 'Bit', definition: 'Abbreviation for binary digit; either a 0 or a 1.' },
        { term: 'Byte', definition: 'A group of 8 bits.' },
        { term: 'Base', definition: 'The number on which the column values of a number system are based (10 for decimal, 2 for binary, 16 for hex).' },
      ],
      workedExamples: [
        {
          code: 'Decimal powers      Binary powers\n10^0 = 1            2^0 = 1\n10^1 = 10           2^1 = 2\n10^2 = 100          2^2 = 4\n10^3 = 1000         2^3 = 8\n...                 2^8 = 256',
          explanation: 'Columns increase in powers of the base, starting at power 0 on the right.',
        },
      ],
      misconceptions: [
        'Thinking Morse code would suit a computer: its codes have different lengths for different letters, which complicates managing and storing the data.',
        'Thinking 10^0 or 2^0 is 0: anything to the power 0 is 1, so the rightmost column is always worth 1.',
      ],
      questions: [
        {
          id: 'T1-T1-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'Which of these is the textbook definition of a byte?',
          options: ['A single binary digit', 'A group of 8 bits', 'A group of 4 bits', 'A group of 1024 bits'],
          answer: 1,
          hint: 'It is the unit used for one ASCII character.',
          explanation: 'A byte is a group of 8 bits. A single binary digit is a bit.',
          skills: ['T1-S1'],
        },
        {
          id: 'T1-T1-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: Morse code would be ideal for storing data in a computer because every letter uses the same number of dots and dashes.',
          answer: false,
          hint: 'Compare the code for E with the code for another letter.',
          explanation: 'Morse code uses a different number of dots or dashes for each letter, which complicates how data is managed and stored.',
          skills: ['T1-S1'],
        },
        {
          id: 'T1-T1-Q3',
          type: 'mc',
          category: 'identify',
          prompt: 'The textbook jokes that a mouse, with four fingers on each front paw, would prefer which number system?',
          options: ['Binary (base-2)', 'Decimal (base-10)', 'Hexadecimal (base-16)', 'Octal (base-8)'],
          answer: 3,
          hint: 'Count the fingers on both front paws.',
          explanation: 'Four fingers on each of two paws gives eight, so a mouse would count in octal (base-8), just as our ten fingers suggest base-10.',
          skills: ['T1-S1'],
        },
      ],
    },
    {
      id: 'T1-T2',
      title: 'Binary to decimal and back',
      sections: ['1.2.1', '1.2.1.1', '1.2.1.2', '1.2.2', '1.2.2.1', '1.2.2.2', '1.2.2.3'],
      skills: ['T1-S2', 'T1-S3'],
      explanation: [
        'Binary to decimal: write the bits under their powers of 2 (increasing from 2^0 on the right), multiply each bit by its column value and add (the expanded form).',
        'Good practice is to write the base of both numbers as a subscript, e.g. 1101010 base 2 = 106 base 10. If you leave out a base, it is assumed to be base 10.',
        'Decimal to binary (division method): divide by 2, write down the quotient and the remainder, repeat until the quotient is 0, then read the remainders from bottom to top.',
        'The same algorithm converts decimal to any base: divide by the base required instead of 2.',
        'Alternative method: write the number as a sum of powers of 2 (1, 2, 4, 8, 16, 32, 64, 128 ...). Subtract the largest power that fits, place a 1 in that column, and repeat with what is left. Any method can be used if the answer is correct.',
      ],
      vocabulary: [
        { term: 'Expanded form', definition: 'Writing a number as the sum of each digit multiplied by its column power, e.g. 1 x 2^6 + 1 x 2^5 + ...' },
        { term: 'Quotient', definition: 'The whole-number result of a division, e.g. 106 / 2 = 53 remainder 0.' },
        { term: 'Remainder', definition: 'What is left over after dividing; in binary conversion it is always 0 or 1.' },
      ],
      workedExamples: [
        {
          code: '2^6 2^5 2^4 2^3 2^2 2^1 2^0\n 1   1   0   1   0   1   0\n= 64 + 32 + 0 + 8 + 0 + 2 + 0 = 106',
          explanation: 'Example 1 of 1.2.1: 1101010 base 2 = 106 base 10. Example 2: 10110 base 2 = 16 + 4 + 2 = 22.',
        },
        {
          code: '167 / 2 = 83 r 1\n 83 / 2 = 41 r 1\n 41 / 2 = 20 r 1\n 20 / 2 = 10 r 0\n 10 / 2 =  5 r 0\n  5 / 2 =  2 r 1\n  2 / 2 =  1 r 0\n  1 / 2 =  0 r 1   read upwards: 10100111',
          explanation: 'Division method: 167 base 10 = 10100111 base 2.',
        },
        {
          code: '167 - 128 = 39   (1 in the 128 column)\n 39 -  32 =  7   (64 no, 32 yes)\n  7 -   4 =  3   (16 no, 8 no, 4 yes)\n  3 -   2 =  1   (2 yes)\n  1 -   1 =  0   (1 yes)\n=> 1 0 1 0 0 1 1 1',
          explanation: 'Alternative method: subtract the largest power of 2 that fits each time.',
        },
      ],
      misconceptions: [
        'Reading the remainders from top to bottom: the first remainder is the rightmost bit (2^0), so you must read from the bottom up.',
        'Stopping when the quotient reaches 1: you stop only when the quotient is 0, otherwise you lose the leftmost 1.',
      ],
      questions: [
        {
          id: 'T1-T2-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Convert these binary numbers to decimal (Exercise 1 d and Check Point 1). Type only the decimal number.',
          code: 'a) 11111111\nb) 10101111',
          rows: [
            { label: 'a) 11111111 in decimal', answer: '255' },
            { label: 'b) 10101111 in decimal', answer: '175' },
          ],
          hint: 'For 8 bits the column values are 128 64 32 16 8 4 2 1.',
          explanation: '11111111 = 128+64+32+16+8+4+2+1 = 255; 10101111 = 128+32+8+4+2+1 = 175.',
          skills: ['T1-S2'],
        },
        {
          id: 'T1-T2-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'Convert these decimal numbers to binary (Exercise 2 and Check Point 1). Type the bits with no leading zeros.',
          code: 'a) 31\nb) 64\nc) 65',
          rows: [
            { label: 'a) 31 in binary', answer: '11111' },
            { label: 'b) 64 in binary', answer: '1000000' },
            { label: 'c) 65 in binary', answer: '1000001' },
          ],
          hint: '64 is a power of 2 by itself; 31 is one less than 32.',
          explanation: '31 = 16+8+4+2+1 = 11111; 64 = 2^6 = 1000000; 65 = 64+1 = 1000001.',
          skills: ['T1-S3'],
        },
        {
          id: 'T1-T2-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'Using the alternative (subtraction) method to convert 167 to binary, what is the first value you subtract?',
          options: ['64', '100', '128', '256'],
          answer: 2,
          hint: 'Choose the largest power of 2 that is not bigger than 167.',
          explanation: '128 is the largest power of 2 that fits into 167 (256 is too big), leaving 39. Then 32, 4, 2 and 1 follow.',
          skills: ['T1-S3'],
        },
      ],
    },
    {
      id: 'T1-T3',
      title: 'Binary addition and subtraction',
      sections: ['Extra'],
      skills: ['T1-S13', 'T1-S14'],
      explanation: [
        'This topic is not in the textbook, but it builds directly on binary place values. Binary numbers are added and subtracted column by column from the right, exactly like decimal sums, except that each column can only hold 0 or 1.',
        'Addition rules: 0 + 0 = 0, 0 + 1 = 1, 1 + 0 = 1, 1 + 1 = 10 (write 0, carry 1) and 1 + 1 + 1 = 11 (write 1, carry 1). A carry is worth 2 in the column it came from, which is 1 in the next column to the left.',
        'Overflow happens when the answer needs more bits than are available. In one byte, 11111111 + 00000001 = 100000000 (255 + 1 = 256) needs 9 bits, so the final carry is lost.',
        'Subtraction rules: 0 - 0 = 0, 1 - 0 = 1, 1 - 1 = 0, and 0 - 1 needs a borrow. Borrow 1 from the column on the left; it is worth 2 here, so the column becomes 10 - 1 = 1, and the column on the left goes down by 1.',
        'If the column on the left is 0, keep moving left until you find a 1. That 1 becomes 0 and every 0 you passed becomes 1, which is why 10000 - 1 = 1111.',
        'Always check: convert the numbers to decimal, or add the answer to the number you took away. You should get back the number you started with.',
      ],
      vocabulary: [
        { term: 'Carry', definition: 'The 1 moved to the next column on the left when a column adds up to 2 (10) or 3 (11).' },
        { term: 'Borrow', definition: 'Taking 1 from the next column on the left so that 1 can be subtracted from 0; it is worth 2 in the current column.' },
        { term: 'Overflow', definition: 'When the answer of a calculation needs more bits than the storage space has, so the leftmost carry is lost.' },
      ],
      workedExamples: [
        {
          code: 'carries  1 1 1\n          1 0 1 1      (11)\n        +   1 1 0      (6)\n        ---------\n        1 0 0 0 1      (17)',
          explanation: 'From the right: 1+0 = 1; 1+1 = 10, write 0 carry 1; 0+1+1 = 10, write 0 carry 1; 1+0+1 = 10, write 0 carry 1; the last carry is written as the leading 1.',
        },
        {
          code: '          1 1 0 0 1    (25)\n        -   1 1 1 0    (14)\n        -----------\n            1 0 1 1    (11)',
          explanation: 'From the right: 1-0 = 1; 0-1 borrows from the 4s column, which is 0, so the borrow comes from the 8s column (8s becomes 0, 4s becomes 1), giving 10-1 = 1; then 1-1 = 0; then 0-1 borrows from the 16s column, giving 10-1 = 1; the 16s column is now 0. Check: 1011 + 1110 = 11001.',
        },
      ],
      misconceptions: [
        'Writing 2 as a digit in binary: 1 + 1 is 10, not 2.',
        'Forgetting the final carry: 1111 + 1 is 10000, not 0000 (unless only 4 bits are available, which is overflow).',
        'Borrowing only from the next column when it is 0: the borrow must come from the nearest 1 on the left, and the 0s in between become 1s.',
      ],
      questions: [
        {
          id: 'T1-T3-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Work out each sum. Type the answer in binary with no leading zeros.',
          code: 'a)  10110 + 1011\nb)   1110 + 111\nc) 100111 + 11101',
          rows: [
            { label: 'a) 10110 + 1011', answer: '100001' },
            { label: 'b) 1110 + 111', answer: '10101' },
            { label: 'c) 100111 + 11101', answer: '1000100' },
          ],
          hint: 'Check in decimal: a) 22 + 11, b) 14 + 7, c) 39 + 29.',
          explanation: 'a) 22 + 11 = 33 = 100001. b) 14 + 7 = 21 = 10101. c) 39 + 29 = 68 = 1000100.',
          skills: ['T1-S13'],
        },
        {
          id: 'T1-T3-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'Work out each difference. Type the answer in binary with no leading zeros.',
          code: 'a)   1101 - 110\nb) 101101 - 10110\nc)  11100 - 111',
          rows: [
            { label: 'a) 1101 - 110', answer: '111' },
            { label: 'b) 101101 - 10110', answer: '10111' },
            { label: 'c) 11100 - 111', answer: '10101' },
          ],
          hint: 'Check in decimal: a) 13 - 6, b) 45 - 22, c) 28 - 7.',
          explanation: 'a) 13 - 6 = 7 = 111. b) 45 - 22 = 23 = 10111. c) 28 - 7 = 21 = 10101.',
          skills: ['T1-S14'],
        },
        {
          id: 'T1-T3-Q3',
          type: 'mc',
          category: 'explain',
          prompt: 'When adding a column of 1 + 1 + 1 (two bits and a carry), what do you do?',
          options: [
            'Write 3 and carry nothing',
            'Write 0 and carry 1',
            'Write 1 and carry 1',
            'Write 1 and carry 2',
          ],
          answer: 2,
          hint: '3 in binary is 11.',
          explanation: '1 + 1 + 1 = 3, which is 11 in binary: write the right-hand 1 in this column and carry the other 1 to the next column.',
          skills: ['T1-S13'],
        },
        {
          id: 'T1-T3-Q4',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: overflow happens when the answer of a binary sum needs more bits than the storage space has.',
          answer: true,
          hint: 'Think of 11111111 + 1 stored in one byte.',
          explanation: '255 + 1 = 256 = 100000000 needs 9 bits. In one byte the leftmost carry is lost, which is called overflow.',
          skills: ['T1-S13'],
        },
        {
          id: 'T1-T3-Q5',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps for subtracting 1 from 0 in a column in order.',
          items: [
            'Subtract: 10 - 1 = 1 in the current column',
            'Find the nearest 1 in a column to the left',
            'Change that 1 to 0 and every 0 you passed to 1',
            'Notice the top bit is 0 and the bottom bit is 1',
          ],
          answer: [3, 1, 2, 0],
          hint: 'You have to find something to borrow before you can subtract.',
          explanation: 'See that you need a borrow, find the nearest 1 on the left, change it to 0 and the 0s in between to 1s, and then the current column becomes 10 - 1 = 1.',
          skills: ['T1-S14'],
        },
      ],
    },
    {
      id: 'T1-T4',
      title: 'Hexadecimal and decimal',
      sections: ['1.2.3', '1.2.4'],
      skills: ['T1-S4', 'T1-S5'],
      explanation: [
        'Hexadecimal ("hex") is base-16 and is used extensively in computing. Decimal to hex works like decimal to binary, except you divide by 16 instead of 2.',
        'Any number system uses the digits from 0 to one less than the base: decimal 0-9, binary 0-1, base-5 0-4. Hex needs the digits 0 to 15, but 15 is not one digit.',
        'Any base larger than 10 uses letters for values greater than 9. Hex digits: 0 1 2 3 4 5 6 7 8 9 A(10) B(11) C(12) D(13) E(14) F(15).',
        'Each remainder must be one digit. 223 / 16 = 13 remainder 15, then 13 / 16 = 0 remainder 13, so 223 = DF base 16 (not 1315, which would equal 4885).',
        'Hex to decimal: multiply each digit by its power of 16 (1, 16, 256, 4096 ...) and add. ACE base 16 = 10 x 256 + 12 x 16 + 14 x 1 = 2766.',
      ],
      vocabulary: [
        { term: 'Hexadecimal (hex)', definition: 'The base-16 number system, using the digits 0-9 and A-F.' },
        { term: 'Hex digit', definition: 'A single symbol 0-9 or A-F representing a value from 0 to 15.' },
      ],
      workedExamples: [
        {
          code: '223 / 16 = 13 r 15  -> F\n 13 / 16 =  0 r 13  -> D\nread upwards: DF\ncheck: 13 x 16 + 15 x 1 = 208 + 15 = 223',
          explanation: 'Decimal to hex, then proving the answer by converting back.',
        },
        {
          code: '16^2  16^1  16^0\n  A     C     E\n10x256 12x16 14x1\n 2560 + 192 + 14 = 2766',
          explanation: 'Hex to decimal: ACE base 16 = 2766 base 10.',
        },
      ],
      misconceptions: [
        'Writing a remainder of 13 as the two digits 1 and 3: each remainder must be a single hex digit (13 = D).',
        'Thinking hex column values go 1, 16, 32, 64: they are powers of 16, so 1, 16, 256, 4096.',
      ],
      questions: [
        {
          id: 'T1-T4-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Convert these decimal numbers to hexadecimal (Exercise 3). Type hex digits in UPPERCASE.',
          code: 'a) 64\nb) 42\nc) 223',
          rows: [
            { label: 'a) 64 in hex', answer: '40' },
            { label: 'b) 42 in hex', answer: '2A' },
            { label: 'c) 223 in hex', answer: 'DF' },
          ],
          hint: 'Divide by 16; remainders above 9 become letters.',
          explanation: '64 = 4 x 16 + 0 = 40; 42 = 2 x 16 + 10 = 2A; 223 = 13 x 16 + 15 = DF.',
          skills: ['T1-S4'],
        },
        {
          id: 'T1-T4-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'Convert these hexadecimal numbers to decimal. Type only the decimal number.',
          code: 'a) EF\nb) 5B\nc) C8',
          rows: [
            { label: 'a) EF in decimal', answer: '239' },
            { label: 'b) 5B in decimal', answer: '91' },
            { label: 'c) C8 in decimal', answer: '200' },
          ],
          hint: 'First digit x 16, plus the second digit.',
          explanation: 'EF = 14 x 16 + 15 = 239; 5B = 5 x 16 + 11 = 91; C8 = 12 x 16 + 8 = 200.',
          skills: ['T1-S5'],
        },
        {
          id: 'T1-T4-Q3',
          type: 'mc',
          category: 'identify',
          prompt: 'Which hex digit represents the decimal value 12?',
          options: ['C', 'B', 'D', 'E'],
          answer: 0,
          hint: 'A is 10.',
          explanation: 'A = 10, B = 11, C = 12, D = 13, E = 14, F = 15.',
          skills: ['T1-S4', 'T1-S5'],
        },
        {
          id: 'T1-T4-Q4',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: the value of the 1 in 10 base 16 is the same as the value of the 1 in 10 base 10.',
          answer: false,
          hint: 'What is the column value just left of the units in each base?',
          explanation: 'In hex that column is 16^1 = 16, so 10 base 16 = 16 base 10, while 10 base 10 is ten.',
          skills: ['T1-S5'],
        },
      ],
    },
    {
      id: 'T1-T5',
      title: 'Hexadecimal and binary',
      sections: ['1.2.5', '1.2.6', '1.2.6.1', '1.2.6.2'],
      skills: ['T1-S6'],
      explanation: [
        'Two-step method: convert hex to decimal, then decimal to binary. DF base 16 = 223 base 10 = 11011111 base 2.',
        'Because 16 = 2^4, every 4 bits make up exactly 1 hex digit (0000 = 0 up to 1111 = F). So each hex digit can simply be written as its 4-bit binary equivalent: D = 1101 and F = 1111, giving DF = 11011111.',
        'Binary to hex reverses this, but the number of bits must be a multiple of 4. Add leading 0s on the left if needed: 11 base 2 becomes 0011.',
        'Example: 1111011 (7 bits) = 01111011 (8 bits) = 0111 1011 = 7 and 11 = 7B.',
        'Example: 100010001 (9 bits) = 000100010001 (12 bits) = 0001 0001 0001 = 111 base 16.',
      ],
      vocabulary: [
        { term: 'Leading zeros', definition: '0s added to the left of a binary number to make the number of bits a multiple of 4; they do not change its value.' },
        { term: 'Group of 4 bits', definition: 'Because 16 = 2^4, every 4 bits make up exactly 1 hex digit.' },
      ],
      workedExamples: [
        {
          code: 'Dec  Bin   Hex      Dec  Bin   Hex\n 0   0000   0        8   1000   8\n 1   0001   1        9   1001   9\n 2   0010   2       10   1010   A\n 3   0011   3       11   1011   B\n 4   0100   4       12   1100   C\n 5   0101   5       13   1101   D\n 6   0110   6       14   1110   E\n 7   0111   7       15   1111   F',
          explanation: 'The 0 to 15 table that links every hex digit to a 4-bit binary pattern.',
        },
        {
          code: '100010001 base 2 (9 bits)\n-> 0001 0001 0001 (12 bits)\n->   1    1    1\n= 111 base 16',
          explanation: 'Pad to a multiple of 4 bits on the left, then convert each group.',
        },
      ],
      misconceptions: [
        'Adding the padding zeros on the right: that changes the value. Leading zeros go on the left.',
        'Grouping bits from the left without padding first: groups of 4 must line up from the right-hand side.',
      ],
      questions: [
        {
          id: 'T1-T5-Q1',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps for converting a binary number directly to hexadecimal in order.',
          items: [
            'Work out the value (0 to 15) of each group of 4 bits',
            'Add leading 0s so the number of bits is a multiple of 4',
            'Write each group value as a single hex digit and join the digits',
            'Split the bits into groups of 4',
          ],
          answer: [1, 3, 0, 2],
          hint: 'You cannot split evenly into groups until the length is right.',
          explanation: 'Pad on the left, split into groups of 4, find each group value, then write it as one hex digit (e.g. 0111 1011 = 7 11 = 7B).',
          skills: ['T1-S6'],
        },
        {
          id: 'T1-T5-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'Calculate X in each case (Exercise 5.5). Type hex in UPPERCASE and binary with no leading zeros.',
          code: 'a) X base 16 = 1001101 base 2\nb) X base 2  = CCD base 16\nc) X base 16 = 100 base 2\nd) X base 16 = 101 base 2',
          rows: [
            { label: 'a) X (hex)', answer: '4D' },
            { label: 'b) X (binary)', answer: '110011001101' },
            { label: 'c) X (hex)', answer: '4' },
            { label: 'd) X (hex)', answer: '5' },
          ],
          hint: 'For a), pad to 0100 1101. For b), C = 1100 and D = 1101.',
          explanation: '0100 1101 = 4D; CCD = 1100 1100 1101; 100 base 2 = 4 and 101 base 2 = 5, which are the same digits in hex.',
          skills: ['T1-S6'],
        },
        {
          id: 'T1-T5-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'How many leading 0s must be added to the 9-bit number 100010001 before converting it to hex?',
          options: ['3', '1', '4', '0'],
          answer: 0,
          hint: 'What is the next multiple of 4 after 9?',
          explanation: 'The next multiple of 4 is 12, so 3 leading 0s are needed: 000100010001 = 111 base 16.',
          skills: ['T1-S6'],
        },
      ],
    },
    {
      id: 'T1-T6',
      title: 'Combinations, word size and data storage',
      sections: ['1.3', '1.3.1', '1.4'],
      skills: ['T1-S7', 'T1-S8'],
      explanation: [
        'Word size (word length) is the number of bits the processor can work with at one time. Working with individual bits is too inefficient, so bits are grouped into words, just like letters are grouped into words. Current word sizes are 32 or 64 bits.',
        'The number of combinations in n bits is 2^n, because each bit position can be 0 or 1. 4 bits: 2 x 2 x 2 x 2 = 2^4 = 16; 5 bits: 32; 6 bits: 64.',
        'In a table of all combinations of 4 bits, the 2^0 column alternates one 0 then one 1, the 2^1 column repeats two 0s then two 1s, the 2^2 column four of each, and the 2^3 column eight of each.',
        'Memory capacity (RAM, hard disk drives) is measured in multiples of bytes. A small b usually indicates bits and a capital B indicates bytes.',
        '8 bits = 1 byte; 1 KB = 2^10 = 1024 bytes; 1 MB = 2^20; 1 GB = 2^30; 1 TB = 2^40; 1 PB = 2^50; 1 EB = 2^60 bytes. A megabyte is sometimes inaccurately taken as 1024 x 1000 = 1 024 000 bytes.',
      ],
      vocabulary: [
        { term: 'Word size (word length)', definition: 'The number of bits that a computer, more precisely the processor, can work with at one time.' },
        { term: 'Combinations', definition: 'The number of unique patterns of 0s and 1s in n bits, calculated as 2^n.' },
        { term: 'Kilobyte (KB)', definition: '2^10 = 1024 bytes, not 1000 bytes.' },
      ],
      workedExamples: [
        {
          code: '2^3 2^2 2^1 2^0\n 0   0   0   0\n 0   0   0   1\n 0   0   1   0\n 0   0   1   1\n ...\n 1   1   1   1     (16 rows = 2^4)',
          explanation: 'All 16 combinations of 4 bits; this is also the pattern in decimal 0 to 15 written in binary (Exercise 2.2).',
        },
        {
          code: '1 KB = 1024 bytes                     = 2^10\n1 MB = 1024 x 1024 bytes              = 2^20\n1 GB = 1024 x 1024 x 1024 bytes       = 2^30\n1 TB = 2^40   1 PB = 2^50   1 EB = 2^60',
          explanation: 'Each unit is 1024 times the previous one.',
        },
      ],
      misconceptions: [
        'Thinking 1 KB is exactly 1000 bytes: in this course 1 KB is 2^10 = 1024 bytes.',
        'Thinking 8 bits give 8 combinations: they give 2^8 = 256, because the possibilities multiply rather than add.',
      ],
      questions: [
        {
          id: 'T1-T6-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'How many combinations are possible in each number of bits?',
          code: 'a) 5 bits\nb) 6 bits\nc) 8 bits',
          rows: [
            { label: 'a) 5 bits', answer: '32' },
            { label: 'b) 6 bits', answer: '64' },
            { label: 'c) 8 bits', answer: '256' },
          ],
          hint: 'Use 2^n.',
          explanation: '2^5 = 32, 2^6 = 64, 2^8 = 256.',
          skills: ['T1-S7'],
        },
        {
          id: 'T1-T6-Q2',
          type: 'mc',
          category: 'define',
          prompt: 'According to the textbook, how many bytes are in 1 kilobyte?',
          options: ['1000', '1024', '1 024 000', '8'],
          answer: 1,
          hint: 'It is a power of 2.',
          explanation: '1 KB = 2^10 = 1024 bytes, not 1000 bytes.',
          skills: ['T1-S8'],
        },
        {
          id: 'T1-T6-Q3',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: in 8 Mb, the small b means bytes, and in 8 MB the capital B means bits.',
          answer: false,
          hint: 'Bytes are the bigger unit.',
          explanation: 'It is the other way round: a small b usually indicates bits and a capital B indicates bytes.',
          skills: ['T1-S8'],
        },
      ],
    },
    {
      id: 'T1-T7',
      title: 'Unsigned and signed integers',
      sections: ['1.5', '1.5.1', '1.5.1.1', '1.5.1.2', '1.5.2', '1.5.2.1', '1.5.2.2', '1.5.3'],
      skills: ['T1-S9'],
      explanation: [
        'Numbers are infinite, but a computer\'s memory is finite, so a fixed number of bits limits the numbers that can be stored. Integers are whole numbers (positive, negative or 0) with no decimal part; an integer has a sign and a value, e.g. +56.',
        'An unsigned integer uses all its bits for the value, so it can only be positive. Largest = 2^n - 1 (8 bits: 11111111 = 255); smallest = 0. There are still 2^n combinations, but 0 is one of the values.',
        'A signed integer uses the first bit for the sign: 0 means positive, 1 means negative. Largest = 2^(n-1) - 1 (8 bits: 01111111 = 127; 4 bits: 7; 6 bits: 31).',
        'Smallest signed = -2^(n-1) (4 bits: -8; 6 bits: -32; 8 bits: -128). We do not subtract 1 because 0 has already been counted with the positive integers. The proof of this formula is beyond the scope of the course.',
        'Summary of formulas: combinations in n bits = 2^n; n unsigned bits: 0 to 2^n - 1; n signed bits: -2^(n-1) to 2^(n-1) - 1.',
      ],
      vocabulary: [
        { term: 'Integer', definition: 'A number with no decimal part: a positive whole number, a negative whole number or 0.' },
        { term: 'Unsigned integer', definition: 'An integer without a sign that uses all the allocated bits for the value; it can only be positive.' },
        { term: 'Signed integer', definition: 'An integer whose first bit stores the sign (0 positive, 1 negative), leaving one less bit for the value.' },
      ],
      workedExamples: [
        {
          code: 'Bits  Unsigned range   Signed range\n  4    0 to 15          -8 to 7\n  6    0 to 63          -32 to 31\n  8    0 to 255         -128 to 127',
          explanation: 'The summary formulas applied to 4, 6 and 8 bits.',
        },
        {
          code: 'unsigned 8 bits: 1 1 1 1 1 1 1 1 = 255 = 2^8 - 1\nsigned 8 bits:   0 1 1 1 1 1 1 1 = 127 = 2^7 - 1',
          explanation: 'The sign bit takes one bit away from the value, reducing the exponent by 1.',
        },
      ],
      misconceptions: [
        'Thinking the largest unsigned number in n bits is 2^n: 0 uses up one combination, so the largest is 2^n - 1.',
        'Thinking the signed range is symmetrical (e.g. -127 to 127): the smallest is -2^(n-1), one further from 0 than the largest.',
      ],
      questions: [
        {
          id: 'T1-T7-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Use the summary formulas. Type whole numbers (use a minus sign for negatives).',
          code: 'n unsigned bits: 0 to 2^n - 1\nn signed bits:   -2^(n-1) to 2^(n-1) - 1',
          rows: [
            { label: '4 unsigned bits: largest', answer: '15' },
            { label: '4 signed bits: largest', answer: '7' },
            { label: '4 signed bits: smallest', answer: '-8' },
            { label: '6 unsigned bits: largest', answer: '63' },
          ],
          hint: '2^4 = 16 and 2^3 = 8.',
          explanation: '2^4 - 1 = 15; 2^3 - 1 = 7; -2^3 = -8; 2^6 - 1 = 63.',
          skills: ['T1-S9'],
        },
        {
          id: 'T1-T7-Q2',
          type: 'mc',
          category: 'explain',
          prompt: '8 bits give 256 combinations. Why is the largest unsigned 8-bit number 255 and not 256?',
          options: [
            'Because 0 is one of the 256 values',
            'Because one bit is used for the sign',
            'Because the computer reserves one value for errors',
            'Because 256 needs 10 bits to store',
          ],
          answer: 0,
          hint: 'Count the values from 0 up to 255.',
          explanation: 'The 256 combinations represent 0, 1, 2 ... 255. Unsigned integers have no sign bit.',
          skills: ['T1-S9'],
        },
        {
          id: 'T1-T7-Q3',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: in a signed integer, a first bit of 1 indicates a negative number.',
          answer: true,
          hint: 'Which bit value did the textbook allocate to positive numbers?',
          explanation: 'The first bit is the sign: 0 means positive and 1 means negative.',
          skills: ['T1-S9'],
        },
        {
          id: 'T1-T7-Q4',
          type: 'mc',
          category: 'identify',
          prompt: 'Which formula gives the smallest number in n signed bits?',
          options: ['0', '-2^n', '-2^(n-1)', '-(2^(n-1) - 1)'],
          answer: 2,
          hint: 'For 8 bits the answer is -128.',
          explanation: 'Smallest signed = -2^(n-1); for 8 bits that is -2^7 = -128. No 1 is subtracted because 0 is counted with the positives.',
          skills: ['T1-S9'],
        },
      ],
    },
    {
      id: 'T1-T8',
      title: 'Primitive data types',
      sections: ['1.5.4'],
      skills: ['T1-S10'],
      explanation: [
        'Most programming languages provide basic data types to store characters, text (strings), real numbers and integers.',
        'Each language decides how many bits to allocate to each data type, and this affects the ability of that type to store extremely large or small numbers.',
        'C++ examples: char 1 byte (signed -128 to 127, unsigned 0 to 255); short int 2 bytes (signed -32768 to 32767, unsigned 0 to 65535); int 4 bytes (signed -2147483648 to 2147483647, unsigned 0 to 4294967295); long int 4 bytes (same as int).',
        'bool is 1 byte and holds true or false. float is 4 bytes (+/- 3.4e +/- 38, about 7 digits); double and long double are 8 bytes (+/- 1.7e +/- 308, about 15 digits).',
        'Java has similar types: short is 16 signed bits and int is 32 signed bits, so they have the same ranges as the C++ signed short and int.',
      ],
      vocabulary: [
        { term: 'Primitive data type', definition: 'A basic data type provided by a programming language to store characters, real numbers, integers or Boolean values.' },
        { term: 'float', definition: 'A 4-byte floating point (real) number, about 7 digits of precision.' },
        { term: 'double', definition: 'An 8-byte double precision floating point (real) number, about 15 digits of precision.' },
      ],
      workedExamples: [
        {
          code: 'Name    Size     Signed range\nchar    1 byte   -128 to 127\nshort   2 bytes  -32768 to 32767\nint     4 bytes  -2147483648 to 2147483647\nbool    1 byte   true or false\nfloat   4 bytes  +/- 3.4e +/- 38 (~7 digits)\ndouble  8 bytes  +/- 1.7e +/- 308 (~15 digits)',
          explanation: 'The integer ranges follow directly from the signed formulas: 2 bytes = 16 bits gives -2^15 to 2^15 - 1.',
        },
      ],
      misconceptions: [
        'Thinking every language uses the same sizes: each language decides how many bits to allocate to each type.',
        'Thinking a bool needs only 1 bit of memory in this table: it occupies 1 byte even though it only stores true or false.',
      ],
      questions: [
        {
          id: 'T1-T8-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'Which C++ data type in the textbook table is 8 bytes with about 15 digits of precision?',
          options: ['float', 'double', 'long int', 'char'],
          answer: 1,
          hint: 'Its name suggests twice the precision of float.',
          explanation: 'double (double precision floating point) is 8 bytes, +/- 1.7e +/- 308 with about 15 digits; float is 4 bytes with about 7 digits.',
          skills: ['T1-S10'],
        },
        {
          id: 'T1-T8-Q2',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: in the textbook C++ table, long int uses 4 bytes and has the same range as int.',
          answer: true,
          hint: 'Compare the sizes in the two rows.',
          explanation: 'Both int and long int are listed as 4 bytes: signed -2147483648 to 2147483647.',
          skills: ['T1-S10'],
        },
        {
          id: 'T1-T8-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'A program must store whole numbers from 0 up to 4 000 000 000. Which C++ type from the table is suitable?',
          options: ['unsigned short int', 'signed int', 'unsigned int', 'unsigned char'],
          answer: 2,
          hint: 'Signed int stops at about 2.1 billion.',
          explanation: 'unsigned int covers 0 to 4294967295 (2^32 - 1). Signed int only reaches 2147483647 and short only 65535.',
          skills: ['T1-S10', 'T1-S9'],
        },
      ],
    },
    {
      id: 'T1-T9',
      title: 'Characters: ASCII, Unicode and UTF-8',
      sections: ['1.6', '1.6.1', '1.6.2', '1.6.3', '1.6.3.1', '1.6.3.2', '1.6.3.3'],
      skills: ['T1-S11'],
      explanation: [
        'In the 1970s computers displayed whole characters, not pixels. The 80 x 25 text mode screen was a grid of 80 characters across 25 rows, and each cell held one character.',
        'ASCII (American Standard Code for Information Interchange) was the first widely used character set. Each character was represented in 8 bits, and the set was extended to 256 characters (2^8): A-Z, a-z, 0-9, some accented and Greek letters, icons and a few line drawing symbols.',
        'ASCII and other early encodings had failings: languages like Afrikaans need more codes than they could provide, and encodings were not consistent (different numbers for the same characters), so transferring data between computers could corrupt it.',
        'Unicode provides a unique number for every character, no matter what operating system, device, application or language. All modern software providers have adopted it, so there is no corruption from inconsistent encoding.',
        'UTF-8 (Unicode Transformation Format) uses at least 8 bits (1 byte) per character and up to 32 bits (4 bytes); each group of 8 bits is called an octet.',
        'In MS Word you can insert characters not on the keyboard with Insert Symbol, or hold <Alt> and type the four-digit decimal code on the numeric keypad: <Alt>+0189 gives a half symbol. The Wingdings Yin Yang symbol has decimal code 91, which is hex 005B.',
      ],
      vocabulary: [
        { term: '80 x 25 text mode screen', definition: 'An early screen made of a grid of character cells, 80 characters across and 25 rows down.' },
        { term: 'ASCII', definition: 'American Standard Code for Information Interchange; the first widely used character set, using 8 bits per character (256 characters).' },
        { term: 'Unicode', definition: 'A standard that provides a unique number for every character, no matter what operating system, device, application or language.' },
        { term: 'UTF-8', definition: 'Unicode Transformation Format; represents each character with 1 to 4 bytes (octets).' },
        { term: 'Octet', definition: 'A group of 8 bits (1 byte) in UTF-8.' },
      ],
      workedExamples: [
        {
          code: 'Yin Yang (Wingdings): decimal 91\n91 / 16 = 5 r 11 -> 5B -> written 005B\ncheck: 5 x 16 + 11 = 80 + 11 = 91',
          explanation: 'Insert Symbol shows character codes; decimal and hex are the same value.',
        },
        {
          code: 'Hold <Alt>, type 0 1 8 9 on the numeric keypad, release <Alt>\n-> \u00bd',
          explanation: 'Alt codes need 4 digits, typed on the numeric keypad.',
        },
      ],
      misconceptions: [
        'Thinking ASCII could store every language: it ran out of codes for languages like Afrikaans and was inconsistent between computers.',
        'Thinking every UTF-8 character is exactly 1 byte: UTF-8 uses at least 1 byte and up to 4 bytes per character.',
        'Typing Alt codes on the number row above the letters: the digits must be typed on the numeric keypad.',
      ],
      questions: [
        {
          id: 'T1-T9-Q1',
          type: 'mc',
          category: 'calculate',
          prompt: 'How many character cells did an 80 x 25 text mode screen have?',
          options: ['105', '800', '1024', '2000'],
          answer: 3,
          hint: 'Multiply the columns by the rows.',
          explanation: '80 characters across x 25 rows = 2000 cells, each holding one character.',
          skills: ['T1-S11'],
        },
        {
          id: 'T1-T9-Q2',
          type: 'tf',
          category: 'define',
          prompt: 'True or false: Unicode provides a unique number for every character, no matter what operating system, device, application or language.',
          answer: true,
          hint: 'This is the textbook definition.',
          explanation: 'That is exactly the purpose of Unicode, which is why it removed the inconsistencies of older encodings.',
          skills: ['T1-S11'],
        },
        {
          id: 'T1-T9-Q3',
          type: 'trace',
          category: 'calculate',
          prompt: 'Check Point 1, question 8: the check mark symbol has the Unicode hex code 2713. Also convert the Yin Yang decimal code 91 to hex. Type hex in UPPERCASE and binary as 16 bits.',
          code: 'Check mark: hex 2713\nYin Yang:   decimal 91',
          rows: [
            { label: 'Check mark 2713 in binary (16 bits)', answer: '0010011100010011' },
            { label: 'Yin Yang 91 in hex (2 digits)', answer: '5B' },
          ],
          hint: 'Each hex digit becomes 4 bits: 2 = 0010, 7 = 0111.',
          explanation: '2713 = 0010 0111 0001 0011. 91 = 5 x 16 + 11 = 5B (shown as 005B in Word).',
          skills: ['T1-S11', 'T1-S6'],
        },
      ],
    },
    {
      id: 'T1-T10',
      title: 'Storing screen data and colour',
      sections: ['1.7', '1.7.1', '1.7.2'],
      skills: ['T1-S12'],
      explanation: [
        'The screen must show correct data in real time. The computer refreshes (redraws) the screen at a rate measured in hertz (Hz), the number of updates per second.',
        'Older 80 x 25 screens had no colour and showed only extended ASCII characters, 1 byte each: 80 x 25 x 1 byte = 2000 bytes (about 2KB) per screen. At 60Hz: 60 x 80 x 25 = 120000 bytes (about 120KB) per second, stored in RAM with a maximum of 640KB.',
        'Modern screens use a matrix of pixels (tiny dots), each with its own colour definition. RGB produces any colour of light by adding varying intensities of red, green and blue, each stored in 1 byte (0 to 255).',
        'Black is 0, 0, 0 (hex 00 00 00); white is 255, 255, 255 (FF FF FF); green is 0, 255, 0 (00 FF 00). Each pixel needs 3 bytes (24 bits), giving 256 x 256 x 256 = 2^24 = 16 777 216 possible colours.',
        'Resolutions range from 360 x 640 to 1920 x 1080. 360 x 640 x 3 bytes = 691200 bytes per screen; at an average 150Hz that is 103 680 000 bytes (about 104MB) per second. High-end gaming computers use a separate graphics card with its own RAM and processors.',
      ],
      vocabulary: [
        { term: 'Refresh rate', definition: 'How often the screen is redrawn, measured in hertz (Hz), the number of updates per second.' },
        { term: 'Pixel', definition: 'A tiny dot on the screen with its own colour definition.' },
        { term: 'RGB', definition: 'Red Green Blue: a system of producing any colour of light by adding varying intensities of red, green and blue light.' },
      ],
      workedExamples: [
        {
          code: '        red       green     blue\nblack   00000000  00000000  00000000   hex 00 00 00\nwhite   11111111  11111111  11111111   hex FF FF FF\ngreen   00000000  11111111  00000000   hex 00 FF 00',
          explanation: 'Each colour channel is one byte, written in decimal, binary or hex.',
        },
        {
          code: 'per screen: 360 x 640 x 3 bytes = 691200 bytes\nper second: 691200 x 150Hz = 103680000 bytes (about 104MB)',
          explanation: 'Memory per second = width x height x bytes per pixel x refresh rate.',
        },
      ],
      misconceptions: [
        'Thinking each pixel needs only 1 byte for colour: RGB needs 1 byte each for red, green and blue, so 3 bytes per pixel.',
        'Thinking a colour value of 256 is allowed: one byte stores 0 to 255 only.',
      ],
      questions: [
        {
          id: 'T1-T10-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'A 360 x 640 screen uses 3 bytes per pixel and refreshes at 150Hz. Type whole numbers only (no spaces or commas).',
          code: 'width x height x bytes per pixel x refresh rate',
          rows: [
            { label: 'Bytes for one screen', answer: '691200' },
            { label: 'Bytes per second', answer: '103680000' },
          ],
          hint: '360 x 640 = 230400.',
          explanation: '230400 pixels x 3 bytes = 691200 bytes; x 150 = 103680000 bytes per second (about 104MB).',
          skills: ['T1-S12'],
        },
        {
          id: 'T1-T10-Q2',
          type: 'mc',
          category: 'calculate',
          prompt: 'How many possible colours can be represented with 3 bytes per pixel in RGB?',
          options: ['16 777 216', '768', '65 536', '4 294 967 296'],
          answer: 0,
          hint: '3 bytes = 24 bits.',
          explanation: '256 x 256 x 256 = 2^24 = 16 777 216 colours. 768 is 256 x 3, which adds instead of multiplies.',
          skills: ['T1-S12', 'T1-S7'],
        },
        {
          id: 'T1-T10-Q3',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: the colour black is represented in RGB as FF FF FF.',
          answer: false,
          hint: 'Black means no light at all.',
          explanation: 'Black is 0, 0, 0 (00 00 00). FF FF FF is the maximum of all three, which is white.',
          skills: ['T1-S12'],
        },
        {
          id: 'T1-T10-Q4',
          type: 'mc',
          category: 'explain',
          prompt: 'What does a refresh rate of 60Hz mean?',
          options: [
            'The screen has 60 pixels per row',
            'The screen is redrawn 60 times per second',
            'The screen uses 60 bytes per character',
            'The screen can show 60 colours',
          ],
          answer: 1,
          hint: 'Hertz counts something per second.',
          explanation: 'Hertz (Hz) is the number of updates per second, so 60Hz means 60 refreshes of the screen every second.',
          skills: ['T1-S12'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't1-vault-cipher',
    unitId: UNIT.id,
    title: 'The Hex Vault Heist',
    icon: 'vault',
    summary: 'Crack the number-base locks before the vault seals.',
    briefing: 'Saboteurs have locked the Reserve Bank data vault in Pretoria behind a chain of keypads that only accept binary, decimal and hexadecimal codes. Every wrong conversion shortens the timer. Convert fast and accurately, Angelo, or the backups are sealed forever.',
    tickerMessages: [
      'Pretoria: Reserve Bank vault reports unusual keypad activity',
      'First lock demands a decimal code written in binary',
      'Second lock switches to hexadecimal; letters A to F spotted on the display',
      'Security warns: lock three converts hex straight to 4-bit groups',
      'Final lock arming now; one wrong digit seals the vault',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T1-S1', 'T1-S2', 'T1-S3', 'T1-S4', 'T1-S5', 'T1-S6'],
    victoryMessage: 'Every lock clicks open. The vault backups are safe, thanks to your flawless conversions.',
    failMessage: 'The vault seals with a heavy clunk. Revise your number base conversions and try again.',
  },
  {
    id: 't1-broadcast-blackout',
    unitId: UNIT.id,
    title: 'Broadcast Blackout',
    icon: 'radio',
    summary: 'Restore the national broadcast before the screens go dark.',
    briefing: 'A glitch has scrambled the control room of a Johannesburg TV broadcaster: colours, characters and memory budgets are all wrong. Fix the RGB values, the character encoding and the overflowing integer counters before the evening news goes out to millions.',
    tickerMessages: [
      'Johannesburg: evening news feed showing garbled Afrikaans subtitles',
      'Engineers report RGB values above 255 in the colour buffer',
      'Viewer counter overflowing its signed integer range',
      'Frame buffer memory running out at 120Hz',
      'Ten minutes to air; the whole country is waiting',
      'Final countdown: fix it now or broadcast black screens',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T1-S7', 'T1-S8', 'T1-S9', 'T1-S10', 'T1-S11', 'T1-S12'],
    victoryMessage: 'The news goes out in full colour with perfect subtitles. The control room cheers.',
    failMessage: 'Screens across the country go black. Review storage, ranges, encoding and colour, then try again.',
  },
  {
    id: 't1-ledger-meltdown',
    unitId: UNIT.id,
    title: 'Ledger Meltdown',
    icon: 'zap',
    summary: 'Balance the binary ledger before the payments run.',
    briefing: 'The calculator chip in a Durban bank\'s payment server has burnt out, and the ledger must be balanced by hand in pure binary. Add the deposits, subtract the withdrawals and watch for overflow before the midnight payment run, Angelo.',
    tickerMessages: [
      'Durban: payment server reports a fried arithmetic chip',
      'Deposits arriving in binary; carries everywhere',
      'Withdrawals need borrowing across long runs of zeros',
      'Warning: one byte counter is about to overflow',
      'Midnight payment run in minutes; balance the ledger now',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T1-S2', 'T1-S3', 'T1-S9', 'T1-S13', 'T1-S14'],
    victoryMessage: 'The ledger balances to the last bit. Every payment goes through on time.',
    failMessage: 'The payment run fails and the ledger is out of balance. Practise carries and borrows, then try again.',
  },
];
