// Theory Learning Unit 2: Overview of a Computer (Exploring IT: Theory Grade 10, 2nd ed)
import { Monitor } from 'lucide-react';

export const UNIT = { id: 'T2', number: 2, name: 'Overview of a Computer', worldId: 'computer-overview' };

export const SKILLS = {
  'T2-S1': { unit: 'T2', name: 'Hardware and software', description: 'Define hardware and software, give examples and explain why each needs the other.', sections: ['2.1'] },
  'T2-S2': { unit: 'T2', name: 'General processing cycle', description: 'Describe how input, processing, output and storage work through the CPU and RAM.', sections: ['2.1', '2.1.1'] },
  'T2-S3': { unit: 'T2', name: 'Connectivity and ICT', description: 'Explain how communication extends the processing model into an ICT system.', sections: ['2.1.2'] },
  'T2-S4': { unit: 'T2', name: 'Advantages and disadvantages', description: 'Classify professional, personal, environmental and upgrading advantages and disadvantages of computers.', sections: ['2.2'] },
  'T2-S5': { unit: 'T2', name: 'Data and information', description: 'Distinguish raw data from processed, useful information.', sections: ['2.3'] },
  'T2-S6': { unit: 'T2', name: 'Computer system types', description: 'Compare desktops, laptops, tablets, smartphones, smart wear, servers, embedded, single board and super computers.', sections: ['2.4'] },
  'T2-S7': { unit: 'T2', name: 'Operating systems', description: 'Explain what an operating system and its kernel do, and compare desktop, mobile and embedded operating systems.', sections: ['2.5', '2.5.1', '2.5.2', '2.5.3'] },
  'T2-S8': { unit: 'T2', name: 'Application software', description: 'Identify application software and explain how a stand-alone application is loaded and run.', sections: ['2.6', '2.6.1'] },
  'T2-S9': { unit: 'T2', name: 'Network applications', description: 'Describe client-server network applications using the terms client, server, local and remote.', sections: ['2.6.2'] },
  'T2-S10': { unit: 'T2', name: 'Data transfer and synchronising', description: 'Explain how devices transfer data and synchronise so both see the latest version.', sections: ['2.7'] },
};

export const SKILL_HINTS = {
  'T2-S1': 'Hardware = physical parts you can see and touch; software = non-physical parts (OS, application programs and data); each needs the other, e.g. an idle printer',
  'T2-S2': 'CPU (processor) executes instructions one at a time from RAM; all data must be in RAM before processing; RAM is not permanent; CPU cannot execute from secondary storage; screen shows only what is in RAM',
  'T2-S3': 'ICT = Information and Communication Technology; communication (networking) lets computers talk and exchange data; model becomes input, processing, output, storage and communication',
  'T2-S4': 'Advantages/disadvantages by area: professional (fast access vs electrical failures, unauthorised access), personal (online shopping vs injuries, scams), environmental (less paper vs toxic waste), upgrading',
  'T2-S5': 'Data = raw unorganised facts; information = processed data organised or presented in context to be useful, e.g. spreadsheet ages (data) become graphs and summaries (information)',
  'T2-S6': 'Computer types with processing power on a 1-10 scale: desktop 3-4, laptop 3-4, tablet 1-2, smartphone 1-2, smart wear 1, server 5-8, single board 1, super computer 10, embedded N/A',
  'T2-S7': 'OS manages hardware and lets users run applications; kernel is the smallest part always in memory; desktop OS (Windows, Mac OS, Linux), mobile OS (Android, iOS), embedded OS (compact, real-time)',
  'T2-S8': 'Application software does user tasks; test: will the computer run without it? YES means application; stand-alone app (e.g. Word) is copied from secondary storage into RAM and processed by the CPU',
  'T2-S9': 'Network application runs on many connected computers in a client-server network; server is remote and provides a service and usually stores the data; client is the local computer',
  'T2-S10': 'Synchronisation keeps data consistent so all devices see the latest version (contacts, calendars, email); via USB cable, dock, cradle, Wi-Fi, Internet or slower Bluetooth; can be two-way',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'System Station',
  subtitle: 'Unit 2 \u00b7 Overview of a Computer',
  color: 'cyan',
  glow: 'ja-glow-cyan',
  bg: 'ja-w-computer-overview',
  icon: Monitor,
  blurb: 'Boot up the big picture: hardware, software, the processing cycle and every type of computer from smartwatch to supercomputer. Sync your skills before the system crashes.',
};

export const LEVELS = [
  { id: 't2-l1', name: 'Power On', subtitle: 'Hardware, software and the processing cycle', challengeIds: ['t2-c1', 't2-c2', 't2-c3', 't2-c4', 't2-c5', 't2-c6'] },
  { id: 't2-l2', name: 'Data and Devices', subtitle: 'Pros and cons, data vs information, computer types', challengeIds: ['t2-c7', 't2-c8', 't2-c9', 't2-c10', 't2-c11', 't2-c12'] },
  { id: 't2-l3', name: 'Systems and Software', subtitle: 'Operating systems, applications and networks', challengeIds: ['t2-c13', 't2-c14', 't2-c15', 't2-c16', 't2-c17', 't2-c18'] },
  { id: 't2-l4', name: 'System Overload', subtitle: 'Boss: mixed review of the whole unit', challengeIds: ['t2-c19', 't2-c20', 't2-c21', 't2-c22', 't2-c23', 't2-c24', 't2-c25'] },
];

export const CHALLENGES = {
  't2-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Angelo\'s computer setup includes the items below. Which one counts as SOFTWARE according to the textbook\'s definition?',
    options: ['The essay document he typed in Word', 'The printer on his desk', 'The keyboard he types on', 'The RAM chips inside the case'],
    answer: 0,
    hint: 'Software is the collection of non-physical parts: the operating system, application programs and ...',
    explanation: 'The textbook defines software as the non-physical parts of the system: the operating system, application programs and the data. A typed document is data, so it is software; the other items are physical hardware.',
    skills: ['T2-S1'],
  },
  't2-c2': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: as long as it is switched on, a printer can produce a printed document without receiving any instruction from software.',
    answer: false,
    hint: 'Think about what the printer does when nobody sends it a print job.',
    explanation: 'Unless a printer receives an instruction to print and what to print, it stands idle. Hardware needs software to tell it what to do, and software needs hardware to perform its tasks.',
    skills: ['T2-S1'],
  },
  't2-c3': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Where must a program\'s instructions be before the CPU can execute them?',
    options: ['In secondary storage such as the hard drive', 'In the memory of the keyboard', 'In RAM', 'On a remote server on the Internet'],
    answer: 2,
    hint: 'The processor is fed instructions from the main memory, one at a time.',
    explanation: 'The CPU cannot execute instructions in secondary storage; they must first be loaded into RAM. Instructions are then fed from RAM to the processor one at a time.',
    skills: ['T2-S2'],
  },
  't2-c4': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Angelo uses a spreadsheet to find the average age of his classmates. Put the steps of the processing cycle in the correct order.',
    items: [
      'The CPU processes the instructions and calculates the average age',
      'Finally, Angelo saves the workbook from RAM to the hard drive',
      'Angelo types the ages of his classmates on the keyboard',
      'The average age is displayed on the screen',
      'The typed ages are placed in RAM',
    ],
    answer: [2, 4, 0, 3, 1],
    hint: 'Input comes first, and all data must be in RAM before it can be processed.',
    explanation: 'Data enters from an input device, is held in RAM, is processed by the CPU, and the result is sent to an output device. Because RAM is not permanent, the work is copied to secondary storage to keep it.',
    skills: ['T2-S2', 'T2-S5'],
  },
  't2-c5': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: a screen only displays what is stored in RAM.',
    answer: true,
    hint: 'The textbook links the screen and RAM in the same note as the CPU and secondary storage.',
    explanation: 'Just as the CPU cannot execute instructions straight from secondary storage, a screen only displays what is stored in RAM. Data must be in RAM before it can be processed or shown.',
    skills: ['T2-S2'],
  },
  't2-c6': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'How is the basic hardware model (input, processing, output, storage) extended to form an ICT system?',
    options: ['Extra RAM chips are added so data is stored permanently', 'Communication devices are added so computers can talk and exchange data', 'A second CPU is added so instructions run faster', 'Larger output devices are added so more information is shown'],
    answer: 1,
    hint: 'ICT stands for Information and ... Technology.',
    explanation: 'ICT stands for Information and Communication Technology. With the advent of communication (networking), computers could exchange data, so the hardware model was extended to include communication devices.',
    skills: ['T2-S3'],
  },
  't2-c7': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each term to its textbook definition.',
    pairs: [
      { left: 'Hardware', right: 'Physical components of the computer system that you can see and touch' },
      { left: 'Software', right: 'Non-physical parts: the operating system, application programs and data' },
      { left: 'Data', right: 'Raw unorganised facts that need to be processed to be useful' },
      { left: 'Information', right: 'Processed data, organised or presented in context to make it useful' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Two terms are about the parts of a computer, two are about what goes in and comes out of processing.',
    explanation: 'Hardware is physical and software is non-physical. Data is raw and unorganised; once processed and given context it becomes information.',
    skills: ['T2-S1', 'T2-S5'],
  },
  't2-c8': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each area from the textbook\'s table to one of its ADVANTAGES of using computers.',
    pairs: [
      { left: 'Professional', right: 'Time-critical transactions can take place at high speed' },
      { left: 'Personal', right: 'Online shopping, banking and mail services' },
      { left: 'Environmental', right: 'Less use of paper and less travelling if you work from home' },
      { left: 'Upgrading', right: 'You can keep abreast of rapidly changing technology' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Ask who or what benefits: a business, you as a person, the planet, or your system staying current.',
    explanation: 'Professional advantages help work (fast access to data, quick transactions), personal ones help individuals, environmental ones reduce paper and pollution, and upgrading keeps your computer up to date.',
    skills: ['T2-S4'],
  },
  't2-c9': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which of these is listed in the textbook as an ENVIRONMENTAL disadvantage of using computers?',
    options: ['Scams and online fraud', 'Unauthorised access to data is possible', 'Injuries related to poor working conditions', 'Toxic waste generated by dumping old equipment'],
    answer: 3,
    hint: 'Environmental means the effect on nature, not on people\'s money or bodies.',
    explanation: 'Toxic waste from dumped equipment, and greater energy use, are the environmental disadvantages. Scams and injuries are personal disadvantages; unauthorised access is a professional disadvantage.',
    skills: ['T2-S4'],
  },
  't2-c10': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'A teacher has a spreadsheet of every learner\'s test mark. Which of these is INFORMATION rather than data?',
    options: ['The mark 67 typed into cell B4', 'The list of learner names typed into column A', 'The test answers written on paper', 'A graph showing the class average per subject'],
    answer: 3,
    hint: 'Information is the result of processing; which item was produced by the spreadsheet itself?',
    explanation: 'Values typed into a spreadsheet are input as data. The application processes them into graphs, summaries and calculations, which are output as information.',
    skills: ['T2-S5'],
  },
  't2-c11': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Using the textbook\'s 1 (lowest) to 10 (highest) processing power scale, order these from LOWEST to HIGHEST processing power.',
    items: ['Server', 'Tablet', 'Super computer', 'Laptop'],
    answer: [1, 3, 0, 2],
    hint: 'One is rated 10 and one is rated in the same band as a smartphone.',
    explanation: 'The table rates a tablet 1-2, a laptop 3-4, a server 5-8 and a super computer 10. Processing power combines speed, number of cores and instructions processed per second.',
    skills: ['T2-S6'],
  },
  't2-c12': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which computer type is a small motherboard with a processor, storage and ports, can be as small as a credit card, and is mainly used to code in Scratch or Python?',
    options: ['Smart wear', 'A single board computer such as a Raspberry Pi', 'An embedded computer', 'A tablet'],
    answer: 1,
    hint: 'Raspberry Pi and Arduino are the textbook examples.',
    explanation: 'A single board computer (e.g. Raspberry Pi or Arduino) is a small motherboard with a processor and storage plus input and output ports. Arduino is very good for writing code to control robotic devices.',
    skills: ['T2-S6'],
  },
  't2-c13': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'What is the kernel of an operating system?',
    options: ['The smallest part of the OS, always stored in memory and loaded when the computer is turned on', 'The largest application program stored on the hard drive', 'The single chip that contains all of the processor circuitry', 'A backup copy of the OS that is kept on a remote server'],
    answer: 0,
    hint: 'It is part of the operating system and it never leaves memory while the computer is on.',
    explanation: 'Most operating systems have a kernel, the smallest part of the operating system that is always stored in memory. It is loaded when the computer is turned on.',
    skills: ['T2-S7'],
  },
  't2-c14': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each kind of operating system to an example from the textbook.',
    pairs: [
      { left: 'Desktop or laptop OS', right: 'Windows, Mac OS or Linux (e.g. Ubuntu)' },
      { left: 'OS on an Apple iPhone or iPad', right: 'iOS' },
      { left: 'OS on many other tablets and smartphones', right: 'Android (e.g. Nougat or Oreo)' },
      { left: 'Embedded OS', right: 'A compact, real-time OS inside a traffic light or ATM' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Kitkat, Lollipop, Nougat and Oreo are all versions of the same mobile OS.',
    explanation: 'Most desktops and laptops use Windows or Mac OS, some use Linux. Apple mobile devices use iOS and many other tablets and phones use Android. Embedded systems in devices like traffic lights and ATMs use compact embedded operating systems.',
    skills: ['T2-S7'],
  },
  't2-c15': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: embedded operating systems are often designed for real-time operations, where data is processed immediately without any delays.',
    answer: true,
    hint: 'Think of a car or traffic light that must react instantly.',
    explanation: 'An embedded OS is a specialised, compact OS for computers built into larger systems, and it is often designed for real-time operations where data is processed immediately.',
    skills: ['T2-S7'],
  },
  't2-c16': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Apply the textbook\'s test to each item. Type exactly application or system (lowercase) for each.',
    code: 'Test: "Will the computer run without this software?"\nYES -> application software\nNO  -> system software (the operating system)\n\n1. Microsoft Word\n2. Windows\n3. A game\n4. Android on a smartphone',
    rows: [
      { label: '1. Microsoft Word', answer: 'application' },
      { label: '2. Windows', answer: 'system' },
      { label: '3. A game', answer: 'application' },
      { label: '4. Android on a smartphone', answer: 'system' },
    ],
    hint: 'Every computer and device needs an operating system installed and running on it.',
    explanation: 'A computer still runs without Word or a game, so they are application software. Windows and Android are operating systems; without them the device cannot run, so they are system software.',
    skills: ['T2-S8', 'T2-S7'],
  },
  't2-c17': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Microsoft Word is a stand-alone application. Order the steps from switching on the computer to Word running.',
    items: [
      'The user loads Microsoft Word',
      'The operating system is loaded from secondary storage into RAM',
      'The CPU processes the Word instructions held in RAM',
      'The computer is turned on',
      'A copy of Word is placed into RAM',
    ],
    answer: [3, 1, 0, 4, 2],
    hint: 'The OS must be running before any application can be loaded.',
    explanation: 'The OS, Word and Word documents are stored permanently on secondary storage. When the computer is turned on the OS is loaded into RAM; when the user loads Word, a copy is placed into RAM and processed by the CPU.',
    skills: ['T2-S8', 'T2-S2'],
  },
  't2-c18': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each network application term to its meaning.',
    pairs: [
      { left: 'Client', right: 'The computer that uses a service, e.g. a laptop, tablet or smartphone' },
      { left: 'Server', right: 'The computer that provides a service and usually stores the data' },
      { left: 'Local', right: 'Describes the computer you are working on directly' },
      { left: 'Remote', right: 'Describes a computer elsewhere, on the local network or across the Internet' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'In the textbook, the client is the local computer and the server is the remote computer.',
    explanation: 'In a client-server network the server provides a service to the client computers. The server is a remote computer (on the local network or via the Internet) and the client is the local computer.',
    skills: ['T2-S9'],
  },
  't2-c19': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Classify each step of an ATM withdrawal. Type exactly one lowercase word for each: input, processing, output, storage or communication.',
    code: 'ATM withdrawal\n1. You enter your PIN and the amount on the keypad\n2. The ATM sends your request to the bank\'s server over the network\n3. The bank checks your PIN and that your balance is enough\n4. Cash and a printed slip come out of the ATM\n5. The bank permanently records your new balance',
    rows: [
      { label: 'Step 1', answer: 'input' },
      { label: 'Step 2', answer: 'communication' },
      { label: 'Step 3', answer: 'processing' },
      { label: 'Step 4', answer: 'output' },
      { label: 'Step 5', answer: 'storage' },
    ],
    hint: 'Sending data between machines is the extra stage that an ICT system adds.',
    explanation: 'The keypad is input, sending the request to the bank is communication, checking the PIN and balance is processing, the cash and slip are output, and permanently recording the balance is storage.',
    skills: ['T2-S2', 'T2-S3'],
  },
  't2-c20': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'How does a calendar app like Google Calendar keep Angelo\'s phone and computer synchronised?',
    options: ['It emails a copy of the calendar to every device once a week', 'It only works while the phone is plugged into the computer with a USB cable', 'It updates the data in a shared location, and both devices simply access that data', 'It deletes the calendar on whichever device is older'],
    answer: 2,
    hint: 'Both devices look at the same place for the data.',
    explanation: 'A calendar app like Google Calendar synchronises by updating the data in a shared location, which both devices access. That way both devices see the latest version.',
    skills: ['T2-S10'],
  },
  't2-c21': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: data transfer between a mobile device and a computer can be a two-way process.',
    answer: true,
    hint: 'Can a phone update a computer, and a computer update a phone?',
    explanation: 'The mobile device can update data on the computer (or another device such as a tablet) and vice versa. A synchronisation management application can detect differences and offer options for which way to overwrite.',
    skills: ['T2-S10'],
  },
  't2-c22': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: in a network application, the data is usually stored on the local client computer rather than on the remote server.',
    answer: false,
    hint: 'Which computer provides the service in a client-server network?',
    explanation: 'In a network application the storage of data is usually on the remote server, not on the local computer. The server provides a service to the clients.',
    skills: ['T2-S9'],
  },
  't2-c23': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which is a typical use of smart wear such as a smartwatch?',
    options: ['Centralised processing for every computer in a network', 'Weather forecasting by manipulating very large databases', 'Writing code to control robotic devices with Arduino', 'Showing directions and fitness statistics, and using a paired smartphone\'s camera'],
    answer: 3,
    hint: 'It is about the size of a wristwatch and has a processing power of 1.',
    explanation: 'Smart wear runs a simpler smartphone OS capable of connectivity and smart apps. It shows information such as directions and fitness statistics, and pairing with a smartphone lets it use the phone\'s apps and hardware.',
    skills: ['T2-S6'],
  },
  't2-c24': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'How do mobile operating systems differ from desktop operating systems?',
    options: ['They are always larger and need more storage than desktop operating systems', 'They are designed to use the limited resources of a mobile device more efficiently', 'They do not need a kernel because mobile devices are small', 'They can only be updated through a USB cable'],
    answer: 1,
    hint: 'Phones and tablets have less power and memory than a desktop.',
    explanation: 'Mobile operating systems such as Android and iOS are designed to use the limited resources of mobile devices more efficiently. They can be updated over USB, wireless networks, the Internet or Bluetooth.',
    skills: ['T2-S7'],
  },
  't2-c25': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Robots controlled by embedded systems are replacing some factory workers. What is the most sensible response for a worker whose job is threatened?',
    options: ['Refuse to use any computers from now on', 'Do nothing, because robots never replace human jobs', 'Learn new skills, for example to operate, program or maintain the new technology', 'Damage the robots so the factory must hire people again'],
    answer: 2,
    hint: 'New technology removes some jobs but also creates new ones.',
    explanation: 'Automation can increase unemployment in labour jobs, but it also creates jobs in designing, programming and maintaining the systems. Retraining and learning new skills is the constructive response.',
    skills: ['T2-S4', 'T2-S7'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Get the big picture of a computer system: its hardware and software, how it processes data, the types of computers and software, and how devices connect and synchronise.',
  outcomes: [
    'By the end you can define hardware and software and explain why each needs the other.',
    'By the end you can describe the general processing cycle using the CPU, RAM, input, output and secondary storage.',
    'By the end you can explain how communication turns a computer into part of an ICT system.',
    'By the end you can list advantages and disadvantages of using computers in different areas.',
    'By the end you can distinguish between data and information.',
    'By the end you can compare the main types of computer systems by use, processing power, size and portability.',
    'By the end you can explain what an operating system does and compare desktop, mobile and embedded operating systems.',
    'By the end you can distinguish stand-alone applications from network applications using client, server, local and remote.',
    'By the end you can explain data transfer and synchronisation between devices.',
  ],
  topics: [
    {
      id: 'T2-T1',
      title: 'Hardware and Software',
      sections: ['2.1'],
      skills: ['T2-S1', 'T2-S8'],
      explanation: [
        'Hardware is the collection of physical components attached to or forming part of the computer system: the items you can see and touch.',
        'Software is the collection of non-physical parts of the system: the operating system, application programs and the data.',
        'Together they make sure the computer can receive input data, process it, store it, and output information to a device or communicate it elsewhere.',
        'Neither can exist on its own: hardware needs software to tell it what to do, and software needs hardware to perform its tasks.',
        'Example: a printer is hardware. No software can create a printed document without a machine to do it, but unless the printer receives an instruction to print and what to print, it stands idle.',
        'Software can be split into system software (the operating system, which the computer needs to run) and application software (programs that carry out tasks for users, covered in section 2.6).',
      ],
      vocabulary: [
        { term: 'Hardware', definition: 'The collection of physical components attached to or forming part of the computer system; those items that you can see and touch.' },
        { term: 'Software', definition: 'The collection of non-physical parts of the system; the operating system, application programs and the data.' },
      ],
      workedExamples: [
        { code: 'Hardware: keyboard, printer, RAM, hard drive, screen\nSoftware: Windows (operating system)\n          Microsoft Word (application program)\n          essay.docx (data)', explanation: 'Sorting items from a typical home computer. Notice that a saved document counts as software because the textbook includes data in the definition.' },
      ],
      misconceptions: [
        'Software is only programs. Wrong: the textbook definition of software includes the operating system, application programs and the data.',
        'A powerful device can work by itself. Wrong: hardware needs software to tell it what to do, just as a printer stands idle until it is told what to print.',
      ],
      questions: [
        {
          id: 'T2-T1-Q1',
          type: 'tf',
          category: 'define',
          prompt: 'True or false: according to the textbook, software includes the data as well as the operating system and application programs.',
          answer: true,
          hint: 'Re-read the list after "the collection of non-physical parts of the system".',
          explanation: 'Software is the collection of non-physical parts of the system: the operating system, application programs and the data.',
          skills: ['T2-S1'],
        },
        {
          id: 'T2-T1-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'Why does the textbook say neither hardware nor software could exist on its own?',
          options: ['Software is stored on hardware, so it is really a type of hardware', 'Hardware needs software to tell it what to do, and software needs hardware to perform its tasks', 'Hardware is too expensive to sell without free software included', 'Software only becomes useful once it has been printed out'],
          answer: 1,
          hint: 'Think of the printer example: what does each part give the other?',
          explanation: 'They depend on each other: hardware does nothing without instructions from software, and software has no way to perform tasks without hardware.',
          skills: ['T2-S1'],
        },
      ],
    },
    {
      id: 'T2-T2',
      title: 'The General Processing Cycle',
      sections: ['2.1.1'],
      skills: ['T2-S2'],
      explanation: [
        'A computer is a device that performs tasks at high speed. The component that performs these tasks is the Central Processing Unit (CPU), commonly called the processor.',
        'The processor is fed instructions that are stored in Random Access Memory (RAM). Instructions are fed to the processor one at a time and each instruction is systematically processed.',
        'All data needs to be stored in RAM before it can be processed. RAM can receive data from input devices such as a keyboard, or from secondary storage such as a hard drive.',
        'The data in RAM is not stored permanently. It can be copied to secondary storage or sent to an output device such as a screen or printer.',
        'The CPU cannot execute instructions in secondary storage; they must first be loaded into RAM. Likewise, a screen only displays what is stored in RAM.',
        'So the cycle is: input, processing, output and storage, with RAM in the middle of everything. (The textbook diagram shows the hardware in boxes and the software travelling along the arrows between them.)',
      ],
      vocabulary: [
        { term: 'CPU', definition: 'Central Processing Unit, commonly called the processor; the component that performs the computer\'s tasks.' },
        { term: 'RAM', definition: 'Random Access Memory; holds the instructions and data being processed. Its data is not stored permanently.' },
        { term: 'Secondary storage', definition: 'Permanent storage such as a hard drive, from which data can be loaded into RAM and to which data in RAM can be copied.' },
        { term: 'Input device', definition: 'A device, such as a keyboard, that sends data into RAM.' },
        { term: 'Output device', definition: 'A device, such as a screen or printer, that data in RAM can be sent to.' },
      ],
      workedExamples: [
        { code: 'Keyboard (input) --> RAM --> CPU (processing)\n                     |\n                     +--> Screen / printer (output)\n                     +--> Hard drive (storage)\nHard drive --> RAM  (loading a program or file)', explanation: 'RAM is the hub: data comes in from input devices or secondary storage, the CPU processes it from RAM, and results go out to output devices or are copied to secondary storage.' },
      ],
      misconceptions: [
        'The CPU runs programs straight from the hard drive. Wrong: instructions in secondary storage must first be loaded into RAM.',
        'Anything in RAM is safe when the power goes off. Wrong: data in RAM is not stored permanently; it must be copied to secondary storage.',
        'The processor handles all instructions at once. Wrong: instructions are fed to the processor one at a time.',
      ],
      questions: [
        {
          id: 'T2-T2-Q1',
          type: 'mc',
          category: 'predict',
          prompt: 'Angelo double-clicks a game that is saved on his hard drive. What must happen before the CPU can execute the game\'s instructions?',
          options: ['Nothing, the CPU reads the instructions directly from the hard drive', 'The game must first be shown on the screen', 'The game must be copied to a USB flash drive', 'The game\'s instructions must first be loaded into RAM'],
          answer: 3,
          hint: 'Where does the processor get its instructions from?',
          explanation: 'The CPU cannot execute instructions in secondary storage. They must first be loaded into RAM, from where they are fed to the processor one at a time.',
          skills: ['T2-S2'],
        },
        {
          id: 'T2-T2-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: instructions are fed to the processor all at once so that the whole program is processed in a single step.',
          answer: false,
          hint: 'The textbook says each instruction is systematically processed.',
          explanation: 'Instructions are fed to the processor one at a time, and each instruction is systematically processed.',
          skills: ['T2-S2'],
        },
        {
          id: 'T2-T2-Q3',
          type: 'mc',
          category: 'identify',
          prompt: 'Which component is commonly called the processor?',
          options: ['RAM', 'The CPU', 'The hard drive', 'The keyboard'],
          answer: 1,
          hint: 'It is the component that performs the tasks.',
          explanation: 'The Central Processing Unit (CPU) is the component that performs the computer\'s tasks and is commonly called the processor.',
          skills: ['T2-S2'],
        },
      ],
    },
    {
      id: 'T2-T3',
      title: 'Connectivity and an ICT System',
      sections: ['2.1.2'],
      skills: ['T2-S3', 'T2-S2'],
      explanation: [
        'ICT is an abbreviation for Information and Communication Technology.',
        'With the advent of communication (networking), computers became able to talk to one another and exchange data between them.',
        'The hardware model is therefore extended to include communication devices. A computer can now output information to a device or communicate it elsewhere.',
        'The extended model has five parts: input, processing, output, storage and communication. Everyday systems such as card payments and ATMs use all five.',
      ],
      vocabulary: [
        { term: 'ICT', definition: 'Information and Communication Technology.' },
        { term: 'Communication (networking)', definition: 'Allows computers to talk to one another and exchange data between them.' },
      ],
      workedExamples: [
        { code: 'ATM withdrawal\nInput:         card and PIN entered on the keypad\nCommunication: request sent to the bank\'s computer\nProcessing:    PIN and balance are checked\nOutput:        cash and a slip are issued\nStorage:       new balance is recorded permanently', explanation: 'An input, process, output, storage and communication breakdown for Check Point question 4.2.' },
      ],
      misconceptions: [
        'Communication is just another kind of output. Wrong: the textbook extends the hardware model with communication devices so computers can exchange data with each other.',
      ],
      questions: [
        {
          id: 'T2-T3-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'What does the abbreviation ICT stand for?',
          options: ['Internet and Computer Technology', 'Input, Calculation and Transfer', 'Information and Communication Technology', 'Information and Computer Training'],
          answer: 2,
          hint: 'The C is the part that lets computers talk to one another.',
          explanation: 'ICT is an abbreviation for Information and Communication Technology.',
          skills: ['T2-S3'],
        },
        {
          id: 'T2-T3-Q2',
          type: 'trace',
          category: 'classify',
          prompt: 'You pay for a meal at a restaurant by credit card. Classify each step by typing exactly one lowercase word: input, processing, output, storage or communication.',
          code: 'Restaurant card payment\n1. The waiter keys in the bill and you enter your card PIN\n2. The card machine sends the transaction to the bank\n3. The bank checks the card and the available funds\n4. The card machine prints a receipt\n5. The bank permanently records the payment',
          rows: [
            { label: 'Step 1', answer: 'input' },
            { label: 'Step 2', answer: 'communication' },
            { label: 'Step 3', answer: 'processing' },
            { label: 'Step 4', answer: 'output' },
            { label: 'Step 5', answer: 'storage' },
          ],
          hint: 'Which step moves data between two different machines?',
          explanation: 'Keying in the bill and PIN is input, sending to the bank is communication, checking funds is processing, the receipt is output and recording the payment is storage.',
          skills: ['T2-S3', 'T2-S2'],
        },
        {
          id: 'T2-T3-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: networking allows computers to exchange data, so the general hardware model is extended to include communication devices.',
          answer: true,
          hint: 'What changed with the advent of communication?',
          explanation: 'With the advent of networking, computers could talk to one another and exchange data, so communication devices were added to the hardware model.',
          skills: ['T2-S3'],
        },
      ],
    },
    {
      id: 'T2-T4',
      title: 'Advantages and Disadvantages of Using Computers',
      sections: ['2.2'],
      skills: ['T2-S4'],
      explanation: [
        'Professional: fast access to data and time-critical transactions at high speed; but electrical failures cause much loss of productivity and unauthorised access to data is possible.',
        'Personal: online shopping, banking and mail services; but injuries related to poor working conditions, and scams and online fraud.',
        'Environmental: less use of paper and less travelling (hence less pollution) if you can work from home; but toxic waste from dumping old equipment and greater energy use, hence more electrical requirements.',
        'Upgrading: your computer is up to date, you can keep abreast of rapidly changing technology and the Internet makes updating software efficient; but hardware quickly becomes outdated, software constantly needs upgrading, and as software develops your hardware becomes obsolete.',
        'Smartphones show both sides: they are very portable and give connectivity, mail, GPS and apps, but have low processing power (1-2) and a small screen, and users are exposed to scams and online fraud.',
        'Robots run by embedded systems can replace humans doing labour, which can cause unemployment, but they also create new jobs (for example designing, programming and maintaining them). Workers whose jobs are threatened should learn new skills.',
      ],
      vocabulary: [
        { term: 'Obsolete', definition: 'Out of date and no longer useful; as software develops, older hardware becomes obsolete.' },
        { term: 'Time-critical transaction', definition: 'A transaction that must happen quickly, which computers can do at high speed.' },
      ],
      workedExamples: [
        { code: 'Area          Advantage              Disadvantage\nProfessional  fast access to data    electrical failures\nPersonal      online banking         scams and online fraud\nEnvironmental less use of paper      toxic waste from old equipment\nUpgrading     keep up with tech      hardware becomes obsolete', explanation: 'A short summary of the textbook table, one advantage and one disadvantage per area.' },
      ],
      misconceptions: [
        'Computers are always better for the environment. Wrong: they save paper and travel, but create toxic waste and need more electricity.',
        'Upgrading software is free of downsides. Wrong: as software develops, hardware quickly becomes outdated and obsolete.',
      ],
      questions: [
        {
          id: 'T2-T4-Q1',
          type: 'mc',
          category: 'classify',
          prompt: 'In the textbook table, "unauthorised access to data is possible" is a disadvantage in which area?',
          options: ['Personal', 'Environmental', 'Professional', 'Upgrading'],
          answer: 2,
          hint: 'It appears alongside electrical failures causing loss of productivity.',
          explanation: 'Unauthorised access to data and electrical failures are the professional disadvantages in the table.',
          skills: ['T2-S4'],
        },
        {
          id: 'T2-T4-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: working from home is linked to an environmental advantage because less travelling means less pollution.',
          answer: true,
          hint: 'Look at the environmental row of the table.',
          explanation: 'The environmental advantages are less use of paper and less travelling, hence less pollution, if you can work from home.',
          skills: ['T2-S4'],
        },
        {
          id: 'T2-T4-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'Which option correctly gives one advantage AND one disadvantage of smartphones?',
          options: ['Advantage: very portable with mail, GPS and apps. Disadvantage: low processing power and a small screen', 'Advantage: the highest processing power of any device. Disadvantage: not portable at all', 'Advantage: no Internet connection is needed. Disadvantage: cannot install applications', 'Advantage: takes up an entire desktop. Disadvantage: cannot make phone calls'],
          answer: 0,
          hint: 'Check the smartphone row of the computer types table: processing power 1-2, very portable.',
          explanation: 'Smartphones are very portable and offer connectivity, mail access, GPS, telephony and apps, but they are rated only 1-2 for processing power and have a small screen.',
          skills: ['T2-S4', 'T2-S6'],
        },
        {
          id: 'T2-T4-Q4',
          type: 'mc',
          category: 'explain',
          prompt: 'How can robots that use embedded operating systems affect employment?',
          options: ['They have no effect, because robots cannot do labour', 'They only create jobs and never cause unemployment', 'They only cause unemployment and never create jobs', 'They can replace labour jobs, but also create new jobs such as programming and maintaining them'],
          answer: 3,
          hint: 'Consider both the people who lose jobs and the people needed to build and look after the robots.',
          explanation: 'Robots can increase unemployment in labour jobs, but they also create jobs in design, programming and maintenance. Learning new skills helps workers adapt.',
          skills: ['T2-S4', 'T2-S7'],
        },
      ],
    },
    {
      id: 'T2-T5',
      title: 'Data and Information',
      sections: ['2.3'],
      skills: ['T2-S5'],
      explanation: [
        'Data is raw unorganised facts that need to be processed to make it useful and meaningful.',
        'Information is processed data: organised, structured or presented in a given context to make it useful.',
        'Example: a spreadsheet containing the names and ages of people is data. The application can process it into graphs, summaries and calculations, which are information.',
        'The numbers or values in the spreadsheet are input as data, processed, and the result is output as information.',
      ],
      vocabulary: [
        { term: 'Data', definition: 'Raw unorganised facts that need to be processed to make it useful and meaningful.' },
        { term: 'Information', definition: 'Processed data; organised, structured or presented in a given context to make it useful.' },
      ],
      workedExamples: [
        { code: 'DATA (input):        Thabo 16, Lerato 15, Angelo 16, Zanele 17\nPROCESSING:          calculate the average age\nINFORMATION (output): Average age of the group = 16', explanation: 'The ages on their own are raw facts. Processing them gives a meaningful result: (16 + 15 + 16 + 17) / 4 = 64 / 4 = 16.' },
      ],
      misconceptions: [
        'Data and information mean the same thing. Wrong: data is raw and unorganised; information is data that has been processed and given context.',
        'Numbers are always information. Wrong: numbers typed into a spreadsheet are data until they are processed into something meaningful.',
      ],
      questions: [
        {
          id: 'T2-T5-Q1',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: data is processed information that has been organised and presented in context.',
          answer: false,
          hint: 'Which one comes first, data or information?',
          explanation: 'It is the other way round: information is processed data. Data is raw unorganised facts that still need to be processed.',
          skills: ['T2-S5'],
        },
        {
          id: 'T2-T5-Q2',
          type: 'mc',
          category: 'classify',
          prompt: 'In the textbook\'s spreadsheet example, which of these is the DATA?',
          options: ['The names and ages of people typed into the spreadsheet', 'A graph comparing the ages', 'A summary showing the average age', 'A calculation of how many people are over 18'],
          answer: 0,
          hint: 'Data is what goes INTO the processing.',
          explanation: 'The names and ages are the raw input data. Graphs, summaries and calculations are produced by processing, so they are information.',
          skills: ['T2-S5'],
        },
      ],
    },
    {
      id: 'T2-T6',
      title: 'Computer System Types',
      sections: ['2.4'],
      skills: ['T2-S6'],
      explanation: [
        'Processing power is a combination of speed, number of cores (processors) and number of instructions processed per second. The textbook rates it on a scale of 1 (lowest) to 10 (highest).',
        'Desktop (power 3-4): also called a personal computer, the most common type; its processor circuitry is in one chip called the microprocessor or CPU. Used for applications needing lots of memory, speed or graphics. Large and not portable at all.',
        'Laptop or notebook (3-4): similar to a desktop but much smaller, with all essential peripherals integrated in the casing; very portable. Price and performance are now comparable to desktops, but high graphics use is limited by screen size.',
        'Tablet (1-2): a lightweight, low-powered mobile computer with a touch screen; you can write on the screen and convert it to digital text. Smartphone (1-2): a mobile phone with advanced computing ability and connectivity for mail, GPS, telephony and apps. Both are very portable.',
        'Smart wear (1): wearable devices such as watches with a simpler smartphone OS, showing information such as directions and fitness statistics; pairing with a smartphone lets it use the phone\'s apps and hardware, such as the camera.',
        'Server (5-8): a powerful computer with large storage that other computers in a network connect to, to use its resources. Types include file, print and web servers, used for centralised processing and management (e.g. application, web, antivirus, mail and data). Not portable.',
        'Embedded computer (N/A): designed to perform one or more dedicated functions as part of a device, e.g. in cars and household appliances. Single board computer (1): e.g. Raspberry Pi and Arduino, credit-card sized, used to code in Scratch or Python and build smart or robotic devices. Super computer (10): the largest type, used for computational science, quantum mechanics and weather forecasting; most use Linux; can fill multiple floors.',
      ],
      vocabulary: [
        { term: 'Processing power', definition: 'A combination of speed, number of cores (processors) and number of instructions processed per second.' },
        { term: 'Server', definition: 'A powerful computer with large storage capacity to which other computers in a network connect to use its resources and services.' },
        { term: 'Embedded computer', definition: 'A computer system designed to perform one or more dedicated functions, embedded as part of a device.' },
        { term: 'Single board computer', definition: 'A small motherboard with a processor, storage and ports for input and output devices, e.g. Raspberry Pi and Arduino.' },
        { term: 'Smartphone', definition: 'A mobile phone that offers more advanced computing ability and connectivity than a conventional phone.' },
      ],
      workedExamples: [
        { code: 'Type              Power  Portability\nSmart wear        1      very portable\nSingle board      1      very portable\nTablet            1-2    very portable\nSmartphone        1-2    very portable\nDesktop           3-4    not portable\nLaptop            3-4    very portable\nServer            5-8    not portable\nSuper computer    10     not at all\nEmbedded          N/A    N/A', explanation: 'A summary of the processing power and portability columns of the textbook table.' },
        { code: 'Desktop or laptop for school?\nLaptop:  very portable, peripherals built in, similar price and performance\nDesktop: better for heavy graphics work, but not portable', explanation: 'Two reasons for each choice, as asked in Check Point question 5.' },
      ],
      misconceptions: [
        'A laptop is always much weaker than a desktop. Wrong: with microprocessors made for mobile computers, price and performance are now quite comparable (both are rated 3-4).',
        'Embedded computers are just small desktops. Wrong: they are not used as typical computers; they provide limited, specific processing inside appliances and equipment.',
      ],
      questions: [
        {
          id: 'T2-T6-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'Which computer type is the largest, is used for weather forecasting and quantum mechanics, and can take up multiple floors of an office building?',
          options: ['A server', 'A desktop computer', 'An embedded computer', 'A super computer'],
          answer: 3,
          hint: 'It scores 10 on the processing power scale.',
          explanation: 'The super computer is the largest type of computer, used in computational science, quantum mechanics and weather forecasting. Most use Linux as an operating system.',
          skills: ['T2-S6'],
        },
        {
          id: 'T2-T6-Q2',
          type: 'tf',
          category: 'define',
          prompt: 'True or false: processing power, as used in the textbook\'s table, combines speed, number of cores and number of instructions processed per second.',
          answer: true,
          hint: 'Read the note above the computer types table.',
          explanation: 'The textbook defines processing power as a combination of speed, number of cores (processors) and number of instructions processed per second.',
          skills: ['T2-S6'],
        },
        {
          id: 'T2-T6-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'Angelo wants one computer that he can carry to school every day and still use for most desktop tasks. Which choice and reason fit the textbook best?',
          options: ['A desktop, because it is the most portable type of computer', 'A server, because it has the largest storage capacity', 'A laptop, because it is very portable, has its peripherals built in and performs similarly to a desktop', 'Smart wear, because it has the highest processing power'],
          answer: 2,
          hint: 'He needs portability without giving up much performance.',
          explanation: 'A laptop is very portable with all essential peripherals integrated in the casing, and its price and performance are now quite comparable to a desktop.',
          skills: ['T2-S6'],
        },
        {
          id: 'T2-T6-Q4',
          type: 'mc',
          category: 'classify',
          prompt: 'Which list gives the types of server mentioned in the textbook?',
          options: ['File servers, print servers and web servers', 'Desktop servers, laptop servers and tablet servers', 'Input servers, output servers and storage servers', 'Kernel servers, RAM servers and CPU servers'],
          answer: 0,
          hint: 'Each type is named after the resource or service it shares with the network.',
          explanation: 'Types of server include file servers, print servers and web servers. They provide services to the machines in the network.',
          skills: ['T2-S6'],
        },
      ],
    },
    {
      id: 'T2-T7',
      title: 'Operating Systems',
      sections: ['2.5', '2.5.1', '2.5.2', '2.5.3'],
      skills: ['T2-S7'],
      explanation: [
        'Every computer needs an operating system installed and running on it. An operating system is a collection of many programs that manages the hardware and allows the user to run software applications like word processors or Internet browsers.',
        'Most operating systems have a kernel, the smallest part of the operating system that is always stored in memory. The kernel is loaded when the computer is turned on. The OS needed varies with the type of device.',
        'Desktop OS: supports hardware functions such as input, processing and output, and acts as the interface between application programs and the computer hardware. Most desktops and laptops use versions of Mac OS or Windows, some use Linux (e.g. Ubuntu).',
        'Mobile OS: designed for mobile phones, smartphones, tablets and other handheld devices, using their limited resources more efficiently. Many use Android (versions such as Kitkat, Lollipop, Nougat and Oreo); Apple iPhones and iPads use iOS.',
        'Embedded OS: an embedded system is part of another machine, such as robots, cars, washing machines, traffic lights, televisions and ATMs. An embedded OS is a specialised OS for computers built into larger systems, typically more compact than a desktop OS and often designed for real-time operations where data is processed immediately.',
      ],
      vocabulary: [
        { term: 'Operating system', definition: 'A collection of many programs that manages the hardware and allows the user to run software applications.' },
        { term: 'Kernel', definition: 'The smallest part of the operating system that is always stored in memory; it is loaded when the computer is turned on.' },
        { term: 'Mobile operating system', definition: 'An OS designed for mobile devices that uses their limited resources more efficiently.' },
        { term: 'Embedded operating system', definition: 'A specialised, compact OS for computers built into larger systems, often designed for real-time operations.' },
        { term: 'Real-time operation', definition: 'Processing where data is processed immediately without any delays.' },
      ],
      workedExamples: [
        { code: 'Device        Operating system\nDesktop       Windows, Mac OS or Linux (Ubuntu)\nSmartphone    Android or iOS\nSmart wear    a simpler smartphone OS\nEmbedded      a compact real-time embedded OS (e.g. Linux based)', explanation: 'A completed version of the Check Point question 7 table.' },
      ],
      misconceptions: [
        'Only desktop computers need an operating system. Wrong: every computer and device needs an OS, though the type varies by device.',
        'An embedded OS must be bigger because it controls a whole machine. Wrong: it is typically more compact than a desktop OS.',
      ],
      questions: [
        {
          id: 'T2-T7-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'Which statement best defines an operating system?',
          options: ['A single program used to type and print documents', 'A collection of many programs that manages the hardware and lets the user run software applications', 'The physical chip that processes instructions one at a time', 'A network application that stores data on a remote server'],
          answer: 1,
          hint: 'It manages the hardware AND makes it possible to run other programs.',
          explanation: 'An operating system is a collection of many programs that manages the hardware and allows the user to run applications such as word processors or Internet browsers.',
          skills: ['T2-S7'],
        },
        {
          id: 'T2-T7-Q2',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: an embedded operating system is typically larger than a desktop operating system because it controls a whole machine.',
          answer: false,
          hint: 'Think about how little space there is inside a washing machine controller.',
          explanation: 'An embedded OS is a specialised OS for computers built into larger systems and is typically more compact than a desktop OS.',
          skills: ['T2-S7'],
        },
        {
          id: 'T2-T7-Q3',
          type: 'mc',
          category: 'identify',
          prompt: 'Which of these is an example of an embedded system named in the textbook?',
          options: ['A traffic light', 'A desktop computer running Ubuntu', 'A laptop running Windows', 'A web server in a data centre'],
          answer: 0,
          hint: 'An embedded system is part of another machine.',
          explanation: 'Embedded systems include those for robots, cars, washing machines, traffic lights, televisions and ATMs. Desktops, laptops and servers are general computers.',
          skills: ['T2-S7'],
        },
      ],
    },
    {
      id: 'T2-T8',
      title: 'Application Software: Stand-alone and Network',
      sections: ['2.6', '2.6.1', '2.6.2'],
      skills: ['T2-S8', 'T2-S9'],
      explanation: [
        'Application software carries out tasks for computer users, such as creating documents, playing games or updating a database.',
        'Test: ask "Will the computer run without this software?" If the answer is YES, it is application software. If NO, it is system software such as the operating system.',
        'A stand-alone or desktop application runs on a computer without any need to interact with any other software, using the computer\'s hardware and operating system to perform its functions.',
        'Example: the OS, Microsoft Word and Word documents are permanently stored on secondary storage. When the computer is turned on, the OS is loaded into RAM. When the user loads Word, a copy of Word is placed into RAM and processed by the CPU.',
        'A network application is designed to run on multiple computers connected via a network, usually the Internet. It uses a client-server network where the server provides a service to the client computers.',
        'The server is a remote computer, on the local network or linked via the Internet. The client is the local computer: a desktop, laptop, smartphone or tablet. Data is usually stored on the remote server, not on the local computer.',
      ],
      vocabulary: [
        { term: 'Application software', definition: 'Software that carries out tasks for computer users, such as creating documents, playing games or updating a database.' },
        { term: 'Stand-alone (desktop) application', definition: 'An application that runs on a computer without any need to interact with any other software.' },
        { term: 'Network application', definition: 'An application designed to run on multiple computers connected via a network, usually the Internet.' },
        { term: 'Client', definition: 'The local computer that uses the service, e.g. a desktop, laptop, smartphone or tablet.' },
        { term: 'Server', definition: 'The remote computer that provides a service to the clients and usually stores the data.' },
      ],
      workedExamples: [
        { code: 'Secondary storage: OS, Word, Word documents  (permanent)\nPower on   -> OS copied into RAM\nLoad Word  -> copy of Word placed into RAM\nCPU        -> processes Word\'s instructions from RAM', explanation: 'How the stand-alone application Microsoft Word is loaded and run.' },
        { code: 'Client (local): Angelo\'s smartphone\n      |  request over the Internet\n      v\nServer (remote): stores the data and provides the service', explanation: 'A client-server network application: the data lives on the remote server, not on the phone.' },
      ],
      misconceptions: [
        'Application software is anything installed on the computer. Wrong: the operating system is installed too, but the computer cannot run without it, so it is not application software.',
        'Remote always means far away on the Internet. Wrong: the remote server can also be on the local network.',
      ],
      questions: [
        {
          id: 'T2-T8-Q1',
          type: 'mc',
          category: 'apply',
          prompt: 'Angelo uninstalls a program and his computer still starts up and runs normally. Using the textbook\'s test, what type of software was it?',
          options: ['The kernel', 'The operating system', 'Application software', 'System software'],
          answer: 2,
          hint: 'The test is "Will the computer run without this software?"',
          explanation: 'If the computer runs without the software, the answer to the test is YES, so it is application software.',
          skills: ['T2-S8'],
        },
        {
          id: 'T2-T8-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: when Microsoft Word is loaded, the CPU processes Word directly from secondary storage without placing a copy in RAM.',
          answer: false,
          hint: 'Recall where the CPU gets its instructions from.',
          explanation: 'When the user loads Word, a copy of Word is placed into RAM, which is then processed by the CPU. The CPU cannot execute instructions in secondary storage.',
          skills: ['T2-S8', 'T2-S2'],
        },
        {
          id: 'T2-T8-Q3',
          type: 'mc',
          category: 'distinguish',
          prompt: 'Which of these is a NETWORK application rather than a stand-alone application?',
          options: ['A word processor that saves documents on the computer\'s own hard drive', 'A calculator program that runs on its own on a laptop', 'A drawing program used offline on a desktop', 'An online banking app where account data is stored on the bank\'s server'],
          answer: 3,
          hint: 'A network application runs on multiple connected computers and keeps the data on a server.',
          explanation: 'Online banking is a client-server network application: the phone or computer is the client and the bank\'s server stores the data. The others run without interacting with other software.',
          skills: ['T2-S9', 'T2-S8'],
        },
        {
          id: 'T2-T8-Q4',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: in a network application, the client could be a desktop computer, a laptop, a smartphone or a tablet.',
          answer: true,
          hint: 'The client is simply the local computer you are using.',
          explanation: 'The client is the local computer and could be a desktop, laptop or a portable device like a smartphone or tablet.',
          skills: ['T2-S9'],
        },
      ],
    },
    {
      id: 'T2-T9',
      title: 'Data Transfer and Synchronising between Devices',
      sections: ['2.7'],
      skills: ['T2-S10'],
      explanation: [
        'Synchronisation is a process where the data on your desktop and mobile device is consistent: both devices see the latest version of the data.',
        'For example, your contacts, calendars and email should reflect the most recent data regardless of which device was used to make the changes.',
        'Mobile devices need a way to load apps, do updates and update their OS or settings. Mobile operating systems provide communication software for this, via a USB port (cable, docking unit or cradle), or wirelessly using the Internet, a wireless network or the slower Bluetooth.',
        'You can use your computer to back up data from your mobile device, transfer data between the two and synchronise contacts, email and calendars. A calendar app like Google Calendar synchronises by updating data in a shared location that both devices access.',
        'Data transfer can be two-way: the mobile device can update data on the computer (or another device such as a tablet) and vice versa. A synchronisation management application can tell when data differs and offer options for which way to overwrite, or not.',
      ],
      vocabulary: [
        { term: 'Synchronisation', definition: 'A process where the data on your desktop and mobile device is consistent, so both devices see the latest version of the data.' },
        { term: 'Bluetooth', definition: 'A wireless connection for transferring data between devices, slower than the other options in the textbook.' },
        { term: 'Docking unit or cradle', definition: 'A stand that connects a mobile device to a computer through a USB port.' },
      ],
      workedExamples: [
        { code: 'Phone: add contact "Gogo Nandi" at 10:00\nSync app compares phone and laptop -> data differs\nOption chosen: phone overwrites laptop\nResult: both devices show the new contact', explanation: 'A two-way synchronisation in action: the sync management application finds the difference and lets you choose which way to overwrite.' },
      ],
      misconceptions: [
        'Synchronising only copies from the computer to the phone. Wrong: data transfer can be two-way.',
        'Synchronising needs a cable. Wrong: it can also happen wirelessly via the Internet, a wireless network or Bluetooth.',
      ],
      questions: [
        {
          id: 'T2-T9-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'What is meant by synchronising devices?',
          options: ['Making both devices run the same operating system', 'Keeping the data on the devices consistent so both see the latest version', 'Copying the kernel from one device to another', 'Making both devices the same physical size'],
          answer: 1,
          hint: 'It is about the data, not the hardware or OS.',
          explanation: 'Synchronisation is a process where the data on your devices is consistent, so both devices see the latest version of the data.',
          skills: ['T2-S10'],
        },
        {
          id: 'T2-T9-Q2',
          type: 'mc',
          category: 'identify',
          prompt: 'Which data does the textbook say you would normally want to synchronise between your computer and mobile device?',
          options: ['Contacts, calendars and email', 'The operating system kernel', 'The current contents of RAM', 'The processor speed settings'],
          answer: 0,
          hint: 'Think of the personal data you change on your phone and want to see on your computer too.',
          explanation: 'Contacts, calendars and email should reflect the most recent data no matter which device was used to make the change.',
          skills: ['T2-S10'],
        },
        {
          id: 'T2-T9-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: a synchronisation management application can determine whether the data on each device is different and offer options for which way to overwrite.',
          answer: true,
          hint: 'Read the final paragraph of section 2.7.',
          explanation: 'The sync management application detects differences between the devices and can give options for which way to overwrite, or not to overwrite at all.',
          skills: ['T2-S10'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't2-bank-blackout',
    unitId: UNIT.id,
    title: 'Bank Blackout',
    icon: 'vault',
    summary: 'A national bank\'s ICT system is failing on payday.',
    briefing: 'It is month-end payday and ATMs across Gauteng are swallowing cards. The bank\'s client-server network is out of sync and the support team has called you in. Explain how the input, processing, output, storage and communication chain should work before customers lose their money.',
    tickerMessages: [
      'BREAKING: ATMs in Johannesburg refuse PINs on payday',
      'Card machines in Durban restaurants fail to reach the bank',
      'Customers report balances that differ between app and branch',
      'Bank servers lose sync as queues stretch around the block',
      'Engineers warn: one more failure and records could be lost',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T2-S2', 'T2-S3', 'T2-S4', 'T2-S9', 'T2-S10'],
    victoryMessage: 'The ICT chain is restored. Every ATM and card machine is talking to the bank again and every balance is in sync.',
    failMessage: 'The servers stay out of sync and the bank shuts its doors. Revise the processing cycle and client-server basics and try again.',
  },
  {
    id: 't2-smart-city-crash',
    unitId: UNIT.id,
    title: 'Smart City Crash',
    icon: 'cpu',
    summary: 'Embedded systems across Cape Town are going haywire.',
    briefing: 'Traffic lights, ATMs and smart meters in Cape Town are rebooting at random. The city needs someone who knows the difference between hardware and software, computer types and operating systems to work out which devices are affected. Get it wrong and the whole city grinds to a halt.',
    tickerMessages: [
      'Traffic lights on the N2 flash red in every direction',
      'Smartwatches lose their paired phones across the CBD',
      'City servers overloaded as embedded devices reboot',
      'Engineers argue: is it a hardware fault or the operating system?',
      'Mayor demands answers before the evening rush hour',
      'Final warning: real-time systems will shut down in minutes',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T2-S1', 'T2-S5', 'T2-S6', 'T2-S7', 'T2-S8'],
    victoryMessage: 'Every embedded system is back online and the city is moving again. You know your computers inside out.',
    failMessage: 'The city stays gridlocked. Brush up on computer types and operating systems, then try again.',
  },
];
