// Theory Learning Unit 3: Hardware (Exploring IT: Theory Grade 10, 2nd ed)
import { Cpu } from 'lucide-react';

export const UNIT = { id: 'T3', number: 3, name: 'Hardware', worldId: 'hardware' };

export const SKILLS = {
  'T3-S1': { unit: 'T3', name: 'Hardware and the motherboard', description: 'Name the hardware categories, apply the IPO principle and describe the motherboard as the PCB that links the CPU, RAM and connectors.', sections: ['3', '3.1'] },
  'T3-S2': { unit: 'T3', name: 'The CPU and its parts', description: 'Explain what the CPU does, von Neumann architecture and the roles of the ALU, Control Unit and registers.', sections: ['3.1.1', '3.1.1.1', '3.1.1.2', '3.1.1.3'] },
  'T3-S3': { unit: 'T3', name: 'Primary memory', description: 'Describe BIOS, RAM, ROM, EEPROM and firmware and distinguish volatile from non-volatile storage.', sections: ['3.1.2', '3.1.2.1', '3.1.2.2', '3.1.2.3'] },
  'T3-S4': { unit: 'T3', name: 'Components vs peripherals', description: 'Classify hardware as a component on the motherboard or a peripheral connected to it.', sections: ['3.1.3'] },
  'T3-S5': { unit: 'T3', name: 'Hard drives', description: 'Define secondary storage and compare mechanical HDDs, SSDs and hybrid drives.', sections: ['3.2', '3.2.1', '3.2.1.1', '3.2.1.2'] },
  'T3-S6': { unit: 'T3', name: 'Portable storage media', description: 'Describe removable media: flash drives, optical drives (CD, DVD, Blu-ray) and SD cards.', sections: ['3.2', '3.2.2', '3.2.3', '3.2.4'] },
  'T3-S7': { unit: 'T3', name: 'Keyboard, mouse and scanners', description: 'Describe common input devices: keyboards, pointing devices and scanners with OCR and dpi.', sections: ['3.3', '3.3.1', '3.3.2', '3.3.3'] },
  'T3-S8': { unit: 'T3', name: 'Codes, cards and biometrics', description: 'Explain barcode scanners, QR codes, magnetic stripe readers and biometric devices.', sections: ['3.3.3.1', '3.3.3.2', '3.3.3.3', '3.3.3.4'] },
  'T3-S9': { unit: 'T3', name: 'Microphones and sensors', description: 'Explain how microphones and sensors turn real-world properties into data for the computer.', sections: ['3.3.4', '3.3.5'] },
  'T3-S10': { unit: 'T3', name: 'Monitors and printers', description: 'Describe output devices: monitor resolution and size, touch screens, laser, inkjet and 3D printers.', sections: ['3.4', '3.4.1', '3.4.2', '3.4.2.1', '3.4.2.2'] },
  'T3-S11': { unit: 'T3', name: 'Speakers and headphones', description: 'Describe speakers, headphones and headsets as sound output devices.', sections: ['3.4.3', '3.4.4'] },
  'T3-S12': { unit: 'T3', name: 'Ports', description: 'Explain why universal USB and HDMI ports are used and what each one connects.', sections: ['3.5', '3.5.1', '3.5.2'] },
};

export const SKILL_HINTS = {
  'T3-S1': 'Hardware categories are Input, Storage, Processing, Output and Communication (IPO principle); the motherboard is the large PCB linking the CPU, RAM and connectors to peripherals',
  'T3-S2': 'CPU is the largest chip on the motherboard (not the case); von Neumann: programs load from secondary storage into RAM because the CPU connects directly to RAM; ALU does arithmetic (only adds) and logic (>, <, =), CU co-ordinates and controls instructions, registers hold an instruction, address or data',
  'T3-S3': 'BIOS is non-volatile firmware on ROM that initialises hardware at start-up; RAM (DRAM) is volatile primary memory that needs refreshing; ROM is non-volatile, EEPROM can be changed by software; firmware is semi-permanent software on a hardware device',
  'T3-S4': 'Components sit directly on the motherboard (CPU, RAM); peripherals (input, output and secondary storage devices) connect to it but are not placed on it',
  'T3-S5': 'Secondary storage is permanent and non-volatile; HDD has a read/write head and stores data magnetically; SSD uses microchips, no moving parts, faster and shock resistant; HDD is cheaper per GB; hybrid drive joins HDD with SSD flash memory',
  'T3-S6': 'Flash drives are solid state, use USB and are good for transferring and backing up; optical drives (CD 700MB, single-sided DVD about 4.5GB, Blu-ray) etch data with laser light and are hard to change; SD cards are small flash cards in cameras and phones',
  'T3-S7': 'Input devices get data into RAM; keyboards have 80 to 110 keys and a QWERTY layout; optical mice use an LED, wireless mice need a receiver; scanners make .jpg/.bmp files, OCR converts text to Unicode, resolution in dpi such as 600x600',
  'T3-S8': 'Barcode scanners at POS shine a red LED on thin and wide lines; QR codes are 2D squares read by a smartphone camera and hold more data; magnetic stripe readers read credit and ATM cards; biometrics compare stored fingerprints, iris scans or voiceprints with input',
  'T3-S9': 'Microphones use a vibrating diaphragm to turn sound into an electrical signal; sensors are input devices converting temperature, speed, light etc. into electrical signals; accelerometer detects phone tilt and orientation; autopilot compares sensor data with pre-set values in real time',
  'T3-S10': 'Output devices only receive information from the computer; LCD monitors: resolution is pixels across by down (1024x768), size measured diagonally without casing; touch screens are input and output; laser and inkjet are non-impact; 3D printing designs a .STL file then slices it into layers',
  'T3-S11': 'Speakers receive digital audio from the sound card, have an amplifier, come in pairs for stereo; headphones and speakers are microphones in reverse using a diaphragm; a headset is a microphone plus headphones on one headband',
  'T3-S12': 'Universal USB and HDMI ports reduce the number of ports needed; USB connects cameras, mice, keyboards, printers, flash drives, supplies power and replaced parallel and serial ports; HDMI carries digital video and audio and replaced VGA and sound jacks',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Hardware Hangar',
  subtitle: 'Unit 3 \u00b7 Hardware',
  color: 'amber',
  glow: 'ja-glow-amber',
  bg: 'ja-w-hardware',
  icon: Cpu,
  blurb: 'Crack open the case and meet the CPU, memory, drives, devices and ports that make a computer tick. Every part has a job, and you will learn them all.',
};

export const LEVELS = [
  { id: 't3-l1', name: 'Motherboard Bay', subtitle: 'Motherboard, CPU, primary memory, components vs peripherals', challengeIds: ['t3-c1', 't3-c2', 't3-c3', 't3-c4', 't3-c5', 't3-c6', 't3-c7'] },
  { id: 't3-l2', name: 'Storage Vault', subtitle: 'HDD, SSD, hybrid, flash, optical and SD storage', challengeIds: ['t3-c8', 't3-c9', 't3-c10', 't3-c11', 't3-c12', 't3-c13'] },
  { id: 't3-l3', name: 'Device Deck', subtitle: 'Input devices, sensors, monitors and printers', challengeIds: ['t3-c14', 't3-c15', 't3-c16', 't3-c17', 't3-c18', 't3-c19', 't3-c20'] },
  { id: 't3-l4', name: 'Boss: Hangar Overhaul', subtitle: 'Sound output, ports and a mixed review of the whole unit', challengeIds: ['t3-c21', 't3-c22', 't3-c23', 't3-c24', 't3-c25', 't3-c26'] },
];

export const CHALLENGES = {
  't3-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Many people point at the computer case and call it "the CPU". What is the CPU actually?',
    options: [
      'The system unit (case) that holds all the parts of the computer',
      'The largest chip on the motherboard, which interprets and executes the instructions stored in RAM',
      'The large printed circuit board that links the RAM and the connectors',
      'The non-volatile chip that starts up the hardware when the computer is switched on',
    ],
    answer: 1,
    hint: 'Think of a single square chip with pins that fits into a socket.',
    explanation: 'The CPU is the largest chip on the motherboard and continually interprets and executes the instructions stored in RAM. The case is the system unit, the PCB is the motherboard and the start-up firmware is the BIOS.',
    skills: ['T3-S1', 'T3-S2'],
  },
  't3-c2': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each part to its job.',
    pairs: [
      { left: 'Motherboard', right: 'Large printed circuit board that links the CPU, RAM and connectors' },
      { left: 'ALU', right: 'Performs arithmetic and logical (true or false) calculations' },
      { left: 'Control Unit', right: 'Co-ordinates the instructions and controls how they are processed' },
      { left: 'Registers', right: 'Small holding places inside the CPU for an instruction, address or data' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Three of these are the three parts of the CPU; one is the board the CPU plugs into.',
    explanation: 'The CPU consists of the ALU, the Control Unit and Registers. The motherboard is the PCB on which the CPU, RAM and connectors are linked.',
    skills: ['T3-S1', 'T3-S2'],
  },
  't3-c3': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'In von Neumann architecture, the CPU can run a program directly from the hard drive without first loading it into RAM.',
    answer: false,
    hint: 'Which memory is the CPU directly connected to?',
    explanation: 'Programs and data are stored permanently in secondary storage, but a program must first be loaded into RAM to run, because the CPU is directly connected to RAM.',
    skills: ['T3-S2', 'T3-S3'],
  },
  't3-c4': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'What is the purpose of the BIOS?',
    options: [
      'To store the user\'s programs and data permanently',
      'To hold the instruction currently being processed by the CPU',
      'To perform arithmetic on integer binary numbers',
      'To initialise the hardware at start-up so the operating system can take over',
    ],
    answer: 3,
    hint: 'BIOS stands for Basic Input Output System, and it does its job the moment you press the power button.',
    explanation: 'BIOS is non-volatile firmware on a ROM chip that initialises the hardware when the computer starts up, so that the operating system can take over and use the hardware afterwards.',
    skills: ['T3-S3'],
  },
  't3-c5': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each memory term to its description.',
    pairs: [
      { left: 'RAM', right: 'Volatile primary memory whose contents are lost when switched off' },
      { left: 'ROM', right: 'Non-volatile chip, e.g. firmware programmed once in a household appliance' },
      { left: 'EEPROM', right: 'ROM chip that can be changed using a software program' },
      { left: 'Firmware', right: 'Software or instructions programmed on a hardware device' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Look for the words volatile, once, changed and software.',
    explanation: 'RAM is volatile; ROM is non-volatile and often programmed once at manufacture; an EEPROM (Electronically Erasable Programmable ROM) can be changed by software; firmware is the program stored on the hardware device.',
    skills: ['T3-S3'],
  },
  't3-c6': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which of these is a component rather than a peripheral?',
    options: ['A flash drive', 'A printer', 'RAM', 'A keyboard'],
    answer: 2,
    hint: 'Components are placed directly on the motherboard.',
    explanation: 'Anything placed directly on the motherboard, like RAM or the CPU, is a component. Input, output and secondary storage devices are peripherals: connected to the motherboard but not placed on it.',
    skills: ['T3-S4'],
  },
  't3-c7': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'The ALU can really only add. How does it work out 4 x 3?',
    options: [
      'By adding 4 three times: 4 + 4 + 4 = 12',
      'By sending the sum to the Control Unit to multiply',
      'By subtracting 3 from 4 over and over',
      'By looking up the answer stored in ROM',
    ],
    answer: 0,
    hint: 'Multiplication is a shortcut for another operation.',
    explanation: 'Multiplication is repeated addition, subtraction is addition of a negative number, division is repeated subtraction and exponentiation is repeated multiplication, so it all boils down to addition.',
    skills: ['T3-S2'],
  },
  't3-c8': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why is it a bad idea to wave a strong magnet past a computer with a mechanical HDD?',
    options: [
      'The HDD stores its data magnetically, so the magnet could damage the data',
      'The magnet would pull the CPU out of its socket',
      'The magnet would erase the RAM, which is non-volatile',
      'The magnet would scratch the data etched on the disk by laser',
    ],
    answer: 0,
    hint: 'How does the read/write head find the data on the disk?',
    explanation: 'An HDD is vacuum sealed and its read/write head scans the disk for data represented magnetically. That is why the data survives power-off, and also why a strong magnet is a bad idea.',
    skills: ['T3-S5'],
  },
  't3-c9': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'Because SSDs outperform HDDs on many levels, there is no longer any reason to use an HDD in a computer.',
    answer: false,
    hint: 'Think about price per gigabyte.',
    explanation: 'SSDs are faster and less susceptible to shock, but the cost per GB is still more favourable for HDDs, and HDDs perform well on computers where users do tasks with little demand.',
    skills: ['T3-S5'],
  },
  't3-c10': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each storage device to how it stores data.',
    pairs: [
      { left: 'Mechanical HDD', right: 'Magnetic disk scanned by a moving read/write head' },
      { left: 'SSD', right: 'Microchips with no moving parts' },
      { left: 'Hybrid drive', right: 'HDD joined with high-speed SSD flash memory on one drive' },
      { left: 'Optical drive', right: 'Laser light etches (burns) data onto a disc' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Magnetic, electronic, a mix of both, and light.',
    explanation: 'HDDs store data magnetically, SSDs store it in microchips, hybrid drives combine both for efficiency and cost benefits, and CD, DVD and Blu-ray drives use laser light.',
    skills: ['T3-S5', 'T3-S6'],
  },
  't3-c11': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why are optical discs such as CDs not suited to data you need to change often?',
    options: [
      'They store data magnetically, which fades over time',
      'They can only be read by a smartphone camera',
      'The data is etched onto a plastic surface, so it cannot easily be changed',
      'They have no moving parts, so the drive cannot reach the data',
    ],
    answer: 2,
    hint: 'Think about what the laser does to the disc.',
    explanation: 'Optical drives etch data onto a plastic surface, so they are not conducive to changing the data, whereas a flash drive can be overwritten at will like a normal hard drive.',
    skills: ['T3-S6'],
  },
  't3-c12': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which statement about SD (Secure Digital) cards is correct?',
    options: [
      'They store data magnetically on a tiny spinning disk',
      'They are clipped onto the motherboard to add more RAM',
      'They are read and written using laser light',
      'They are small flash memory cards used in devices like digital cameras and mobile phones',
    ],
    answer: 3,
    hint: 'They give high memory for a very small size.',
    explanation: 'SD cards are very small flash memory cards used mainly in portable devices like camcorders, digital cameras, tablets, audio players and mobile phones. Micro SD cards are about the size of a SIM card.',
    skills: ['T3-S6'],
  },
  't3-c13': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'A flash drive uses solid state technology with no moving parts and connects via a USB port.',
    answer: true,
    hint: 'Is there a spinning disk inside a flash drive?',
    explanation: 'Flash drives use solid state technology with only electronic circuits. They connect via USB, and their small size makes them useful for transferring and backing up data.',
    skills: ['T3-S6'],
  },
  't3-c14': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each input device to what it reads.',
    pairs: [
      { left: 'Barcode scanner', right: 'Pattern of thin and wide lines on a product' },
      { left: 'Smartphone camera', right: 'Two-dimensional QR code of different sized squares' },
      { left: 'Magnetic stripe reader', right: 'Information encoded on a credit card or ATM card' },
      { left: 'Biometric device', right: 'Unique physical characteristics such as a fingerprint' },
      { left: 'Microphone', right: 'Sound waves sensed by a vibrating diaphragm' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Lines, squares, a stripe, your body and your voice.',
    explanation: 'Barcodes are thin and wide lines, QR codes are 2D squares easily read by a smartphone camera, magnetic stripes are on bank cards, biometrics use physical characteristics and microphones turn sound into an electrical signal.',
    skills: ['T3-S8', 'T3-S9'],
  },
  't3-c15': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the steps of fingerprint identification at a school gate in the correct order.',
    items: [
      'The computer compares the input against the stored sample',
      'At the gate, a scanner inputs the person\'s fingerprint',
      'If a match is found, the person is identified',
      'A sample fingerprint of the person is captured and stored',
      'The fingerprint is converted to a digital format and represented mathematically',
    ],
    answer: [3, 1, 4, 0, 2],
    hint: 'Nothing can be compared until a sample has been stored.',
    explanation: 'Biometrics first stores a sample. Later the input fingerprint is captured, converted to a digital, mathematical form and compared with the stored sample; a match identifies the person.',
    skills: ['T3-S8'],
  },
  't3-c16': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'A learner scans a printed page and wants to edit the text in a word processor. What does the scanner need?',
    options: [
      'A higher screen resolution on the monitor',
      'Optical Character Recognition (OCR) software that converts the text into Unicode',
      'A magnetic stripe to encode the page',
      'An accelerometer to detect the page orientation',
    ],
    answer: 1,
    hint: 'Without help, a scanner just produces a picture file like .jpg or .bmp.',
    explanation: 'Some scanners provide OCR software that analyses an image containing text and converts the text into Unicode, so it can be altered and edited.',
    skills: ['T3-S7'],
  },
  't3-c17': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'What is the purpose of the accelerometer in a smartphone?',
    options: [
      'To measure the temperature of the battery',
      'To convert sound energy into an electrical signal',
      'To gauge the tilt and orientation of the phone so the screen shows the right way round',
      'To read QR codes using near-infrared light',
    ],
    answer: 2,
    hint: 'Turn your phone sideways while watching a video.',
    explanation: 'An accelerometer is a sensor that gauges the tilting and orientation of a smartphone to determine which orientation the phone must show on the screen.',
    skills: ['T3-S9'],
  },
  't3-c18': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'A monitor has the resolution shown. Type whole numbers only, with no spaces or commas.',
    code: 'Screen resolution: 1024 x 768',
    rows: [
      { label: 'Pixels across the screen', answer: '1024' },
      { label: 'Pixels down the screen', answer: '768' },
      { label: 'Total number of pixels', answer: '786432' },
    ],
    hint: 'Resolution is given as pixels across by pixels down; multiply to get the total.',
    explanation: 'Resolution is the number of picture elements (pixels) on the monitor. 1024 x 768 = 786432 pixels, each with its own colour.',
    skills: ['T3-S10'],
  },
  't3-c19': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the 3D printing process in the correct order.',
    items: [
      'Print the object from the bottom up, slice by slice',
      'Design the object (normally as a .STL file) or download one',
      'The tiny layers stick together to form a solid object',
      'Slice the object into thin layers for the printer',
    ],
    answer: [1, 3, 0, 2],
    hint: 'Like baking each slice of bread and then gluing the slices into a loaf.',
    explanation: 'Stage one is designing (or downloading) the object, usually as a .STL file. Stage two is slicing it into thin layers. The printer then builds it bottom-up and the layers stick together into a solid object.',
    skills: ['T3-S10'],
  },
  't3-c20': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'Laser and inkjet, the two common printer technologies, are both non-impact printers: nothing touches the paper besides the ink or toner.',
    answer: true,
    hint: 'Which old printer used a hammer?',
    explanation: 'Laser and inkjet printers are non-impact printers. Impact printers, like the old dot-matrix, had a hammer that struck a ribbon onto the paper.',
    skills: ['T3-S10'],
  },
  't3-c21': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'How does a headset differ from a pair of headphones?',
    options: [
      'A headset is just a louder pair of headphones with an amplifier',
      'A headset projects sound over a wide area like speakers',
      'A headset is an input device only',
      'A headset combines a microphone and headphones on the same headband',
    ],
    answer: 3,
    hint: 'Call centre agents and gamers need to speak and listen at the same time.',
    explanation: 'A headset combines a microphone and headphones. They are essentially two different devices attached to the same headband for convenience.',
    skills: ['T3-S11'],
  },
  't3-c22': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which TWO ports do most modern computers mainly present for connecting devices?',
    options: ['USB and HDMI', 'VGA and parallel', 'Serial and sound jack', 'LAN and VGA'],
    answer: 0,
    hint: 'Look for the universal, versatile ports that replaced the older ones.',
    explanation: 'Most modern computers only present USB and HDMI ports. USB replaced parallel and serial ports, and HDMI replaced the VGA and sound jack ports. LAN ports still exist, but a LAN/USB adapter can be used.',
    skills: ['T3-S12'],
  },
  't3-c23': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'An HDMI port carries only video, so a separate sound jack is always needed for audio.',
    answer: false,
    hint: 'What does the M in HDMI stand for?',
    explanation: 'HDMI (High Definition Multimedia Interface) is a digital interface that receives and transmits both video and audio. It replaced the older VGA port and the sound jack port.',
    skills: ['T3-S12'],
  },
  't3-c24': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Complete the table from Check Point 2. For each component type exactly Input or Output.',
    code: 'Component     Input/Output\nMonitor       ?\nKeyboard      ?\nScanner       ?\nHeadphone     ?\nMicrophone    ?',
    rows: [
      { label: 'Monitor', answer: 'Output' },
      { label: 'Keyboard', answer: 'Input' },
      { label: 'Scanner', answer: 'Input' },
      { label: 'Headphone', answer: 'Output' },
      { label: 'Microphone', answer: 'Input' },
    ],
    hint: 'Does the device get data into the computer, or only receive information from it?',
    explanation: 'Keyboards, scanners and microphones get data into the computer, so they are input devices. Monitors and headphones only receive information from the computer, so they are output devices.',
    skills: ['T3-S7', 'T3-S10', 'T3-S11'],
  },
  't3-c25': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each device to its category.',
    pairs: [
      { left: 'Touch screen', right: 'Both an input and an output device' },
      { left: 'RAM', right: 'Component placed directly on the motherboard' },
      { left: 'Flash drive', right: 'Removable secondary storage' },
      { left: 'Printer', right: 'Output device' },
      { left: 'Barcode scanner', right: 'Input device' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'One device works in both directions; one sits on the motherboard itself.',
    explanation: 'A touch screen displays output and accepts finger or stylus input. RAM is a component on the motherboard. A flash drive is removable media. Printers output and barcode scanners input.',
    skills: ['T3-S4', 'T3-S6', 'T3-S10'],
  },
  't3-c26': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why does a computer need both volatile and non-volatile storage?',
    options: [
      'Volatile storage is only used for the BIOS, and non-volatile storage only for the CPU',
      'Volatile RAM holds data while it is processed, and non-volatile storage keeps it after the computer is switched off',
      'Non-volatile storage is faster, so volatile storage is only used as a backup',
      'Volatile storage keeps data permanently, while non-volatile storage loses it',
    ],
    answer: 1,
    hint: 'One is for working on data now, the other is for keeping it for later.',
    explanation: 'Data must be stored long enough to be processed, which is the job of volatile RAM that the CPU is connected to. To keep data permanently it must be saved to non-volatile secondary storage.',
    skills: ['T3-S3', 'T3-S5'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Learn the essential hardware of a computer system: what is on the motherboard, how data is stored, and which devices get data in and out.',
  outcomes: [
    'By the end you can name the hardware categories and describe the motherboard.',
    'By the end you can explain the CPU, von Neumann architecture and the roles of the ALU, CU and registers.',
    'By the end you can describe BIOS, RAM, ROM, EEPROM and firmware and explain volatile vs non-volatile storage.',
    'By the end you can classify hardware as components or peripherals.',
    'By the end you can compare HDDs, SSDs, hybrid drives, flash drives, optical drives and SD cards.',
    'By the end you can describe input devices from keyboards and scanners to biometric devices and sensors.',
    'By the end you can describe output devices: monitors, laser, inkjet and 3D printers, speakers and headphones.',
    'By the end you can explain why USB and HDMI ports are used to connect peripherals.',
  ],
  topics: [
    {
      id: 'T3-T1',
      title: 'Hardware, the motherboard and the CPU',
      sections: ['3', '3.1', '3.1.1', '3.1.1.1', '3.1.1.2', '3.1.1.3'],
      skills: ['T3-S1', 'T3-S2'],
      explanation: [
        'Hardware is categorised into Input, Storage, Processing, Output and Communication. A computer follows the principle of Input, Processing and Output (IPO).',
        'The motherboard is the large printed circuit board (PCB) that houses the essential electronic components of a device. The CPU, primary memory (RAM) and the connectors between them and other peripherals are all linked on the printed circuit.',
        'The CPU is the largest chip on the motherboard. It is square with pins that are inserted into a socket on the motherboard, and it continually interprets and executes the instructions stored in RAM. Many people confuse the system unit (computer case) with the CPU.',
        'Von Neumann architecture (first developed in 1945): programs and data are stored permanently in secondary storage. For a program to run it must first be loaded into RAM, because the CPU is directly connected to RAM.',
        'The CPU consists of the Arithmetic Logic Unit (ALU), the Control Unit (CU) and Registers. The ALU is an electronic circuit made of logic gates. It performs simple arithmetic on integer binary numbers and all logical calculations, deciding whether a condition is true or false using relational operators such as >, < and =.',
        'The ALU can only add: subtraction is addition of a negative number, multiplication is repeated addition, division is repeated subtraction and exponentiation is repeated multiplication.',
        'The Control Unit is the co-ordinator of program instructions sent to the processor: it controls what the processor does and how each instruction is processed in terms of the ALU, RAM and input/output devices. Registers are small memory holding places in the CPU; each may hold an instruction, a memory address or data, and registers can refer to other registers.',
      ],
      vocabulary: [
        { term: 'IPO', definition: 'Input, Processing and Output: the principle a computer follows.' },
        { term: 'Motherboard', definition: 'The large printed circuit board (PCB) that houses the essential electronic components of a device.' },
        { term: 'CPU', definition: 'Central Processing Unit: the largest chip on the motherboard, which continually interprets and executes instructions stored in RAM.' },
        { term: 'Von Neumann architecture', definition: 'The 1945 design in which programs and data are stored in secondary storage and loaded into RAM, which is directly connected to the CPU, to run.' },
        { term: 'ALU', definition: 'Arithmetic Logic Unit: a circuit of logic gates that does simple integer arithmetic and all logical calculations.' },
        { term: 'Control Unit (CU)', definition: 'The co-ordinator of program instructions sent to the processor; controls how each instruction is processed.' },
        { term: 'Register', definition: 'A small memory holding place in the CPU that may hold an instruction, a memory address or data.' },
      ],
      workedExamples: [
        { code: 'Secondary storage --(load)--> RAM <--> CPU [ ALU | CU | Registers ]', explanation: 'Von Neumann architecture: programs are kept in secondary storage but must be loaded into RAM, which is directly connected to the CPU.' },
        { code: '7 - 2   ->  7 + (-2)            = 5\n4 x 3   ->  4 + 4 + 4           = 12\n12 / 4  ->  12 - 4 - 4 - 4 = 0  (3 subtractions) = 3\n2 ^ 3   ->  2 x 2 x 2           = 8', explanation: 'How an ALU that can only add still handles subtraction, multiplication, division and exponentiation.' },
      ],
      misconceptions: [
        'The CPU is the computer case. Wrong: the case is the system unit; the CPU is the largest chip on the motherboard.',
        'The Control Unit does the calculations. Wrong: the ALU calculates; the CU co-ordinates and controls how instructions are processed.',
        'A program runs straight from the hard drive. Wrong: it must first be loaded into RAM, because the CPU is directly connected to RAM.',
      ],
      questions: [
        {
          id: 'T3-T1-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'Which description of the motherboard is correct?',
          options: [
            'The computer case that protects the internal parts',
            'A removable storage card used in cameras',
            'The large printed circuit board that houses the CPU, RAM and the connectors to other peripherals',
            'The chip that interprets and executes instructions',
          ],
          answer: 2,
          hint: 'PCB stands for printed circuit board.',
          explanation: 'The motherboard is the large PCB on which the CPU, primary memory (RAM) and the connectors to other peripherals are linked.',
          skills: ['T3-S1'],
        },
        {
          id: 'T3-T1-Q2',
          type: 'tf',
          category: 'distinguish',
          prompt: 'The Control Unit performs the arithmetic and logical calculations, while the ALU co-ordinates the instructions.',
          answer: false,
          hint: 'What does the A in ALU stand for?',
          explanation: 'The roles are swapped: the ALU does arithmetic and logical calculations, and the Control Unit is the co-ordinator of instructions.',
          skills: ['T3-S2'],
        },
        {
          id: 'T3-T1-Q3',
          type: 'mc',
          category: 'explain',
          prompt: 'Why must a program be loaded into RAM before it can run?',
          options: [
            'Because the CPU is directly connected to RAM, not to secondary storage',
            'Because RAM is non-volatile and keeps the program safe',
            'Because the hard drive can only store data, never programs',
            'Because the BIOS will not run programs stored in ROM',
          ],
          answer: 0,
          hint: 'Think about von Neumann architecture.',
          explanation: 'In von Neumann architecture programs are stored permanently in secondary storage, but the CPU is directly connected to RAM, so the program must be loaded into RAM first.',
          skills: ['T3-S2'],
        },
        {
          id: 'T3-T1-Q4',
          type: 'mc',
          category: 'identify',
          prompt: 'Hardware is categorised into Input, Storage, Processing, Output and which other category?',
          options: ['Compilation', 'Conversion', 'Calculation', 'Communication'],
          answer: 3,
          hint: 'Think of networks and connecting to other computers.',
          explanation: 'The five hardware categories are Input, Storage, Processing, Output and Communication.',
          skills: ['T3-S1'],
        },
      ],
    },
    {
      id: 'T3-T2',
      title: 'Primary memory and components vs peripherals',
      sections: ['3.1.2', '3.1.2.1', '3.1.2.2', '3.1.2.3', '3.1.3'],
      skills: ['T3-S3', 'T3-S4'],
      explanation: [
        'BIOS (Basic Input Output System) is non-volatile firmware (software programmed on a ROM chip) used to initialise hardware when the computer starts up, so that the operating system can take over and use the hardware afterwards.',
        'Once data is input it must be stored long enough to be processed. RAM (Random Access Memory) and other storage on the motherboard is primary storage. RAM is volatile: its contents constantly change during processing and are lost when the computer is switched off. Non-volatile (permanent) storage is secondary storage.',
        'RAM holds the instructions and data the user has loaded, and the processor accesses both. RAM is Dynamic RAM (DRAM): it constantly needs to be refreshed or it loses its contents. RAM comes on long circuit boards clipped into one, two or four slots on the motherboard, and adding more RAM can improve the speed of the computer.',
        'ROM (Read Only Memory) is a non-volatile chip that permanently stores data such as BIOS firmware, embedded operating systems and appliance or robotics controllers. A household appliance chip is programmed once when the device is manufactured. A robotics controller that must change tasks uses an EEPROM (Electronically Erasable Programmable ROM), which can be changed by a software program.',
        'Firmware is a software program or set of instructions programmed on a hardware device, typically stored in flash ROM. It is "semi-permanent": it stays the same unless it is updated by a firmware updater.',
        'Components vs peripherals: anything placed directly on the motherboard, like RAM or the CPU, is a component. Input, output and secondary storage devices are peripherals: connected to the motherboard but not placed directly on it.',
      ],
      vocabulary: [
        { term: 'BIOS', definition: 'Basic Input Output System: non-volatile firmware on a ROM chip that initialises hardware at start-up so the operating system can take over.' },
        { term: 'Volatile', definition: 'Contents are lost when the computer is switched off (e.g. RAM).' },
        { term: 'Non-volatile', definition: 'Permanent; keeps its contents without power (e.g. ROM, secondary storage).' },
        { term: 'DRAM', definition: 'Dynamic RAM: RAM that constantly needs to be refreshed or it loses its contents.' },
        { term: 'ROM', definition: 'Read Only Memory: a non-volatile chip that permanently stores data such as firmware.' },
        { term: 'EEPROM', definition: 'Electronically Erasable Programmable ROM: a ROM chip that can be changed using a software program.' },
        { term: 'Firmware', definition: 'A software program or set of instructions programmed on a hardware device; semi-permanent.' },
        { term: 'Component', definition: 'Hardware placed directly on the motherboard, like RAM or the CPU.' },
        { term: 'Peripheral', definition: 'An input, output or secondary storage device connected to, but not placed on, the motherboard.' },
      ],
      workedExamples: [
        { code: 'Memory        Volatile?   Where\nRAM (DRAM)    Yes         Clipped into a slot on the motherboard\nROM (BIOS)    No          Chip on the motherboard\nHard drive    No          Secondary storage (peripheral)', explanation: 'RAM loses its contents at power-off; ROM and secondary storage keep theirs.' },
        { code: 'Component:  CPU, RAM\nPeripheral: keyboard, mouse, monitor, printer, hard drive, flash drive', explanation: 'Components sit directly on the motherboard; peripherals are connected to it.' },
      ],
      misconceptions: [
        'RAM keeps your work if the power fails. Wrong: RAM is volatile, so unsaved work is lost; save it to secondary storage.',
        'ROM can never be changed. Wrong: an EEPROM can be changed by software, and firmware can be updated with a firmware updater.',
        'Everything inside the case is a component. Wrong: the hard drive is inside the case, but as a secondary storage device it is a peripheral, not placed on the motherboard.',
      ],
      questions: [
        {
          id: 'T3-T2-Q1',
          type: 'tf',
          category: 'define',
          prompt: 'Volatile storage, like RAM, keeps its contents after the computer is switched off.',
          answer: false,
          hint: 'Think about what happens to unsaved work during load shedding.',
          explanation: 'Volatile storage loses its contents when the computer is switched off. Non-volatile storage, like secondary storage, keeps data permanently.',
          skills: ['T3-S3'],
        },
        {
          id: 'T3-T2-Q2',
          type: 'order',
          category: 'sequence',
          prompt: 'Put these events in order, from switching the computer on to running a program.',
          items: [
            'The operating system takes over and uses the hardware',
            'The CPU interprets and executes the program\'s instructions from RAM',
            'The computer is switched on',
            'The user\'s program is loaded from secondary storage into RAM',
            'The BIOS initialises the hardware',
          ],
          answer: [2, 4, 0, 3, 1],
          hint: 'The BIOS gets the hardware ready before anything else can use it.',
          explanation: 'At start-up the BIOS initialises the hardware so the operating system can take over. A program is then loaded into RAM, where the CPU executes its instructions.',
          skills: ['T3-S3'],
        },
        {
          id: 'T3-T2-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'A robotics controller must be reprogrammed to perform a different task. Which chip should store its firmware?',
          options: [
            'A ROM chip programmed once at the factory',
            'An EEPROM',
            'Extra DRAM',
            'A register',
          ],
          answer: 1,
          hint: 'The chip must be non-volatile but still changeable.',
          explanation: 'An EEPROM (Electronically Erasable Programmable ROM) is non-volatile and can be changed using a software program, so it suits a controller that needs new tasks.',
          skills: ['T3-S3'],
        },
        {
          id: 'T3-T2-Q4',
          type: 'tf',
          category: 'classify',
          prompt: 'The hard drive is housed inside the computer case, yet it is a peripheral rather than a component.',
          answer: true,
          hint: 'Is it placed directly on the motherboard?',
          explanation: 'Secondary storage devices are peripherals: connected to the motherboard but not placed directly on it, even when they sit inside the case.',
          skills: ['T3-S4'],
        },
      ],
    },
    {
      id: 'T3-T3',
      title: 'Secondary storage: hard drives',
      sections: ['3.2', '3.2.1', '3.2.1.1', '3.2.1.2'],
      skills: ['T3-S5'],
      explanation: [
        'Secondary storage provides permanent, non-volatile storage that keeps data after the device has been switched off, for retrieval later. It can be fixed inside the computer or removable (removable media). Media is the general word for what the data is stored upon; examples of removable media are external hard drives, flash drives, SD cards and CDs.',
        'The hard drive is housed inside the computer case and stores all the user\'s programs and data permanently.',
        'A mechanical Hard Disk Drive (HDD) has mechanical parts, including a read/write head that scans the disk for data represented magnetically. It is vacuum sealed. Magnetic storage means data is not lost when the computer is switched off, and also explains why waving a strong magnet past the computer is a bad idea.',
        'A Solid State Drive (SSD) has no moving mechanical parts (disks, read/write heads), only electronic circuits; information is stored in microchips. This makes SSDs much faster and less susceptible to shock or damage. SSDs can be internal or external; an external SSD is removable media connected via a USB port.',
        'Although SSDs outperform HDDs on many levels, the cost per GB is still more favourable for HDDs, and HDDs still perform successfully where users do tasks with little demand.',
        'A hybrid drive joins an HDD with high-speed flash memory using SSD technology on the same drive, to benefit from the efficiencies and cost benefits of both.',
      ],
      vocabulary: [
        { term: 'Secondary storage', definition: 'Permanent, non-volatile storage that keeps data after the device has been switched off, for retrieval later.' },
        { term: 'Removable media', definition: 'Secondary storage that is not fixed inside the computer, e.g. external hard drives, flash drives, SD cards and CDs.' },
        { term: 'Media', definition: 'The general word describing what the data is stored upon.' },
        { term: 'HDD', definition: 'Mechanical Hard Disk Drive: stores data magnetically on a disk read by a moving read/write head.' },
        { term: 'SSD', definition: 'Solid State Drive: stores data in microchips with no moving mechanical parts.' },
        { term: 'Hybrid drive', definition: 'An HDD joined with high-speed flash memory using SSD technology on the same drive.' },
      ],
      workedExamples: [
        { code: 'Feature        HDD                    SSD\nMoving parts   Yes (disk, head)       No (microchips)\nSpeed          Slower                 Much faster\nShock damage   More susceptible       Less susceptible\nCost per GB    More favourable        Higher', explanation: 'The main trade-off: SSDs are faster and tougher, HDDs are cheaper per GB.' },
      ],
      misconceptions: [
        'An SSD has a spinning disk like an HDD, just faster. Wrong: an SSD has no moving parts at all; data is stored in microchips.',
        'HDDs are obsolete. Wrong: their cost per GB is more favourable, and they work well for low-demand users.',
      ],
      questions: [
        {
          id: 'T3-T3-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'Which is the best definition of secondary storage?',
          options: [
            'Volatile storage on the motherboard used while data is processed',
            'Small holding places inside the CPU',
            'Firmware that starts up the hardware',
            'Permanent, non-volatile storage that keeps data after the device is switched off',
          ],
          answer: 3,
          hint: 'It is the opposite of RAM.',
          explanation: 'Secondary storage is permanent and non-volatile: it keeps data after the device has been switched off, for retrieval later.',
          skills: ['T3-S5'],
        },
        {
          id: 'T3-T3-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'SSDs are less susceptible to shock or damage than HDDs because they have no moving mechanical parts.',
          answer: true,
          hint: 'What happens to a moving read/write head when a laptop is dropped?',
          explanation: 'With no disks or read/write heads, only electronic circuits, SSDs are faster and less susceptible to shock or damage.',
          skills: ['T3-S5'],
        },
        {
          id: 'T3-T3-Q3',
          type: 'mc',
          category: 'distinguish',
          prompt: 'What is the MAIN difference between an HDD and an SSD?',
          options: [
            'An HDD is removable media, but an SSD can only be internal',
            'An SSD stores data magnetically, an HDD stores it in microchips',
            'An HDD uses moving mechanical parts and magnetic storage; an SSD uses microchips with no moving parts',
            'An HDD is volatile and an SSD is non-volatile',
          ],
          answer: 2,
          hint: 'Think about what is physically inside each drive.',
          explanation: 'An HDD has a disk and a read/write head and stores data magnetically; an SSD has no moving parts and stores data in microchips. Both are non-volatile.',
          skills: ['T3-S5'],
        },
      ],
    },
    {
      id: 'T3-T4',
      title: 'Flash drives, optical drives and SD cards',
      sections: ['3.2.2', '3.2.3', '3.2.4'],
      skills: ['T3-S6'],
      explanation: [
        'A flash drive is a small, very portable storage device that uses solid state technology with no moving parts, only electronic circuits. It connects via a USB port, and its small size makes it useful for transferring and backing up data.',
        'Optical drives use (laser) light to etch (burn) data onto a disc for reading and writing. CD, DVD and Blu-ray drives are optical drives.',
        'Optical drives have lost popularity to higher capacity flash drives, and many devices, particularly laptops, no longer include them. A CD could only store 700MB and a single-sided DVD around 4.5GB, while flash drives of 8 to 16GB are commonplace.',
        'Because optical discs store data by etching a plastic surface, they are not conducive to changing data, whereas a flash drive can have its data overwritten at will, like a normal hard drive.',
        'SD (Secure Digital) cards are very small flash memory cards that provide high memory for a small size. They are used mainly in portable devices like digital video camcorders, digital cameras, tablets, audio players and mobile phones, provide 16GB upwards, and micro SD cards are similar in size to a mobile phone SIM card.',
      ],
      vocabulary: [
        { term: 'Flash drive', definition: 'A small, very portable solid state storage device that connects via USB.' },
        { term: 'Optical drive', definition: 'A drive that uses laser light to etch (burn) and read data on a disc: CD, DVD or Blu-ray.' },
        { term: 'SD card', definition: 'Secure Digital card: a very small flash memory card used in portable devices.' },
      ],
      workedExamples: [
        { code: 'CD                 700MB\nSingle-sided DVD   around 4.5GB\nFlash drive        8 to 16GB commonplace\nSD card            16GB upwards', explanation: 'Capacities from the textbook, showing why flash storage has overtaken optical discs.' },
      ],
      misconceptions: [
        'A CD can be rewritten as easily as a flash drive. Wrong: data is etched onto a plastic surface, so it is not conducive to changes.',
        'Flash drives contain a tiny spinning disk. Wrong: they use solid state technology with only electronic circuits.',
      ],
      questions: [
        {
          id: 'T3-T4-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'Which of these is NOT an optical drive?',
          options: ['CD drive', 'DVD drive', 'Blu-ray drive', 'Solid state drive'],
          answer: 3,
          hint: 'Optical drives use laser light.',
          explanation: 'CD, DVD and Blu-ray drives use laser light, so they are optical drives. A solid state drive stores data in microchips.',
          skills: ['T3-S6'],
        },
        {
          id: 'T3-T4-Q2',
          type: 'tf',
          category: 'distinguish',
          prompt: 'Like a hard drive, a flash drive can have its data overwritten at will, while data etched onto a CD is not easily changed.',
          answer: true,
          hint: 'Compare electronic circuits with a burned plastic surface.',
          explanation: 'Optical discs store data by etching a plastic surface, which is not conducive to change. Flash drives can be overwritten at will, like a normal hard drive.',
          skills: ['T3-S6'],
        },
      ],
    },
    {
      id: 'T3-T5',
      title: 'Keyboard, mouse and scanners',
      sections: ['3.3', '3.3.1', '3.3.2', '3.3.3'],
      skills: ['T3-S7'],
      explanation: [
        'An input device is a hardware device that is used to get data into the computer; this data is stored in RAM. The most common input devices are the keyboard and the mouse.',
        'A keyboard has many keys that represent characters with a unique value. Most keyboards have between 80 and 110 keys, divided into typing keys, a numeric keypad, function keys and control keys. The most common layout is QWERTY, named after the first six letters on the top left of the keyboard.',
        'A pointing device like a mouse is needed to select and click icons on a graphical display. The mouse detects a change in position when it is moved and makes a similar change on the screen. Optical mice have no mechanical parts and are reliable: they use a Light Emitting Diode (LED) that bounces light off the surface. Wireless mice need a receiver for the signals from the mouse. Touch screens do not require a mouse.',
        'A scanner is an input device that analyses an image and converts it to a file, normally a .jpg or .bmp file. Some scanners provide Optical Character Recognition (OCR) software that analyses an image containing text and converts the text into Unicode, so that it can be altered and edited.',
        'The better the scanner, the higher the resolution of the image. Scanner resolution is measured in dots per inch (dpi), for example 600x600 dpi. Many scanners are combined with multi-function printers.',
      ],
      vocabulary: [
        { term: 'Input device', definition: 'A hardware device used to get data into the computer; the data is stored in RAM.' },
        { term: 'QWERTY', definition: 'The most common keyboard layout, named after the first six letters on the top left.' },
        { term: 'Optical mouse', definition: 'A mouse with no mechanical parts that uses an LED to bounce light off the surface.' },
        { term: 'Scanner', definition: 'An input device that analyses an image and converts it to a file.' },
        { term: 'OCR', definition: 'Optical Character Recognition: software that converts text in a scanned image into Unicode so it can be edited.' },
        { term: 'dpi', definition: 'Dots per inch: the unit of scanner resolution, e.g. 600x600 dpi.' },
      ],
      workedExamples: [
        { code: 'Keyboard sections: Typing keys | Numeric keypad | Function keys | Control keys\nKeys: 80 to 110\nLayout: Q W E R T Y ...', explanation: 'How a typical keyboard is organised.' },
      ],
      misconceptions: [
        'Any scanned page of text can be edited. Wrong: without OCR the scan is only an image file such as .jpg or .bmp.',
        'Every device needs a mouse. Wrong: devices with touch screens do not require a mouse to select images and icons.',
      ],
      questions: [
        {
          id: 'T3-T5-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'Why is the most common keyboard layout called QWERTY?',
          options: [
            'It is named after the first six letters on the top left of the keyboard',
            'It is named after the six function keys at the top',
            'It is named after the company that invented the keyboard',
            'It is named after the six keys of the numeric keypad',
          ],
          answer: 0,
          hint: 'Look at the top row of letters on your keyboard.',
          explanation: 'QWERTY is named after the first six letters on the top left of the keyboard.',
          skills: ['T3-S7'],
        },
        {
          id: 'T3-T5-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'An optical mouse relies on mechanical moving parts, which makes it less reliable.',
          answer: false,
          hint: 'What does the LED do?',
          explanation: 'Optical mice have no mechanical parts and are reliable; they use an LED that bounces light off the surface to detect movement.',
          skills: ['T3-S7'],
        },
        {
          id: 'T3-T5-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'Scanner A scans at 300x300 dpi and scanner B at 600x600 dpi. Which statement is correct?',
          options: [
            'Scanner A produces the higher resolution image',
            'Scanner B captures more dots per inch, giving a higher resolution image',
            'Both give the same image, because dpi only applies to printers',
            'dpi measures how fast the scanner works, not image quality',
          ],
          answer: 1,
          hint: 'More dots in every inch means more detail.',
          explanation: 'Scanner resolution is measured in dots per inch; the better the scanner, the higher the resolution of the image.',
          skills: ['T3-S7'],
        },
      ],
    },
    {
      id: 'T3-T6',
      title: 'Barcodes, QR codes, magnetic stripes and biometrics',
      sections: ['3.3.3.1', '3.3.3.2', '3.3.3.3', '3.3.3.4'],
      skills: ['T3-S8'],
      explanation: [
        'Barcode scanners are commonly used at a Point of Sale (POS) terminal at a supermarket checkout. The barcode stores information about the product, including a description and a price. The reader shines a red LED light onto the black and white barcode and reads the pattern of reflected light. This information can update stock levels and even signal reordering when stock runs low.',
        'A barcode is a simple pattern of thin and wide lines decoded by the scanner to represent data. Barcode scanners can be handheld or built into the checkout lane.',
        'Quick Response (QR) codes are easily read by the camera of a smartphone. They differ from barcodes because they are two-dimensional sets of different sized squares on a white background and can contain a lot more information. Both barcodes and QR codes can be read and created with many proprietary and free apps.',
        'A magnetic stripe reader converts the information encoded in the magnetic stripe of a card (such as a credit card, ATM card or employee identification card) into a format the computer can understand.',
        'Biometrics is a way of uniquely recognising humans based on physical characteristics such as fingerprints or retina scans. A sample is stored, and the input data is compared against it; if a match is found, the user is identified. The most common biometric systems are fingerprints, iris/retinal scans and voiceprints.',
        'Fingerprints are unique and do not change over a life span (except after an injury), making them the most commonly used biometric. A fingerprint is captured, converted to a digital format and represented mathematically.',
        'An iris scan uses the unique patterns of the iris (the coloured area around the pupil). A digital camera takes a picture, plus one using near-infrared light for a clear, high-contrast image; the person does not need to touch the camera. The patterns are translated into a mathematical expression and compared quickly and with high accuracy.',
      ],
      vocabulary: [
        { term: 'POS', definition: 'Point of Sale: the checkout terminal where products are scanned and paid for.' },
        { term: 'Barcode', definition: 'A simple pattern of thin and wide lines decoded by a scanner to represent data.' },
        { term: 'QR code', definition: 'Quick Response code: a two-dimensional set of different sized squares that holds a lot more information than a barcode.' },
        { term: 'Magnetic stripe reader', definition: 'Converts information encoded on a card\'s magnetic stripe into a format the computer understands.' },
        { term: 'Biometrics', definition: 'A way of uniquely recognising humans based on physical characteristics such as fingerprints.' },
        { term: 'Iris', definition: 'The coloured area of the eye that surrounds the pupil; its unique patterns are used for recognition.' },
      ],
      workedExamples: [
        { code: 'Barcode:  | || ||| | ||  (1D lines)\nQR code:  2D grid of squares, read by a smartphone camera', explanation: 'A barcode is one-dimensional lines; a QR code is two-dimensional squares that can hold far more information.' },
      ],
      misconceptions: [
        'A QR code is just a square barcode holding the same data. Wrong: it is two-dimensional and can contain a lot more information.',
        'Iris scanning requires touching the camera. Wrong: the process does not need the person to touch the camera.',
      ],
      questions: [
        {
          id: 'T3-T6-Q1',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps of scanning an item at a supermarket POS terminal in order.',
          items: [
            'The scanner reads the pattern of reflected light',
            'Stock levels are updated and a reorder can be signalled',
            'A red LED light shines onto the black and white barcode',
            'The pattern is decoded into product data such as description and price',
          ],
          answer: [2, 0, 3, 1],
          hint: 'Light must hit the barcode before anything can be read.',
          explanation: 'The reader shines a red LED onto the barcode, reads the reflected pattern, decodes the product description and price, and the information can then update stock levels.',
          skills: ['T3-S8'],
        },
        {
          id: 'T3-T6-Q2',
          type: 'mc',
          category: 'distinguish',
          prompt: 'How does a QR code differ from a barcode?',
          options: [
            'A QR code can only be read by a POS terminal at a supermarket',
            'A QR code is a pattern of thin and wide lines, and a barcode is made of squares',
            'A QR code is a two-dimensional set of different sized squares that can hold a lot more information',
            'A QR code stores data magnetically, and a barcode stores it optically',
          ],
          answer: 2,
          hint: 'Think in dimensions.',
          explanation: 'QR codes are two-dimensional sets of different sized squares on a white background, easily read by a smartphone camera, and hold a lot more information than barcodes.',
          skills: ['T3-S8'],
        },
        {
          id: 'T3-T6-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'Fingerprints change regularly over a person\'s life, so they are seldom used for biometric identification.',
          answer: false,
          hint: 'Which is the MOST commonly used biometric?',
          explanation: 'Fingerprints are unique and do not change over a life span (except after an injury), which makes fingerprinting the most commonly used biometric.',
          skills: ['T3-S8'],
        },
      ],
    },
    {
      id: 'T3-T7',
      title: 'Microphones and sensors',
      sections: ['3.3.4', '3.3.5'],
      skills: ['T3-S9'],
      explanation: [
        'A microphone converts sound energy into electrical/digital energy, which is understood by a computer. Microphones differ in how they convert the energy, but all use a diaphragm (a vibrating membrane) that senses the sound wave and converts it into an electrical signal.',
        'Just as humans detect the real world through their senses, computers receive information about the physical world through sensors. A sensor converts a real-world property (for example temperature, blood pressure, height, humidity or speed) into a signal that can be measured electrically, i.e. data the computer can process. There are sensors for light, sound, heat and much more.',
        'In Smart Homes, alarms and other controlling devices respond to sensors. Many robotics controllers rely on sensors to decide what the robot must do.',
        'An accelerometer is a sensor that gauges the tilting and orientation of a smartphone to determine which orientation the phone must show on the screen.',
        'Sensors are input: the computer detects the real world, makes decisions and provides output in real time, adjusting the output as input is received. In an aircraft Autopilot System, sensors input speed, height, position, doors, obstacles, fuel and manoeuvring data; the computer compares it with pre-set values and signals engines, flaps and rudders.',
      ],
      vocabulary: [
        { term: 'Microphone', definition: 'An input device that converts sound energy into electrical/digital energy.' },
        { term: 'Diaphragm', definition: 'A vibrating membrane that senses sound waves (or produces them in speakers).' },
        { term: 'Sensor', definition: 'A device that converts a real-world property into data a computer can process.' },
        { term: 'Accelerometer', definition: 'A sensor that gauges the tilt and orientation of a smartphone.' },
        { term: 'Real time', definition: 'The output is adjusted as the input is received.' },
      ],
      workedExamples: [
        { code: 'Sensor input (speed, height, fuel)\n  -> compare with pre-set values\n  -> decision\n  -> signal engines, flaps, rudders', explanation: 'The real-time input-process-output loop of an aircraft autopilot.' },
      ],
      misconceptions: [
        'Sensors are output devices because they make alarms go off. Wrong: sensors are input; the alarm is the output that responds to them.',
      ],
      questions: [
        {
          id: 'T3-T7-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'How does a microphone work?',
          options: [
            'A diaphragm vibrates with the sound wave and the vibration is converted into an electrical signal',
            'A laser etches the sound onto a disc for the computer to read',
            'An LED bounces light off the sound wave to measure it',
            'A magnetic stripe records the sound for the computer to decode',
          ],
          answer: 0,
          hint: 'All microphones share one vibrating part.',
          explanation: 'All microphones use a diaphragm, a vibrating membrane, that senses the sound wave and converts it into an electrical signal the computer can understand.',
          skills: ['T3-S9'],
        },
        {
          id: 'T3-T7-Q2',
          type: 'tf',
          category: 'classify',
          prompt: 'Sensors are input devices: they convert a real-world property into data the computer can process.',
          answer: true,
          hint: 'Which way does the data flow: from the world to the computer, or the other way?',
          explanation: 'Sensors are used by computers to detect the real world as input; the computer then makes decisions and provides output.',
          skills: ['T3-S9'],
        },
        {
          id: 'T3-T7-Q3',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps of an aircraft autopilot in order.',
          items: [
            'The computer signals the engines, flaps and rudders',
            'The computer compares the data with pre-set values and makes decisions',
            'The computer inputs the data from the sensors',
            'Sensors measure physical properties such as speed and height',
          ],
          answer: [3, 2, 1, 0],
          hint: 'Input, then processing, then output.',
          explanation: 'Sensors measure the real world, the computer inputs that data, compares it with pre-set values and then signals parts of the plane, all in real time.',
          skills: ['T3-S9'],
        },
      ],
    },
    {
      id: 'T3-T8',
      title: 'Monitors and printers',
      sections: ['3.4', '3.4.1', '3.4.2', '3.4.2.1', '3.4.2.2'],
      skills: ['T3-S10'],
      explanation: [
        'An output device is any device that only receives information from the computer; it does not send information to the computer. The most common output devices are monitors (screens) and printers.',
        'The most commonly used monitors are Liquid Crystal Display (LCD) screens. Two important factors when choosing a screen are the resolution and the screen size.',
        'Resolution is the number of picture elements (pixels) on the monitor, each with its own colour. It is given as the number of pixels across by the number of pixels down, such as 1024x768. Resolution is affected by several factors, including the size of the screen.',
        'Screen size is measured diagonally from the top left to the bottom right (or vice versa), not including the casing. LCD screen sizes are 15, 17, 19 and 21 inches; laptop screens are smaller, typically 12 to 17 inches.',
        'A touch screen (used in smartphones, tablets and some laptops) lets a finger or stylus emulate a mouse, so it is both an input and an output device.',
        'Printers use laser or inkjet technology and print in black and colour or only black. Both are non-impact printers: nothing touches the paper besides the ink or toner. Impact printers, like the old dot-matrix, had a hammer that struck a ribbon onto the paper.',
        '3D printers can produce objects in different materials, from ceramic cups and plastic toys to metal machine parts and even chocolate cakes. Like baking each slice of bread and gluing the slices into a loaf, the object is turned into thousands of thin slices and made bottom-up, slice by slice. Stage 1: design the object (normally a .STL file) or download one. Stage 2: slicing, dividing the object into thin layers for the printer.',
      ],
      vocabulary: [
        { term: 'Output device', definition: 'Any device that only receives information from the computer and does not send information to it.' },
        { term: 'LCD', definition: 'Liquid Crystal Display: the most commonly used type of monitor.' },
        { term: 'Pixel', definition: 'Picture element: one dot on the screen with its own colour.' },
        { term: 'Resolution', definition: 'The number of pixels on the monitor, given as pixels across by pixels down, e.g. 1024x768.' },
        { term: 'Non-impact printer', definition: 'A printer where nothing touches the paper besides the ink or toner (laser and inkjet).' },
        { term: 'Slicing', definition: 'Dividing a 3D object into thin layers for the 3D printer to print.' },
      ],
      workedExamples: [
        { code: 'Resolution 1024 x 768\nTotal pixels = 1024 x 768 = 786432', explanation: 'Multiply pixels across by pixels down to get the total number of pixels on the screen.' },
        { code: 'Desktop LCD: 15, 17, 19, 21 inches\nLaptop:      12 to 17 inches\nMeasured diagonally, top left to bottom right, without the casing', explanation: 'Standard screen sizes from the textbook.' },
      ],
      misconceptions: [
        'Screen size includes the casing. Wrong: it is measured diagonally across the screen only.',
        'A touch screen is only an output device. Wrong: it is both input and output, because your finger or stylus emulates a mouse.',
        'Inkjet printers strike the paper. Wrong: laser and inkjet are non-impact; the old dot-matrix was the impact printer.',
      ],
      questions: [
        {
          id: 'T3-T8-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'How is the size of a monitor measured?',
          options: [
            'Across the width of the screen, including the casing',
            'Diagonally from one corner to the opposite corner, not including the casing',
            'Down the height of the screen, from top to bottom',
            'By counting the pixels across the screen',
          ],
          answer: 1,
          hint: 'Corner to corner.',
          explanation: 'Screen size is measured diagonally from the top left to the bottom right (or vice versa), not including the casing.',
          skills: ['T3-S10'],
        },
        {
          id: 'T3-T8-Q2',
          type: 'tf',
          category: 'classify',
          prompt: 'Because an output device only receives information from the computer, a touch screen is an output device only.',
          answer: false,
          hint: 'What does your finger do on a touch screen?',
          explanation: 'A touch screen displays output but also lets a finger or stylus emulate a mouse, so it is both an input and an output device.',
          skills: ['T3-S10'],
        },
        {
          id: 'T3-T8-Q3',
          type: 'mc',
          category: 'define',
          prompt: 'In 3D printing, what is slicing?',
          options: [
            'Cutting a printed object into pieces after printing',
            'Designing the object as a .STL file',
            'Gluing the finished layers together with ink',
            'Dividing the designed object into thin layers for the printer to print',
          ],
          answer: 3,
          hint: 'It is the second stage, after the design.',
          explanation: 'Slicing is the second stage: dividing the designed object into thin layers, which the printer then builds bottom-up.',
          skills: ['T3-S10'],
        },
        {
          id: 'T3-T8-Q4',
          type: 'mc',
          category: 'identify',
          prompt: 'Which range describes typical laptop screen sizes?',
          options: ['12 to 17 inches', '15 to 21 inches', '4 to 7 inches', '24 to 32 inches'],
          answer: 0,
          hint: 'Laptop screens are smaller than desktop LCD screens.',
          explanation: 'Desktop LCD screens come in 15, 17, 19 and 21 inches; laptop screens are smaller, typically 12 to 17 inches.',
          skills: ['T3-S10'],
        },
      ],
    },
    {
      id: 'T3-T9',
      title: 'Speakers and headphones',
      sections: ['3.4.3', '3.4.4'],
      skills: ['T3-S11'],
      explanation: [
        'Speakers are commonly used output devices. They receive audio input (in a digital format) from the computer\'s sound card and produce audio output as sound waves we can hear. Most computer speakers have an internal amplifier to increase the volume, or amplitude, of the sound.',
        'Speakers usually come in pairs, to produce stereo sound from two separate audio channels.',
        'Headphones and speakers are the exact opposite of microphones, using the same technology in reverse: a diaphragm converts the digital data into sound waves.',
        'Speakers project sound over a wide area, while headphones are connected to a band that fits your head and only provide adequate sound to the person wearing them.',
        'A headset combines a microphone and headphones. Call centre agents, gamers and others who speak and listen simultaneously use them, but they are essentially two different devices attached to the same headband for convenience.',
      ],
      vocabulary: [
        { term: 'Speaker', definition: 'An output device that turns digital audio from the sound card into sound waves.' },
        { term: 'Amplifier', definition: 'Part of most computer speakers that increases the volume (amplitude) of the sound.' },
        { term: 'Stereo', definition: 'Sound from two separate audio channels, produced by a pair of speakers.' },
        { term: 'Headset', definition: 'A microphone and headphones attached to the same headband.' },
      ],
      workedExamples: [
        { code: 'Microphone: sound waves -> diaphragm -> electrical signal (input)\nSpeaker:    digital data -> diaphragm -> sound waves  (output)', explanation: 'Speakers and headphones use the microphone\'s technology in reverse.' },
      ],
      misconceptions: [
        'A headset is a single new type of device. Wrong: it is two different devices, a microphone and headphones, on one headband.',
      ],
      questions: [
        {
          id: 'T3-T9-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'Why do computer speakers usually come in pairs?',
          options: [
            'So that one speaker can act as a microphone',
            'Because each speaker can only play one volume level',
            'To produce stereo sound from two separate audio channels',
            'So that the amplifier can be removed',
          ],
          answer: 2,
          hint: 'Left channel and right channel.',
          explanation: 'Speakers usually come in pairs to produce stereo sound from two separate audio channels.',
          skills: ['T3-S11'],
        },
        {
          id: 'T3-T9-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'Headphones work like a microphone in reverse: a diaphragm converts the data into sound waves.',
          answer: true,
          hint: 'Compare what goes in and what comes out of each device.',
          explanation: 'Headphones and speakers are the exact opposite of microphones, using the same diaphragm technology in reverse.',
          skills: ['T3-S11'],
        },
      ],
    },
    {
      id: 'T3-T10',
      title: 'Ports: USB and HDMI',
      sections: ['3.5', '3.5.1', '3.5.2'],
      skills: ['T3-S12'],
      explanation: [
        'Input and output devices need a connecting port to communicate with the computer. Microphones and speakers may use jack plugs via a sound card, but most devices use the more versatile, universal USB and HDMI ports.',
        'Universal ports reduce the number of ports needed on a computer for all the devices that may connect. Most modern computers only present USB and HDMI ports; LAN ports can still be found, and a LAN/USB adapter can be used.',
        'USB (Universal Serial Bus) is a common interface that enables communication between devices and a host controller such as a personal computer. It connects digital cameras, mice, keyboards, printers, scanners, media devices, external hard drives and flash drives. Because of its wide variety of uses, including support for electrical power, USB has replaced interfaces like the parallel and serial port.',
        'HDMI (High Definition Multimedia Interface) ports provide a digital interface to receive and transmit both video and audio signals. They replaced the older VGA graphics port and the sound jack port, and can transmit data from many source devices to numerous display monitors. An HDMI port looks like a USB port but has tapered edges at the bottom.',
      ],
      vocabulary: [
        { term: 'Port', definition: 'A connection point that lets a device communicate with the computer.' },
        { term: 'USB', definition: 'Universal Serial Bus: a common interface between devices and a host controller such as a PC; also supplies power.' },
        { term: 'HDMI', definition: 'High Definition Multimedia Interface: a digital interface that receives and transmits video and audio.' },
      ],
      workedExamples: [
        { code: 'USB  replaced  parallel port, serial port\nHDMI replaced  VGA graphics port, sound jack port', explanation: 'How two universal ports took over from many older ones.' },
      ],
      misconceptions: [
        'More ports are always better. Wrong: manufacturers use universal ports to reduce the number of ports needed.',
        'HDMI and USB are identical. Wrong: an HDMI port looks similar but has tapered edges at the bottom, and it carries video and audio.',
      ],
      questions: [
        {
          id: 'T3-T10-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'Why have computer manufacturers reduced the number of ports on modern computers?',
          options: [
            'Peripherals no longer need to communicate with the computer',
            'Universal ports such as USB and HDMI connect many kinds of devices, so fewer ports are needed',
            'LAN ports have been banned on modern computers',
            'HDMI can store data like a flash drive, so drives no longer need ports',
          ],
          answer: 1,
          hint: 'The U in USB stands for Universal.',
          explanation: 'Using universal ports reduces the number of ports needed on a computer for all the devices that may need to connect.',
          skills: ['T3-S12'],
        },
        {
          id: 'T3-T10-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'USB replaced older interfaces like the parallel and serial port, partly because it also supports electrical power.',
          answer: true,
          hint: 'A flash drive needs no separate power cable.',
          explanation: 'Because of its wide variety of uses, including support for electrical power, USB has replaced a wide range of interfaces like the parallel and serial port.',
          skills: ['T3-S12'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't3-exam-day-boot-failure',
    unitId: UNIT.id,
    title: 'Exam Day Boot Failure',
    icon: 'cpu',
    summary: 'Revive the school lab PCs before the IT exam starts.',
    briefing: 'It is 07:45 and the Grade 10 IT practical exam starts at 08:00. Half the lab PCs will not start and the rest lose work every time the power dips. Diagnose the CPUs, memory and drives before the invigilator walks in.',
    tickerMessages: [
      'LAB 4: fifteen PCs stuck on a black screen after power-on',
      'TECHNICIAN: "Check the BIOS and the RAM slots first"',
      'LOAD SHEDDING ALERT: all unsaved work in RAM at risk',
      'PRINCIPAL: exam cancelled if the machines are not ready by 08:00',
      'FINAL WARNING: invigilator walking down the corridor',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T3-S1', 'T3-S2', 'T3-S3', 'T3-S4', 'T3-S5'],
    victoryMessage: 'Every PC boots, all work is saved to secondary storage and the exam starts on time. The lab technician owes you a koeksister.',
    failMessage: 'The screens stay black and the exam is postponed. Back to the motherboard for some revision.',
  },
  {
    id: 't3-checkout-chaos',
    unitId: UNIT.id,
    title: 'Black Friday Checkout Chaos',
    icon: 'alert',
    summary: 'Keep the supermarket tills running on the busiest day of the year.',
    briefing: 'It is Black Friday at a Durban supermarket and the POS terminals are failing: barcode scanners, card readers and slip printers are all down. Pick the right input and output devices and the ports that connect them before the queues reach the parking lot.',
    tickerMessages: [
      'TILL 3: barcode scanner red LED flickering, prices not loading',
      'CUSTOMER SERVICE: card machines rejecting every swipe',
      'STOCK ROOM: sensors report the fridges warming up',
      'MANAGER: queues now stretch past the bakery',
      'SECURITY: crowd growing restless at the entrance',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T3-S7', 'T3-S8', 'T3-S9', 'T3-S10', 'T3-S12'],
    victoryMessage: 'Every till beeps, every card swipes and every slip prints. The shoppers cheer and the manager offers you a job.',
    failMessage: 'The tills stay dark and the shoppers walk out. Time to revise your input and output devices.',
  },
];
