// Theory Learning Unit 4: System Software (Exploring IT: Theory Grade 10, 2nd ed)
import { Settings } from 'lucide-react';

export const UNIT = { id: 'T4', number: 4, name: 'System Software', worldId: 'system-software' };

export const SKILLS = {
  'T4-S1': { unit: 'T4', name: 'Parts of system software', description: 'Name the parts of system software and the three main functions of an operating system.', sections: ['4', '4.1', '4.1.1'] },
  'T4-S2': { unit: 'T4', name: 'CLI vs GUI', description: 'Distinguish a text-based command line interface from a graphical user interface (WIMP and touch).', sections: ['4.1.1.1'] },
  'T4-S3': { unit: 'T4', name: 'Running programs and resources', description: 'Explain how the OS loads and runs programs and manages I/O, files, memory and processes.', sections: ['4.1.1.2', '4.1.1.3'] },
  'T4-S4': { unit: 'T4', name: 'Device drivers', description: 'Explain what a driver does, how applications reach hardware through it, and how new devices get drivers.', sections: ['4.1.2', '4.4.2'] },
  'T4-S5': { unit: 'T4', name: 'Programming tools', description: 'Describe IDEs and development tools and distinguish source code from executable code.', sections: ['4.1.3', '4.1.3.1'] },
  'T4-S6': { unit: 'T4', name: 'Utilities and defragmentation', description: 'Explain the purpose of utility programs and what a Disk Defragmenter does.', sections: ['4.1.4', '4.1.4.1'] },
  'T4-S7': { unit: 'T4', name: 'Software licensing', description: 'Compare proprietary, free and open source, Creative Commons, freeware and freemium licences.', sections: ['4.2', '4.2.1', '4.2.2', '4.2.2.1', '4.2.2.2', '4.2.2.3'] },
  'T4-S8': { unit: 'T4', name: 'Profiles, desktop and folders', description: 'Manage user profiles, the desktop and a hierarchical file and folder structure.', sections: ['4.3', '4.3.1', '4.3.2', '4.3.2.1', '4.3.3'] },
  'T4-S9': { unit: 'T4', name: 'Cloud storage and sharing', description: 'Explain cloud-based storage and how sharing and permissions work locally and in the cloud.', sections: ['4.3.3.1', '4.3.3.2'] },
  'T4-S10': { unit: 'T4', name: 'Compression, archive and backup', description: 'Compress and extract files and distinguish an archive from a backup.', sections: ['4.3.4', '4.3.4.1', '4.3.4.2', '4.3.5', '4.3.5.1', '4.3.5.2'] },
  'T4-S11': { unit: 'T4', name: 'System management', description: 'Install and uninstall software, schedule tasks and keep the system updated.', sections: ['4.4', '4.4.1', '4.4.3', '4.4.3.1', '4.4.3.2'] },
  'T4-S12': { unit: 'T4', name: 'Security features', description: 'Explain firewalls, the types of malware and how anti-malware and anti-virus software protect a computer.', sections: ['4.5', '4.5.1', '4.5.2', '4.5.2.1', '4.5.2.2', '4.5.2.3', '4.5.3', '4.5.3.1'] },
};

export const SKILL_HINTS = {
  'T4-S1': 'System software = operating system, utilities, compilers and drivers; every OS provides a user interface, loads and runs programs and manages resources; kernel loads at switch-on',
  'T4-S2': 'CLI: text commands typed at a command prompt (MS DOS); GUI: WIMP = Windows, Icons, Mouse control, Pull-down menus; touch screens let a stylus or finger replace the pointer; Linux has both',
  'T4-S3': 'OS loads, runs and controls programs; manages I/O (hides device details), file management (create, save, delete, move, copy), memory management (enough memory, no shared space), process management (CPU time per process)',
  'T4-S4': 'Driver = small specific program giving the OS what it needs to work with a device; app -> OS -> driver -> hardware; same printer driver for any app; plug and play detects hardware; hot swappable = no restart, most USB',
  'T4-S5': 'IDE = source code editor + compiler or interpreter + add-ons (NetBeans); Unity for 2D/3D games; WORA cross-platform tools (Codename One, PhoneGap); source .java/.pas compiled to executable .class/.exe; .class needs JRE',
  'T4-S6': 'Utilities help manage, analyse, maintain, optimise and control the computer, many in the Control Panel; Disk Defragmenter rearranges fragmented data on mechanical hard disks; SSDs and flash drives do not need it',
  'T4-S7': 'Licence protects copyright, licence manager fights piracy (illegal copying); proprietary: no copying, product keys, no source, EULA; GNU GPL copyleft shares source; Creative Commons: copy with acknowledgement; freeware: free, no resale, no source; freemium: pay to unlock',
  'T4-S8': 'User profile: own Documents, Pictures, Desktop, only user or admin can change it; keep only shortcuts on the desktop (large files slow logon, clutter, lost on OS reinstall); drive\\folder\\file path; no duplicate names in a folder',
  'T4-S9': 'Cloud storage = data stored remotely, accessed via the Internet (Google File Stream, iCloud, Dropbox), synchronises with local folders; local permissions Full Control, Modify, Read & Execute, List folder contents, Read, Write; Google Drive owner: organise, add & edit, view only',
  'T4-S10': 'Compression (WinZip, 7-Zip, WinRAR) shrinks files to save space and bandwidth, text compresses well, images less; Send To creates one compressed file; archive removes unused files to compressed storage; backup copies files to a separate location in case of data loss',
  'T4-S11': 'Installer places files, creates folders and updates the registry; typical, custom or full install; product/activation key; uninstall removes files, folders, icons and updates the registry; Task Scheduler runs tasks automatically; updates over the Internet, once service packs on CD',
  'T4-S12': 'Firewall permits or denies transmissions by rules; malware = any harmful program or file: virus (damages, spreads), spyware (keystroke logger), adware (pop-ups, usually benign, slows PC); anti-virus updates signature database, protection categories, scan options',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Kernel Citadel',
  subtitle: 'Unit 4 \u00b7 System Software',
  color: 'magenta',
  glow: 'ja-glow-magenta',
  bg: 'ja-w-system-software',
  icon: Settings,
  blurb: 'Command the operating system, drivers, utilities and licences that keep every computer alive. Then defend the citadel from viruses, spyware and adware.',
};

export const LEVELS = [
  { id: 't4-l1', name: 'Boot Sequence', subtitle: 'Operating systems, interfaces and drivers', challengeIds: ['t4-c1', 't4-c2', 't4-c3', 't4-c4', 't4-c5', 't4-c6'] },
  { id: 't4-l2', name: 'Toolbox and Licences', subtitle: 'Programming tools, utilities and licensing models', challengeIds: ['t4-c7', 't4-c8', 't4-c9', 't4-c10', 't4-c11', 't4-c12'] },
  { id: 't4-l3', name: 'Storage Vaults', subtitle: 'Profiles, folders, cloud, compression, archive and backup', challengeIds: ['t4-c13', 't4-c14', 't4-c15', 't4-c16', 't4-c17', 't4-c18', 't4-c19'] },
  { id: 't4-l4', name: 'Citadel Defence', subtitle: 'Boss: system management, security and full unit review', challengeIds: ['t4-c20', 't4-c21', 't4-c22', 't4-c23', 't4-c24', 't4-c25', 't4-c26'] },
];

export const CHALLENGES = {
  't4-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Every operating system has three main functions. Which option lists them?',
    options: [
      'Provide a user interface, compile source code and defragment the disk',
      'Provide a user interface, load and run programs and manage the computer\'s resources',
      'Load and run programs, block viruses and back up files',
      'Manage the computer\'s resources, print documents and browse the Internet',
    ],
    answer: 1,
    hint: 'Think of how you talk to the computer, how apps start, and who controls the CPU, RAM and devices.',
    explanation: 'Every OS provides a user interface, loads and runs programs, and manages resources such as the CPU, RAM, storage and peripherals. Compiling, backups and anti-virus are jobs for other system software.',
    skills: ['T4-S1', 'T4-S3'],
  },
  't4-c2': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each term to its description.',
    pairs: [
      { left: 'MS DOS', right: 'Early OS with a text-based interface; commands are typed at the command prompt' },
      { left: 'WIMP', right: 'Windows, Icons, Mouse control and Pull-down menus' },
      { left: 'Touch screen', right: 'Lets a stylus or finger pressure replace the pointing device' },
      { left: 'Kernel', right: 'Core of the operating system that is loaded when the computer is turned on' },
      { left: 'Linux', right: 'Today provides both a GUI and a text interface' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'One is an acronym for the parts of a GUI; one is the part of the OS that loads first.',
    explanation: 'Early systems like MS DOS used a command line, while most modern systems use a WIMP GUI, often with touch input. Linux offers both kinds of interface.',
    skills: ['T4-S2', 'T4-S1'],
  },
  't4-c3': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: Linux today offers only a graphical user interface, because text-based command lines disappeared with MS DOS.',
    answer: false,
    hint: 'The textbook mentions one modern OS that still gives you a choice.',
    explanation: 'False. Linux today provides both a GUI and a text interface, so command lines are still in use.',
    skills: ['T4-S2'],
  },
  't4-c4': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'The OS controls all the activities in the computer. Match each resource management task to what the OS does.',
    pairs: [
      { left: 'Input and Output (I/O)', right: 'Helps the user use the monitor, keyboard and mouse by hiding how these devices work' },
      { left: 'File management', right: 'Lets users create, save, delete, move and copy files on secondary storage' },
      { left: 'Memory management', right: 'Gives each loaded program enough memory and stops two programs using the same space' },
      { left: 'Process management', right: 'Makes sure each program in memory gets enough CPU time to run' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'A program in memory is called a process.',
    explanation: 'The OS manages I/O, files, memory and processes. A process is simply a program in memory, and the OS shares CPU time between all the processes that are running.',
    skills: ['T4-S3'],
  },
  't4-c5': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Angelo prints an essay from his word processor. Put the steps in the order they happen.',
    items: [
      'The driver translates the document into a format the printer can understand',
      'Angelo clicks Print in the word processing application',
      'The printer prints the page',
      'The word processing program communicates with the operating system',
      'The operating system sends the file to the driver',
    ],
    answer: [1, 3, 4, 0, 2],
    hint: 'Applications never talk to hardware directly: application, then OS, then driver, then hardware.',
    explanation: 'The application talks to the OS, the OS passes the file to the driver, and the driver translates it for the printer. This chain is how every application reaches hardware.',
    skills: ['T4-S4'],
  },
  't4-c6': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'After printing a word processing document, Angelo prints a spreadsheet on the same printer. Which driver is used?',
    options: [
      'A new spreadsheet printer driver must be installed first',
      'No driver: the spreadsheet program talks directly to the printer',
      'The same printer driver is used for both applications',
      'The operating system swaps in a different driver for each application',
    ],
    answer: 2,
    hint: 'A driver belongs to the device, not to the application.',
    explanation: 'The driver links the hardware device to the software, so any application that prints to that printer uses the same driver.',
    skills: ['T4-S4'],
  },
  't4-c7': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Fill in the missing files. Type the full file name, for example Hello.txt. For the last row, type the 3-letter abbreviation in capitals.',
    code: 'Language   Source code file   Executable file\nJava       Hello.java         ?\nDelphi     ?                  Hello.exe',
    rows: [
      { label: 'Java executable file name', answer: 'Hello.class' },
      { label: 'Delphi source code file name', answer: 'Hello.pas' },
      { label: 'Needed to run the Java file in Windows', answer: 'JRE' },
    ],
    hint: 'Delphi source files end in .pas. Java compiles to a file named after a class.',
    explanation: 'Source code (.java, .pas) is compiled to a separate executable file (.class, .exe). Windows runs .exe files directly, but a .class file needs a Java Runtime Environment (JRE).',
    skills: ['T4-S5'],
  },
  't4-c8': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which description best fits an IDE such as NetBeans?',
    options: [
      'A source code editor plus a compiler or interpreter, with add-ons that make developing applications easier',
      'A utility that rearranges fragmented files on a mechanical hard disk',
      'A driver that links the keyboard and mouse to the operating system',
      'A licence manager that stops the software from being pirated',
    ],
    answer: 0,
    hint: 'IDE stands for Integrated Development Environment. What do you need to write and build code?',
    explanation: 'An IDE is a programming tool made up of a source code editor and a compiler or interpreter with add-ons. NetBeans supports Java, PHP, C/C++ and more.',
    skills: ['T4-S5'],
  },
  't4-c9': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Cross-platform mobile development tools such as Codename One and PhoneGap support WORA. What does WORA mean?',
    options: [
      'Work offline, run always: apps run without the Internet',
      'Write once, read always: the source code can never be changed',
      'Windows only, run anywhere: apps run only on Windows Phone',
      'Write once, run anywhere: code written once runs on multiple platforms',
    ],
    answer: 3,
    hint: 'The point of these tools is to save the developer time across Android, iOS and others.',
    explanation: 'WORA means write once, run anywhere. The developer writes code once on one platform and runs it on multiple platforms, saving time and effort.',
    skills: ['T4-S5'],
  },
  't4-c10': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'What does a Disk Defragmenter utility do?',
    options: [
      'Compresses files so that they take up less storage space',
      'Rearranges fragmented data on a mechanical hard disk so the disk works more efficiently',
      'Deletes viruses that are hiding inside fragmented files',
      'Copies files to a separate location in case of data loss',
    ],
    answer: 1,
    hint: 'Fragmented means the pieces of a file are scattered over the disk.',
    explanation: 'A Disk Defragmenter rearranges fragmented data on a mechanical hard disk. It can take minutes to hours, and flash drives and SSDs do not need it because they have no moving parts.',
    skills: ['T4-S6'],
  },
  't4-c11': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each licensing model to its description.',
    pairs: [
      { left: 'Proprietary licence', right: 'No free copying or distribution, uses product keys and gives no access to the source code' },
      { left: 'GNU General Public License (copyleft)', right: 'You may change and redistribute the software but must include the source code' },
      { left: 'Creative Commons licence', right: 'You keep the copyright; others may copy and distribute your work if they acknowledge you' },
      { left: 'Freeware', right: 'Copyrighted and free to use, but not to resell, and the source code is not given' },
      { left: 'Freemium', right: 'Limited functions are free; a paid licence key unlocks advanced features' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Copyleft licences share source code; freeware and freemium do not.',
    explanation: 'Proprietary licences restrict copying and hide source code, copyleft licences such as the GNU GPL share it, and Creative Commons, freeware and freemium each allow free use in their own limited way.',
    skills: ['T4-S7'],
  },
  't4-c12': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Angelo\'s school buys ONE copy of a Microsoft package under its EULA and wants it on all 30 lab computers. What does the proprietary licence allow?',
    options: [
      'It may go on all 30 computers because the school owns the software',
      'It may go on 30 computers as long as the source code is included',
      'It may only go on more than one machine with a multiple licence agreement',
      'It may be copied freely as long as Microsoft is acknowledged',
    ],
    answer: 2,
    hint: 'When you buy proprietary software, what are you really buying?',
    explanation: 'Buying proprietary software buys the rights to use it as described in the EULA. One purchase does not allow installing on more than one machine without a multiple licence agreement.',
    skills: ['T4-S7'],
  },
  't4-c13': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Study Angelo\'s folder tree (sub-folders are indented below their parent). Type the path with backslashes, for example C:\\Folder\\file.txt. For yes/no rows type yes or no.',
    code: 'C:\n  Users\n    Angelo\n      Documents\n        IT\n          LU4notes.docx\n      Pictures',
    rows: [
      { label: 'Parent folder of IT', answer: 'Documents' },
      { label: 'Full path of LU4notes.docx', answer: 'C:\\Users\\Angelo\\Documents\\IT\\LU4notes.docx' },
      { label: 'Is Pictures a sub-folder of Documents?', answer: 'no' },
    ],
    hint: 'The path is drive\\folder\\folder... down to the file. Folders at the same indentation are not sub-folders of each other.',
    explanation: 'The drive is the highest level, followed by folders and sub-folders, and the drive\\folder\\folder address is the path. Pictures and Documents share the same indentation, so both are sub-folders of Angelo.',
    skills: ['T4-S8'],
  },
  't4-c14': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Thandi\'s logon takes a very long time. Her desktop holds a huge video folder and dozens of large files. What is the most likely cause?',
    options: [
      'The profile loads the desktop early, so large files and folders on it slow the logon',
      'Her firewall is blocking the logon until it scans every file',
      'Her keyboard driver is out of date',
      'Having too many shortcuts on the desktop slows the logon',
    ],
    answer: 0,
    hint: 'What is one of the first things a user profile loads?',
    explanation: 'One of the first things a profile loads is the desktop, so large files and folders there make the logon much slower. Keep only shortcuts on the desktop and store files elsewhere in your profile.',
    skills: ['T4-S8'],
  },
  't4-c15': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: Cloud storage is data stored remotely (off your computer) that is accessed through the Internet.',
    answer: true,
    hint: 'Compare remote with local.',
    explanation: 'True. Cloud storage is stored remotely as opposed to locally, and apps such as iCloud and Dropbox let local folders synchronise with it over the Internet.',
    skills: ['T4-S9'],
  },
  't4-c16': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Using the dropdown on the edit option, which permissions can the owner of a shared Google Drive folder give?',
    options: [
      'Full Control, Modify and Read & Execute',
      'Organise, add & edit, or view only',
      'Read, Write and Delete',
      'Administrator, Guest and Public',
    ],
    answer: 1,
    hint: 'The first option is from the Windows Sharing tab on a local computer, not the cloud.',
    explanation: 'In Google Drive the owner adds users by email address and gives them organise, add & edit or view only. Full Control, Modify and Read & Execute are local Windows permissions.',
    skills: ['T4-S9'],
  },
  't4-c17': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'The textbook compressed a folder called Bingo. Work out the results. Give the space saved to 3 decimal places and the percentage as a whole number without the % sign.',
    code: 'Folder: Bingo\nOriginal size:   9.61 MB\nCompressed size: 4.363 MB',
    rows: [
      { label: 'Space saved in MB', answer: '5.247' },
      { label: 'Compressed size as a percentage of the original', answer: '45' },
    ],
    hint: 'Saved = original - compressed. Percentage = compressed / original x 100, then round.',
    explanation: '9.610 - 4.363 = 5.247 MB saved, and 4.363 / 9.61 x 100 is about 45.4%, which rounds to 45. Smaller files use less storage and less bandwidth when sent over the Internet.',
    skills: ['T4-S10'],
  },
  't4-c18': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: In Windows, right-clicking a folder and using Send To can create a single compressed file of the whole folder that can be emailed as one attachment.',
    answer: true,
    hint: 'This is exactly what Activity 1 asks you to try.',
    explanation: 'True. Send To creates one compressed file of the entire folder, much smaller than the original. All compression utilities also include a decompression utility to extract it again.',
    skills: ['T4-S10'],
  },
  't4-c19': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which statement correctly distinguishes archiving from backup?',
    options: [
      'Archiving copies files in case of data loss; backup removes old files to save space',
      'Both delete the original files and always store them in the cloud',
      'Archiving removes rarely used files to a compressed separate location; backup copies files to a separate location in case of data loss',
      'Archiving is only for email folders; backup is only for operating systems',
    ],
    answer: 2,
    hint: 'One frees up space for files you seldom use; the other protects you if your storage fails.',
    explanation: 'An archive removes files that are seldom used and stores them, compressed, in a separate location to save space. A backup is a copy kept in a separate location in case of damage, space problems or corruption.',
    skills: ['T4-S10'],
  },
  't4-c20': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each installation term to its meaning.',
    pairs: [
      { left: 'Typical/standard installation', right: 'Installs only the standard features of the package' },
      { left: 'Custom installation', right: 'Lets you adapt the way the software is installed and change settings' },
      { left: 'Full installation', right: 'Installs all features and takes up the most space' },
      { left: 'Product (activation) key', right: 'Unique code showing the software was bought legally and is licensed to you' },
      { left: 'Uninstall program', right: 'Removes all files, folders and icons of a program and updates the registry' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Think about which option gives you the most control and which uses the most space.',
    explanation: 'Typical, custom and full installations differ in features and space. Licensed software needs a product key to activate it, and uninstall programs safely remove every part and update the registry.',
    skills: ['T4-S11', 'T4-S7'],
  },
  't4-c21': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Angelo connects a new USB device to a modern computer. Put the plug and play steps in order.',
    items: [
      'The driver program is installed and the settings for the device are stored',
      'Angelo plugs the device into a USB port',
      'The OS leads the user through a series of steps, or needs no input at all',
      'The plug and play feature detects the new hardware',
    ],
    answer: [1, 3, 2, 0],
    hint: 'Detection happens as soon as the device is connected.',
    explanation: 'Plug and play detects new hardware as soon as it is connected, guides the user if needed, then installs the driver and stores the settings. Most USB devices are hot swappable, so no restart is needed.',
    skills: ['T4-S4', 'T4-S11'],
  },
  't4-c22': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Angelo wants his planned backup to run automatically every Friday at 17:00. Which utility should he use?',
    options: [
      'Disk Defragmenter',
      'File Explorer',
      'Programs and Features',
      'Task Scheduler',
    ],
    answer: 3,
    hint: 'Activity 2 asks you to find this utility.',
    explanation: 'A task scheduler runs programs automatically at specified times with specified conditions, for example a backup at shut down or at a set time.',
    skills: ['T4-S11', 'T4-S10'],
  },
  't4-c23': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each security term to its description.',
    pairs: [
      { left: 'Virus', right: 'Illegally loaded program that damages the system and spreads by infecting files or attaching to emails' },
      { left: 'Spyware', right: 'Installed secretly to intercept the user\'s interaction without informed consent' },
      { left: 'Adware', right: 'Usually benign software that shows unwanted pop-ups and can slow the computer' },
      { left: 'Firewall', right: 'Permits or denies network transmissions based on a set of rules' },
      { left: 'Signature', right: 'Identifying piece of code in a virus that anti-virus software searches for' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Three are kinds of malware; two help protect you.',
    explanation: 'Viruses, spyware and adware are malware. A firewall filters network traffic, and anti-virus software finds viruses by their signatures.',
    skills: ['T4-S12'],
  },
  't4-c24': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'A criminal records every key a victim presses, receives the data over the Internet and uses it to log in to the victim\'s bank account. What malware was used?',
    options: [
      'Adware that shows pop-up adverts',
      'Spyware, in the form of a keystroke-logging program',
      'A virus that only modifies itself to avoid detection',
      'A cookie stored by the Internet browser',
    ],
    answer: 1,
    hint: 'The program secretly watches what the user types.',
    explanation: 'A keystroke logger is a form of spyware. It records each keystroke and sends it to the criminal, who rebuilds the login data and passwords.',
    skills: ['T4-S12'],
  },
  't4-c25': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: Once anti-virus software is installed it never needs updating, because virus signatures do not change.',
    answer: false,
    hint: 'Viruses keep getting more complex and harder to trace.',
    explanation: 'False. Anti-virus software must be continuously updated, usually by downloading the signature database from the Internet, so it can recognise new viruses and delete or quarantine them.',
    skills: ['T4-S12'],
  },
  't4-c26': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Angelo lists the programs on his PC. Which group is made up ONLY of system software?',
    options: [
      'Operating system, utilities, compilers and drivers',
      'Word processor, spreadsheet, drivers and games',
      'Web browser, operating system, email and photo editor',
      'Utilities, photo editor, word processor and compilers',
    ],
    answer: 0,
    hint: 'System software looks after the computer itself rather than doing a user task.',
    explanation: 'System software consists of the operating system, utilities, compilers and drivers. Word processors, spreadsheets, browsers and photo editors are application programs.',
    skills: ['T4-S1', 'T4-S6'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Understand the software that runs, manages, maintains and protects a computer so that application programs can do their work.',
  outcomes: [
    'By the end you can name the parts of system software and the three main functions of an operating system.',
    'By the end you can distinguish a command line interface from a GUI and explain how the OS manages resources.',
    'By the end you can explain what a device driver does and how new devices are added.',
    'By the end you can describe programming tools and distinguish source code from executable code.',
    'By the end you can explain the purpose of utilities such as the Disk Defragmenter.',
    'By the end you can compare proprietary, open source, Creative Commons, freeware and freemium licences.',
    'By the end you can manage profiles, the desktop, folders, cloud storage and sharing permissions.',
    'By the end you can compress files and distinguish an archive from a backup.',
    'By the end you can install, uninstall, schedule and update software.',
    'By the end you can explain firewalls, malware and anti-virus software.',
  ],
  topics: [
    {
      id: 'T4-T1',
      title: 'Operating Systems and the User Interface',
      sections: ['4', '4.1', '4.1.1', '4.1.1.1', '4.1.1.2', '4.1.1.3'],
      skills: ['T4-S1', 'T4-S2', 'T4-S3'],
      explanation: [
        'System software consists of the operating system, utilities, compilers and drivers. The operating system is a large part of it and usually provides management and housekeeping tools that let a user, normally with administrative permissions, configure the computer to run efficiently.',
        'Every computer needs an operating system installed and running on it. The kernel is loaded when the computer is turned on.',
        'Every OS has three main functions: provide a user interface, load and run programs, and manage the computer\'s resources.',
        'Early operating systems such as MS DOS used a text-based command line interface, where commands are typed at the command prompt. Most operating systems now provide a Graphical User Interface (GUI) with Windows, Icons, Mouse control and Pull-down menus (WIMP). Touch screens let a stylus or finger pressure replace the pointing device. Linux provides both a GUI and a text interface.',
        'The OS loads, runs and controls application programs, and manages resources such as the CPU, RAM, monitor, storage devices, keyboard, mouse and printer.',
        'Resource management covers Input and Output (hiding how devices work), file management (create, save, delete, move and copy files on secondary storage), memory management (each program gets enough memory and no two programs use the same space) and process management (each process, a program in memory, gets enough CPU time).',
      ],
      vocabulary: [
        { term: 'System software', definition: 'The operating system, utilities, compilers and drivers.' },
        { term: 'Kernel', definition: 'The core of the operating system that is loaded when the computer is turned on.' },
        { term: 'Command line interface', definition: 'A text-based interface where commands are typed at the command prompt, as in MS DOS.' },
        { term: 'GUI / WIMP', definition: 'Graphical User Interface with Windows, Icons, Mouse control and Pull-down menus.' },
        { term: 'Process', definition: 'In simple terms, a program in memory.' },
      ],
      workedExamples: [
        {
          code: 'Angelo has a browser, music player and NetBeans open.\nMemory management : each gets its own memory space\nProcess management: each gets enough CPU time\nI/O               : keyboard and mouse work without him knowing how',
          explanation: 'Several programs can be loaded and running at the same time, so the OS must share memory and CPU time fairly between the processes.',
        },
      ],
      misconceptions: [
        'Thinking a GUI is the only kind of interface today. Linux still offers a text interface alongside its GUI.',
        'Thinking application programs control the hardware directly. The OS controls all activities in the computer and hides the details of how devices work.',
      ],
      questions: [
        {
          id: 'T4-T1-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'What does a command line interface require the user to do?',
          options: [
            'Click icons and pull-down menus with a mouse',
            'Type text commands at a command prompt',
            'Touch the screen with a stylus or finger',
            'Drag windows around the desktop',
          ],
          answer: 1,
          hint: 'MS DOS was a text-based interface.',
          explanation: 'A command line interface is text-based: the user types commands at the command prompt. Icons, menus and touch belong to a GUI.',
          skills: ['T4-S2'],
        },
        {
          id: 'T4-T1-Q2',
          type: 'mc',
          category: 'classify',
          prompt: 'The OS makes sure that no two loaded programs use the same memory space. Which part of resource management is this?',
          options: ['Process management', 'File management', 'Input and Output', 'Memory management'],
          answer: 3,
          hint: 'It is about RAM, not CPU time.',
          explanation: 'Memory management gives each program enough memory and keeps programs out of each other\'s memory space. Process management is about sharing CPU time.',
          skills: ['T4-S3'],
        },
        {
          id: 'T4-T1-Q3',
          type: 'mc',
          category: 'classify',
          prompt: 'Check Point 1 asks you to look up the latest versions of several operating systems. Which of these is NOT an operating system?',
          options: ['Android', 'WinZip', 'Linux', 'iOS'],
          answer: 1,
          hint: 'One of these shrinks files.',
          explanation: 'WinZip is a compression utility. Android, Linux and iOS (like Windows and macOS) are operating systems.',
          skills: ['T4-S1'],
        },
      ],
    },
    {
      id: 'T4-T2',
      title: 'Device Drivers',
      sections: ['4.1.2'],
      skills: ['T4-S4'],
      explanation: [
        'The operating system uses device drivers to link a hardware device to the software, so the computer can perform its tasks when applications send instructions to that device.',
        'Every device connected to a computer has a small, specific program called a driver that gives the operating system the information it needs to work with that device.',
        'There can be more than one driver for a device, but the more up to date the driver is, the better the device will work.',
        'A user can interact with an application, or directly with the OS or utilities (for example through the Control Panel and Task Manager). An application talks to the OS, the OS talks to the driver and the driver talks to the hardware.',
        'When printing, the OS sends the file to the printer driver, which translates it into a format the printer understands. Any application printing to that printer uses the same driver.',
      ],
      vocabulary: [
        { term: 'Device driver', definition: 'A small, specific program that provides the operating system with the information needed to work with a device.' },
        { term: 'Control Panel', definition: 'A system program that lets the user manage and control the operating system and utilities.' },
        { term: 'Task Manager', definition: 'A program that lets the user manage and control the operating system and utilities.' },
      ],
      workedExamples: [
        {
          code: 'User -> Application -> Operating system -> Driver -> Hardware\nWord processor --\\\n                  > OS -> printer driver -> printer\nSpreadsheet ----/',
          explanation: 'Different applications share one driver for the same printer, because the driver belongs to the device.',
        },
      ],
      misconceptions: [
        'Thinking each application needs its own driver for a device. The same printer driver is used by the word processor and the spreadsheet.',
        'Thinking any old driver works just as well. The more up to date the driver, the better the device works.',
      ],
      questions: [
        {
          id: 'T4-T2-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'What is a device driver?',
          options: [
            'A small, specific program that gives the OS the information it needs to work with a device',
            'The port on the computer that a device plugs into',
            'A utility that runs tasks at specified times',
            'A chip inside the device that stores its settings permanently',
          ],
          answer: 0,
          hint: 'A driver is software, not hardware.',
          explanation: 'Every connected device has a driver: a small, specific program that links the device to the software via the operating system.',
          skills: ['T4-S4'],
        },
        {
          id: 'T4-T2-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: There can be more than one driver for a device, and a more up-to-date driver usually makes the device work better.',
          answer: true,
          hint: 'Think about why drivers are downloaded from the Internet.',
          explanation: 'True. More than one driver can be used with a device, but the more up to date it is, the better the device works.',
          skills: ['T4-S4'],
        },
      ],
    },
    {
      id: 'T4-T3',
      title: 'Programming Tools and Related Applications',
      sections: ['4.1.3', '4.1.3.1'],
      skills: ['T4-S5'],
      explanation: [
        'A programming tool is any computer program that can be used to create programs that work on their own, support other programs or interact with the resources on a device.',
        'The IDE (Integrated Development Environment) you use in your programming course is a programming tool. Most IDEs consist of a source code editor and a compiler or interpreter with add-ons. NetBeans supports Java desktop, mobile and web applications, PHP, C/C++ and more.',
        'Game development applications such as Unity let developers create 2D and 3D games for platforms such as Android, iOS and Windows Phone, with tutorials for new developers.',
        'Cross-platform mobile development tools such as Codename One and PhoneGap support write once, run anywhere (WORA): code written once runs on multiple platforms.',
        'Source code is the original code written by the programmer (.pas in Delphi, .java in Java). It is compiled to a separate file called object code, the executable code (.exe in Delphi, .class in Java). Windows can execute .exe files, but a .class file needs a Java Runtime Environment (JRE).',
      ],
      vocabulary: [
        { term: 'Programming tool', definition: 'Any computer program used to create programs, support other programs or interact with the resources on a device.' },
        { term: 'IDE', definition: 'Integrated Development Environment: a source code editor and a compiler or interpreter with add-ons.' },
        { term: 'WORA', definition: 'Write once, run anywhere: code written once on one platform runs on multiple platforms.' },
        { term: 'Source code', definition: 'The original code written by the programmer.' },
        { term: 'Executable code', definition: 'The separate object code file produced by compiling the source code.' },
      ],
      workedExamples: [
        {
          code: 'Hello.java  --compile-->  Hello.class  (needs a JRE to run)\nHello.pas   --compile-->  Hello.exe    (runs directly in Windows)',
          explanation: 'The compiler turns the programmer\'s source code into a separate executable file.',
        },
      ],
      misconceptions: [
        'Thinking source code and executable code are the same file. Compiling creates a separate object code file.',
        'Thinking a .class file runs in Windows like an .exe. It needs a Java Runtime Environment installed.',
      ],
      questions: [
        {
          id: 'T4-T3-Q1',
          type: 'mc',
          category: 'distinguish',
          prompt: 'Which statement correctly distinguishes source code from executable code?',
          options: [
            'Source code is the .exe file; executable code is the .pas file',
            'Source code runs directly in Windows; executable code must still be compiled',
            'Source code is the original code written by the programmer; it is compiled to a separate executable file',
            'Source code and executable code are the same file saved under two names',
          ],
          answer: 2,
          hint: 'Which one does the programmer type?',
          explanation: 'The programmer writes source code (.java, .pas), which is compiled to a separate object code file, the executable code (.class, .exe).',
          skills: ['T4-S5'],
        },
        {
          id: 'T4-T3-Q2',
          type: 'mc',
          category: 'identify',
          prompt: 'Which tool from the textbook lets developers create 2D and 3D games for Android, iOS and Windows Phone?',
          options: ['7-Zip', 'Task Scheduler', 'Dropbox', 'Unity'],
          answer: 3,
          hint: 'It is a game development application with detailed tutorials.',
          explanation: 'Unity is a game development application for 2D and 3D games on multiple platforms. 7-Zip is a compression utility, Task Scheduler a system utility and Dropbox cloud storage.',
          skills: ['T4-S5'],
        },
      ],
    },
    {
      id: 'T4-T4',
      title: 'Utilities and Defragmentation',
      sections: ['4.1.4', '4.1.4.1'],
      skills: ['T4-S6'],
      explanation: [
        'System software provides many utilities to help a user manage, analyse, maintain, optimise and control the computer. Many of them are found in the Control Panel, a program that is part of the system software.',
        'Utilities covered in this unit: defragmentation, scheduling tasks, updating, file compression and extraction, archive, backup, installing and uninstalling software, and security (firewall and anti-malware).',
        'A Disk Defragmenter rearranges fragmented data on a mechanical hard disk so the disk can work more efficiently. It may take several minutes to a few hours, depending on the size of the disk and how fragmented it is.',
        'Defragmentation may be impossible if there is not enough space to create a copy of the files being rearranged.',
        'Flash drives and solid-state drives do not need to be defragmented because they have no moving parts; their loading and saving speed is not compromised.',
      ],
      vocabulary: [
        { term: 'Utility', definition: 'System software that helps the user manage, analyse, maintain, optimise and control the computer.' },
        { term: 'Disk Defragmenter', definition: 'A utility that rearranges fragmented data on a mechanical hard disk so the disk works more efficiently.' },
      ],
      workedExamples: [],
      misconceptions: [
        'Thinking every drive should be defragmented. Flash drives and SSDs have no moving parts and do not need it.',
        'Thinking utilities are application programs. They look after the computer itself, which is why they are part of system software.',
      ],
      questions: [
        {
          id: 'T4-T4-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'Why are utilities such as a Disk Defragmenter considered system software and not application programs?',
          options: [
            'They are always free of charge',
            'They can only be run from a command line',
            'They help the user manage, analyse, maintain, optimise and control the computer itself',
            'They are built into every word processor',
          ],
          answer: 2,
          hint: 'Ask what the program looks after: a user task, or the computer?',
          explanation: 'Utilities exist to manage and maintain the computer itself, not to do a user task such as writing an essay, so they belong to system software.',
          skills: ['T4-S6'],
        },
        {
          id: 'T4-T4-Q2',
          type: 'tf',
          category: 'apply',
          prompt: 'True or false: Angelo\'s new laptop has a solid-state drive, so he should defragment it every week to keep it fast.',
          answer: false,
          hint: 'Fragmentation slows down disks with moving parts.',
          explanation: 'False. Solid-state drives and flash drives have no moving parts and do not need defragmentation.',
          skills: ['T4-S6'],
        },
      ],
    },
    {
      id: 'T4-T5',
      title: 'Software Distribution and Licensing Models',
      sections: ['4.2', '4.2.1', '4.2.2', '4.2.2.1', '4.2.2.2', '4.2.2.3'],
      skills: ['T4-S7'],
      explanation: [
        'A software licence legally describes how software can be used and copied and protects its copyright; copyright laws establish that the authors own the software. A licence manager program can enforce the licence terms to protect the vendor from piracy, the illegal copying of software.',
        'Licences fall into two main types: proprietary, and free and open source.',
        'A proprietary licence does not allow the software to be freely distributed or copied, usually enforced with product or activation keys, and gives no access to the source code. You buy the rights to use the software as described in an End User Licence Agreement (EULA). Microsoft uses this model; one purchase does not cover more than one machine without a multiple licence agreement.',
        'Free and open source licences share the source code and are called copyleft licences. The GNU General Public License lets users change, modify and redistribute the software, but they must include the source code so others can use the improvements. Linux is a typical example.',
        'Creative Commons: you keep the copyright but others may copy and distribute your work if they acknowledge you, a response to collaboration on the Internet and Web 2.0.',
        'Freeware is copyrighted but given away free to use, not to resell; you cannot alter it because you do not get the source code. Freemium is a variant of freeware: limited functions are free, and a paid licence key unlocks advanced features.',
      ],
      vocabulary: [
        { term: 'Software licence', definition: 'Legally describes how software can be used and copied; protects its copyright.' },
        { term: 'Piracy', definition: 'The illegal copying of software.' },
        { term: 'EULA', definition: 'End User Licence Agreement describing your rights to use proprietary software.' },
        { term: 'Copyleft', definition: 'Open source licences that share the source code, such as the GNU General Public License.' },
        { term: 'Freemium', definition: 'A variant of freeware where limited functions are free and advanced features cost money.' },
      ],
      workedExamples: [
        {
          code: 'Licence           Source code?  Cost\nProprietary       No            Paid (product key)\nGNU GPL           Yes           Free to change and share\nFreeware          No            Free, may not resell\nFreemium          No            Basic free, pay to unlock',
          explanation: 'A quick comparison of who gets the source code and what it costs.',
        },
      ],
      misconceptions: [
        'Thinking freeware means you may change the program. The author keeps the copyright and you get no source code.',
        'Thinking buying a box of software lets you install it on every computer you own. A proprietary licence usually allows one machine unless you have a multiple licence agreement.',
      ],
      questions: [
        {
          id: 'T4-T5-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'A licence manager program protects the software vendor from piracy. What is piracy?',
          options: [
            'The illegal copying of software',
            'Downloading updates from the vendor site',
            'Sharing the source code under a copyleft licence',
            'Installing software with a custom installation',
          ],
          answer: 0,
          hint: 'It breaks the copyright of the software.',
          explanation: 'Piracy is the illegal copying of software. Licences and licence managers exist to protect the author\'s copyright against it.',
          skills: ['T4-S7'],
        },
        {
          id: 'T4-T5-Q2',
          type: 'mc',
          category: 'distinguish',
          prompt: 'How does a Creative Commons licence differ from freeware?',
          options: [
            'Creative Commons work always costs money; freeware never does',
            'Creative Commons hides the source code; freeware always includes it',
            'There is no difference; both are proprietary licences',
            'Creative Commons lets others copy and distribute your work if they acknowledge you; freeware is free to use but not to resell, without source code',
          ],
          answer: 3,
          hint: 'One is about sharing with acknowledgement; the other is about free use with no resale.',
          explanation: 'With Creative Commons you keep copyright but allow copying and distribution with acknowledgement. Freeware is copyrighted, free to use, may not be resold and comes without source code.',
          skills: ['T4-S7'],
        },
        {
          id: 'T4-T5-Q3',
          type: 'tf',
          category: 'define',
          prompt: 'True or false: Freemium software provides limited functions free, and the user can pay for a licence key that unlocks more advanced features.',
          answer: true,
          hint: 'Free plus premium.',
          explanation: 'True. Freemium is a variant of freeware: the basics are free, and a paid licence key unlocks additional features.',
          skills: ['T4-S7'],
        },
        {
          id: 'T4-T5-Q4',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: Under the GNU General Public License you may modify and redistribute the software, but you must keep the source code secret.',
          answer: false,
          hint: 'Copyleft licences want everyone to benefit from the improvements.',
          explanation: 'False. You must include the source code when you redistribute GPL software, so others can use the improvements.',
          skills: ['T4-S7'],
        },
      ],
    },
    {
      id: 'T4-T6',
      title: 'User Profiles, the Desktop and Folders',
      sections: ['4.3', '4.3.1', '4.3.2', '4.3.2.1', '4.3.3'],
      skills: ['T4-S8'],
      explanation: [
        'On a computer with more than one user, each user has a unique profile with its own Documents folder, Pictures folder, Desktop and more. The user logs on with a username and password and can personalise settings such as the Desktop Theme and shortcuts.',
        'Only an administrator or the user can change a profile; other users have no access to it. Users usually may not perform many Control Panel tasks (such as adding or deleting programs). A Public Profile may hold documents shared by all users.',
        'The desktop is the first window after logon and is linked to the user\'s profile. Programs and folders open on it, and the taskbar at the bottom shows running programs, lets you switch between them and holds the Start button. You can pin applications to the taskbar.',
        'Keep only shortcuts on the desktop: large files and folders slow down logon because the desktop is loaded early, mixed items cause clutter, and desktops may be deleted if the operating system is reinstalled.',
        'A computer uses a hierarchical file structure: the drive is the highest level, then folders and sub-folders, with files inside folders. The drive\\folder\\folder address is the path. File Explorer is the GUI utility for viewing, editing, saving and deleting files and folders.',
        'Sub-folders are indented below their parent; folders at the same indentation are not sub-folders of one another. Two files or folders cannot have the same name in the same folder; most operating systems warn you and offer to create a copy with a different name.',
      ],
      vocabulary: [
        { term: 'User profile', definition: 'A user\'s own set of folders (Documents, Pictures, Desktop) and settings, opened with a username and password.' },
        { term: 'Desktop', definition: 'The first window that appears after a user logs on; a surface for your work.' },
        { term: 'Taskbar', definition: 'Bar at the bottom of the desktop showing running programs and holding the Start button.' },
        { term: 'Path', definition: 'The drive\\folder\\folder address of a file.' },
        { term: 'File Explorer', definition: 'GUI utility to view, edit, save and delete folders and files.' },
      ],
      workedExamples: [
        {
          code: 'C:\\Users\\Angelo\\Documents\\IT\\LU4notes.docx\n\nDrive  : C:\nFolders: Users > Angelo > Documents > IT\nFile   : LU4notes.docx',
          explanation: 'A path lists the drive, then each folder down the hierarchy, then the file.',
        },
      ],
      misconceptions: [
        'Thinking the desktop is a safe, fast place to keep work. Large files slow logon and may be lost if the OS is reinstalled.',
        'Thinking any user can open another user\'s profile. Only the user or an administrator can.',
      ],
      questions: [
        {
          id: 'T4-T6-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'Why does each user who logs onto the same computer see a different desktop?',
          options: [
            'The monitor changes its resolution for each user',
            'The operating system picks a random theme at each logon',
            'The desktop is a folder linked to each user\'s own profile',
            'The administrator redesigns the desktop every morning',
          ],
          answer: 2,
          hint: 'Each profile has its own Documents, Pictures and ...',
          explanation: 'The desktop is one of the folders linked to a particular user profile, so each user sees their own files, shortcuts and theme.',
          skills: ['T4-S8'],
        },
        {
          id: 'T4-T6-Q2',
          type: 'order',
          category: 'sequence',
          prompt: 'Order the levels of the file hierarchy from highest to lowest.',
          items: ['Sub-folder', 'File', 'Drive', 'Folder'],
          answer: [2, 3, 0, 1],
          hint: 'The highest level is the physical hard drive.',
          explanation: 'The drive is the highest level; it holds folders, which hold sub-folders, and files live inside these folders.',
          skills: ['T4-S8'],
        },
        {
          id: 'T4-T6-Q3',
          type: 'tf',
          category: 'predict',
          prompt: 'True or false: If Angelo saves a second file called Essay.docx into a folder that already has Essay.docx, both files will simply exist side by side with the same name.',
          answer: false,
          hint: 'How would the computer tell them apart?',
          explanation: 'False. Files and folders may not share a name in the same folder; the OS warns the user and offers to create a copy with a different name.',
          skills: ['T4-S8'],
        },
      ],
    },
    {
      id: 'T4-T7',
      title: 'Cloud-Based Storage, Sharing and Permissions',
      sections: ['4.3.3.1', '4.3.3.2'],
      skills: ['T4-S9'],
      explanation: [
        'Cloud-based storage must be managed like other storage because it is an extension of your secondary storage. Cloud storage is data stored remotely (off your computer) as opposed to locally (on your computer), and it is accessible through the Internet.',
        'Applications such as Google File Stream, iCloud and Dropbox let folders on your computer synchronise with cloud storage. Some make local copies and others do not (Google File Stream does not). You can have several cloud storage areas if you install the relevant software, and each can be treated as a folder on local storage.',
        'On a local computer, access is controlled by the default profile settings and the administrator. Sharing and permissions can be set on multi-user computers or on servers on a network.',
        'To share a local folder, right-click it, choose Properties, open the Sharing tab and click Share. Permissions range from Full Control, Modify, Read & Execute, List folder contents, Read and Write.',
        'In Google Drive, the person who creates a shared folder is the owner and adds users by email address, then uses the dropdown on the edit option to give permissions such as organise, add & edit, or view only.',
      ],
      vocabulary: [
        { term: 'Cloud storage', definition: 'Data stored remotely (off your computer), accessible through the Internet.' },
        { term: 'Synchronise', definition: 'Keep folders on your computer and in cloud storage up to date with each other.' },
        { term: 'Permissions', definition: 'Rules for what each user may do with a shared file or folder, such as Read or Full Control.' },
      ],
      workedExamples: [
        {
          code: 'Local (Windows Sharing tab): Full Control, Modify, Read & Execute,\n                             List folder contents, Read, Write\nCloud (Google Drive owner) : organise, add & edit, view only',
          explanation: 'Both local and cloud storage let you control who can do what with shared files.',
        },
      ],
      misconceptions: [
        'Thinking all cloud apps keep a copy of every file on your computer. Some do and some, like Google File Stream, do not.',
        'Thinking shared cloud files must still be emailed as attachments. With correct permissions users already have shared access.',
      ],
      questions: [
        {
          id: 'T4-T7-Q1',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: Google File Stream always makes a local copy of every file in your cloud storage.',
          answer: false,
          hint: 'The textbook says some synchronising apps make copies and others do not.',
          explanation: 'False. Some apps make local copies, but Google File Stream does not.',
          skills: ['T4-S9'],
        },
        {
          id: 'T4-T7-Q2',
          type: 'mc',
          category: 'apply',
          prompt: 'How does a Windows user give other users access to a local folder called Creative?',
          options: [
            'Right-click the folder, choose Properties, open the Sharing tab and click Share',
            'Compress the folder and save it on the desktop',
            'Run the Disk Defragmenter on the folder',
            'Rename the folder to Public',
          ],
          answer: 0,
          hint: 'Look in the folder\'s Properties.',
          explanation: 'The Sharing tab in Properties has a Share button that shows which users or groups have access and their permissions.',
          skills: ['T4-S9'],
        },
        {
          id: 'T4-T7-Q3',
          type: 'mc',
          category: 'explain',
          prompt: 'Cloud storage is accessed through the Internet. Which of these is therefore a disadvantage of cloud-based storage?',
          options: [
            'Cloud files can never be shared with other users',
            'Each user may only have one cloud storage area',
            'Cloud storage cannot appear as a folder on your computer',
            'Without an Internet connection you cannot reach files stored only in the cloud',
          ],
          answer: 3,
          hint: 'Three of these are contradicted by the textbook.',
          explanation: 'Because cloud storage is remote, you need the Internet to reach it. Cloud files can be shared, you may have several cloud areas, and they can be treated as local folders.',
          skills: ['T4-S9'],
        },
      ],
    },
    {
      id: 'T4-T8',
      title: 'Compression, Archive and Backup',
      sections: ['4.3.4', '4.3.4.1', '4.3.4.2', '4.3.5', '4.3.5.1', '4.3.5.2'],
      skills: ['T4-S10'],
      explanation: [
        'File compression programs reduce the size of files so they take up less storage space or transfer more quickly over the Internet. Examples are WinZip, 7-Zip and WinRAR, and recent Windows versions have a built-in compression utility. Text files compress well, but images do not allow a high degree of compression.',
        'You can combine several files into one compressed folder and attach one file to an email instead of many, saving bandwidth. With cloud storage and the correct permissions there is no need to compress and email, because users already share access.',
        'All compression utilities contain a decompression utility to extract the compressed file. In Windows, right-click a folder and use Send To to create one compressed file of the whole folder. Google Drive downloads a compressed file automatically when you select download.',
        'Archiving: files that stay unused for long periods waste space but may be needed later. An archiving utility removes them and stores them in a compressed separate archive location.',
        'Backup: a copy of files or folders in a separate location in case of data loss, such as cloud storage, local drives, network drives or external drives. It can include applications or even entire operating systems or drives, and may be a simple copy or use compression.',
        'A backup utility has options for the types of files, how often to back up, whether to overwrite previous backups, a backup schedule and saving the settings. Some operating systems can also restore the system to a previous stable state.',
      ],
      vocabulary: [
        { term: 'Compression', definition: 'Reducing file size so files use less storage space or transfer faster over the Internet.' },
        { term: 'Decompression (extraction)', definition: 'Extracting the original files from a compressed file.' },
        { term: 'Archive', definition: 'Removing seldom-used files and storing them in a compressed separate location for later use.' },
        { term: 'Backup', definition: 'A copy of files or folders kept in a separate location in case of data loss.' },
      ],
      workedExamples: [
        {
          code: 'Folder Bingo: 9.61 MB -> compressed 4.363 MB\nSaved: 9.610 - 4.363 = 5.247 MB\nSize now: 4.363 / 9.61 x 100 = about 45% of the original',
          explanation: 'The textbook\'s example shows compression cutting the folder to less than half its size.',
        },
        {
          code: 'Activity 1\n1. Select a folder and check its size (right-click > Properties)\n2. Right-click > Send To > compressed folder\n3. Check the compressed size and compare',
          explanation: 'A quick practical way to see how much space compression saves.',
        },
      ],
      misconceptions: [
        'Thinking an archive and a backup are the same. An archive moves unused files away to save space; a backup copies files in case of loss.',
        'Thinking every file shrinks by the same amount. Text compresses well; images do not allow a high degree of compression.',
      ],
      questions: [
        {
          id: 'T4-T8-Q1',
          type: 'tf',
          category: 'predict',
          prompt: 'True or false: If Angelo compresses a folder of text files and a folder of photos, the text files are likely to compress more.',
          answer: true,
          hint: 'The textbook compares text and images.',
          explanation: 'True. Text files compress successfully, but images do not allow a high degree of compression.',
          skills: ['T4-S10'],
        },
        {
          id: 'T4-T8-Q2',
          type: 'mc',
          category: 'apply',
          prompt: 'Where should Angelo store his backup files so the backup is reliable?',
          options: [
            'In the same folder as the original files',
            'On the desktop so it loads at every logon',
            'In a separate location, such as an external drive, a network drive or cloud storage',
            'In the Recycle Bin so it is easy to find',
          ],
          answer: 2,
          hint: 'What happens to the backup if the original storage is damaged?',
          explanation: 'A backup is kept in a separate location so it survives if the normal storage becomes unusable through damage, space restrictions or corruption.',
          skills: ['T4-S10'],
        },
        {
          id: 'T4-T8-Q3',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps of Activity 1 in order.',
          items: [
            'Check the size of the compressed file and compare it to the original',
            'Right-click the folder and select Properties to check its size',
            'Right-click the folder, select Send To and choose the compress option',
            'Select a folder on your hard disk',
          ],
          answer: [3, 1, 2, 0],
          hint: 'You need the original size before you compress.',
          explanation: 'Choose a folder, record its size, compress it with Send To, then compare the compressed size with the original.',
          skills: ['T4-S10'],
        },
      ],
    },
    {
      id: 'T4-T9',
      title: 'System Management',
      sections: ['4.4', '4.4.1', '4.4.2', '4.4.3', '4.4.3.1', '4.4.3.2'],
      skills: ['T4-S11', 'T4-S4'],
      explanation: [
        'An installation program installs new software. Operating systems use a registry to record settings and changes during installations. The installer places the executable files, creates folders for supporting software and registers the software in the registry.',
        'A typical/standard installation installs the standard features, a custom installation lets you adapt settings, and a full installation installs all features and uses the most space. Licensed software needs a product key (activation key) proving it was bought legally. Google and Office 365 may license per email address per month with nothing installed.',
        'Uninstall programs safely remove all files, folders and icons and update the registry. In Windows, the Control Panel has a Programs and Features option to uninstall or modify a program.',
        'Drivers once came on CDs, which are often out of date; most are now downloaded from the Internet. Devices such as 3G cards and flash drives carry their own driver. Plug and play detects new hardware as soon as it is connected and installs the driver. A hot swappable device installs without restarting; most USB devices are hot swappable.',
        'A task scheduler runs programs automatically at specified times and conditions, for example a backup at shut down or at a set time (Activity 2: plan a backup and run it with Task Scheduler).',
        'Older Windows systems were updated with service packs on CD; today a scheduled task checks the vendor site for updates over the Internet. You can update automatically or on request. Google apps run on a website, so updates are already done: users cannot refuse them, though they may use the previous version until the update is enforced.',
      ],
      vocabulary: [
        { term: 'Registry', definition: 'Records settings and changes that affect the system when installations take place.' },
        { term: 'Product key (activation key)', definition: 'A unique code that ensures the software was purchased legally and is licensed to you.' },
        { term: 'Plug and play', definition: 'The OS detects new hardware as soon as it is connected and installs its driver.' },
        { term: 'Hot swappable', definition: 'A device that can be installed without restarting the computer.' },
        { term: 'Task scheduler', definition: 'Utility that runs programs automatically at specified times with specified conditions.' },
      ],
      workedExamples: [
        {
          code: 'Activity 2 backup plan\nFiles   : Documents\\IT and Pictures\nHow often: every Friday at 17:00\nWhere   : external drive E:\nRun with: Task Scheduler',
          explanation: 'A backup plan answers what, how often and where, then uses the scheduler to run it automatically.',
        },
      ],
      misconceptions: [
        'Thinking deleting a program\'s folder uninstalls it. An uninstall program also removes icons and updates the registry.',
        'Thinking every new device needs a restart. Hot swappable devices, such as most USB devices, do not.',
      ],
      questions: [
        {
          id: 'T4-T9-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'What does the registry do when software is installed?',
          options: [
            'It compresses the new program to save space',
            'It records settings and changes that affect the system when installations take place',
            'It scans the program for virus signatures',
            'It schedules the program to update every week',
          ],
          answer: 1,
          hint: 'The installer registers the software so the application will run successfully.',
          explanation: 'The registry records settings and changes from installations. Uninstall programs update it again when the software is removed.',
          skills: ['T4-S11'],
        },
        {
          id: 'T4-T9-Q2',
          type: 'tf',
          category: 'define',
          prompt: 'True or false: A hot swappable device can be installed without restarting the computer, and most USB devices are hot swappable.',
          answer: true,
          hint: 'Think of plugging in a flash drive.',
          explanation: 'True. Hot swappable devices are installed successfully without a restart, and most USB devices are hot swappable.',
          skills: ['T4-S4'],
        },
        {
          id: 'T4-T9-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: Because Google\'s apps are not installed on the computer, a user can refuse their updates forever.',
          answer: false,
          hint: 'Where are Google\'s updates actually done?',
          explanation: 'False. Updates are done on the Google site, so the user cannot refuse them, although they may use the previous version before the update is enforced.',
          skills: ['T4-S11'],
        },
        {
          id: 'T4-T9-Q4',
          type: 'mc',
          category: 'identify',
          prompt: 'Before most updating was done over the Internet, how did older Windows systems receive operating system updates?',
          options: [
            'Service packs distributed on CD',
            'Pop-up windows from the browser',
            'New registry keys typed in by the user',
            'Email attachments from other users',
          ],
          answer: 0,
          hint: 'The same medium drivers used to come on.',
          explanation: 'Older Windows systems were updated with service packs on CD; today a scheduled task checks the vendor\'s update site over the Internet.',
          skills: ['T4-S11'],
        },
      ],
    },
    {
      id: 'T4-T10',
      title: 'Security Features',
      sections: ['4.5', '4.5.1', '4.5.2', '4.5.2.1', '4.5.2.2', '4.5.2.3', '4.5.3', '4.5.3.1'],
      skills: ['T4-S12'],
      explanation: [
        'A firewall is a device or set of devices that permits or denies network transmissions based on a set of rules, protecting networks from unauthorised access and permitting legitimate communications only. Many operating systems include software firewalls (more in Learning Unit 5).',
        'Malware (malicious software) is any program or file that is harmful to a computer. It includes viruses, spyware and adware.',
        'Viruses are programs illegally loaded onto a computer that damage the system. They can modify themselves to avoid detection and spread via removable media, Internet downloads, infected files and outgoing emails, sometimes to every address in the address book. Bogus websites and email attachments make spreading easy.',
        'Spyware is installed secretly to intercept or partly control the user\'s interaction without informed consent. A keystroke logger records each keystroke and sends it to the criminal, who rebuilds logins and passwords, for example to access bank accounts.',
        'Adware is unwanted software that automatically displays or downloads, such as pop-ups while surfing. It is usually benign but can slow the computer, and uses cookies (small text files with personal data) to customise adverts.',
        'Anti-malware safeguards against malicious threats by preventing access, detecting malware and recovering from attacks. Anti-virus software must be continuously updated to find signatures and delete or quarantine files. Good anti-virus updates its signature database, offers network, email and computer protection, scans external drives when attached, and offers full system, selected drive or individual file scans.',
      ],
      vocabulary: [
        { term: 'Firewall', definition: 'A device or set of devices that permits or denies network transmissions based on a set of rules.' },
        { term: 'Malware', definition: 'Malicious software: any program or file that is harmful to a computer.' },
        { term: 'Spyware', definition: 'Software installed secretly to intercept or take partial control of the user\'s interaction without informed consent.' },
        { term: 'Cookie', definition: 'A small text file containing personal data, stored by the Internet browser.' },
        { term: 'Signature', definition: 'An identifying piece of code embedded in a virus program.' },
      ],
      workedExamples: [
        {
          code: 'Scan file -> compare with signature database -> match found?\n  yes: delete or quarantine the file, depending on its severity\n  no : file is clean',
          explanation: 'Anti-virus software matches signatures and takes action, usually delete or quarantine, depending on severity.',
        },
      ],
      misconceptions: [
        'Thinking adware is always dangerous. It is usually benign, but annoying and it can slow your computer.',
        'Thinking anti-virus software works forever once installed. It must keep updating its signature database.',
      ],
      questions: [
        {
          id: 'T4-T10-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'What is malware?',
          options: [
            'Software that compresses files without permission',
            'Any software that is out of date',
            'A device that filters network traffic',
            'Any program or file that is harmful to a computer',
          ],
          answer: 3,
          hint: 'Mal- means bad.',
          explanation: 'Malware, or malicious software, is any program or file that is harmful to a computer, including viruses, spyware and adware.',
          skills: ['T4-S12'],
        },
        {
          id: 'T4-T10-Q2',
          type: 'mc',
          category: 'identify',
          prompt: 'Which THREE categories of protection should good anti-virus software offer?',
          options: [
            'Defragmentation, compression and backup',
            'Typical, custom and full protection',
            'Network security, email security and computer protection',
            'Read, write and execute protection',
          ],
          answer: 2,
          hint: 'Think about traffic, messages and files.',
          explanation: 'Network security checks network traffic, email security protects emails and attachments, and computer protection protects files and folders.',
          skills: ['T4-S12'],
        },
        {
          id: 'T4-T10-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'A full scan of Angelo\'s computer takes a very long time. What does good anti-virus software offer to help?',
          options: [
            'Scanning options such as selected drives, individual files or only recent activity',
            'Only a full system scan once a year',
            'Deleting all files on external drives before scanning',
            'Switching off the firewall during the scan',
          ],
          answer: 0,
          hint: 'You do not always need to scan everything.',
          explanation: 'Good anti-virus software offers full system, selected drive or individual file scans, and can limit a scan to recent activity.',
          skills: ['T4-S12'],
        },
        {
          id: 'T4-T10-Q4',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: A firewall protects a computer by permitting or denying network transmissions based on a set of rules.',
          answer: true,
          hint: 'It filters what comes in and goes out.',
          explanation: 'True. A firewall blocks unauthorised access and permits legitimate communications only; firewalls are covered in more detail in Learning Unit 5.',
          skills: ['T4-S12'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't4-keylogger-heist',
    unitId: UNIT.id,
    title: 'Keylogger Heist',
    icon: 'shield',
    summary: 'Stop malware draining a Johannesburg bank before midnight.',
    briefing: 'A keystroke logger has slipped onto the computers of a Johannesburg bank, and customer passwords are leaking every minute. You must lock down the systems, update the defences and restore clean data from backup before the criminals empty the accounts.',
    tickerMessages: [
      'Bank reports unusual logins from overseas servers',
      'Pop-up adverts flooding staff computers since this morning',
      'Infected email attachment traced to the accounts department',
      'Anti-virus signature database found three months out of date',
      'Criminals rebuilding passwords from stolen keystrokes',
      'Final transfers scheduled for midnight',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T4-S12', 'T4-S11', 'T4-S10', 'T4-S9'],
    victoryMessage: 'Firewall up, spyware quarantined and data restored from a clean backup. The bank is safe.',
    failMessage: 'The keylogger kept recording and the accounts were emptied. Update those defences and try again.',
  },
  {
    id: 't4-lab-meltdown',
    unitId: UNIT.id,
    title: 'Exam Lab Meltdown',
    icon: 'cpu',
    summary: 'Rescue the school computer lab before the IT practical exam.',
    briefing: 'The IT practical exam starts in four minutes and the lab is failing: logons crawl, printers ignore every print job and NetBeans will not run the learners\' Java programs. Use your system software knowledge to get every computer working before the invigilator arrives.',
    tickerMessages: [
      'Logons taking ten minutes; desktops stuffed with huge folders',
      'New printer connected but no driver installed',
      'Learners report .class files will not run',
      'Hard disk on the server badly fragmented',
      'Invigilator is walking down the corridor',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T4-S1', 'T4-S3', 'T4-S4', 'T4-S5', 'T4-S6', 'T4-S8'],
    victoryMessage: 'Fast logons, working printers and running programs. The exam starts on time.',
    failMessage: 'The lab crashed and the exam was postponed. Brush up on system software and try again.',
  },
];
