// Exploring IT: Theory Grade 10 (2nd ed) - Learning Unit 5: Computer Networks
import { Network } from 'lucide-react';

export const UNIT = { id: 'T5', number: 5, name: 'Computer Networks', worldId: 'networks' };

export const SKILLS = {
  'T5-S1': { unit: 'T5', name: 'Networks and nodes', description: 'Define a network, node, server, LAN and cloud computing, and identify the kinds of nodes on a network.', sections: ['5.1', '5.2'] },
  'T5-S2': { unit: 'T5', name: 'Channels and bandwidth', description: 'Describe the three parts of a network, the communication channel and bandwidth in Kbps, Mbps and Gbps.', sections: ['5.3'] },
  'T5-S3': { unit: 'T5', name: 'UTP and copper problems', description: 'Describe UTP cabling, the problems with copper cables and the advantages and disadvantages of UTP.', sections: ['5.4', '5.4.1', '5.4.1.1', '5.4.1.2', '5.4.1.3'] },
  'T5-S4': { unit: 'T5', name: 'STP and fibre optic', description: 'Describe STP and fibre optic cable, the pros and cons of fibre and its use as a backbone.', sections: ['5.4.2', '5.4.3', '5.4.3.1', '5.4.3.2', '5.4.4'] },
  'T5-S5': { unit: 'T5', name: 'Wireless transmission', description: 'Explain unbounded media: terrestrial and satellite microwave for long distances and radio waves for short distances.', sections: ['5.5', '5.5.1', '5.5.2', '5.5.2.1', '5.5.2.2'] },
  'T5-S6': { unit: 'T5', name: 'Network classification', description: 'Classify networks by area covered as LAN, MAN, WAN, GAN, PAN or HAN and give typical uses.', sections: ['5.6', '5.6.1', '5.6.2', '5.6.3', '5.6.4', '5.6.5', '5.6.6'] },
  'T5-S7': { unit: 'T5', name: 'The home network', description: 'Explain the role of the router, Wi-Fi hotspots and how fibre reaches a home through an ONT.', sections: ['5.7', '5.7.1', '5.7.2'] },
  'T5-S8': { unit: 'T5', name: 'Firewalls and access control', description: 'Explain how a firewall protects a private network and how network access control authenticates users and assigns rights.', sections: ['5.7.3', '5.9'] },
  'T5-S9': { unit: 'T5', name: 'Server roles', description: 'Describe the client-server model and the purpose of file, print, web, email and proxy servers.', sections: ['5.8', '5.8.1'] },
  'T5-S10': { unit: 'T5', name: 'Local vs cloud servers and clients', description: 'Compare local and cloud servers and describe the roles of client and server operating systems.', sections: ['5.8.1.1', '5.8.2'] },
  'T5-S11': { unit: 'T5', name: 'Advantages of networks', description: 'Explain communication, file sharing, resource sharing, centralisation, data transfer and productivity benefits of networks.', sections: ['5.10', '5.10.1', '5.10.2', '5.10.3', '5.10.4', '5.10.4.1', '5.10.4.2', '5.10.4.3', '5.10.5', '5.10.6'] },
  'T5-S12': { unit: 'T5', name: 'Disadvantages of networks', description: 'Explain security issues, virus spread, cost and dependency on central servers, and compare with stand-alone computers.', sections: ['5.11', '5.11.1', '5.11.2', '5.11.3', '5.11.4'] },
};

export const SKILL_HINTS = {
  'T5-S1': 'Network = two or more nodes joined by a communications channel; node = any connected device (computer, printer, mobile, switch, router, server); server provides central resources; LAN = home, school, lab or building; cloud computing = services over the Internet, pay only for what you use',
  'T5-S2': 'Every network has a sender (source), receiver (destination) and communication channel (transmission medium); bandwidth = maximum data per unit time in bits per second: Kbps thousands, Mbps millions, Gbps billions; bounded = cables, unbounded = wireless',
  'T5-S3': 'UTP = twisted copper pairs in plastic cover with RJ45 connectors, twisting reduces interference; copper problems: attenuation, EMI, eavesdropping, crosstalk; UTP cheap, easy, fast, widely used; max 100 m, repeater boosts signal to join lengths',
  'T5-S4': 'STP = twisted pairs in protective foil, more expensive and bulkier, less affected by interference and crosstalk; fibre = glass or plastic core, cladding reflects light, light pulses, SC connector; faster, secure, long distance, no EMI, immune to lightning; expensive and complex; backbone joins LAN segments',
  'T5-S5': 'Wireless signals use different frequencies (Hertz); microwave for long distances: terrestrial line-of-sight up to 50 km, satellite with transponders; geo-stationary fixed position good for TV, low-orbit less delay for interactive use; weather affects microwave; radio waves (Wi-Fi, Bluetooth) for short distances',
  'T5-S6': 'LAN building or campus (school); MAN LANs across a city; WAN LANs/MANs across cities or countries (Edgars, bank, enterprise WAN); GAN worldwide WAN such as the Internet; PAN one person\'s devices via Bluetooth or USB; HAN home devices, made up of PANs',
  'T5-S7': 'Router joins networks, connects home nodes to the Internet; ADSL and fibre lines need routers; Wi-Fi router creates hotspot, devices need range and valid password; fibre path: distribution node, backbone to street, boundary wall box, ONT, router, devices',
  'T5-S8': 'Firewall = hardware and/or software that prevents unauthorised access to or from a private network, a one-way digital gate; NAC = computer settings and user login must comply with network rules, users authenticated then given rights by profile',
  'T5-S9': 'Server shares resources, clients use services; file server stores files, print server shares printers, web server sends web pages, email server stores and sends mail, proxy server checks traffic and caches web pages; one server can do several jobs',
  'T5-S10': 'Local server: physical control, no Internet needed, but setup cost and IT staff; cloud server: no hardware upgrades, add storage and pay for use, backups every 15 minutes, but no access if Internet down; server OS manages logons, rights, IP addresses, sharing, traffic; server not a workstation, higher specs',
  'T5-S11': 'Network advantages: communication, file sharing, printer and router sharing (one each instead of one per computer), centralised apps (Google Docs, Office 365), central file storage, shared calendars, data transfer rate matters, productivity via collaboration',
  'T5-S12': 'Network disadvantages: more unauthorised access than stand-alone, need security software, viruses spread rapidly, high setup cost (routers, switches, servers, NICs, cables, wireless access point), faulty server stops the system and servers need maintenance',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Network Nexus',
  subtitle: 'Unit 5 \u00b7 Computer Networks',
  color: 'sky',
  glow: 'ja-glow-sky',
  bg: 'ja-w-networks',
  icon: Network,
  blurb: 'Patch cables, beam signals off satellites and guard the server room. Learn how nodes, media, servers and firewalls keep the world connected.',
};

export const LEVELS = [
  { id: 't5-l1', name: 'Node Zero', subtitle: 'Networks, nodes, channels, bandwidth and copper problems', challengeIds: ['t5-c1', 't5-c2', 't5-c3', 't5-c4', 't5-c5', 't5-c6'] },
  { id: 't5-l2', name: 'Cable and Sky', subtitle: 'UTP, STP, fibre optic and wireless transmissions', challengeIds: ['t5-c7', 't5-c8', 't5-c9', 't5-c10', 't5-c11', 't5-c12'] },
  { id: 't5-l3', name: 'Home Base and Server Room', subtitle: 'Network types, home networks, servers and access control', challengeIds: ['t5-c13', 't5-c14', 't5-c15', 't5-c16', 't5-c17', 't5-c18', 't5-c19'] },
  { id: 't5-l4', name: 'Nexus Core Boss', subtitle: 'Mixed review of the whole unit, including the pros and cons of networks', challengeIds: ['t5-c20', 't5-c21', 't5-c22', 't5-c23', 't5-c24', 't5-c25', 't5-c26'] },
];

export const CHALLENGES = {
  't5-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which statement matches the textbook definition of a network?',
    options: [
      'A single computer running many different programs',
      'Two or more nodes connected by a communications channel',
      'Any device that is able to connect to the Internet',
      'A server that stores files for many different users',
    ],
    answer: 1,
    hint: 'Think about how many devices are needed and what joins them.',
    explanation: 'A network consists of two or more devices, called nodes, connected by some type of communications channel, which can be bounded (wires) or unbounded (wireless).',
    skills: ['T5-S1'],
  },
  't5-c2': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each node to the role it plays on a network.',
    pairs: [
      { left: 'Laptop or smartphone', right: 'A device that users use' },
      { left: 'Switch', right: 'Connects nodes to each other' },
      { left: 'Router', right: 'Connects the network to the Internet' },
      { left: 'Printer or server', right: 'Provides a service to the network' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'One device joins nodes inside the network; another links the network to the outside world.',
    explanation: 'The textbook lists four kinds of nodes: user devices, a switch to connect nodes, a router to connect to the Internet and service devices such as a server or printer.',
    skills: ['T5-S1'],
  },
  't5-c3': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: with cloud computing a company must keep buying and upgrading its own servers to store its data.',
    answer: false,
    hint: 'Where do cloud services run, and how do you pay for them?',
    explanation: 'Cloud computing uses services like storage, databases and software over the Internet. You pay only for the services you use, removing the need to upgrade servers and software.',
    skills: ['T5-S1'],
  },
  't5-c4': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Every network has a sender, a receiver and a connection between them. What is that connection called?',
    options: [
      'The node',
      'The bandwidth',
      'The server',
      'The communication channel (transmission medium)',
    ],
    answer: 3,
    hint: 'It is the path the data travels along, wired or wireless.',
    explanation: 'The connection between source and destination is usually called the communication channel or transmission medium. Bandwidth is a property of the channel, not the channel itself.',
    skills: ['T5-S2'],
  },
  't5-c5': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Convert each data rate. Type whole numbers only, digits with no spaces.',
    code: 'Kbps = thousands of bits per second\nMbps = millions of bits per second\nGbps = billions of bits per second',
    rows: [
      { label: '2 Gbps in Mbps', answer: '2000' },
      { label: '5 Mbps in Kbps', answer: '5000' },
      { label: '3 Kbps in bits per second', answer: '3000' },
      { label: '4000 Mbps in Gbps', answer: '4' },
    ],
    hint: 'Each step up (bps to Kbps to Mbps to Gbps) is a factor of 1000.',
    explanation: 'One billion is 1000 million and one million is 1000 thousand, so each unit is 1000 times the one below it: 2 Gbps = 2000 Mbps and 4000 Mbps = 4 Gbps.',
    skills: ['T5-S2'],
  },
  't5-c6': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each problem with copper cables to its description.',
    pairs: [
      { left: 'Attenuation', right: 'The signal loses strength over a distance' },
      { left: 'Electro-Magnetic Interference', right: 'Signals from machinery corrupt signals in nearby cables' },
      { left: 'Eavesdropping', right: 'Outsiders intercept the signals travelling along the cable' },
      { left: 'Crosstalk', right: 'Signals in adjacent wires interfere with each other' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Crosstalk is like a crossed telephone conversation; eavesdropping involves outsiders.',
    explanation: 'These are the four problems with copper cables listed in the textbook. Fibre optic cable avoids them because it carries light, not electronic signals.',
    skills: ['T5-S3'],
  },
  't5-c7': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'What is the maximum length of a UTP cable before the signal degenerates, and what causes it?',
    options: [
      '50 m, because of crosstalk between pairs',
      '1 km, because of electro-magnetic interference',
      '100 m, because of attenuation',
      '100 m, because of eavesdropping',
    ],
    answer: 2,
    hint: 'Which copper problem is about signal strength fading with distance?',
    explanation: 'A UTP cable can be a maximum of 100 m before the signal degenerates due to attenuation. A repeater can boost the signal to join two long lengths.',
    skills: ['T5-S3'],
  },
  't5-c8': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: STP cable is cheaper and less bulky than UTP, but more affected by crosstalk.',
    answer: false,
    hint: 'What does the extra foil around the twisted pairs add, and what does it protect against?',
    explanation: 'STP is more expensive and bulkier than UTP because its twisted pairs are enclosed in protective foil, which makes it less affected by interference and crosstalk.',
    skills: ['T5-S4'],
  },
  't5-c9': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why is fibre optic cable often used as a backbone to join LANs in different buildings?',
    options: [
      'It is the cheapest and easiest cable to install',
      'It is made of copper wires twisted in pairs',
      'It only works over distances shorter than 100 m',
      'Lightning does not affect it and it covers long distances',
    ],
    answer: 3,
    hint: 'Cables between buildings run outside, exposed to the weather.',
    explanation: 'Fibre carries light, so lightning and electrical surges do not affect it and the signal does not weaken over long distances. Several LAN segments hanging off one fibre cable form a backbone.',
    skills: ['T5-S4'],
  },
  't5-c10': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the steps of a satellite transmission in the correct order.',
    items: [
      'The transponder converts the signal to a different frequency and boosts it',
      'A ground station sends the signal up to the satellite',
      'A ground station in line-of-sight of the satellite receives the signal',
      'The satellite transponder receives the signal',
    ],
    answer: [1, 3, 0, 2],
    hint: 'The signal goes up, gets processed by the transponder, then comes down.',
    explanation: 'A transponder receives signals, converts them into a different frequency, boosts them and sends them to a ground station which must be in line-of-sight of the satellite.',
    skills: ['T5-S5'],
  },
  't5-c11': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which type of satellite is better for interactive communication, and why?',
    options: [
      'Geo-stationary, because it stays in a fixed position',
      'Low-orbit, because it is nearer the earth so there is little delay',
      'Geo-stationary, because it is much nearer the earth',
      'Low-orbit, because it rotates at the same speed as the earth',
    ],
    answer: 1,
    hint: 'The further the signal must travel, the longer the delay.',
    explanation: 'Low-orbit satellites are much nearer the earth, so there is little delay. Geo-stationary satellites appear fixed and are excellent for TV broadcasting.',
    skills: ['T5-S5'],
  },
  't5-c12': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: a Wi-Fi router and a Bluetooth headset both use radio waves to transmit signals.',
    answer: true,
    hint: 'Which kind of wireless transmission is used for short distances?',
    explanation: 'Radio-wave transmission is used for short distances, and Wi-Fi and Bluetooth both use radio waves. A Wi-Fi router uses them to create a hotspot for nearby devices.',
    skills: ['T5-S5', 'T5-S7'],
  },
  't5-c13': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Classify each network by the area it covers. Type exactly one of: LAN, MAN, WAN, GAN, PAN.',
    code: 'LAN  MAN  WAN  GAN  PAN',
    rows: [
      { label: 'Your phone syncing with your smartwatch over Bluetooth', answer: 'PAN' },
      { label: 'A bank with branches in Durban, Cape Town and Johannesburg', answer: 'WAN' },
      { label: 'The Internet', answer: 'GAN' },
      { label: 'A company joining its offices scattered across Pretoria', answer: 'MAN' },
      { label: 'All the computers on one school campus', answer: 'LAN' },
    ],
    hint: 'Think person, building, city, many cities or countries, the whole world.',
    explanation: 'A PAN serves one individual, a LAN a building or campus, a MAN a city, a WAN different cities or countries and a GAN is a worldwide WAN such as the Internet.',
    skills: ['T5-S6'],
  },
  't5-c14': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the path of a fibre connection into a home in order, from the provider to your devices.',
    items: [
      'Router',
      'Local distribution node',
      'ONT (Optical Network Terminal)',
      'Devices in the home (copper cable or Wi-Fi)',
      'Distribution box at your boundary wall',
      'Fibre optic backbone cable to your street',
    ],
    answer: [1, 5, 4, 2, 0, 3],
    hint: 'The ONT sits between the fibre on the outside of your house and the router.',
    explanation: 'A fibre backbone runs from a local distribution node to your street, then from the box at your boundary wall into your home. The ONT connects the fibre to your router, which serves your devices by cable or wirelessly.',
    skills: ['T5-S7'],
  },
  't5-c15': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which statement best describes how a firewall works?',
    options: [
      'It blocks all traffic so devices cannot reach the Internet',
      'It boosts the signal so data can travel further',
      'It is a one-way gate: it blocks outside access but lets inside devices out',
      'It assigns IP addresses to devices joining the network',
    ],
    answer: 2,
    hint: 'Your own devices still need to reach websites.',
    explanation: 'A firewall prevents unauthorised access to or from a private network. It acts like a one-way digital gate, blocking devices on the Internet while allowing devices on your network to connect out.',
    skills: ['T5-S8'],
  },
  't5-c16': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each type of server to its purpose.',
    pairs: [
      { left: 'File server', right: 'Large hard disk capacity storing files for network users' },
      { left: 'Print server', right: 'Shares attached high-speed printers with the network' },
      { left: 'Web server', right: 'Accepts requests for web pages and sends them to clients' },
      { left: 'Email server', right: 'Stores incoming mail for users and sends outgoing messages' },
      { left: 'Proxy server', right: 'Checks all web traffic and caches web documents' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'The name of most servers tells you what resource it shares.',
    explanation: 'In a client-server network each server can have a specific purpose depending on the resource it shares. The proxy server sits between clients and servers, checking traffic and caching pages.',
    skills: ['T5-S9'],
  },
  't5-c17': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: to save money, the server should also be used as a workstation when it is not busy.',
    answer: false,
    hint: 'What is the purpose of the server?',
    explanation: 'The server should not be used as a workstation; its purpose is to provide services to the computers on the network, so it also needs higher hardware specifications than the clients.',
    skills: ['T5-S10'],
  },
  't5-c18': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which is an advantage of a cloud-based server over a local server?',
    options: [
      'Users can still reach the data when the Internet is down',
      'The company has physical control over the server',
      'IT staff must set up and manage the hardware on site',
      'Storage can be added when needed and you pay only for use',
    ],
    answer: 3,
    hint: 'Three of these describe a server kept inside the organisation.',
    explanation: 'Cloud servers avoid continued upgrading of on-site hardware: storage is added when needed and you pay for what you use. Physical control and access without the Internet are advantages of a local server.',
    skills: ['T5-S10'],
  },
  't5-c19': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the steps of network access control in the correct order.',
    items: [
      'The network authenticates the user by verifying the logon details',
      'The user uses only the resources they have permission for',
      'The user enters their logon information',
      'Rights are awarded according to the user profile',
    ],
    answer: [2, 0, 3, 1],
    hint: 'You cannot be given rights before the network knows who you are.',
    explanation: 'Users are first authenticated by verifying their logon information. Once authenticated, rights are awarded according to their profile, and they may only use the resources they have permission for.',
    skills: ['T5-S8'],
  },
  't5-c20': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Order these networks from the smallest area covered to the largest.',
    items: ['WAN', 'PAN', 'GAN', 'LAN', 'MAN'],
    answer: [1, 3, 4, 0, 2],
    hint: 'Start with one person and end with the whole world.',
    explanation: 'A PAN serves one person, a LAN a building or campus, a MAN a city, a WAN several cities or countries, and a GAN is worldwide.',
    skills: ['T5-S6'],
  },
  't5-c21': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Four people at home each have their own computer and all want to print and use the Internet. Type whole numbers.',
    code: 'Each person needs: 1 router + 1 printer (if not networked)\nNetworked home: devices are shared by all four computers',
    rows: [
      { label: 'Routers + printers needed with no network', answer: '8' },
      { label: 'Routers + printers needed with a network', answer: '2' },
      { label: 'Devices saved by networking', answer: '6' },
    ],
    hint: 'Without a network each computer needs its own router and printer.',
    explanation: 'Without a network: 4 routers + 4 printers = 8 devices. Networked: just 1 router + 1 printer = 2 devices serve all four users, saving 6 expensive devices.',
    skills: ['T5-S11'],
  },
  't5-c22': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why do computer viruses spread so rapidly on a network?',
    options: [
      'All the computers are connected, so one infected computer can affect others',
      'Fibre optic cables carry viruses faster than copper cables do',
      'Faulty network servers create new viruses on their own',
      'Firewalls are designed to let viruses through on purpose',
    ],
    answer: 0,
    hint: 'What is the defining feature of a network?',
    explanation: 'If any computer on a network gets a virus, others may become affected too because all computers are connected. The problem is compounded when the network is connected to the Internet.',
    skills: ['T5-S12'],
  },
  't5-c23': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: if the file server or email server of a network becomes faulty, the system can lose its functionality.',
    answer: true,
    hint: 'Think about what the clients depend on.',
    explanation: 'Networks depend on their central servers. A faulty server means the system loses functionality, and servers are expensive to repair or replace and need constant maintenance.',
    skills: ['T5-S12', 'T5-S9'],
  },
  't5-c24': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each advantage of networks to an example of it.',
    pairs: [
      { left: 'Communication', right: 'Email lets people share ideas, news and research worldwide' },
      { left: 'File sharing', right: 'Opening a file saved on another workstation, if authorised' },
      { left: 'Network applications', right: 'Using Google Docs or Office 365 online from any device' },
      { left: 'Sharing data', right: 'A manager and secretary using one online calendar' },
      { left: 'Productivity', right: 'Team video calls and task organisers speed up work' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Network applications are delivered centrally or online rather than installed on each machine.',
    explanation: 'Networks improve communication, let authorised users share files, centralise applications and data such as calendars, and improve productivity through collaboration tools.',
    skills: ['T5-S11'],
  },
  't5-c25': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'A learner requests a web page that another learner opened earlier. How does the proxy server speed this up?',
    options: [
      'It forwards the request to the email server first',
      'It serves the page from its cache instead of the Internet',
      'It lowers the bandwidth so the page loads faster',
      'It blocks the page because it was already viewed',
    ],
    answer: 1,
    hint: 'Proxy servers store web documents that were previously accessed.',
    explanation: 'Caching means the proxy stores previously accessed web documents. It checks its cache first and serves the page if it is there; otherwise it obtains it from the Internet.',
    skills: ['T5-S9'],
  },
  't5-c26': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'A school must join the LANs in two buildings and connect the PCs in each lab to a switch. Which cabling plan fits the textbook best?',
    options: [
      'Fibre optic backbone between buildings, UTP from PCs to the switch',
      'UTP between buildings, fibre optic from PCs to the switch',
      'UTP everywhere, because copper is immune to lightning',
      'STP between buildings, because it carries light pulses',
    ],
    answer: 0,
    hint: 'One cable is cheap and easy for short runs; the other survives lightning and long distances.',
    explanation: 'UTP is inexpensive, easy to install and connects devices to a switch with RJ45 connectors. Fibre is used to join LAN segments in different buildings because lightning does not affect it.',
    skills: ['T5-S3', 'T5-S4'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Understand what computer networks are, the media that connect them, how they are classified and protected, and their advantages and disadvantages.',
  outcomes: [
    'By the end you can define a network, node, server and cloud computing.',
    'By the end you can explain bandwidth and convert between Kbps, Mbps and Gbps.',
    'By the end you can describe UTP, STP and fibre optic cable and compare their advantages and disadvantages.',
    'By the end you can explain terrestrial and satellite microwave and radio-wave transmission.',
    'By the end you can classify networks as LAN, MAN, WAN, GAN, PAN or HAN.',
    'By the end you can describe a home network with a router, ONT and firewall.',
    'By the end you can describe the roles of servers and clients and compare local and cloud servers.',
    'By the end you can explain network access control and the advantages and disadvantages of networks.',
  ],
  topics: [
    {
      id: 'T5-T1',
      title: 'What is a network?',
      sections: ['5.1', '5.2'],
      skills: ['T5-S1'],
      explanation: [
        'A network consists of two or more devices called nodes that are connected by some type of communications channel. A node is any device connected to the network: usually a computer, but it can also be a printer or a mobile device.',
        'The communication channel can be bounded (using wires) or unbounded (using a form of wireless technology).',
        'A network server is a computer designed to act as a central network computer that provides resources like network security, hardware access, disk space and printer access. Server software manages logins and user access to computers on the network.',
        'A network in a geographical area such as a home, school, computer laboratory, office building or group of buildings is called a Local Area Network (LAN).',
        'The trend today is cloud computing: using computing services like storage, databases, software and networking over the Internet ("the cloud"). You pay only for what you use, removing the need to upgrade servers and software.',
        'Nodes can be: a device users use (laptop, desktop or mobile device), a switch to connect nodes to each other, a router to connect to the Internet, or a device that provides a service (a server or a printer).',
        'A switch connects nodes using communication media such as cables; each node plugs into a port on the switch. A file server lets users store files centrally and open them from any node, provided they have the correct permissions.',
      ],
      vocabulary: [
        { term: 'Network', definition: 'Two or more devices (nodes) connected by some type of communications channel.' },
        { term: 'Node', definition: 'Any device connected to the network, such as a computer, printer or mobile device.' },
        { term: 'Network server', definition: 'A computer designed to act as a central network computer that provides resources like network security, hardware access, disk space and printer access.' },
        { term: 'LAN', definition: 'Local Area Network: a network in a geographical area such as a home, school, lab, office building or group of buildings.' },
        { term: 'Cloud computing', definition: 'Making use of computing services like storage, databases, software and networking over the Internet, paying only for what you use.' },
        { term: 'Switch', definition: 'A device that connects nodes in a network; each node is connected to a port in the switch.' },
      ],
      workedExamples: [
        {
          code: 'Laptop  ---+\nDesktop ---+--- [Switch] --- File server\nPrinter ---+        |\n                 [Router] --- Internet',
          explanation: 'A small LAN: user devices and the printer plug into ports on the switch, the server provides shared files, and the router connects the whole network to the Internet. Every box here is a node.',
        },
      ],
      misconceptions: [
        'Only computers are nodes. Wrong: a node is any connected device, including printers, switches, routers and mobile devices.',
        'Cloud computing means buying bigger servers. Wrong: cloud services are used over the Internet and you pay only for what you use, so you avoid upgrading your own servers.',
      ],
      questions: [
        {
          id: 'T5-T1-Q1',
          category: 'define',
          type: 'mc',
          prompt: 'Which is the best definition of a node?',
          options: [
            'Any device connected to the network',
            'Only a computer that stores shared files',
            'The cable that joins two computers',
            'The software that manages user logins',
          ],
          answer: 0,
          hint: 'Printers and phones can also be nodes.',
          explanation: 'A node is any device connected to the network. It is typically a computer but can also be a printer, mobile device, switch, router or server.',
          skills: ['T5-S1'],
        },
        {
          id: 'T5-T1-Q2',
          category: 'apply',
          type: 'mc',
          prompt: 'A small business pays a monthly fee to store its database online and only pays for the storage it uses. What is this called?',
          options: [
            'A local area network',
            'Cloud computing',
            'A switch',
            'Network access control',
          ],
          answer: 1,
          hint: 'The service is delivered over the Internet.',
          explanation: 'Cloud computing is using services like storage and databases over the Internet and paying only for the services you use.',
          skills: ['T5-S1'],
        },
      ],
    },
    {
      id: 'T5-T2',
      title: 'Communication media and bandwidth',
      sections: ['5.3'],
      skills: ['T5-S2'],
      explanation: [
        'Irrespective of the distance it covers, every network has 3 parts: hardware that acts as the source or sender, hardware that is the destination or receiver, and some sort of connection between them.',
        'The connection is usually called the communication channel or transmission medium. The sending and receiving devices can be any node, such as a computer, cell phone or printer.',
        'Bandwidth is the maximum amount of data a channel can transfer per unit time, usually measured in bits per second.',
        'Rates are measured in kilobits per second (Kbps, thousands of bits), megabits per second (Mbps, millions of bits) or gigabits per second (Gbps, billions of bits). The higher the bandwidth, the faster the transmission rate.',
        'Bounded channels (physical cabling) are commonly used for wired LANs, while unbounded media (no cables) carry signals for wireless LANs and larger networks.',
      ],
      vocabulary: [
        { term: 'Communication channel', definition: 'The connection between the source and destination; also called the transmission medium.' },
        { term: 'Bandwidth', definition: 'The maximum amount of data a communication channel can transfer per unit time, usually in bits per second.' },
        { term: 'Kbps / Mbps / Gbps', definition: 'Kilobits (thousands), megabits (millions) and gigabits (billions) of bits per second.' },
        { term: 'Bounded media', definition: 'Communication channels made of physical cabling.' },
        { term: 'Unbounded media', definition: 'Communication channels with no cables, such as wireless signals.' },
      ],
      workedExamples: [
        {
          code: '1 Kbps = 1 000 bits per second\n1 Mbps = 1 000 000 bits per second\n1 Gbps = 1 000 000 000 bits per second\n\n100 Mbps = 100 000 Kbps = 0.1 Gbps',
          explanation: 'Each unit is 1000 times the one below it. To go down a unit multiply by 1000; to go up a unit divide by 1000.',
        },
      ],
      misconceptions: [
        'Bandwidth is measured in bytes, like storage. Wrong: the textbook measures channel rates in bits per second (Kbps, Mbps, Gbps).',
        'Only computers can send and receive on a network. Wrong: the sender and receiver can be any node, such as a cell phone or printer.',
      ],
      questions: [
        {
          id: 'T5-T2-Q1',
          category: 'calculate',
          type: 'trace',
          prompt: 'Convert each data rate. Type whole numbers only, digits with no spaces.',
          code: 'Kbps = thousands, Mbps = millions, Gbps = billions of bits per second',
          rows: [
            { label: '1 Gbps in Kbps', answer: '1000000' },
            { label: '250 Kbps in bits per second', answer: '250000' },
            { label: '3000 Kbps in Mbps', answer: '3' },
          ],
          hint: 'Gbps to Kbps is two steps of 1000.',
          explanation: '1 Gbps = 1000 Mbps = 1 000 000 Kbps; 250 Kbps = 250 x 1000 = 250 000 bps; 3000 Kbps / 1000 = 3 Mbps.',
          skills: ['T5-S2'],
        },
        {
          id: 'T5-T2-Q2',
          category: 'sequence',
          type: 'order',
          prompt: 'Order the three parts of a network in the direction a message travels.',
          items: ['Receiver (destination)', 'Sender (source)', 'Communication channel'],
          answer: [1, 2, 0],
          hint: 'The message starts at the source.',
          explanation: 'Data leaves the sender, travels along the communication channel (transmission medium) and arrives at the receiver.',
          skills: ['T5-S2'],
        },
        {
          id: 'T5-T2-Q3',
          category: 'distinguish',
          type: 'mc',
          prompt: 'What is the difference between bounded and unbounded transmission media?',
          options: [
            'Bounded media are wireless; unbounded media use cables',
            'Bounded media are only used in WANs; unbounded only in LANs',
            'Bounded media use physical cables; unbounded media have no cables',
            'Bounded media measure bandwidth; unbounded media do not',
          ],
          answer: 2,
          hint: 'Bounded means the signal is bound to a physical path.',
          explanation: 'Bounded channels consist of physical cabling and are common in wired LANs; unbounded media have no cables and carry signals for wireless LANs and larger networks.',
          skills: ['T5-S2'],
        },
      ],
    },
    {
      id: 'T5-T3',
      title: 'Twisted pair cables: UTP and STP',
      sections: ['5.4', '5.4.1', '5.4.1.1', '5.4.1.2', '5.4.1.3', '5.4.2'],
      skills: ['T5-S3', 'T5-S4'],
      explanation: [
        'UTP (Unshielded Twisted Pair) is the most common bounded media cabling in small LANs. It consists of several pairs of twisted wires in an outer protective plastic cover. The twisting helps eliminate interference from signals on other wires and from other electrical devices.',
        'UTP has an RJ45 connector on each end: one end connects to a port on a computing device and the other connects to a switch.',
        'Problems with copper cables: attenuation (the signal loses strength over a distance), electro-magnetic interference or EMI (signals from sources such as machinery corrupt the signals), eavesdropping (signals can be intercepted by outsiders) and crosstalk (signals in adjacent wires interfere, like a crossed telephone conversation).',
        'Advantages of UTP: it is inexpensive and easy to install, supports fast transmission rates, is widely used and tested, and can be used in many different types of networks.',
        'Disadvantages of UTP: it is susceptible to interference from other devices, crosstalk can corrupt signals, and there are distance limitations. A cable can be a maximum of 100 m before the signal degenerates due to attenuation. A repeater can join two long lengths of cable by boosting (amplifying) the signal.',
        'Shielded Twisted Pair (STP) is more expensive and bulkier. Its twisted pairs are enclosed in protective foil, so it is less affected than UTP by interference and crosstalk.',
      ],
      vocabulary: [
        { term: 'UTP', definition: 'Unshielded Twisted Pair: several pairs of twisted wires in an outer protective plastic cover.' },
        { term: 'RJ45 connector', definition: 'The connector on each end of a UTP cable; one end plugs into a device, the other into a switch.' },
        { term: 'Attenuation', definition: 'The signal loses strength over a distance.' },
        { term: 'EMI', definition: 'Electro-Magnetic Interference: signals from other sources such as machinery corrupt signals in nearby copper cables.' },
        { term: 'Crosstalk', definition: 'Signals in adjacent wires interfere with each other, as in a crossed telephone conversation.' },
        { term: 'Repeater', definition: 'A device that joins two long lengths of cable and boosts or amplifies the signal.' },
        { term: 'STP', definition: 'Shielded Twisted Pair: twisted pairs enclosed in protective foil; more expensive and bulkier, less affected by interference.' },
      ],
      workedExamples: [
        {
          code: 'Cable run needed: 250 m   UTP maximum: 100 m per length\nLengths: 100 m + 100 m + 50 m = 3 lengths\nRepeaters (one between each pair of lengths) = 2',
          explanation: 'Because of attenuation each UTP length is limited to 100 m. A repeater joins two lengths and boosts the signal, so three lengths need two repeaters.',
        },
      ],
      misconceptions: [
        'The wires are twisted just to keep the cable neat. Wrong: twisting helps eliminate interference from other wires and electrical devices.',
        'STP is the cheaper option. Wrong: STP is more expensive and bulkier than UTP because of its protective foil.',
      ],
      questions: [
        {
          id: 'T5-T3-Q1',
          category: 'explain',
          type: 'tf',
          prompt: 'True or false: UTP is expensive and difficult to install, which is why it is rarely used in small LANs.',
          answer: false,
          hint: 'Think about which cable the textbook calls the most common in small LANs.',
          explanation: 'UTP is the most common cabling in small LANs because it is inexpensive, easy to install, supports fast transmission rates and is widely used and tested.',
          skills: ['T5-S3'],
        },
        {
          id: 'T5-T3-Q2',
          category: 'calculate',
          type: 'trace',
          prompt: 'A cable must run 300 m along a school corridor using UTP. Type whole numbers.',
          code: 'UTP maximum length per cable: 100 m\nA repeater joins two lengths of cable',
          rows: [
            { label: 'Number of 100 m lengths needed', answer: '3' },
            { label: 'Number of repeaters needed to join them', answer: '2' },
          ],
          hint: 'A repeater goes between two lengths, not at the ends.',
          explanation: '300 m / 100 m = 3 lengths. Joining 3 lengths in a line needs 2 joins, so 2 repeaters boost the signal.',
          skills: ['T5-S3'],
        },
        {
          id: 'T5-T3-Q3',
          category: 'classify',
          type: 'mc',
          prompt: 'Signals from a nearby lift motor corrupt the data in a copper network cable. Which problem is this?',
          options: [
            'Attenuation',
            'Eavesdropping',
            'Electro-Magnetic Interference',
            'Crosstalk',
          ],
          answer: 2,
          hint: 'The source of the problem is machinery outside the cable.',
          explanation: 'EMI is when signals from other sources such as machinery corrupt signals in nearby copper cables. Crosstalk comes from adjacent wires in the cable itself.',
          skills: ['T5-S3'],
        },
      ],
    },
    {
      id: 'T5-T4',
      title: 'Fibre optic cable',
      sections: ['5.4.3', '5.4.3.1', '5.4.3.2', '5.4.4'],
      skills: ['T5-S4'],
      explanation: [
        'Fibre optic cable consists of a central glass or plastic core surrounded by several layers of protective materials. Cladding surrounds the core and reflects light back into it.',
        'It transmits light pulses rather than electronic signals, eliminating interference. The light bounces off the cladding even if the cable is bent. The most common connector today is the SC connector.',
        'Advantages: much faster transmission rates; more secure than UTP because light signals cannot easily be tapped; much longer distances because light does not weaken like electronic signals in copper; not susceptible to EMI; immune to lightning and electrical surges.',
        'Disadvantages: it is very expensive to purchase and install, and complex to install, with strict criteria that must be met for the cabling to be certified.',
        'Fibre is often used to join LAN segments together, especially when the LANs are in different buildings, because lightning does not affect it. When several LAN segments hang off one fibre optic cable, it is called a backbone.',
      ],
      vocabulary: [
        { term: 'Core', definition: 'The central glass or plastic part of a fibre optic cable that carries the light.' },
        { term: 'Cladding', definition: 'The layer surrounding the core that reflects light back into the core.' },
        { term: 'SC connector', definition: 'The most common connector used with fibre optic cable today.' },
        { term: 'Backbone', definition: 'One fibre optic cable off which several LAN segments hang.' },
      ],
      workedExamples: [
        {
          code: 'Aspect        UTP                     Fibre optic\nSignal        Electronic (copper)     Light pulses\nCost          Inexpensive             Very expensive\nDistance      Max 100 m               Much longer\nInterference  Susceptible to EMI      Not susceptible\nSecurity      Can be eavesdropped     Not easily tapped',
          explanation: 'A comparison of UTP and fibre optic cable on several aspects, as asked in Check Point 1.',
        },
      ],
      misconceptions: [
        'Fibre stops working if the cable bends. Wrong: the light is bounced off the cladding even if the cable is bent.',
        'Fibre is used everywhere because it is cheap. Wrong: it is very expensive and complex to install, so it is mostly used where its advantages matter, such as backbones.',
      ],
      questions: [
        {
          id: 'T5-T4-Q1',
          category: 'define',
          type: 'mc',
          prompt: 'What is the job of the cladding in a fibre optic cable?',
          options: [
            'It reflects light back into the core',
            'It converts light into electronic signals',
            'It twists the strands to stop crosstalk',
            'It connects the cable to an RJ45 port',
          ],
          answer: 0,
          hint: 'The light must stay inside the core.',
          explanation: 'Cladding surrounds the core and reflects light back into it, so light keeps travelling through the core even when the cable bends.',
          skills: ['T5-S4'],
        },
        {
          id: 'T5-T4-Q2',
          category: 'distinguish',
          type: 'tf',
          prompt: 'True or false: fibre optic cable is cheaper and simpler to install than UTP.',
          answer: false,
          hint: 'Recall the two disadvantages of fibre.',
          explanation: 'Fibre is very expensive to purchase and install, and complex to install because strict criteria must be met for certification.',
          skills: ['T5-S4'],
        },
        {
          id: 'T5-T4-Q3',
          category: 'identify',
          type: 'mc',
          prompt: 'What is a backbone cable?',
          options: [
            'A UTP cable from a PC to a switch',
            'A satellite link between two countries',
            'A copper cable from a router to devices',
            'One fibre optic cable that several LAN segments hang off',
          ],
          answer: 3,
          hint: 'It joins LAN segments, often between buildings.',
          explanation: 'When several LAN segments hang off one fibre optic cable it is called a backbone. Fibre is used because lightning does not affect it.',
          skills: ['T5-S4'],
        },
      ],
    },
    {
      id: 'T5-T5',
      title: 'Unbounded (wireless) media',
      sections: ['5.5', '5.5.1', '5.5.2', '5.5.2.1', '5.5.2.2'],
      skills: ['T5-S5'],
      explanation: [
        'Nodes do not have to be connected with cabling. Wireless networks use the air to transmit signals such as Bluetooth, infrared beams, microwaves, satellites or laser light. Each type uses a different frequency (measured in Hertz, or cycles per second) so the signals remain separate.',
        'Microwave transmissions are used for long distances and can be terrestrial (land-based) or satellite (above the surface of the earth).',
        'Terrestrial microwave systems use the line-of-sight method between two antennas and can transmit over ranges of 50 km provided there is no obstacle in the way.',
        'Satellites have transponders. A transponder receives signals, converts them into a different frequency, boosts them and sends them to a ground station that must be in line-of-sight of the satellite.',
        'Geo-stationary satellites are in a fixed position above the earth, rotating at the same speed as the earth, so they appear to stay in the same place; they are excellent for TV broadcasting. Low-orbit satellites are much nearer the earth and circle it every few hours; they are better for interactive communication because there is little delay.',
        'All microwave transmissions are affected by adverse weather conditions such as lightning.',
        'Radio-wave transmissions (short distances) are used by radio, TV and cellular phones. Low-frequency radio waves can travel through walls and an entire building. Wi-Fi and Bluetooth both use radio waves.',
      ],
      vocabulary: [
        { term: 'Frequency', definition: 'Measured in Hertz (cycles per second); each type of wireless signal uses a different frequency so signals stay separate.' },
        { term: 'Terrestrial microwave', definition: 'Land-based microwave using line-of-sight between two antennas, over ranges of about 50 km.' },
        { term: 'Transponder', definition: 'A device on a satellite that receives signals, converts them to a different frequency, boosts them and sends them to a ground station.' },
        { term: 'Geo-stationary', definition: 'A satellite in a fixed position above the earth that rotates at the same speed as the earth, so it appears to stay in the same place.' },
        { term: 'Low-orbit satellite', definition: 'A satellite much nearer the earth that circles it every few hours; little delay, good for interactive communication.' },
      ],
      workedExamples: [
        {
          code: 'Long distance  -> microwave\n                  terrestrial: line-of-sight, about 50 km\n                  satellite: geo-stationary (TV) or low-orbit (interactive)\nShort distance -> radio waves (Wi-Fi, Bluetooth, cellphones)',
          explanation: 'A quick way to choose the type of unbounded transmission by distance, as in Check Point 2.',
        },
      ],
      misconceptions: [
        'Geo-stationary satellites do not move. Wrong: they rotate at the same speed as the earth, so they only appear to stay in the same place.',
        'Terrestrial microwave can pass through mountains. Wrong: it uses line-of-sight, so there must be no obstacle between the antennas.',
      ],
      questions: [
        {
          id: 'T5-T5-Q1',
          category: 'define',
          type: 'mc',
          prompt: 'What does geo-stationary mean?',
          options: [
            'The satellite orbits close to the earth every few hours',
            'The satellite is fixed above the earth and rotates at the same speed as it',
            'The satellite is land-based and uses line-of-sight',
            'The satellite only transmits on low radio frequencies',
          ],
          answer: 1,
          hint: 'It appears to hang in the same spot in the sky.',
          explanation: 'Geo-stationary satellites are in a fixed position above the earth and rotate at the same speed as the earth, so they appear to stay in the same place.',
          skills: ['T5-S5'],
        },
        {
          id: 'T5-T5-Q2',
          category: 'identify',
          type: 'tf',
          prompt: 'True or false: terrestrial microwave systems can transmit over ranges of about 50 km, provided there is no obstacle in the way.',
          answer: true,
          hint: 'Terrestrial microwave uses line-of-sight between two antennas.',
          explanation: 'Terrestrial microwave uses line-of-sight between two antennas and can cover about 50 km if nothing blocks the path.',
          skills: ['T5-S5'],
        },
        {
          id: 'T5-T5-Q3',
          category: 'apply',
          type: 'mc',
          prompt: 'Which type of wireless transmission is suited to long distances?',
          options: [
            'Microwave',
            'Bluetooth',
            'Infrared',
            'Wi-Fi',
          ],
          answer: 0,
          hint: 'The textbook heading pairs one type with long distances and radio waves with short distances.',
          explanation: 'Microwave transmissions (terrestrial or satellite) are used for long distances. Wi-Fi and Bluetooth use radio waves for short distances.',
          skills: ['T5-S5'],
        },
      ],
    },
    {
      id: 'T5-T6',
      title: 'Network classification',
      sections: ['5.6', '5.6.1', '5.6.2', '5.6.3', '5.6.4', '5.6.5', '5.6.6'],
      skills: ['T5-S6'],
      explanation: [
        'Networks can be classified according to the distances covered: LAN, MAN, WAN, GAN, PAN and HAN.',
        'LAN (Local Area Network): a network set up in a limited physical location such as a building or a campus, for example a school network.',
        'MAN (Metropolitan Area Network): LANs interconnected using high-speed connections across a city or metropolitan area, for example a company with offices scattered across a city.',
        'WAN (Wide Area Network): interconnected LANs and/or MANs in different cities or countries, for example Edgars or a bank with branches in many cities. The WAN of a large company is often called an enterprise WAN. A worldwide WAN such as the Internet is called a GAN (Global Area Network).',
        'PAN (Personal Area Network): used by an individual to communicate, transfer and synchronise data between their own devices such as a desktop, laptop, smartphone, smart wear, tablet, printer or camera. Data moves wirelessly (for example Bluetooth) or over bounded media such as a USB cable.',
        'HAN (Home Area Network): a network within a home that connects the devices of all individuals in the home, such as computers, smartphones, tablets, routers, televisions, home security systems and smart appliances. The PANs of the individuals in the home, sharing resources, make up the HAN.',
      ],
      vocabulary: [
        { term: 'LAN', definition: 'A network in a limited physical location such as a building or campus.' },
        { term: 'MAN', definition: 'LANs interconnected using high-speed connections across a city or metropolitan area.' },
        { term: 'WAN', definition: 'Interconnected LANs and/or MANs in different cities or countries.' },
        { term: 'Enterprise WAN', definition: 'The WAN of a large company.' },
        { term: 'GAN', definition: 'A worldwide WAN such as the Internet.' },
        { term: 'PAN', definition: 'A network used by one individual to communicate and synchronise data between their own devices.' },
        { term: 'HAN', definition: 'A network in a home connecting the devices of everyone in the home; made up of the PANs of the individuals.' },
      ],
      workedExamples: [
        {
          code: 'Type  Area                      Typical use\nPAN   One person                Phone syncing with a laptop over Bluetooth\nHAN   One home                  Family sharing a router, TV and printer\nLAN   Building or campus        School network\nMAN   A city                    Company offices across a city\nWAN   Cities or countries       Bank with branches in many cities\nGAN   Worldwide                 The Internet',
          explanation: 'Each network type with its area and a typical use, as asked in Check Point 3.',
        },
      ],
      misconceptions: [
        'A PAN must be wireless. Wrong: data in a PAN can also move over bounded media such as a USB cable.',
        'A WAN is just a big LAN in one building. Wrong: a WAN joins LANs and/or MANs across different cities or countries.',
      ],
      questions: [
        {
          id: 'T5-T6-Q1',
          category: 'classify',
          type: 'mc',
          prompt: 'A company links the LANs at its offices around Cape Town using high-speed connections. Which type of network is this?',
          options: ['PAN', 'GAN', 'HAN', 'MAN'],
          answer: 3,
          hint: 'The network covers one city.',
          explanation: 'A MAN is made up of LANs interconnected using high-speed connections across a city or metropolitan area.',
          skills: ['T5-S6'],
        },
        {
          id: 'T5-T6-Q2',
          category: 'explain',
          type: 'tf',
          prompt: 'True or false: the PANs of the individuals in a home, sharing resources, make up the HAN.',
          answer: true,
          hint: 'Think of how a home network is built from each person\'s devices.',
          explanation: 'A HAN connects the devices of all individuals in the home; the textbook says the PANs of the individuals, sharing resources, make up the HAN.',
          skills: ['T5-S6'],
        },
        {
          id: 'T5-T6-Q3',
          category: 'distinguish',
          type: 'tf',
          prompt: 'True or false: a PAN can only transfer data wirelessly.',
          answer: false,
          hint: 'How else can you move photos from your phone to your laptop?',
          explanation: 'PAN data can be transferred wirelessly using Bluetooth, for example, or using bounded media such as a USB cable.',
          skills: ['T5-S6'],
        },
      ],
    },
    {
      id: 'T5-T7',
      title: 'The home network',
      sections: ['5.7', '5.7.1', '5.7.2', '5.7.3'],
      skills: ['T5-S7', 'T5-S8'],
      explanation: [
        'An Internet-connected home network consists of a variety of hardware and software components.',
        'A router is a small electronic device that joins computer networks together using wired or wireless connections. In a home or small office it connects all the nodes to networks outside the home, namely the Internet. ADSL and fibre lines require routers: the telephone line plugs into an ADSL router, and the fibre line into a fibre router.',
        'A Wi-Fi router creates a Wi-Fi hotspot. Devices with Wi-Fi can connect if they are within range and have access rights (valid passwords). With correct setup, devices connected wirelessly can also connect to one another.',
        'Fibre in the home: a fibre optic backbone cable runs from a local distribution node to your street. Fibre runs from the distribution box at your boundary wall into your home. An ONT (Optical Network Terminal) connects that fibre to your router. Copper cables can then run from the router to devices, or devices connect wirelessly.',
        'A firewall is a system designed to prevent unauthorised access to or from a private network. It can be hardware, software or a combination of both. It acts like a one-way digital gate: it blocks devices on the Internet from accessing your network but allows your devices to connect to the Internet.',
        'A firewall is not the only protection. Other strategies covered in this unit include user logons with access rights (network access control), valid Wi-Fi passwords, network security software, filtering Internet access and a proxy server that checks all traffic.',
      ],
      vocabulary: [
        { term: 'Router', definition: 'A small electronic device that joins computer networks together using wired or wireless connections.' },
        { term: 'Wi-Fi hotspot', definition: 'Created by a Wi-Fi router so devices in range with valid passwords can connect wirelessly.' },
        { term: 'ONT', definition: 'Optical Network Terminal: the device that connects the fibre wired to the outside of your house to your router.' },
        { term: 'Firewall', definition: 'A system designed to prevent unauthorised access to or from a private network; hardware, software or both.' },
      ],
      workedExamples: [
        {
          code: 'Local distribution node\n  -> fibre backbone cable to your street\n  -> distribution box at your boundary wall\n  -> ONT (Optical Network Terminal)\n  -> router (with firewall)\n  -> devices (copper cable or Wi-Fi)',
          explanation: 'The simplified path of fibre into a home. The ONT is the link between the fibre and the router, and the router shares the connection with every device.',
        },
      ],
      misconceptions: [
        'A firewall stops your own devices from using the Internet. Wrong: it is a one-way gate that blocks outside access while letting your devices connect out.',
        'Any device in range can join a Wi-Fi router. Wrong: devices also need access rights, such as a valid password.',
      ],
      questions: [
        {
          id: 'T5-T7-Q1',
          category: 'define',
          type: 'mc',
          prompt: 'What is the main function of the router in a home network?',
          options: [
            'It connects all the nodes in the home to the Internet',
            'It converts light pulses into satellite microwaves',
            'It stores all the family\'s files on a central disk',
            'It boosts signals on UTP cables longer than 100 m',
          ],
          answer: 0,
          hint: 'A router joins networks together.',
          explanation: 'A router joins computer networks together. In a home it connects all the nodes in the network to networks outside the home, namely the Internet.',
          skills: ['T5-S7'],
        },
        {
          id: 'T5-T7-Q2',
          category: 'identify',
          type: 'mc',
          prompt: 'Which device connects the fibre that has been wired to the outside of your house to your router?',
          options: [
            'A switch',
            'A repeater',
            'An RJ45 connector',
            'An ONT (Optical Network Terminal)',
          ],
          answer: 3,
          hint: 'Its name contains the word optical.',
          explanation: 'An ONT (Optical Network Terminal) connects the fibre wired to the outside of the house to the router.',
          skills: ['T5-S7'],
        },
        {
          id: 'T5-T7-Q3',
          category: 'explain',
          type: 'mc',
          prompt: 'Why is it important to set up a firewall when a network connects to the Internet?',
          options: [
            'To increase the bandwidth of the Internet connection',
            'To stop intruders on the Internet accessing the private network',
            'To let devices without passwords join the Wi-Fi',
            'To replace the need for a router in the home',
          ],
          answer: 1,
          hint: 'Firewalls are about unauthorised access.',
          explanation: 'Firewalls prevent intruders on the Internet from accessing a private network that is connected to the Internet.',
          skills: ['T5-S8'],
        },
      ],
    },
    {
      id: 'T5-T8',
      title: 'Client-server networks',
      sections: ['5.8', '5.8.1', '5.8.1.1', '5.8.2'],
      skills: ['T5-S9', 'T5-S10'],
      explanation: [
        'A server computer shares resources with other computers in a network. The computers that connect to it are called client computers because they use the services of the server. A network may have several servers, each with a specific purpose, and one server can also perform more than one function, such as sharing files and printers.',
        'A file server has large hard disk capacity to store files for network users. A print server has one or many high-speed printers attached for sharing. A web server (hardware and software) accepts requests for web pages and sends them to clients. An email server stores incoming mail for users and sends out outgoing messages.',
        'A proxy server is a server through which all web content passes. It sits between clients and servers, intercepting and checking traffic and disallowing unauthorised users. It also caches previously accessed web documents: it checks its cache first and serves the document if it is there; otherwise it obtains it from the Internet.',
        'Local servers (located in the organisation) give physical control over the setup and critical data, and access does not rely on the Internet, but the organisation pays for setup and IT staff to manage them.',
        'Cloud servers need no continued upgrading of on-site hardware; storage is added when needed and you pay only for what you use. Data can be backed up as often as every 15 minutes. If the Internet connection is down, users have no access to the data.',
        'The client operating system must let the client connect to the server and use its resources. The server should not be used as a workstation. Server operating system functions include storing user details (logons and access rights), letting computers connect and disconnect and allocating IP addresses, file and printer sharing, and monitoring all network traffic.',
        'The server should have higher hardware specifications than the clients: a faster processor, more RAM and more local storage.',
      ],
      vocabulary: [
        { term: 'Server', definition: 'A computer which shares resources with other computers in a network.' },
        { term: 'Client', definition: 'A computer that connects to the server and uses its services.' },
        { term: 'Proxy server', definition: 'A server through which all web content passes; it checks traffic for security and caches web documents.' },
        { term: 'Caching', definition: 'Storing previously accessed web documents to speed up download time.' },
        { term: 'Local server', definition: 'A server located in the organisation itself.' },
        { term: 'Cloud server', definition: 'A server accessed over the Internet, where storage is added as needed and you pay for what you use.' },
      ],
      workedExamples: [
        {
          code: '                 Local server             Cloud server\nControl          Physical control         Provider manages hardware\nInternet down    Still accessible         No access to data\nCost             Setup and IT staff       Pay only for what you use\nUpgrades         Buy new hardware         Add storage when needed\nBackups          Done by IT staff         As often as every 15 minutes',
          explanation: 'A comparison to help justify a choice of local or cloud server, as in Check Point 4.',
        },
      ],
      misconceptions: [
        'Each server can only do one job. Wrong: in some networks one server performs more than one function, for example sharing files and printers.',
        'A cloud server keeps working when the Internet is down. Wrong: without an Internet connection users have no access to cloud data.',
      ],
      questions: [
        {
          id: 'T5-T8-Q1',
          category: 'sequence',
          type: 'order',
          prompt: 'Order how a proxy server handles a request for a document that is NOT yet in its cache.',
          items: [
            'The proxy obtains the document from the Internet',
            'A client requests a document',
            'The proxy serves the document to the client',
            'The proxy checks its cache',
          ],
          answer: [1, 3, 0, 2],
          hint: 'The proxy always looks in its cache before going to the Internet.',
          explanation: 'When a document is requested, the proxy first checks its cache. If the document is not there, it obtains it from the Internet and then serves it to the client.',
          skills: ['T5-S9'],
        },
        {
          id: 'T5-T8-Q2',
          category: 'identify',
          type: 'mc',
          prompt: 'Which of these is a function of a server operating system?',
          options: [
            'Storing users\' logons and access rights',
            'Converting light pulses into electronic data',
            'Acting as a workstation for typing documents',
            'Boosting signals on long lengths of cable',
          ],
          answer: 0,
          hint: 'The server OS manages users and computers on the network.',
          explanation: 'Server OS functions include storing user details with logons and access rights, connecting computers and allocating IP addresses, file and printer sharing and monitoring traffic.',
          skills: ['T5-S10'],
        },
        {
          id: 'T5-T8-Q3',
          category: 'distinguish',
          type: 'tf',
          prompt: 'True or false: with a local server, users lose access to the data whenever the Internet connection is down.',
          answer: false,
          hint: 'Where is a local server physically located?',
          explanation: 'A local server is located in the organisation, so there is no need to rely on the Internet. Losing access when the Internet is down is a disadvantage of cloud servers.',
          skills: ['T5-S10'],
        },
        {
          id: 'T5-T8-Q4',
          category: 'apply',
          type: 'mc',
          prompt: 'A school with an unreliable Internet connection needs constant access to learner records. Which option suits it best?',
          options: [
            'Cloud server, because data is backed up every 15 minutes',
            'Local server, because access does not rely on the Internet',
            'Cloud server, because it works without any Internet connection',
            'Local server, because it needs no setup or IT staff',
          ],
          answer: 1,
          hint: 'What happens to cloud access when the Internet is down?',
          explanation: 'A local server does not rely on the Internet for access, which matters when the connection is unreliable. The trade-off is the cost of setting it up and IT staff to manage it.',
          skills: ['T5-S10'],
        },
      ],
    },
    {
      id: 'T5-T9',
      title: 'Network access control and the advantages of networks',
      sections: ['5.9', '5.10', '5.10.1', '5.10.2', '5.10.3', '5.10.4', '5.10.4.1', '5.10.4.2', '5.10.4.3', '5.10.5', '5.10.6'],
      skills: ['T5-S8', 'T5-S11'],
      explanation: [
        'Network access control (NAC): a computer can only access a network if its settings and the user\'s login comply with the protocols (rules) of the network. Users are authenticated by verifying their logon information, then awarded rights and permissions according to their user profile (see Learning Unit 4.3.1). A learner may access student files and print in the computer centre, but not change workstation settings, open administration files or print in the administration building.',
        'Communication: networking allows email and messaging to send messages and files to people anywhere in the world, sharing ideas, facts, news and research.',
        'File sharing: an authorised user can access a file saved on another computer in the network, saving the time of copying files with storage devices. Many people can update a database so it stays up to date and accurate, and a storage server can make huge storage capacity available.',
        'Printer and resource sharing: expensive devices such as printers and routers are shared. Four people at home with four computers would otherwise need four routers and four printers; networked, one router and one printer serve all four.',
        'Centralisation: network applications can be loaded on a central server and delivered to machines on request, or used online as web-based applications such as Google Docs or MS Office 365 from any device with Internet access and an account. Files can be stored on a central file server, and data such as shared calendars, email and contacts in suites like Office 365 or G-Suite are shared and synchronised with smartphones. Shared documents can be viewed or edited according to the permissions set by the owner.',
        'Data transfer: the data transfer rate is the amount of data that can be sent between two points on a network in a given time. A low rate makes transferring large amounts of data to the cloud a bad idea. The network setup, hardware and available bandwidth (maximum transfer capacity) all affect it.',
        'Productivity: networks make communication fast and efficient, make information easily accessible and enable collaboration. Cloud storage and remote access make data easy to get and share, and apps for shared calendars, surveys, team video calls and task organisers improve productivity.',
      ],
      vocabulary: [
        { term: 'Network access control (NAC)', definition: 'Only allowing a computer onto the network if its settings and the user\'s login comply with the network\'s protocols (rules).' },
        { term: 'Authentication', definition: 'Verifying a user\'s logon information when they log onto the network.' },
        { term: 'File sharing', definition: 'Accessing a file saved on another computer in the network, as long as you are authorised.' },
        { term: 'Network application', definition: 'An application loaded on a central server or used online, rather than installed on every machine.' },
        { term: 'Data transfer rate', definition: 'The amount of data that can be sent between two points on a network in a given time.' },
      ],
      workedExamples: [
        {
          code: 'User:     Grade 10 learner\nProfile:  Student\nAllowed:  student files, printer in the computer centre\nDenied:   workstation settings, administration files,\n          printer in the administration building',
          explanation: 'After authentication, NAC awards rights based on the user profile, so a learner can only use the resources a student is permitted to use.',
        },
      ],
      misconceptions: [
        'Once you have logged on, you can access everything on the network. Wrong: rights are awarded according to your profile and you only get permission for certain resources.',
        'Online applications like Google Docs only work on the computer where you created the document. Wrong: they can be used from any device with Internet access and an account.',
      ],
      questions: [
        {
          id: 'T5-T9-Q1',
          category: 'explain',
          type: 'tf',
          prompt: 'True or false: once a user is authenticated, they are allocated permissions to use only certain resources, according to their profile.',
          answer: true,
          hint: 'Think about what a learner may and may not access on the school network.',
          explanation: 'After authentication, rights are awarded according to the user\'s profile, and the user is allocated permissions to use certain resources only.',
          skills: ['T5-S8'],
        },
        {
          id: 'T5-T9-Q2',
          category: 'explain',
          type: 'mc',
          prompt: 'How does storing files on a central file server help avoid unnecessary duplication of data?',
          options: [
            'Each user keeps a separate copy on every machine',
            'Files are copied onto a flash drive before each lesson',
            'One central copy is opened from any computer by authorised users',
            'The router deletes duplicate files automatically',
          ],
          answer: 2,
          hint: 'Think about how many copies exist when files are centralised.',
          explanation: 'Instead of loading files on every machine, files are stored on a central file server and accessed from any computer by users who have access, so there is one up-to-date copy.',
          skills: ['T5-S11'],
        },
        {
          id: 'T5-T9-Q3',
          category: 'predict',
          type: 'mc',
          prompt: 'Thabo has a very low data transfer rate. What is likely to happen when he uploads 20 GB of videos to cloud storage?',
          options: [
            'The upload will take a very long time',
            'The videos will be deleted by the cloud service',
            'The upload will be instant because the cloud is fast',
            'His router will block the upload completely',
          ],
          answer: 0,
          hint: 'Transfer rate is the amount of data sent in a given time.',
          explanation: 'The data transfer rate is the amount of data sent between two points in a given time. With a low rate, transferring large amounts of data to the cloud is slow, which is why the textbook says it would not be a good idea.',
          skills: ['T5-S11'],
        },
      ],
    },
    {
      id: 'T5-T10',
      title: 'Disadvantages of networks',
      sections: ['5.11', '5.11.1', '5.11.2', '5.11.3', '5.11.4'],
      skills: ['T5-S12'],
      explanation: [
        'Security issues: networked computers are more susceptible to unauthorised access than stand-alone computers, so they need additional network security software to prevent theft of confidential and private data. Users are allocated rights to log on and access specific devices, and Internet access may be filtered according to the organisation\'s policy. Controlling access from inside and outside the organisation is key to good security.',
        'Spread of computer viruses: if one computer on a network gets a virus, others may become affected too. The spread is rapid because all computers are connected, and worse when the network is connected to the Internet.',
        'Cost: the initial setup cost can be high. Routers, switches and file servers may be needed, workstations need network interface cards if they have no built-in network cards, and computers must be connected with cables. A wireless network needs a wireless access point and computers that can receive wireless signals or wireless network cards. Cloud storage can reduce the cost of physical storage, but network devices and Internet connections still cost money.',
        'Dependency on central servers: if a server such as the file server or email server is faulty, the system loses its functionality. Servers are expensive to repair or replace and need constant maintenance.',
        'A stand-alone computer is one that is not connected to a network; the opposite is a networked computer. Because of the points above, a stand-alone computer is less exposed to unauthorised network access and network-spread viruses, does not depend on a server and avoids network setup costs, but it loses the advantages of sharing.',
      ],
      vocabulary: [
        { term: 'Stand-alone computer', definition: 'A computer that is not connected to a network.' },
        { term: 'Network interface card', definition: 'Hardware a workstation needs to connect to a network if it has no built-in network card.' },
        { term: 'Wireless access point', definition: 'A device that sends out wireless signals so computers can connect without cables.' },
        { term: 'Network security software', definition: 'Additional software networked computers need to prevent theft of confidential and private data.' },
      ],
      workedExamples: [
        {
          code: 'Disadvantage        Why it happens\nSecurity issues     More open to unauthorised access\nVirus spread        All computers are connected\nCost                Routers, switches, servers, NICs, cables, access points\nServer dependency   A faulty server stops the system',
          explanation: 'A summary of the four disadvantages of computer networks.',
        },
      ],
      misconceptions: [
        'Using cloud storage makes a network free to run. Wrong: it reduces the cost of physical storage, but network-enabled devices and Internet connections still cost money.',
        'A virus on one networked computer stays on that computer. Wrong: because all the computers are connected, viruses can spread rapidly to others.',
      ],
      questions: [
        {
          id: 'T5-T10-Q1',
          category: 'identify',
          type: 'mc',
          prompt: 'If you connect the computers without cables, which device do you need to send out wireless signals?',
          options: [
            'A repeater',
            'A wireless access point',
            'An RJ45 connector',
            'An ONT',
          ],
          answer: 1,
          hint: 'It is a point that gives wireless access.',
          explanation: 'A wireless network needs a wireless access point to send out wireless signals, plus computers that can receive them or wireless network cards.',
          skills: ['T5-S12'],
        },
        {
          id: 'T5-T10-Q2',
          category: 'explain',
          type: 'tf',
          prompt: 'True or false: networked computers are more susceptible to unauthorised access than stand-alone computers.',
          answer: true,
          hint: 'More connections means more ways in.',
          explanation: 'Networked computers are more susceptible to unauthorised access, so they need additional network security software and access control.',
          skills: ['T5-S12'],
        },
        {
          id: 'T5-T10-Q3',
          category: 'distinguish',
          type: 'mc',
          prompt: 'Which is an advantage of a stand-alone computer compared to a networked computer?',
          options: [
            'It can print to printers shared by others',
            'It can share files instantly with colleagues',
            'It can run applications from a central server',
            'It is not exposed to viruses spreading across a network',
          ],
          answer: 3,
          hint: 'Three of these options need a network.',
          explanation: 'A stand-alone computer is not connected to a network, so it avoids network virus spread, unauthorised network access and server dependency, but cannot share resources.',
          skills: ['T5-S12'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't5-branch-blackout',
    unitId: UNIT.id,
    title: 'Branch Blackout',
    icon: 'globe',
    summary: 'Restore a national bank WAN before month-end payments fail.',
    briefing: 'Lightning has struck during month-end and a major bank\'s WAN is collapsing branch by branch, from Durban to Cape Town. Angelo must diagnose broken cables, a failed backbone and dropped satellite links before salaries fail to pay out. Every wrong call keeps another city offline.',
    tickerMessages: [
      'Storm over Gauteng: bank reports intermittent outages at several branches',
      'Durban branch offline after copper cables fried by electrical surge',
      'Engineers report the fibre backbone between buildings is still standing',
      'Satellite link to remote branches showing heavy delay in bad weather',
      'Salary payments for thousands now at risk as the WAN keeps dropping',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T5-S2', 'T5-S3', 'T5-S4', 'T5-S5', 'T5-S6'],
    victoryMessage: 'Every branch is back online. Your cable and wireless know-how saved month-end.',
    failMessage: 'The WAN has gone dark and the payments have bounced. Review your media and network types and try again.',
  },
  {
    id: 't5-server-room-siege',
    unitId: UNIT.id,
    title: 'Server Room Siege',
    icon: 'shield',
    summary: 'Stop a virus outbreak on a 1200-learner school network.',
    briefing: 'The night before exams, a virus is racing through the school LAN of 1200 learners and someone is trying to reach the exam papers on the file server. Angelo must lock down the firewall, user rights and servers before the papers leak. The whole school is depending on you.',
    tickerMessages: [
      'Unusual traffic detected on the school network after hours',
      'Several lab computers infected as the virus spreads across the LAN',
      'Intruder probing the router from the Internet, firewall under pressure',
      'Learner account caught trying to open administration files',
      'File server holding exam papers is starting to slow down',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T5-S8', 'T5-S9', 'T5-S10', 'T5-S11', 'T5-S12'],
    victoryMessage: 'The network is locked down and the exam papers are safe. The school owes you one.',
    failMessage: 'The papers leaked and the network is crippled. Brush up on firewalls, access control and servers.',
  },
];
