// Theory Learning Unit 6: Boolean Logic (Exploring IT: Theory Grade 10, 2nd ed)
import { ToggleLeft } from 'lucide-react';

export const UNIT = { id: 'T6', number: 6, name: 'Boolean Logic', worldId: 'boolean-logic' };

export const SKILLS = {
  'T6-S1': { unit: 'T6', name: 'Bits and Boolean values', description: 'Explain how switches, bits and voltages represent TRUE (1) and FALSE (0), and define Boolean values and variables.', sections: ['6.1'] },
  'T6-S2': { unit: 'T6', name: 'Relational operators', description: 'Decide whether Boolean logical statements, including those using >, <, =, !=, >= and <=, are TRUE or FALSE.', sections: ['6.2', '6.2.1'] },
  'T6-S3': { unit: 'T6', name: 'The NOT operator', description: 'Apply NOT to swap TRUE and FALSE (1 and 0) and describe NOT A on a Venn diagram.', sections: ['6.2.2', '6.2.2.1'] },
  'T6-S4': { unit: 'T6', name: 'The AND operator', description: 'Apply AND, which is TRUE only when BOTH statements are TRUE, using the series-switch and intersection models.', sections: ['6.2.2', '6.2.2.2'] },
  'T6-S5': { unit: 'T6', name: 'The OR operator', description: 'Apply OR, which is TRUE when EITHER or both statements are TRUE, using the parallel-switch and union models.', sections: ['6.2.2', '6.2.2.3'] },
  'T6-S6': { unit: 'T6', name: 'Order of operations', description: 'Evaluate logical expressions in the order brackets, NOT, AND, OR, showing all workings.', sections: ['6.2.2.4'] },
  'T6-S7': { unit: 'T6', name: 'Functional notation', description: 'Read and write Boolean functions using + for OR, . for AND and \' for NOT, and evaluate them for given values.', sections: ['6.2.3', '6.2.3.1'] },
  'T6-S8': { unit: 'T6', name: 'Two-variable truth tables', description: 'Build 4-row truth tables for two variables and use them to find when a function is TRUE or to prove two expressions equal.', sections: ['6.2.3', '6.2.3.1'] },
  'T6-S9': { unit: 'T6', name: 'Three-variable truth tables', description: 'Build 8-row truth tables for three variables and read off the rows where the function is TRUE.', sections: ['6.2.3.2'] },
  'T6-S10': { unit: 'T6', name: 'De Morgan\'s Law', description: 'Negate whole expressions with De Morgan\'s Law: negate each variable and swap AND with OR, keeping brackets.', sections: ['6.2.4'] },
  'T6-S11': { unit: 'T6', name: 'Modelling statements', description: 'Turn English statements into Boolean variables and functions, and turn results back into English.', sections: ['6.2.3.1', '6.2.3.2', '6.2.4'] },
};

export const SKILL_HINTS = {
  'T6-S1': 'Switch on = 1 = TRUE, off = 0 = FALSE; a single switch is a bit; 1 is 5 volts, 0 is 0 volts; 2-5 V reads as 1, 0-0.8 V reads as 0, 0.8-2 V not used; Boolean value is only TRUE or FALSE; Boolean variable stores one',
  'T6-S2': 'Boolean logical statement is either true or false; relational operators compare two values: > < = != (or <>) >= <=; e.g. 5 >= 5 TRUE, 5 > 5 FALSE, 0 != 0 FALSE, 10 < 10.01 TRUE',
  'T6-S3': 'NOT swaps the value: NOT 0 = 1, NOT 1 = 0; Venn diagram: NOT A is everything outside A; e.g. NOT 5 > 3 is FALSE, NOT 3 = 2 is TRUE',
  'T6-S4': 'AND is TRUE only if BOTH statements are TRUE; switches in series, lamp on only if both closed; Venn intersection; truth table 0,0,0,1',
  'T6-S5': 'OR is TRUE if EITHER or both statements are TRUE; switches in parallel; Venn union; truth table 0,1,1,1; FALSE only when both FALSE',
  'T6-S6': 'Order: 1 brackets, 2 NOT, 3 AND, 4 OR; first replace each statement with TRUE/FALSE, then evaluate; e.g. TRUE OR TRUE AND FALSE = TRUE OR FALSE = TRUE',
  'T6-S7': 'Functional notation: OR is +, AND is a dot (.) or left out, NOT is \' (B\' = NOT B); A AND NOT B is F(A,B) = A.B\'; evaluate F(0,1) by substituting values; true rows become terms like X\'Y\' + X\'Y + XY\'',
  'T6-S8': 'Two variables give 2^2 = 4 rows 00, 01, 10, 11; right column alternates every line, left column in groups of 2; prove equality by matching result columns, e.g. X + X\'Y = X + Y, A\' + AB = A\' + B',
  'T6-S9': 'Three variables give 2^3 = 8 rows 000 to 111; e.g. A + B.C is 0,0,0,1,1,1,1,1; X(Y + Z) is 0,0,0,0,0,1,1,1; AB + A\'C + BC = AB + A\'C',
  'T6-S10': 'De Morgan: (A + B)\' = A\'.B\' and (A.B)\' = A\' + B\'; negate each variable and change AND to OR and OR to AND; keep brackets: (X + Y\'Z)\' = X\'.(Y + Z\'), (AB + CD)\' = (A\' + B\')(C\' + D\')',
  'T6-S11': 'Let a Boolean variable stand for each statement, e.g. A = Fazul is in Grade 10; backup F = C + W + M, not backed up C\'.W\'.M\'; colours F = P(W + C), no colours P\' + W\'C\'; no tea or coffee (T + C)\' = T\'.C\'',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Logic Gate Jungle',
  subtitle: 'Unit 6 \u00b7 Boolean Logic',
  color: 'emerald',
  glow: 'ja-glow-emerald',
  bg: 'ja-w-boolean-logic',
  icon: ToggleLeft,
  blurb: 'Every vine is a switch and every path is TRUE or FALSE. Master NOT, AND, OR, truth tables and De Morgan\'s Law to find the way through.',
};

export const LEVELS = [
  { id: 't6-l1', name: 'Switch Clearing', subtitle: 'Bits, Boolean statements, relational operators and NOT', challengeIds: ['t6-c1', 't6-c2', 't6-c3', 't6-c4', 't6-c5', 't6-c6'] },
  { id: 't6-l2', name: 'Series and Parallel Vines', subtitle: 'AND, OR and the order of operations', challengeIds: ['t6-c7', 't6-c8', 't6-c9', 't6-c10', 't6-c11', 't6-c12'] },
  { id: 't6-l3', name: 'Truth Table Temple', subtitle: 'Functional notation and two- and three-variable truth tables', challengeIds: ['t6-c13', 't6-c14', 't6-c15', 't6-c16', 't6-c17', 't6-c18', 't6-c19'] },
  { id: 't6-l4', name: 'De Morgan\'s Canopy', subtitle: 'Boss: De Morgan\'s Law and mixed review of the whole unit', challengeIds: ['t6-c20', 't6-c21', 't6-c22', 't6-c23', 't6-c24', 't6-c25', 't6-c26'] },
];

export const CHALLENGES = {
  't6-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'A wire inside a computer carries 3.5 volts. According to the textbook, how is this voltage read?',
    options: ['As a 1 (TRUE)', 'As a 0 (FALSE)', 'Not at all: that range is unused', 'As half of a bit'],
    answer: 0,
    hint: 'Check which voltage band 3.5 V falls into: 0 to 0.8, 0.8 to 2, or 2 to 5.',
    explanation: 'Any value between 2 and 5 volts is detected as a 1 (TRUE). Values from 0 to 0.8 volts are a 0, and 0.8 to 2 volts is not used to avoid confusion.',
    skills: ['T6-S1'],
  },
  't6-c2': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each term to its textbook meaning.',
    pairs: [
      { left: 'Bit', right: 'A single switch that is on (1) or off (0)' },
      { left: 'Boolean value', right: 'A value that can only be TRUE or FALSE (0 or 1)' },
      { left: 'Boolean variable', right: 'A variable that stores a Boolean value' },
      { left: 'Boolean logical statement', right: 'A statement that is either true or false' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'One is about hardware, one is about a value, one is about storage and one is about a sentence.',
    explanation: 'A bit is one switch. A Boolean value is TRUE or FALSE, a Boolean variable stores such a value, and a Boolean logical statement such as "3 + 3 = 6" is either true or false.',
    skills: ['T6-S1', 'T6-S2'],
  },
  't6-c3': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Activity 1: write the result of each statement. Type TRUE or FALSE in capitals.',
    code: 'Statement            Result\n6 < 2                ?\n5 >= 5               ?\n5 > 5                ?\n0 != 0               ?\n10 < 10.01           ?\n0.000001 > 0.0001    ?',
    rows: [
      { label: '6 < 2', answer: 'FALSE' },
      { label: '5 >= 5', answer: 'TRUE' },
      { label: '5 > 5', answer: 'FALSE' },
      { label: '0 != 0', answer: 'FALSE' },
      { label: '10 < 10.01', answer: 'TRUE' },
      { label: '0.000001 > 0.0001', answer: 'FALSE' },
    ],
    hint: '>= is TRUE when the values are equal; > is not. Count the zeros after the decimal point carefully.',
    explanation: '5 >= 5 is TRUE because 5 equals 5, but 5 > 5 is FALSE. 0 != 0 is FALSE because 0 does equal 0, and 0.000001 is smaller than 0.0001, so that statement is FALSE.',
    skills: ['T6-S2'],
  },
  't6-c4': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'There is no single keyboard key for "not equal to". Which combination does this Learning Unit use?',
    options: ['=!', '=/=', '!=', '><'],
    answer: 2,
    hint: 'The book says the symbol can be written two ways, and chooses the one with an exclamation mark first.',
    explanation: 'Not equal to can be written as != or <>. The textbook uses != in this Learning Unit. Similarly >= stands for greater than or equal to and <= for less than or equal to.',
    skills: ['T6-S2'],
  },
  't6-c5': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'The statement NOT 4 != 2 is TRUE.',
    answer: false,
    hint: 'First decide whether 4 != 2 is TRUE or FALSE, then apply NOT.',
    explanation: '4 != 2 is TRUE because 4 is not equal to 2. NOT swaps the value, so NOT 4 != 2 is FALSE.',
    skills: ['T6-S3', 'T6-S2'],
  },
  't6-c6': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'On a Venn diagram with a single circle labelled A, which area represents NOT A?',
    options: ['The circle A itself', 'Only the edge of circle A', 'Half of circle A', 'Everything outside circle A'],
    answer: 3,
    hint: 'NOT swaps the value: where A is 1, NOT A is 0.',
    explanation: 'NOT swaps the values for A, so NOT A is TRUE exactly where A is FALSE. On the Venn diagram that is everything outside circle A.',
    skills: ['T6-S3'],
  },
  't6-c7': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Two switches A and B are connected in series with a lamp. The lamp only goes on when both switches are closed. Which logical operator does this circuit represent?',
    options: ['OR', 'AND', 'NOT', 'NOT OR'],
    answer: 1,
    hint: 'In series, the current has to pass through every switch.',
    explanation: 'Switches in series represent AND: BOTH must be closed (1 or TRUE) for the lamp to be on. If either is open (0 or FALSE) the result is 0.',
    skills: ['T6-S4'],
  },
  't6-c8': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Exercise 2: evaluate each AND statement. Type TRUE or FALSE in capitals.',
    code: `5 > 3 AND 4 = 2\n3 = 2 AND Cape Town is a City\n4 != 2 AND 'L' is a capital letter\n5 >= 1 AND 5 <= 10`,
    rows: [
      { label: '5 > 3 AND 4 = 2', answer: 'FALSE' },
      { label: '3 = 2 AND Cape Town is a City', answer: 'FALSE' },
      { label: `4 != 2 AND 'L' is a capital letter`, answer: 'TRUE' },
      { label: '5 >= 1 AND 5 <= 10', answer: 'TRUE' },
    ],
    hint: 'Work out each side first. AND needs BOTH sides to be TRUE.',
    explanation: 'In the first two statements one side is FALSE (4 = 2 and 3 = 2), so AND gives FALSE. In the last two both sides are TRUE, so AND gives TRUE.',
    skills: ['T6-S4'],
  },
  't6-c9': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Exercise 3: evaluate each OR statement. Type TRUE or FALSE in capitals.',
    code: '5 > 3 OR 4 = 2\nJohannesburg is in Egypt OR 3 <= -9\n3 = 2 OR Cape Town is a City\n1 <= 3 OR 9 >= 6',
    rows: [
      { label: '5 > 3 OR 4 = 2', answer: 'TRUE' },
      { label: 'Johannesburg is in Egypt OR 3 <= -9', answer: 'FALSE' },
      { label: '3 = 2 OR Cape Town is a City', answer: 'TRUE' },
      { label: '1 <= 3 OR 9 >= 6', answer: 'TRUE' },
    ],
    hint: 'OR only needs ONE side to be TRUE. It is FALSE only when both sides are FALSE.',
    explanation: 'Johannesburg is not in Egypt and 3 is not less than or equal to -9, so both sides are FALSE and OR gives FALSE. Every other statement has at least one TRUE side, so OR gives TRUE.',
    skills: ['T6-S5'],
  },
  't6-c10': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each logical operator to its switch and Venn diagram model.',
    pairs: [
      { left: 'AND', right: 'Two switches in series; the intersection of A and B' },
      { left: 'OR', right: 'Two switches in parallel; the union of A and B' },
      { left: 'NOT', right: 'Swaps 0 and 1; everything outside circle A' },
    ],
    answer: [0, 1, 2],
    hint: 'Series means both must be closed; parallel means either one is enough.',
    explanation: 'AND is modelled by series switches and the Venn intersection, OR by parallel switches and the union, and NOT swaps the value, shown as the area outside the circle.',
    skills: ['T6-S3', 'T6-S4', 'T6-S5'],
  },
  't6-c11': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the parts of a logical expression in the order in which they are evaluated.',
    items: ['OR', 'Brackets', 'AND', 'NOT'],
    answer: [1, 3, 2, 0],
    hint: 'It works like arithmetic: brackets come first, and OR behaves like + so it comes last.',
    explanation: 'Logical expressions are evaluated in the order: 1 brackets, 2 NOT, 3 AND, 4 OR.',
    skills: ['T6-S6'],
  },
  't6-c12': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'The expression "A tomato is not edible AND a tomato is a fruit OR a potato is a vegetable" evaluates to TRUE.',
    answer: true,
    hint: 'Replace each statement with TRUE or FALSE, then do AND before OR.',
    explanation: 'It becomes FALSE AND TRUE OR TRUE. AND is done first: FALSE AND TRUE = FALSE. Then FALSE OR TRUE = TRUE.',
    skills: ['T6-S6'],
  },
  't6-c13': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'A truth table is drawn for F(A,B,C) = A + B.C. How many rows of possible values (not counting the heading) does it need?',
    options: ['6', '8', '9', '3'],
    answer: 1,
    hint: 'Each variable can be 0 or 1. Use 2 to the power of the number of variables.',
    explanation: 'With three variables the number of combinations is 2^3 = 8, the binary values 000 to 111 (decimal 0 to 7).',
    skills: ['T6-S9'],
  },
  't6-c14': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Exercise 5: evaluate each expression. Type 1 or 0.',
    code: '1 OR 0\n(1 AND 0) AND 1\n1 OR 0 OR 0 AND NOT 1\nNOT 0 OR NOT 1 OR NOT(NOT 0)',
    rows: [
      { label: '1 OR 0', answer: '1' },
      { label: '(1 AND 0) AND 1', answer: '0' },
      { label: '1 OR 0 OR 0 AND NOT 1', answer: '1' },
      { label: 'NOT 0 OR NOT 1 OR NOT(NOT 0)', answer: '1' },
    ],
    hint: '1 means TRUE and 0 means FALSE. Remember: brackets, NOT, AND, then OR.',
    explanation: '(1 AND 0) is 0, and 0 AND 1 is 0. In 1 OR 0 OR 0 AND NOT 1, NOT 1 = 0, then 0 AND 0 = 0, then 1 OR 0 OR 0 = 1. The last one is 1 OR 0 OR 0 = 1.',
    skills: ['T6-S6', 'T6-S7'],
  },
  't6-c15': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: `Exercise 5: complete the truth table for F(A,B) = A' + AB. Type 1 or 0 for each row.`,
    code: `A B | A' + AB\n0 0 | ?\n0 1 | ?\n1 0 | ?\n1 1 | ?`,
    rows: [
      { label: 'A=0, B=0', answer: '1' },
      { label: 'A=0, B=1', answer: '1' },
      { label: 'A=1, B=0', answer: '0' },
      { label: 'A=1, B=1', answer: '1' },
    ],
    hint: `A' is NOT A. Whenever A is 0, A' is 1, so the whole OR is 1.`,
    explanation: `When A = 0, A' = 1 so the result is 1. When A = 1, A' = 0 and the result equals AB, which is 0 for B = 0 and 1 for B = 1.`,
    skills: ['T6-S8'],
  },
  't6-c16': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: `The truth table for F(X,Y) = (X.Y)' is TRUE in the rows X=0,Y=0 and X=0,Y=1 and X=1,Y=0. Which expression lists exactly those TRUE rows?`,
    options: [`XY + X'Y + XY'`, `X'Y' + XY`, `X'Y' + X'Y + XY'`, `X'Y' + X'Y + XY' + XY`],
    answer: 2,
    hint: `Write one term per TRUE row: a variable that is 0 gets a ', a variable that is 1 does not.`,
    explanation: `Row 00 gives X'Y', row 01 gives X'Y and row 10 gives XY', so F(X,Y) = X'Y' + X'Y + XY', read as NOT X AND NOT Y OR NOT X AND Y OR X AND NOT Y.`,
    skills: ['T6-S7', 'T6-S8'],
  },
  't6-c17': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each expression in functional notation to how it is read.',
    pairs: [
      { left: 'A + B', right: 'A OR B' },
      { left: 'A.B', right: 'A AND B' },
      { left: `B'`, right: 'NOT B' },
      { left: `(X.Y)'`, right: 'NOT (X AND Y)' },
      { left: `A.B'`, right: 'A AND NOT B' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: `In functional notation + means OR, the dot means AND and ' means NOT.`,
    explanation: `OR is written as +, AND as a dot (which may be left out) and NOT with a '. So A AND NOT B becomes A.B' and NOT (X AND Y) becomes (X.Y)'.`,
    skills: ['T6-S7'],
  },
  't6-c18': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: `Exercise 6: find F(X,Y,Z) = (X + Y')(Y + Z) for each row. Type 1 or 0.`,
    code: `X Y Z | (X + Y')(Y + Z)\n0 0 0 | ?\n0 0 1 | ?\n0 1 1 | ?\n1 0 0 | ?\n1 0 1 | ?\n1 1 0 | ?`,
    rows: [
      { label: 'X=0, Y=0, Z=0', answer: '0' },
      { label: 'X=0, Y=0, Z=1', answer: '1' },
      { label: 'X=0, Y=1, Z=1', answer: '0' },
      { label: 'X=1, Y=0, Z=0', answer: '0' },
      { label: 'X=1, Y=0, Z=1', answer: '1' },
      { label: 'X=1, Y=1, Z=0', answer: '1' },
    ],
    hint: 'Work out each bracket separately, then AND the two results. Both brackets must be 1.',
    explanation: `For 001: (0 + 1)(0 + 1) = 1.1 = 1. For 011: (0 + 0)(1 + 1) = 0.1 = 0. For 100: (1 + 1)(0 + 0) = 1.0 = 0. For 110: (1 + 0)(1 + 0) = 1.`,
    skills: ['T6-S9'],
  },
  't6-c19': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: `A truth table shows that F(X,Y) = X(X + Y') always gives the same result as X.`,
    answer: true,
    hint: 'Work out the four rows 00, 01, 10 and 11 and compare with the X column.',
    explanation: `When X = 0 the AND gives 0. When X = 1, (1 + Y') is always 1, so the result is 1. The result column 0, 0, 1, 1 matches X exactly.`,
    skills: ['T6-S8'],
  },
  't6-c20': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: `According to De Morgan's Law, (A + B)' is equal to:`,
    options: [`A' + B'`, `A.B`, `(A.B)'`, `A'.B'`],
    answer: 3,
    hint: 'Negate each variable AND change the operator.',
    explanation: `De Morgan's Law states (A + B)' = A'.B' and similarly (A.B)' = A' + B'. Each variable is negated and OR changes to AND.`,
    skills: ['T6-S10'],
  },
  't6-c21': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: `Use De Morgan's Law to negate F(A,B,C,D) = AB + CD.`,
    options: [`(A' + B')(C' + D')`, `A'B' + C'D'`, `(A'B')(C'D')`, `A' + B' + C' + D'`],
    answer: 0,
    hint: 'Treat AB and CD as single terms first, then apply De Morgan to each term.',
    explanation: `(AB + CD)' = (AB)'.(CD)' because the OR becomes AND. Applying De Morgan to each term while keeping the brackets gives (A' + B')(C' + D').`,
    skills: ['T6-S10'],
  },
  't6-c22': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: `Exercise 7: a learner does NOT get full colours when P' + W'C' is TRUE (P = 80% of practices, W = won 75% of games, C = provincial colours). Find the result for each row. Type 1 or 0.`,
    code: `P W C | P' + W'C'\n0 0 0 | ?\n0 1 1 | ?\n1 0 0 | ?\n1 0 1 | ?\n1 1 0 | ?\n1 1 1 | ?`,
    rows: [
      { label: 'P=0, W=0, C=0', answer: '1' },
      { label: 'P=0, W=1, C=1', answer: '1' },
      { label: 'P=1, W=0, C=0', answer: '1' },
      { label: 'P=1, W=0, C=1', answer: '0' },
      { label: 'P=1, W=1, C=0', answer: '0' },
      { label: 'P=1, W=1, C=1', answer: '0' },
    ],
    hint: `If P is 0 then P' is 1 and the learner misses out. If P is 1, the result depends on W'C'.`,
    explanation: `Full colours is P(W + C); by De Morgan its negation is P' + (W + C)' = P' + W'C'. A learner who attended 80% of practices only misses colours when W = 0 and C = 0.`,
    skills: ['T6-S10', 'T6-S11', 'T6-S9'],
  },
  't6-c23': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: `A computer is backed up when there are changes to the files (C) or it is the end of the week (W) or the end of the month (M). Which expression describes when it is NOT backed up?`,
    options: [`C' + W' + M'`, `C'.W'.M'`, `(C.W.M)'`, `C + W + M'`],
    answer: 1,
    hint: `Start with F = C + W + M, negate the whole expression and apply De Morgan's Law.`,
    explanation: `The backup rule is F(C,W,M) = C + W + M. Its negation (C + W + M)' = C'.W'.M': no changes AND not the end of the week AND not the end of the month.`,
    skills: ['T6-S11', 'T6-S10'],
  },
  't6-c24': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: `Using De Morgan's Law, (X + Y'Z)' can be written as X'.Y + Z' without any brackets.`,
    answer: false,
    hint: `Y'Z is one term, so its negation must stay together.`,
    explanation: `The correct negation is X'.(Y + Z'). The brackets around the second term must be kept, otherwise AND would be done before OR and the meaning would change.`,
    skills: ['T6-S10'],
  },
  't6-c25': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Evaluate: Ice is cold AND 4 is even OR 7 is positive AND NOT water is liquid.',
    options: [
      'FALSE, because NOT water is liquid is FALSE',
      'FALSE, because it is worked from left to right',
      'TRUE, because TRUE AND TRUE gives TRUE, then TRUE OR FALSE',
      'TRUE, because OR is always evaluated first',
    ],
    answer: 2,
    hint: 'Do NOT first, then both ANDs, then the OR.',
    explanation: 'TRUE AND TRUE OR TRUE AND NOT TRUE becomes TRUE AND TRUE OR TRUE AND FALSE. The ANDs give TRUE and FALSE, and TRUE OR FALSE = TRUE.',
    skills: ['T6-S6'],
  },
  't6-c26': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: `Exercise 6: "I have IT homework OR Maths homework AND NOT (tomorrow is the weekend)" is F(I,M,W) = I + M.W'. Find the result for each row. Type 1 or 0.`,
    code: `I M W | I + M.W'\n0 0 0 | ?\n0 0 1 | ?\n0 1 0 | ?\n0 1 1 | ?\n1 0 1 | ?\n1 1 1 | ?`,
    rows: [
      { label: 'I=0, M=0, W=0', answer: '0' },
      { label: 'I=0, M=0, W=1', answer: '0' },
      { label: 'I=0, M=1, W=0', answer: '1' },
      { label: 'I=0, M=1, W=1', answer: '0' },
      { label: 'I=1, M=0, W=1', answer: '1' },
      { label: 'I=1, M=1, W=1', answer: '1' },
    ],
    hint: `AND is done before OR, so work out M.W' first, then OR it with I.`,
    explanation: `Whenever I = 1 the result is 1. When I = 0 the result equals M.W', which is 1 only for M = 1 and W = 0.`,
    skills: ['T6-S11', 'T6-S9', 'T6-S6'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Learn how computers make decisions using TRUE and FALSE values, the operators NOT, AND and OR, truth tables and De Morgan\'s Law.',
  outcomes: [
    'By the end you can explain how switches, bits and voltages represent TRUE (1) and FALSE (0).',
    'By the end you can evaluate Boolean logical statements that use relational operators.',
    'By the end you can apply NOT, AND and OR, and describe them with switches and Venn diagrams.',
    'By the end you can evaluate logical expressions using the order brackets, NOT, AND, OR.',
    'By the end you can read and write Boolean functions in functional notation using +, . and \'.',
    'By the end you can build truth tables with two and three variables and use them to prove two expressions are equal.',
    'By the end you can turn English statements into Boolean functions.',
    'By the end you can negate expressions using De Morgan\'s Law.',
  ],
  topics: [
    {
      id: 'T6-T1',
      title: 'Switches, bits and Boolean values',
      sections: ['6.1'],
      skills: ['T6-S1'],
      explanation: [
        'A computer is made up of millions of switches which can be either on (1) or off (0). A single switch is known as a bit, and groups of bits form codes that represent integers, real numbers, characters and colours (Learning Unit 1).',
        'Besides storing data, a computer must decide things, for example: if this switch is on, then do this action; or if this switch is on and that switch is off, then do this action, otherwise do another action. These statements use logic.',
        'A statement such as "if this switch is on" produces a result of either TRUE or FALSE. TRUE is represented in a bit with a 1 and FALSE with a 0.',
        'Electronically, a 1 is 5 volts and a 0 is 0 volts. Because voltages may not be exact, any value from 2 to 5 volts is detected as a 1 and any value from 0 to 0.8 volts as a 0. Values between 0.8 and 2 volts are not used, to avoid confusion.',
        'A value that can only be TRUE or FALSE (0 or 1) is called a Boolean value. A variable that stores a Boolean value is a Boolean variable.',
      ],
      vocabulary: [
        { term: 'Bit', definition: 'A single switch, which is either on (1) or off (0).' },
        { term: 'Boolean value', definition: 'A value that can only be TRUE or FALSE (0 or 1).' },
        { term: 'Boolean variable', definition: 'A variable that stores a Boolean value.' },
      ],
      workedExamples: [
        { code: '2 V to 5 V      -> 1 (TRUE)\n0.8 V to 2 V    -> not used\n0 V to 0.8 V    -> 0 (FALSE)', explanation: 'How a computer reads voltages as bits. The unused gap between 0.8 and 2 volts prevents confusion between 0 and 1.' },
      ],
      misconceptions: [
        'Thinking a 1 must be exactly 5 volts. Voltages are not exact, so anything from 2 to 5 volts is still read as a 1.',
        'Thinking every voltage is read as either 0 or 1. Voltages between 0.8 and 2 volts are deliberately not used.',
      ],
      questions: [
        {
          id: 'T6-T1-Q1',
          type: 'tf',
          category: 'apply',
          prompt: 'A wire carrying 1.5 volts is read by the computer as a 1.',
          answer: false,
          hint: 'Compare 1.5 V with the bands 0 to 0.8, 0.8 to 2 and 2 to 5.',
          explanation: '1.5 volts lies between 0.8 and 2 volts, a band that is not used so that there is no confusion between a 0 and a 1.',
          skills: ['T6-S1'],
        },
        {
          id: 'T6-T1-Q2',
          type: 'mc',
          category: 'define',
          prompt: 'What is a Boolean variable?',
          options: ['A variable that can store any whole number', 'A single switch inside the CPU', 'A value that is either 0 volts or 5 volts', 'A variable that stores a Boolean value'],
          answer: 3,
          hint: 'A Boolean value can only be TRUE or FALSE.',
          explanation: 'A Boolean variable is a variable that stores a Boolean value, meaning a value that can only be TRUE or FALSE (0 or 1).',
          skills: ['T6-S1'],
        },
        {
          id: 'T6-T1-Q3',
          type: 'mc',
          category: 'identify',
          prompt: 'Which voltage range is detected as a 0 (FALSE)?',
          options: ['0 to 0.8 volts', '0.8 to 2 volts', '2 to 5 volts', 'Exactly 5 volts'],
          answer: 0,
          hint: 'A 0 is represented by 0 volts, plus a small margin.',
          explanation: 'Any value between 0 and 0.8 volts is a 0. From 2 to 5 volts is a 1, and 0.8 to 2 volts is not used.',
          skills: ['T6-S1'],
        },
      ],
    },
    {
      id: 'T6-T2',
      title: 'Boolean logical statements and relational operators',
      sections: ['6.2', '6.2.1'],
      skills: ['T6-S2'],
      explanation: [
        'A Boolean logical statement is either true or false. For example, "Johannesburg is in South Africa" is TRUE, "Botswana is north of the Equator" is FALSE, "3 + 3 = 6" is TRUE and "12 < 8" is FALSE.',
        'Relational operators compare two values: > (greater than), < (less than), = (equal to), != or <> (not equal to), >= (greater than or equal to) and <= (less than or equal to).',
        'There is no single keyboard key for the not equal, greater than or equal and less than or equal symbols, so keys are combined: != (or <>), >= and <=. This Learning Unit uses !=.',
        'The result of a statement with a relational operator is TRUE or FALSE, for example 2 >= 1 is TRUE.',
      ],
      vocabulary: [
        { term: 'Boolean logical statement', definition: 'A statement that is either true or false.' },
        { term: 'Relational operator', definition: 'An operator that compares two values: >, <, =, !=, >=, <=.' },
        { term: '!=', definition: 'Not equal to (also written <>).' },
      ],
      workedExamples: [
        { code: '3 + 3 = 6    TRUE\n12 < 8       FALSE\n2 >= 1       TRUE\n5 >= 5       TRUE\n5 > 5        FALSE', explanation: 'Each comparison gives a single TRUE or FALSE result. >= includes the equal case, > does not.' },
      ],
      misconceptions: [
        'Thinking 5 >= 5 is FALSE. >= means greater than OR equal to, so equal values give TRUE.',
        'Thinking a longer decimal is a bigger number. 0.000001 is smaller than 0.0001, so 0.000001 > 0.0001 is FALSE.',
      ],
      questions: [
        {
          id: 'T6-T2-Q1',
          type: 'trace',
          category: 'predict',
          prompt: 'Give the result of each statement. Type TRUE or FALSE in capitals.',
          code: '5 >= 4\n10 = 10.01\n12 < 8\n2 >= 1',
          rows: [
            { label: '5 >= 4', answer: 'TRUE' },
            { label: '10 = 10.01', answer: 'FALSE' },
            { label: '12 < 8', answer: 'FALSE' },
            { label: '2 >= 1', answer: 'TRUE' },
          ],
          hint: 'Read each operator aloud: greater than or equal to, equal to, less than.',
          explanation: '5 is greater than 4 and 2 is greater than 1, so both >= statements are TRUE. 10 is not equal to 10.01, and 12 is not less than 8.',
          skills: ['T6-S2'],
        },
        {
          id: 'T6-T2-Q2',
          type: 'mc',
          category: 'classify',
          prompt: 'Which of these is a Boolean logical statement?',
          options: ['What is the capital of Botswana?', 'Botswana is north of the Equator.', 'Please close the door.', '3 + 3'],
          answer: 1,
          hint: 'A Boolean logical statement must be either true or false.',
          explanation: '"Botswana is north of the Equator" can be judged as true or false (it is FALSE). A question, an instruction or a calculation on its own has no true or false value.',
          skills: ['T6-S2'],
        },
      ],
    },
    {
      id: 'T6-T3',
      title: 'Logical operators and NOT',
      sections: ['6.2.2', '6.2.2.1'],
      skills: ['T6-S3'],
      explanation: [
        'Logical statements, also called logical expressions, can be combined using logical operators, which define how the statements should be processed. Boolean logic uses NOT, AND and OR.',
        'A single switch represented by the Boolean variable A can have two values: 0 or 1. It can also be drawn as a Venn diagram with one circle.',
        'The NOT operator swaps the value of A: 0 becomes 1 and 1 becomes 0. In a Venn diagram, NOT A is everything outside A.',
        'Exercise 1: NOT 5 > 3 is FALSE, NOT 3 = 2 is TRUE, "Johannesburg is NOT in Egypt" is TRUE and NOT 4 != 2 is FALSE.',
      ],
      vocabulary: [
        { term: 'Logical expression', definition: 'Another name for a logical statement; expressions can be combined with logical operators.' },
        { term: 'Logical operator', definition: 'An operator (NOT, AND, OR) that combines statements and defines how they are processed.' },
        { term: 'NOT', definition: 'Swaps the value of a variable: 0 becomes 1 and 1 becomes 0.' },
      ],
      workedExamples: [
        { code: 'A | NOT A\n0 |   1\n1 |   0', explanation: 'The NOT truth table: the output is always the opposite of the input.' },
        { code: 'NOT 5 > 3\n= NOT TRUE\n= FALSE', explanation: 'Work out the relational statement first, then apply NOT.' },
      ],
      misconceptions: [
        'Thinking NOT rewrites the operator inside the statement, for example turning 5 > 3 into 5 < 3. NOT takes the result of 5 > 3 (TRUE) and swaps it to FALSE.',
        'Thinking NOT A on a Venn diagram is the circle A. It is everything outside the circle.',
      ],
      questions: [
        {
          id: 'T6-T3-Q1',
          type: 'trace',
          category: 'predict',
          prompt: 'Exercise 1: give the result of each statement. Type TRUE or FALSE in capitals.',
          code: 'NOT 5 > 3\nNOT 3 = 2\nJohannesburg is NOT in Egypt',
          rows: [
            { label: 'NOT 5 > 3', answer: 'FALSE' },
            { label: 'NOT 3 = 2', answer: 'TRUE' },
            { label: 'Johannesburg is NOT in Egypt', answer: 'TRUE' },
          ],
          hint: 'Decide the plain statement first, then swap it.',
          explanation: '5 > 3 is TRUE so NOT gives FALSE. 3 = 2 is FALSE so NOT gives TRUE. Johannesburg is in Egypt is FALSE, so it is TRUE that Johannesburg is NOT in Egypt.',
          skills: ['T6-S3'],
        },
        {
          id: 'T6-T3-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'Applying NOT twice gives back the original value, so NOT(NOT 0) = 0.',
          answer: true,
          hint: 'Swap 0 once, then swap the result again.',
          explanation: 'NOT 0 = 1, and NOT 1 = 0. Two swaps return to the starting value.',
          skills: ['T6-S3'],
        },
      ],
    },
    {
      id: 'T6-T4',
      title: 'AND and OR',
      sections: ['6.2.2.2', '6.2.2.3'],
      skills: ['T6-S4', 'T6-S5'],
      explanation: [
        'With AND, BOTH statements must be TRUE for the combined statement to be TRUE. It is modelled by two switches A and B in series: the lamp goes on (1 or TRUE) only when both switches are closed. If either is open (0 or FALSE) the result is 0.',
        'Two switches have 2^2 = 4 possible combinations: 00, 01, 10 and 11. On a Venn diagram, AND is the intersection of A and B.',
        'With OR, the result is TRUE when EITHER switch A or B is TRUE. It is modelled by two switches in parallel: when A, B or both are closed, the lamp goes on. On a Venn diagram, OR is the union of A and B.',
        'Exercise 2 answers: FALSE, FALSE, FALSE, TRUE, TRUE, TRUE. Exercise 3 answers: TRUE, TRUE, FALSE, TRUE, TRUE, TRUE.',
      ],
      vocabulary: [
        { term: 'AND', definition: 'Produces TRUE only when BOTH statements are TRUE.' },
        { term: 'OR', definition: 'Produces TRUE when EITHER statement (or both) is TRUE.' },
        { term: 'Series', definition: 'Switches connected one after the other; models AND.' },
        { term: 'Parallel', definition: 'Switches connected side by side; models OR.' },
      ],
      workedExamples: [
        { code: 'A B | A AND B | Lamp\n0 0 |    0    | OFF\n0 1 |    0    | OFF\n1 0 |    0    | OFF\n1 1 |    1    | ON', explanation: 'AND with switches in series: the lamp is ON only when both A and B are closed.' },
        { code: 'A B | A OR B | Lamp\n0 0 |   0    | OFF\n0 1 |   1    | ON\n1 0 |   1    | ON\n1 1 |   1    | ON', explanation: 'OR with switches in parallel: the lamp is OFF only when both A and B are open.' },
      ],
      misconceptions: [
        'Thinking OR means "one or the other but not both". In Boolean logic, A OR B is also TRUE when both are TRUE.',
        'Thinking AND is TRUE if most of the statements are TRUE. A single FALSE statement makes the whole AND FALSE.',
      ],
      questions: [
        {
          id: 'T6-T4-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'In the truth table for A AND B, in which row is the result 1?',
          options: ['A = 0, B = 0', 'A = 0, B = 1', 'A = 1, B = 0', 'A = 1, B = 1'],
          answer: 3,
          hint: 'Think of two switches in series and when the lamp goes on.',
          explanation: 'AND needs BOTH inputs to be 1, so only the row A = 1, B = 1 gives 1.',
          skills: ['T6-S4'],
        },
        {
          id: 'T6-T4-Q2',
          type: 'tf',
          category: 'distinguish',
          prompt: 'A OR B is FALSE when both A and B are TRUE.',
          answer: false,
          hint: 'Look at the last row of the OR truth table: both switches closed.',
          explanation: 'When both parallel switches are closed the lamp is ON, so A OR B is TRUE (1) when both are TRUE. OR is FALSE only when both are FALSE.',
          skills: ['T6-S5'],
        },
        {
          id: 'T6-T4-Q3',
          type: 'mc',
          category: 'predict',
          prompt: 'Which statement is TRUE?',
          options: ['5 >= 1 AND 5 <= 10', '5 > 3 AND 4 = 2', 'Johannesburg is in Egypt OR 3 <= -9', `3 = 2 AND 'L' is a capital letter`],
          answer: 0,
          hint: 'For AND both sides must be TRUE; for OR at least one side must be TRUE.',
          explanation: '5 is at least 1 and at most 10, so both sides are TRUE and the AND is TRUE. Each of the others has a FALSE side under AND, or two FALSE sides under OR.',
          skills: ['T6-S4', 'T6-S5'],
        },
      ],
    },
    {
      id: 'T6-T5',
      title: 'Order of operations',
      sections: ['6.2.2.4'],
      skills: ['T6-S6'],
      explanation: [
        'When a logical expression has more than one logical operator, they are executed in the order: 1 brackets, 2 NOT, 3 AND, 4 OR.',
        'A logical expression is evaluated just as you would an arithmetic expression: first determine the truth of each statement, then combine the results using the operators in the correct order.',
        'Example 1: 5 > 3 OR 5 < 10 AND Cape Town is in Canada = TRUE OR TRUE AND FALSE = TRUE OR FALSE (AND first) = TRUE.',
        'Example 3: NOT (fish swim in water) AND NOT (pink is the same colour as blue OR humans have 2 legs) = NOT TRUE AND NOT (FALSE OR TRUE) = NOT TRUE AND NOT TRUE (brackets first) = FALSE AND FALSE (then NOT) = FALSE.',
        'Exercise 4 answers: all five expressions evaluate to TRUE, for example NOT(9 = 9 AND 5 > 25) = NOT(TRUE AND FALSE) = NOT FALSE = TRUE.',
      ],
      vocabulary: [
        { term: 'Order of operations', definition: 'The order logical operators are executed: brackets, NOT, AND, OR.' },
      ],
      workedExamples: [
        { code: 'A tomato is not edible AND a tomato is a fruit OR a potato is a vegetable\n= FALSE AND TRUE OR TRUE\n= FALSE OR TRUE\n= TRUE', explanation: 'Example 2: AND is executed first. The printed textbook ends this example with FALSE, but FALSE OR TRUE is TRUE.' },
        { code: '7 is an integer AND (a rectangle has 3 sides OR a cat is a mammal)\n= TRUE AND (FALSE OR TRUE)\n= TRUE AND TRUE\n= TRUE', explanation: 'Exercise 4 question 1: the brackets are worked out before the AND.' },
      ],
      misconceptions: [
        'Thinking the expression is simply worked from left to right. AND is always executed before OR unless brackets say otherwise.',
        'Thinking NOT is applied before the brackets are worked out. Brackets come first, then NOT is applied to the bracket result.',
      ],
      questions: [
        {
          id: 'T6-T5-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Exercise 4: evaluate "Humans can walk AND dogs can fly OR NOT (insects can fly AND insects can do Math)" step by step. Type TRUE or FALSE in capitals.',
          code: 'Humans can walk AND dogs can fly OR NOT (insects can fly AND insects can do Math)',
          rows: [
            { label: 'Step 1: value inside the brackets', answer: 'FALSE' },
            { label: 'Step 2: after applying NOT to the brackets', answer: 'TRUE' },
            { label: 'Step 3: humans can walk AND dogs can fly', answer: 'FALSE' },
            { label: 'Step 4: final result after OR', answer: 'TRUE' },
          ],
          hint: 'Brackets first, then NOT, then AND, then OR.',
          explanation: 'Insects can fly (TRUE) AND insects can do Math (FALSE) is FALSE; NOT FALSE is TRUE. TRUE AND FALSE is FALSE, and FALSE OR TRUE is TRUE.',
          skills: ['T6-S6'],
        },
        {
          id: 'T6-T5-Q2',
          type: 'mc',
          category: 'sequence',
          prompt: 'In TRUE OR TRUE AND FALSE (from Example 1), which part is executed first?',
          options: ['TRUE OR TRUE', 'Nothing: the answer is always the first value', 'TRUE AND FALSE', 'The whole line at once'],
          answer: 2,
          hint: 'There are no brackets or NOTs here, so look for the next operator in the order.',
          explanation: 'AND is executed before OR, so TRUE AND FALSE = FALSE comes first, then TRUE OR FALSE = TRUE.',
          skills: ['T6-S6'],
        },
        {
          id: 'T6-T5-Q3',
          type: 'tf',
          category: 'predict',
          prompt: 'NOT(9 = 9 AND 5 > 25) evaluates to FALSE.',
          answer: false,
          hint: 'Work out the bracket first: 9 = 9 is TRUE, but is 5 > 25?',
          explanation: '9 = 9 AND 5 > 25 is TRUE AND FALSE, which is FALSE. NOT FALSE is TRUE.',
          skills: ['T6-S6'],
        },
      ],
    },
    {
      id: 'T6-T6',
      title: 'Truth tables and functional notation',
      sections: ['6.2.3', '6.2.3.1'],
      skills: ['T6-S7', 'T6-S8', 'T6-S11'],
      explanation: [
        'Sometimes we do not know whether a statement is TRUE or FALSE. A truth table examines ALL possible values for a logical expression, assigning TRUE or FALSE to each statement and then working out the combined result for each combination.',
        'Example: "Fazul is in Grade 10 AND NOT (tennis is on Wednesday)". Let A = "Fazul is in Grade 10" and B = "tennis is on Wednesday". The statement becomes A AND NOT B.',
        'With two variables there are 2^2 = 4 combinations, the decimal values 0 to 3. The right column switches between 0 and 1 every line (2^0) and the left column switches in groups of 2 (2^1). 0 is the same as FALSE and 1 is the same as TRUE.',
        'A AND NOT B is only TRUE when A = 1 and B = 0: when Fazul is in Grade 10 and tennis is not on Wednesday.',
        `In functional notation OR is written as +, AND as a dot (.), and NOT with a ' (so NOT B is B'). A AND NOT B becomes F(A,B) = A.B'. The dot can be left out, just as in mathematics.`,
        `Each TRUE row of a truth table can be written as a term: a variable that is 0 gets a '. Example 4: (X.Y)' is TRUE for rows 00, 01 and 10, so F(X,Y) = X'Y' + X'Y + XY', read as NOT X AND NOT Y OR NOT X AND Y OR X AND NOT Y. A function can have more than one TRUE row.`,
      ],
      vocabulary: [
        { term: 'Truth table', definition: 'A table that examines ALL possible values for a logical expression based on the combination of statements.' },
        { term: '+', definition: 'Functional notation for OR.' },
        { term: '. (dot)', definition: 'Functional notation for AND; it may be left out.' },
        { term: `' (prime)`, definition: `Functional notation for NOT, e.g. B' means NOT B.` },
      ],
      workedExamples: [
        { code: `A B | WORKINGS              | A AND NOT B | RESULT\n0 0 | 0 AND NOT 0 = 0 AND 1 |      0      | FALSE\n0 1 | 0 AND NOT 1 = 0 AND 0 |      0      | FALSE\n1 0 | 1 AND NOT 0 = 1 AND 1 |      1      | TRUE\n1 1 | 1 AND NOT 1 = 1 AND 0 |      0      | FALSE`, explanation: `The Fazul truth table. The only TRUE row is A=1, B=0, written A.B', which is exactly F(A,B) = A.B'.` },
        { code: `X Y | NOT (X AND Y) | (X.Y)'\n0 0 | NOT (0)       | 1\n0 1 | NOT (0)       | 1\n1 0 | NOT (0)       | 1\n1 1 | NOT (1)       | 0\nF(X,Y) = X'Y' + X'Y + XY'`, explanation: 'Example 4: three TRUE rows give three terms joined by OR.' },
      ],
      misconceptions: [
        `Thinking a truth table only needs the rows you expect to be TRUE. It must list ALL combinations, 2^n rows for n variables.`,
        `Thinking XY' means NOT (X AND Y). The ' applies only to Y, so XY' is X AND NOT Y; NOT (X AND Y) needs brackets: (XY)'.`,
      ],
      questions: [
        {
          id: 'T6-T6-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Exercise 5: evaluate each function for the given values. Type 1 or 0.',
          code: `F(X,Y) = XY' + X        find F(0,1)\nF(X,Y,Z) = Z + X'YZ     find F(1,0,1)\nF(A,B) = A.B'           find F(1,0)`,
          rows: [
            { label: 'F(0,1) for XY\' + X', answer: '0' },
            { label: 'F(1,0,1) for Z + X\'YZ', answer: '1' },
            { label: 'F(1,0) for A.B\'', answer: '1' },
          ],
          hint: 'Substitute the values in order: F(X,Y) = F(0,1) means X = 0 and Y = 1.',
          explanation: `F(0,1) = 0.1' + 0 = 0.0 + 0 = 0. F(1,0,1): Z = 1, so the OR is 1. F(1,0) = 1.0' = 1.1 = 1.`,
          skills: ['T6-S7'],
        },
        {
          id: 'T6-T6-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'Why does a truth table with two variables have exactly 4 rows?',
          options: ['Because each operator adds two rows', 'Because there are 4 logical operators', 'Because AND and OR each need 2 rows', 'Because 2 binary digits have 2^2 = 4 combinations'],
          answer: 3,
          hint: 'Each variable is one binary digit that can be 0 or 1.',
          explanation: 'Two binary digits give 2^2 = 4 combinations: 00, 01, 10 and 11, the decimal values 0 to 3.',
          skills: ['T6-S8'],
        },
        {
          id: 'T6-T6-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'Let A = "Fazul is in Grade 10" and B = "tennis is on Wednesday". How is "Fazul is in Grade 10 AND NOT (tennis is on Wednesday)" written in functional notation?',
          options: [`F(A,B) = A.B'`, `F(A,B) = (A.B)'`, `F(A,B) = A + B'`, `F(A,B) = A'.B`],
          answer: 0,
          hint: `AND is a dot and NOT is a ' after the variable it applies to.`,
          explanation: `A AND NOT B is written F(A,B) = A.B'. The ' applies only to B, and the dot means AND.`,
          skills: ['T6-S7', 'T6-S11'],
        },
      ],
    },
    {
      id: 'T6-T7',
      title: 'Proving with two-variable truth tables',
      sections: ['6.2.3.1'],
      skills: ['T6-S8', 'T6-S11'],
      explanation: [
        'A truth table can prove that two expressions are equal: work out the left-hand side (LHS) and right-hand side (RHS) for every row. If the result columns match in every row, LHS = RHS.',
        `Example 5: prove X + X'Y = X + Y. Both columns give 0, 1, 1, 1 for the rows 00, 01, 10, 11, so X + X'Y = X + Y.`,
        `Exercise 5 also asks you to prove A' + AB = A' + B. Both sides give 1, 1, 0, 1.`,
        `English statements can be turned into truth tables. "I have IT homework OR Maths homework" with I and M is I + M (0, 1, 1, 1). "NOT (I have IT homework) AND Maths homework" is I'.M, which is TRUE only for I = 0, M = 1.`,
        `Other Exercise 5 tables: F(A,B) = A' + AB gives 1, 1, 0, 1 and F(X,Y) = X(X + Y') gives 0, 0, 1, 1.`,
      ],
      vocabulary: [
        { term: 'LHS', definition: 'Left-hand side of the expression being proved.' },
        { term: 'RHS', definition: 'Right-hand side of the expression being proved.' },
      ],
      workedExamples: [
        { code: `X Y | LHS = X + X'Y           | RHS = X + Y\n0 0 | 0 + 0'0 = 0 + 1.0 = 0   | 0 + 0 = 0\n0 1 | 0 + 0'1 = 0 + 1.1 = 1   | 0 + 1 = 1\n1 0 | 1 + 1'0 = 1 + 0.0 = 1   | 1 + 0 = 1\n1 1 | 1 + 1'1 = 1 + 0.1 = 1   | 1 + 1 = 1`, explanation: `Example 5: the LHS and RHS columns are identical, hence X + X'Y = X + Y.` },
      ],
      misconceptions: [
        'Thinking two expressions are equal because they match in one or two rows. They must match in EVERY row of the truth table.',
        `Thinking 1 + 1 = 2 in Boolean logic. + means OR, so 1 + 1 = 1.`,
      ],
      questions: [
        {
          id: 'T6-T7-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: `Exercise 5: to prove A' + AB = A' + B, complete the RHS column A' + B. Type 1 or 0.`,
          code: `A B | A' + B\n0 0 | ?\n0 1 | ?\n1 0 | ?\n1 1 | ?`,
          rows: [
            { label: 'A=0, B=0', answer: '1' },
            { label: 'A=0, B=1', answer: '1' },
            { label: 'A=1, B=0', answer: '0' },
            { label: 'A=1, B=1', answer: '1' },
          ],
          hint: `A' is 1 whenever A is 0.`,
          explanation: `The RHS gives 1, 1, 0, 1, which matches A' + AB in every row, so A' + AB = A' + B.`,
          skills: ['T6-S8'],
        },
        {
          id: 'T6-T7-Q2',
          type: 'tf',
          category: 'explain',
          prompt: `Example 5 shows that X + X'Y and X + Y produce exactly the same result column in a truth table.`,
          answer: true,
          hint: 'Compare the two columns row by row.',
          explanation: `Both expressions give 0, 1, 1, 1 for the rows 00, 01, 10, 11, which proves X + X'Y = X + Y.`,
          skills: ['T6-S8'],
        },
        {
          id: 'T6-T7-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'Let I = "I have IT homework" and M = "I have Maths homework". When is "NOT (I have IT homework) AND Maths homework" TRUE?',
          options: ['I = 1 and M = 1', 'I = 0 and M = 1', 'I = 1 and M = 0', 'I = 0 and M = 0'],
          answer: 1,
          hint: `The function is I'.M. Both parts of the AND must be 1.`,
          explanation: `I'.M needs I' = 1 (so I = 0) and M = 1: you have Maths homework but no IT homework.`,
          skills: ['T6-S11', 'T6-S8'],
        },
      ],
    },
    {
      id: 'T6-T8',
      title: 'Three-variable truth tables',
      sections: ['6.2.3.2'],
      skills: ['T6-S9', 'T6-S11'],
      explanation: [
        'A truth table can have three Boolean variables. The number of combinations is then 2^3 = 8, the binary values 000 to 111.',
        'Example 6: "I have a yellow book OR the sun is shining AND it is winter". Let A = "I have a yellow book", B = "the sun is shining" and C = "it is winter". The function is F(A,B,C) = A + B.C.',
        `Working each row (AND before OR) gives 0, 0, 0, 1, 1, 1, 1, 1. The TRUE rows give F(A,B,C) = A'BC + AB'C' + AB'C + ABC' + ABC.`,
        `Exercise 6 results: X'Y + Y'Z' gives 1, 0, 1, 1, 1, 0, 0, 0; (X + Y')(Y + Z) gives 0, 1, 0, 0, 0, 1, 1, 1; X(Y + Z) gives 0, 0, 0, 0, 0, 1, 1, 1.`,
        `A truth table shows AB + A'C + BC = AB + A'C: both give 0, 1, 0, 1, 0, 0, 1, 1. "The food is delicious AND the cool drink tastes sweet OR it is not a school night" is DS + N'.`,
      ],
      vocabulary: [
        { term: 'Three-variable truth table', definition: 'A truth table with 2^3 = 8 rows covering every combination of three Boolean variables.' },
      ],
      workedExamples: [
        { code: 'A B C | A + B.C\n0 0 0 | 0 + 0.0 = 0\n0 0 1 | 0 + 0.1 = 0\n0 1 0 | 0 + 1.0 = 0\n0 1 1 | 0 + 1.1 = 1\n1 0 0 | 1 + 0.0 = 1\n1 0 1 | 1 + 0.1 = 1\n1 1 0 | 1 + 1.0 = 1\n1 1 1 | 1 + 1.1 = 1', explanation: 'Example 6: B.C is worked out first, then ORed with A. The result is 1 whenever A is 1, or when B and C are both 1.' },
      ],
      misconceptions: [
        'Thinking three variables need 6 rows (2 x 3). The number of rows is 2^3 = 8.',
        'Thinking A + B.C means (A + B).C. AND is done before OR, so it means A + (B.C).',
      ],
      questions: [
        {
          id: 'T6-T8-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: `Exercise 6: find F(X,Y,Z) = X'Y + Y'Z' for each row. Type 1 or 0.`,
          code: `X Y Z | X'Y + Y'Z'\n0 0 0 | ?\n0 0 1 | ?\n0 1 0 | ?\n1 0 0 | ?\n1 0 1 | ?\n1 1 0 | ?`,
          rows: [
            { label: 'X=0, Y=0, Z=0', answer: '1' },
            { label: 'X=0, Y=0, Z=1', answer: '0' },
            { label: 'X=0, Y=1, Z=0', answer: '1' },
            { label: 'X=1, Y=0, Z=0', answer: '1' },
            { label: 'X=1, Y=0, Z=1', answer: '0' },
            { label: 'X=1, Y=1, Z=0', answer: '0' },
          ],
          hint: `X'Y is 1 only when X = 0 and Y = 1. Y'Z' is 1 only when Y = 0 and Z = 0.`,
          explanation: `Rows 000 and 100 are TRUE through Y'Z', row 010 is TRUE through X'Y. Rows 001, 101 and 110 make both terms 0.`,
          skills: ['T6-S9'],
        },
        {
          id: 'T6-T8-Q2',
          type: 'tf',
          category: 'calculate',
          prompt: `A truth table shows that AB + A'C + BC = AB + A'C.`,
          answer: true,
          hint: 'Check the rows where BC = 1 (011 and 111). Is one of the other terms already 1 there?',
          explanation: `Both sides give 0, 1, 0, 1, 0, 0, 1, 1. Wherever BC = 1, either A'C (row 011) or AB (row 111) is already 1, so the BC term adds nothing.`,
          skills: ['T6-S9'],
        },
        {
          id: 'T6-T8-Q3',
          type: 'order',
          category: 'sequence',
          prompt: 'Put these A B C rows in the order they appear in a three-variable truth table.',
          items: ['1 0 0', '0 0 1', '1 1 1', '0 1 0', '0 1 1'],
          answer: [1, 3, 4, 0, 2],
          hint: 'The rows count upwards in binary, from 000 to 111.',
          explanation: 'The rows follow the binary values 001 (1), 010 (2), 011 (3), 100 (4) and 111 (7). C switches every line, B in groups of 2 and A in groups of 4.',
          skills: ['T6-S9'],
        },
      ],
    },
    {
      id: 'T6-T9',
      title: 'De Morgan\'s Law',
      sections: ['6.2.4'],
      skills: ['T6-S10', 'T6-S11'],
      explanation: [
        'Boolean expressions can be simplified using the laws of Boolean Algebra. Boolean Algebra is beyond this course, but De Morgan\'s Law is useful when an entire expression must be negated, for example later when writing programs, SQL statements or search engine queries.',
        `De Morgan's Law states (A + B)' = A'.B' and similarly (A.B)' = A' + B'.`,
        `"I do NOT want to find any cats OR dogs" is F(C,D) = NOT(C OR D) = (C + D)'. By De Morgan this is C'.D', and a truth table proves it: both columns give 1, 0, 0, 0.`,
        'NOT (A AND B) is not the same as NOT A AND NOT B: the operator must change too. When you negate an expression, negate each variable and change each AND to OR and each OR to AND.',
        `Example 7: (X + Y'Z)' = X'.(Y + Z'). Keep the brackets around the second term. Example 8: (AB + CD)' = (AB)'.(CD)' = (A' + B')(C' + D'), treating AB and CD as single terms first.`,
        `Exercise 7: no tea or coffee is (T + C)' = T'.C'. Backup is C + W + M, so no backup is C'.W'.M'. Full colours is P(W + C), so no colours is P' + W'C'.`,
      ],
      vocabulary: [
        { term: 'De Morgan\'s Law', definition: `(A + B)' = A'.B' and (A.B)' = A' + B'.` },
        { term: 'Negate', definition: 'Find the opposite (NOT) of a statement or expression.' },
      ],
      workedExamples: [
        { code: `C D | (C + D)'      | C'.D'\n0 0 | (0 + 0)' = 1  | 1.1 = 1\n0 1 | (0 + 1)' = 0  | 1.0 = 0\n1 0 | (1 + 0)' = 0  | 0.1 = 0\n1 1 | (1 + 1)' = 0  | 0.0 = 0`, explanation: `Proof that (C + D)' = C'.D': the two result columns match in every row.` },
        { code: `F'(X,Y,Z) = (X + Y'Z)'\n          = X'.(Y + Z')`, explanation: 'Example 7: X becomes X\', the OR becomes AND, and Y\'Z becomes (Y + Z\'). Both sides give 1, 0, 1, 1, 0, 0, 0, 0.' },
        { code: `F'(A,B,C,D) = (AB + CD)'\n            = (AB)'.(CD)'\n            = (A' + B')(C' + D')`, explanation: 'Example 8: treat AB and CD as single terms, then apply De Morgan to each term while keeping the brackets.' },
      ],
      misconceptions: [
        `Thinking (A.B)' = A'.B'. Negating the variables is not enough; the AND must also change to OR: (A.B)' = A' + B'.`,
        `Thinking the brackets can be dropped after negating. (X + Y'Z)' is X'.(Y + Z'), not X'.Y + Z'.`,
      ],
      questions: [
        {
          id: 'T6-T9-Q1',
          type: 'mc',
          category: 'apply',
          prompt: `"I do not want any tea or coffee" is (T + C)'. After applying De Morgan's Law, which English sentence matches the result?`,
          options: ['I want tea or I want coffee.', 'I do not want tea or I do not want coffee.', 'I do not want tea and I do not want coffee.', 'I want tea and I want coffee.'],
          answer: 2,
          hint: `De Morgan turns (T + C)' into T'.C'.`,
          explanation: `(T + C)' = T'.C', which reads NOT tea AND NOT coffee: I do not want tea and I do not want coffee.`,
          skills: ['T6-S10', 'T6-S11'],
        },
        {
          id: 'T6-T9-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: `Complete the C'.D' column to prove (C + D)' = C'.D'. Type 1 or 0.`,
          code: `C D | C'.D'\n0 0 | ?\n0 1 | ?\n1 0 | ?\n1 1 | ?`,
          rows: [
            { label: 'C=0, D=0', answer: '1' },
            { label: 'C=0, D=1', answer: '0' },
            { label: 'C=1, D=0', answer: '0' },
            { label: 'C=1, D=1', answer: '0' },
          ],
          hint: `Negate each value first, then AND them: both negated values must be 1.`,
          explanation: `Only C = 0, D = 0 gives 1.1 = 1. The column 1, 0, 0, 0 matches (C + D)', proving the law.`,
          skills: ['T6-S10'],
        },
        {
          id: 'T6-T9-Q3',
          type: 'tf',
          category: 'distinguish',
          prompt: 'NOT (A AND B) means the same as NOT A AND NOT B.',
          answer: false,
          hint: 'When you negate, what must happen to the operator?',
          explanation: `By De Morgan's Law (A.B)' = A' + B', so NOT (A AND B) is NOT A OR NOT B. The AND must change to OR.`,
          skills: ['T6-S10'],
        },
        {
          id: 'T6-T9-Q4',
          type: 'mc',
          category: 'apply',
          prompt: `Full colours is given when F(P,W,C) = P(W + C) is TRUE. Which expression gives when the learner will NOT get colours?`,
          options: [`P'(W' + C')`, `P' + W' + C'`, `P'.W'.C'`, `P' + W'C'`],
          answer: 3,
          hint: 'Treat P and (W + C) as two terms joined by AND, then negate each term.',
          explanation: `(P(W + C))' = P' + (W + C)' = P' + W'C'. The AND became OR, and the bracket (W + C) was negated with De Morgan to W'C'.`,
          skills: ['T6-S10', 'T6-S11'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't6-vault-logic',
    unitId: UNIT.id,
    title: 'Reserve Bank Vault Lockdown',
    icon: 'vault',
    summary: 'Crack the logic lock before the vault seals for good.',
    briefing: 'The vault in the Reserve Bank in Pretoria is controlled by a logic lock built from switches joined with NOT, AND and OR. A glitch is sealing it, and only someone who can evaluate every expression in the right order can override it. Get one wrong and the vault locks for a week.',
    tickerMessages: [
      'Reserve Bank reports a fault in the main vault logic lock.',
      'Engineers confirm the lock uses series and parallel switch circuits.',
      'Override panel is showing logical expressions with brackets and NOT.',
      'Warning: two wrong answers will trigger a full seven-day lockdown.',
      'Final override sequence is now live. Every expression counts.',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T6-S2', 'T6-S3', 'T6-S4', 'T6-S5', 'T6-S6'],
    victoryMessage: 'Override accepted. The vault doors swing open and the bank is back in business, thanks to your flawless logic.',
    failMessage: 'The lock reads your answer as FALSE and the vault seals for the week. Review the operators and the order of operations, then try again.',
  },
  {
    id: 't6-backup-blackout',
    unitId: UNIT.id,
    title: 'Server Backup Blackout',
    icon: 'shield',
    summary: 'Fix the backup rule before the school loses its marks.',
    briefing: 'The school server decides when to back up using a Boolean function, and someone has corrupted it the night before report cards. You must rebuild the rule from truth tables and use De Morgan\'s Law to work out exactly when the backup will NOT run. If you get it wrong, a term of marks disappears.',
    tickerMessages: [
      'School server skips its nightly backup for the third time.',
      'IT technician suspects the Boolean backup rule was overwritten.',
      'Report cards are due tomorrow and the marks file is unprotected.',
      'Power dip detected: a crash could wipe the latest changes.',
      'Last chance to restore the rule before the server goes offline.',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T6-S7', 'T6-S8', 'T6-S9', 'T6-S10', 'T6-S11'],
    victoryMessage: 'Backup rule restored and verified with a truth table. The marks are safe and report cards go out on time.',
    failMessage: 'The rule still has a gap and the backup never runs. Rebuild your truth tables, check De Morgan\'s Law and try again.',
  },
];
