// Theory Learning Unit 7: Internet and WWW (Exploring IT: Theory Grade 10, 2nd ed)
import { Globe } from 'lucide-react';

export const UNIT = { id: 'T7', number: 7, name: 'Internet and WWW', worldId: 'internet-www' };

export const SKILLS = {
  'T7-S1': { unit: 'T7', name: 'What the Internet is', description: 'Define the Internet and describe how hosts, routers and communication links work together.', sections: ['7.1'] },
  'T7-S2': { unit: 'T7', name: 'Basic Internet services', description: 'Explain cloud storage (benefits and concerns), email and its protocols, and web sites.', sections: ['7.2', '7.2.1', '7.2.2', '7.2.3'] },
  'T7-S3': { unit: 'T7', name: 'IP addresses and DNS', description: 'Explain TCP/IP, DNS, hostnames and IPv4 addresses, and convert IPv4 addresses between binary and dotted decimal.', sections: ['7.3'] },
  'T7-S4': { unit: 'T7', name: 'Connecting to the Internet', description: 'Identify the hardware and software needed to connect and compare ADSL, fibre, wireless and cellular connections.', sections: ['7.4', '7.4.1', '7.4.2', '7.4.2.1', '7.4.2.2', '7.4.2.3', '7.4.2.4'] },
  'T7-S5': { unit: 'T7', name: 'The WWW and URLs', description: 'Distinguish the WWW from the Internet, a web page from a web site, and name the parts of a URL.', sections: ['7.5', '7.5.1', '7.5.2', '7.5.3'] },
  'T7-S6': { unit: 'T7', name: 'Browsers and successful searching', description: 'Describe web browsers and search engines and use search techniques that balance general and specific searches.', sections: ['7.6', '7.6.1', '7.6.2', '7.6.3'] },
  'T7-S7': { unit: 'T7', name: 'Searching with AND, OR, NOT', description: 'Predict how the logical operators AND, OR and NOT change the number of search results.', sections: ['7.6.4', '7.6.4.1', '7.6.4.2', '7.6.4.3'] },
  'T7-S8': { unit: 'T7', name: 'Order of operations and search expressions', description: 'Apply the order of operations and write searches as search expressions and Boolean functions.', sections: ['7.6.5', '7.6.5.1'] },
  'T7-S9': { unit: 'T7', name: 'Truth tables for searches', description: 'Evaluate a search expression with a truth table and read off when the function is true.', sections: ['7.6.5.2'] },
  'T7-S10': { unit: 'T7', name: 'User interface design principles', description: 'Apply readability, navigation, typography and colour, layout, theme and consistency to interface design.', sections: ['7.8', '7.8.1', '7.8.2', '7.8.3', '7.8.4', '7.8.5', '7.8.6'] },
  'T7-S11': { unit: 'T7', name: 'Desktop vs mobile design', description: 'Compare designing for desktops, phones, tablets and hybrids, including thumb-friendly layouts.', sections: ['7.8.6', '7.8.7'] },
};

export const SKILL_HINTS = {
  'T7-S1': 'Internet = worldwide collection of computer networks for sharing resources or communicating; hosts send/receive, links are bounded (wired) or unbounded (wireless), routers pick the path and connect a network to an ISP',
  'T7-S2': 'Cloud storage benefits (no equipment, access anywhere, automatic remote backup, pay for what you use) vs concerns (unreliable connection, security, company could close); SMTP sends email, POP/IMAP retrieve; web sites are linked pages accessed by domain name',
  'T7-S3': 'TCP gets the transmission to the destination host, IP identifies computers; DNS gives unique names and numbers; IPv4 = 32 bits as four bytes 0-255 with dots, e.g. 131.107.2.200; 2^32 is about 4.29 billion addresses so IPv6 was introduced; tracert and ipconfig',
  'T7-S4': 'Computer needs network card or wireless, browser, router; mobile needs SIM card, Wi-Fi or hotspot (tethering), browser app; ADSL = copper telephone lines plus ADSL router, fibre = light, wireless = radio frequency always on, cellular = SIM card 3G/4G',
  'T7-S5': 'WWW = mass of linked web pages accessed via the Internet, not the Internet itself; web page = any document on the Web, web site = many pages with a home page; URL = unique address: protocol http:// or https://, www, domain name, path',
  'T7-S6': 'Browser locates and views pages by processing HTML (Chrome, Edge, Firefox); search engine searches documents for keywords and returns hyperlinks; state exactly what you want, identify keywords, use synonyms; "exact phrase", inurl:, site:, define:',
  'T7-S7': 'AND returns results containing both terms and limits results; OR returns at least one term and gives more results; NOT excludes a term (Google uses -word with no space); irrelevant results are false positives',
  'T7-S8': 'Brackets first, then most search engines give AND precedence over OR, NOT term excluded before anything else; search symbols + is AND, | is OR, - is NOT; Pets NOT cats is F(P,C) = P.C\'',
  'T7-S9': 'Truth tables list 2^n combinations (4 for two terms, 8 for three); Europe AND (Paris OR Amsterdam) is E.(P + A), true for 101, 110, 111 so F = EP\'A + EPA\' + EPA',
  'T7-S10': 'Good UI: constant informative feedback, readability (few elements, recognisable icons, dark on light), three-click rule navigation, at most three colours, red danger/yellow caution/green safe, simple layout, theme, consistent elements',
  'T7-S11': 'Desktop has keyboard, mouse, maybe touch so give multiple ways (Ctrl+C, Edit then Copy, right-click); mobile has a small touch screen, design for all sizes and low bandwidth, thumb friendly; tablets use sides and top corners; hybrids cluster controls bottom and sides',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Hyperlink Harbour',
  subtitle: 'Unit 7 \u00b7 Internet and WWW',
  color: 'teal',
  glow: 'ja-glow-teal',
  bg: 'ja-w-internet-www',
  icon: Globe,
  blurb: 'Trace packets across routers, crack IP addresses, hunt with AND, OR and NOT, and design interfaces that thumbs love.',
};

export const LEVELS = [
  { id: 't7-l1', name: 'Network of Networks', subtitle: 'The Internet, basic services and IP addresses', challengeIds: ['t7-c1', 't7-c2', 't7-c3', 't7-c4', 't7-c5', 't7-c6'] },
  { id: 't7-l2', name: 'Plugged In and Browsing', subtitle: 'Connections, the WWW, URLs and search engines', challengeIds: ['t7-c7', 't7-c8', 't7-c9', 't7-c10', 't7-c11', 't7-c12'] },
  { id: 't7-l3', name: 'Boolean Search Lab', subtitle: 'Logical operators, search expressions and truth tables', challengeIds: ['t7-c13', 't7-c14', 't7-c15', 't7-c16', 't7-c17', 't7-c18'] },
  { id: 't7-l4', name: 'Interface Architect', subtitle: 'Boss: UI design plus a mixed review of the whole unit', challengeIds: ['t7-c19', 't7-c20', 't7-c21', 't7-c22', 't7-c23', 't7-c24', 't7-c25'] },
];

export const CHALLENGES = {
  't7-c1': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Which statement best describes the Internet?',
    options: [
      'A single huge computer network owned and run by one company',
      'A worldwide collection of computer networks connected to share resources or communicate',
      'A mass of linked web pages that you view with a web browser',
      'A local network that connects the computers in one school building',
    ],
    answer: 1,
    hint: 'Think "global network" made of many smaller networks.',
    explanation: 'The Internet is a worldwide collection of computer networks connected for sharing resources or communicating. The linked web pages are the WWW, which runs on the Internet.',
    skills: ['T7-S1'],
  },
  't7-c2': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each part of Internet communication to its description.',
    pairs: [
      { left: 'Host', right: 'A sender or receiver computer, such as a workstation or a server' },
      { left: 'Communication link', right: 'Connects hosts and is made up of transmission media' },
      { left: 'Router', right: 'Determines the path data must travel from one host to another' },
      { left: 'Bounded media', right: 'Wired transmission media' },
      { left: 'Unbounded media', right: 'Wireless transmission media' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Communication on the Internet involves hosts, routers and links.',
    explanation: 'Hosts send and receive, links (wired or wireless media) connect them, and routers work out the path. A router usually connects an organisation\'s network to an ISP\'s network.',
    skills: ['T7-S1'],
  },
  't7-c3': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: a benefit of cloud storage is that you can still reach your files even if your Internet connection is down.',
    answer: false,
    hint: 'Where are the files actually stored, and how do you reach them?',
    explanation: 'Cloud storage is accessed over the Internet, so an unreliable Internet connection can stop data access. This is one of the concerns, not a benefit.',
    skills: ['T7-S2'],
  },
  't7-c4': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each protocol or system to what it does.',
    pairs: [
      { left: 'TCP', right: 'Makes sure the transmission gets from the sender host to the destination host' },
      { left: 'IP', right: 'Identifies the different computers connected to the Internet' },
      { left: 'DNS', right: 'Addressing system that assigns unique names and numbers to hosts' },
      { left: 'SMTP', right: 'Used to send email messages' },
      { left: 'POP or IMAP', right: 'Used to retrieve email messages from a mail server' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Two of these together form the TCP/IP suite; two are email protocols.',
    explanation: 'TCP and IP form the TCP/IP suite, DNS gives hosts unique names and numbers, SMTP sends email and POP or IMAP retrieves it.',
    skills: ['T7-S2', 'T7-S3'],
  },
  't7-c5': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'The host funworks.co.za has this IPv4 address in binary. Convert each byte to decimal, then type the full address in dotted decimal.',
    code: '00101001 . 10111001 . 00010000 . 00001010\nPlace values: 128 64 32 16 8 4 2 1',
    rows: [
      { label: 'Byte 1 in decimal', answer: '41' },
      { label: 'Byte 2 in decimal', answer: '185' },
      { label: 'Byte 3 in decimal', answer: '16' },
      { label: 'Byte 4 in decimal', answer: '10' },
      { label: 'Full IP address (dotted decimal)', answer: '41.185.16.10' },
    ],
    hint: 'Add the place values wherever there is a 1 in the byte.',
    explanation: '00101001 = 32 + 8 + 1 = 41, 10111001 = 128 + 32 + 16 + 8 + 1 = 185, 00010000 = 16 and 00001010 = 8 + 2 = 10, so the address is 41.185.16.10.',
    skills: ['T7-S3'],
  },
  't7-c6': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'In a movie, a hacker types the IP address 112.203.1.256. Why is this address incorrect?',
    code: '112.203.1.256',
    options: [
      'It has only four numbers, but an IPv4 address needs six',
      'The first number is too big to start an IP address',
      'Each number is one 8-bit byte, so it must be 0 to 255, and 256 is too big',
      'IPv4 addresses are not allowed to contain the number 1',
    ],
    answer: 2,
    hint: 'What is the largest value 8 bits can hold?',
    explanation: 'IPv4 uses 32 bits divided into four 8-bit numbers ranging from 0 to 255. 256 needs 9 bits, so the address cannot exist, which is exactly why a movie might use it.',
    skills: ['T7-S3'],
  },
  't7-c7': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each type of Internet connection to its description.',
    pairs: [
      { left: 'ADSL', right: 'Fast data transmission over copper telephone lines; needs a special router' },
      { left: 'Fibre', right: 'Uses light to transmit data at superfast speeds and high capacities' },
      { left: 'Wireless (Wi-Fi)', right: 'Uses radio frequency instead of telephone lines or cables; always on' },
      { left: 'Cellular', right: 'Uses a SIM card; common speeds are 3G and 4G' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Think copper, light, radio and SIM.',
    explanation: 'ADSL (Asymmetric Digital Subscriber Line) runs over copper telephone lines with an ADSL router, fibre uses light, Wi-Fi uses radio frequency and cellular uses a SIM card on 3G or 4G networks.',
    skills: ['T7-S4'],
  },
  't7-c8': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Angelo\'s phone is not in range of any Wi-Fi access point. Which item in the phone lets it reach the Internet using mobile data?',
    options: [
      'A SIM card',
      'A browser app such as Safari',
      'An ADSL router',
      'A fibre optic cable',
    ],
    answer: 0,
    hint: 'Mobile data comes from the cellular provider.',
    explanation: 'A mobile device needs a SIM card for access to mobile data. A browser app is also needed to view pages, but it does not provide the connection.',
    skills: ['T7-S4'],
  },
  't7-c9': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: the Internet and the World Wide Web are two names for the same thing.',
    answer: false,
    hint: 'One runs on top of the other.',
    explanation: 'The Internet is a global network of interconnected computer networks. The Web runs on the Internet and consists of documents connected by hyperlinks or URLs.',
    skills: ['T7-S5'],
  },
  't7-c10': {
    type: 'order', world: UNIT.worldId,
    prompt: 'Put the parts of this URL in the order they appear, from left to right.',
    code: 'http://www.schoolname.co.za/High/Academics/tabid/88/Details.html',
    items: [
      'The path to the resource on the server hosting the web site',
      'The protocol used to access the resource',
      'The domain name that points to the resource',
      'www, the World Wide Web',
    ],
    answer: [1, 3, 2, 0],
    hint: 'The URL starts with how to talk to the server and ends with where the file is on it.',
    explanation: 'http:// is the protocol, www is the World Wide Web, .schoolname.co.za is the domain name and /High/Academics/tabid/88/Details.html is the path on the server.',
    skills: ['T7-S5'],
  },
  't7-c11': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'What is the primary function of a web browser such as Google Chrome, MS Edge or Mozilla Firefox?',
    options: [
      'To store web sites online in the cloud for a fee',
      'To assign unique IP addresses to hosts',
      'To search the web for keywords and list the matching documents',
      'To process HTML code and display the web page in the browser window',
    ],
    answer: 3,
    hint: 'HTML is the code used to mark up web pages. Who reads it?',
    explanation: 'A browser locates and views web pages; its primary function is to process HTML. Searching for keywords is the job of a search engine, which you use through a browser.',
    skills: ['T7-S6'],
  },
  't7-c12': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Angelo only wants pages that contain the words IP Addresses exactly as he typed them, together. What should he type?',
    options: [
      'inurl: IP Addresses',
      '"IP Addresses"',
      'IP | Addresses',
      'define: IP Addresses',
    ],
    answer: 1,
    hint: 'A specific phrase is marked with a pair of characters around it.',
    explanation: 'Placing a phrase in inverted commas tells the search engine to only find pages with those terms exactly as typed. inurl: searches the web address and define: looks for definitions.',
    skills: ['T7-S6'],
  },
  't7-c13': {
    type: 'order', world: UNIT.worldId,
    prompt: 'In Activity 5 you compare result counts. Order these searches from the MOST results to the FEWEST results.',
    items: [
      'Earth AND Wind',
      'Earth OR Wind OR Fire',
      'Earth AND Wind AND Fire',
      'Earth',
    ],
    answer: [1, 3, 0, 2],
    hint: 'Each OR adds results; each AND takes results away.',
    explanation: 'OR means at least one term is required, so it returns the most. Every AND you add returns fewer results, so Earth AND Wind AND Fire returns the fewest.',
    skills: ['T7-S7'],
  },
  't7-c14': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Google does not work with the word NOT. How should Angelo search for wind but exclude fire in Google?',
    options: [
      'wind - fire',
      'wind NOT fire',
      'wind | fire',
      'wind -fire',
    ],
    answer: 3,
    hint: 'Look carefully at the spacing.',
    explanation: 'Instead of NOT, Google uses the - character with no space between the dash and the keyword you want to exclude. The | symbol means OR.',
    skills: ['T7-S7'],
  },
  't7-c15': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Which part of this search will be evaluated first?',
    code: 'South Africa AND (endangered species OR protected species)',
    options: [
      'endangered species OR protected species',
      'South Africa',
      'South Africa AND endangered species',
      'protected species',
    ],
    answer: 0,
    hint: 'Like BODMAS in Mathematics.',
    explanation: 'Statements in brackets (parentheses) are dealt with first, so the OR inside the brackets is evaluated before the AND.',
    skills: ['T7-S8'],
  },
  't7-c16': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'The search "pets -cats" means Pets NOT cats. Which Boolean function represents it, with P for Pets and C for Cats?',
    options: [
      'F(P,C) = P + C',
      'F(P,C) = P.C',
      'F(P,C) = P.C\'',
      'F(P,C) = P\' + C',
    ],
    answer: 2,
    hint: 'NOT is shown with a dash in the search and with a prime (\') in the function.',
    explanation: 'Pets AND NOT cats is written F(P,C) = P.C\': the dot is AND and the prime on C means NOT cats.',
    skills: ['T7-S8'],
  },
  't7-c17': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'Exercise 2: virus (V) or spam (S) but not hacking (H) gives F(V,S,H) = (V + S).H\'. Work out F for each row. Type 1 or 0.',
    code: 'V S H | (V + S).H\'\n1 0 0 | ?\n0 1 1 | ?\n0 0 0 | ?\n1 1 0 | ?',
    rows: [
      { label: 'Row V=1, S=0, H=0', answer: '1' },
      { label: 'Row V=0, S=1, H=1', answer: '0' },
      { label: 'Row V=0, S=0, H=0', answer: '0' },
      { label: 'Row V=1, S=1, H=0', answer: '1' },
    ],
    hint: 'Work out the bracket first, then AND it with the opposite of H.',
    explanation: 'F is 1 only when at least one of V or S is 1 AND H is 0. When H is 1 the NOT makes the whole AND false; when V and S are both 0 the bracket is false.',
    skills: ['T7-S9', 'T7-S8'],
  },
  't7-c18': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: a truth table for a search with three terms, such as Europe, Paris and Amsterdam, has 6 rows of possible combinations.',
    answer: false,
    hint: 'Each term has two possible truth values.',
    explanation: 'With three terms there are 2^3 = 8 possible combinations. Two terms give 2^2 = 4.',
    skills: ['T7-S9'],
  },
  't7-c19': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each user interface design principle to the guideline from the textbook.',
    pairs: [
      { left: 'Readability', right: 'Reduce the number of elements and use recognisable icons' },
      { left: 'Navigation', right: 'Apply the three-click rule and keep menus in the same place' },
      { left: 'Typography/Colour', right: 'Limit the design to at most three colours with variations in shade' },
      { left: 'Layout', right: 'Keep it simple and place important sections where the user will look' },
      { left: 'Theme', right: 'Give all pages the same look and feel, applied using software' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Clicks belong to moving around; shades belong to colour.',
    explanation: 'Each principle has its own focus: readability (few elements, clear icons), navigation (three clicks, consistent menus), typography and colour, layout (simple, important parts where users look) and theme (consistent look and feel).',
    skills: ['T7-S10'],
  },
  't7-c20': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'What does the "three-click rule" in web site design say?',
    options: [
      'A user should never need to click more than three times on any single button',
      'After entering a web site, a user should achieve their purpose in a maximum of three clicks',
      'Every page must contain exactly three hyperlinks to other pages',
      'A web site must have no more than three pages besides the home page',
    ],
    answer: 1,
    hint: 'It is about how quickly the user reaches their goal.',
    explanation: 'A user entering a web site should be able to achieve their purpose in at most three clicks; otherwise they are likely to move to a different web site.',
    skills: ['T7-S10'],
  },
  't7-c21': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: the Close button should have the same shape, colour and size and appear in a similar position on every screen.',
    answer: true,
    hint: 'Elements that behave the same should ...',
    explanation: 'Consistency means elements that behave the same look the same and are placed in the same position on each screen. Elements that behave differently should look different.',
    skills: ['T7-S10'],
  },
  't7-c22': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Where should you cluster the controls when designing for touch screen laptops and hybrids?',
    options: [
      'Around the bottom and sides of the screen',
      'Along the centre of the top edge',
      'Only in the middle of the screen',
      'Spread evenly over the whole screen',
    ],
    answer: 0,
    hint: 'Think where your hands rest when you hold or touch a hybrid.',
    explanation: 'For touch screen laptops and hybrids, controls should be clustered around the bottom and sides, where the thumbs and fingers reach easily.',
    skills: ['T7-S11'],
  },
  't7-c23': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'A desktop program lets you copy with Ctrl + C, with Edit then Copy, or by right-clicking and choosing Copy. Why is this good desktop design?',
    options: [
      'Desktop users have small touch screens, so bigger menus are needed',
      'Only one of the three methods works on most computers',
      'It makes the program load faster on low bandwidth connections',
      'Desktop users have a keyboard, a mouse and maybe a touch screen, so they need multiple ways to perform a function',
    ],
    answer: 3,
    hint: 'Think about the input devices a desktop user has.',
    explanation: 'Desktop interfaces should offer multiple ways to perform a function because the user has a keyboard, mouse and possibly a touch screen. All three copy methods work.',
    skills: ['T7-S11'],
  },
  't7-c24': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'Check Point 1: convert the IP address 24.3.212.34 to binary. Type each byte as exactly 8 bits (include leading zeros).',
    code: 'IP address: 24.3.212.34\nPlace values: 128 64 32 16 8 4 2 1',
    rows: [
      { label: 'Byte 1 (24)', answer: '00011000' },
      { label: 'Byte 2 (3)', answer: '00000011' },
      { label: 'Byte 3 (212)', answer: '11010100' },
      { label: 'Byte 4 (34)', answer: '00100010' },
    ],
    hint: 'Subtract the largest place value that fits, put a 1 there, and repeat.',
    explanation: '24 = 16 + 8, 3 = 2 + 1, 212 = 128 + 64 + 16 + 4 and 34 = 32 + 2. Each byte is written with 8 bits because IPv4 uses four 8-bit numbers.',
    skills: ['T7-S3'],
  },
  't7-c25': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Which of these searches will give you the FEWEST results?',
    options: [
      '(diabetes OR cancer) AND diet',
      'diabetes OR cancer OR diet',
      '(diabetes AND cancer) AND diet',
      'diabetes OR (cancer AND diet)',
    ],
    answer: 2,
    hint: 'Count how many terms each result is forced to contain.',
    explanation: 'With only ANDs, every result must contain all three terms, and every AND you add returns fewer results. Each OR lets more results in.',
    skills: ['T7-S7', 'T7-S8'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Understand how the Internet connects the world, how the World Wide Web and searching work, and how to design user-friendly interfaces.',
  outcomes: [
    'By the end you can define the Internet and explain the roles of hosts, routers and links.',
    'By the end you can describe cloud storage, email and web sites as basic Internet services.',
    'By the end you can explain TCP/IP, DNS and hostnames and convert IPv4 addresses between binary and decimal.',
    'By the end you can list what is needed to connect to the Internet and compare ADSL, fibre, wireless and cellular connections.',
    'By the end you can distinguish the WWW from the Internet, a web page from a web site, and name the parts of a URL.',
    'By the end you can explain browsers and search engines and search successfully.',
    'By the end you can use AND, OR and NOT, apply the order of operations and write searches as Boolean functions.',
    'By the end you can evaluate a search expression with a truth table.',
    'By the end you can apply user interface design principles to desktop and mobile designs.',
  ],
  topics: [
    {
      id: 'T7-T1',
      title: 'The Internet and its basic services',
      sections: ['7.1', '7.2', '7.2.1', '7.2.2', '7.2.3'],
      skills: ['T7-S1', 'T7-S2'],
      explanation: [
        'The Internet is a worldwide collection of computer networks that can be connected for the purposes of sharing resources or communicating. Because it spans the whole world it is a global network, and information usually travels through several interconnected networks.',
        'Communication on the Internet involves hosts, routers and links. A host is a sender or receiver computer, such as your workstation or a server. Hosts are connected by communication links made of bounded (wired) or unbounded (wireless) transmission media.',
        'Routers determine the path(s) data must travel to get from one host to another. A router is usually used to connect an organisation\'s network to an ISP\'s network to enable Internet access.',
        'Cloud storage is the storage of data online, "in the cloud", for a fee. Benefits: no new equipment to buy, no expensive storage devices to manage, access any time from any place on any device with Internet, an automatic remote backup, and you only pay for the space you use. Concerns: an unreliable Internet connection can stop data access, you have no control over the company\'s security other than trusting their contract, and the company could close or have an irrecoverable disaster.',
        'Email (electronic mail) is sent via the Internet to any recipient with an email address. SMTP is used to send messages, while POP or IMAP are used to retrieve messages from a mail server. Setting up an account needs an email address, password and mail servers, although most webmail services configure this automatically.',
        'A web site is a collection of linked web pages accessed with an Internet browser. Web sites are accessed by their domain name and are created, uploaded and managed by a person, company or organisation.',
      ],
      vocabulary: [
        { term: 'Internet', definition: 'A worldwide collection of computer networks that can be connected for the purposes of sharing resources or communicating.' },
        { term: 'Host', definition: 'A sender or receiver computer, such as a workstation or a server.' },
        { term: 'Router', definition: 'A device that determines the path(s) data must travel to get from one host to another.' },
        { term: 'Cloud storage', definition: 'The storage of data online, "in the cloud", usually for a fee.' },
        { term: 'SMTP', definition: 'The protocol used to send email messages.' },
        { term: 'POP / IMAP', definition: 'Protocols used to retrieve email messages from a mail server.' },
        { term: 'Web site', definition: 'A collection of linked web pages accessed using an Internet browser and reached by its domain name.' },
      ],
      workedExamples: [
        { code: 'Your PC (host) -> school router -> ISP network -> ... routers ... -> web server (host)', explanation: 'A message travels from a sender host over links through several routers and networks before it reaches the destination host.' },
      ],
      misconceptions: [
        'Cloud storage means your files are stored nowhere physical. Wrong: the files are stored on the storage company\'s devices, which is why you must trust their security and their survival.',
        'Email uses one protocol for everything. Wrong: SMTP sends messages, while POP or IMAP retrieve them from the mail server.',
      ],
      questions: [
        {
          id: 'T7-T1-Q1', type: 'mc', category: 'define',
          prompt: 'In Internet communication, what is a host?',
          options: [
            'A device that decides the path data travels between networks',
            'The wired or wireless media that joins two computers',
            'A sender or receiver computer, such as a workstation or a server',
            'The company that provides your Internet connection',
          ],
          answer: 2,
          hint: 'Hosts are at the two ends of a communication.',
          explanation: 'A host is a sender or receiver computer. Routers choose paths, links are the media, and the ISP provides access.',
          skills: ['T7-S1'],
        },
        {
          id: 'T7-T1-Q2', type: 'tf', category: 'identify',
          prompt: 'True or false: SMTP is used to send email messages, while POP or IMAP is used to retrieve messages from a mail server.',
          answer: true,
          hint: 'Sending and receiving use different sets of rules.',
          explanation: 'Different protocols are used: SMTP for sending, and POP or IMAP for retrieving from the mail server.',
          skills: ['T7-S2'],
        },
        {
          id: 'T7-T1-Q3', type: 'mc', category: 'classify',
          prompt: 'Which of these is a BENEFIT of cloud storage rather than a concern?',
          options: [
            'An unreliable Internet connection can stop data access',
            'You have no control over the security of the storage company',
            'The storage company could close or have an irrecoverable disaster',
            'You have an automatic remote backup of your data',
          ],
          answer: 3,
          hint: 'Three of these are things that could go wrong.',
          explanation: 'An automatic remote backup is a benefit. The other three are the concerns listed in the textbook.',
          skills: ['T7-S2'],
        },
        {
          id: 'T7-T1-Q4', type: 'tf', category: 'explain',
          prompt: 'True or false: web sites are accessed by their domain name using an application called an Internet browser.',
          answer: true,
          hint: 'Think of how you type funworks.co.za into a browser.',
          explanation: 'A web site is a collection of linked web pages, accessed through a browser by its domain name.',
          skills: ['T7-S2'],
        },
      ],
    },
    {
      id: 'T7-T2',
      title: 'IP addresses, TCP/IP and DNS',
      sections: ['7.3'],
      skills: ['T7-S3'],
      explanation: [
        'Computers need protocols (sets of rules) to communicate. The most common on the Internet are TCP (Transmission Control Protocol) and IP (Internet Protocol). TCP makes sure the transmission gets from the sender host to the destination host, while IP identifies the different computers connected to the Internet. Together they are the TCP/IP suite.',
        'TCP/IP allows direct access to the Internet and enables communication between computer systems that may be totally different.',
        'The Domain Name System (DNS) assigns unique names and numbers to the hosts connected to the Internet. Each host has a hostname (also called a domain name) and a unique IP address. A hostname is made of words and is easy for humans to understand; an IP address is a 32-bit or 128-bit number that is difficult for humans to read.',
        'IPv4 uses 32 bits divided into four 8-bit numbers (0 to 255) separated by dots. To write one, split the binary into four bytes, convert each byte to decimal and separate the decimals with dots. If you know a computer\'s IP address you can type it into a browser instead of the URL.',
        '32 bits allow 2^32 different addresses, about 4.29 billion. All of these IPv4 addresses have now been assigned, causing a shortage, so a new version, IPv6, has been introduced (covered in Grade 11).',
        'Activity 1 and 2: at the Command Prompt, tracert www.howstuffworks.com lists the "hops" from router to router, with the web site\'s IP address on the last line. The command ipconfig shows the Windows IP Configuration, including the IP address of your own computer.',
      ],
      vocabulary: [
        { term: 'TCP', definition: 'Transmission Control Protocol: makes sure the transmission gets from the sender host to the destination host.' },
        { term: 'IP', definition: 'Internet Protocol: identifies the different computers connected to the Internet.' },
        { term: 'DNS', definition: 'Domain Name System: the addressing system that assigns unique names and numbers to hosts connected to the Internet.' },
        { term: 'Hostname', definition: 'A host\'s name made up of words (also called a domain name), such as funworks.co.za.' },
        { term: 'IPv4 address', definition: 'A 32-bit address written as four 8-bit numbers from 0 to 255 separated by dots, such as 41.185.16.10.' },
      ],
      workedExamples: [
        { code: '10000011 01101011 00000010 11001000\n10000011 . 01101011 . 00000010 . 11001000\n   131   .    107   .     2    .   200\n= 131.107.2.200', explanation: 'Split the 32 bits into four bytes, convert each byte to decimal (128 + 2 + 1 = 131, 64 + 32 + 8 + 2 + 1 = 107, 2, 128 + 64 + 8 = 200) and join with dots.' },
        { code: 'Hostname: funworks.co.za\nIP address: 41.185.16.10', explanation: 'The same host is identified by an easy-to-read hostname and by a unique IP address.' },
      ],
      misconceptions: [
        'Any four numbers with dots form a valid IPv4 address. Wrong: each number is one byte, so it must be from 0 to 255; 112.203.1.256 is invalid.',
        'There are unlimited IPv4 addresses. Wrong: 32 bits allow only 2^32 (about 4.29 billion) addresses, and they have all been assigned, which is why IPv6 was introduced.',
      ],
      questions: [
        {
          id: 'T7-T2-Q1', type: 'trace', category: 'calculate',
          prompt: 'Work out these IPv4 facts. Type whole numbers only, with no spaces or commas.',
          code: 'IPv4 address = 32 bits = four 8-bit numbers\nNumber of addresses = 2^32\nLargest value in 8 bits = ?',
          rows: [
            { label: 'Exact number of different IPv4 addresses (2^32)', answer: '4294967296' },
            { label: 'Largest decimal value in one byte of an IPv4 address', answer: '255' },
          ],
          hint: '2^10 is 1024; 2^32 is a little over 4 billion. Eight 1s in binary is the largest byte.',
          explanation: '2^32 = 4 294 967 296, about 4.29 billion addresses. 11111111 = 128 + 64 + 32 + 16 + 8 + 4 + 2 + 1 = 255.',
          skills: ['T7-S3'],
        },
        {
          id: 'T7-T2-Q2', type: 'mc', category: 'distinguish',
          prompt: 'Which statement correctly compares a hostname and an IP address?',
          options: [
            'A hostname is made of words and easy for humans to read; an IP address is a 32-bit or 128-bit number',
            'A hostname is a 32-bit number; an IP address is made of words',
            'A hostname identifies a web page; an IP address identifies a web site',
            'A hostname is only used for email; an IP address is only used for web sites',
          ],
          answer: 0,
          hint: 'One is for people, one is for computers.',
          explanation: 'Each host has both a hostname (words, easy for humans) and a unique IP address (a 32-bit or 128-bit number, hard for humans to read).',
          skills: ['T7-S3'],
        },
        {
          id: 'T7-T2-Q3', type: 'order', category: 'sequence',
          prompt: 'Activity 1: put these steps in order to find a web site\'s IP address with tracert and then visit the site using it.',
          items: [
            'Enter that IP address in the browser\'s address bar',
            'Open a Command Prompt window',
            'Read the web site\'s IP address on the last line of the list of hops',
            'Type tracert www.howstuffworks.com and press Enter',
          ],
          answer: [1, 3, 2, 0],
          hint: 'You need the command window before you can type a command.',
          explanation: 'Open the Command Prompt, run tracert, read the IP address on the last hop, then type it into the browser to reach the same site.',
          skills: ['T7-S3'],
        },
      ],
    },
    {
      id: 'T7-T3',
      title: 'Connecting to the Internet',
      sections: ['7.4', '7.4.1', '7.4.2', '7.4.2.1', '7.4.2.2', '7.4.2.3', '7.4.2.4'],
      skills: ['T7-S4'],
      explanation: [
        'A device needs certain hardware and software depending on the type of connection used.',
        'A computer needs a network card or must be wireless enabled, software such as an Internet browser, and a device such as a router or wireless router to connect to a physical line or a wireless access point.',
        'A mobile device needs a SIM card for mobile data, Wi-Fi capabilities to connect to an access point in range or to a personal hotspot (tethered to a second device to use its mobile data), and a browser app, such as Safari on Apple devices.',
        'ADSL (Asymmetric Digital Subscriber Line) provides fast data transmission over copper telephone lines and requires an ADSL router. Fibre uses light to transmit data at superfast speeds and high capacities.',
        'Wireless (Wi-Fi) does not use telephone lines or cables; it uses radio frequency, is always on and can be accessed from just about anywhere. Cellular access uses a SIM card; speeds vary by provider, with 3G (3rd generation) and 4G (fourth generation) most common.',
      ],
      vocabulary: [
        { term: 'ADSL', definition: 'Asymmetric Digital Subscriber Line: fast data transmission over copper telephone lines, using an ADSL router.' },
        { term: 'Fibre', definition: 'A data communications technology that uses light to transmit data at superfast speeds and high capacities.' },
        { term: 'Wi-Fi', definition: 'A wireless, always on connection that uses radio frequency instead of telephone lines or cables.' },
        { term: 'Personal hotspot', definition: 'A mobile device tethered to a second device to use the mobile data available to the second device.' },
        { term: '3G / 4G', definition: 'Third and fourth generation cellular wireless standards.' },
      ],
      workedExamples: [],
      misconceptions: [
        'A browser alone connects you to the Internet. Wrong: you also need hardware such as a network card or wireless capability and a router or SIM card.',
        'Wi-Fi runs over telephone cables. Wrong: Wi-Fi uses radio frequency; ADSL is the connection that uses copper telephone lines.',
      ],
      questions: [
        {
          id: 'T7-T3-Q1', type: 'mc', category: 'apply',
          prompt: 'A house in Durban has only a copper telephone line. Which connection type and device does it need to get on the Internet over that line?',
          options: [
            'Fibre, using a fibre optic cable',
            'ADSL, using an ADSL router',
            'Cellular, using a SIM card',
            'Wi-Fi, using radio frequency only',
          ],
          answer: 1,
          hint: 'Which technology was designed for copper telephone lines?',
          explanation: 'ADSL provides fast data transmission over copper telephone lines and requires an ADSL router.',
          skills: ['T7-S4'],
        },
        {
          id: 'T7-T3-Q2', type: 'tf', category: 'explain',
          prompt: 'True or false: a computer needs only an Internet browser to connect; no network card, wireless capability or router is required.',
          answer: false,
          hint: 'Software alone cannot reach a physical line or access point.',
          explanation: 'A computer needs a network card or wireless capability, a browser, and a device such as a router or wireless router.',
          skills: ['T7-S4'],
        },
      ],
    },
    {
      id: 'T7-T4',
      title: 'The World Wide Web and URLs',
      sections: ['7.5', '7.5.1', '7.5.2', '7.5.3'],
      skills: ['T7-S5'],
      explanation: [
        'The World Wide Web is a mass of linked web pages that can be accessed via the Internet. These hypertext documents are viewed with a web browser and may contain text, images, videos, sound and other multimedia. You navigate between them via hyperlinks.',
        'Web pages are often dynamically linked to databases to provide up-to-date information, and databases can in turn be updated from web pages.',
        'The Internet and the WWW are not the same thing. The Internet is a global network of interconnected computer networks; the Web runs on the Internet and consists of interconnected documents connected by hyperlinks or URLs.',
        'A web page is any document on the Web, text only or with graphics, videos, audio and hyperlinks. A web site is made up of a number of web pages, is created and managed by an individual or a company, and always has a home page.',
        'Each web page has a unique address called the URL (Uniform Resource Locator). Many URLs begin with http:// (Hypertext Transfer Protocol). Sites with https:// are secure and safer for entering private information.',
      ],
      vocabulary: [
        { term: 'World Wide Web', definition: 'A mass of linked web pages which can be accessed via the Internet.' },
        { term: 'Hyperlink', definition: 'A link that lets you navigate from one web page to another.' },
        { term: 'Web page', definition: 'Any document on the Web.' },
        { term: 'Web site', definition: 'A number of web pages, created and managed by an individual or company, that always has a home page.' },
        { term: 'URL', definition: 'Uniform Resource Locator: the unique address of each web page on the Internet.' },
        { term: 'HTTP / HTTPS', definition: 'Hypertext Transfer Protocol; the s in https shows a secure site.' },
      ],
      workedExamples: [
        { code: 'http://  www  .schoolname.co.za  /High/Academics/tabid/88/Details.html\nprotocol  WWW   domain name        path to the resource on the server', explanation: 'The four parts of a URL: the protocol used to access the resource, www (the World Wide Web), the domain name that points to the resource and the path on the server hosting the site.' },
      ],
      misconceptions: [
        'The Web and the Internet are the same. Wrong: the Web is the linked documents; the Internet is the network that carries them.',
        'A web page and a web site mean the same thing. Wrong: a web site is made up of many web pages and always has a home page.',
      ],
      questions: [
        {
          id: 'T7-T4-Q1', type: 'mc', category: 'distinguish',
          prompt: 'Which statement correctly describes the difference between the Internet and the WWW?',
          options: [
            'The WWW is the hardware and the Internet is the software that runs on it',
            'The Internet is only used for email, while the WWW is used for everything else',
            'The WWW is a global network of networks, while the Internet is a collection of web pages',
            'The Internet is a global network of networks, while the Web runs on it and consists of documents linked by hyperlinks',
          ],
          answer: 3,
          hint: 'Which one is the network, and which one is the documents?',
          explanation: 'The Internet is the global network of interconnected networks; the Web runs on the Internet and is made of documents connected by hyperlinks or URLs.',
          skills: ['T7-S5'],
        },
        {
          id: 'T7-T4-Q2', type: 'mc', category: 'explain',
          prompt: 'Angelo wants to buy a game online. What does the s in https:// at the start of the URL tell him?',
          options: [
            'The site is secure and safer for entering private information',
            'The site is a search engine',
            'The site is stored on a server in South Africa',
            'The site has several web pages',
          ],
          answer: 0,
          hint: 'Think about entering banking details.',
          explanation: 'Web sites with https:// include the s to show that they are secure sites, safer for a user entering private information.',
          skills: ['T7-S5'],
        },
        {
          id: 'T7-T4-Q3', type: 'tf', category: 'define',
          prompt: 'True or false: a web site is made up of a number of web pages and always has a home page.',
          answer: true,
          hint: 'Where do you land when you first type the domain name?',
          explanation: 'A web site is made up of many web pages, which hyperlinks can lead to, and it always has a home page.',
          skills: ['T7-S5'],
        },
      ],
    },
    {
      id: 'T7-T5',
      title: 'Web browsers, search engines and successful searching',
      sections: ['7.6', '7.6.1', '7.6.2', '7.6.3'],
      skills: ['T7-S6'],
      explanation: [
        'A web browser is a program used to locate and view web pages, such as Google Chrome, MS Edge or Mozilla Firefox. Its primary function is to process HTML, the code used to mark up web pages, and display the result. Browsers also offer bookmarks, refresh and navigation buttons, and page tabs.',
        'A search engine is a program that searches documents on the web for specified keywords and returns a list of the documents where the keywords were found, with hyperlinks to the relevant pages.',
        'Successful searching balances being too general against being too specific; the main aim is to reduce the number of returns. State exactly what you want to find, identify keywords and use synonyms.',
        'Useful techniques (Activity 3): put a phrase in inverted commas for an exact match ("IP Addresses"); inurl: network finds sites with network in the web address; and ensures both items are included (zoos and South Africa); site: limits to a domain such as .edu, .org or .gov; define: finds definitions.',
        'Different search engines return different results and some specialise in genres such as games or books. Google Scholar returns scholarly research from theses, papers and books written by academics, while ordinary Google searches do not have to be based on research.',
      ],
      vocabulary: [
        { term: 'Web browser', definition: 'A program used to locate and view web pages by processing HTML.' },
        { term: 'HTML', definition: 'The code used to design or mark up web pages.' },
        { term: 'Search engine', definition: 'A program that searches documents on the web for specified keywords and returns a list of matching documents with hyperlinks.' },
        { term: 'Bookmark', definition: 'A browser feature that saves a link to a favourite site.' },
      ],
      workedExamples: [
        { code: '"IP Addresses"\ninurl: network\nzoos and South Africa\nsite:edu "web cams"\ndefine: Fake News', explanation: 'Exact phrase, word in the URL, both terms, limit to educational sites, and find a definition.' },
      ],
      misconceptions: [
        'A browser and a search engine are the same thing. Wrong: the browser displays web pages; a search engine is a program (used through the browser) that finds pages matching keywords.',
        'More search results is always better. Wrong: the aim of successful searching is to reduce the number of returns to the relevant ones.',
      ],
      questions: [
        {
          id: 'T7-T5-Q1', type: 'mc', category: 'define',
          prompt: 'Which description fits a search engine?',
          options: [
            'A program that processes HTML and displays pages in a window',
            'A device that connects an organisation\'s network to an ISP',
            'A program that searches web documents for keywords and returns hyperlinks to matching pages',
            'A feature that saves a link to your favourite sites',
          ],
          answer: 2,
          hint: 'It works with keywords.',
          explanation: 'A search engine searches documents on the web for specified keywords and returns a list of documents with hyperlinks. Processing HTML is the browser\'s job; saving links is a bookmark.',
          skills: ['T7-S6'],
        },
        {
          id: 'T7-T5-Q2', type: 'mc', category: 'apply',
          prompt: 'Angelo wants results about web cams only from educational sites. Which search should he type?',
          options: [
            'define: "web cams"',
            'site:edu "web cams"',
            'inurl: web cams',
            'web cams OR edu',
          ],
          answer: 1,
          hint: 'You want to limit the search to one kind of domain.',
          explanation: 'site: limits a search to a specific domain such as .edu, .org or .gov, and the inverted commas keep "web cams" together as a phrase.',
          skills: ['T7-S6'],
        },
        {
          id: 'T7-T5-Q3', type: 'tf', category: 'explain',
          prompt: 'True or false: the main aim of successful searching is to increase the number of returns so that nothing is missed.',
          answer: false,
          hint: 'Think about balancing too general and too specific.',
          explanation: 'The main aim is to reduce the number of returns by stating exactly what you want, identifying keywords and using synonyms.',
          skills: ['T7-S6'],
        },
      ],
    },
    {
      id: 'T7-T6',
      title: 'Searching with logical operators AND, OR, NOT',
      sections: ['7.6.4', '7.6.4.1', '7.6.4.2', '7.6.4.3'],
      skills: ['T7-S7'],
      explanation: [
        'Logical (Boolean) operators define the logical relationship between search terms. The operators are AND, OR and NOT, and any number of search terms can be connected with them to refine results. The only time you will not use search logic is when you search for a single item.',
        'AND gives results that contain both terms. Rugby players AND known South Africans returns South African rugby players. AND limits results: every AND you add returns fewer results. In a Venn diagram, AND is only the overlap of the two circles.',
        'OR gives results that contain one, several or all of the terms: "at least one is required, more than one or all can be returned". Rugby players OR known South Africans returns known players from anywhere in the world as well as known South Africans. Every OR you add returns more results.',
        'NOT excludes keywords. Rugby players NOT known South Africans returns known players excluding all South Africans. Google does not work with NOT; use the - character with no space before the keyword, for example wind -fire.',
        'When a search produces many results that are not relevant to the query, these are called false positive results.',
      ],
      vocabulary: [
        { term: 'AND', definition: 'Returns results that contain both terms; limits the results.' },
        { term: 'OR', definition: 'Returns results that contain at least one of the terms; increases the results.' },
        { term: 'NOT', definition: 'Excludes a keyword from the search results.' },
        { term: 'False positive results', definition: 'Search results that are not relevant to the query.' },
      ],
      workedExamples: [
        { code: 'Earth OR Wind OR Fire   (most results)\nEarth\nEarth AND Wind AND Fire (fewest results)\nwind -fire              (Google form of wind NOT fire)', explanation: 'Activity 5: OR grows the result count, AND shrinks it, and NOT removes pages containing the excluded word.' },
      ],
      misconceptions: [
        'Adding more AND terms gives more results because you typed more words. Wrong: every AND you add returns fewer results.',
        'Google understands the word NOT. Wrong: in Google you use -keyword with no space after the dash.',
      ],
      questions: [
        {
          id: 'T7-T6-Q1', type: 'mc', category: 'predict',
          prompt: 'What will the search rugby players OR known South Africans return?',
          options: [
            'Known rugby players from anywhere in the world as well as known South Africans',
            'Only South African rugby players',
            'Only known rugby players who are not South African',
            'Only known South Africans who do not play rugby',
          ],
          answer: 0,
          hint: 'OR means at least one is required.',
          explanation: 'OR returns results with either term or both, so you get all known players plus all known South Africans. Only South African rugby players would be the AND search.',
          skills: ['T7-S7'],
        },
        {
          id: 'T7-T6-Q2', type: 'tf', category: 'predict',
          prompt: 'True or false: for every OR you add to a search query, fewer results are returned.',
          answer: false,
          hint: 'Compare with what each AND does.',
          explanation: 'Every OR adds more results; it is every AND that returns fewer results.',
          skills: ['T7-S7'],
        },
        {
          id: 'T7-T6-Q3', type: 'mc', category: 'define',
          prompt: 'What are false positive results?',
          options: [
            'Results that are excluded by a NOT operator',
            'Pages that the search engine could not load',
            'Results that contain both search terms joined by AND',
            'Many results that are not relevant to the query',
          ],
          answer: 3,
          hint: 'The search says "yes", but the result is not what you wanted.',
          explanation: 'When a search produces many results that are not relevant to the query, these results are called false positive results.',
          skills: ['T7-S7'],
        },
      ],
    },
    {
      id: 'T7-T7',
      title: 'Order of operations and search expressions',
      sections: ['7.6.5', '7.6.5.1'],
      skills: ['T7-S8'],
      explanation: [
        'Just as BODMAS sets the order of operations in Mathematics, Boolean statements have an order: statements in brackets (parentheses) are dealt with first, and then most search engines give AND precedence over OR.',
        'NOT is a very powerful operator: the "NOTed" term will be excluded before any other statement is evaluated. Be careful, because useful pages that happen to mention the NOTed term are lost.',
        'Different search engines may use different symbols: + refers to AND, | refers to OR and - refers to NOT.',
        'A search can also be written as a Boolean function with one variable per term. In a Boolean function the dot (.) means AND, + means OR and a prime (\') means NOT. Pets NOT cats can be typed as "pets -cats" and written as F(P,C) = P.C\'.',
        'Watch the + sign: in a search box + means AND, but in a Boolean function + means OR. Crime AND poverty AND gender is typed "Crime + poverty + gender" but written as the function F(C,P,G) = C.P.G.',
      ],
      vocabulary: [
        { term: 'Order of operations', definition: 'Brackets first, then AND before OR in most search engines; a NOTed term is excluded before anything else.' },
        { term: '+ (in a search)', definition: 'Search symbol for AND.' },
        { term: '| (in a search)', definition: 'Search symbol for OR.' },
        { term: '- (in a search)', definition: 'Search symbol for NOT.' },
      ],
      workedExamples: [
        { code: 'Mammals excluding cats and dogs\nSearch:   mammals -cats -dogs\nFunction: F(M,C,D) = M.C\'.D\'', explanation: 'Exercise 1.1: M = mammals, C = cats, D = dogs. Each excluded term gets a dash in the search and a prime in the function.' },
        { code: 'RAM, ROM and BIOS excluding CMOS and male sheep\nSearch:   RAM + ROM + BIOS -CMOS -"male sheep"\nFunction: F(R,O,B,C,M) = R.O.B.C\'.M\'', explanation: 'Exercise 1.3: excluding "male sheep" stops results about rams, the animals.' },
        { code: 'Programmer, developer or system analyst jobs in South Africa and the USA\nSearch:   (programmer | developer | "system analyst") + jobs + "South Africa" + USA\nFunction: F(P,D,A,J,S,U) = (P + D + A).J.S.U', explanation: 'Exercise 1.4: the job titles are joined with OR inside brackets so they are evaluated first.' },
      ],
      misconceptions: [
        'Search engines read a query strictly from left to right. Wrong: brackets come first, then AND before OR, and a NOTed term is excluded before anything else.',
        'The + sign means the same thing in a search box and in a Boolean function. Wrong: in a search + means AND, but in a Boolean function + means OR and the dot means AND.',
      ],
      questions: [
        {
          id: 'T7-T7-Q1', type: 'mc', category: 'apply',
          prompt: 'Exercise 1.1: which search expression finds mammals excluding cats and dogs?',
          options: [
            'mammals + cats + dogs',
            'mammals | cats | dogs',
            'mammals -cats -dogs',
            '-mammals cats dogs',
          ],
          answer: 2,
          hint: 'Which symbol excludes a term, and which term must stay?',
          explanation: 'The - symbol means NOT, so mammals -cats -dogs keeps mammals and excludes cats and dogs. As a function: F(M,C,D) = M.C\'.D\'.',
          skills: ['T7-S8'],
        },
        {
          id: 'T7-T7-Q2', type: 'mc', category: 'explain',
          prompt: 'Why should you be careful about using NOT in a search?',
          options: [
            'NOT is ignored by all search engines, so it wastes time',
            'The NOTed term is excluded before anything else, so relevant pages mentioning it are lost',
            'NOT always increases the number of results returned',
            'NOT can only be used inside brackets',
          ],
          answer: 1,
          hint: 'The textbook calls NOT a very powerful operator.',
          explanation: 'If you include a NOT, the NOTed term is excluded before any other statement is evaluated, so any page containing it disappears, even useful ones.',
          skills: ['T7-S8', 'T7-S7'],
        },
        {
          id: 'T7-T7-Q3', type: 'tf', category: 'identify',
          prompt: 'True or false: after brackets, most search engines give AND precedence over OR.',
          answer: true,
          hint: 'Compare with multiplication before addition in BODMAS.',
          explanation: 'Statements in brackets are dealt with first; thereafter most search engines evaluate AND before OR.',
          skills: ['T7-S8'],
        },
      ],
    },
    {
      id: 'T7-T8',
      title: 'Evaluating searches with truth tables',
      sections: ['7.6.5.2'],
      skills: ['T7-S9'],
      explanation: [
        'A truth table evaluates a logical expression. Each search term is either true or false, so two terms give 2^2 = 4 combinations and three terms give 2^3 = 8 combinations.',
        'For Mammals and Fish: Mammals AND Fish is true only when both are true; Mammals OR Fish is true when at least one is true.',
        'For Europe AND (Paris OR Amsterdam), F(E,P,A) = E.(P + A). Work out the bracket first, then AND it with E. The function is true in rows 101, 110 and 111.',
        'Reading the true rows gives F(E,P,A) = EP\'A + EPA\' + EPA: Europe without Paris with Amsterdam, Europe with Paris without Amsterdam, or Europe with both.',
        'Check Point 1 also asks you to negate a search with De Morgan\'s law (from Unit 6) and check that the negated column is the exact opposite of the original.',
      ],
      vocabulary: [
        { term: 'Truth table', definition: 'A table that lists every combination of true/false values and the result of the expression for each.' },
        { term: 'Number of combinations', definition: '2^n rows for n search terms.' },
      ],
      workedExamples: [
        { code: 'Mammals Fish | AND | OR\n   T     T   |  T  | T\n   T     F   |  F  | T\n   F     T   |  F  | T\n   F     F   |  F  | F', explanation: 'Two terms give four combinations. AND needs both; OR needs at least one.' },
        { code: 'E P A | E.(P + A)\n0 0 0 | 0\n0 0 1 | 0\n0 1 0 | 0\n0 1 1 | 0\n1 0 0 | 0\n1 0 1 | 1\n1 1 0 | 1\n1 1 1 | 1\nF(E,P,A) = EP\'A + EPA\' + EPA', explanation: 'Europe AND (Paris OR Amsterdam): only rows with E = 1 and at least one of P or A equal to 1 are true.' },
        { code: 'Laptops (L) and desktops (D) but not servers (S)\nF(L,D,S) = L.D.S\'  -> true only for L=1, D=1, S=0\nAlan Turing (A) after WW2 (S) but before 1950 (N)\nF(A,S,N) = A.S.N  -> true only for A=1, S=1, N=1', explanation: 'Exercise 2.2 and 2.3: expressions made only of ANDs are true in exactly one row.' },
      ],
      misconceptions: [
        'Three search terms give six combinations. Wrong: each term doubles the rows, so there are 2^3 = 8.',
        'E.(P + A) is true whenever Paris or Amsterdam is true. Wrong: Europe must also be true because of the AND.',
      ],
      questions: [
        {
          id: 'T7-T8-Q1', type: 'trace', category: 'calculate',
          prompt: 'Check Point 1 Q17: evaluate RAM AND (SSD OR HDD), F(R,S,H) = R.(S + H). Type 1 or 0 for each row, and the number of rows in the full table.',
          code: 'R S H | S + H | R.(S + H)\n1 0 1 |   ?   |    ?\n0 1 1 |   ?   |    ?\n1 0 0 |   ?   |    ?',
          rows: [
            { label: 'F for R=1, S=0, H=1', answer: '1' },
            { label: 'F for R=0, S=1, H=1', answer: '0' },
            { label: 'F for R=1, S=0, H=0', answer: '0' },
            { label: 'Number of rows in the full truth table', answer: '8' },
          ],
          hint: 'Do the OR in brackets first; then both R and the bracket must be 1.',
          explanation: 'Row 101: S + H = 1 and R = 1, so F = 1. Row 011: R = 0, so F = 0. Row 100: S + H = 0, so F = 0. Three terms give 2^3 = 8 rows.',
          skills: ['T7-S9'],
        },
        {
          id: 'T7-T8-Q2', type: 'mc', category: 'identify',
          prompt: 'Which function lists exactly the rows where Europe AND (Paris OR Amsterdam) is true?',
          options: [
            'F(E,P,A) = EP\'A + EPA\' + EPA',
            'F(E,P,A) = E\'P\'A\' + EPA',
            'F(E,P,A) = EP\'A\' + EPA',
            'F(E,P,A) = E + P + A',
          ],
          answer: 0,
          hint: 'E must be 1, and at least one of P or A must be 1.',
          explanation: 'The true rows are 101, 110 and 111, which give EP\'A + EPA\' + EPA.',
          skills: ['T7-S9'],
        },
        {
          id: 'T7-T8-Q3', type: 'mc', category: 'apply',
          prompt: 'Check Point 1 Q17.2: use De Morgan\'s law to negate F = R.(S + H).',
          options: [
            'F\' = R\'.(S\' + H\')',
            'F\' = R\' . S\' . H\'',
            'F\' = R + S + H',
            'F\' = R\' + S\'.H\'',
          ],
          answer: 3,
          hint: 'De Morgan swaps AND with OR and negates each part, including the bracket.',
          explanation: '(R.(S + H))\' = R\' + (S + H)\' = R\' + S\'.H\'. Its truth table column is the exact opposite of R.(S + H) in every row.',
          skills: ['T7-S9'],
        },
      ],
    },
    {
      id: 'T7-T9',
      title: 'User interface design principles',
      sections: ['7.8', '7.8.1', '7.8.2', '7.8.3', '7.8.4', '7.8.5', '7.8.6'],
      skills: ['T7-S10'],
      explanation: [
        'The user interface provides a system for a user to interact with a system such as a web site or program. A command line interface (CLI) requires the user to learn and type commands, which are easily misspelt. A GUI is easier because the user clicks buttons with text or icons.',
        'Good UI design focuses on what the user needs to do, with elements that are consistent, predictable and readable. It can eliminate errors and frustration. Constant informative feedback matters: if nothing happens when the user clicks, they assume the system, button or hyperlink is broken.',
        'Readability: reduce the number of elements on the screen, use readable fonts available in all browsers, dark on light or light on dark, and recognisable icons (magnifying glass for search, printer for print, disk to save). A remote with few clearly labelled buttons is easier than one with 50 ungrouped buttons.',
        'Navigation: apply the three-click rule, so a user achieves their purpose in at most three clicks. Keep menu bars and buttons in the same place on every page, use headings, and let the user return to the home page or the last page visited.',
        'Typography/colour: use colours as users expect (red danger, yellow caution, green safety), and limit colours to at most three with highlights or shades, for example light blue for an unclicked link and navy blue once clicked. Layout: keep it simple and put important sections where the user will look.',
        'Theme: gives all pages or screens a consistent look and feel with the same colours and menus, applied using software. Consistency: elements that behave the same look the same and sit in the same place (like the Close button); elements that behave differently look different.',
      ],
      vocabulary: [
        { term: 'User interface', definition: 'Provides a system for a user to interact with a system such as a web site or computer program.' },
        { term: 'Informative feedback', definition: 'The interface reacts every time the user clicks or moves the mouse.' },
        { term: 'Three-click rule', definition: 'A user entering a web site should achieve their purpose in a maximum of three clicks.' },
        { term: 'Theme', definition: 'Settings applied to all pages or screens so they have a consistent look and feel.' },
        { term: 'Consistency', definition: 'Elements that behave the same are the same in colour, design and position on every screen.' },
      ],
      workedExamples: [
        { code: 'Home monitoring app (Check Point 2 Q4)\n[Lights: ON]      green\n[Geyser: ON]      green\n[Back door: OPEN] red\n[Log out] same corner on every screen', explanation: 'Icons with text, red for a problem, green for OK, and the Log out button kept in the same place apply readability, colour and consistency together.' },
      ],
      misconceptions: [
        'Using lots of bright colours makes an interface more attractive. Wrong: too many colours make the screen busy and difficult to read; use at most three.',
        'If a button takes time to respond, there is no need to show anything. Wrong: without feedback the user will assume it is broken.',
      ],
      questions: [
        {
          id: 'T7-T9-Q1', type: 'mc', category: 'explain',
          prompt: 'Why should an interface give constant informative feedback each time the user clicks?',
          options: [
            'So that the user has to learn fewer commands',
            'So that the page loads on low bandwidth connections',
            'Because if nothing happens, the user will assume the system, button or hyperlink is broken',
            'Because feedback reduces the number of colours on the screen',
          ],
          answer: 2,
          hint: 'Imagine clicking a button and seeing no change.',
          explanation: 'Each time the user clicks or moves the mouse, the interface should react. If nothing happens, the user assumes something is broken.',
          skills: ['T7-S10'],
        },
        {
          id: 'T7-T9-Q2', type: 'tf', category: 'apply',
          prompt: 'True or false: in an app that monitors a house, showing that the back door is open in green follows good use of colour.',
          answer: false,
          hint: 'What do users expect red, yellow and green to mean?',
          explanation: 'Users expect red for danger, yellow for caution and green for safety. An open back door is a problem, so it should be red.',
          skills: ['T7-S10'],
        },
        {
          id: 'T7-T9-Q3', type: 'mc', category: 'distinguish',
          prompt: 'Why is a GUI usually easier to use than a command line interface (CLI)?',
          options: [
            'A GUI needs no input devices at all',
            'In a GUI the user clicks buttons with text or icons instead of remembering and typing commands that are easily misspelt',
            'A GUI shows more elements on the screen than a CLI',
            'A CLI cannot be used to run any programs',
          ],
          answer: 1,
          hint: 'Think about what a CLI user must remember.',
          explanation: 'A CLI requires the user to learn a large list of typed commands that can be misspelt. A GUI lets them click buttons that contain text or icons.',
          skills: ['T7-S10'],
        },
      ],
    },
    {
      id: 'T7-T10',
      title: 'Desktop design vs mobile design',
      sections: ['7.8.6', '7.8.7'],
      skills: ['T7-S11'],
      explanation: [
        'Consistency also applies across devices: the mobile version should have the same theme as the desktop version. The mobile version may not have all the desktop functions, but common elements must behave and appear the same.',
        'Desktop users have a keyboard, mouse and possibly a touch screen, so they need multiple ways to perform a function, for example copying with Ctrl + C, Edit then Copy, or right-click then Copy.',
        'A mobile device usually has a smaller touch screen that also acts as keyboard and mouse. Design for all screen sizes, and make sure the site or app loads on both low and high bandwidth connections.',
        'Designs must be finger friendly and, more specifically, thumb friendly. When a phone is held in the right hand, the textbook says the thumb falls naturally in an arc at the bottom left corner of the screen.',
        'On tablets the thumb zone changes with posture (sitting, standing, lying down), but users access the sides and top corners easily. For touch screen laptops and hybrids, cluster the controls around the bottom and sides.',
      ],
      vocabulary: [
        { term: 'Thumb friendly', definition: 'Designed so that the main actions can be reached by the thumb of the hand holding the device.' },
        { term: 'Thumb zone', definition: 'The area of the screen the thumb reaches naturally; it changes with the device and posture.' },
        { term: 'Hybrid', definition: 'A touch screen laptop that can also be used like a tablet; controls are clustered around the bottom and sides.' },
      ],
      workedExamples: [
        { code: 'Desktop: keyboard + mouse (+ touch) -> Ctrl + C | Edit > Copy | right-click > Copy\nPhone:   small touch screen       -> large thumb-reachable buttons, low bandwidth friendly\nTablet:  sides and top corners\nHybrid:  bottom and sides', explanation: 'The same app adapts its controls to each device while keeping the same theme.' },
      ],
      misconceptions: [
        'The mobile version must have every function of the desktop version. Wrong: it may have fewer functions, but shared elements must look and behave the same.',
        'Every user has a fast connection. Wrong: a site or app must load on both low and high bandwidth connections.',
      ],
      questions: [
        {
          id: 'T7-T10-Q1', type: 'mc', category: 'identify',
          prompt: 'According to the textbook, which areas of a tablet screen can users access easily, no matter their posture?',
          options: [
            'The sides and top corners',
            'Only the exact centre of the screen',
            'Only the bottom left corner',
            'Only the middle of the top edge',
          ],
          answer: 0,
          hint: 'Think about where your hands hold a tablet.',
          explanation: 'The tablet thumb zone changes with posture, but no matter the position, tablet users access the sides and top corners easily.',
          skills: ['T7-S11'],
        },
        {
          id: 'T7-T10-Q2', type: 'tf', category: 'explain',
          prompt: 'True or false: a web site or app only needs to load well on high bandwidth connections.',
          answer: false,
          hint: 'Not everyone has fibre.',
          explanation: 'The web site or app must load on both low and high bandwidth Internet connections, and be designed for all screen sizes.',
          skills: ['T7-S11'],
        },
        {
          id: 'T7-T10-Q3', type: 'tf', category: 'distinguish',
          prompt: 'True or false: a mobile app may have fewer functions than the desktop version, but the elements common to both must behave and appear the same.',
          answer: true,
          hint: 'Consistency also applies across devices.',
          explanation: 'The mobile version should share the desktop theme. It may lack some functions, but common elements must look and behave the same.',
          skills: ['T7-S11', 'T7-S10'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't7-dns-blackout',
    unitId: UNIT.id,
    title: 'Operation DNS Blackout',
    icon: 'globe',
    summary: 'Get Mzansi back online before the routers go dark.',
    briefing: 'A rogue update has scrambled the routers and name servers that link South Africa to the rest of the Internet. Hospitals, banks and the matric results site are unreachable by name. Only someone who understands hosts, IP addresses, connections and URLs can reroute the traffic in time.',
    tickerMessages: [
      'BREAKING: Web sites failing to load across Gauteng.',
      'ISPs report routers sending packets in circles.',
      'Hostnames no longer resolving; only raw IP addresses still work.',
      'Fibre and ADSL users cut off; cellular towers overloaded.',
      'Matric results release in minutes. The country is watching.',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T7-S1', 'T7-S2', 'T7-S3', 'T7-S4', 'T7-S5'],
    victoryMessage: 'Traffic is flowing again. Every hostname resolves and the results site is live. Mzansi salutes you.',
    failMessage: 'The routers stayed tangled and the country stayed offline. Review IP addresses, DNS and connections, then try again.',
  },
  {
    id: 't7-rhino-watch',
    unitId: UNIT.id,
    title: 'Rhino Watch: Search and Protect',
    icon: 'radio',
    summary: 'Find the poachers\' trail online and fix the rangers\' app.',
    briefing: 'Poachers are moving on a game reserve tonight and their plans are buried in millions of web pages. You must build precise AND, OR and NOT searches, prove them with truth tables, and redesign the rangers\' clunky mobile app so they can act with one thumb before sunset.',
    tickerMessages: [
      'Tip-off received: poaching gang active near the reserve.',
      'Search results flooded with false positives. Rangers losing time.',
      'Rangers report the alert app is cluttered and has no feedback.',
      'Sun setting in 30 minutes. Helicopter on standby.',
      'Last chance: one precise search could save the herd.',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T7-S6', 'T7-S7', 'T7-S8', 'T7-S9', 'T7-S10', 'T7-S11'],
    victoryMessage: 'Your searches pinpointed the gang and the rangers\' app guided them straight there. The rhinos are safe.',
    failMessage: 'The search drowned in false positives and the app confused the rangers. Sharpen your Boolean searches and UI design and try again.',
  },
];
