// Exploring IT: Theory Grade 10 (2nd ed), Learning Unit 8: Social and Ethical Issues
import { Scale } from 'lucide-react';

export const UNIT = { id: 'T8', number: 8, name: 'Social and Ethical Issues', worldId: 'social-ethical' };

export const SKILLS = {
  'T8-S1': {
    unit: 'T8',
    name: 'Economic reasons for computers',
    description: 'Explain why computers are faster, more accurate, more reliable and more cost effective than manual methods in business and industry.',
    sections: ['8.1'],
  },
  'T8-S2': {
    unit: 'T8',
    name: 'The digital divide',
    description: 'Define the digital divide, the haves and have nots, digitally enabled citizens and the groups the divide is discussed in.',
    sections: ['8.2'],
  },
  'T8-S3': {
    unit: 'T8',
    name: 'Reasons for the divide',
    description: 'Identify infrastructure, poverty, education and political reasons for the digital divide from a scenario.',
    sections: ['8.2.1', '8.2.1.1', '8.2.1.2', '8.2.1.3', '8.2.1.4'],
  },
  'T8-S4': {
    unit: 'T8',
    name: 'Bridging the divide',
    description: 'Explain why closing the gap needs a combination of solutions and how cell phones help produce digitally enabled citizens.',
    sections: ['8.2.2'],
  },
  'T8-S5': {
    unit: 'T8',
    name: 'Ergonomics',
    description: 'Define ergonomics and apply safe habits such as correct wrist position, frequent screen breaks and regular eye tests.',
    sections: ['8.3', '8.3.2', '8.3.4'],
  },
  'T8-S6': {
    unit: 'T8',
    name: 'Computer-related injuries',
    description: 'Describe the causes, symptoms and treatment of Sore Thumb Syndrome, RSI, Carpal Tunnel Syndrome and eye strain.',
    sections: ['8.3.1', '8.3.2', '8.3.3', '8.3.4'],
  },
  'T8-S7': {
    unit: 'T8',
    name: 'Electrical consumption',
    description: 'Explain how much electricity computer systems use and why computers left on or in sleep mode waste power collectively.',
    sections: ['8.4', '8.4.1'],
  },
  'T8-S8': {
    unit: 'T8',
    name: 'Green disposal and buying',
    description: 'Choose responsible ways to upgrade, recycle and dispose of computer equipment, and green factors to check when buying.',
    sections: ['8.4', '8.4.2'],
  },
};

export const SKILL_HINTS = {
  'T8-S1': 'Economic reasons: computers are quicker, more accurate and more reliable than manual work (if fed accurate data), streamline business, enable globalised business via the Internet, paperless communication, store huge amounts of data with easy retrieval, raise manufacturing productivity by replacing manual labour',
  'T8-S2': 'Digital divide: gap between the haves (regular, effective access to digital and information technology) and have nots; also about skills and resources; groups: socioeconomic rich/poor, racial white/minority, geographical urban/rural; digitally enabled citizens communicate globally with e-Communications',
  'T8-S3': 'Reasons for the divide: infrastructure (undersea fibre cables, fewer cell phone and Internet users in developing countries), poverty (governments cannot fund infrastructure, schools, basics), education (literacy, schooling; Dr Sugata Mitra showed children self-learn with computers), political (civil war, violence)',
  'T8-S4': 'Bridging the divide: not simple, needs political stability, improved infrastructure, reduced poverty and improved education; cell phone use grew faster than computers in Africa, most phones have Internet and social networking, creating digitally enabled citizens',
  'T8-S5': 'Ergonomics: science of designing equipment, furniture and environment to fit the user\'s capabilities and promote safety; wrists should not rest on anything or bend sideways while typing; take frequent screen breaks; have eyes tested regularly',
  'T8-S6': 'Injuries: Sore Thumb Syndrome from tiny repeated texting movements with poor blood circulation; RSI damages tendons, nerves, muscles from repeated keyboard/mouse use; CTS swollen flexor tendons press on the median nerve in the carpal tunnel, treated with splints, anti-inflammatories, cortisone or surgery; eye strain, CRT flicker',
  'T8-S7': 'Electrical consumption: computer systems use 5 to 10 percent of the world\'s electricity; much is wasted by leaving computers on when not in use; one computer in sleep mode uses little, but many together use a great deal',
  'T8-S8': 'Green disposal: recycle and reuse; upgrade components before buying new; recycle at a reliable IT waste disposal centre; non-refillable cartridges to a cartridge store; dispose of batteries responsibly; print less and recycle paper; buy energy-efficient devices from makers with a green manufacturing policy',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Conscience Quarter',
  subtitle: 'Unit 8 \u00b7 Social and Ethical Issues',
  color: 'rose',
  glow: 'ja-glow-rose',
  bg: 'ja-w-social-ethical',
  icon: Scale,
  blurb: 'Computers change lives, bodies and the planet. Bridge the digital divide, protect your wrists and eyes, and keep e-waste out of the dump.',
};

export const LEVELS = [
  {
    id: 't8-l1',
    name: 'The Money and the Gap',
    subtitle: 'Economic reasons for computers and what the digital divide is',
    challengeIds: ['t8-c1', 't8-c2', 't8-c3', 't8-c4', 't8-c5', 't8-c6'],
  },
  {
    id: 't8-l2',
    name: 'Mind the Gap',
    subtitle: 'Reasons for the digital divide and how to bridge it',
    challengeIds: ['t8-c7', 't8-c8', 't8-c9', 't8-c10', 't8-c11', 't8-c12'],
  },
  {
    id: 't8-l3',
    name: 'Body and Planet',
    subtitle: 'Ergonomics, computer injuries and green computing',
    challengeIds: ['t8-c13', 't8-c14', 't8-c15', 't8-c16', 't8-c17', 't8-c18', 't8-c19'],
  },
  {
    id: 't8-l4',
    name: 'The Ethics Summit',
    subtitle: 'Boss level: mixed review of the whole unit and the Check Point',
    challengeIds: ['t8-c20', 't8-c21', 't8-c22', 't8-c23', 't8-c24', 't8-c25'],
  },
];

export const CHALLENGES = {
  't8-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which of these is an economic reason for using a computer instead of doing a task manually?',
    options: [
      'Computers always give correct results, even when wrong data is typed in',
      'Computers do tasks quickly and more accurately than the manual alternative',
      'Computers make business communication depend more on printed paper',
      'Computers remove the need for a business to store any data',
    ],
    answer: 1,
    hint: 'Think about speed and accuracy compared to doing it by hand.',
    explanation: 'The textbook says computers do things quickly and more accurately than doing the task manually, and they are more reliable, provided the user feeds them accurate data.',
    skills: ['T8-S1'],
  },
  't8-c2': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: a computer will produce accurate, reliable results no matter what data the user feeds it.',
    answer: false,
    hint: 'Read the condition the textbook attaches to "accurate and reliable".',
    explanation: 'False. A computer is accurate and more reliable than the manual alternative only provided the user feeds it accurate data.',
    skills: ['T8-S1'],
  },
  't8-c3': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each economic benefit of computers to the example that shows it.',
    pairs: [
      { left: 'Globalised business', right: 'A Durban firm talks to overseas partners effortlessly over the Internet' },
      { left: 'Paperless communication', right: 'Invoices are sent by e-mail instead of being printed and posted' },
      { left: 'Large data storage', right: 'Millions of customer records are stored and retrieved effortlessly' },
      { left: 'Manufacturing productivity', right: 'Computer-controlled machines replace manual labour on a production line' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Look for the key idea in each example: distance, paper, records or factory work.',
    explanation: 'Computers make globalised business possible through Internet communication, make communication almost paperless, store huge amounts of data with effortless retrieval, and raise productivity in manufacturing by replacing manual labour.',
    skills: ['T8-S1'],
  },
  't8-c4': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'What does the term "digital divide" refer to?',
    options: [
      'The gap between fast and slow computers on the same network',
      'The split between the hardware and the software of a computer system',
      'The difference between analogue and digital signals on a cable',
      'The gap between those who have regular, effective access to digital technology and those who do not',
    ],
    answer: 3,
    hint: 'It is about people, not machines: the "haves" and the "have nots".',
    explanation: 'The digital divide is the gap between the haves, who have regular, effective access to digital and information technology, and the have nots, who do not.',
    skills: ['T8-S2'],
  },
  't8-c5': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each digital divide term to its meaning.',
    pairs: [
      { left: 'The haves', right: 'People with regular, effective access to digital and information technology' },
      { left: 'The have nots', right: 'People without regular, effective access to digital technology' },
      { left: 'Digitally enabled citizen', right: 'Has access to technology, communicates globally and has skills to be productive' },
      { left: 'Geographical divide', right: 'The gap between urban and rural areas' },
      { left: 'Socioeconomic divide', right: 'The gap between rich and poor' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Two terms describe people with and without access; two describe groups; one describes a skilled, connected person.',
    explanation: 'The divide separates the haves from the have nots. It is often discussed by socioeconomic (rich/poor), racial and geographical (urban/rural) groups. Digitally enabled citizens have access, communicate globally using e-Communications and have productive skills.',
    skills: ['T8-S2'],
  },
  't8-c6': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: the digital divide is not only about access to computers and the Internet, but also about the skills and resources that enable the technology to be used.',
    answer: true,
    hint: 'Can someone with a computer but no skills really use it?',
    explanation: 'True. The textbook says the divide is clearly about access, but also about the accompanying skills and resources which enable the technology to be used.',
    skills: ['T8-S2'],
  },
  't8-c7': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Classify the main reason for the digital divide in each situation. Type exactly one of: Infrastructure, Poverty, Education, Political',
    code: 'A: No fibre cable or cell towers reach the region\nB: The government has no money to build schools or networks\nC: Most adults in the village cannot read or write\nD: A civil war means leaders cannot focus on technology',
    rows: [
      { label: 'Reason for A', answer: 'Infrastructure' },
      { label: 'Reason for B', answer: 'Poverty' },
      { label: 'Reason for C', answer: 'Education' },
      { label: 'Reason for D', answer: 'Political' },
    ],
    hint: 'Cables and towers, money, literacy, and war each point to a different reason.',
    explanation: 'Missing cables and towers are infrastructure; no government finances is poverty; lack of literacy and schooling is education; civil war and violence are political reasons.',
    skills: ['T8-S3'],
  },
  't8-c8': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'The textbook shows maps of undersea fibre cables linking Africa to other continents in 2013 and 2014. What do the maps show?',
    options: [
      'Infrastructure to Africa has improved in recent years; thicker lines mean higher bandwidth',
      'Africa has no undersea cables connecting it to other continents',
      'Undersea cables carry only electricity, not data, to Africa',
      'Infrastructure to Africa has improved; thinner lines mean higher bandwidth',
    ],
    answer: 0,
    hint: 'More cables means better connections. Which lines carry more?',
    explanation: 'The maps show improved infrastructure to the African continent over recent years, and on the 2014 map the thicker lines are higher in bandwidth.',
    skills: ['T8-S3'],
  },
  't8-c9': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Graphs show that developing countries are far behind in the number of cell phone users and Internet users. What does this imply?',
    options: [
      'People in developing countries do not need online services at all',
      'Developing countries have more Internet users per 100 inhabitants',
      'People lack services others take for granted, like online banking and weather forecasts for farmers',
      'There is no longer a digital divide between developing and developed countries',
    ],
    answer: 2,
    hint: 'Fewer connected users means fewer people can reach online services.',
    explanation: 'Being far behind implies a lack of access to information and services that people in developed countries take for granted, such as online shopping, weather forecasts for farmers, online education and banking.',
    skills: ['T8-S3'],
  },
  't8-c10': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: the textbook says a lack of education is probably one of the easier reasons for the divide to overcome, provided that the technology exists.',
    answer: true,
    hint: 'Remember the experiment showing children can teach themselves with computers.',
    explanation: 'True. Education is described as one of the easier factors to overcome if the technology exists, because Dr Sugata Mitra showed that children can learn by themselves given computers and fast Internet access.',
    skills: ['T8-S3'],
  },
  't8-c11': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'According to the textbook, where does the answer to bridging the digital divide lie?',
    options: [
      'In improved infrastructure alone, because cables solve everything',
      'In banning cell phones so that people use computers instead',
      'In replacing all teachers with textbooks and classrooms',
      'In a combination of political stability, better infrastructure, reduced poverty and better education',
    ],
    answer: 3,
    hint: 'The reasons for the divide come in four kinds. How many must be solved?',
    explanation: 'Closing the gap is not a simple solution. The answer lies in a combination of political stability, improved infrastructure, reduced poverty and improved education.',
    skills: ['T8-S4'],
  },
  't8-c12': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Why have cell phones helped to reduce the digital divide in Africa?',
    options: [
      'Their use has grown faster than computers, and most provide Internet access',
      'They work without any network infrastructure at all',
      'They are cheaper to recycle than desktop computers',
      'They remove the need for people to be literate',
    ],
    answer: 0,
    hint: 'Compare how quickly phones and computers spread, and what phones can connect to.',
    explanation: 'Cell phone use increased in Africa faster than computer use. Most phones provide Internet connectivity and social networking, giving users access to information and services.',
    skills: ['T8-S4'],
  },
  't8-c13': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which is the textbook definition of ergonomics?',
    options: [
      'The study of how fast a computer can process data for its user',
      'The science of making computers use less electricity',
      'The science of designing equipment, furniture and environment to fit the user\'s capabilities and promote safety',
      'The study of the economic reasons for using computers in business',
    ],
    answer: 2,
    hint: 'It is about fitting things to the human body and keeping people safe.',
    explanation: 'Ergonomics is the science which deals with the design of equipment, furniture and environment to fit the user\'s capabilities and to promote user safety.',
    skills: ['T8-S5'],
  },
  't8-c14': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each computer-related condition to its description.',
    pairs: [
      { left: 'Sore Thumb Syndrome', right: 'Hundreds of tiny repeated texting movements that do not make the blood circulate' },
      { left: 'Repetitive Strain Injury (RSI)', right: 'Repeated keyboard or mouse movements damage tendons, nerves and muscles' },
      { left: 'Carpal Tunnel Syndrome (CTS)', right: 'Swollen flexor tendons press on the median nerve in the wrist' },
      { left: 'Eye strain', right: 'Eye problems from long screen time, made worse by CRT screen flicker' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Thumbs, soft tissue in general, a nerve in the wrist, and eyes.',
    explanation: 'Texting can cause Sore Thumb Syndrome; RSI is damage to soft body tissue from repeated movements; CTS involves swollen tendons pressing on the median nerve; eye strain comes from long screen use and CRT flicker.',
    skills: ['T8-S6'],
  },
  't8-c15': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the stages of Carpal Tunnel Syndrome in the order they happen.',
    items: [
      'The swollen tendons apply pressure to the median nerve',
      'Hand and finger movements make the flexor tendons rub against the sides of the tunnel',
      'Tingling, numbness and eventually debilitating pain',
      'The rubbing irritates the tendons, causing them to swell',
    ],
    answer: [1, 3, 0, 2],
    hint: 'Start with movement, end with the symptoms the person feels.',
    explanation: 'Moving the hand makes the flexor tendons rub against the tunnel, the irritated tendons swell, the swelling presses on the median nerve, and the result is tingling, numbness and eventually debilitating pain.',
    skills: ['T8-S6'],
  },
  't8-c16': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: while typing, you should rest your wrists on the desk and bend them to the side for support.',
    answer: false,
    hint: 'Check the textbook advice on wrist position in the RSI section.',
    explanation: 'False. While you are typing your wrists should not rest on anything and should not be bent to the side. Incorrect typing techniques and body positions make RSI more likely.',
    skills: ['T8-S5'],
  },
  't8-c17': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'A school lab leaves its computers in sleep mode every night. Work out the power and energy used. Type whole numbers only.',
    code: 'Computers in the lab:          30\nPower each in sleep mode:      2 W\nHours in sleep mode per night: 10',
    rows: [
      { label: 'Total power for the whole lab (W)', answer: '60' },
      { label: 'Energy used in one night (Wh)', answer: '600' },
      { label: 'Energy used over 5 school nights (Wh)', answer: '3000' },
    ],
    hint: 'Power x number of computers, then power x hours, then x 5 nights.',
    explanation: '30 x 2 W = 60 W; 60 W x 10 h = 600 Wh; 600 Wh x 5 = 3000 Wh. One computer in sleep mode uses very little, but many computers together use a great deal of power.',
    skills: ['T8-S7'],
  },
  't8-c18': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Angelo\'s printer cartridge is empty and cannot be refilled. What should he do with it?',
    options: [
      'Throw it in the household rubbish bin',
      'Take it to a print cartridge store that takes old cartridges, or an IT waste centre',
      'Burn it so that it takes up less space',
      'Bury it in the garden so that it breaks down naturally',
    ],
    answer: 1,
    hint: 'Green disposal means a proper collection point, not the bin.',
    explanation: 'Printer cartridges which cannot be refilled should be disposed of at a print cartridge store that takes in old cartridges, or at an IT waste disposal centre.',
    skills: ['T8-S8'],
  },
  't8-c19': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each item to the green computing action the textbook recommends for it.',
    pairs: [
      { left: 'Printing paper', right: 'Print less and recycle unwanted paper' },
      { left: 'Old batteries', right: 'Dispose of them responsibly at an appropriate disposal centre' },
      { left: 'A slow but working computer', right: 'Upgrade some components to extend its life' },
      { left: 'Broken computer components', right: 'Recycle them at a reliable IT waste disposal centre' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Reduce, upgrade before replacing, and recycle at the right place.',
    explanation: 'The textbook says to reduce printing and recycle paper, dispose of batteries responsibly, upgrade components before buying new, and recycle components at a reliable IT waste disposal centre.',
    skills: ['T8-S8'],
  },
  't8-c20': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: computer systems account for between 5 and 10 percent of the world\'s electricity usage.',
    answer: true,
    hint: 'This is the figure given at the start of the electrical consumption section.',
    explanation: 'True. The textbook states that computer systems account for between 5 and 10 percent of the world\'s electricity usage, and much of it is wasted.',
    skills: ['T8-S7'],
  },
  't8-c21': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which green computing factors should you check when buying a new computer or device?',
    options: [
      'An energy-efficient design and the maker\'s green manufacturing policy',
      'The brightest possible screen and the loudest speakers',
      'The thickest printed manual and the largest box',
      'Whether it can stay switched on permanently without sleeping',
    ],
    answer: 0,
    hint: 'Think about power use and how the company treats waste.',
    explanation: 'When purchasing, check for energy-efficient computers, servers, printers and devices, and check the manufacturer\'s green manufacturing policy and commitment to minimise waste.',
    skills: ['T8-S7', 'T8-S8'],
  },
  't8-c22': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Which social or ethical issue does each situation belong to? Type exactly one of: Economic, Divide, Ergonomics, Green',
    code: 'A: A factory replaces manual labour with computer-controlled machines\nB: A rural learner has no Internet access or computer skills\nC: An office worker gets tingling wrists from bent-wrist typing\nD: A school takes its old monitors to an IT waste disposal centre',
    rows: [
      { label: 'Issue for A', answer: 'Economic' },
      { label: 'Issue for B', answer: 'Divide' },
      { label: 'Issue for C', answer: 'Ergonomics' },
      { label: 'Issue for D', answer: 'Green' },
    ],
    hint: 'Productivity, access, the body, and the environment.',
    explanation: 'Replacing manual labour raises productivity (economic); lacking access and skills is the digital divide; wrist injuries from bad posture are ergonomics; responsible disposal is green computing.',
    skills: ['T8-S1', 'T8-S6', 'T8-S8'],
  },
  't8-c23': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'How can Carpal Tunnel Syndrome be treated, according to the textbook?',
    options: [
      'By typing faster to strengthen the tendons',
      'By resting the wrists on the edge of the desk while typing',
      'By switching from a CRT screen to a flat screen',
      'With splints or braces, anti-inflammatories, cortisone injections or surgery',
    ],
    answer: 3,
    hint: 'The goal of treatment is to reduce swelling and pressure on the median nerve.',
    explanation: 'CTS can be treated with splints or braces, anti-inflammatory medications, cortisone injections or surgery to reduce the swelling and pressure on the median nerve.',
    skills: ['T8-S6'],
  },
  't8-c24': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Angelo\'s eyes feel tired after hours of studying on his laptop. How does the textbook say eye problems can be prevented?',
    options: [
      'Use an old CRT screen, because it refreshes the image continually',
      'Only use the computer late at night when it is dark',
      'Take frequent breaks from the screen and have your eyes tested regularly',
      'Turn the screen brightness to maximum at all times',
    ],
    answer: 2,
    hint: 'Two simple habits: rest your eyes, and get them checked.',
    explanation: 'Eye problems can be prevented by taking frequent breaks from viewing the computer screen and having your eyes tested regularly. The continual refreshing of CRT screens caused flicker that added to eye strain.',
    skills: ['T8-S5', 'T8-S6'],
  },
  't8-c25': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: closing the digital divide is a simple problem that can be solved by improving infrastructure alone.',
    answer: false,
    hint: 'Infrastructure is only one of the four reasons for the divide.',
    explanation: 'False. Closing the gap is not a simple solution; it needs political stability, improved infrastructure, reduced poverty and improved education together.',
    skills: ['T8-S4'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Understand how computers affect the economy, society, our bodies and the environment, and how to use them responsibly.',
  outcomes: [
    'By the end you can list economic reasons for using computers instead of manual methods.',
    'By the end you can define the digital divide, the haves and have nots, and digitally enabled citizens.',
    'By the end you can identify infrastructure, poverty, education and political reasons for the digital divide.',
    'By the end you can explain how the digital divide can be bridged, including the role of cell phones in Africa.',
    'By the end you can define ergonomics and describe a safe way of working with computers and mobile devices.',
    'By the end you can describe Sore Thumb Syndrome, RSI, Carpal Tunnel Syndrome and eye strain, and how to prevent or treat them.',
    'By the end you can explain how computers waste electricity and how to reduce it.',
    'By the end you can describe green disposal, recycling and green factors to consider when buying a device.',
  ],
  topics: [
    {
      id: 'T8-T1',
      title: 'Economic Reasons for Using Computers',
      sections: ['8.1'],
      skills: ['T8-S1'],
      explanation: [
        'A computer does things quickly and more accurately than the alternative of doing the task manually.',
        'Computers are more reliable than the manual alternative, provided that the user feeds the computer accurate data.',
        'Computers streamline operations in businesses and make globalised businesses possible by providing effortless communication using the Internet.',
        'Business communication has become almost completely paperless, which is good for our environment.',
        'Computers allow efficient, accurate and reliable computation of complex calculations, and can store extremely large amounts of data with effortless retrieval, which saves paper.',
        'In manufacturing, computers replace manual labour, so productivity is much greater, more cost effective, more efficient and more reliable.',
      ],
      vocabulary: [
        { term: 'Manual', definition: 'Doing a task by hand without a computer.' },
        { term: 'Globalised business', definition: 'A business that operates across the world, made possible by effortless communication using the Internet.' },
        { term: 'Paperless', definition: 'Communication and record keeping done electronically instead of on paper.' },
        { term: 'Productivity', definition: 'How much is produced; it is greater, more cost effective, efficient and reliable when computers are used in manufacturing.' },
      ],
      workedExamples: [
        {
          code: 'Check Point 1, Question 1:\nList THREE economic reasons for using a computer.\n\n1. Faster and more accurate than doing the task manually\n2. More reliable (if fed accurate data)\n3. Stores huge amounts of data with effortless retrieval',
          explanation: 'Other valid answers: globalised business through Internet communication, paperless communication, and greater manufacturing productivity.',
        },
      ],
      misconceptions: [
        'Thinking a computer is always correct. It is only accurate and reliable if the user feeds it accurate data.',
        'Thinking computers increase paper use. Business communication has become almost completely paperless.',
      ],
      questions: [
        {
          id: 'T8-T1-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'Which list gives THREE economic reasons for using a computer?',
          options: [
            'More printing, larger offices and more filing cabinets',
            'Faster, more accurate and more reliable than doing it manually',
            'More manual labour, slower calculations and less storage',
            'Fewer users, no Internet and more paper records',
          ],
          answer: 1,
          hint: 'Compare a computer with a person doing the same job by hand.',
          explanation: 'Computers are quicker, more accurate and more reliable than manual methods, which saves time and money.',
          skills: ['T8-S1'],
        },
        {
          id: 'T8-T1-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: business communication using computers is good for the environment because it has become almost completely paperless.',
          answer: true,
          hint: 'What do e-mails replace?',
          explanation: 'True. Business communication has become almost completely paperless, which the textbook says is good for our environment.',
          skills: ['T8-S1'],
        },
        {
          id: 'T8-T1-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'A clothing company in Durban wants to sell to customers in Europe. Which economic benefit of computers makes this possible?',
          options: [
            'Computers remove the need for accurate data',
            'Computers increase the amount of paper needed for orders',
            'Computers make globalised business possible through effortless Internet communication',
            'Computers make manual labour more necessary',
          ],
          answer: 2,
          hint: 'The company and its customers are on different continents.',
          explanation: 'Computers make globalised businesses possible by providing effortless communication using the Internet.',
          skills: ['T8-S1'],
        },
      ],
    },
    {
      id: 'T8-T2',
      title: 'The Digital Divide',
      sections: ['8.2'],
      skills: ['T8-S2'],
      explanation: [
        'The digital divide refers to the gap between the "haves" and the "have nots".',
        'The haves are those who have regular, effective access to digital and information technology; the have nots do not.',
        'The divide is clearly about access to computers and the Internet, but it is also about the accompanying skills and resources which enable the technology to be used.',
        'Groups often discussed in the context of a digital divide include socioeconomic (rich/poor), racial (white/minority) and geographical (urban/rural) groups.',
        'Digitally enabled citizens have access to technology and can communicate globally using e-Communications. They have a set of skills they can use to become productive members of society.',
        'Check Point 1, Question 3 asks whether the divide exists in your school or suburb: think about who has regular, effective access and the skills to use it.',
      ],
      vocabulary: [
        { term: 'Digital divide', definition: 'The gap between the haves and the have nots of digital and information technology.' },
        { term: 'Haves', definition: 'Those who have regular, effective access to digital and information technology.' },
        { term: 'Have nots', definition: 'Those who do not have regular, effective access to digital and information technology.' },
        { term: 'Digitally enabled citizen', definition: 'Someone who has access to technology, can communicate globally using e-Communications and has skills to be a productive member of society.' },
      ],
      workedExamples: [
        {
          code: 'Socioeconomic -> rich / poor\nRacial        -> white / minority\nGeographical  -> urban / rural',
          explanation: 'The three groups the textbook lists when the digital divide is discussed.',
        },
      ],
      misconceptions: [
        'Thinking the digital divide is only about owning a device. Skills and resources to use the technology matter too.',
        'Thinking the digital divide only exists between countries. It can exist between groups in the same country, such as urban and rural areas.',
      ],
      questions: [
        {
          id: 'T8-T2-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'In the context of the digital divide, who are the "haves"?',
          options: [
            'Those who have regular, effective access to digital and information technology',
            'Those who own the most expensive smartphones',
            'Those who live in cities, whether or not they have access',
            'Those who build and repair computers for a living',
          ],
          answer: 0,
          hint: 'The key words are "regular" and "effective".',
          explanation: 'The haves are classified as those who have regular, effective access to digital and information technology.',
          skills: ['T8-S2'],
        },
        {
          id: 'T8-T2-Q2',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: anyone who owns a computer is a digitally enabled citizen, even if they cannot use it to communicate.',
          answer: false,
          hint: 'Digitally enabled citizens need access AND skills.',
          explanation: 'False. Digitally enabled citizens have access to technology, can communicate globally using e-Communications and have skills to become productive members of society.',
          skills: ['T8-S2'],
        },
        {
          id: 'T8-T2-Q3',
          type: 'mc',
          category: 'classify',
          prompt: 'Two learners come from families with the same income. One lives in a city with fibre Internet; the other lives in a remote rural area with no network coverage. Which divide group does this show?',
          options: [
            'Socioeconomic (rich/poor)',
            'Racial (white/minority)',
            'Geographical (urban/rural)',
            'Economic reasons for computers',
          ],
          answer: 2,
          hint: 'Income is the same, so what is different?',
          explanation: 'The only difference is where they live, city versus remote countryside, which is the geographical (urban/rural) divide.',
          skills: ['T8-S2'],
        },
      ],
    },
    {
      id: 'T8-T3',
      title: 'Reasons for the Divide',
      sections: ['8.2.1', '8.2.1.1', '8.2.1.2', '8.2.1.3', '8.2.1.4'],
      skills: ['T8-S3'],
      explanation: [
        'Infrastructure: maps of undersea fibre cables in 2013 and 2014 show improved infrastructure to Africa in recent years; thicker lines are higher in bandwidth.',
        'Graphs of Internet users per 100 inhabitants and mobile phone penetration show developing countries far behind. This means a lack of access to services others take for granted, like online shopping, weather forecasts for farmers, online education and banking.',
        'Poverty: many countries are extremely poor, and their governments do not have the finances to provide the infrastructure, schools and basic necessities.',
        'Education: a lack of education, basic literacy and schooling facilities adds to the divide. It is probably one of the easier reasons to overcome if the technology exists.',
        'Dr Sugata Mitra showed that children can learn by themselves given access to computers and fast Internet. Without technology, education relies on teachers, textbooks and classrooms.',
        'Political: many countries are waging civil wars and are torn apart by violence, so they cannot focus on bridging the divide for their people.',
      ],
      vocabulary: [
        { term: 'Infrastructure', definition: 'The physical network needed for connectivity, such as undersea fibre cables and cell networks.' },
        { term: 'Bandwidth', definition: 'The amount of data a connection can carry; on the cable map thicker lines show higher bandwidth.' },
        { term: 'Literacy', definition: 'The basic ability to read and write.' },
        { term: 'Developing country', definition: 'A country that is far behind developed countries in cell phone and Internet users.' },
      ],
      workedExamples: [
        {
          code: 'Check Point 1, Question 2:\nGive THREE reasons for the digital divide.\n\n1. Infrastructure  2. Poverty\n3. Education       4. Political',
          explanation: 'Any three of the four reasons in section 8.2.1 earn the marks.',
        },
      ],
      misconceptions: [
        'Thinking Africa has no undersea cables. The maps show infrastructure to Africa has improved in recent years.',
        'Thinking children can only learn from teachers. Dr Sugata Mitra showed children can learn by themselves with computers and fast Internet.',
      ],
      questions: [
        {
          id: 'T8-T3-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'What did Dr Sugata Mitra prove, according to the textbook?',
          options: [
            'Children can only learn from teachers, textbooks and classrooms',
            'Computers make children less literate',
            'Fast Internet is not needed for children to learn online',
            'Children can learn by themselves given computers and fast Internet access',
          ],
          answer: 3,
          hint: 'His work suggests education is one of the easier reasons to overcome.',
          explanation: 'Dr Sugata Mitra proved that children can learn by themselves given access to computers and fast Internet access.',
          skills: ['T8-S3'],
        },
        {
          id: 'T8-T3-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: poverty adds to the divide because governments do not have the finances to provide infrastructure, schools and basic necessities.',
          answer: true,
          hint: 'Infrastructure and schools cost money.',
          explanation: 'True. Along with a lack of infrastructure, many countries are extremely poor and their governments cannot pay for infrastructure, schools and basic necessities.',
          skills: ['T8-S3'],
        },
        {
          id: 'T8-T3-Q3',
          type: 'trace',
          category: 'classify',
          prompt: 'Classify each cause of the digital divide. Type exactly one of: Infrastructure, Poverty, Education, Political',
          code: 'A: Farmers cannot get online weather forecasts because there is no network\nB: Violence in the country means the government cannot focus on technology\nC: Schools lack facilities and many people lack basic literacy',
          rows: [
            { label: 'Cause of A', answer: 'Infrastructure' },
            { label: 'Cause of B', answer: 'Political' },
            { label: 'Cause of C', answer: 'Education' },
          ],
          hint: 'Network, violence, literacy.',
          explanation: 'No network is an infrastructure problem; violence and civil war are political; a lack of schooling facilities and literacy is an education problem.',
          skills: ['T8-S3'],
        },
      ],
    },
    {
      id: 'T8-T4',
      title: 'Bridging the Divide',
      sections: ['8.2.2'],
      skills: ['T8-S4'],
      explanation: [
        'Closing the gap between those who have access to technology and those who do not is not a simple solution.',
        'The answer lies in a combination of political stability, improved infrastructure, reduced poverty and improved education.',
        'Cell phones have helped to reduce the gap, because their use has increased in Africa faster than the use of computers.',
        'Most phones provide Internet connectivity and are used for social networking, so users are connected and have access to information and other services.',
        'Through mobile service, cell phones can produce more digitally enabled citizens in Africa and other deprived areas.',
      ],
      vocabulary: [
        { term: 'Bridging the divide', definition: 'Closing the gap between those who have access to technology and those who do not.' },
        { term: 'Mobile service', definition: 'Cell phone network service that gives users Internet connectivity and access to information.' },
      ],
      workedExamples: [
        {
          code: 'Reason for divide  -> Fix needed\nPolitical          -> political stability\nInfrastructure     -> improved infrastructure\nPoverty            -> reduced poverty\nEducation          -> improved education',
          explanation: 'Each reason for the divide has a matching fix; the textbook says all four are needed together.',
        },
      ],
      misconceptions: [
        'Thinking one fix, such as laying cables, will close the gap. A combination of all four solutions is needed.',
        'Thinking computers are the main way Africa is getting connected. Cell phone use has grown faster than computer use.',
      ],
      questions: [
        {
          id: 'T8-T4-Q1',
          type: 'mc',
          category: 'predict',
          prompt: 'A new fibre cable reaches a region, but the region is at war and most people cannot read. What will most likely happen to the digital divide there?',
          options: [
            'It will close completely, because the cable has arrived',
            'It will mostly remain, because infrastructure alone is not enough',
            'It will close, because war does not affect technology use',
            'It will close, because literacy is not needed to use the Internet',
          ],
          answer: 1,
          hint: 'Which of the four fixes is still missing?',
          explanation: 'Bridging the divide needs political stability, improved infrastructure, reduced poverty and improved education together, so a cable alone will not close the gap.',
          skills: ['T8-S4'],
        },
        {
          id: 'T8-T4-Q2',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: in Africa, the use of cell phones has increased faster than the use of computers.',
          answer: true,
          hint: 'This is why phones are helping to close the gap.',
          explanation: 'True. Cell phones have helped reduce the gap because their use has increased in Africa faster than the use of computers.',
          skills: ['T8-S4'],
        },
        {
          id: 'T8-T4-Q3',
          type: 'mc',
          category: 'apply',
          prompt: 'Which features of cell phones help to produce more digitally enabled citizens?',
          options: [
            'Internet connectivity and social networking that give access to information',
            'The ability to work without any network infrastructure',
            'Small keyboards that prevent Sore Thumb Syndrome',
            'Built-in printers that produce paper copies of web pages',
          ],
          answer: 0,
          hint: 'Being digitally enabled means being connected and able to communicate.',
          explanation: 'Most phones provide Internet connectivity and social networking, which connect users and give them access to information and other services.',
          skills: ['T8-S4'],
        },
      ],
    },
    {
      id: 'T8-T5',
      title: 'Ergonomics and Text Messaging',
      sections: ['8.3', '8.3.1'],
      skills: ['T8-S5', 'T8-S6'],
      explanation: [
        'Ergonomics is the science which deals with the design of equipment, furniture and environment to fit the user\'s capabilities and to promote user safety.',
        'The textbook includes a picture showing how your computer should be positioned in relation to your body.',
        'Computers can cause physical problems if you use them constantly and incorrectly.',
        'Text messaging has become the most popular way to communicate. Each message involves hundreds of tiny repeated movements on a cell phone keyboard.',
        'Because the movements are small, they do not cause the blood to circulate. The result can be Sore Thumb Syndrome.',
      ],
      vocabulary: [
        { term: 'Ergonomics', definition: 'The science which deals with the design of equipment, furniture and environment to fit the user\'s capabilities and to promote user safety.' },
        { term: 'Sore Thumb Syndrome', definition: 'Pain from the hundreds of tiny repeated movements made when texting, which do not cause the blood to circulate.' },
      ],
      workedExamples: [
        {
          code: 'Check Point 1, Question 4:\nTHREE ways to prepare an ergonomically correct environment:\n1. Equipment and furniture that fit the user\n2. Wrists not resting on anything or bent sideways when typing\n3. Frequent breaks from the screen and regular eye tests',
          explanation: 'These answers come from the ergonomics, RSI and eye strain sections of the textbook.',
        },
      ],
      misconceptions: [
        'Thinking ergonomics is about computer speed. It is about fitting equipment, furniture and environment to the user and keeping the user safe.',
        'Thinking small movements are harmless. The tiny repeated movements of texting do not cause the blood to circulate and can lead to Sore Thumb Syndrome.',
      ],
      questions: [
        {
          id: 'T8-T5-Q1',
          type: 'mc',
          category: 'classify',
          prompt: 'Which of these is an example of applying ergonomics?',
          options: [
            'Buying a faster processor to save time',
            'Choosing a desk and chair designed to fit the user and keep them safe',
            'Switching off computers at night to save electricity',
            'Taking old cartridges to a print cartridge store',
          ],
          answer: 1,
          hint: 'Ergonomics is about the user\'s body and safety.',
          explanation: 'Ergonomics deals with designing equipment, furniture and environment to fit the user\'s capabilities and promote safety. The other options are about speed or green computing.',
          skills: ['T8-S5'],
        },
        {
          id: 'T8-T5-Q2',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps that lead to Sore Thumb Syndrome in order.',
          items: [
            'The small movements do not cause the blood to circulate',
            'You type a text message on a cell phone keyboard',
            'The result can be Sore Thumb Syndrome',
            'Each message involves hundreds of tiny repeated movements',
          ],
          answer: [1, 3, 0, 2],
          hint: 'Start with the action and end with the injury.',
          explanation: 'Texting involves hundreds of tiny repeated movements; because they are small they do not make the blood circulate, which can result in Sore Thumb Syndrome.',
          skills: ['T8-S6'],
        },
        {
          id: 'T8-T5-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: texting uses only tiny movements, so it cannot cause any physical problems.',
          answer: false,
          hint: 'Think about what the small movements fail to do for the blood.',
          explanation: 'False. The tiny repeated movements do not cause the blood to circulate, and the result can be Sore Thumb Syndrome.',
          skills: ['T8-S6'],
        },
      ],
    },
    {
      id: 'T8-T6',
      title: 'RSI, Carpal Tunnel Syndrome and Eye Strain',
      sections: ['8.3.2', '8.3.3', '8.3.4'],
      skills: ['T8-S6', 'T8-S5'],
      explanation: [
        'Repetitive Strain Injuries (RSI) occur from repeated physical movements, like using the keyboard or mouse, which damage tendons, nerves, muscles and other soft body tissues.',
        'RSI symptoms include tightness, discomfort, tingling, coldness, numbness, stiffness, soreness, burning or pain in the hands, wrists, fingers, forearms, elbows, upper back, shoulders or neck.',
        'RSI is more likely with incorrect typing techniques or body positions that stress muscles. While typing, your wrists should not rest on anything and should not be bent to the side.',
        'Carpal Tunnel Syndrome (CTS) involves the median nerve and the flexor tendons that pass from the forearm into the hand through a tunnel made of the wrist bones (carpals) and the transverse carpal ligament.',
        'Moving the hand makes the tendons rub against the tunnel, so they become irritated and swell. The swollen tendons press on the median nerve, causing tingling, numbness and eventually debilitating pain.',
        'CTS can be treated with splints or braces, anti-inflammatory medications, cortisone injections or surgery to reduce the swelling and pressure on the median nerve.',
        'Eye strain is increasing because people spend more time on computers. Prevent it with frequent breaks from the screen and regular eye tests. The flicker of CRT screens also contributed to eye strain.',
      ],
      vocabulary: [
        { term: 'Repetitive Strain Injury (RSI)', definition: 'Damage to tendons, nerves, muscles and other soft body tissues caused by repeated physical movements such as typing or using a mouse.' },
        { term: 'Carpal Tunnel Syndrome (CTS)', definition: 'A painful condition where swollen flexor tendons press on the median nerve in the tunnel formed by the carpals and the transverse carpal ligament.' },
        { term: 'Median nerve', definition: 'The nerve that runs through the carpal tunnel into the hand.' },
        { term: 'Carpals', definition: 'The wrist bones that form part of the carpal tunnel.' },
        { term: 'Eye strain', definition: 'Eye problems caused by spending long periods looking at a computer screen.' },
      ],
      workedExamples: [
        {
          code: 'Check Point 1, Question 5:\nList THREE types of injuries from computing devices.\n\n1. Sore Thumb Syndrome (texting)\n2. Repetitive Strain Injury (RSI)\n3. Carpal Tunnel Syndrome (CTS)\n(also: eye strain)',
          explanation: 'Any three of the four conditions in section 8.3 earn the marks.',
        },
      ],
      misconceptions: [
        'Thinking RSI only affects the hands. Symptoms can appear in the forearms, elbows, upper back, shoulders and neck too.',
        'Thinking you should rest your wrists while typing. The textbook says wrists should not rest on anything or be bent to the side.',
        'Thinking CRT flicker was harmless. The continual refreshing of CRT screens caused flicker that contributed to eye strain.',
      ],
      questions: [
        {
          id: 'T8-T6-Q1',
          type: 'mc',
          category: 'distinguish',
          prompt: 'What is the difference between RSI and Carpal Tunnel Syndrome?',
          options: [
            'RSI affects only the eyes, while CTS affects only the thumbs',
            'CTS is swollen tendons pressing on the median nerve; RSI is wider damage from repeated movements',
            'CTS is caused by CRT flicker, while RSI is caused only by texting',
            'RSI and CTS are the same thing and are both treated with eye tests',
          ],
          answer: 1,
          hint: 'One is a general injury to soft tissues; the other involves one specific nerve.',
          explanation: 'RSI is damage to tendons, nerves, muscles and soft tissue from repeated movements. CTS is a specific condition where swollen flexor tendons press on the median nerve in the carpal tunnel.',
          skills: ['T8-S6'],
        },
        {
          id: 'T8-T6-Q2',
          type: 'mc',
          category: 'identify',
          prompt: 'What forms the "tunnel" in Carpal Tunnel Syndrome?',
          options: [
            'The forearm bones and the elbow joint',
            'The thumb muscles and the median nerve',
            'The flexor tendons and the finger bones',
            'The wrist bones (carpals) and the transverse carpal ligament',
          ],
          answer: 3,
          hint: '"Carpal" refers to the wrist.',
          explanation: 'The tunnel is made up of the wrist bones, or carpals, and the transverse carpal ligament. The median nerve and flexor tendons pass through it.',
          skills: ['T8-S6'],
        },
        {
          id: 'T8-T6-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: the continual refreshing of CRT screens caused a detectable flicker that contributed to eye strain.',
          answer: true,
          hint: 'Older CRT monitors redrew the picture over and over.',
          explanation: 'True. The textbook says the continual refreshing of CRT screens caused detectable flickering that contributed to eye strain.',
          skills: ['T8-S6'],
        },
        {
          id: 'T8-T6-Q4',
          type: 'mc',
          category: 'apply',
          prompt: 'After long gaming sessions with poor posture, Angelo\'s shoulders and neck feel stiff and sore. Which condition best matches these symptoms?',
          options: [
            'Repetitive Strain Injury (RSI)',
            'Carpal Tunnel Syndrome (CTS)',
            'Eye strain',
            'Sore Thumb Syndrome',
          ],
          answer: 0,
          hint: 'Which condition lists the shoulders and neck among its symptoms?',
          explanation: 'RSI symptoms such as stiffness and soreness can appear in the upper back, shoulders and neck. CTS affects the wrist and hand, and Sore Thumb Syndrome affects the thumbs.',
          skills: ['T8-S6', 'T8-S5'],
        },
      ],
    },
    {
      id: 'T8-T7',
      title: 'Green Computing: Electrical Consumption',
      sections: ['8.4', '8.4.1'],
      skills: ['T8-S7'],
      explanation: [
        'Green computing means using computers in a way that is kind to the environment. Its two major areas in the textbook are electrical consumption, and recycling and reusing.',
        'Computer systems account for between 5 and 10 percent of the world\'s electricity usage.',
        'Much of this energy is wasted because many people leave their computers on even when they are not in use.',
        'One computer left in sleep mode uses a very small amount of power, but a large number of computers left in sleep mode use a great deal of power collectively.',
        'Check Point 1, Question 9: switching computers off when not in use is one way to reduce the impact of computers on the environment.',
      ],
      vocabulary: [
        { term: 'Green computing', definition: 'Using computers in an environmentally responsible way, by reducing electrical consumption and by recycling and reusing.' },
        { term: 'Sleep mode', definition: 'A low-power state; one computer uses very little power, but many together use a great deal.' },
      ],
      workedExamples: [
        {
          code: '1 computer in sleep mode:   3 W\n200 computers in sleep mode: 200 x 3 = 600 W\nLeft on for 12 hours:       600 x 12 = 7200 Wh',
          explanation: 'A small amount per computer becomes a large total when many computers are left on.',
        },
      ],
      misconceptions: [
        'Thinking sleep mode uses no power. It uses a very small amount, which adds up across many computers.',
        'Thinking computers use a tiny share of the world\'s electricity. They account for between 5 and 10 percent.',
      ],
      questions: [
        {
          id: 'T8-T7-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Imagine the world uses 1000 units of electricity. Using the textbook\'s range for computer systems, how many units do they use? Type whole numbers only.',
          code: 'World electricity usage: 1000 units\nComputer systems share:  5 to 10 percent',
          rows: [
            { label: 'Lowest estimate (5%)', answer: '50' },
            { label: 'Highest estimate (10%)', answer: '100' },
          ],
          hint: 'Percent means per hundred: multiply 1000 by 5/100 and by 10/100.',
          explanation: '5% of 1000 = 1000 x 5 / 100 = 50 units, and 10% of 1000 = 100 units.',
          skills: ['T8-S7'],
        },
        {
          id: 'T8-T7-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: because one computer in sleep mode uses very little power, leaving many computers in sleep mode never wastes much electricity.',
          answer: false,
          hint: 'Think about the word "collectively".',
          explanation: 'False. One computer in sleep mode uses very little, but a large number of computers in sleep mode use a great deal of power collectively.',
          skills: ['T8-S7'],
        },
        {
          id: 'T8-T7-Q3',
          type: 'mc',
          category: 'explain',
          prompt: 'Why is much of the energy used by computers wasted?',
          options: [
            'Computers must be switched on and off many times a day',
            'Recycling computers uses more electricity than running them',
            'Energy-efficient printers use more power than older printers',
            'Many people leave their computers on even when not in use',
          ],
          answer: 3,
          hint: 'What happens to computers when nobody is using them?',
          explanation: 'Much of the energy is wasted because many people leave their computers on even when they are not in use.',
          skills: ['T8-S7'],
        },
      ],
    },
    {
      id: 'T8-T8',
      title: 'Green Computing: Green Disposal',
      sections: ['8.4.2'],
      skills: ['T8-S8', 'T8-S7'],
      explanation: [
        'The second major area of green computing is recycling and reusing.',
        'Before buying a new computer or device, consider upgrading some of the components to extend the life of the device.',
        'Computer components must be recycled. Locate a reliable IT waste disposal centre in your area and use it for electrical, computer and electronic components.',
        'Printer cartridges that cannot be refilled should go to a print cartridge store that takes old cartridges, or to an IT waste disposal centre. Batteries must be disposed of responsibly at an appropriate disposal centre.',
        'Reduce the amount you print and recycle the unwanted paper you use for printing.',
        'When buying, check for energy-efficient computers, servers, printers and devices, and check the manufacturer\'s green manufacturing policy and commitment to minimise waste.',
        'Check Point 1, Question 7 asks you to find an IT waste disposal centre near you and make a poster to raise awareness of responsible e-waste disposal at your school.',
      ],
      vocabulary: [
        { term: 'Green disposal', definition: 'Recycling and reusing computer equipment responsibly instead of throwing it away.' },
        { term: 'IT waste disposal centre', definition: 'A place that recycles electrical, computer and electronic components.' },
        { term: 'Green manufacturing policy', definition: 'A manufacturer\'s commitment to minimise waste when making computers and devices.' },
      ],
      workedExamples: [
        {
          code: 'Check Point 1, Question 6:\nGreen factors when buying a new device:\n1. Energy-efficient design\n2. Manufacturer\'s green manufacturing policy\n3. Could upgrading the old device be enough?',
          explanation: 'The textbook asks you to check energy efficiency and the maker\'s commitment to minimise waste, and to consider upgrading before buying.',
        },
      ],
      misconceptions: [
        'Thinking an old computer can go in the rubbish bin. Computer components must be recycled at an IT waste disposal centre.',
        'Thinking you must buy a new computer when it gets slow. Upgrading some components can extend its life.',
      ],
      questions: [
        {
          id: 'T8-T8-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'According to the textbook, what is the second major area of green computing?',
          options: [
            'Recycling and reusing',
            'Electrical consumption',
            'Ergonomics',
            'Bridging the digital divide',
          ],
          answer: 0,
          hint: 'The first area is about saving power; the second is about what happens to old equipment.',
          explanation: 'Electrical consumption is the first area of green computing; recycling and reusing is the second major area.',
          skills: ['T8-S8'],
        },
        {
          id: 'T8-T8-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'Why is it important that old computers are not simply thrown away?',
          options: [
            'They can be thrown away safely once the hard drive is wiped',
            'Only the screen needs recycling; the rest can go in the bin',
            'Their parts can be reused or recycled at an IT waste centre instead of being dumped',
            'Rubbish dumps recycle electronic parts automatically',
          ],
          answer: 2,
          hint: 'The textbook says computer components "must" be handled a certain way.',
          explanation: 'Computer components must be recycled at a reliable IT waste disposal centre, and parts can be reused or upgraded to extend a device\'s life, so they should not be dumped.',
          skills: ['T8-S8'],
        },
        {
          id: 'T8-T8-Q3',
          type: 'tf',
          category: 'apply',
          prompt: 'True or false: printing less and recycling unwanted printing paper are ways to reduce the impact of computers on the environment.',
          answer: true,
          hint: 'Green disposal includes paper too.',
          explanation: 'True. The textbook says to try to reduce the amount you print and to recycle the unwanted paper you use for printing.',
          skills: ['T8-S8'],
        },
        {
          id: 'T8-T8-Q4',
          type: 'mc',
          category: 'apply',
          prompt: 'Angelo\'s computer is getting slow. Before buying a new one, what does the textbook suggest he consider?',
          options: [
            'Buying two new computers so that one is a spare',
            'Upgrading some components to extend the life of the computer',
            'Throwing the old computer away to make space',
            'Leaving it on all the time so that it never has to start up',
          ],
          answer: 1,
          hint: 'Reusing is better than replacing.',
          explanation: 'Before buying a new computer or device, consider upgrading some of the components to extend the life of the device.',
          skills: ['T8-S8', 'T8-S7'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 't8-connect-the-village',
    unitId: UNIT.id,
    title: 'Connect the Village',
    icon: 'globe',
    summary: 'Win the budget to bring a rural district online.',
    briefing: 'A remote district in Limpopo has no reliable Internet, and its learners are falling behind. The minister will approve funding at noon only if you can prove you understand why the digital divide exists and how to bridge it. Answer fast, or the budget goes elsewhere.',
    tickerMessages: [
      'Minister arrives early; budget hearing moved forward',
      'Rival bid claims a single cable will fix everything',
      'Farmers report no access to online weather forecasts',
      'Local school confirms learners have no computer skills training',
      'Final vote in minutes: the district waits for your answer',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['T8-S1', 'T8-S2', 'T8-S3', 'T8-S4'],
    victoryMessage: 'Budget approved. Cell towers, training and connected classrooms are on their way, and a new generation of digitally enabled citizens is born.',
    failMessage: 'The funding went to the rival bid. The divide stays open for another year. Review the reasons for the divide and try again.',
  },
  {
    id: 't8-e-waste-emergency',
    unitId: UNIT.id,
    title: 'E-Waste Emergency',
    icon: 'alert',
    summary: 'Save the school lab from injury and illegal dumping.',
    briefing: 'Inspectors arrive in under four minutes. The school storeroom is full of broken computers, dead batteries and empty cartridges about to be dumped, the lab computers have been left on all week, and learners are complaining of sore wrists and tired eyes. Fix the ergonomics and green computing crisis before the inspection fails.',
    tickerMessages: [
      'Caretaker spotted loading old monitors into a skip',
      'Lab computers found in sleep mode all weekend',
      'Three learners report tingling wrists after typing practice',
      'Inspectors pull into the school car park',
      'Final checklist: one wrong answer and the lab is shut',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['T8-S5', 'T8-S6', 'T8-S7', 'T8-S8'],
    victoryMessage: 'Inspection passed. The e-waste is off to an IT waste disposal centre, the lab is powered down at night and every workstation is set up safely.',
    failMessage: 'The inspectors closed the lab. Review ergonomics, injuries and green disposal, then try again.',
  },
];
