// Java Unit 1: Introduction to Java Programming (Exploring IT: Java Programming Grade 10, 3rd ed)
import { Bug } from 'lucide-react';

export const UNIT = { id: 'U1', number: 1, name: 'Introduction to Java Programming', worldId: 'java-intro' };

export const SKILLS = {
  'U1-S1': { unit: 'U1', name: 'Java, classes and the IDE', description: 'Explain what a class is, what the Gogga class is, what an IDE does and which files you need to download.', sections: ['1.1', '1.1.1'] },
  'U1-S2': { unit: 'U1', name: 'Program skeleton', description: 'Write a correct class with a main method, matching file name, comments, curly brackets and semi-colons.', sections: ['1.2', '1.7'] },
  'U1-S3': { unit: 'U1', name: 'Creating Gogga objects', description: 'Import the it package and create a Gogga object with the new operator and the Gogga() constructor.', sections: ['1.2.1', '1.5', '1.7'] },
  'U1-S4': { unit: 'U1', name: 'Fields, methods and dot notation', description: 'Distinguish fields (properties) from methods (behaviours) and call a method on an object with dot notation.', sections: ['1.2.2', '1.7'] },
  'U1-S5': { unit: 'U1', name: 'Moving and turning', description: 'Predict where a Gogga ends up and which way it faces after move(), turnLeft() and turnRight().', sections: ['1.2.2', '1.2.3'] },
  'U1-S6': { unit: 'U1', name: 'Renaming a program', description: 'Rename a program by replacing the class name everywhere and saving it with the matching new file name.', sections: ['1.2.4'] },
  'U1-S7': { unit: 'U1', name: 'Programmer versus end user', description: 'Tell the programmer from the end user and the code window from the output window.', sections: ['1.3'] },
  'U1-S8': { unit: 'U1', name: 'Text output with print and println', description: 'Predict text output from System.out.print and System.out.println, with and without quotes.', sections: ['1.4'] },
  'U1-S9': { unit: 'U1', name: 'Set methods and parameters', description: 'Use setPosition, setDirection, setColor, setTrailWidth, setLabel, trailOn and trailOff with the correct parameters.', sections: ['1.5', '1.7'] },
  'U1-S10': { unit: 'U1', name: 'Syntax and logical errors', description: 'Find and fix syntax (compilation) errors and recognise logical errors.', sections: ['1.6'] },
  'U1-S11': { unit: 'U1', name: 'Compiling and running', description: 'Describe the steps from source code to bytecode to running on the Java Virtual Machine.', sections: ['1.2', '1.8'] },
  'U1-S12': { unit: 'U1', name: 'Gogga grid size', description: 'Change the grid size with the class method Gogga.setGridSize before any Gogga objects are created.', sections: ['1.9'] },
};

export const SKILL_HINTS = {
  'U1-S1': 'A class is a template from which objects can be created; Gogga is a class written by the book authors; an IDE (jGrasp, later NetBeans) gives an editor, syntax-checker and run/test tools; install Java 8 or later, then jGrasp, then copy it.jar to the jGRASP extensions\\classes folder',
  'U1-S2': 'Class names start with a capital letter (MakeSquare), file is MakeSquare.java, main heading is public static void main (String[] args), curly brackets mark blocks, // starts a comment, statements end with ;, Java is case-sensitive',
  'U1-S3': 'import it.*; above the class heading; Gogga bug = new Gogga(); uses the new operator and the Gogga() constructor; default Gogga is red, faces UP, at x = 7, y = 5; any one-word object name is allowed',
  'U1-S4': 'Properties are stored in fields (variables, named locations in RAM); behaviours are methods and always have round brackets; dot notation joins an object to its method: bug.move();',
  'U1-S5': 'move() moves one block in the facing direction; turnLeft() and turnRight() turn 90 degrees without moving; x is the column across, y is the row down, so moving UP makes y smaller and moving RIGHT makes x bigger',
  'U1-S6': 'Class name must equal file name; use Edit Find / Replace with Replace All to change MakeSquare to MakeSquare3Blocks, then File | Save As MakeSquare3Blocks.java',
  'U1-S7': 'The programmer types code in the code window; the end user normally does not understand programming and sees only the output window (the Gogga grid); at this stage programs expect no input',
  'U1-S8': 'System.out.print keeps the next output on the same line, System.out.println moves to the next line; text in double quotes is shown as is, while println(2 + 3) calculates and shows 5',
  'U1-S9': 'setPosition(x, y) moves without a trail and keeps direction; setDirection(Gogga.DOWN); setColor(Color.blue) needs import java.awt.*; and shows on the next move; setTrailWidth(0) means no trail; setLabel("Fred"); trailOn()/trailOff(); values in brackets are parameters',
  'U1-S10': 'Syntax (compilation) errors stop compiling: missing ; or bracket or quote, misspelt moove(), undeclared bugg; logical errors compile and run but give wrong output, e.g. setPosition(8, 22) puts the Gogga off the grid',
  'U1-S11': 'Compile: check syntax, translate MakeSquare.java into bytecode saved as MakeSquare.class; run: the Java Virtual Machine interprets the bytecode for the operating system; execution starts at the first statement of main',
  'U1-S12': 'Gogga.setGridSize(numAcross, numDown) is a class method used with the class name, called before any Gogga is created; setGridSize(25, 20) gives columns 0 to 24 and rows 0 to 19; maximum about (31, 19)',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Gogga Grid Garden',
  subtitle: 'Unit 1 \u00b7 Introduction to Java',
  color: 'teal',
  glow: 'ja-glow-teal',
  bg: 'ja-w-java-intro',
  icon: Bug,
  blurb: 'Write your very first Java program and bring a Gogga to life. Move it, turn it, colour its trail and squash your first bugs.',
};

export const LEVELS = [
  { id: 'u1-l1', name: 'Hello, Gogga', subtitle: 'Classes, the IDE, the program skeleton and your first object', challengeIds: ['u1-c1', 'u1-c2', 'u1-c3', 'u1-c4', 'u1-c5', 'u1-c6'] },
  { id: 'u1-l2', name: 'Move, Turn, Rename', subtitle: 'Methods, moving on the grid, renaming, end users and text output', challengeIds: ['u1-c7', 'u1-c8', 'u1-c9', 'u1-c10', 'u1-c11', 'u1-c12', 'u1-c13'] },
  { id: 'u1-l3', name: 'Set It and Fix It', subtitle: 'Set methods, print versus println and finding errors', hasCoding: true, challengeIds: ['u1-c14', 'u1-c15', 'u1-c16', 'u1-c17', 'u1-c18', 'u1-c19'] },
  { id: 'u1-l4', name: 'Grid Master', subtitle: 'Boss: compiling, class methods, grid size and full programs', hasCoding: true, challengeIds: ['u1-c20', 'u1-c21', 'u1-c22', 'u1-c23', 'u1-c24', 'u1-c25'] },
];

export const CHALLENGES = {
  'u1-c1': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'A Java program consists of one or more classes. What is a class?',
    options: [
      'A template from which objects can be created',
      'A single Gogga object drawn on the grid',
      'A file that stores the translated bytecode',
      'An IDE used for typing in Java instructions',
    ],
    answer: 0,
    hint: 'Think of a cookie cutter and the cookies it makes.',
    explanation: 'A class is a template from which objects can be created, and it is the basic unit in Java for organising code. Gogga is a class; bug is one object made from it.',
    skills: ['U1-S1'],
  },
  'u1-c2': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each item you set up in section 1.1.1 to its purpose.',
    pairs: [
      { left: 'Java platform 8 (or later)', right: 'Installed first, free from the Oracle website' },
      { left: 'jGrasp', right: 'A simple IDE to start coding Java' },
      { left: 'it.jar', right: 'File that holds the Gogga class and other classes' },
      { left: 'jGRASP\\extensions\\classes', right: 'Folder that it.jar must be copied into' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'One is the language itself, one is the editor, one is the Gogga file and one is a place on the C drive.',
    explanation: 'Install Java first, then jGrasp from www.jgrasp.org, then download it.jar from www.funworks.co.za and copy it to the jGRASP extensions\\classes folder so Gogga programs work.',
    skills: ['U1-S1'],
  },
  'u1-c3': {
    type: 'error-spot', world: UNIT.worldId,
    prompt: 'This program will not compile. What is wrong?',
    code: '// Thandi 3 October\nPublic class MakeSquare\n{\n   public static void main (String[] args)\n   {\n      //program instructions go here\n   } // main method\n} // MakeSquare class',
    options: [
      'The comment on the first line must be removed before compiling',
      'The main method heading needs a semi-colon at the end',
      'Java is case-sensitive, so Public must be written as public',
      'The class must create a Gogga object before it can compile',
    ],
    answer: 2,
    hint: 'Look closely at capital letters.',
    explanation: 'Java is case-sensitive: public is not the same as Public or PUBLIC. Comments are ignored, and an empty main method compiles fine; it just does nothing.',
    skills: ['U1-S2'],
  },
  'u1-c4': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: compiling MakeSquare.java converts the instructions into Java bytecode and stores it in a new file called MakeSquare.class.',
    answer: true,
    hint: 'Compiling produces a new file with a different extension.',
    explanation: 'Compiling converts the program in the .java file into Java bytecode and stores it in a new file with the extension .class. Running then carries out the instructions.',
    skills: ['U1-S2', 'U1-S11'],
  },
  'u1-c5': {
    type: 'code-read', world: UNIT.worldId,
    prompt: 'What appears on the Gogga grid when this program is run?',
    code: '// your name and today\'s date\nimport it.*;\npublic class MakeSquare\n{\n    public static void main (String[] args)\n    {\n        Gogga bug = new Gogga();\n    } // main method\n} // MakeSquare class',
    options: [
      'A red Gogga facing right at column 0, row 0',
      'A red Gogga facing up at column 7, row 5',
      'Nothing, because the Gogga has not been told to move',
      'A blue Gogga facing up at column 7, row 5',
    ],
    answer: 1,
    hint: 'A new Gogga gets all the default settings.',
    explanation: 'Gogga bug = new Gogga(); creates the object and displays it at the default position x = 7, y = 5, coloured red and facing UP.',
    skills: ['U1-S3'],
  },
  'u1-c6': {
    type: 'order', world: UNIT.worldId,
    prompt: 'Put the parts of the Activity 2 program in the order they appear, from top to bottom.',
    items: [
      'Gogga bug = new Gogga();',
      'import it.*;',
      '} // main method   } // MakeSquare class',
      '// your name and today\'s date',
      'public static void main (String[] args) {',
      'public class MakeSquare {',
    ],
    answer: [3, 1, 5, 4, 0, 2],
    hint: 'The import goes under the comment but above the class heading; instructions go inside main.',
    explanation: 'The comment comes first, then import it.*; above the class heading. The main method sits inside the class, the instruction sits inside main, and the closing curly brackets end main and then the class.',
    skills: ['U1-S2', 'U1-S3'],
  },
  'u1-c7': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each Java term to its meaning.',
    pairs: [
      { left: 'Field', right: 'Stores a property, such as colour or x-position' },
      { left: 'Method', right: 'A behaviour or action, such as move()' },
      { left: 'Dot notation', right: 'The full stop joining an object to its method' },
      { left: 'Statement', right: 'An instruction that ends with a semi-colon' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'A dog has a colour and can bark. Which is which in Java?',
    explanation: 'Properties are stored in fields and behaviours are methods. In bug.move(); the dot joins the object to the method, and the whole instruction is a statement ending with a semi-colon.',
    skills: ['U1-S4'],
  },
  'u1-c8': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'A new Gogga starts at x = 7, y = 5 facing UP. x is the column across (bigger to the right) and y is the row down (bigger going down), so moving UP makes y smaller. Fill in where bug ends up. For direction type UP, DOWN, LEFT or RIGHT.',
    code: 'Gogga bug = new Gogga();\nbug.move();\nbug.move();\nbug.turnRight();\nbug.move();\nbug.move();\nbug.move();',
    rows: [
      { label: 'Final x', answer: '10' },
      { label: 'Final y', answer: '3' },
      { label: 'Final direction', answer: 'RIGHT' },
    ],
    hint: 'Two moves up first, then a quarter turn, then three moves in the new direction.',
    explanation: 'Two moves UP take bug from (7, 5) to (7, 3). turnRight() turns it 90 degrees to face RIGHT without moving, and three moves take it to (10, 3).',
    skills: ['U1-S5'],
  },
  'u1-c9': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'What does bug.turnLeft(); do?',
    options: [
      'It moves bug one block to the left',
      'It turns bug 180 degrees to face the other way',
      'It moves bug one block left and then faces it up',
      'It turns bug 90 degrees to its left without moving it',
    ],
    answer: 3,
    hint: 'Turning and moving are separate methods.',
    explanation: 'turnLeft() and turnRight() turn a Gogga 90 degrees from the direction it is facing. They do not move the object; they only change its direction.',
    skills: ['U1-S5', 'U1-S4'],
  },
  'u1-c10': {
    type: 'order', world: UNIT.worldId,
    prompt: 'Activity 5: put the steps in order to turn MakeSquare into a new program, MakeSquare3Blocks, that draws a 3-unit square.',
    items: [
      'Select Replace All so the name changes everywhere in the file',
      'Open the original MakeSquare program',
      'Add instructions so bug draws a square of side 3 units, then save',
      'Use Find / Replace: find MakeSquare, replace with MakeSquare3Blocks',
      'Use File | Save As to save it as MakeSquare3Blocks.java',
    ],
    answer: [1, 3, 0, 4, 2],
    hint: 'Change the name in the code before you save under the new name.',
    explanation: 'The class name must match the file name, so you first replace every MakeSquare with MakeSquare3Blocks, then Save As MakeSquare3Blocks.java. The original MakeSquare stays unchanged.',
    skills: ['U1-S6'],
  },
  'u1-c11': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: the end user is the person who types the Java instructions into the code window.',
    answer: false,
    hint: 'Who usually does not understand any programming?',
    explanation: 'The programmer types instructions in the code window. An end user normally does not understand programming; they simply run the program and see the output window.',
    skills: ['U1-S7'],
  },
  'u1-c12': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'When you run MakeSquare, which window shows what the end user sees?',
    options: [
      'The code window, where the instructions are typed',
      'The output window, such as the Gogga grid',
      'The Find / Replace window in the Edit menu',
      'The error message area at the bottom of the editor',
    ],
    answer: 1,
    hint: 'It is where the results of the program appear.',
    explanation: 'The output window displays the results of your program, which is what the end user sees. The code window is the programmer\'s workspace.',
    skills: ['U1-S7'],
  },
  'u1-c13': {
    type: 'code-read', world: UNIT.worldId,
    prompt: 'What does the TextOutput program display? (A | marks a new line.)',
    code: 'public class TextOutput\n{\n   public static void main (String [] args)\n   {\n      System.out.print ("Hello, 2 + 3 = ");\n      System.out.println (2 + 3);\n      System.out.println ("Good Bye");\n   }\n}',
    options: [
      'Hello, 2 + 3 = 2 + 3 | Good Bye',
      'Hello, 2 + 3 = | 5 | Good Bye',
      'Hello, 2 + 3 = 5 | Good Bye',
      'Hello, 2 + 3 = 5 Good Bye',
    ],
    answer: 2,
    hint: 'print stays on the same line; 2 + 3 has no quotes around it.',
    explanation: 'print leaves the cursor on the same line, so the 5 follows "Hello, 2 + 3 = ". Without quotes 2 + 3 is calculated first. println then moves to a new line, so Good Bye is on line 2.',
    skills: ['U1-S8'],
  },
  'u1-c14': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'Exercise 2: predict the output. Type each line exactly as it appears (case-sensitive). If a line is empty, type the word blank.',
    code: 'System.out.print("I am going");\nSystem.out.println(" to the");\nSystem.out.println("shopping mall.");\nSystem.out.println();\nSystem.out.println("There is no bus");\nSystem.out.print("may I have a lift?");',
    rows: [
      { label: 'Line 1', answer: 'I am going to the' },
      { label: 'Line 3', answer: 'blank' },
      { label: 'Line 5', answer: 'may I have a lift?' },
      { label: 'Total number of lines (including blank ones)', answer: '5' },
    ],
    hint: 'print does not end the line, but println does. An empty println() just ends a line.',
    explanation: 'print("I am going") and println(" to the") share line 1. println() with nothing in the brackets produces a blank line 3, and the last print puts its text on line 5.',
    skills: ['U1-S8'],
  },
  'u1-c15': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'Activity 7: trace kreepy. x is the column across and y is the row down. Fill in the numbers.',
    code: 'Gogga kreepy = new Gogga();\nkreepy.setPosition(3,1);\nkreepy.setDirection (Gogga.RIGHT);\nkreepy.setLabel("kreepy");\nkreepy.setTrailWidth (9);\nkreepy.move();\nkreepy.move();\nkreepy.move();\nkreepy.move();\nkreepy.move();\nkreepy.trailOff();\nkreepy.move();\nkreepy.move();\nkreepy.trailOn();\nkreepy.move();',
    rows: [
      { label: 'x after the first five moves', answer: '8' },
      { label: 'x when trailOn() is called', answer: '10' },
      { label: 'Final x', answer: '11' },
      { label: 'Final y', answer: '1' },
      { label: 'Total blocks of trail drawn', answer: '6' },
    ],
    hint: 'setPosition does not change the direction; trailOff only stops the trail, not the moving.',
    explanation: 'kreepy starts at (3, 1) facing RIGHT. Five moves with a trail reach (8, 1), two moves with the trail off reach (10, 1), and one more move with the trail on reaches (11, 1). That is 5 + 1 = 6 blocks of trail.',
    skills: ['U1-S9', 'U1-S5'],
  },
  'u1-c16': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'You add kreepy.setColor (Color.blue); and get an error message. Which statement must you add above the class heading?',
    options: [
      'import it.*;',
      'import Color.blue;',
      'import java.color.*;',
      'import java.awt.*;',
    ],
    answer: 3,
    hint: 'The Color class lives in a Java package, not in the it package.',
    explanation: 'The Color class (American spelling) belongs to the java.awt package, so you add import java.awt.*; above or below import it.*; above the class heading.',
    skills: ['U1-S9'],
  },
  'u1-c17': {
    type: 'error-spot', world: UNIT.worldId,
    prompt: 'Exercise 3: this LetterS program has at least three syntax errors. Which option lists them correctly?',
    code: '// The LetterS class.\npublic class LetterS\n{\n   public static void main (String[] args)\n   {\n      Gogga bug = new Gogga;\n      tick.setTrailWidth (12);\n      tick.setPosition (8, 22);\n      tick.setDirection (Gogga.LEFT);\n      tick.move ();\n      tick.move ();\n      tick.move ();\n      tick.turnLeft ();\n      // ... more moves and turnLeft () calls\n   } // main method\n} // LetterS class',
    options: [
      'import it.*; is missing, new Gogga needs round brackets (), and no object called tick was created',
      'import java.awt.*; is missing, Gogga.LEFT should be just LEFT, and tick.move () has a space before ()',
      'The class name must be lowercase, the comment needs a semi-colon, and main needs a second set of ()',
      'The Gogga starts off the grid at y = 22, it turns left every time, and it draws a square instead of an S',
    ],
    answer: 0,
    hint: 'Syntax errors stop compiling. Errors that only give the wrong picture are a different kind.',
    explanation: 'Gogga needs import it.*;, the constructor call must be new Gogga(), and the object is named bug but used as tick. The off-grid position and the square shape are logical errors, which only show up when the program runs.',
    skills: ['U1-S10', 'U1-S3'],
  },
  'u1-c18': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: a logical error stops a program from compiling.',
    answer: false,
    hint: 'Think of the LetterS program that drew a square instead of an S.',
    explanation: 'Logical errors do not prevent a program from compiling; the program runs but produces unexpected or illogical output. Syntax errors are the ones that stop compiling.',
    skills: ['U1-S10'],
  },
  'u1-c19': {
    type: 'code-write', world: UNIT.worldId,
    prompt: 'Exercise 1: complete the MakeRect program so that a Gogga draws a rectangle with vertical sides 5 blocks long and horizontal sides 2 blocks long, ending where it started and facing the same way.',
    criteria: 'Class must be named MakeRect (matching MakeRect.java) with import it.*; above the class heading and the main method heading public static void main (String[] args). Create exactly one Gogga with Gogga bug = new Gogga(); (any one-word object name is fine) and do not call setPosition or setDirection, so it starts at the default (7, 5) facing UP. Use only move(), turnLeft() and turnRight(). The trail must form a closed rectangle whose vertical sides are 5 moves long and whose horizontal sides are 2 moves long, e.g. 5 moves, turnLeft, 2 moves, turnLeft, 5 moves, turnLeft, 2 moves, turnLeft (turning right every time instead is also correct). The Gogga must finish at (7, 5) facing UP. Every statement ends with a semi-colon and every method call has round brackets. No loops are needed.',
    starter: '// your name and today\'s date\nimport it.*;\n\npublic class MakeRect\n{\n   public static void main (String[] args)\n   {\n      // your code here\n   } // main method\n} // MakeRect class',
    skills: ['U1-S5', 'U1-S6', 'U1-S2'],
    explanation: 'From (7, 5) facing UP, five moves reach row 0, two moves cross the top, five moves come down and two moves return to (7, 5). A final turn makes it face UP again, just like the 2-unit square in Activity 4.',
  },
  'u1-c20': {
    type: 'order', world: UNIT.worldId,
    prompt: 'Put the steps that happen when you compile and run MakeSquare.java in the correct order.',
    items: [
      'The .class bytecode file is interpreted by the Java Virtual Machine for the operating system',
      'The statements in MakeSquare.java are checked for syntax errors',
      'Output is displayed as statements run, from the first statement in main onwards',
      'The program is translated into Java bytecode and saved as MakeSquare.class',
    ],
    answer: [1, 3, 0, 2],
    hint: 'A program cannot be translated while it still has syntax errors.',
    explanation: 'First the source code is checked for syntax errors, then it is translated into bytecode in MakeSquare.class. The Java Virtual Machine interprets that bytecode so it can run on the operating system, and output appears as each statement in main is carried out.',
    skills: ['U1-S11'],
  },
  'u1-c21': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Which grid is produced by Gogga.setGridSize (25, 20); ?',
    options: [
      'Columns 1 to 25 and rows 1 to 20',
      'Columns 0 to 20 and rows 0 to 25',
      'Columns 0 to 24 and rows 0 to 19',
      'Columns 0 to 25 and rows 0 to 20',
    ],
    answer: 2,
    hint: 'The first number is across, and numbering starts at 0.',
    explanation: 'setGridSize (numAcross, numDown) takes the number across first. Numbering starts at 0, so 25 across gives columns 0 to 24 and 20 down gives rows 0 to 19.',
    skills: ['U1-S12'],
  },
  'u1-c22': {
    type: 'error-spot', world: UNIT.worldId,
    prompt: 'According to the textbook, what is wrong with how this Cross program sets the grid size?',
    code: 'import it.*;\npublic class Cross\n{\n   public static void main (String[] args)\n   {\n      Gogga fred = new Gogga ();\n      fred.setGridSize (20, 10);\n   }\n}',
    options: [
      'setGridSize needs three parameters: across, down and a colour',
      'It is a class method: write Gogga.setGridSize (20, 10); before fred is created',
      'The grid cannot be larger than 15 across, so (20, 10) is too big',
      'The object must be called bug because the Gogga class expects it',
    ],
    answer: 1,
    hint: 'The grid must exist before any Gogga can be placed on it.',
    explanation: 'setGridSize() is a class method, so it is used with the class name Gogga, not an object. The grid is independent of the Goggas on it and must be set up before any Gogga objects are created.',
    skills: ['U1-S12', 'U1-S4'],
  },
  'u1-c23': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each part of the ColouredLines program to what it is.',
    pairs: [
      { left: 'Gogga ()', right: 'Constructor method that gives a new object its default field values' },
      { left: 'Color.black', right: 'Class value of the Color class' },
      { left: 'Gogga.RIGHT', right: 'Class value of the Gogga class used as a direction' },
      { left: '(2, 1) in louse.setPosition (2, 1)', right: 'Parameters: the column across, then the row down' },
      { left: 'new', right: 'Operator used with a constructor to create an object' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Class values are used with the class name and a dot, not with an object name.',
    explanation: 'An object is created with the new operator and the Gogga() constructor. Color.black and Gogga.RIGHT are class values used with their class name, and the values in a method\'s brackets are its parameters.',
    skills: ['U1-S9', 'U1-S3'],
  },
  'u1-c24': {
    type: 'code-write', world: UNIT.worldId,
    prompt: 'Check Point 2: extend ColouredLines so that louse draws three parallel lines, each 10 units long: black on row 1, blue on row 3 and a new yellow line on row 5.',
    criteria: 'Class ColouredLines with import it.*; and import java.awt.*; above the class heading. Create one Gogga object called louse with Gogga louse = new Gogga (); and use only that object. Line 1: louse.setPosition (2, 1); louse.setDirection (Gogga.RIGHT); louse.setColor (Color.black); then exactly 10 louse.move (); calls, ending at (12, 1). Line 2: setPosition (2, 3), direction Gogga.RIGHT, setColor (Color.blue), 10 moves. Line 3: setPosition (2, 5), direction Gogga.RIGHT, setColor (Color.yellow), 10 moves. Each setColor call must come before the moves it colours. Directions must be prefixed with Gogga and colours with Color. No loops are needed; a long list of move() statements is expected at this stage.',
    starter: '// The ColouredLines class.\n// Your name & today\'s date\nimport it.*;\nimport java.awt.*;\n\npublic class ColouredLines\n{\n    public static void main (String[] args)\n    {\n        Gogga louse = new Gogga ();\n        // your code here\n    } //end of main method\n} // end of ColouredLines class',
    skills: ['U1-S9', 'U1-S3', 'U1-S2'],
    explanation: 'setPosition jumps louse to a new start without drawing a trail, setDirection points it RIGHT, and setColor changes the trail colour that shows on the next move. Rows 1, 3 and 5 keep the lines parallel and two rows apart.',
  },
  'u1-c25': {
    type: 'code-write', world: UNIT.worldId,
    prompt: 'Activity 9: write the Cross program. Use a grid 20 across and 10 down and make a Gogga called fred draw a plus-shaped cross.',
    criteria: 'Class Cross with import it.*; above the class heading. The FIRST statement in main must be Gogga.setGridSize (20, 10); (class name Gogga, not an object), followed by Gogga fred = new Gogga ();. Draw the vertical bar from (10, 1) down to (10, 7): fred.setPosition (10, 1); fred.setDirection (Gogga.DOWN); then 6 moves. Draw the horizontal bar from (7, 4) to (13, 4): fred.setPosition (7, 4); fred.setDirection (Gogga.RIGHT); then 6 moves. The bars cross at (10, 4). Drawing the bars in the other order, or each bar in the opposite direction (e.g. UP from (10, 7), LEFT from (13, 4)), is also correct. Optional extras such as setColor (with import java.awt.*;), setTrailWidth or setLabel("fred") are fine. No loops are needed.',
    starter: '// your name and today\'s date\nimport it.*;\n\npublic class Cross\n{\n   public static void main (String[] args)\n   {\n      // your code here\n   } // main method\n} // Cross class',
    skills: ['U1-S12', 'U1-S9', 'U1-S5'],
    explanation: 'The grid must be set up before fred exists, so Gogga.setGridSize comes first. setPosition moves fred to the start of each bar without leaving a trail, so the two bars are not joined by a stray line.',
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Get set up with Java and an IDE, write your first programs using Gogga objects and text output, fix errors and understand what happens when a program runs.',
  outcomes: [
    'By the end you can explain what a class, an object and an IDE are, and set up Java, jGrasp and it.jar.',
    'By the end you can write a Java program skeleton with a correctly named class, a main method and comments.',
    'By the end you can create a Gogga object and describe its default colour, direction and position.',
    'By the end you can use move(), turnLeft() and turnRight() and predict where a Gogga ends up.',
    'By the end you can use the set methods and trail methods of the Gogga class with the correct parameters.',
    'By the end you can rename a program and tell the programmer and code window from the end user and output window.',
    'By the end you can predict text output from System.out.print and System.out.println.',
    'By the end you can tell syntax (compilation) errors from logical errors and fix them.',
    'By the end you can describe compiling to bytecode and running on the Java Virtual Machine.',
    'By the end you can change the size of the Gogga grid with Gogga.setGridSize.',
  ],
  topics: [
    {
      id: 'U1-T1',
      title: 'Getting started with Java',
      sections: ['1.1', '1.1.1'],
      skills: ['U1-S1'],
      explanation: [
        'There are many programming languages and they are all used to solve problems. The process of problem solving is the same in any language; Java is a language that uses objects.',
        'A Java program consists of one or more classes. A class is a template from which objects can be created, and it is the basic unit in Java for organising code.',
        'Gogga (a Khoisan word for a bug or any creepy crawly insect) is a class written by some of the book\'s authors. Gogga objects move in a window with horizontal and vertical lines 25 pixels apart, forming a grid. You will also use many classes that come with Java.',
        'Java programs are often created in an Integrated Development Environment (IDE): a program with an editor for typing Java code, a syntax-checker that detects grammatical or punctuation errors, and tools to run and test programs. The book starts with jGrasp and later moves to NetBeans for programs with a Graphical User Interface (GUI).',
        'Set-up steps: install the free Java platform 8 (or later) from Oracle, then install jGrasp from www.jgrasp.org, then download it.jar (the Gogga class and other classes) from www.funworks.co.za and copy it to C:\\Program Files (x86)\\jGRASP\\extensions\\classes.',
      ],
      vocabulary: [
        { term: 'Class', definition: 'A template from which objects can be created; the basic unit in Java for organising code.' },
        { term: 'Gogga', definition: 'A class of objects, written by the authors, that move on a grid of lines 25 pixels apart.' },
        { term: 'IDE', definition: 'Integrated Development Environment: a program with tools such as an editor and a syntax-checker that also lets you run and test programs.' },
        { term: 'it.jar', definition: 'The downloaded file that contains the Gogga class and other classes.' },
      ],
      workedExamples: [
        { code: 'C:\\Program Files (x86)\\jGRASP\\extensions\\classes', explanation: 'The folder where it.jar must be copied so that jGrasp can find the Gogga class.' },
      ],
      misconceptions: [
        'Thinking you must pay for Java. Java is free and can be downloaded without any cost.',
        'Thinking you write every class yourself. Most programs use classes written by other programmers, such as Gogga or the classes that come with Java.',
      ],
      questions: [
        {
          id: 'U1-T1-Q1', type: 'mc', category: 'define',
          prompt: 'Which description of an IDE matches the textbook?',
          options: [
            'A file that stores Java bytecode for the operating system',
            'A class that creates Gogga objects on a grid',
            'A website where you download the it.jar file',
            'A program with an editor and syntax-checker that lets you run and test programs',
          ],
          answer: 3,
          hint: 'jGrasp and NetBeans are examples.',
          explanation: 'An Integrated Development Environment provides tools such as an editor and a syntax-checker, and lets programs be run and tested from within it.',
          skills: ['U1-S1'],
        },
        {
          id: 'U1-T1-Q2', type: 'tf', category: 'identify',
          prompt: 'True or false: the IDE used to start coding in this unit is NetBeans.',
          answer: false,
          hint: 'NetBeans comes later, for GUI programs.',
          explanation: 'The book starts with jGrasp, a simple IDE for learning Java. NetBeans is used later to code programs with graphical user interfaces.',
          skills: ['U1-S1'],
        },
        {
          id: 'U1-T1-Q3', type: 'mc', category: 'identify',
          prompt: 'What is inside the it.jar file?',
          options: [
            'The Gogga class and other classes',
            'The Java platform 8 installer',
            'The jGrasp editor and syntax-checker',
            'The bytecode of your MakeSquare program',
          ],
          answer: 0,
          hint: 'You need it for your bug to appear.',
          explanation: 'The it.jar file consists of the Gogga class and other classes. Java and jGrasp are installed separately.',
          skills: ['U1-S1'],
        },
      ],
    },
    {
      id: 'U1-T2',
      title: 'Coding your first program',
      sections: ['1.2'],
      skills: ['U1-S2', 'U1-S11'],
      explanation: [
        'A Java application is a stand-alone application designed to run on a computer or laptop. Activity 1 creates the MakeSquare class, an outline program that runs but does nothing.',
        'Java is case-sensitive: public is not the same as PUBLIC or Public. Every class name starts with a capital letter; if it has more than one word there are no spaces and each new word starts with a capital, as in MakeSquare.',
        'The body of a class is enclosed in curly brackets. A program that can be run must have a main method with the heading public static void main (String[] args); the instructions go inside its curly brackets, and main sits completely inside the class.',
        'Every opening curly bracket needs a matching closing bracket. Indent code inside the brackets, and leave blank lines between sections to make the program easier to read. Code preceded by // is a comment, ignored when the program runs, and used to explain the code.',
        'The file must be saved with the same name as the class: MakeSquare.java. Compiling converts the instructions into Java bytecode stored in a new file with the extension .class; running carries out the instructions.',
      ],
      vocabulary: [
        { term: 'Java application', definition: 'A stand-alone application designed to run on a computer or laptop.' },
        { term: 'Case-sensitive', definition: 'It makes a difference whether a letter is uppercase or lowercase.' },
        { term: 'main method', definition: 'The starting section of a Java program, with the heading public static void main (String[] args).' },
        { term: 'Comment', definition: 'Code preceded by // that is ignored when the program runs and explains the code.' },
        { term: 'Compiling', definition: 'Converting the .java program instructions into Java bytecode stored in a .class file.' },
      ],
      workedExamples: [
        { code: '// Your name Today\'s date\npublic class MakeSquare\n{\n   public static void main (String[] args)\n   {\n      //program instructions go here\n   } // main method\n} // MakeSquare class', explanation: 'The skeleton from Activity 1. Saved as MakeSquare.java, it compiles and runs but does nothing yet.' },
      ],
      misconceptions: [
        'Thinking the file name can be anything. Java wants the file name to be the same as the class name, followed by .java.',
        'Thinking comments are shown to the user. Comments are ignored when the program runs; they explain the code to people reading it.',
      ],
      questions: [
        {
          id: 'U1-T2-Q1', type: 'mc', category: 'identify',
          prompt: 'Which is the correct heading for the main method?',
          options: [
            'public static void main (String() args)',
            'Public Static Void Main [String[] args]',
            'public static void main (String[] args)',
            'public static void main {String[] args}',
          ],
          answer: 2,
          hint: 'Note the square and the round brackets, and the lowercase letters.',
          explanation: 'The main method always has the heading public static void main (String[] args): lowercase keywords, round brackets around String[] args, and square brackets after String.',
          skills: ['U1-S2'],
        },
        {
          id: 'U1-T2-Q2', type: 'tf', category: 'explain',
          prompt: 'True or false: Java treats public, Public and PUBLIC as the same word.',
          answer: false,
          hint: 'What does case-sensitive mean?',
          explanation: 'Java is case-sensitive, so a change from lowercase to uppercase makes a different word. Only public is correct.',
          skills: ['U1-S2'],
        },
        {
          id: 'U1-T2-Q3', type: 'order', category: 'sequence',
          prompt: 'Put the steps of Activity 1 in order.',
          items: [
            'Use the menus to compile and run the program',
            'Type in the code for the MakeSquare class',
            'Save the program as MakeSquare.java',
            'Change the first comment line to show your name and today\'s date',
          ],
          answer: [1, 3, 2, 0],
          hint: 'You cannot compile a file that has not been saved.',
          explanation: 'Type the code, update the comment, save it as MakeSquare.java (matching the class name), then compile and run it.',
          skills: ['U1-S2', 'U1-S11'],
        },
      ],
    },
    {
      id: 'U1-T3',
      title: 'Creating a Gogga object',
      sections: ['1.2.1'],
      skills: ['U1-S3'],
      explanation: [
        'Java programs use objects that have properties. Gogga objects have characteristics (properties) such as colour and direction, and actions (behaviours) such as moving along the grid lines. They draw shapes by leaving a trail.',
        'Gogga objects live in an output window called the Gogga Grid. The grid can be saved and printed, and the speed of the movements can be changed.',
        'A new Gogga is red, faces UP and sits at the intersection of column 7 and row 5, which is x = 7 and y = 5. These are the defaults if no other values are given.',
        'Put import it.*; under your name comment and above the class heading. The it (eye-tee) package contains the Gogga class, and the * makes all classes in the package available.',
        'Gogga bug = new Gogga(); creates an object of the Gogga class named bug, gives it all its characteristics and shows it on the grid. The object can have any one-word name, such as flea, fred, x or item.',
      ],
      vocabulary: [
        { term: 'Object', definition: 'Something created from a class that has properties and behaviours, such as the Gogga bug.' },
        { term: 'Gogga Grid', definition: 'The output window in which Gogga objects exist and move.' },
        { term: 'it package', definition: 'The package that contains the Gogga class and related classes, imported with import it.*;' },
      ],
      workedExamples: [
        { code: '// your name and today\'s date\nimport it.*;\npublic class MakeSquare\n{\n    public static void main (String[] args)\n    {\n        Gogga bug = new Gogga();\n    } // main method\n} // MakeSquare class', explanation: 'Activity 2: the import goes above the class heading and the object is created inside main. A red Gogga appears facing up at (7, 5).' },
      ],
      misconceptions: [
        'Thinking a Gogga can only be named bug. Any one-word name works, such as flea, fred, x or item, and it need not be an insect.',
        'Thinking import it.*; goes inside main. It goes at the beginning of the program, above the class heading.',
      ],
      questions: [
        {
          id: 'U1-T3-Q1', type: 'trace', category: 'identify',
          prompt: 'Gogga bug = new Gogga(); has just run. Fill in the default field values. Type the direction as UP, DOWN, LEFT or RIGHT and the colour in lowercase.',
          code: 'Gogga bug = new Gogga();',
          rows: [
            { label: 'x', answer: '7' },
            { label: 'y', answer: '5' },
            { label: 'Direction', answer: 'UP' },
            { label: 'Colour', answer: 'red' },
          ],
          hint: 'Picture the bug as it first appears near the middle of the grid.',
          explanation: 'The constructor gives a new Gogga the defaults: red, facing UP, at column 7 and row 5.',
          skills: ['U1-S3'],
        },
        {
          id: 'U1-T3-Q2', type: 'mc', category: 'explain',
          prompt: 'What is the purpose of import it.*; and why is the * used?',
          options: [
            'It creates a Gogga object; the * multiplies its speed',
            'It makes classes in the it package available; * means all of them',
            'It imports colours for the trail; * means every colour',
            'It saves the program as it.java; * stands for the class name',
          ],
          answer: 1,
          hint: 'Gogga is one of several classes in a package.',
          explanation: 'The it package contains the Gogga class and related classes. Importing it lets you create Gogga objects, and the * makes all classes in the package available.',
          skills: ['U1-S3'],
        },
        {
          id: 'U1-T3-Q3', type: 'tf', category: 'apply',
          prompt: 'True or false: a Gogga object can only be given the name of an insect, such as bug or flea.',
          answer: false,
          hint: 'The book lists x and item as example names.',
          explanation: 'A Gogga object can be given any one-word name, such as flea, fred, x or item.',
          skills: ['U1-S3'],
        },
      ],
    },
    {
      id: 'U1-T4',
      title: 'Fields, methods and moving the Gogga',
      sections: ['1.2.2', '1.2.3'],
      skills: ['U1-S4', 'U1-S5'],
      explanation: [
        'Objects have properties and behaviours, like a real dog that has a colour and can bark. In Java, properties are stored in fields and behaviours (actions) are called methods.',
        'Fields are also called variables, which are named locations in memory (RAM). A Gogga has fields for its x-position, its y-position and its colour (red by default).',
        'Method names are always followed by round brackets. move() makes a Gogga move one unit (one block) in the direction it is facing.',
        'In bug.move(); the dot (full stop) joins the method to the object that carries it out. This is called dot notation. The whole line is a statement, an instruction telling the computer what to do, and every Java statement ends with a semi-colon.',
        'turnLeft() and turnRight() turn a Gogga 90 degrees left or right from the direction it faces. They do not move it; they only change its direction. x is the column across and y is the row down, so moving UP makes y smaller.',
        'Activity 4 draws a square of side 2 by repeating two moves and a turnLeft() four times, ending where it started. The repetition hints that a loop is needed, which comes later in the book.',
      ],
      vocabulary: [
        { term: 'Field', definition: 'Where a property of an object is stored; also called a variable, a named location in memory (RAM).' },
        { term: 'Method', definition: 'A behaviour or action an object can carry out; its name is followed by round brackets.' },
        { term: 'Dot notation', definition: 'Using a dot to join a method to the object that carries it out, as in bug.move();' },
        { term: 'Statement', definition: 'An instruction telling the computer what to do; all Java statements end with a semi-colon.' },
      ],
      workedExamples: [
        { code: 'Gogga bug = new Gogga ();\n\nbug.move ();\nbug.move ();\nbug.turnLeft ();\nbug.move ();\nbug.move ();\nbug.turnLeft ();\nbug.move ();\nbug.move ();\nbug.turnLeft ();\nbug.move ();\nbug.move ();\nbug.turnLeft ();', explanation: 'Activity 4: from (7, 5) the bug visits (7, 3), (5, 3), (5, 5) and back to (7, 5), drawing a square of side 2 and ending up facing UP again.' },
      ],
      misconceptions: [
        'Thinking turnLeft() moves the Gogga to the left. It only turns it 90 degrees; you need move() to change position.',
        'Thinking a method can be written without brackets, as in bug.move. Method names are always followed by round brackets.',
      ],
      questions: [
        {
          id: 'U1-T4-Q1', type: 'mc', category: 'define',
          prompt: 'According to the textbook, what are fields also called?',
          options: [
            'Methods, which are actions the object carries out',
            'Parameters, which are values in round brackets',
            'Statements, which end with a semi-colon',
            'Variables, which are named locations in memory (RAM)',
          ],
          answer: 3,
          hint: 'They store values such as x-position and colour.',
          explanation: 'Fields store an object\'s properties and are also called variables, named locations in memory (RAM).',
          skills: ['U1-S4'],
        },
        {
          id: 'U1-T4-Q2', type: 'trace', category: 'predict',
          prompt: 'Trace the Activity 4 square. bug starts at x = 7, y = 5 facing UP; moving UP makes y smaller and moving LEFT makes x smaller. Type directions as UP, DOWN, LEFT or RIGHT.',
          code: 'Gogga bug = new Gogga ();\nbug.move ();\nbug.move ();\nbug.turnLeft ();\nbug.move ();\nbug.move ();\nbug.turnLeft ();\nbug.move ();\nbug.move ();\nbug.turnLeft ();\nbug.move ();\nbug.move ();\nbug.turnLeft ();',
          rows: [
            { label: 'y after the first two moves', answer: '3' },
            { label: 'x after the second side is drawn', answer: '5' },
            { label: 'Direction after the second turnLeft ()', answer: 'DOWN' },
            { label: 'Final direction', answer: 'UP' },
          ],
          hint: 'Turning left from UP gives LEFT, then DOWN, then RIGHT, then UP.',
          explanation: 'Two moves up reach (7, 3); facing LEFT, two moves reach (5, 3); facing DOWN, two moves reach (5, 5); facing RIGHT, two moves return to (7, 5); the fourth turn faces UP.',
          skills: ['U1-S5'],
        },
        {
          id: 'U1-T4-Q3', type: 'tf', category: 'explain',
          prompt: 'True or false: turnLeft() and turnRight() change the direction of a Gogga but do not move it.',
          answer: true,
          hint: 'Which method actually changes the position?',
          explanation: 'The turn methods turn the Gogga 90 degrees and only change its direction. Only move() changes its position.',
          skills: ['U1-S5', 'U1-S4'],
        },
      ],
    },
    {
      id: 'U1-T5',
      title: 'Renaming a program, programmer and end user',
      sections: ['1.2.4', '1.3'],
      skills: ['U1-S6', 'U1-S7'],
      explanation: [
        'To change a program but keep the original, give it a new name. In Java the class name must be the same as the file name, so both must change.',
        'Activity 5: use Edit, Find / Replace to find MakeSquare and replace it with MakeSquare3Blocks, select Replace All, check the code, then use File | Save As to save MakeSquare3Blocks.java. Then add instructions so it draws a square of side 3.',
        'Exercise 1 renames MakeSquare to MakeRect (a rectangle with vertical sides of 5 blocks and horizontal sides of 2) and creates a new class Bumps, where a Gogga called flea draws a picture and ends at (11, 5) facing up.',
        'When you type instructions in the editor you are the programmer, working in the code window. An end user normally does not understand programming and just uses the program.',
        'The window that shows the Gogga grid, where the results appear, is the output window: it displays what the end user sees. For now you are both programmer and end user, and your programs expect no input; later end users will input data that programs process to give output.',
      ],
      vocabulary: [
        { term: 'Programmer', definition: 'The person who codes programs, typing instructions in the code window, for end users to use.' },
        { term: 'End user', definition: 'Somebody who normally does not understand programming and simply uses a program.' },
        { term: 'Code window', definition: 'The window where the programmer types the Java instructions.' },
        { term: 'Output window', definition: 'The window that displays the results of the program, which is what the end user sees.' },
      ],
      workedExamples: [
        { code: 'Find:    MakeSquare\nReplace: MakeSquare3Blocks\n[Replace All]\nFile | Save As  ->  MakeSquare3Blocks.java', explanation: 'Renaming keeps the original MakeSquare.java and creates a new program whose class and file names match.' },
      ],
      misconceptions: [
        'Thinking that saving under a new file name is enough. The class name inside the code must also be changed to match the new file name.',
        'Thinking the code window and the output window are the same thing. One is for writing instructions, the other shows the results.',
      ],
      questions: [
        {
          id: 'U1-T5-Q1', type: 'mc', category: 'explain',
          prompt: 'Why must you change every occurrence of MakeSquare when you rename the program?',
          options: [
            'The class name must be the same as the file name it is saved with',
            'Java will delete the original MakeSquare.java otherwise',
            'Comments that mention MakeSquare stop the program compiling',
            'The Gogga object must have the same name as the class',
          ],
          answer: 0,
          hint: 'What two names must always match in Java?',
          explanation: 'In Java the name of the class must be the same as the file name with which the class is saved, so the class name and the file name change together.',
          skills: ['U1-S6'],
        },
        {
          id: 'U1-T5-Q2', type: 'tf', category: 'define',
          prompt: 'True or false: the output window displays what the end user sees.',
          answer: true,
          hint: 'The Gogga grid is an example.',
          explanation: 'The output window shows the output or results of the program, which is what the end user sees.',
          skills: ['U1-S7'],
        },
        {
          id: 'U1-T5-Q3', type: 'mc', category: 'distinguish',
          prompt: 'Which statement about your programs at this beginning stage is correct?',
          options: [
            'End users type data into your Gogga programs while they run',
            'Only end users may run a program, never the programmer',
            'They expect no input, and you act as both programmer and end user',
            'The code window shows exactly what the end user sees',
          ],
          answer: 2,
          hint: 'Who writes and who runs your programs right now?',
          explanation: 'At this stage you create the programs and are the only one running them, and the programs expect no input. Input from end users comes later.',
          skills: ['U1-S7'],
        },
      ],
    },
    {
      id: 'U1-T6',
      title: 'Different forms of output',
      sections: ['1.4'],
      skills: ['U1-S8'],
      explanation: [
        'Gogga objects produce graphical output. A program can also produce text output: letters, numbers and special characters such as *, % and $.',
        'System.out.print() and System.out.println() display, in an output window, whatever is in the round brackets. println can be read as "print and go to the next line".',
        'Anything in double quotes is displayed exactly as it is. A calculation without quotes, such as (2 + 3), is worked out first and the result 5 is displayed. With quotes, "2 + 3" is shown as text.',
        'With print the next output appears on the same line. With println the next output appears on the next line. An empty System.out.println(); just ends the line, which can give a blank line.',
      ],
      vocabulary: [
        { term: 'Text output', definition: 'Output made of letters, numbers and special characters such as *, % and $.' },
        { term: 'print', definition: 'Displays what is in the brackets; the next output is on the same line.' },
        { term: 'println', definition: 'Displays what is in the brackets; the next output is on the next line.' },
      ],
      workedExamples: [
        { code: 'System.out.print ("Hello, 2 + 3 = ");\nSystem.out.println (2 + 3);\nSystem.out.println ("Good Bye");', explanation: 'Activity 6 output: line 1 is Hello, 2 + 3 = 5 and line 2 is Good Bye.' },
        { code: 'System.out.println("Hello!");\nSystem.out.println("How are you?");\nSystem.out.println("My name is Sam.");', explanation: 'Exercise 2 Greet program: three println statements put the three messages one below the other.' },
      ],
      misconceptions: [
        'Thinking System.out.println("2 + 3"); prints 5. The quotes make it text, so it prints 2 + 3.',
        'Thinking print and println are the same. Only println moves the next output to a new line.',
      ],
      questions: [
        {
          id: 'U1-T6-Q1', type: 'trace', category: 'predict',
          prompt: 'Predict the output. Type each line exactly as it appears.',
          code: 'System.out.println ("Hello, 2 + 3 = ");\nSystem.out.println (2 + 3);\nSystem.out.println ("2 + 3");',
          rows: [
            { label: 'Line 2', answer: '5' },
            { label: 'Line 3', answer: '2 + 3' },
            { label: 'Total number of lines', answer: '3' },
          ],
          hint: 'Each println ends its line. Quotes mean "show as is".',
          explanation: 'Because the first line now uses println, the 5 goes on line 2. The third statement has quotes, so it shows the text 2 + 3 instead of calculating.',
          skills: ['U1-S8'],
        },
        {
          id: 'U1-T6-Q2', type: 'mc', category: 'distinguish',
          prompt: 'What is the difference between the print and println methods?',
          options: [
            'print shows text only; println shows numbers only',
            'print adds a blank line before the text; println does not',
            'println calculates what is in quotes; print does not',
            'println moves the next output to a new line; print keeps it on the same line',
          ],
          answer: 3,
          hint: 'Read println as "print and go to the next line".',
          explanation: 'Both display what is in the brackets. After print the next output stays on the same line; after println it starts on the next line.',
          skills: ['U1-S8'],
        },
        {
          id: 'U1-T6-Q3', type: 'mc', category: 'apply',
          prompt: 'Which code displays Hello!, How are you? and My name is Sam. on three lines, one below the other?',
          options: [
            'System.out.println("Hello!"); System.out.println("How are you?"); System.out.println("My name is Sam.");',
            'System.out.print("Hello!"); System.out.print("How are you?"); System.out.println("My name is Sam.");',
            'System.out.println(Hello!); System.out.println(How are you?); System.out.println(My name is Sam.);',
            'System.out.print("Hello!"); System.out.println("How are you?"); System.out.println("My name is Sam.");',
          ],
          answer: 0,
          hint: 'Each message needs to end its own line, and text needs double quotes.',
          explanation: 'Each println ends the line, so the three messages appear one below the other. Text must be in double quotes, and print would join messages on one line.',
          skills: ['U1-S8'],
        },
      ],
    },
    {
      id: 'U1-T7',
      title: 'Getting and changing field values',
      sections: ['1.5'],
      skills: ['U1-S9', 'U1-S3'],
      explanation: [
        'Gogga tic = new Gogga(); creates an object with the new operator and a special constructor method Gogga(), which has the same name as the class. The constructor assigns values to the fields: red, facing up, roughly in the middle of the grid.',
        'move() changes the x- and y-position fields. Other methods change fields too: setPosition (x,y) moves the Gogga to new coordinates without drawing a trail and keeps its direction; setDirection(dir) uses Gogga.UP, Gogga.DOWN, Gogga.LEFT or Gogga.RIGHT.',
        'setColor (col), for example bug.setColor(Color.blue);, changes the colour of the Gogga and its trail, seen after the next move(). It needs import java.awt.*; at the top, and Color uses American spelling.',
        'setTrailWidth (num) changes the trail width in pixels; 0 means no trail. setLabel("Fred") shows a text label (in double quotes) that follows the Gogga. trailOn() and trailOff() turn the trail on or off from the next move(), with no error if it is already on or off.',
        'The values in round brackets after a method name are parameters: setPosition needs two, setColor needs one and move() needs none. Using a method is a method call (call statement); it transfers control to the method\'s definition, the list of instructions that tells Java how to carry it out.',
      ],
      vocabulary: [
        { term: 'Constructor', definition: 'A special method with the same name as the class, such as Gogga(), that assigns values to the new object\'s fields.' },
        { term: 'new operator', definition: 'Used with a constructor to create an object.' },
        { term: 'Parameters', definition: 'The values in round brackets after a method name.' },
        { term: 'Method call', definition: 'Using a method in a program; the call statement transfers control to the method\'s definition.' },
        { term: 'String', definition: 'A text value: a set of characters in double quote marks, such as "Fred".' },
      ],
      workedExamples: [
        { code: 'import it.*;\nimport java.awt.*;\n...\nGogga kreepy = new Gogga();\nkreepy.setColor (Color.blue);\nkreepy.setPosition(3,1);\nkreepy.setDirection (Gogga.RIGHT);\nkreepy.setLabel("kreepy");\nkreepy.setTrailWidth (9);\nkreepy.move();', explanation: 'Activity 7: without import java.awt.*; the setColor line gives an error. With it, kreepy is blue and draws a wide blue trail.' },
        { code: 'bug.setPosition(7, 2);', explanation: 'A call statement: Java finds the definition of setPosition and carries it out with 7 for x and 2 for y.' },
      ],
      misconceptions: [
        'Thinking setPosition draws a line to the new spot. It jumps there without a trail and keeps the same direction.',
        'Thinking setColor changes the trail immediately. The new colour is only seen after the next move().',
        'Writing setDirection(DOWN). The direction must be prefixed with the class name: Gogga.DOWN.',
      ],
      questions: [
        {
          id: 'U1-T7-Q1', type: 'mc', category: 'define',
          prompt: 'In bug.setPosition (4,3); what are 4 and 3 called?',
          options: [
            'Fields of the Gogga class',
            'Parameters of the method',
            'Constructors of the object',
            'Class values of the grid',
          ],
          answer: 1,
          hint: 'They are the values in round brackets after the method name.',
          explanation: 'The numbers in round brackets after a method name are parameters. setPosition needs two: x (column across) and y (row down).',
          skills: ['U1-S9'],
        },
        {
          id: 'U1-T7-Q2', type: 'tf', category: 'explain',
          prompt: 'True or false: bug.setPosition (4,3); draws a trail from bug\'s old position to (4, 3).',
          answer: false,
          hint: 'Check the table in section 1.5.',
          explanation: 'setPosition moves the Gogga to the new coordinates without drawing a trail, and its direction stays the same.',
          skills: ['U1-S9'],
        },
        {
          id: 'U1-T7-Q3', type: 'mc', category: 'explain',
          prompt: 'How can you tell that Gogga() is a constructor method?',
          options: [
            'It is the only method that needs a parameter',
            'It is always the last statement in main',
            'It is used with the class name, like Gogga.setGridSize',
            'It has the same name as the class and is used with new',
          ],
          answer: 3,
          hint: 'Compare its name with the class name.',
          explanation: 'A constructor has the same name as the class and is used with the new operator to create an object and assign values to its fields.',
          skills: ['U1-S3', 'U1-S9'],
        },
      ],
    },
    {
      id: 'U1-T8',
      title: 'Errors',
      sections: ['1.6'],
      skills: ['U1-S10'],
      explanation: [
        'A new program will probably have errors. The IDE gives an error message and points to the location, and most errors are easy to fix. Sometimes it highlights the next line, because it was still looking for the missing semi-colon.',
        'Activity 8 makes errors on purpose: a missing semi-colon (bug.move ()), a missing closing bracket (bug.move (), a missing closing quote (bug.setLabel("Thabo), a misspelt method (bug.moove()) and an undeclared object (bugg.move();).',
        'These are syntax errors, also called compilation errors, because they prevent the program from compiling. They come from misspellings, incorrect or missing characters such as semi-colons and brackets, or a word that has not been defined.',
        'If your IDE compiles before running, it will not run a program that cannot compile.',
        'Logical errors are mistakes in the logical steps of the solution. The program compiles and runs but gives unexpected or illogical output, like the LetterS program that starts off the grid at (8, 22) or draws a square instead of an S.',
      ],
      vocabulary: [
        { term: 'Syntax error', definition: 'An error, such as a misspelling, missing semi-colon or bracket, or undefined word, that prevents the program from compiling; also called a compilation error.' },
        { term: 'Logical error', definition: 'An error in the logical steps of the solution; the program runs but produces unexpected or illogical output.' },
      ],
      workedExamples: [
        { code: 'Gogga bug = new Gogga();\nbugg.move();\nbug.moove();', explanation: 'Both are syntax errors: no object called bugg was created, and there is no method called moove().' },
        { code: 'Gogga bug = new Gogga;      // error: should be new Gogga();\ntick.setPosition (8, 22);   // error: tick was never created', explanation: 'Two of the syntax errors in Exercise 3. The program also needs import it.*; above the class heading.' },
      ],
      misconceptions: [
        'Thinking a program that compiles must be correct. It can still have logical errors that give the wrong output.',
        'Thinking the error is always on the highlighted line. A missing semi-colon is often reported on the next line.',
      ],
      questions: [
        {
          id: 'U1-T8-Q1', type: 'mc', category: 'classify',
          prompt: 'A program contains bug.moove(); instead of bug.move();. What kind of error is this?',
          options: [
            'A syntax (compilation) error',
            'A logical error',
            'No error; Java ignores spelling inside method names',
            'An error that appears only after the program has run',
          ],
          answer: 0,
          hint: 'Does Java know a method called moove()?',
          explanation: 'Java does not know a method called moove(), so the program cannot compile. Misspellings and undefined words are syntax errors.',
          skills: ['U1-S10'],
        },
        {
          id: 'U1-T8-Q2', type: 'tf', category: 'define',
          prompt: 'True or false: a program with a logical error still compiles and runs, but gives unexpected output.',
          answer: true,
          hint: 'It is the steps of the solution that are wrong, not the spelling.',
          explanation: 'Logical errors do not stop compiling. The program runs but produces unexpected or illogical output.',
          skills: ['U1-S10'],
        },
        {
          id: 'U1-T8-Q3', type: 'mc', category: 'classify',
          prompt: 'After the syntax errors in LetterS are fixed, the grid appears empty because of tick.setPosition (8, 22);. What kind of error is this?',
          options: [
            'A syntax error, because 22 is not a valid number in Java',
            'A syntax error, because setPosition is misspelt',
            'A logical error: it compiles and runs, but y = 22 is off the grid',
            'No error: the Gogga is hidden on purpose by setPosition',
          ],
          answer: 2,
          hint: 'Did the program compile and run?',
          explanation: 'The program compiles and runs, but row 22 is off the grid, so the output is wrong. That makes it a logical error.',
          skills: ['U1-S10'],
        },
      ],
    },
    {
      id: 'U1-T9',
      title: 'Program summary and what happens when it runs',
      sections: ['1.7', '1.8'],
      skills: ['U1-S2', 'U1-S9', 'U1-S11'],
      explanation: [
        'ColouredLines brings it together. import it.*; makes the Gogga classes available and import java.awt.*; lets the program use colours from the Color class. Both go above the class heading.',
        'main() is the starting point and holds the instructions inside its curly brackets: the outer set belongs to the class and the inner set to main. Methods always have round brackets; some take parameters and must be called with the correct number.',
        'setPosition() takes two parameters (column across, then row down). setDirection() needs UP, DOWN, LEFT or RIGHT prefixed with Gogga, and setColor() needs a colour prefixed with Color. The methods depend on louse and must come from the same class as the object.',
        'Some fields and methods are independent of any object. These class fields or methods are used with their class name in dot notation, for example Color.black, or Gogga.RIGHT, a class value of the Gogga class.',
        'When you compile or run MakeSquare.java (the source code): 1) it is checked for syntax errors, with messages if any are found; 2) it is translated into Java bytecode (close to machine code) saved as MakeSquare.class, with a "Successful compilation" message; 3) the Java Virtual Machine interprets the bytecode into a format the operating system (OSX, Linux or Windows) can run; 4) execution runs from the first statement in main and output appears as statements are carried out.',
        'Some IDEs compile and run in one action; others need two separate steps.',
      ],
      vocabulary: [
        { term: 'Source code', definition: 'The program you type, such as MakeSquare.java.' },
        { term: 'Bytecode', definition: 'The translated program, close to computer machine code, saved in a .class file.' },
        { term: 'Java Virtual Machine', definition: 'Interprets the .class bytecode into a format the operating system can run.' },
        { term: 'Class field or method', definition: 'A field or method independent of any object, used with its class name, such as Color.black.' },
      ],
      workedExamples: [
        { code: '// The ColouredLines class.\n// Your name & today\'s date\nimport it.*;\nimport java.awt.*;\n\npublic class ColouredLines\n{\n    public static void main (String[] args)\n    {\n        Gogga louse = new Gogga ();\n        louse.setPosition (2, 1);\n        louse.setDirection (Gogga.RIGHT);\n        louse.setColor (Color.black);\n        louse.move ();\n        louse.move ();\n        louse.setPosition (2, 3);\n        louse.setDirection (Gogga.RIGHT);\n        louse.setColor (Color.blue);\n        louse.move ();\n        louse.move ();\n    } //end of main method\n} // end of ColouredLines class', explanation: 'The summary program draws a black line from (2, 1) to (4, 1) and a blue line from (2, 3) to (4, 3).' },
      ],
      misconceptions: [
        'Thinking a comment displays what the program does when it runs. Comments are ignored when the program runs.',
        'Thinking setColor can go anywhere. It only affects moves that come after it, so it must come before the moves to be coloured.',
        'Thinking the .java file is run directly. It is compiled to bytecode in a .class file, which the Java Virtual Machine interprets.',
      ],
      questions: [
        {
          id: 'U1-T9-Q1', type: 'mc', category: 'identify',
          prompt: 'In louse.setColor (Color.black); what is Color.black?',
          options: [
            'A field belonging only to the object louse',
            'A class value of the Color class, used with the class name',
            'A constructor method that creates a black Gogga',
            'A String label that is displayed next to louse',
          ],
          answer: 1,
          hint: 'It is written with a class name in front, not an object name.',
          explanation: 'Color.black is a fixed colour value that can be applied to any object. Class fields like this are used with their class name in dot notation.',
          skills: ['U1-S9'],
        },
        {
          id: 'U1-T9-Q2', type: 'trace', category: 'identify',
          prompt: 'MakeSquare.java compiles successfully. Fill in the blanks exactly.',
          code: 'Source code:  MakeSquare.java\nCompile  ->   ?\nRun      ->   bytecode interpreted by the ?',
          rows: [
            { label: 'File that holds the bytecode', answer: 'MakeSquare.class' },
            { label: 'Program that interprets the bytecode (3-letter abbreviation in capitals)', answer: 'JVM' },
          ],
          hint: 'Same name as the source file, different extension.',
          explanation: 'Compiling saves the bytecode with the same name but the extension .class. The Java Virtual Machine (JVM) interprets it so the operating system can run it.',
          skills: ['U1-S11'],
        },
        {
          id: 'U1-T9-Q3', type: 'mc', category: 'explain',
          prompt: 'Does it make a difference where setColor() is placed in a program?',
          options: [
            'No, it always colours the whole trail, wherever it is placed',
            'No, as long as it comes after the last move() in main',
            'Yes, it must be the very first statement in main',
            'Yes, it only affects the trail from the next move() onwards',
          ],
          answer: 3,
          hint: 'In ColouredLines, why does the first line come out black and the second blue?',
          explanation: 'The colour change is seen only after the next move(), so setColor must come before the moves you want in that colour.',
          skills: ['U1-S9', 'U1-S2'],
        },
      ],
    },
    {
      id: 'U1-T10',
      title: 'Changing the size of the Gogga grid',
      sections: ['1.9'],
      skills: ['U1-S12'],
      explanation: [
        'Section 1.9 gives the default grid as 15 blocks across and 10 down (section 1.2.1 describes it as 14 columns by 9 rows). You can make it larger with Gogga.setGridSize (numAcross, numDown);',
        'Gogga.setGridSize (25, 20); produces a grid with columns 0 to 24 and rows 0 to 19.',
        'setGridSize() is a class method, so it is used with the class name Gogga, not with an object.',
        'The grid is independent of the Gogga objects on it and must be set up before any Gogga objects are created, so it exists for them to be placed on. For Activity 9 (Cross): Gogga.setGridSize (20, 10); and then Gogga fred = new Gogga ();',
        'The maximum grid size is (31, 19), though this may vary with your screen. Exercise 4 (HeartBeat) uses a custom grid size; plan the drawing with an algorithm first.',
      ],
      vocabulary: [
        { term: 'setGridSize', definition: 'A class method of Gogga that sets the number of grid positions across and down.' },
        { term: 'Class method', definition: 'A method used with the class name rather than with a specific object.' },
      ],
      workedExamples: [
        { code: 'Gogga.setGridSize (20, 10);\nGogga fred = new Gogga ();', explanation: 'Activity 9: the grid is set first, then fred is created on it.' },
        { code: 'Gogga.setGridSize (11, 6);', explanation: 'Check Point 3: a grid 11 columns across and 6 rows down.' },
      ],
      misconceptions: [
        'Writing fred.setGridSize(20, 10). setGridSize is a class method and is used with the class name Gogga.',
        'Thinking the grid can be any size. The maximum is (31, 19), depending on your screen.',
      ],
      questions: [
        {
          id: 'U1-T10-Q1', type: 'mc', category: 'apply',
          prompt: 'Which line makes the grid 11 columns across and 6 rows down?',
          options: [
            'Gogga.setGridSize (11, 6);',
            'Gogga.setGridSize (6, 11);',
            'bug.setGridSize (11, 6);',
            'Gogga.setPosition (11, 6);',
          ],
          answer: 0,
          hint: 'Across comes first, and it is a class method.',
          explanation: 'setGridSize (numAcross, numDown) is called with the class name Gogga, with the number across first.',
          skills: ['U1-S12'],
        },
        {
          id: 'U1-T10-Q2', type: 'tf', category: 'explain',
          prompt: 'True or false: the grid size must be set before any Gogga objects are created.',
          answer: true,
          hint: 'Where are Gogga objects placed?',
          explanation: 'The grid must exist before Gogga objects can be placed on it, so Gogga.setGridSize comes before any new Gogga.',
          skills: ['U1-S12'],
        },
        {
          id: 'U1-T10-Q3', type: 'trace', category: 'calculate',
          prompt: 'Fill in the numbers for the grid this statement creates and the maximum size the book gives.',
          code: 'Gogga.setGridSize (20, 10);',
          rows: [
            { label: 'Highest column number', answer: '19' },
            { label: 'Highest row number', answer: '9' },
            { label: 'Maximum number across the book says can be set', answer: '31' },
          ],
          hint: 'setGridSize (25, 20) gives columns 0 to 24.',
          explanation: 'Numbering starts at 0, so 20 across gives columns 0 to 19 and 10 down gives rows 0 to 9. The maximum size is (31, 19), depending on your screen.',
          skills: ['U1-S12'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 'u1-gogga-rescue',
    unitId: UNIT.id,
    title: 'Lost in the Mine Shaft',
    icon: 'alert',
    summary: 'Program a rescue Gogga through a flooded mine grid before the air runs out.',
    briefing: 'A rock fall has trapped miners deep below Johannesburg, and the only way to reach them is a tiny robot Gogga steered by Java code. Every move, turn and setPosition must be exactly right, and the grid must be sized before the robot is created. One wrong instruction and the robot is lost.',
    tickerMessages: [
      'Rescue team on standby: robot Gogga powered up at the shaft entrance.',
      'Mine map loaded: the grid size must be set before the robot is created.',
      'Water rising in tunnel 3: the robot must turn and move without wasted steps.',
      'Air supply below half: every coordinate must be correct the first time.',
      'Final tunnel ahead: one wrong turn and the robot is lost in the dark.',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['U1-S3', 'U1-S4', 'U1-S5', 'U1-S9', 'U1-S12'],
    victoryMessage: 'The robot Gogga reaches the miners and lights the way out. Every one of them is safe.',
    failMessage: 'The robot wandered off the grid. Review moving, turning and the set methods, then try again.',
  },
  {
    id: 'u1-launch-compile',
    unitId: UNIT.id,
    title: 'Compile Before Launch',
    icon: 'rocket',
    summary: 'Fix the launch program so it compiles and prints the right countdown.',
    briefing: 'A student satellite at Hartebeesthoek is minutes from launch, but the control program will not compile and its output is scrambled. You must find the syntax errors, fix the class and main method, and make sure print and println give exactly the right messages before the window closes.',
    tickerMessages: [
      'Launch control: countdown program fails to compile.',
      'Engineers report a missing semi-colon and a misspelt method.',
      'Status messages printing on one line: print and println mixed up.',
      'Bytecode still not generated: the JVM has nothing to run.',
      'Launch window closing in under four minutes.',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['U1-S2', 'U1-S8', 'U1-S10', 'U1-S11'],
    victoryMessage: 'Successful compilation. The countdown prints perfectly and the satellite lifts off.',
    failMessage: 'The program still does not compile and the launch is scrubbed. Revise errors, output and compiling, then try again.',
  },
];
