// Unit 10: Nested Loops (Exploring IT: Java Programming Grade 10, 3rd ed)
import { Layers } from 'lucide-react';

export const UNIT = { id: 'U10', number: 10, name: 'Nested Loops', worldId: 'nested-loops' };

export const SKILLS = {
  'U10-S1': { unit: 'U10', name: 'Nested loop structure', description: 'Place one loop completely inside another, with correctly matched curly brackets and indentation.', sections: ['10.1'] },
  'U10-S2': { unit: 'U10', name: 'Counting nested iterations', description: 'Work out how many times the body of an inner loop runs (outer repetitions x inner repetitions).', sections: ['10.1', '10.2', '10.3'] },
  'U10-S3': { unit: 'U10', name: 'Rows with print and println', description: 'Use print inside the inner loop to stay on a line and println after the inner loop to move to the next line.', sections: ['10.1'] },
  'U10-S4': { unit: 'U10', name: 'User input and char loops', description: 'Let the user choose the character, rows and row length, and use a char loop control variable inside an outer loop.', sections: ['10.1', '10.4.1'] },
  'U10-S5': { unit: 'U10', name: 'Gogga with nested loops', description: 'Draw squares in all four directions with setDirection and nested move/turnLeft loops.', sections: ['10.1', '10.2', '10.3'] },
  'U10-S6': { unit: 'U10', name: 'Repeating a section inside another', description: 'Decide what must be repeated and where, e.g. the Yeah Yeah Yeah part inside each repeated song line.', sections: ['10.2'] },
  'U10-S7': { unit: 'U10', name: 'Nested loops for processing data', description: 'Process groups of input (students and marks, shares and days) with averages, percentages and the highest value.', sections: ['10.2'] },
  'U10-S8': { unit: 'U10', name: 'More complex nested loops', description: 'Use three levels of loops and a changing position variable to repeat whole shapes across or diagonally on the grid.', sections: ['10.3'] },
  'U10-S9': { unit: 'U10', name: 'Outer loop controls the inner loop', description: 'Use the outer loop control variable as the termination value of the inner loop to print a triangle of stars.', sections: ['10.4', '10.4.1'] },
  'U10-S10': { unit: 'U10', name: 'Star pattern formulas', description: 'Use the odd number generator 2n - 1 for stars and 5 - loop for spaces with two inner loops to build centred patterns.', sections: ['10.4.2'] },
};

export const SKILL_HINTS = {
  'U10-S1': 'A nested loop is one loop completely inside another; the outer loop curly brackets must enclose the whole inner loop; indent the inner loop',
  'U10-S2': 'Total inner-body runs = outer repetitions x inner repetitions, e.g. 5 rows x 12 per row = 60; three levels multiply again (4 x 4 x 5 = 80)',
  'U10-S3': 'System.out.print keeps the cursor on the same line; put print inside the inner loop and System.out.println() after the inner loop to start a new row',
  'U10-S4': 'Input with JOptionPane.showInputDialog and Integer.parseInt for rows and row length; a char loop for (char ch = \'A\'; ch <= \'Z\'; ch++) can be the inner loop',
  'U10-S5': 'Gogga.UP = 1, DOWN = 2, LEFT = 3, RIGHT = 4; outer loop for (dir 1 to 4) calls bug.setDirection(dir); inner loop draws a square with move() and turnLeft()',
  'U10-S6': 'Decide what repeats and where: "She loves you," then an inner loop displaying Yeah 3 times, then "!" and a new line, all inside an outer loop of 3 lines',
  'U10-S7': 'Outer loop per student (or share), inner loop per subject (or day); reset total inside the outer loop; average = total / 3.0; % change = 100.0 * (evening - morning) / morning',
  'U10-S8': 'Three levels: squares, sides, length; int x = 5 and bug.setPosition(x, 7) then x = x + 6 after each square places 3 squares side by side; add a y variable for diagonal',
  'U10-S9': 'Triangle: for loop 1 to 5, inner for numStars 1 to loop prints "*", then new line; inner loop is dependent on the outer loop control variable',
  'U10-S10': 'Odd number generator 2n - 1 gives 1, 3, 5, 7, 9 stars; spaces = 5 - loop (4, 3, 2, 1, 0); spaces loop runs before stars loop; a loop to 0 does not execute',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'The Loop-in-a-Loop Lair',
  subtitle: 'Unit 10 \u00b7 Nested Loops',
  color: 'violet',
  glow: 'ja-glow-violet',
  bg: 'ja-w-nested-loops',
  icon: Layers,
  blurb: 'Loops hide inside loops here. Count every iteration, forge star patterns and steer the Gogga through squares within squares.',
};

export const LEVELS = [
  { id: 'u10-l1', name: 'Loop Inside a Loop', subtitle: 'Simple nested loops, rows and columns', challengeIds: ['u10-c1', 'u10-c2', 'u10-c3', 'u10-c4', 'u10-c5', 'u10-c6'] },
  { id: 'u10-l2', name: 'Sections Within Sections', subtitle: 'Songs, Gogga squares and repeated data', challengeIds: ['u10-c7', 'u10-c8', 'u10-c9', 'u10-c10', 'u10-c11', 'u10-c12', 'u10-c13'] },
  { id: 'u10-l3', name: 'Loops Three Deep', subtitle: 'Complex nesting and the outer loop in control', hasCoding: true, challengeIds: ['u10-c14', 'u10-c15', 'u10-c16', 'u10-c17', 'u10-c18', 'u10-c19', 'u10-c20'] },
  { id: 'u10-l4', name: 'Boss: The Star Forge', subtitle: 'Mixed review: patterns, formulas and full programs', hasCoding: true, challengeIds: ['u10-c21', 'u10-c22', 'u10-c23', 'u10-c24', 'u10-c25', 'u10-c26'] },
];

export const CHALLENGES = {
  'u10-c1': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'What does this code from the NestedFor class display?',
    code: 'for (int row = 1; row <= 5; row++)\n{\n   for (int col = 1; col <= 12; col++)\n   {\n      System.out.print("!");\n   }\n   System.out.println();\n}',
    options: [
      '5 rows with 12 exclamation marks in each row',
      '12 rows with 5 exclamation marks in each row',
      'One long row of 60 exclamation marks',
      '5 rows with 1 exclamation mark in each row',
    ],
    answer: 0,
    hint: 'The outer loop decides how many rows; the inner loop decides what goes on one row.',
    explanation: 'The inner loop prints 12 marks on the same line, then println() moves the cursor down. The outer loop repeats that 5 times, giving 5 rows of 12.',
    skills: ['U10-S1', 'U10-S3'],
  },
  'u10-c2': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Trace the nested loop. Type whole numbers only.',
    code: 'int count = 0;\nfor (int i = 1; i <= 4; i++)\n{\n   for (int j = 1; j <= 3; j++)\n   {\n      count++;\n   }\n}',
    rows: [
      { label: 'Times the inner body runs while i = 1', answer: '3' },
      { label: 'Value of j that makes the inner loop stop', answer: '4' },
      { label: 'Final value of count', answer: '12' },
    ],
    hint: 'The whole inner loop runs from the start for every single value of i.',
    explanation: 'For each of the 4 values of i, j runs 1, 2, 3 and stops when j becomes 4. So count++ runs 4 x 3 = 12 times.',
    skills: ['U10-S2'],
  },
  'u10-c3': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'In Nested2 the programmer wanted ten rows of ABCDE, one below the other. What is wrong?',
    code: 'for (int i = 1; i <= 10; i = i + 1)\n{\n   System.out.print("ABCDE");\n}',
    options: [
      'The loop only runs 9 times because i starts at 1',
      'i = i + 1 is a syntax error in a for loop header',
      'print keeps the cursor on the line, so all 50 letters are on one row',
      'The curly brackets make only the first ABCDE display',
    ],
    answer: 2,
    hint: 'Where does the cursor end up after System.out.print?',
    explanation: 'System.out.print does not move to a new line, so ABCDE is displayed ten times next to each other. Using System.out.println("ABCDE") puts each one on its own row.',
    skills: ['U10-S3'],
  },
  'u10-c4': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: in a nested loop the curly brackets of the outer loop must be outside the inner loop, so that the inner loop is completely enclosed in the outer loop.',
    answer: true,
    hint: 'Think of the inner loop as sitting inside a box drawn by the outer loop.',
    explanation: 'That is exactly why it is called a nested loop: one loop is completely inside the other. Check that every opening curly bracket has a matching closing one.',
    skills: ['U10-S1'],
  },
  'u10-c5': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'The inner loop now generates the letters. What is displayed?',
    code: 'for (int row = 1; row <= 3; row++)\n{\n   for (char ch = \'A\'; ch <= \'E\'; ch++)\n   {\n      System.out.print(ch);\n   }\n   System.out.println();\n}',
    options: [
      'ABCDEABCDEABCDE',
      'AAA\nBBB\nCCC\nDDD\nEEE',
      'ABCDE\nABCDE\nABCDE',
      'A\nB\nC\nD\nE',
    ],
    answer: 2,
    hint: 'A char loop control variable counts A, B, C, D, E. Which statement moves to a new line, and where is it?',
    explanation: 'The char loop prints A to E on one line with print, then println() ends the row. The outer loop repeats this for 3 rows.',
    skills: ['U10-S4', 'U10-S3'],
  },
  'u10-c6': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Exercise 1: match each pattern to the inner loop that builds ONE row of it.',
    pairs: [
      { left: '11 rows of %%%%%%%', right: 'for (int k = 1; k <= 7; k++) System.out.print("%");' },
      { left: '5 rows of 9876543210', right: 'for (int d = 9; d >= 0; d--) System.out.print(d);' },
      { left: '4 rows of ( ) ( ) ... with 9 pairs per row', right: 'for (int k = 1; k <= 9; k++) System.out.print("( ) ");' },
      { left: '10 rows of ABCDE', right: 'for (char ch = \'A\'; ch <= \'E\'; ch++) System.out.print(ch);' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Look at what appears on one row and how many times; the number of rows belongs to the outer loop.',
    explanation: 'The inner loop builds a single row, so its header depends only on what is in that row. The number of rows (11, 5, 4, 10) goes in the outer loop header.',
    skills: ['U10-S1', 'U10-S4'],
  },
  'u10-c7': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the steps of the Song1 algorithm in order to display "She loves you, Yeah Yeah Yeah!" three times.',
    items: [
      'display "!" and move to the next line',
      'start outer loop: line = 1; line <= 3; line = line + 1',
      'inner loop body: display "Yeah"',
      'display "She loves you, "',
      'start inner loop: count = 1; count <= 3; count = count + 1',
    ],
    answer: [1, 3, 4, 2, 0],
    hint: 'Decide what is repeated inside each line, and what is displayed before and after that part.',
    explanation: 'Each line starts with "She loves you, ", then the inner loop displays Yeah three times, then "!" ends the line. The outer loop repeats the whole line three times.',
    skills: ['U10-S6'],
  },
  'u10-c8': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Activity 4: fill in the missing values of the inner loop header so each line has Yeah Yeah Yeah. Type whole numbers.',
    code: 'line = 1 ; line <= 3 ; line = line + 1\n    display "She loves you, "\n    count = ... ; count <= ... ; count = count + ...\n        display "Yeah "\n    display "!" and move to the next line',
    rows: [
      { label: 'count starts at', answer: '1' },
      { label: 'count <= ?', answer: '3' },
      { label: 'count = count + ?', answer: '1' },
      { label: 'Total Yeahs displayed for all 3 lines', answer: '9' },
    ],
    hint: 'Yeah appears three times per line; count it 1, 2, 3.',
    explanation: 'count goes from 1 to 3 in steps of 1, so Yeah is displayed 3 times per line. The outer loop runs 3 times, so 3 x 3 = 9 Yeahs.',
    skills: ['U10-S6', 'U10-S2'],
  },
  'u10-c9': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'This is a Song2 solution. How many times is "round and round" displayed in total, and how many times is "All over town!" displayed?',
    code: 'for (int line = 1; line <= 3; line++)\n{\n   System.out.print("The wheels on the bus go round and round");\n   for (int k = 1; k <= 2; k++)\n   {\n      System.out.print(", round and round");\n   }\n   System.out.println(",");\n}\nSystem.out.println("All over town!");',
    options: [
      'round and round 6 times; All over town! once',
      'round and round 9 times; All over town! once',
      'round and round 9 times; All over town! 3 times',
      'round and round 6 times; All over town! 3 times',
    ],
    answer: 1,
    hint: 'Count the "round and round" in the first print too. Is the last println inside or outside the outer loop?',
    explanation: 'Each line has 1 + 2 = 3 "round and round", and there are 3 lines, so 9. "All over town!" comes after the closing bracket of the outer loop, so it is displayed once.',
    skills: ['U10-S6'],
  },
  'u10-c10': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Activity 3: the outer loop draws the square in each direction. Count the method calls. Type whole numbers.',
    code: 'Gogga bug = new Gogga();\n\nfor (int dir = 1; dir <= 4; dir++)\n{\n   bug.setDirection(dir);\n\n   for (int sides = 1; sides <= 4; sides++)\n   {\n      bug.move();\n      bug.move();\n      bug.turnLeft();\n   }\n}',
    rows: [
      { label: 'Times setDirection is called', answer: '4' },
      { label: 'Times turnLeft() is called', answer: '16' },
      { label: 'Times move() is called', answer: '32' },
    ],
    hint: 'setDirection is in the outer loop only. The inner body runs 4 x 4 times and has two move() calls.',
    explanation: 'setDirection runs once per direction (4). The inner body runs 4 x 4 = 16 times, so turnLeft runs 16 times and move runs 16 x 2 = 32 times.',
    skills: ['U10-S5', 'U10-S2'],
  },
  'u10-c11': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: Gogga.LEFT is a named constant with the value 3, so bug.setDirection(3) makes the bug face left.',
    answer: true,
    hint: 'UP, DOWN, LEFT, RIGHT are numbered 1 to 4 in that order.',
    explanation: 'Gogga.UP is 1, Gogga.DOWN is 2, Gogga.LEFT is 3 and Gogga.RIGHT is 4. That is why the loop control variable dir can go from 1 to 4 and be passed to setDirection.',
    skills: ['U10-S5'],
  },
  'u10-c12': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'StudentAverages: how many input dialog boxes appear when this runs?',
    code: 'for (int student = 1; student <= 5; student++)\n{\n   String name = JOptionPane.showInputDialog("Name?");\n   int total = 0;\n   for (int subject = 1; subject <= 3; subject++)\n   {\n      total = total + Integer.parseInt(JOptionPane.showInputDialog("Mark?"));\n   }\n   System.out.println(name + " " + total / 3.0);\n}',
    options: ['15', '8', '18', '20'],
    answer: 3,
    hint: 'One dialog is in the outer loop only; the other is in the inner loop.',
    explanation: 'The name is asked once per student (5 times) and a mark 3 times per student (5 x 3 = 15). That is 5 + 15 = 20 dialogs.',
    skills: ['U10-S7', 'U10-S2'],
  },
  'u10-c13': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'StockExchange: the Stocks share was 800 in the morning and 850 in the evening on Wednesday. Type each value exactly as Java prints it.',
    code: 'int morning = 800;\nint evening = 850;\nint change = evening - morning;\ndouble pctA = change / morning * 100;\ndouble pctB = 100.0 * change / morning;\nSystem.out.println(pctA);\nSystem.out.println(pctB);',
    rows: [
      { label: 'change', answer: '50' },
      { label: 'First line printed (pctA)', answer: '0.0' },
      { label: 'Second line printed (pctB)', answer: '6.25' },
    ],
    hint: 'Work left to right. What is 50 / 800 when both are int?',
    explanation: 'change / morning is int division: 50 / 800 = 0, and 0 * 100 = 0, stored as 0.0. Starting with 100.0 makes the calculation double: 5000.0 / 800 = 6.25 percent increase.',
    skills: ['U10-S7'],
  },
  'u10-c14': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Make3HorizSquares: trace x and count the moves. Type whole numbers.',
    code: 'int x = 5;\n\nfor (int numSquares = 1; numSquares <= 3; numSquares++)\n{\n   bug.setPosition(x, 7);\n   for (int sides = 1; sides <= 4; sides++)\n   {\n      for (int length = 1; length <= 5; length++)\n      {\n         bug.move();\n      }\n      bug.turnLeft();\n   }\n   x = x + 6;\n}',
    rows: [
      { label: 'x used by setPosition for square 2', answer: '11' },
      { label: 'x used by setPosition for square 3', answer: '17' },
      { label: 'Value of x after the outer loop ends', answer: '23' },
      { label: 'Total times move() is called', answer: '60' },
    ],
    hint: 'x changes only at the end of each square. Multiply the three loop counts for the moves.',
    explanation: 'x is 5, 11 and 17 for the three squares and becomes 23 after the third square. move() runs 3 x 4 x 5 = 60 times.',
    skills: ['U10-S8', 'U10-S5'],
  },
  'u10-c15': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Make3DiagSquares must draw the three squares diagonally instead of next to each other. What change is needed to Make3HorizSquares?',
    options: [
      'Change the length loop to run to 10 so the squares are bigger',
      'Add a y variable, use setPosition(x, y) and change x and y after each square',
      'Add a fourth loop around the numSquares loop to move the bug down',
      'Only change Gogga.setGridSize so that the grid becomes square',
    ],
    answer: 1,
    hint: 'Horizontal squares only change x. Diagonal means both co-ordinates move.',
    explanation: 'The textbook says to introduce a y variable and change its value after each square is drawn. Changing both x and y moves each new square diagonally.',
    skills: ['U10-S8', 'U10-S5'],
  },
  'u10-c16': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'Activity 6 (MakeSquareWithManyLoops): how many times is bug.move() called?',
    code: 'Gogga.setGridSize(18, 18);\nGogga bug = new Gogga();\n\nfor (int dir = 1; dir <= 4; dir++)\n{\n   bug.setDirection(dir);\n   for (int sides = 1; sides <= 4; sides++)\n   {\n      for (int length = 1; length <= 5; length++)\n      {\n         bug.move();\n      }\n      bug.turnLeft();\n   }\n}',
    options: ['80', '13', '16', '20'],
    answer: 0,
    hint: 'There are three levels of loops. Do you add or multiply their counts?',
    explanation: 'Each square has 4 sides of 5 moves (20 moves) and it is drawn in 4 directions, so 4 x 4 x 5 = 80 moves. 16 is the number of turnLeft calls.',
    skills: ['U10-S8', 'U10-S2'],
  },
  'u10-c17': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: in the Stars1 triangle program, the inner loop control variable is independent of the outer loop control variable.',
    answer: false,
    hint: 'Look at the termination value of the inner loop: for numStars 1 to loop.',
    explanation: 'The outer loop control variable loop is the termination value of the inner loop, so the inner loop is dependent on the outer loop. In the earlier blocks of characters there was no relation between them.',
    skills: ['U10-S9'],
  },
  'u10-c18': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'What does this code display?',
    code: 'for (int loop = 1; loop <= 4; loop++)\n{\n   for (int numStars = 1; numStars <= loop; numStars++)\n   {\n      System.out.print("*");\n   }\n   System.out.println();\n}',
    options: [
      '****\n***\n**\n*',
      '****\n****\n****\n****',
      '*\n*\n*\n*',
      '*\n**\n***\n****',
    ],
    answer: 3,
    hint: 'On line 1 the inner loop runs to 1, on line 2 it runs to 2, and so on.',
    explanation: 'The inner loop runs loop times, so line 1 has 1 star, line 2 has 2 stars, up to 4 stars on line 4. This is the Stars1 triangle with 4 rows.',
    skills: ['U10-S9'],
  },
  'u10-c19': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'This should print a triangle (*, **, ***) but prints 6 stars, each on its own line. How do you fix it?',
    code: 'for (int loop = 1; loop <= 3; loop++)\n{\n   for (int numStars = 1; numStars <= loop; numStars++)\n   {\n      System.out.println("*");\n   }\n}',
    options: [
      'Start the outer loop at 0 instead of 1',
      'Use print("*") in the inner loop and add System.out.println() after it',
      'Change the inner loop to end at 3 instead of loop',
      'Declare numStars before the outer loop starts',
    ],
    answer: 1,
    hint: 'Which statement should keep the cursor on the line, and where should the new line happen?',
    explanation: 'println inside the inner loop puts every star on a new line. Use print inside the inner loop and one println() after the inner loop to end each line.',
    skills: ['U10-S3', 'U10-S9'],
  },
  'u10-c20': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Activity 1 extension: write a program that asks the user for a character, the number of rows and the number of characters per row, then displays THREE identical blocks of that character, one under the other, with a blank line between each block. Example: # with 4 rows and 56 characters per row gives three blocks of 4 rows of 56 hashes.',
    criteria: 'Class NestedFor with a main method. Uses JOptionPane.showInputDialog three times: the character to display (stored as a String, or a char taken with charAt(0)), the number of rows and the number of characters per row (both converted with Integer.parseInt). Uses three nested for loops: an outer loop that runs exactly 3 times (one per block), a middle loop that runs once per row (1 to rows) and an inner loop that runs once per character (1 to characters per row). Only ONE System.out.print statement displays the character, inside the innermost loop (no hard-coded strings of characters). A System.out.println() after the innermost loop ends each row. A further System.out.println() after the row loop gives a blank line between blocks (a blank line after the last block is acceptable). Curly brackets correctly matched so each loop is completely enclosed by the one outside it, and the code is indented.',
    starter: 'import javax.swing.JOptionPane;\n\npublic class NestedFor\n{\n    public static void main(String[] args)\n    {\n        // your code here\n    }\n}',
    explanation: 'The block loop repeats a whole block, the row loop repeats a row and the character loop fills one row. println() after the inner loop ends a row and another println() after the row loop leaves the blank line.',
    skills: ['U10-S4', 'U10-S1', 'U10-S3'],
  },
  'u10-c21': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'What does this display? In the options a dot (.) stands for one space.',
    code: 'for (int loop = 1; loop <= 3; loop++)\n{\n   for (int numSpaces = 1; numSpaces <= 3 - loop; numSpaces++)\n   {\n      System.out.print(" ");\n   }\n   for (int numStars = 1; numStars <= 2 * loop - 1; numStars++)\n   {\n      System.out.print("*");\n   }\n   System.out.println();\n}',
    options: [
      '*\n***\n*****',
      '..*\n..***\n..*****',
      '..*\n.***\n*****',
      '*****\n.***\n..*',
    ],
    answer: 2,
    hint: 'Line by line: spaces = 3 - loop and stars = 2 * loop - 1.',
    explanation: 'Line 1 has 2 spaces and 1 star, line 2 has 1 space and 3 stars, line 3 has 0 spaces and 5 stars. The space loop runs before the star loop, so the triangle is centred.',
    skills: ['U10-S10'],
  },
  'u10-c22': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'The final triangle of stars from Activity 8 (5 lines). Type whole numbers.',
    code: 'for (int loop = 1; loop <= 5; loop++)\n{\n   for (int numSpaces = 1; numSpaces <= 5 - loop; numSpaces++)\n   {\n      System.out.print(" ");\n   }\n   for (int numStars = 1; numStars <= 2 * loop - 1; numStars++)\n   {\n      System.out.print("*");\n   }\n   System.out.println();\n}',
    rows: [
      { label: 'Spaces printed on line 2', answer: '3' },
      { label: 'Stars printed on line 4', answer: '7' },
      { label: 'Total stars printed', answer: '25' },
      { label: 'Total spaces printed', answer: '10' },
    ],
    hint: 'Use 5 - loop for spaces and 2 * loop - 1 for stars, then add up all 5 lines.',
    explanation: 'Stars are 1 + 3 + 5 + 7 + 9 = 25 and spaces are 4 + 3 + 2 + 1 + 0 = 10. On line 5 the space loop header is numSpaces <= 0, so it does not execute.',
    skills: ['U10-S10', 'U10-S2'],
  },
  'u10-c23': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'This should print *****, ****, ***, **, * (one row each) but prints a 5 by 5 square of stars. What is the bug?',
    code: 'for (int loop = 5; loop >= 1; loop--)\n{\n   for (int numStars = 1; numStars <= 5; numStars++)\n   {\n      System.out.print("*");\n   }\n   System.out.println();\n}',
    options: [
      'The outer loop must count up from 1 to 5, not down',
      'System.out.println() must be moved inside the inner loop',
      'The inner loop must start at 0 instead of starting at 1',
      'The inner loop always ends at 5; change numStars <= 5 to numStars <= loop',
    ],
    answer: 3,
    hint: 'For a triangle, should the number of stars on a line depend on the outer loop?',
    explanation: 'The inner loop is independent of the outer loop, so every line gets 5 stars. Using loop as the termination value gives 5, 4, 3, 2, 1 stars as loop counts down.',
    skills: ['U10-S9'],
  },
  'u10-c24': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Stars2 final version: ask the user how many lines the triangle must have, then print a centred triangle of stars where line loop has (lines - loop) spaces followed by 2 * loop - 1 stars. For 5 lines the last line has 9 stars and no spaces.',
    criteria: 'Class Stars2 with a main method. Inputs the number of lines with JOptionPane.showInputDialog and Integer.parseInt. Outer for loop with control variable loop from 1 to the number of lines. First inner for loop prints lines - loop spaces using System.out.print(" "). Second inner for loop (after the space loop, not nested in it) prints 2 * loop - 1 stars using System.out.print("*"). System.out.println() after both inner loops, inside the outer loop. No hard-coded strings of stars or spaces and no separate println statement per line. For input 5 the output is exactly: 4 spaces + 1 star, 3 spaces + 3 stars, 2 spaces + 5 stars, 1 space + 7 stars, 0 spaces + 9 stars. For input 0 or a negative number nothing is printed and the program does not crash.',
    starter: 'import javax.swing.JOptionPane;\n\npublic class Stars2\n{\n    public static void main(String[] args)\n    {\n        // your code here\n    }\n}',
    explanation: 'The outer loop control variable controls both inner loops: 2 * loop - 1 is the odd number generator for stars and lines - loop gives the spaces. If the user enters 0 or a negative number the outer loop never executes.',
    skills: ['U10-S10', 'U10-S9', 'U10-S4'],
  },
  'u10-c25': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Exercise 2 Question 3: a class has five students and each student takes three subjects. Input each student\'s name and three marks (out of 100), display each name with its average, then display the class average of all the averages and the name and average of the student with the highest average.',
    criteria: 'Class StudentAverages with a main method. Outer for loop runs exactly 5 times (one per student) and inputs the name with JOptionPane.showInputDialog. A total variable is reset to 0 inside the outer loop before the inner loop. Inner for loop runs exactly 3 times, inputs a mark with Integer.parseInt(JOptionPane.showInputDialog(...)) and adds it to the total. The average is a double calculated without integer division (e.g. total / 3.0). Displays the name and average for each student inside the outer loop (System.out.println or JOptionPane.showMessageDialog). Adds each average to a running sum and, after the outer loop, displays the class average (sum / 5). The highest average variable is set from the FIRST student\'s average (e.g. if (student == 1 || average > highest)), not from a guessed value, and the matching name is stored. After the loop the program displays the name and average of the student with the highest average.',
    starter: 'import javax.swing.JOptionPane;\n\npublic class StudentAverages\n{\n    public static void main(String[] args)\n    {\n        // your code here\n    }\n}',
    explanation: 'The outer loop handles one student at a time and the inner loop handles that student\'s three marks. Resetting total inside the outer loop stops marks from one student spilling into the next.',
    skills: ['U10-S7', 'U10-S2'],
  },
  'u10-c26': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Boss review: match each description to its formula or value.',
    pairs: [
      { left: 'Stars on line loop of the Stars1 triangle', right: 'loop' },
      { left: 'Stars on line loop of the odd-number triangle', right: '2 * loop - 1' },
      { left: 'Spaces on line loop of the 5-line centred triangle', right: '5 - loop' },
      { left: 'move() calls in Activity 6 (4 directions, 4 sides, 5 long)', right: '4 * 4 * 5 = 80' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Check each formula with loop = 1: the centred triangle starts with 4 spaces and 1 star.',
    explanation: 'Stars1 prints loop stars per line, the odd number generator 2n - 1 gives 1, 3, 5, 7, 9 stars and 5 - loop gives 4, 3, 2, 1, 0 spaces. Three nested loop counts multiply.',
    skills: ['U10-S10', 'U10-S9', 'U10-S2'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Learn to place one loop completely inside another to repeat a section inside a bigger section, draw Gogga shapes and print patterns of stars.',
  outcomes: [
    'By the end you can explain what a nested loop is and write one with correctly enclosed curly brackets.',
    'By the end you can calculate how many times the body of an inner loop executes.',
    'By the end you can use print and println correctly to build rows and blocks of characters.',
    'By the end you can let the user choose the character, row length and number of rows of a block.',
    'By the end you can use nested loops with the Gogga to draw squares in all four directions and repeat shapes across the grid.',
    'By the end you can decide what must be repeated and where, for songs and for data such as student marks and share prices.',
    'By the end you can use the outer loop control variable as the termination value of the inner loop.',
    'By the end you can use 2n - 1 for stars and 5 - loop for spaces to print a centred triangle of stars.',
  ],
  topics: [
    {
      id: 'U10-T1',
      title: 'Simple nested loops',
      sections: ['10.1'],
      skills: ['U10-S1', 'U10-S2', 'U10-S3'],
      explanation: [
        'A nested loop is one loop completely inside another loop. You start with one loop and then enclose it in another loop.',
        'In Activity 1 (class NestedFor) an inner loop displays twelve exclamation marks next to each other with System.out.print, so the cursor stays on the same line.',
        'A statement AFTER the inner loop, System.out.println(), moves the cursor to the beginning of the next line.',
        'An outer loop around this repeats the row, giving five rows of twelve exclamation marks. The inner body runs 5 x 12 = 60 times.',
        'Indent the inner loop inside the outer loop. Every opening curly bracket needs a matching closing curly bracket, and the brackets of the outer loop must be outside the inner loop so the inner loop is completely enclosed.',
        'Exercise 1 practises this with patterns: 11 rows of 7 % signs, 5 rows of 9876543210, and 4 rows of 9 ( ) pairs.',
      ],
      vocabulary: [
        { term: 'Nested loop', definition: 'One loop completely inside another loop.' },
        { term: 'Outer loop', definition: 'The loop that encloses the other loop; in a pattern it controls the rows.' },
        { term: 'Inner loop', definition: 'The loop inside the outer loop; it runs completely for every repetition of the outer loop and builds one row.' },
      ],
      workedExamples: [
        {
          code: 'for (int row = 1; row <= 5; row++)\n{\n   for (int col = 1; col <= 12; col++)\n   {\n      System.out.print("!");\n   }\n   System.out.println();\n}',
          explanation: 'Five rows of twelve exclamation marks. The println() is after the inner loop but inside the outer loop.',
        },
      ],
      misconceptions: [
        'Thinking the inner loop continues where it left off: it starts again from its initial value every time the outer loop repeats.',
        'Thinking the outer and inner loops run the same total number of times: the inner body runs outer x inner times.',
      ],
      questions: [
        {
          id: 'U10-T1-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'Which statement best describes a nested loop?',
          options: [
            'Two loops written one after the other',
            'A loop that calls itself until a condition is false',
            'A loop with more than one condition in its header',
            'A loop that is completely enclosed inside another loop',
          ],
          answer: 3,
          hint: 'Nested means one thing sits inside another.',
          explanation: 'A nested loop is one loop completely inside the other. Loops one after the other are not nested.',
          skills: ['U10-S1'],
        },
        {
          id: 'U10-T1-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'This code displays Pattern1 from Exercise 1. Type whole numbers.',
          code: 'for (int row = 1; row <= 11; row++)\n{\n   for (int k = 1; k <= 7; k++)\n   {\n      System.out.print("%");\n   }\n   System.out.println();\n}',
          rows: [
            { label: 'Times print("%") runs', answer: '77' },
            { label: 'Times println() runs', answer: '11' },
          ],
          hint: 'println() is in the outer loop only.',
          explanation: 'print("%") is in the inner loop: 11 x 7 = 77 times. println() runs once per row, 11 times.',
          skills: ['U10-S2'],
        },
        {
          id: 'U10-T1-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: to display five rows of twelve exclamation marks, the statement that moves the cursor to the next line must be inside the inner loop.',
          answer: false,
          hint: 'How many exclamation marks would end up on each line if it were inside?',
          explanation: 'If the new line were inside the inner loop, every mark would be on its own line. It belongs after the inner loop, inside the outer loop.',
          skills: ['U10-S3'],
        },
      ],
    },
    {
      id: 'U10-T2',
      title: 'Characters, user input and row output',
      sections: ['10.1'],
      skills: ['U10-S3', 'U10-S4'],
      explanation: [
        'Activity 1 is extended so the user enters the character to be displayed, how many characters per row and how many rows. Test it with a star (*), 50 per row and 20 rows.',
        'A further extension displays three identical blocks one under the other with a blank line between each block, which needs a third loop around the row loop.',
        'In Activity 2 (class Nested2) a loop of ten System.out.print("ABCDE") statements displays everything on one line. Changing to System.out.println("ABCDE") gives ten rows.',
        'Instead of displaying ABCDE as one String, an inner loop with a char loop control variable can generate the letters: for (char ch = \'A\'; ch <= \'E\'; ch++). Use print inside it and println() after it.',
        'The program can then ask the user for the number of rows and display the whole alphabet by changing the inner loop to end at \'Z\'.',
      ],
      vocabulary: [
        { term: 'System.out.print', definition: 'Displays output and leaves the cursor on the same line.' },
        { term: 'System.out.println', definition: 'Displays output and then moves the cursor to the beginning of the next line.' },
        { term: 'char loop control variable', definition: 'A loop control variable of type char, possible because characters are treated like numbers (their Unicode values) in Java.' },
      ],
      workedExamples: [
        {
          code: 'int rows = Integer.parseInt(JOptionPane.showInputDialog("How many rows?"));\nfor (int r = 1; r <= rows; r++)\n{\n   for (char ch = \'A\'; ch <= \'Z\'; ch++)\n   {\n      System.out.print(ch);\n   }\n   System.out.println();\n}',
          explanation: 'The user chooses the number of rows; each row shows the whole alphabet A to Z.',
        },
      ],
      misconceptions: [
        'Thinking print and println are interchangeable: inside the inner loop println breaks every character onto its own line.',
        'Thinking the number of rows must be fixed in the code: it can be a variable entered by the user and used as the termination value of the outer loop.',
      ],
      questions: [
        {
          id: 'U10-T2-Q1',
          type: 'mc',
          category: 'predict',
          prompt: 'The inner loop uses println instead of print. What is displayed?',
          code: 'for (int i = 1; i <= 10; i++)\n{\n   for (char ch = \'A\'; ch <= \'E\'; ch++)\n   {\n      System.out.println(ch);\n   }\n}',
          options: [
            'Every letter on its own line, A to E repeated 10 times down the screen',
            'Ten rows of ABCDE, one below the other',
            'One long row of ABCDE repeated ten times',
            'A compile error because ch is a char',
          ],
          answer: 0,
          hint: 'println moves to a new line after every single letter.',
          explanation: 'println(ch) is inside the inner loop, so all 50 letters are each on their own line. Use print(ch) in the inner loop and println() after it to get rows.',
          skills: ['U10-S3', 'U10-S4'],
        },
        {
          id: 'U10-T2-Q2',
          type: 'tf',
          category: 'apply',
          prompt: 'True or false: to display the whole alphabet on each row, the inner loop header can be for (char ch = \'A\'; ch <= \'Z\'; ch++).',
          answer: true,
          hint: 'Characters are compared by their Unicode values, and A to Z are consecutive.',
          explanation: 'A char loop control variable can run from \'A\' to \'Z\' with ch++, giving all 26 letters.',
          skills: ['U10-S4'],
        },
        {
          id: 'U10-T2-Q3',
          type: 'trace',
          category: 'calculate',
          prompt: 'In the worked example the user enters 4 rows. Type whole numbers.',
          code: 'for (int r = 1; r <= rows; r++)\n{\n   for (char ch = \'A\'; ch <= \'Z\'; ch++)\n   {\n      System.out.print(ch);\n   }\n   System.out.println();\n}',
          rows: [
            { label: 'Letters on each row', answer: '26' },
            { label: 'Total letters displayed', answer: '104' },
          ],
          hint: 'How many letters are in the alphabet?',
          explanation: 'Each row has the 26 letters A to Z, and 4 rows x 26 = 104 letters.',
          skills: ['U10-S4', 'U10-S2'],
        },
      ],
    },
    {
      id: 'U10-T3',
      title: 'Nested loops with the Gogga',
      sections: ['10.1', '10.2'],
      skills: ['U10-S5', 'U10-S2'],
      explanation: [
        'In Activity 3 an outer loop is added to MakeSquareWithLoop so the square is drawn in each of the four directions.',
        'The direction Gogga.UP is a named constant which corresponds to the value 1, Gogga.DOWN is 2, Gogga.LEFT is 3 and Gogga.RIGHT is 4.',
        'The loop control variable dir runs from 1 to 4. In the outer loop, before the inner loop, bug.setDirection(dir) sets the direction.',
        'The inner loop draws one square: for each of the 4 sides it moves twice and turns left. The program can be shown as a flowchart with one loop inside the other.',
        'In Activity 5 the two bug.move() statements are replaced with another for loop (for length 1 to 2) completely inside the sides loop. Saved as MakeSquareWithManyLoops, it then draws squares with sides five units long (length 1 to 5); you may have to change the grid size.',
      ],
      vocabulary: [
        { term: 'Named constant', definition: 'A name for a fixed value, e.g. Gogga.UP stands for 1.' },
        { term: 'setDirection', definition: 'Gogga method that sets the direction the Gogga faces, using a direction value as the parameter.' },
      ],
      workedExamples: [
        {
          code: 'Gogga bug = new Gogga();\n\nfor (int dir = 1; dir <= 4; dir++)\n{\n   bug.setDirection(dir);\n   for (int sides = 1; sides <= 4; sides++)\n   {\n      bug.move();\n      bug.move();\n      bug.turnLeft();\n   }\n}',
          explanation: 'Activity 3: a square with sides 2 units long drawn in all four directions, producing a block of squares.',
        },
      ],
      misconceptions: [
        'Thinking setDirection belongs inside the sides loop: then the bug would be reset every side and could not draw a square.',
        'Thinking replacing two move() calls with a loop of 2 moves changes the drawing: it draws the same square but is easier to change to longer sides.',
      ],
      questions: [
        {
          id: 'U10-T3-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'Which value does the named constant Gogga.DOWN correspond to?',
          options: ['1', '2', '3', '4'],
          answer: 1,
          hint: 'The order is UP, DOWN, LEFT, RIGHT.',
          explanation: 'Gogga.UP is 1, Gogga.DOWN is 2, Gogga.LEFT is 3 and Gogga.RIGHT is 4.',
          skills: ['U10-S5'],
        },
        {
          id: 'U10-T3-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'MakeSquareWithManyLoops with sides five units long draws ONE square. Type whole numbers.',
          code: 'for (int sides = 1; sides <= 4; sides++)\n{\n   for (int length = 1; length <= 5; length++)\n   {\n      bug.move();\n   }\n   bug.turnLeft();\n}',
          rows: [
            { label: 'Times move() is called', answer: '20' },
            { label: 'Times turnLeft() is called', answer: '4' },
          ],
          hint: 'turnLeft() is after the length loop, inside the sides loop.',
          explanation: 'move() runs 4 x 5 = 20 times; turnLeft() runs once per side, 4 times.',
          skills: ['U10-S5', 'U10-S2'],
        },
        {
          id: 'U10-T3-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: replacing bug.move(); bug.move(); with for (int length = 1; length <= 2; length++) { bug.move(); } changes the shape that is drawn.',
          answer: false,
          hint: 'How many times does the new loop call move()?',
          explanation: 'The loop calls move() twice, exactly like the two statements, so the same square is drawn. The loop just makes it easy to change the side length.',
          skills: ['U10-S5'],
        },
      ],
    },
    {
      id: 'U10-T4',
      title: 'Repeating a section inside another',
      sections: ['10.2'],
      skills: ['U10-S6', 'U10-S5'],
      explanation: [
        'Nested loops are very useful when a section must be repeated inside a bigger section which must be repeated itself. It is important to decide what must be repeated and where.',
        'In the Beatles song "She Loves You" the opening chorus is "She loves you, Yeah Yeah Yeah!" three times. The Yeah Yeah Yeah part of one line is a loop repeated three times: count = 1; count <= 3; count = count + 1.',
        'Before the inner loop, "She loves you, " is displayed; after it, "!" is displayed and the cursor moves to the next line. The whole line is then repeated three times in an outer loop (line = 1; line <= 3; line = line + 1).',
        'Nested loops can be represented by drawing one loop totally inside the other. Song1 codes this; Song2 (The wheels on the bus) and Song3 (Ooh watch me, watch me) use the same idea, with a last line displayed once after the outer loop.',
        'With the Gogga, MakeX uses one loop to draw the top right-hand zig zag spoke and an outer loop to repeat it in all four directions. FourPyramids uses three separate loops (zig zag up, zig zag down, base) inside an outer loop that rotates through the four directions.',
      ],
      vocabulary: [
        { term: 'Section', definition: 'A part of the output or task that must be repeated, e.g. Yeah inside one song line.' },
      ],
      workedExamples: [
        {
          code: 'for (int line = 1; line <= 3; line = line + 1)\n{\n   System.out.print("She loves you,");\n   for (int count = 1; count <= 3; count = count + 1)\n   {\n      System.out.print(" Yeah");\n   }\n   System.out.println("!");\n}',
          explanation: 'Song1: displays "She loves you, Yeah Yeah Yeah!" on three lines.',
        },
      ],
      misconceptions: [
        'Thinking every line of a song belongs inside the loop: a line that appears once at the end (like "All over town!") goes after the outer loop.',
      ],
      questions: [
        {
          id: 'U10-T4-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'For the Song1 worked example, type whole numbers.',
          code: 'for (int line = 1; line <= 3; line = line + 1)\n{\n   System.out.print("She loves you,");\n   for (int count = 1; count <= 3; count = count + 1)\n   {\n      System.out.print(" Yeah");\n   }\n   System.out.println("!");\n}',
          rows: [
            { label: 'Times "She loves you," is displayed', answer: '3' },
            { label: 'Times " Yeah" is displayed', answer: '9' },
          ],
          hint: 'One of these is in the outer loop only.',
          explanation: '"She loves you," is displayed once per line (3). " Yeah" is in the inner loop: 3 x 3 = 9.',
          skills: ['U10-S6'],
        },
        {
          id: 'U10-T4-Q2',
          type: 'mc',
          category: 'apply',
          prompt: 'Song3 must display "Ooh watch me, watch me" three times and then "Ooh ooh ooh ooh" once. Which plan is correct?',
          options: [
            'Put both lines inside one loop that runs 3 times',
            'Loop "Ooh ooh ooh ooh" 3 times, then display "Ooh watch me, watch me"',
            'Loop "Ooh watch me, watch me" 3 times, then display the last line once after the loop',
            'Use one loop of 4 that displays "Ooh watch me, watch me" each time',
          ],
          answer: 2,
          hint: 'Decide what must be repeated and where.',
          explanation: 'Only the first line repeats, so it goes in the loop. The last line is displayed once after the loop has ended.',
          skills: ['U10-S6'],
        },
        {
          id: 'U10-T4-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: in MakeX, a loop draws one zig zag spoke and an outer loop repeats the spoke in all four directions.',
          answer: true,
          hint: 'The X has four identical spokes pointing in different directions.',
          explanation: 'Exercise 2 Question 2 codes the top right-hand spoke in a for loop, then uses an outer loop to repeat it in all four directions.',
          skills: ['U10-S5', 'U10-S6'],
        },
      ],
    },
    {
      id: 'U10-T5',
      title: 'Nested loops for processing data',
      sections: ['10.2'],
      skills: ['U10-S7', 'U10-S2'],
      explanation: [
        'Exercise 2 Question 3 (StudentAverages): a class has five students and each takes three subjects. The outer loop handles each student (input the name) and the inner loop inputs the three marks out of 100.',
        'The total must be reset to 0 for each student inside the outer loop. The average is total / 3.0 so that integer division does not cut off the decimals.',
        'The class average is the average of all the averages. To find the student with the highest average, use the first student\'s average to set the variable that stores the highest average.',
        'Exercise 2 Question 5 (StockExchange): prices of shares are recorded twice daily, morning and evening. Percentage increase or decrease = (evening - morning) / morning x 100.',
        'Extending it to five days (Monday to Friday) needs a loop over the days; extending again to four shares (SA Brews, Stocks, Rainbow, Wooltru) puts the days loop inside a shares loop.',
        'Further extensions find the share with the highest % increase / decrease and the day it happened, and the share with the highest price, the day and whether it was a morning or evening price.',
      ],
      vocabulary: [
        { term: 'Average of averages', definition: 'The class average found by adding each student\'s average and dividing by the number of students.' },
        { term: 'Percentage increase / decrease', definition: '(evening price - morning price) / morning price x 100; a negative result is a decrease.' },
      ],
      workedExamples: [
        {
          code: 'int morning = 3500;\nint evening = 3475;\ndouble percent = 100.0 * (evening - morning) / morning;',
          explanation: 'Fregold test data: a change of -25 on 3500 gives about -0.71 percent, a decrease. Starting with 100.0 avoids integer division.',
        },
      ],
      misconceptions: [
        'Thinking the highest variable can safely start at 0 or 100: using the first item\'s value guarantees it starts as a real value from the data.',
        'Thinking total can be set to 0 once before the outer loop: then each student\'s total would include the previous students\' marks.',
      ],
      questions: [
        {
          id: 'U10-T5-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'Why should the variable that stores the highest average be set from the first student\'s average?',
          options: [
            'So it starts as a real average from the data, not a guessed value',
            'Because the first student always has the highest average',
            'Because Java does not allow a double variable to start at 0',
            'So that the loop runs one time fewer and finishes faster',
          ],
          answer: 0,
          hint: 'What if a guessed starting value were higher or lower than every real average?',
          explanation: 'Starting with the first real average means every later average is compared with an actual value from the data.',
          skills: ['U10-S7'],
        },
        {
          id: 'U10-T5-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'Wooltru on Wednesday: 2000 in the morning, 1950 in the evening. Type each value exactly as Java would print it.',
          code: 'int morning = 2000;\nint evening = 1950;\nint change = evening - morning;\ndouble percent = 100.0 * change / morning;',
          rows: [
            { label: 'change', answer: '-50' },
            { label: 'percent', answer: '-2.5' },
          ],
          hint: '100.0 * -50 first, then divide by 2000.',
          explanation: 'change is 1950 - 2000 = -50. 100.0 * -50 = -5000.0 and -5000.0 / 2000 = -2.5, a 2.5 percent decrease.',
          skills: ['U10-S7'],
        },
        {
          id: 'U10-T5-Q3',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: in StudentAverages the student loop is the outer loop and the subject loop is the inner loop.',
          answer: true,
          hint: 'Each student takes three subjects.',
          explanation: 'For each student (outer) you input three subject marks (inner), so the subject loop is nested inside the student loop.',
          skills: ['U10-S7'],
        },
        {
          id: 'U10-T5-Q4',
          type: 'mc',
          category: 'calculate',
          prompt: 'Exercise 2 Question 5.4 processes 4 shares for the five-day working week, with a morning and an evening price each day. How many prices are input?',
          options: ['20', '10', '45', '40'],
          answer: 3,
          hint: 'Shares x days x prices per day.',
          explanation: '4 shares x 5 days x 2 prices = 40 prices.',
          skills: ['U10-S7', 'U10-S2'],
        },
      ],
    },
    {
      id: 'U10-T6',
      title: 'More complex nested loops',
      sections: ['10.3'],
      skills: ['U10-S8', 'U10-S5'],
      explanation: [
        'In Activity 6, MakeSquareWithManyLoops has three levels of loops: directions (dir 1 to 4), sides (1 to 4) and length (1 to 5), on a grid set with Gogga.setGridSize(18, 18).',
        'Only small modifications produce three separate squares next to each other (Make3HorizSquares): change the grid to Gogga.setGridSize(20, 9), declare int x = 5 to store changing x values and use bug.setPosition(x, 7).',
        'The outer loop is changed to draw each of the squares, and its loop variable is renamed numSquares so it is more readable. After each square x = x + 6 moves the starting point of the next square right by 6 positions.',
        'The outer loop can be changed so its loop control variable itself determines the x position of the square.',
        'Make3DiagSquares displays the squares diagonally by introducing a y variable and changing its value after each square is drawn.',
        'Exercise 3 adapts ThickCross to show three crosses in a diagonal line, then makes them overlap with minimal changes (ThickCross2), and finally asks you to make your own shape with a loop and repeat it with another loop.',
      ],
      vocabulary: [
        { term: 'Gogga.setGridSize', definition: 'Sets the number of columns and rows of the Gogga grid, e.g. setGridSize(20, 9).' },
        { term: 'setPosition(x, y)', definition: 'Places the Gogga at column x and row y on the grid.' },
      ],
      workedExamples: [
        {
          code: 'Gogga.setGridSize(20, 9);\nGogga bug = new Gogga();\nint x = 5;\n\nfor (int numSquares = 1; numSquares <= 3; numSquares++)\n{\n   bug.setPosition(x, 7);\n   for (int sides = 1; sides <= 4; sides++)\n   {\n      for (int length = 1; length <= 5; length++)\n      {\n         bug.move();\n      }\n      bug.turnLeft();\n   }\n   x = x + 6;\n}',
          explanation: 'Make3HorizSquares: three squares with sides 5 long, starting at x = 5, 11 and 17.',
        },
      ],
      misconceptions: [
        'Thinking you need a new copy of the square code for every square: an outer loop with a changing position variable repeats the whole shape.',
        'Thinking x must change inside the length loop: it changes once per square, after the sides loop.',
      ],
      questions: [
        {
          id: 'U10-T6-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'In Make3HorizSquares, why is x = x + 6 placed after the sides loop?',
          options: [
            'So the square sides become 6 units long',
            'So the starting point of the next square moves 6 positions to the right',
            'So the bug turns to face a new direction after each square',
            'So the outer loop knows when it must stop repeating',
          ],
          answer: 1,
          hint: 'x is only used in bug.setPosition(x, 7).',
          explanation: 'x is the horizontal start position. Adding 6 after each square moves the next square 6 positions to the right.',
          skills: ['U10-S8'],
        },
        {
          id: 'U10-T6-Q2',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: Make3HorizSquares needs four levels of nested loops (squares, sides, length and moves).',
          answer: false,
          hint: 'Count the for loop headers in the worked example.',
          explanation: 'There are three levels: numSquares, sides and length. The move() call is the body of the length loop, not another loop.',
          skills: ['U10-S8'],
        },
        {
          id: 'U10-T6-Q3',
          type: 'trace',
          category: 'predict',
          prompt: 'Here the loop control variable determines the x position of each square. Type whole numbers.',
          code: 'for (int x = 5; x <= 17; x = x + 6)\n{\n   bug.setPosition(x, 7);\n   // draw one square here\n}',
          rows: [
            { label: 'Number of squares drawn', answer: '3' },
            { label: 'x for the second square', answer: '11' },
          ],
          hint: 'List the values of x: start at 5 and add 6 while x <= 17.',
          explanation: 'x takes the values 5, 11 and 17, so three squares are drawn. Then x becomes 23 and the loop ends.',
          skills: ['U10-S8', 'U10-S5'],
        },
      ],
    },
    {
      id: 'U10-T7',
      title: 'The outer loop controls the inner loop',
      sections: ['10.4', '10.4.1'],
      skills: ['U10-S9', 'U10-S4'],
      explanation: [
        'To print a triangle of 5 rows of stars (*, **, ***, ****, *****) we could write 5 println statements, but we want to use only one System.out.print("*") statement and loops.',
        'We need two loops: one to print the number of stars on each line and one to control each line. The inner loop always executes more than the outer loop, so the inner loop prints the stars on one line and the outer loop prints each line.',
        'Identify the pattern: line 1 has 1 star, line 2 has 2 stars and so on. When the outer loop is 1 the inner loop runs from 1 to 1, when it is 2 the inner loop runs from 1 to 2, up to 1 to 5.',
        'Pseudocode: for loop 1 to 5, for numStars 1 to loop, print "*", end for, go to a new line, end for. The loop control variable loop of the outer loop is the termination value of the inner loop.',
        'The inner loop control variable is dependent on the outer loop control variable. Previously the inner loop was independent of the outer loop, as there was no relation between the two.',
        'Activity 7 codes this as Stars1, then lets the user input the number of rows. Test with positive numbers, negative numbers and 0: for 0 or a negative number the outer loop does not execute, so nothing is printed.',
      ],
      vocabulary: [
        { term: 'Termination value', definition: 'The value in the loop condition that decides when the loop stops, e.g. loop in numStars <= loop.' },
        { term: 'Dependent inner loop', definition: 'An inner loop whose termination value is the outer loop control variable, so it runs a different number of times on each line.' },
      ],
      workedExamples: [
        {
          code: 'for (int loop = 1; loop <= 5; loop++)\n{\n   for (int numStars = 1; numStars <= loop; numStars++)\n   {\n      System.out.print("*");\n   }\n   System.out.println();\n}',
          explanation: 'Stars1: line loop has loop stars, giving a triangle of 1 to 5 stars and 15 stars altogether.',
        },
      ],
      misconceptions: [
        'Thinking the inner loop must always run a fixed number of times: its termination value can be the outer loop control variable.',
        'Thinking a negative number of rows crashes the program: the outer loop condition is false at once, so the loop simply does not execute.',
      ],
      questions: [
        {
          id: 'U10-T7-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'What does it mean that the inner loop is dependent on the outer loop?',
          options: [
            'The outer loop control variable is the termination value of the inner loop',
            'The inner loop runs the same number of times on every line',
            'The inner loop control variable is declared before the outer loop',
            'The outer loop stops as soon as the inner loop stops',
          ],
          answer: 0,
          hint: 'Look at numStars <= loop.',
          explanation: 'In Stars1 the inner loop runs from 1 to loop, so how many times it runs depends on the outer loop control variable.',
          skills: ['U10-S9'],
        },
        {
          id: 'U10-T7-Q2',
          type: 'trace',
          category: 'predict',
          prompt: 'Stars1 lets the user enter the number of rows. Type whole numbers.',
          code: 'int rows = Integer.parseInt(JOptionPane.showInputDialog("Rows?"));\nfor (int loop = 1; loop <= rows; loop++)\n{\n   for (int numStars = 1; numStars <= loop; numStars++)\n   {\n      System.out.print("*");\n   }\n   System.out.println();\n}',
          rows: [
            { label: 'Stars on the last line when rows = 6', answer: '6' },
            { label: 'Total stars when rows = 6', answer: '21' },
            { label: 'Total stars when rows = -3', answer: '0' },
          ],
          hint: 'For 6 rows add 1 + 2 + ... + 6. For -3, is 1 <= -3?',
          explanation: '6 rows give 1 + 2 + 3 + 4 + 5 + 6 = 21 stars with 6 on the last line. For -3 the outer condition 1 <= -3 is false, so nothing is printed.',
          skills: ['U10-S9', 'U10-S4'],
        },
        {
          id: 'U10-T7-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'True or false: the inner loop always executes more than the outer loop, so it is used to print the stars on one line.',
          answer: true,
          hint: 'Which loop prints individual stars and which handles whole lines?',
          explanation: 'The textbook uses the inner loop (which executes more) for the stars on one line and the outer loop for each line.',
          skills: ['U10-S9'],
        },
      ],
    },
    {
      id: 'U10-T8',
      title: 'A more complex set of stars',
      sections: ['10.4.2'],
      skills: ['U10-S10', 'U10-S9'],
      explanation: [
        'The goal is a centred triangle where each line has an odd number of stars starting from 1: 4 spaces 1 star, 3 spaces 3 stars, 2 spaces 5 stars, 1 space 7 stars, 0 spaces 9 stars.',
        'Break the problem down: first ignore the spaces and print the stars on the margin. The number of stars per line is 1, 3, 5, 7, 9: the odd numbers in relation to the integers 1 to 5.',
        'The odd number generator 2n - 1 (n = 1, 2, 3, ...) gives 1, 3, 5, ... So the termination value of the inner loop is 2*loop - 1 when the outer loop control variable is called loop (Activity 8, Stars2).',
        'Spaces: the number of spaces and the line number always add up to 5, so the number of spaces is 5 - loop. A second inner loop, BEFORE the star loop, prints the spaces.',
        'On the last line loop is 5 and 5 - loop is 0, so the header becomes for (int numSpaces = 1; numSpaces <= 0; numSpaces++). The loop does NOT execute as 0 is less than 1, so no spaces are printed, which is what we want.',
        'Exercise 4 extends this to a triangle that grows then shrinks, a diamond, three triangles next to each other and a hollow triangle with a solid base.',
      ],
      vocabulary: [
        { term: 'Odd number generator', definition: 'The standard formula 2n - 1 where n is an integer 1, 2, 3, ..., giving 1, 3, 5, ...' },
        { term: 'Two inner loops', definition: 'Two loops one after the other inside the same outer loop, e.g. one for spaces then one for stars.' },
      ],
      workedExamples: [
        {
          code: 'for (int loop = 1; loop <= 5; loop++)\n{\n   for (int numSpaces = 1; numSpaces <= 5 - loop; numSpaces++)\n   {\n      System.out.print(" ");\n   }\n   for (int numStars = 1; numStars <= 2 * loop - 1; numStars++)\n   {\n      System.out.print("*");\n   }\n   System.out.println();\n}',
          explanation: 'The final triangle of stars: 5 - loop spaces then 2 * loop - 1 stars on each line, 25 stars in total.',
        },
      ],
      misconceptions: [
        'Thinking the space loop must be nested inside the star loop: the two inner loops run one after the other inside the outer loop.',
        'Thinking a loop with termination value 0 runs once: numSpaces starts at 1, and 1 <= 0 is false, so it runs zero times.',
      ],
      questions: [
        {
          id: 'U10-T8-Q1',
          type: 'mc',
          category: 'calculate',
          prompt: 'Using the odd number generator 2n - 1, how many stars are on line 7 of a bigger triangle?',
          options: ['14', '15', '13', '12'],
          answer: 2,
          hint: 'Multiply by 2 first, then subtract 1.',
          explanation: '2 x 7 - 1 = 13 stars.',
          skills: ['U10-S10'],
        },
        {
          id: 'U10-T8-Q2',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the pseudocode of the final triangle in order.',
          items: [
            'print "*" in an inner loop from 1 to 2*loop - 1',
            'go to a new line',
            'for loop 1 to 5 (the outer loop starts)',
            'print " " in an inner loop from 1 to 5 - loop',
          ],
          answer: [2, 3, 0, 1],
          hint: 'The spaces come before the stars on each line.',
          explanation: 'Inside the outer loop, the space loop runs first, then the star loop, then the cursor moves to a new line.',
          skills: ['U10-S10'],
        },
        {
          id: 'U10-T8-Q3',
          type: 'tf',
          category: 'predict',
          prompt: 'True or false: on line 5 of the 5-line centred triangle, the space loop runs once and prints one space.',
          answer: false,
          hint: 'Work out 5 - loop when loop is 5.',
          explanation: '5 - 5 = 0, and the header numSpaces <= 0 is false from the start, so the space loop does not execute.',
          skills: ['U10-S10'],
        },
        {
          id: 'U10-T8-Q4',
          type: 'trace',
          category: 'calculate',
          prompt: 'Exercise 4 1.2 is a diamond: lines of 1, 3, 5, 7, 9, 7, 5, 3, 1 stars. Type whole numbers.',
          code: '    *\n   ***\n  *****\n *******\n*********\n *******\n  *****\n   ***\n    *',
          rows: [
            { label: 'Number of lines', answer: '9' },
            { label: 'Total stars in the diamond', answer: '41' },
          ],
          hint: 'The top half is the 25-star triangle. Add the bottom half.',
          explanation: 'The top 5 lines have 25 stars and the bottom 4 lines have 7 + 5 + 3 + 1 = 16, so 41 stars on 9 lines.',
          skills: ['U10-S10', 'U10-S9'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 'u10-stadium-card-stunt',
    unitId: UNIT.id,
    title: 'Stadium Card Stunt',
    icon: 'zap',
    summary: 'Rebuild the crowd-card pattern program before kick-off.',
    briefing: 'The Springboks run out at Ellis Park in four minutes and the crowd-card display program is printing garbage. Every row of the giant star pattern must be rebuilt with nested loops before 60 000 fans hold up the wrong cards on live TV.',
    tickerMessages: [
      'Card display rehearsal fails: the star triangle comes out as a square.',
      'Stadium technicians report every card printed on its own line.',
      'Broadcasters warn the half-time pattern could be upside down.',
      'Coach asks: who put println inside the inner loop?',
      'Two minutes to kick-off: the centred triangle still has no spaces.',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['U10-S1', 'U10-S2', 'U10-S3', 'U10-S9', 'U10-S10'],
    victoryMessage: 'The crowd lifts the cards and a perfect star triangle fills the stand. Ellis Park roars.',
    failMessage: 'The cards go up in a jumbled mess and the cameras catch it all. Recount those loops and try again.',
  },
  {
    id: 'u10-jse-night-shift',
    unitId: UNIT.id,
    title: 'JSE Night Shift',
    icon: 'briefcase',
    summary: 'Process five days of share prices before the market opens.',
    briefing: 'The Johannesburg Stock Exchange report program crashed overnight. Every share needs its morning and evening prices processed day by day with nested loops, and the % change report must reach the traders by 09:00.',
    tickerMessages: [
      'Overnight report missing: traders arrive to blank screens.',
      'Analysts spot every share showing a 0 percent change. Integer division suspected.',
      'Rumour: Stocks jumped 6.25 percent on Wednesday, but nobody can confirm it.',
      'The highest-average routine started at 0 and named the wrong winner.',
      'Market opens in five minutes. The days loop is still not inside the shares loop.',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['U10-S2', 'U10-S6', 'U10-S7', 'U10-S8'],
    victoryMessage: 'The report lands on every trader\'s desk at 08:59. The JSE opens on time.',
    failMessage: 'The market opens blind and the phones go wild. Check which loop is outside which and run it again.',
  },
];
