// Learning Unit 12: Databases and SQL (Exploring IT: Java Programming Grade 10, 3rd ed)
import { Database } from 'lucide-react';

const COMRADES = [
  'tblComrades (sample rows)',
  'ID | RaceYear | WinName          | Gender | WinTime  | Country',
  '---+----------+------------------+--------+----------+-------------',
  '1  | 1990     | Naidene Harrison | F      | 07:02:00 | South Africa',
  '2  | 1991     | Andile Zulu      | M      | 05:41:10 | South Africa',
  '3  | 1992     | Olga Petrova     | F      | 06:51:05 | Russia',
  '4  | 1993     | Klaus Becker     | M      | 05:39:41 | Germany',
  '5  | 1994     | Beata Nowak      | F      | 06:41:23 | Poland',
  '6  | 1995     | Ivan Sokolov     | M      | 05:34:22 | Russia',
  '7  | 1996     | Elize Steyn      | F      | 06:28:40 | South Africa',
  '8  | 1997     | Ben Carter       | M      | 05:28:37 | USA',
  '9  | 1998     | Ivan Sokolov     | M      | 05:31:05 | Russia',
].join('\n');

const CLUBS = [
  'tblComrades (sample rows, a blank Club cell is NULL)',
  'ID | WinName          | Club',
  '---+------------------+-------------',
  '1  | Naidene Harrison | LadySmith AC',
  '2  | Andile Zulu      |',
  '3  | Olga Petrova     | Unknown',
  '4  | Klaus Becker     |',
  '5  | Beata Nowak      | Warsaw RC',
  '6  | Ben Carter       | Boston AC',
].join('\n');

const STUDENTS = [
  'tblStudent',
  'Name     | Class | House',
  '---------+-------+------',
  'Rachael  | B     | Blue',
  'Samuel   | C     | Red',
  'Thabo    | C     | Red',
  'Jermaine | B     | Blue',
  'Susanna  | A     | Blue',
  'Jason    | B     | Red',
  'Nelson   | C     | Blue',
  'Fatima   | A     | Red',
  'Sipho    | A     | Red',
].join('\n');

export const UNIT = { id: 'U12', number: 12, name: 'Databases and SQL', worldId: 'databases-sql' };

export const SKILLS = {
  'U12-S1': { unit: 'U12', name: 'Databases and DBMSs', description: 'Define a database, a relational database and a DBMS, and compare MS Access, MySQL and Java DB.', sections: ['12.1'] },
  'U12-S2': { unit: 'U12', name: 'Fields, records and keys', description: 'Explain fields, records, tables, databases, schemas and primary keys.', sections: ['12.2', '12.2.1', '12.2.2'] },
  'U12-S3': { unit: 'U12', name: 'Table design in MS Access', description: 'Design an MS Access table using Design view, naming conventions, field properties, Required and Indexed.', sections: ['12.3', '12.3.1'] },
  'U12-S4': { unit: 'U12', name: 'Choosing data types', description: 'Choose the most efficient MS Access or Java DB data type for a field and justify its range.', sections: ['12.3.1', '12.3.2', '12.3.4'] },
  'U12-S5': { unit: 'U12', name: 'Tables in Java DB', description: 'Create, connect to and populate a Java DB database in NetBeans using CREATE TABLE.', sections: ['12.3.3', '12.3.4', '12.5.2'] },
  'U12-S6': { unit: 'U12', name: 'Creating queries', description: 'Create and run queries with MS Access Query Design, SQL View and the Java DB Execute Command window.', sections: ['12.4', '12.4.1', '12.4.2', '12.4.3', '12.5', '12.5.1', '12.5.2'] },
  'U12-S7': { unit: 'U12', name: 'SELECT fields and ORDER BY', description: 'Limit the fields in a SELECT query and sort the results on one or more fields with ASC and DESC.', sections: ['12.6', '12.6.1', '12.6.2', '12.9'] },
  'U12-S8': { unit: 'U12', name: 'WHERE conditions', description: 'Filter records with WHERE and the comparison operators, using the correct quotes and # symbols.', sections: ['12.6.3', '12.9'] },
  'U12-S9': { unit: 'U12', name: 'NOT, AND and OR', description: 'Build compound conditions with NOT, AND and OR and apply the order of operations.', sections: ['12.6.4', '12.6.4.1', '12.6.4.2', '12.6.4.3', '12.9'] },
  'U12-S10': { unit: 'U12', name: 'BETWEEN, IN, NULL and LIKE', description: 'Use BETWEEN...AND, IN, IS NULL, IS NOT NULL and LIKE with the correct wildcard characters.', sections: ['12.6.5', '12.6.5.1', '12.6.5.2', '12.6.5.3', '12.6.5.4', '12.9'] },
  'U12-S11': { unit: 'U12', name: 'DISTINCT and TOP n', description: 'Remove duplicates with DISTINCT and limit results with TOP n or FETCH FIRST n ROWS ONLY.', sections: ['12.7', '12.7.1', '12.7.2', '12.9'] },
  'U12-S12': { unit: 'U12', name: 'INSERT, DELETE and UPDATE', description: 'Edit table data with INSERT INTO, DELETE FROM and UPDATE ... SET, always with a careful WHERE.', sections: ['12.8', '12.8.1', '12.8.1.1', '12.8.1.2', '12.8.2', '12.8.3', '12.8.4', '12.9'] },
};

export const SKILL_HINTS = {
  'U12-S1': 'Database = a collection of related information about a subject organised in a useful manner; relational DB links tables by a common field; DBMS creates, controls, gives access to and manages data, avoids duplication, keeps data consistent and reliable; MS Access is proprietary for Windows, MySQL is open source for commercial use; Java DB comes with NetBeans',
  'U12-S2': 'Field = single data item (a column), record = collection of fields (a row), table = collection of records, database = collection of tables, primary key uniquely identifies each record; schema = logical design of the database',
  'U12-S3': 'MS Access: Datasheet view shows data, Design view defines field names and data types; prefixes tbl, qry, frm, rpt; one-word UpperCamelCase field names; avoid reserved words Year, Time, Name (RaceYear, WinTime, WinName); Required = may not be Null; Indexed speeds searching and sorting but slows updating',
  'U12-S4': 'MS Access: Byte 0 to 255 (1 byte), Integer -32768 to 32767 (2 bytes), Long Integer about -2 billion to 2 billion (4 bytes), Double and Currency 8 bytes, Short Text up to 255 chars, Long Text up to 64 000, Yes/No 0 false -1 true; Java DB: SMALLINT, INTEGER, DOUBLE, VARCHAR (up to 32 672), TIMESTAMP, DATE, TIME, BOOLEAN',
  'U12-S5': 'Java DB in NetBeans: Services tab, Start Server, Create Database, Connect, Tables folder, Execute Command, Run SQL; CREATE TABLE with ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1); View Data and Insert Record(s); field names shown in capitals',
  'U12-S6': 'SQL = Structured Query Language; a query searches or extracts data based on criteria; MS Access Query Design, save as qryALL, Run (!), SQL View shows SELECT tblComrades.* FROM tblComrades; the * wild card means all fields; Java DB uses Execute Command and Run SQL',
  'U12-S7': 'SELECT RaceYear, WinName FROM tblComrades limits fields; ORDER BY sorts ascending (ASC) by default, DESC reverses; ORDER BY Country, WinName sorts on a second field within the first; ORDER BY is always the last clause',
  'U12-S8': 'WHERE <condition> with =, <>, <, >, <=, >=; text values in single quotes; MS Access times in # symbols (#6:30:00#), Java DB times in single quotes; MS Access data is not case sensitive, Java DB is case sensitive',
  'U12-S9': 'NOT returns records that satisfy the negative of the condition, AND needs BOTH conditions true, OR needs EITHER condition true; order of operations: Brackets, NOT, AND, OR',
  'U12-S10': 'BETWEEN 1995 AND 1999 includes both end values; IN (1992, 1998) checks a set of values, NOT IN excludes them; IS NULL / IS NOT NULL (NULL means no data, not 0 or empty string); LIKE uses * in MS Access and % in Java DB for one, none or many characters',
  'U12-S11': 'SELECT DISTINCT WinName removes duplicates (works best on one field); MS Access TOP n goes after SELECT, Java DB FETCH FIRST n ROWS ONLY goes at the end; use ORDER BY WinTime for the best, ORDER BY WinTime DESC for the worst',
  'U12-S12': 'INSERT INTO table (fields) VALUES (values) in the same order, left-out fields get NULL, auto number ID is left out; INSERT without a field list needs ALL fields; DELETE FROM table WHERE ... (no WHERE deletes all records); UPDATE table SET field = value WHERE ... (no WHERE changes all records)',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'The Query Vault',
  subtitle: 'Unit 12 \u00b7 Databases and SQL',
  color: 'rose',
  glow: 'ja-glow-rose',
  bg: 'ja-w-databases-sql',
  icon: Database,
  blurb: 'Design tables, then make the data talk: SELECT, WHERE, ORDER BY, LIKE and friends. Finish by inserting, updating and deleting records without wrecking the Comrades Marathon database.',
};

export const LEVELS = [
  { id: 'u12-l1', name: 'Data Foundations', subtitle: 'Databases, DBMSs, fields, records, keys and data types', challengeIds: ['u12-c1', 'u12-c2', 'u12-c3', 'u12-c4', 'u12-c5', 'u12-c6', 'u12-c7'] },
  { id: 'u12-l2', name: 'Query Quarry', subtitle: 'Running queries, choosing fields, sorting and WHERE', challengeIds: ['u12-c8', 'u12-c9', 'u12-c10', 'u12-c11', 'u12-c12', 'u12-c13', 'u12-c14'] },
  { id: 'u12-l3', name: 'Filter Fortress', subtitle: 'NOT, AND, OR, BETWEEN, IN, LIKE, NULL, DISTINCT and TOP', challengeIds: ['u12-c15', 'u12-c16', 'u12-c17', 'u12-c18', 'u12-c19', 'u12-c20', 'u12-c21'] },
  { id: 'u12-l4', name: 'Boss: The Data Editor', subtitle: 'INSERT, DELETE, UPDATE and a mixed review of the unit', challengeIds: ['u12-c22', 'u12-c23', 'u12-c24', 'u12-c25', 'u12-c26'] },
];

export const CHALLENGES = {
  'u12-c1': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'According to the textbook, what is a Database Management System (DBMS)?',
    options: [
      'A single table that stores all the records about one subject',
      'The language used to write queries such as SELECT and UPDATE',
      'A set of programs used to create, control, provide access to and manage the data in a database',
      'A field that uniquely identifies each record in a table',
    ],
    answer: 2,
    hint: 'Think of the software that looks after the database, not the data or the language.',
    explanation: 'A DBMS is a set of programs used to create the database, control it, provide access to it and manage the data within it. MS Access and MySQL are examples; SQL is the language, a table holds records and a primary key identifies a record.',
    skills: ['U12-S1'],
  },
  'u12-c2': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Match each database term to its textbook description.',
    pairs: [
      { left: 'Field', right: 'Stores a single data item (a column)' },
      { left: 'Record', right: 'A collection of fields about one item (a row)' },
      { left: 'Table', right: 'A collection of records' },
      { left: 'Database', right: 'A collection of tables' },
      { left: 'Primary key', right: 'Uniquely identifies a record' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Build up from the smallest piece: one item, then a row, then many rows, then many tables.',
    explanation: 'A field stores a single data item, a record is a collection of fields, a table is a collection of records and a database is a collection of tables. A primary key uniquely identifies each record.',
    skills: ['U12-S2'],
  },
  'u12-c3': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: MS Access is open source software designed for commercial use on many operating systems.',
    answer: false,
    hint: 'One of MS Access and MySQL is proprietary and made for Windows.',
    explanation: 'MS Access is proprietary software developed for Windows and is not designed for commercial use. MySQL is the open source DBMS designed for commercial use and multiple operating systems.',
    skills: ['U12-S1'],
  },
  'u12-c4': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Following the textbook\'s MS Access naming convention, which is the best name for a query that shows only South African winners?',
    options: ['qrySA', 'tblSA', 'rptSA', 'frmSA'],
    answer: 0,
    hint: 'Each object type has its own three-letter prefix.',
    explanation: 'The prefix tells you the type of object: tbl (table), qry (query), frm (form) and rpt (report). A query that shows South African winners is named qrySA, as in Activity 11.',
    skills: ['U12-S3'],
  },
  'u12-c5': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Which MS Access Number data type stores ages in the range 0 to 100 using the least memory?',
    options: ['Integer', 'Long Integer', 'Double', 'Byte'],
    answer: 3,
    hint: 'Find the smallest type whose range still includes 0 to 100.',
    explanation: 'A Byte stores integers from 0 to 255 in one byte, which covers 0 to 100. Integer (2 bytes), Long Integer (4 bytes) and Double (8 bytes) would all waste memory.',
    skills: ['U12-S4'],
  },
  'u12-c6': {
    type: 'match', world: UNIT.worldId,
    prompt: 'The Java DB CREATE TABLE statement for TBLCOMRADES uses these data types. Match each type to the field it was chosen for.',
    pairs: [
      { left: 'SMALLINT', right: 'RACEYEAR: a year, an integer from -32768 to 32767' },
      { left: 'BOOLEAN', right: 'UPDOWN: only two values, uphill (true) or downhill (false)' },
      { left: 'TIME', right: 'WINTIME: a winning time such as 07:02:00' },
      { left: 'VARCHAR(50)', right: 'WINNAME: text of at most 50 characters' },
      { left: 'INTEGER', right: 'ID: the auto-numbered primary key' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Look at what kind of value each field holds: a small whole number, two values, a time, text or a growing counter.',
    explanation: 'RaceYear stores a year so it can be a SMALLINT, UpDown needs only two values so it is a BOOLEAN, WinTime is a TIME, text fields are VARCHAR with the maximum length in brackets, and the ID is an INTEGER primary key.',
    skills: ['U12-S4', 'U12-S5'],
  },
  'u12-c7': {
    type: 'code-read', world: UNIT.worldId,
    prompt: 'What does the ID line in this Java DB statement set up?',
    code: 'CREATE TABLE TBLCOMRADES\n(\n    ID INTEGER NOT NULL PRIMARY KEY\n        GENERATED ALWAYS AS IDENTITY\n        (START WITH 1, INCREMENT BY 1),\n    RACEYEAR SMALLINT,\n    UPDOWN BOOLEAN,\n    WINNAME VARCHAR(50),\n    WINTIME TIME,\n    GENDER VARCHAR(1),\n    CLUB VARCHAR(50),\n    COUNTRY VARCHAR(50)\n)',
    options: [
      'An ID that you must type in yourself for every new record',
      'An integer primary key that starts at 1 and increases by 1 automatically for each new record',
      'An ID field that may be left empty (NULL) for some records',
      'An index on RACEYEAR so that searches on the year run faster',
    ],
    answer: 1,
    hint: 'Read START WITH and INCREMENT BY carefully, and notice NOT NULL.',
    explanation: 'The ID field is set to an integer primary key that starts at 1 and automatically increases. That is why the ID shows <GENERATED> when you insert a record in NetBeans and you cannot enter a value.',
    skills: ['U12-S5', 'U12-S2'],
  },
  'u12-c8': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: Indexing a field speeds up searching and sorting on that field, but can slow down updating it.',
    answer: true,
    hint: 'Think of the index at the back of a book. What happens to it when the content changes?',
    explanation: 'The DBMS keeps a structure like the index at the back of a book to speed up searching and sorting. When the data changes, the index must change too, so editing becomes slower.',
    skills: ['U12-S3'],
  },
  'u12-c9': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'This statement appears in SQL View for the query qryALL. What does the * mean?',
    code: 'SELECT tblComrades.*\nFROM tblComrades;',
    options: [
      'Multiply the values of the fields together',
      'Only the first field of the table is shown',
      'It is a wild card meaning all the fields in tblComrades',
      'Only the fields that contain no NULL values are shown',
    ],
    answer: 2,
    hint: 'In the Query Design window you double-clicked the star to choose fields.',
    explanation: 'In tblComrades.* the * is a wild card indicating that all the fields are required from tblComrades. SELECT * FROM tblComrades; gives the same result.',
    skills: ['U12-S6'],
  },
  'u12-c10': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'You are connected to the comrades1 database in NetBeans. Which option do you choose (after right-clicking the table or the Tables folder) to open a window where you can type and run SQL statements?',
    options: ['Start Server', 'Connect', 'View Data', 'Execute Command'],
    answer: 3,
    hint: 'You want to run a command, not look at the rows.',
    explanation: 'Execute Command opens the window where SQL is typed; then you click Run SQL. Start Server and Connect are earlier steps, and View Data shows the rows with a ready-made select statement.',
    skills: ['U12-S6', 'U12-S5'],
  },
  'u12-c11': {
    type: 'order', world: UNIT.worldId,
    prompt: 'Put the clauses of this SQL query in the correct order.',
    items: ['ORDER BY WinName;', 'FROM tblComrades', 'WHERE Country = \'South Africa\'', 'SELECT WinName, RaceYear'],
    answer: [3, 1, 2, 0],
    hint: 'Say what you want, where it comes from, which rows, and then how to sort.',
    explanation: 'A query starts with SELECT <fields>, then FROM <table>, then WHERE <condition>. ORDER BY must always be the last clause in a query.',
    skills: ['U12-S7', 'U12-S8'],
  },
  'u12-c12': {
    type: 'code-read', world: UNIT.worldId,
    prompt: 'Using the sample table, which WinName is shown in the FIRST row of the result?',
    code: `${COMRADES}\n\nSELECT *\nFROM tblComrades\nORDER BY Country, WinName;`,
    options: ['Andile Zulu', 'Klaus Becker', 'Ben Carter', 'Naidene Harrison'],
    answer: 1,
    hint: 'The records are sorted on Country first; WinName only decides ties within a country.',
    explanation: 'Country is sorted first in ascending order, and Germany comes before Poland, Russia, South Africa and USA. Klaus Becker is the only German winner, so he is first.',
    skills: ['U12-S7'],
  },
  'u12-c13': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'Using the sample table, type how many rows each MS Access query returns (a whole number).',
    code: `${COMRADES}\n\nQuery A: SELECT * FROM tblComrades WHERE RaceYear > 1994;\nQuery B: SELECT * FROM tblComrades WHERE WinTime < #6:00:00#;\nQuery C: SELECT * FROM tblComrades WHERE Country = 'South Africa';\nQuery D: SELECT * FROM tblComrades WHERE Gender <> 'M';`,
    rows: [
      { label: 'Query A: number of rows', answer: '4' },
      { label: 'Query B: number of rows', answer: '5' },
      { label: 'Query C: number of rows', answer: '3' },
      { label: 'Query D: number of rows', answer: '4' },
    ],
    hint: 'Check each row against the condition. <> means "not equal to", and 1994 itself is not greater than 1994.',
    explanation: 'A: 1995 to 1998 gives 4 rows. B: the five male times all start with 05, so 5 rows. C: Naidene Harrison, Andile Zulu and Elize Steyn give 3 rows. D: Gender not M leaves the 4 female winners.',
    skills: ['U12-S8'],
  },
  'u12-c14': {
    type: 'error-spot', world: UNIT.worldId,
    prompt: 'This MS Access query should list only the South African winners. What is wrong with it?',
    code: 'SELECT *\nFROM tblComrades\nWHERE Country = South Africa;',
    options: [
      'The text value must be enclosed in single quotes: \'South Africa\'',
      'The WHERE clause must come before the FROM clause',
      'The = operator cannot be used with text fields, only LIKE can',
      'Text values must be surrounded by # symbols',
    ],
    answer: 0,
    hint: 'How does SQL tell the difference between a field name and a piece of text?',
    explanation: 'Text values in a condition must be enclosed in single quotes: WHERE Country = \'South Africa\'. The # symbols are used for Date/Time values in MS Access.',
    skills: ['U12-S8'],
  },
  'u12-c15': {
    type: 'code-read', world: UNIT.worldId,
    prompt: 'Using the sample table, which winner(s) does this query return?',
    code: `${COMRADES}\n\nSELECT *\nFROM tblComrades\nWHERE Gender = 'M' AND Country = 'South Africa';`,
    options: [
      'Naidene Harrison, Andile Zulu and Elize Steyn',
      'All five rows for the male winners',
      'No rows, because no winner is both male and South African',
      'Andile Zulu only',
    ],
    answer: 3,
    hint: 'With AND, a record is returned only if it satisfies BOTH conditions.',
    explanation: 'AND needs both conditions to be true. The South African winners are Naidene Harrison, Andile Zulu and Elize Steyn, and of those only Andile Zulu is male.',
    skills: ['U12-S9'],
  },
  'u12-c16': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'Using the sample table, type how many rows each query returns (a whole number).',
    code: `${COMRADES}\n\nQuery A: SELECT * FROM tblComrades WHERE NOT (Country = 'Russia');\nQuery B: SELECT * FROM tblComrades WHERE Gender = 'F' OR Country = 'USA';\nQuery C: SELECT * FROM tblComrades WHERE RaceYear BETWEEN 1992 AND 1995;\nQuery D: SELECT * FROM tblComrades WHERE RaceYear IN (1990, 1993, 1997);`,
    rows: [
      { label: 'Query A: number of rows', answer: '6' },
      { label: 'Query B: number of rows', answer: '5' },
      { label: 'Query C: number of rows', answer: '4' },
      { label: 'Query D: number of rows', answer: '3' },
    ],
    hint: 'NOT flips the condition, OR needs either part true, BETWEEN includes both end values, IN checks a list.',
    explanation: 'A: 3 Russian rows are excluded, leaving 6. B: 4 female winners plus Ben Carter from the USA gives 5. C: 1992, 1993, 1994 and 1995 gives 4 because BETWEEN is inclusive. D: 1990, 1993 and 1997 gives 3.',
    skills: ['U12-S9', 'U12-S10'],
  },
  'u12-c17': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'This MS Access condition finds winners whose names start with A: WHERE WinName LIKE \'A*\'. How is it written in Java DB?',
    options: [
      'WHERE WinName LIKE \'A?\'',
      'WHERE WinName = \'A*\'',
      'WHERE WinName LIKE \'A%\'',
      'WHERE WinName LIKE \'%A\'',
    ],
    answer: 2,
    hint: 'Java DB uses a different wildcard character, but it still goes after the A.',
    explanation: 'In Java DB the % character is used instead of *. The wildcard can replace one, none or many characters, so \'A%\' matches any name starting with A; \'%A\' would match names ending in A.',
    skills: ['U12-S10'],
  },
  'u12-c18': {
    type: 'code-read', world: UNIT.worldId,
    prompt: 'Using the sample table, which names does this query return?',
    code: `${CLUBS}\n\nSELECT WinName\nFROM tblComrades\nWHERE Club IS NULL;`,
    options: [
      'Andile Zulu and Klaus Becker',
      'Andile Zulu, Olga Petrova and Klaus Becker',
      'Olga Petrova only',
      'No rows, because NULL is the same as an empty string',
    ],
    answer: 0,
    hint: 'Is the text Unknown "no data", or is it data?',
    explanation: 'NULL means the data does not exist. Andile Zulu and Klaus Becker have no club value, so they are NULL. Olga Petrova\'s club is the text Unknown, which is real data, so it is not NULL.',
    skills: ['U12-S10'],
  },
  'u12-c19': {
    type: 'code-read', world: UNIT.worldId,
    prompt: 'Using the sample table, how many rows does this query return?',
    code: `${COMRADES}\n\nSELECT DISTINCT Country\nFROM tblComrades;`,
    options: ['9', '5', '3', '6'],
    answer: 1,
    hint: 'DISTINCT shows each different value only once.',
    explanation: 'DISTINCT removes duplicates. The different countries are South Africa, Russia, Germany, Poland and USA, so 5 rows are shown instead of 9.',
    skills: ['U12-S11'],
  },
  'u12-c20': {
    type: 'order', world: UNIT.worldId,
    prompt: 'Put the lines of this Java DB query (the top 3 male winners on time) in the correct order.',
    items: ['FETCH FIRST 3 ROWS ONLY;', 'FROM tblComrades', 'ORDER BY WinTime', 'SELECT WinName, WinTime', 'WHERE Gender = \'M\''],
    answer: [3, 1, 4, 2, 0],
    hint: 'In Java DB the "first n rows" part comes after the sorting.',
    explanation: 'SELECT, FROM and WHERE come first, then ORDER BY WinTime sorts fastest to slowest. In Java DB, FETCH FIRST 3 ROWS ONLY goes at the very end; in MS Access you would write TOP 3 straight after SELECT instead.',
    skills: ['U12-S11'],
  },
  'u12-c21': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: In MS Access, SELECT TOP 1 WinName FROM tblComrades ORDER BY WinTime DESC; returns the winner with the slowest (longest) winning time.',
    answer: true,
    hint: 'There is no opposite of TOP in SQL. What does DESC do to the list?',
    explanation: 'DESC sorts the times from longest to shortest, so TOP 1 now picks the slowest winner. The book explains that there is no word that is the opposite of TOP; you reverse the sort instead.',
    skills: ['U12-S11'],
  },
  'u12-c22': {
    type: 'error-spot', world: UNIT.worldId,
    prompt: 'Why will this MS Access statement not work on tblComrades (fields ID, RaceYear, UpDown, WinTime, WinName, Gender, Club, Country)?',
    code: 'INSERT INTO tblComrades\nVALUES (1989, False, #5:35:41#, \'Samuel Tshabalala\', \'M\', \'South Africa\');',
    options: [
      'Text values may not be placed in single quotes in an INSERT statement',
      'INSERT INTO can only be used in Java DB, not in MS Access',
      'The time must be in single quotes in MS Access, not # symbols',
      'Without a field list, values for ALL fields must be given in table order, but ID is an auto number and Club is missing',
    ],
    answer: 3,
    hint: 'Compare the number of values with the number of fields in the table.',
    explanation: 'The version of INSERT INTO without a field list needs data for ALL fields in the order they exist. The ID auto number cannot be inserted manually and you cannot leave out Club, so you must list the fields (RaceYear, UpDown, WinTime, WinName, Gender, Country).',
    skills: ['U12-S12', 'U12-S2'],
  },
  'u12-c23': {
    type: 'tf', world: UNIT.worldId,
    prompt: 'True or false: DELETE FROM tblComrades; (with no WHERE clause) deletes only the first record in the table.',
    answer: false,
    hint: 'Without a condition, which records match?',
    explanation: 'Without a condition every record matches, so ALL the records in the table are removed. You MUST add a WHERE condition to a DELETE statement, ideally using the primary key.',
    skills: ['U12-S12'],
  },
  'u12-c24': {
    type: 'trace', world: UNIT.worldId,
    prompt: 'The three statements run one after another on the sample table. Type each answer as a whole number.',
    code: `${COMRADES}\n\n1: UPDATE tblComrades SET Country = 'RUS' WHERE Country = 'Russia';\n2: DELETE FROM tblComrades WHERE RaceYear BETWEEN 1990 AND 1992;\n3: UPDATE tblComrades SET RaceYear = RaceYear + 1;`,
    rows: [
      { label: 'Records changed by statement 1', answer: '3' },
      { label: 'Records deleted by statement 2', answer: '3' },
      { label: 'Records changed by statement 3', answer: '6' },
      { label: 'Records left in the table at the end', answer: '6' },
    ],
    hint: 'Every record that matches the WHERE condition is affected; with no WHERE, every remaining record is affected.',
    explanation: 'Statement 1 changes the 3 Russia rows. Statement 2 deletes IDs 1, 2 and 3 (1990 to 1992 inclusive), leaving 6. Statement 3 has no WHERE, so all 6 remaining records get 1 added to RaceYear.',
    skills: ['U12-S12', 'U12-S10'],
  },
  'u12-c25': {
    type: 'match', world: UNIT.worldId,
    prompt: 'Check Point 2 asks for changes to tblStudent (fields Name, Class, House). Match each task to the correct SQL statement.',
    pairs: [
      { left: 'Insert Mary, class B, Blue house', right: 'INSERT INTO tblStudent (Name, Class, House) VALUES (\'Mary\', \'B\', \'Blue\');' },
      { left: 'Rename the Red house to Sisulu', right: 'UPDATE tblStudent SET House = \'Sisulu\' WHERE House = \'Red\';' },
      { left: 'Rename the Blue house to Tambo', right: 'UPDATE tblStudent SET House = \'Tambo\' WHERE House = \'Blue\';' },
      { left: 'Delete all the students in class C', right: 'DELETE FROM tblStudent WHERE Class = \'C\';' },
      { left: 'Change Mary\'s name to Mary-Anne', right: 'UPDATE tblStudent SET Name = \'Mary-Anne\' WHERE Name = \'Mary\';' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'New rows use INSERT, removing rows uses DELETE, changing values uses UPDATE ... SET ... WHERE.',
    explanation: 'INSERT INTO adds a record with values in the same order as the field list. UPDATE changes every record matching the WHERE condition, so one statement renames a whole house. DELETE removes every record that matches.',
    skills: ['U12-S12'],
  },
  'u12-c26': {
    type: 'mc', world: UNIT.worldId,
    prompt: 'Using tblStudent, which are the first four names displayed by this query? (Blue comes before Red alphabetically.)',
    code: `${STUDENTS}\n\nSELECT * FROM tblStudent ORDER BY House, Class, Name;`,
    options: [
      'Susanna, Fatima, Sipho, Jermaine',
      'Fatima, Sipho, Jason, Samuel',
      'Susanna, Jermaine, Rachael, Nelson',
      'Jermaine, Nelson, Rachael, Susanna',
    ],
    answer: 2,
    hint: 'Sort by House first, then by Class inside each house, then by Name inside each class.',
    explanation: 'All Blue students come first. Inside Blue, class A (Susanna) comes before class B (Jermaine, Rachael in name order) and class C (Nelson).',
    skills: ['U12-S7'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Learn how data is structured in database tables in MS Access and Java DB, and how SQL is used to search, sort and edit that data.',
  outcomes: [
    'By the end you can define a database, a relational database and a DBMS, and compare MS Access, MySQL and Java DB.',
    'By the end you can explain fields, records, tables, databases and primary keys.',
    'By the end you can design a table in MS Access and Java DB and choose efficient data types and field properties.',
    'By the end you can create, save and run queries in MS Access and Java DB and view their SQL.',
    'By the end you can write SELECT queries that limit fields, sort with ORDER BY and filter with WHERE.',
    'By the end you can build conditions with NOT, AND, OR, BETWEEN...AND, IN, LIKE, IS NULL and IS NOT NULL.',
    'By the end you can use DISTINCT, TOP n and FETCH FIRST n ROWS ONLY.',
    'By the end you can add, delete and change records with INSERT INTO, DELETE FROM and UPDATE.',
  ],
  topics: [
    {
      id: 'U12-T1',
      title: 'Databases and DBMSs',
      sections: ['12.1'],
      skills: ['U12-S1'],
      explanation: [
        'Instead of storing data in text files and manipulating it with programs, data can be stored in tables in a database, using a database program, and manipulated using Structured Query Language (SQL).',
        'A database is "a collection of related information about a subject, organised in a useful manner" (QUE\'s Computer and Internet dictionary). The data can be easily retrieved and used to draw conclusions or make decisions.',
        'A relational database program stores data in tables and relates the data in one table to another using a common column or field. Most major commercial databases, created with programs such as Microsoft Access or MySQL, use a relational approach.',
        'A Database Management System (DBMS) is a set of programs used to create the database, control the database, provide access to it and manage the data within it. A good DBMS avoids duplication of data and provides data that is consistent and reliable. Many users may share a database across a network, so the DBMS controls access to the data.',
        'MS Access is proprietary software developed for Windows and is not designed for commercial use. MySQL is open source, designed for commercial use and multiple operating systems, and supports more programming languages. Both support Delphi and Java. This unit uses Java DB, which is bundled with the free NetBeans.',
        'In Grade 10 you learn how to structure the data in a database; in Grade 11 you will write programs that use and manipulate it. Application programs can connect to other types of databases with minimal changes.',
      ],
      vocabulary: [
        { term: 'Database', definition: 'A collection of related information about a subject, organised in a useful manner.' },
        { term: 'Relational database', definition: 'Stores data in tables and relates the data in one table to another using a common column or field.' },
        { term: 'DBMS', definition: 'A set of programs used to create the database, control it, provide access to it and manage the data within it.' },
        { term: 'SQL', definition: 'Structured Query Language, used to manipulate the data stored in database tables.' },
      ],
      workedExamples: [],
      misconceptions: [
        'A DBMS is the file that holds the data. Wrong: the DBMS is the set of programs that creates, controls, gives access to and manages the database.',
        'MS Access and MySQL are licensed the same way. Wrong: MS Access is proprietary and made for Windows, while MySQL is open source and runs on multiple operating systems.',
      ],
      questions: [
        {
          id: 'U12-T1-Q1', type: 'mc', category: 'define',
          prompt: 'Which list gives the four functions of a DBMS named in the textbook?',
          options: [
            'Compile, run, debug and test the database',
            'Create the database, control it, provide access to it and manage the data in it',
            'Store, print, email and back up the tables',
            'Sort, search, delete and format text files',
          ],
          answer: 1,
          hint: 'A DBMS looks after a database from the moment it is made.',
          explanation: 'A DBMS is a set of programs used to create the database, control the database, provide access to it and manage the data within it.',
          skills: ['U12-S1'],
        },
        {
          id: 'U12-T1-Q2', type: 'tf', category: 'distinguish',
          prompt: 'True or false: MySQL is an open source DBMS designed for commercial use and multiple operating systems.',
          answer: true,
          hint: 'Compare it with MS Access, which is proprietary.',
          explanation: 'MySQL is open source, designed for commercial use and runs on multiple operating systems. If you do not have a licensed copy of MS Access you can freely download MySQL.',
          skills: ['U12-S1'],
        },
      ],
    },
    {
      id: 'U12-T2',
      title: 'Fields, Records, Tables and Primary Keys',
      sections: ['12.2', '12.2.1', '12.2.2'],
      skills: ['U12-S2'],
      explanation: [
        'A DBMS schema is the skeleton structure or logical design of the entire database. It defines how the data is organised into tables and how the tables are linked together to form relationships.',
        'The simplest entity in a database is a field, which stores a single data item. Fields are the columns in a table, for example a name, date of birth or telephone number. An age is never stored (it changes every year), so the date of birth is stored instead. Each field must have a data type, just like a variable needs a type in a programming language.',
        'Related fields grouped together form a record, for example all the information your school stores about you. Records are the horizontal rows of a table. Field names are one word, like a variable name, e.g. StudentID.',
        'A Primary Key is a field that uniquely identifies each record in the table. Two students can share a name, surname and even grade, so without a primary key the DBMS cannot be sure it is working with the correct record; you might delete more than one student or edit the wrong one.',
        'Tables can use an auto number primary key, which the DBMS fills in automatically. Summary: a field stores a single data item, a record is a collection of fields, a table is a collection of records, a database is a collection of tables, and a primary key uniquely identifies a record.',
      ],
      vocabulary: [
        { term: 'Schema', definition: 'The skeleton structure or logical design of the entire database.' },
        { term: 'Field', definition: 'Stores a single data item; the columns of a table.' },
        { term: 'Record', definition: 'A collection of fields; the horizontal rows of a table.' },
        { term: 'Table', definition: 'A collection of records.' },
        { term: 'Primary key', definition: 'A field that uniquely identifies each record in the table.' },
      ],
      workedExamples: [
        {
          code: 'StudentID | Name   | Surname | Grade\n1001      | Thabo  | Nkosi   | 10\n1002      | Thabo  | Nkosi   | 10',
          explanation: 'Two records with the same name, surname and grade. Only the StudentID primary key tells them apart, so an edit or delete can target exactly one student.',
        },
      ],
      misconceptions: [
        'A record is one column of a table. Wrong: a record is a row; fields are the columns.',
        'Name and surname together are good enough as a key. Wrong: two students can share name, surname and grade, so only a unique field such as StudentID is safe.',
      ],
      questions: [
        {
          id: 'U12-T2-Q1', type: 'mc', category: 'identify',
          prompt: 'A school stores StudentID, Name, Surname, Grade and DateOfBirth for every learner. Which is the best primary key?',
          options: ['StudentID', 'Surname', 'Name and Surname together', 'Grade'],
          answer: 0,
          hint: 'The primary key must be different for every single record.',
          explanation: 'A primary key must uniquely identify each record. Names, surnames and grades can repeat, but each StudentID is unique.',
          skills: ['U12-S2'],
        },
        {
          id: 'U12-T2-Q2', type: 'order', category: 'sequence',
          prompt: 'Order these database terms from the smallest to the largest.',
          items: ['Table', 'Database', 'Field', 'Record'],
          answer: [2, 3, 0, 1],
          hint: 'Each one is a collection of the one before it.',
          explanation: 'A field stores a single data item, a record is a collection of fields, a table is a collection of records and a database is a collection of tables.',
          skills: ['U12-S2'],
        },
        {
          id: 'U12-T2-Q3', type: 'tf', category: 'explain',
          prompt: 'True or false: Without a primary key, a delete meant for one student could remove more than one student who has the same name.',
          answer: true,
          hint: 'What if the DBMS cannot tell two records apart?',
          explanation: 'Without a primary key the DBMS cannot guarantee it is working with the correct record, so you may delete more than one student or edit the wrong one.',
          skills: ['U12-S2'],
        },
      ],
    },
    {
      id: 'U12-T3',
      title: 'Creating a Table in MS Access',
      sections: ['12.3', '12.3.1', '12.3.2'],
      skills: ['U12-S3', 'U12-S4'],
      explanation: [
        'Activity 1 creates a blank database Comrades1 and saves the first table as tblComrades. The prefix tbl shows the object is a table; the others are frm (form), qry (query) and rpt (report). Datasheet view is where the data is viewed; Design view (the ruler and set square icon) is where the schema is defined by giving each field a name and data type.',
        'MS Access automatically inserts an ID field and marks it as the Primary Key; it increases automatically each time a record is added. Field names are one word in upper camel case, e.g. RaceYear. Year, Time and Name may be reserved words, so the fields are named RaceYear (Number, Long Integer), WinTime (Date/Time, Long Time for hh:mm:ss) and WinName (Short Text, size 50).',
        'UpDown is Yes/No with format True/False: up (Durban to Pietermaritzburg) is TRUE and down is FALSE. Gender is Short Text of size 1 holding F or M, because calling a gender True or False is discriminatory. Club and Country are Short Text of size 50.',
        'Required set to Yes means a value must be provided when adding or changing a record; it may not be Null or empty. Indexed fields speed up frequent searches or sorts (like the index at the back of a book) but can slow down updating, because the index must change with the data. Activity 2 enters the data in Datasheet view; the ID fills in automatically.',
        'Useful MS Access data types: AutoNumber (self-incrementing long integer), Byte (0 to 255, one byte), Integer (-32768 to 32767, two bytes), Long Integer (-2 billion to 2 billion, four bytes), Currency and Double (8 bytes), Short Text (up to 255 characters, the default size) and Long Text (up to 64 000 characters), Date/Time formats, and Yes/No (0 for false and -1 for true in one byte).',
        'Choose the smallest type that fits so memory is used efficiently. A Yes/No field only needs two values, yet it uses a whole byte because memory is stored and addressed in whole bytes, not single bits.',
        'The ranges come from the number of bits: a Byte has 8 unsigned bits, so 2^8 = 256 values (0 to 255). An Integer has 16 signed bits: 2^15 = 32768, giving -32768 to 32767. A Long Integer has 32 signed bits: 2^31 = 2147483648, giving -2147483648 to 2147483647 (about 2 billion).',
      ],
      vocabulary: [
        { term: 'Datasheet view', definition: 'The view in which the data in a table is viewed and entered.' },
        { term: 'Design view', definition: 'The view in which the schema is defined by giving each field a name and a data type.' },
        { term: 'Required', definition: 'A value must be provided for the field when adding or changing a record; it may not be Null or empty.' },
        { term: 'Indexed', definition: 'A field with an index structure that speeds up searching and sorting but can slow down updating.' },
        { term: 'Reserved word', definition: 'A word with a special meaning to MS Access, such as Year, Time or Name, that should not be used as a field name.' },
      ],
      workedExamples: [
        {
          code: 'Field Name | Data Type  | Property\nRaceYear   | Number     | Field Size: Long Integer\nUpDown     | Yes/No     | Format: True/False\nWinTime    | Date/Time  | Format: Long Time\nWinName    | Short Text | Field Size: 50\nGender     | Short Text | Field Size: 1\nClub       | Short Text | Field Size: 50\nCountry    | Short Text | Field Size: 50',
          explanation: 'The design of tblComrades (the ID AutoNumber primary key is added automatically).',
        },
        {
          code: 'Ages 0 to 100            -> Byte\nIntegers -2 million to 2 million -> Long Integer\nHeights like 1.68 m      -> Double\nNames and surnames       -> Short Text',
          explanation: 'Picking the smallest suitable type for each kind of data, as in Check Point 1.',
        },
      ],
      misconceptions: [
        'A Short Text field of size 255 always uses 255 characters. Wrong: 255 is the maximum number of characters that may be stored in the field.',
        'A Yes/No field uses a single bit. Wrong: MS Access stores it in one byte, with 0 for false and -1 for true.',
        'Indexing every field is always better. Wrong: indexes speed up searching and sorting but slow down updating.',
      ],
      questions: [
        {
          id: 'U12-T3-Q1', type: 'mc', category: 'apply',
          prompt: 'Which MS Access Number data type is most appropriate for heights of people in metres, such as 1.68?',
          options: ['Byte', 'Integer', 'Long Integer', 'Double'],
          answer: 3,
          hint: 'The value has a decimal part.',
          explanation: 'Byte, Integer and Long Integer store whole numbers only. A Double stores a decimal number in 8 bytes.',
          skills: ['U12-S4'],
        },
        {
          id: 'U12-T3-Q2', type: 'trace', category: 'calculate',
          prompt: 'Prove the MS Access number ranges with a calculation. Type whole numbers with no spaces or commas (use a minus sign for negatives).',
          code: 'Byte         : 8 unsigned bits\nInteger      : 16 signed bits (1 bit for the sign)\nLong Integer : 32 signed bits (1 bit for the sign)',
          rows: [
            { label: 'Number of different Byte values (2^8)', answer: '256' },
            { label: 'Smallest Integer value (-2^15)', answer: '-32768' },
            { label: 'Largest Integer value (2^15 - 1)', answer: '32767' },
            { label: 'Largest Long Integer value (2^31 - 1)', answer: '2147483647' },
          ],
          hint: 'Signed types use 15 or 31 bits for the size of the number; one value of the positive side is used by 0.',
          explanation: '2^8 = 256 values, so a Byte holds 0 to 255. 2^15 = 32768, so an Integer holds -32768 to 32767. 2^31 = 2147483648, so a Long Integer holds -2147483648 to 2147483647, about 2 billion either way.',
          skills: ['U12-S4'],
        },
        {
          id: 'U12-T3-Q3', type: 'mc', category: 'explain',
          prompt: 'Why is the winner\'s name field in tblComrades called WinName and not Name?',
          options: [
            'Field names must be longer than four characters',
            'Name may only be used for Short Text fields of size 255',
            'Name is a reserved word, so Win is added to remove the conflict',
            'Field names may not start with a capital letter',
          ],
          answer: 2,
          hint: 'The same reason applies to RaceYear and WinTime.',
          explanation: 'Name, Time and Year may be reserved words in MS Access, so a prefix is added to avoid a conflict: WinName, WinTime and RaceYear.',
          skills: ['U12-S3'],
        },
      ],
    },
    {
      id: 'U12-T4',
      title: 'Creating a Table in Java DB',
      sections: ['12.3.3', '12.3.4'],
      skills: ['U12-S5', 'U12-S4'],
      explanation: [
        'Java DB is used through NetBeans. Besides being open source, you can work on your Java program and view your database in the same application without installing other software. NetBeans can be downloaded from netbeans.org.',
        'Activity 3: in the Services tab expand Databases, right-click Java DB and select Start Server, then Create Database and type comrades1 (Java DB is not case sensitive for the name). Leave the username and password blank for now, although normally you should choose a suitable username and a strong password.',
        'A broken orange connection icon means you are not connected. Right-click the database and select Connect; the icon becomes whole. Expand the database, then APP, then right-click the Tables folder and select Execute Command. The window shows the connection jdbc:derby://localhost:1527/comrades1. Type the CREATE TABLE statement and click Run SQL.',
        'CREATE TABLE defines the fields. The ID is an integer primary key that starts at 1 and increases automatically. RaceYear is a SMALLINT, UpDown a BOOLEAN, WinTime a TIME and the other fields VARCHAR with the maximum number of characters in brackets. Java DB writes all field names in capitals. The ID is coloured red as the primary key, and the Indexes folder lists the primary key.',
        'Activity 4: right-click tblComrades and choose View Data, then Insert Record(s). The ID shows <GENERATED>, so you cannot enter it. Enter 1990, tick UPDOWN, 07:02:00, Naidene Harrison, F, LadySmith AC and South Africa, then click Add Row.',
        'Java DB types: SMALLINT (-32768 to 32767, two bytes), INTEGER (-2 billion to 2 billion, four bytes), DOUBLE (decimal number, 8 bytes), VARCHAR (text up to 32 672 characters), TIMESTAMP (date and time), DATE, TIME and BOOLEAN.',
      ],
      vocabulary: [
        { term: 'Java DB', definition: 'The database bundled with NetBeans, used in this unit to create tables and run SQL.' },
        { term: 'Execute Command', definition: 'The NetBeans option that opens a window where SQL statements are typed and run.' },
        { term: 'VARCHAR', definition: 'Java DB text type that can hold up to 32 672 characters; the maximum length is given in brackets.' },
        { term: 'SMALLINT', definition: 'Java DB integer type for values from -32768 to 32767 in two bytes.' },
      ],
      workedExamples: [
        {
          code: 'CREATE TABLE TBLCOMRADES\n(\n    ID INTEGER NOT NULL PRIMARY KEY\n        GENERATED ALWAYS AS IDENTITY\n        (START WITH 1, INCREMENT BY 1),\n    RACEYEAR SMALLINT,\n    UPDOWN BOOLEAN,\n    WINNAME VARCHAR(50),\n    WINTIME TIME,\n    GENDER VARCHAR(1),\n    CLUB VARCHAR(50),\n    COUNTRY VARCHAR(50)\n)',
          explanation: 'The statement from Activity 3 that creates tblComrades with an auto-numbered primary key.',
        },
      ],
      misconceptions: [
        'You type the ID value when inserting a record in Java DB. Wrong: it shows <GENERATED> because the identity column fills itself in.',
        'Java DB needs extra software installed besides NetBeans. Wrong: it is bundled with NetBeans.',
      ],
      questions: [
        {
          id: 'U12-T4-Q1', type: 'order', category: 'sequence',
          prompt: 'Order the NetBeans steps to create the tblComrades table in a new Java DB database.',
          items: [
            'Right-click the Tables folder and select Execute Command',
            'Right-click Java DB and select Start Server',
            'Click Run SQL to run the CREATE TABLE statement',
            'Right-click Java DB and select Create Database',
            'Right-click the new database and select Connect',
          ],
          answer: [1, 3, 4, 0, 2],
          hint: 'The server must run before a database exists, and you must be connected before you can run commands.',
          explanation: 'Start the server, create the database, connect to it, open Execute Command on the Tables folder, then type the CREATE TABLE statement and click Run SQL.',
          skills: ['U12-S5'],
        },
        {
          id: 'U12-T4-Q2', type: 'tf', category: 'identify',
          prompt: 'True or false: In Java DB a VARCHAR field can hold at most 255 characters.',
          answer: false,
          hint: 'The 255 limit belongs to an MS Access text type.',
          explanation: 'A Java DB VARCHAR can hold text up to 32 672 characters. Short Text in MS Access is the type limited to 255 characters.',
          skills: ['U12-S4', 'U12-S5'],
        },
      ],
    },
    {
      id: 'U12-T5',
      title: 'Creating Queries and Opening a Database',
      sections: ['12.4', '12.4.1', '12.4.2', '12.4.3', '12.5', '12.5.1', '12.5.2'],
      skills: ['U12-S6'],
      explanation: [
        'SQL (Structured Query Language) contains a set of commands used to access and modify the data in a relational database. There are many versions; all use the basic statements in a similar way, but advanced statements may give slightly different results. SQL statements are processed by the DBMS. A query is used to search or extract data from a table in a database based on specified criteria.',
        'Activity 5 (MS Access): on the Create tab click Query Design, add tblComrades in the Show Table window, double-click the * to select all fields, save as qryALL (qry shows it is a query) and run it with the red ! button.',
        'In SQL View the query reads SELECT tblComrades.* FROM tblComrades; The table name in front of the field is only important when more than one table is used. The statement ends with a semicolon, and SELECT * FROM tblComrades; does the same, because the * is a wild card meaning all fields.',
        'Activity 6 (Java DB): connect to comrades1, right-click tblComrades, select Execute Command, type SELECT * FROM tblComrades; and click Run SQL. View Data generates select * from APP.TBLCOMRADES; on one line, but it is more readable to put each part on its own line.',
        'Activities 7 and 8 open the complete database with all winners from 1990 to 2018. MS Access users download Comrades.accDB from the Funworks resources page. Java DB users create a database called Comrades, connect, and paste the Comrades.sql file (a CREATE statement plus INSERT statements) into Execute Command. View Data should show 58 records, 20 at a time.',
      ],
      vocabulary: [
        { term: 'Query', definition: 'Used to search or extract data from a table in a database based on specified criteria.' },
        { term: 'SQL View', definition: 'The MS Access view that shows the SQL statement behind a query.' },
        { term: 'Wild card (*)', definition: 'In SELECT tblComrades.* the * indicates that all the fields are required.' },
      ],
      workedExamples: [
        {
          code: 'SELECT tblComrades.*\nFROM tblComrades;\n\nSELECT *\nFROM tblComrades;',
          explanation: 'Both statements display all the fields of all the records in tblComrades.',
        },
      ],
      misconceptions: [
        'Every version of SQL is identical. Wrong: the basic statements work the same way, but versions differ slightly, as with * versus % in LIKE.',
        'The table name must always be written in front of each field. Wrong: it is only needed when more than one table is used.',
      ],
      questions: [
        {
          id: 'U12-T5-Q1', type: 'mc', category: 'define',
          prompt: 'Which is the textbook definition of a query?',
          options: [
            'Used to search or extract data from a table in a database based on specified criteria',
            'A structure that speeds up sorting, like the index at the back of a book',
            'The skeleton structure or logical design of the entire database',
            'A field that uniquely identifies each record in the table',
          ],
          answer: 0,
          hint: 'A query asks the database a question.',
          explanation: 'A query is used to search or extract data from a table based on specified criteria. The other options describe an index, a schema and a primary key.',
          skills: ['U12-S6'],
        },
        {
          id: 'U12-T5-Q2', type: 'tf', category: 'predict',
          prompt: 'True or false: SELECT * FROM tblComrades; and SELECT tblComrades.* FROM tblComrades; display the same result.',
          answer: true,
          hint: 'Both use the * wild card on the same single table.',
          explanation: 'Both select all fields from tblComrades. Writing the table name in front only matters when a query uses more than one table.',
          skills: ['U12-S6'],
        },
        {
          id: 'U12-T5-Q3', type: 'mc', category: 'identify',
          prompt: 'Which statement about opening the complete Comrades database (winners from 1990 to 2018) is correct?',
          options: [
            'Java DB users open the Comrades.accDB file directly in NetBeans',
            'MS Access users open Comrades.accDB; Java DB users run Comrades.sql, which holds the CREATE and INSERT statements for tblComrades',
            'Both products require all 58 records to be retyped by hand in Datasheet view',
            'Comrades.sql contains only the SELECT queries used in the exercises',
          ],
          answer: 1,
          hint: 'One file is a ready-made database, the other is a text file of SQL statements.',
          explanation: 'MS Access users download and open Comrades.accDB. Java DB users create a Comrades database and paste Comrades.sql (a CREATE statement and INSERT statements) into Execute Command, giving 58 records.',
          skills: ['U12-S6', 'U12-S5'],
        },
      ],
    },
    {
      id: 'U12-T6',
      title: 'Limiting Fields and Sorting with ORDER BY',
      sections: ['12.6', '12.6.1', '12.6.2'],
      skills: ['U12-S7'],
      explanation: [
        'A SELECT query does not change the data; it merely searches the database for data based on certain criteria. Unless stated otherwise, the statements work in both MS Access and Java DB.',
        'To show only some fields, list them: SELECT RaceYear, WinName FROM tblComrades; The general form is SELECT <field(s)> FROM <table>; and * selects all fields. SQL code is not case sensitive, but the fields as typed after SELECT become the column headings. It is good practice to write reserved words like SELECT and FROM in capitals. MS Access still works without the final semicolon.',
        'ORDER BY sorts the result. Ascending (ASC) is the default, so ORDER BY WinName and ORDER BY WinName ASC are the same; DESC sorts in descending order (Z to A). ASC and DESC also apply to numbers, dates and times.',
        'You can sort on more than one field: ORDER BY Country, WinName sorts by country and then by name within each country. ORDER BY Country ASC, WinName DESC mixes the directions. General form: ORDER BY <field1> (DESC), <field2> (DESC), ... <fieldn> (DESC).',
      ],
      vocabulary: [
        { term: 'SELECT', definition: 'Chooses the fields to display; a SELECT query does not change the data.' },
        { term: 'ORDER BY', definition: 'Sorts the result on one or more fields; it must be the last clause in a query.' },
        { term: 'ASC / DESC', definition: 'Ascending order (the default) and descending order.' },
      ],
      workedExamples: [
        {
          code: 'SELECT WinName, Club, Country\nFROM tblComrades;',
          explanation: 'Exercise 1.1: only three fields are shown for every record.',
        },
        {
          code: 'SELECT WinName\nFROM tblComrades\nORDER BY WinTime;',
          explanation: 'Exercise 2.1: winners\' names from fastest to slowest time. You can sort on a field that is not displayed.',
        },
        {
          code: 'SELECT WinName, WinTime, Country\nFROM tblComrades\nORDER BY Country, WinTime DESC;',
          explanation: 'Exercise 2.4: sorted by country, then slowest to fastest within each country.',
        },
      ],
      misconceptions: [
        'ORDER BY needs ASC to sort A to Z. Wrong: ascending is the default.',
        'ORDER BY Country, WinName sorts the whole list by name. Wrong: names are only sorted within each country.',
      ],
      questions: [
        {
          id: 'U12-T6-Q1', type: 'trace', category: 'predict',
          prompt: 'Using tblStudent, predict the order of the result. Type each name exactly as it appears in the table.',
          code: `${STUDENTS}\n\nSELECT * FROM tblStudent ORDER BY Class, House, Name;`,
          rows: [
            { label: '1st name displayed', answer: 'Susanna' },
            { label: '2nd name displayed', answer: 'Fatima' },
            { label: '4th name displayed', answer: 'Jermaine' },
            { label: 'Last (9th) name displayed', answer: 'Thabo' },
          ],
          hint: 'Group by class A, B, C; inside each class put Blue before Red; inside each house sort the names.',
          explanation: 'The full order is Susanna, Fatima, Sipho (class A), Jermaine, Rachael, Jason (class B), Nelson, Samuel, Thabo (class C).',
          skills: ['U12-S7'],
        },
        {
          id: 'U12-T6-Q2', type: 'mc', category: 'apply',
          prompt: 'Exercise 2.2: display all the female winners and the year they won, followed by all the male winners, each group sorted alphabetically on name. Which statement does this?',
          options: [
            'SELECT WinName, RaceYear FROM tblComrades ORDER BY WinName, Gender;',
            'SELECT WinName, RaceYear FROM tblComrades ORDER BY Gender DESC, WinName;',
            'SELECT WinName, RaceYear FROM tblComrades WHERE Gender = \'F\';',
            'SELECT WinName, RaceYear FROM tblComrades ORDER BY Gender, WinName;',
          ],
          answer: 3,
          hint: 'F comes before M in ascending order.',
          explanation: 'Sorting on Gender first in ascending order puts F before M; WinName then sorts each group alphabetically. DESC on Gender would put the men first.',
          skills: ['U12-S7'],
        },
        {
          id: 'U12-T6-Q3', type: 'tf', category: 'distinguish',
          prompt: 'True or false: ORDER BY WinName ASC sorts the records differently from ORDER BY WinName.',
          answer: false,
          hint: 'What is the default sort direction?',
          explanation: 'By default a column is sorted in ascending order (ASC), so the two statements give the same result.',
          skills: ['U12-S7'],
        },
        {
          id: 'U12-T6-Q4', type: 'tf', category: 'predict',
          prompt: 'True or false: SELECT raceyear, WINNAME FROM tblComrades; runs correctly, and its column headings appear as raceyear and WINNAME.',
          answer: true,
          hint: 'Activity 9 asks you to run this query and note the column headings.',
          explanation: 'SQL code is not case sensitive, so the query runs, but whatever you type as the SELECT fields is shown as the column headings. Only the two listed fields are displayed.',
          skills: ['U12-S7'],
        },
      ],
    },
    {
      id: 'U12-T7',
      title: 'WHERE Conditions with NOT, AND and OR',
      sections: ['12.6.3', '12.6.4', '12.6.4.1', '12.6.4.2', '12.6.4.3'],
      skills: ['U12-S8', 'U12-S9'],
      explanation: [
        'WHERE limits the rows by giving a condition that must be satisfied: SELECT <field(s)> FROM <table> WHERE <condition>; For example WHERE RaceYear > 1999 (or RaceYear >= 2000) finds winners from 2000 onwards. The comparison operators =, >, <, <=, >= and <> can all be used.',
        'Text values are enclosed in single quotes: WHERE Country = \'South Africa\'. The data in MS Access is not case sensitive, but Java DB is case sensitive, so \'SOUTH AFRICA\' only works in MS Access.',
        'Date/Time values are surrounded by # symbols in MS Access (WHERE WinTime > #6:30:00#) and by single quotes in Java DB (WHERE WinTime > \'6:30:00\'). A Boolean field is compared without quotes, e.g. UpDown = False for downhill races.',
        'NOT returns a record if it satisfies the NEGATIVE of the condition: WHERE NOT (Country = \'Germany\'). AND returns a record only if it satisfies BOTH conditions: WHERE Gender = \'M\' AND Country = \'South Africa\'. OR returns a record if it satisfies EITHER condition: WHERE Country = \'South Africa\' OR Country = \'Russia\'.',
        'The order of operations is Brackets, NOT, AND, OR. Use brackets when you want an OR to be worked out before an AND.',
      ],
      vocabulary: [
        { term: 'WHERE', definition: 'The clause added to an SQL statement to include a condition that records must satisfy.' },
        { term: 'NOT', definition: 'A record is returned if it satisfies the negative of the condition.' },
        { term: 'AND', definition: 'A record is returned if it satisfies BOTH conditions.' },
        { term: 'OR', definition: 'A record is returned if it satisfies EITHER one of the conditions.' },
      ],
      workedExamples: [
        {
          code: 'SELECT WinName, WinTime\nFROM tblComrades\nWHERE WinTime < #6:00:00#;',
          explanation: 'Exercise 3.1 in MS Access; in Java DB write WHERE WinTime < \'6:00:00\'.',
        },
        {
          code: 'SELECT WinName\nFROM tblComrades\nWHERE UpDown = False;',
          explanation: 'Exercise 3.4: downhill races were stored as False.',
        },
        {
          code: 'SELECT *\nFROM tblComrades\nWHERE Gender = \'F\' AND Country = \'USA\';',
          explanation: 'Activity 13: female winners from the USA.',
        },
      ],
      misconceptions: [
        'Time values go in single quotes in MS Access. Wrong: MS Access uses # symbols; Java DB uses single quotes.',
        'OR is worked out before AND. Wrong: the order is Brackets, NOT, AND, OR.',
        'AND gives more rows than OR. Wrong: AND needs both conditions true, so it usually returns fewer rows.',
      ],
      questions: [
        {
          id: 'U12-T7-Q1', type: 'trace', category: 'predict',
          prompt: 'Check Point 2.3: use tblStudent. Type the row counts as whole numbers and the name exactly as in the table.',
          code: `${STUDENTS}\n\n3.1: SELECT Name FROM tblStudent WHERE Class = 'A' OR House = 'Blue';\n3.2: SELECT Name FROM tblStudent WHERE Class = 'A' AND House = 'Blue';`,
          rows: [
            { label: 'Rows returned by 3.1', answer: '6' },
            { label: 'Rows returned by 3.2', answer: '1' },
            { label: 'Name returned by 3.2', answer: 'Susanna' },
          ],
          hint: 'OR: either condition may be true. AND: both must be true.',
          explanation: '3.1 returns Rachael, Jermaine, Susanna, Nelson, Fatima and Sipho (class A or Blue house). 3.2 needs class A and Blue house, which is only Susanna.',
          skills: ['U12-S9'],
        },
        {
          id: 'U12-T7-Q2', type: 'mc', category: 'calculate',
          prompt: 'Using tblStudent from Check Point 2, how many rows does this query return? SELECT Name FROM tblStudent WHERE Class = \'A\' OR Class = \'B\' AND House = \'Red\';',
          options: ['3', '6', '4', '1'],
          answer: 2,
          hint: 'AND is worked out before OR unless there are brackets.',
          explanation: 'AND first: class B and Red gives Jason. OR then adds every class A student: Susanna, Fatima and Sipho. That is 4 rows. With brackets around the OR it would be 3.',
          skills: ['U12-S9', 'U12-S8'],
        },
        {
          id: 'U12-T7-Q3', type: 'tf', category: 'distinguish',
          prompt: 'True or false: In Java DB, WHERE Country = \'SOUTH AFRICA\' finds the records stored as \'South Africa\'.',
          answer: false,
          hint: 'One of the two products is case sensitive.',
          explanation: 'Java DB is case sensitive, so \'SOUTH AFRICA\' does not match \'South Africa\'. The same query would work in MS Access, whose data is not case sensitive.',
          skills: ['U12-S8'],
        },
      ],
    },
    {
      id: 'U12-T8',
      title: 'BETWEEN...AND, IN, IS NULL and LIKE',
      sections: ['12.6.5', '12.6.5.1', '12.6.5.2', '12.6.5.3', '12.6.5.4'],
      skills: ['U12-S10'],
      explanation: [
        'These operators simplify compound AND or OR conditions. BETWEEN...AND finds records whose field is in a range: WHERE RaceYear BETWEEN 1995 AND 1999 includes 1995 and 1999, the same as RaceYear > 1994 AND RaceYear < 2000. The operand and the range must be of the same, ordinal data type.',
        'IN checks a collection of values that need not be in order: WHERE RaceYear IN (1992, 1998, 2004, 2010). It replaces a condition joined with OR. NOT IN excludes those values: WHERE RaceYear NOT IN (1992, 1998, 2004, 2010).',
        'NULL means the data does not exist. It is not a 0 value or an empty string; those are real data. WHERE Club IS NULL finds winners with no known club, and WHERE Club IS NOT NULL finds winners registered with a club. (The Comrades database had its Unknown clubs removed so IS NULL could be shown.)',
        'LIKE matches text to a pattern using a wildcard character that can replace one, none or many characters. MS Access uses * and Java DB uses %. LIKE \'A*\' finds names starting with A, LIKE \'*e\' finds names ending with e, and LIKE \'*en*\' finds names containing en anywhere.',
        'ORDER BY can be added to any of these queries, but it must always be the last clause.',
      ],
      vocabulary: [
        { term: 'BETWEEN...AND', definition: 'Finds records whose field value is in a specified range, including both end values.' },
        { term: 'IN', definition: 'Finds records whose field value is in a collection (set) of values.' },
        { term: 'NULL', definition: 'The data does not exist; it is not the same as 0 or an empty string.' },
        { term: 'LIKE', definition: 'Matches text to a pattern condition using a wildcard.' },
        { term: 'Wildcard', definition: 'A character (* in MS Access, % in Java DB) that replaces one, none or many characters.' },
      ],
      workedExamples: [
        {
          code: 'SELECT *\nFROM tblComrades\nWHERE WinName LIKE \'A*\' OR WinName LIKE \'B*\'\nORDER BY WinName;',
          explanation: 'Activity 18 in MS Access. In Java DB write LIKE \'A%\' OR WinName LIKE \'B%\'.',
        },
        {
          code: 'SELECT *\nFROM tblComrades\nWHERE Country IN (\'Germany\', \'Russia\', \'Poland\');',
          explanation: 'Exercise 4.5; change IN to NOT IN for Exercise 4.6.',
        },
        {
          code: 'SELECT *\nFROM tblComrades\nWHERE Club IS NOT NULL\nORDER BY Country, Club;',
          explanation: 'Exercise 4.2: only winners with a known club, sorted by country and then club.',
        },
      ],
      misconceptions: [
        'BETWEEN 1995 AND 1999 leaves out 1995 and 1999. Wrong: both end values are included.',
        'A field containing 0 or an empty string is NULL. Wrong: NULL means no data exists at all.',
        'Java DB uses * in LIKE patterns. Wrong: Java DB uses %; MS Access uses *.',
      ],
      questions: [
        {
          id: 'U12-T8-Q1', type: 'tf', category: 'predict',
          prompt: 'True or false: WHERE RaceYear BETWEEN 1995 AND 1999 returns the winners of 1995 and 1999 as well as the years in between.',
          answer: true,
          hint: 'Activity 15 asks exactly this question.',
          explanation: 'BETWEEN...AND includes both end values, so it is the same as RaceYear >= 1995 AND RaceYear <= 1999.',
          skills: ['U12-S10'],
        },
        {
          id: 'U12-T8-Q2', type: 'mc', category: 'distinguish',
          prompt: 'Which statement about NULL is correct?',
          options: [
            'NULL means the data does not exist; it is not the same as 0 or an empty string',
            'NULL is stored as the value 0 in number fields',
            'NULL is the same as an empty string in text fields',
            'NULL is the text Unknown that MS Access inserts automatically',
          ],
          answer: 0,
          hint: 'A 0 or an empty string is still something.',
          explanation: 'NULL means the data simply does not exist. A 0 value or an empty string can exist as data and is not the same as NULL.',
          skills: ['U12-S10'],
        },
        {
          id: 'U12-T8-Q3', type: 'mc', category: 'apply',
          prompt: 'Activity 16 asks you to rewrite WHERE RaceYear IN (1992, 1998, 2004, 2010) without IN. Which condition is equivalent?',
          options: [
            'WHERE RaceYear = 1992 AND RaceYear = 1998 AND RaceYear = 2004 AND RaceYear = 2010',
            'WHERE RaceYear BETWEEN 1992 AND 2010',
            'WHERE RaceYear >= 1992 OR RaceYear <= 2010',
            'WHERE RaceYear = 1992 OR RaceYear = 1998 OR RaceYear = 2004 OR RaceYear = 2010',
          ],
          answer: 3,
          hint: 'A record has only one RaceYear, so it can never equal two years at once.',
          explanation: 'IN means "equal to any one of these", which is a chain of OR conditions. With AND no record could match, and BETWEEN would include every year from 1992 to 2010.',
          skills: ['U12-S10', 'U12-S9'],
        },
        {
          id: 'U12-T8-Q4', type: 'mc', category: 'predict',
          prompt: 'A table holds the winners Naidene Harrison, Ben Carter, Elize Steyn and Andile Zulu. Which of them match the MS Access condition WHERE WinName LIKE \'*en*\'?',
          options: [
            'Naidene Harrison and Ben Carter',
            'Ben Carter only',
            'Naidene Harrison, Ben Carter and Elize Steyn',
            'None of them, because * may only be used at the end of a pattern',
          ],
          answer: 0,
          hint: 'Look for the letters e and n next to each other anywhere in the name.',
          explanation: 'With * at both ends, the pattern matches en anywhere in the name: NaidENe and BEN. Elize Steyn has an e and an n but not next to each other. The * can go at the front, the back or both ends.',
          skills: ['U12-S10'],
        },
      ],
    },
    {
      id: 'U12-T9',
      title: 'DISTINCT and TOP / FETCH FIRST',
      sections: ['12.7', '12.7.1', '12.7.2'],
      skills: ['U12-S11'],
      explanation: [
        'Some queries repeat a name (a runner who won more than once) or a country (Russia provided many winners). DISTINCT and TOP <n> (FETCH FIRST <n> ROWS ONLY in Java DB) do not need conditions.',
        'DISTINCT removes duplicates: SELECT DISTINCT WinName FROM tblComrades; shows the 39 unique names in the full database. It works very well on a single field; with more fields each combination becomes more distinct, so values in one field can still repeat.',
        'The textbook notes that the DISTINCT list appears automatically ordered, but you can add ORDER BY to reverse it, and a WHERE clause such as WHERE Gender = \'F\' to list only female winners.',
        'TOP <n> (MS Access, straight after SELECT) or FETCH FIRST <n> ROWS ONLY (Java DB, at the end) is used with ORDER BY to display only the first n records. ORDER BY WinTime gives the best times first.',
        'There is no word in SQL that is the opposite of TOP. To find the bottom (worst) 5, reverse the sort with ORDER BY WinTime DESC. The SQL summary also mentions LIMIT <n>, which other versions of SQL use for the same purpose.',
      ],
      vocabulary: [
        { term: 'DISTINCT', definition: 'Removes duplicates from the result so each value is shown only once.' },
        { term: 'TOP <n>', definition: 'MS Access: displays only the first n records produced by the query.' },
        { term: 'FETCH FIRST <n> ROWS ONLY', definition: 'Java DB: displays only the first n records; written at the end of the query.' },
      ],
      workedExamples: [
        {
          code: 'MS Access:\nSELECT TOP 3 WinName, WinTime\nFROM tblComrades\nWHERE Gender = \'M\' AND Country = \'South Africa\'\nORDER BY WinTime;\n\nJava DB:\nSELECT WinName, WinTime\nFROM tblComrades\nWHERE Gender = \'M\' AND Country = \'South Africa\'\nORDER BY WinTime\nFETCH FIRST 3 ROWS ONLY;',
          explanation: 'Activity 20: the top 3 male South African winners in both products.',
        },
        {
          code: 'SELECT DISTINCT Country\nFROM tblComrades\nORDER BY Country;',
          explanation: 'Exercise 5.1: every country represented, without repetition, in alphabetical order.',
        },
      ],
      misconceptions: [
        'SQL has a BOTTOM keyword. Wrong: you reverse the sort with DESC and use TOP or FETCH FIRST.',
        'DISTINCT on several fields shows each name only once. Wrong: it removes repeated combinations, so a name can still repeat.',
      ],
      questions: [
        {
          id: 'U12-T9-Q1', type: 'mc', category: 'apply',
          prompt: 'Which Java DB query does the same as the MS Access query SELECT TOP 3 WinName, WinTime FROM tblComrades ORDER BY WinTime; ?',
          options: [
            'SELECT TOP 3 WinName, WinTime FROM tblComrades ORDER BY WinTime;',
            'SELECT WinName, WinTime FROM tblComrades ORDER BY WinTime FETCH FIRST 3 ROWS ONLY;',
            'SELECT WinName, WinTime FROM tblComrades FETCH FIRST 3 ROWS ONLY ORDER BY WinTime;',
            'SELECT FIRST 3 WinName, WinTime FROM tblComrades ORDER BY WinTime;',
          ],
          answer: 1,
          hint: 'Java DB puts the row limit after the sort.',
          explanation: 'Java DB uses FETCH FIRST n ROWS ONLY at the end of the query, after ORDER BY. TOP is the MS Access version.',
          skills: ['U12-S11'],
        },
        {
          id: 'U12-T9-Q2', type: 'tf', category: 'explain',
          prompt: 'True or false: SELECT DISTINCT WinName, Country FROM tblComrades; is guaranteed to show each winner\'s name only once.',
          answer: false,
          hint: 'DISTINCT works best on a single field.',
          explanation: 'With more than one field, DISTINCT removes repeated combinations of name and country. A field can still repeat, so it works best on a single field.',
          skills: ['U12-S11'],
        },
      ],
    },
    {
      id: 'U12-T10',
      title: 'Editing Data and the SQL Summary',
      sections: ['12.8', '12.8.1', '12.8.1.1', '12.8.1.2', '12.8.2', '12.8.3', '12.8.4', '12.9'],
      skills: ['U12-S12', 'U12-S7'],
      explanation: [
        'Data must be able to change: add, delete or edit records. Programs often have to do this through SQL, because the database may be on a remote server. Keep a copy of the original Comrades database, because these changes affect its accuracy.',
        'INSERT INTO <table> (<field1>, ..., <fieldn>) VALUES (<value1>, ..., <valuen>); The values must correspond, in the same order, to the fields listed. Fields that are left out get NULL values, except the auto number ID, which gets the next ID value (not 1 and 2). Numbers and Booleans (False) have no quotes, text has single quotes, and times use # in MS Access or single quotes in Java DB.',
        'The 1989 winners were Samuel Tshabalala (5:35:41) and Frith van der Merwe (5:54:43), both South African, in a downhill race. Their INSERT statements leave out ID and Club. MS Access shows a message confirming you are about to add a record; the record goes to the end of the table.',
        'INSERT INTO <table> VALUES (...); without a field list needs values for ALL fields in table order. It cannot be used on tblComrades, because the ID auto number cannot be inserted manually and empty (null) values cannot be left out.',
        'DELETE FROM <table> WHERE <condition>; deletes rows. You MUST add a condition; without one, ALL records are removed. Deleting by the primary key (ID) is best, or use a compound condition that uniquely identifies the record.',
        'UPDATE <table> SET <field> = <new value> WHERE <condition>; changes data. Without WHERE all records change. Using the primary key guarantees only 1 record changes, e.g. SET WinName = \'Charly Dollar\' WHERE ID = 8. One UPDATE can change many records (Country = \'RUS\' WHERE Country = \'Russia\') or apply a formula to all (SET RaceYear = RaceYear + 1). Updates by primary key are easy to reverse.',
        'The summary lists SELECT with ORDER BY, WHERE, IN, LIKE, NOT, AND, BETWEEN and OR; DISTINCT or TOP <n> / LIMIT <n> can follow SELECT and NOT can be used in any WHERE condition. Updating statements are INSERT INTO, DELETE FROM and UPDATE.',
      ],
      vocabulary: [
        { term: 'INSERT INTO', definition: 'Adds a record; values are given in the same order as the listed fields.' },
        { term: 'DELETE FROM', definition: 'Deletes the rows (records) that satisfy the WHERE condition.' },
        { term: 'UPDATE ... SET', definition: 'Changes field values in every record that matches the WHERE condition.' },
      ],
      workedExamples: [
        {
          code: 'INSERT INTO tblComrades (RaceYear, UpDown, WinTime, WinName, Gender,\nCountry)\nVALUES (1989,False,#5:35:41#,\'Samuel Tshabalala\',\'M\',\'South Africa\');',
          explanation: 'MS Access version from 12.8.1. In Java DB the time is written \'5:35:41\'. ID and Club are left out.',
        },
        {
          code: 'DELETE\nFROM tblComrades\nWHERE RaceYear = 2010;',
          explanation: 'Exercise 6.5: removes both 2010 entries.',
        },
        {
          code: 'UPDATE tblComrades\nSET Country = \'GER\'\nWHERE Country = \'Germany\';',
          explanation: 'Exercise 6.3: every Germany record changes in one statement.',
        },
      ],
      misconceptions: [
        'DELETE without WHERE only removes one record. Wrong: it removes ALL the records in the table.',
        'Left-out fields in an INSERT get the value 0. Wrong: they get NULL, while the auto number ID gets the next number.',
        'UPDATE only ever changes one record. Wrong: every record that matches the condition is changed.',
      ],
      questions: [
        {
          id: 'U12-T10-Q1', type: 'mc', category: 'explain',
          prompt: 'Why is the ID field left out of INSERT INTO tblComrades (RaceYear, UpDown, WinTime, WinName, Gender, Country) VALUES (...)?',
          options: [
            'Because ID is a text field and would need quotes',
            'Because fields that are left out are given the value 0',
            'Because ID is an auto number field and the DBMS gives it the next ID value automatically',
            'Because INSERT can only add six fields at a time',
          ],
          answer: 2,
          hint: 'Who decides the ID of a new record?',
          explanation: 'ID is an auto number field that cannot be inserted manually. The new record takes the next ID after those already allocated.',
          skills: ['U12-S12'],
        },
        {
          id: 'U12-T10-Q2', type: 'tf', category: 'predict',
          prompt: 'True or false: UPDATE tblComrades SET Country = \'SA\'; (with no WHERE clause) changes only the first record.',
          answer: false,
          hint: 'Which records match when there is no condition?',
          explanation: 'Without a WHERE clause all the records change, so every country would become SA. Always make the condition specific.',
          skills: ['U12-S12'],
        },
        {
          id: 'U12-T10-Q3', type: 'trace', category: 'calculate',
          prompt: 'Check Point 2.4: the statements run one after another on tblStudent. Type each answer as a whole number.',
          code: `${STUDENTS}\n\n1: INSERT INTO tblStudent (Name, Class, House) VALUES ('Mary', 'B', 'Blue');\n2: UPDATE tblStudent SET House = 'Sisulu' WHERE House = 'Red';\n3: DELETE FROM tblStudent WHERE Class = 'C';`,
          rows: [
            { label: 'Rows in the table after statement 1', answer: '10' },
            { label: 'Records changed by statement 2', answer: '5' },
            { label: 'Records deleted by statement 3', answer: '3' },
            { label: 'Rows left in the table at the end', answer: '7' },
          ],
          hint: 'Count the Red students and the class C students carefully; Mary is in class B.',
          explanation: 'The insert gives 9 + 1 = 10 rows. Samuel, Thabo, Jason, Fatima and Sipho are Red, so 5 change. Samuel, Thabo and Nelson are in class C, so 3 are deleted, leaving 7.',
          skills: ['U12-S12'],
        },
        {
          id: 'U12-T10-Q4', type: 'mc', category: 'apply',
          prompt: 'Each option starts with INSERT INTO tblComrades (RaceYear, UpDown, WinTime, WinName, Gender, Country). Which VALUES part is correct in Java DB?',
          options: [
            'VALUES (1989,False,#5:35:41#,\'Samuel Tshabalala\',\'M\',\'South Africa\');',
            'VALUES (1989,\'False\',\'5:35:41\',Samuel Tshabalala,M,South Africa);',
            'VALUES (\'1989\',False,5:35:41,\'Samuel Tshabalala\',\'M\',\'South Africa\');',
            'VALUES (1989,False,\'5:35:41\',\'Samuel Tshabalala\',\'M\',\'South Africa\');',
          ],
          answer: 3,
          hint: 'Numbers and Booleans have no quotes; text has single quotes; Java DB treats a time like text.',
          explanation: 'In Java DB the time value is enclosed in single quotes like the string values. The # symbols are the MS Access version, and the year and False never take quotes.',
          skills: ['U12-S12', 'U12-S8'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 'u12-comrades-data-meltdown',
    unitId: UNIT.id,
    title: 'Comrades Data Meltdown',
    icon: 'alert',
    summary: 'Query the winners database before the prize-giving goes live.',
    briefing: 'The Comrades Marathon prize-giving starts in minutes and the presenters\' printed lists have been lost. Only the tblComrades database survives, and you must pull the right winners, times and countries with precise SELECT queries. One wrong condition and the wrong runner walks on stage on live TV.',
    tickerMessages: [
      'Prize-giving delayed: organisers searching for winner lists',
      'Broadcaster demands the fastest times ever, sorted, within minutes',
      'Rumour: wrong country flag about to be raised on stage',
      'Crowd in Durban growing restless as the screens stay blank',
      'Final call: the database query must run NOW',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['U12-S7', 'U12-S8', 'U12-S9', 'U12-S10', 'U12-S11'],
    victoryMessage: 'Every name, time and country was spot on. The ceremony runs like clockwork and the champions get their moment.',
    failMessage: 'The wrong runner was called to the stage. The broadcaster cuts to an advert while the organisers scramble.',
  },
  {
    id: 'u12-vault-ledger-lockdown',
    unitId: UNIT.id,
    title: 'Vault Ledger Lockdown',
    icon: 'vault',
    summary: 'Repair a bank database before a careless UPDATE wipes it out.',
    briefing: 'A junior clerk at a Johannesburg bank is about to run UPDATE and DELETE statements without WHERE clauses on the customer database. You must check the table design, the primary keys and every editing statement before the night batch runs. Get it wrong and thousands of records are changed or erased forever.',
    tickerMessages: [
      'Night batch scheduled: unchecked SQL statements in the queue',
      'Auditors ask: does every table have a primary key?',
      'Warning: a DELETE statement with no condition has been spotted',
      'Customers report balances showing the same value for everyone',
      'Batch runs in seconds: last chance to fix the SQL',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['U12-S1', 'U12-S2', 'U12-S4', 'U12-S12'],
    victoryMessage: 'Every statement now targets exactly the right records. The batch runs cleanly and the vault ledger is safe.',
    failMessage: 'The batch ran with a missing WHERE clause. Every record changed, and the backup tapes are now the bank\'s only hope.',
  },
];
