// Learning Unit 8: Switch Statements and More (Exploring IT: Java Programming Grade 10, 3rd ed)
import { GitBranch } from 'lucide-react';

const J = (...lines) => lines.join('\n');

export const UNIT = { id: 'U8', number: 8, name: 'Switch Statements and More', worldId: 'switch-strings' };

export const SKILLS = {
  'U8-S1': { unit: 'U8', name: 'equals and equalsIgnoreCase', description: 'Compare Strings with the equals and equalsIgnoreCase methods and explain why == must not be used.', sections: ['8.1', '8.1.1'] },
  'U8-S2': { unit: 'U8', name: 'toLowerCase and toUpperCase', description: 'Convert Strings (including input) to one case before comparing or extracting a char.', sections: ['8.1.2'] },
  'U8-S3': { unit: 'U8', name: 'How Strings are compared', description: 'Explain that Strings are compared character by character using Unicode code values.', sections: ['8.1.3'] },
  'U8-S4': { unit: 'U8', name: 'Alphabetic order with compareTo', description: 'Use compareTo and the sign of its result to put Strings in alphabetic order or test equality.', sections: ['8.1.4'] },
  'U8-S5': { unit: 'U8', name: 'Trace tables with if', description: 'Draw trace tables with a column for every variable and condition to find logic errors in programs with if statements.', sections: ['8.2'] },
  'U8-S6': { unit: 'U8', name: 'Largest and smallest', description: 'Decompose and code the algorithm that finds the highest and lowest of a set of values using a loop and a nested if.', sections: ['8.3', '8.3.1'] },
  'U8-S7': { unit: 'U8', name: 'Switch instead of nested if', description: 'Replace multiple if ... else statements with a switch statement using case labels and a default.', sections: ['8.4'] },
  'U8-S8': { unit: 'U8', name: 'How switch and break work', description: 'Predict how a switch executes, including fall-through when break is left out and when default runs.', sections: ['8.4.1', '8.4.1.1'] },
  'U8-S9': { unit: 'U8', name: 'Switch rules and limits', description: 'Apply the rules for switch: int or char expressions, one unique value per case, no ranges or relational operators.', sections: ['8.4.2'] },
  'U8-S10': { unit: 'U8', name: 'Boolean variables', description: 'Declare boolean variables and store the result of a condition in them, then use them in if statements.', sections: ['8.5'] },
  'U8-S11': { unit: 'U8', name: 'Boolean expressions', description: 'Evaluate Boolean expressions and rewrite if statements that set true/false as a single Boolean assignment.', sections: ['8.5.1'] },
};

export const SKILL_HINTS = {
  'U8-S1': 'Strings are objects, not primitives: use s1.equals(s2) (case matters) or s1.equalsIgnoreCase(s2); s1 == s2 gives no error but often wrong output',
  'U8-S2': 'toLowerCase()/toUpperCase() return a new String with letters changed, non-letters unchanged; apply before charAt(0) since they are String methods',
  'U8-S3': 'Strings compared char by char by Unicode value until a difference: space 32, digits 48-57, A-Z 65-90, a-z 97-122, so "GARTH" < "Garth" < "garth"',
  'U8-S4': 'a.compareTo(b) subtracts Unicode values of the first different chars: negative means a comes first, 0 means equal, positive means b comes first ("Sugar" vs "Super" = 103 - 112 = -9)',
  'U8-S5': 'Trace table: one column per variable and per condition, row per line executed, show screen output; int arithmetic like 4*30 + qty*50*85/100 truncates',
  'U8-S6': 'Max/min algorithm: input first number, set max and min to it, loop for the other numbers: if num > max then max = num else if num < min then min = num; display both',
  'U8-S7': 'switch (markDiv10) { case 8: case 9: case 10: grade = \'A\'; break; ... default: ... } replaces a nested if; char case labels in single quotes',
  'U8-S8': 'switch jumps to the matching case label and runs until break; without break it falls through to the next cases; no match runs default, or skips the switch if no default',
  'U8-S9': 'switch tests an int or char value (not double or boolean); each case one unique value, no ranges like 0..9, no relational operators like case > 0; then use if instead',
  'U8-S10': 'boolean holds only true or false; leap = year % 4 == 0; if (leap) is the same as if (leap == true); named after George Boole',
  'U8-S11': 'Boolean expression always gives a value: hot = temp >= 35; replaces if/else setting true/false; evaluate e.g. 35/9*11+7 > 45 is false (int division); no quotes around true/false',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Switchyard Skies',
  subtitle: 'Unit 8 \u00b7 Switch and Strings',
  color: 'sky',
  glow: 'ja-glow-sky',
  bg: 'ja-w-switch-strings',
  icon: GitBranch,
  blurb: 'Compare Strings letter by letter, flip the switch on messy nested ifs and store true or false in boolean variables.',
};

export const LEVELS = [
  { id: 'u8-l1', name: 'String Showdown', subtitle: 'equals, case methods and compareTo', challengeIds: ['u8-c1', 'u8-c2', 'u8-c3', 'u8-c4', 'u8-c5', 'u8-c6'] },
  { id: 'u8-l2', name: 'Trace Track', subtitle: 'Alphabetic order, trace tables, max and min', challengeIds: ['u8-c7', 'u8-c8', 'u8-c9', 'u8-c10', 'u8-c11', 'u8-c12'] },
  { id: 'u8-l3', name: 'The Switchboard', subtitle: 'switch, case, break and default', challengeIds: ['u8-c13', 'u8-c14', 'u8-c15', 'u8-c16', 'u8-c17', 'u8-c18'], hasCoding: true },
  { id: 'u8-l4', name: 'Boolean Boss', subtitle: 'Switch rules, booleans and full-unit review', challengeIds: ['u8-c19', 'u8-c20', 'u8-c21', 'u8-c22', 'u8-c23', 'u8-c24', 'u8-c25'], hasCoding: true },
];

export const CHALLENGES = {
  'u8-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which statement correctly rewrites the incorrect line below?',
    code: 'if ( greeting ==  "hello" )',
    options: [
      'if (greeting = "hello")',
      'if (greeting.equals("hello"))',
      'if (greeting.equals == "hello")',
      'if (equals(greeting, "hello"))',
    ],
    answer: 1,
    hint: 'Strings are objects, so you need a method of the String class that takes the other String as a parameter.',
    explanation: 'The equals method of the String class is called on one String and takes the second String as a parameter. A single = is assignment, and equals is not used with == or as a stand-alone method.',
    skills: ['U8-S1'],
  },
  'u8-c2': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'Activity 1 has been changed to use ==. The user types HELLO (all capitals). What is displayed?',
    code: J(
      'String stg1, stg2, message = "";',
      'stg1 = "HELLO";',
      'stg2 = JOptionPane.showInputDialog ("Type in any word and <Enter>");',
      'if (stg1 == stg2)',
      '{',
      '    message = "The strings are equal";',
      '}',
      'else',
      '{',
      '    message = "The strings are NOT equal";',
      '}',
      'JOptionPane.showMessageDialog (null, message);',
    ),
    options: [
      'The strings are equal',
      'A compile error: == cannot be used with Strings',
      'The strings are NOT equal',
      'Nothing is displayed because the program crashes',
    ],
    answer: 2,
    hint: 'The textbook warns that == with Strings gives no error message, but often gives incorrect output.',
    explanation: 'Using == with Strings compiles, but it does not compare the characters. The String typed into the dialog box is a different String object from "HELLO", so the condition is false even though the letters match. Use stg1.equals(stg2).',
    skills: ['U8-S1'],
  },
  'u8-c3': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: "HELLO".equalsIgnoreCase("hElLo") gives true.',
    answer: true,
    hint: 'Look at what the "IgnoreCase" part of the method name means.',
    explanation: 'equalsIgnoreCase treats uppercase and lowercase letters as the same, so HELLO, hello and hElLo all match. It is useful when you do not want to worry about the case the user typed.',
    skills: ['U8-S1', 'U8-S2'],
  },
  'u8-c4': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each String method to what it does.',
    pairs: [
      { left: 'equals', right: 'true only if both Strings have exactly the same characters, case included' },
      { left: 'equalsIgnoreCase', right: 'true if the Strings match when capitals and small letters are treated as the same' },
      { left: 'toLowerCase', right: 'gives the String with every letter changed to a small letter' },
      { left: 'toUpperCase', right: 'gives the String with every letter changed to a capital' },
      { left: 'compareTo', right: 'gives a negative, zero or positive int that shows alphabetic order' },
    ],
    answer: [0, 1, 2, 3, 4],
    hint: 'Only one of these methods returns a number instead of true/false or a String.',
    explanation: 'equals and equalsIgnoreCase return true or false, toLowerCase and toUpperCase return a changed String (non-letters stay the same), and compareTo returns an int whose sign shows the order.',
    skills: ['U8-S1', 'U8-S2', 'U8-S4'],
  },
  'u8-c5': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'compareTo subtracts the Unicode values of the first characters that differ. Type the int each call returns (use a minus sign for negatives). Unicode: a 97, b 98, c 99, e 101, g 103, h 104, p 112, H 72.',
    code: J(
      'int r1 = "carrots".compareTo("broccoli");',
      'int r2 = "Sugar".compareTo("Super");',
      'int r3 = "Jane".compareTo("Jean");',
      'int r4 = "Hi".compareTo("hi");',
    ),
    rows: [
      { label: 'r1', answer: '1' },
      { label: 'r2', answer: '-9' },
      { label: 'r3', answer: '-4' },
      { label: 'r4', answer: '-32' },
    ],
    hint: 'Skip the characters that are the same and subtract: first word\'s character minus second word\'s character.',
    explanation: 'c - b = 99 - 98 = 1; in Sugar/Super the third letters differ: g - p = 103 - 112 = -9; Jane/Jean: a - e = 97 - 101 = -4; Hi/hi: H - h = 72 - 104 = -32. A negative result means the first word comes first.',
    skills: ['U8-S3', 'U8-S4'],
  },
  'u8-c6': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: In the Unicode table small letters come before capital letters, so Java puts "garth" before "Garth".',
    answer: false,
    hint: 'Compare the code values of G (71) and g (103).',
    explanation: 'In the Unicode table the digits come first, then the capitals, then the small letters. So "GARTH" < "Garth" < "garth".',
    skills: ['U8-S3'],
  },
  'u8-c7': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'This is the AlphOrder program from Activity 3 with new words. What is displayed on the second line of output?',
    code: J(
      'String word1, word2;',
      'word1 = "jelly";',
      'word2 = "jam";',
      'System.out.println("ALPHABETIC ORDER");',
      'if ( word1.compareTo(word2) < 0 )',
      '{',
      '    System.out.print (word1 + " comes before " + word2);',
      '}',
      'else',
      '{',
      '    System.out.print (word2 + " comes before " + word1);',
      '}',
    ),
    options: [
      'jam comes before jelly',
      'jelly comes before jam',
      'jelly comes before jam, because jelly is longer',
      'Nothing, because the result is not 0',
    ],
    answer: 0,
    hint: 'The first letters match. Compare e (101) with a (97).',
    explanation: 'The second letters differ: e - a = 101 - 97 = 4, which is NOT < 0, so the else part runs and prints word2 first: jam comes before jelly.',
    skills: ['U8-S4'],
  },
  'u8-c8': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Trace the earrings program from 8.2. First the user enters 6, then the program is run again with 3. Type doubles the way Java prints them (e.g. 12.0), and type true or false for the condition.',
    code: J(
      'int qty;',
      'double price;',
      'qty = Integer.parseInt (JOptionPane.showInputDialog ("How many pairs?"));   // line 1',
      'if (qty <= 4)                                 // line 2',
      '{',
      '    price = qty * 30;                         // line 3',
      '}',
      'else',
      '{',
      '    price = 4*30 + qty*50*85/100;             // line 4',
      '}',
      'System.out.println ("You owe R" + price);     // line 5',
    ),
    rows: [
      { label: 'qty = 6: line 2, qty <= 4?', answer: 'false' },
      { label: 'qty = 6: price after line 4', answer: '375.0' },
      { label: 'qty = 6: screen output', answer: 'You owe R375.0' },
      { label: 'qty = 3: price', answer: '90.0' },
    ],
    hint: 'Work left to right with ints: 4*30, then 6*50*85, then divide by 100. The int result is stored in a double.',
    explanation: 'For 6: 4*30 = 120 and 6*50*85/100 = 25500/100 = 255, so price = 375.0. That is too much, because all 6 pairs are charged at 85% of R50 instead of only the 2 extra pairs. For 3, price = 3*30 = 90.0.',
    skills: ['U8-S5'],
  },
  'u8-c9': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'The customer who bought 6 pairs correctly says she only owes R205.00. What is the problem in the earrings program?',
    code: J(
      'if (qty <= 4)',
      '{',
      '    price = qty * 30;',
      '}',
      'else',
      '{',
      '    price = 4*30 + qty*50*85/100;',
      '}',
    ),
    options: [
      'Line 2 should be if (qty < 4), because 4 pairs must use the else part',
      'price should be declared as int, because R30 is a whole number',
      'The if part should be price = qty * 50, because R30 only applies after 4 pairs',
      'Every pair is charged at 85% in the else part; it should be 4*30 + (qty - 4)*50*85/100',
    ],
    answer: 3,
    hint: 'Which pairs should be charged at 85% of the full price of R50?',
    explanation: 'Only the pairs after the first four cost 85% of R50. With (qty - 4): 120 + 2*50*85/100 = 120 + 85 = 205, so the output is You owe R205.0.',
    skills: ['U8-S5'],
  },
  'u8-c10': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Trace this program from Exercise 1 (question 4). Type doubles the way Java prints them (e.g. 4.0).',
    code: J(
      'int i;',
      'double x = 4, sum = 1.0;',
      'for (i = 3; i <= 8; i++)',
      '{',
      '    sum = sum + i;',
      '    if (i % 2 == 0)',
      '    {',
      '        x = x + i * 3;',
      '    }',
      '    System.out.println (i);',
      '    System.out.println (sum);',
      '}',
      'System.out.println (i);',
      'System.out.println (x);',
    ),
    rows: [
      { label: 'sum when the loop ends', answer: '34.0' },
      { label: 'Number of times x is changed', answer: '3' },
      { label: 'Value of i printed after the loop', answer: '9' },
      { label: 'Value of x printed at the end', answer: '58.0' },
    ],
    hint: 'Make a column for i, sum, x and the condition i % 2 == 0. Only even values of i change x.',
    explanation: 'sum goes 4.0, 8.0, 13.0, 19.0, 26.0, 34.0. x changes when i is 4, 6 and 8: 4 + 12 = 16.0, 16 + 18 = 34.0, 34 + 24 = 58.0. The loop stops when i becomes 9, and i is declared outside the loop, so 9 is printed.',
    skills: ['U8-S5'],
  },
  'u8-c11': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the steps of the algorithm for finding the largest and smallest of 10 numbers in the correct order.',
    items: [
      'Repeat 9 times: input the next number',
      'Display max and min',
      'Input the first number',
      'Inside the loop: if num > max then max = num, else if num < min then min = num',
      'Set both max and min to the first number',
    ],
    answer: [2, 4, 0, 3, 1],
    hint: 'Task 1 sets things up, Task 2 is the repetition and Task 3 displays the result.',
    explanation: 'The first number sets both max and min (Task 1). The loop inputs the remaining 9 numbers and compares each one (Task 2 and Task 4). Finally the results are displayed (Task 3).',
    skills: ['U8-S6'],
  },
  'u8-c12': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'This MaxMin program gives the wrong lowest value for some data. What is the logic error?',
    code: J(
      'num = Integer.parseInt (JOptionPane.showInputDialog ("Enter a number"));',
      'max = num;',
      'min = num;',
      'for (i = 2; i <= 10; i++)',
      '{',
      '    num = Integer.parseInt (JOptionPane.showInputDialog ("Enter a number"));',
      '    if (num > max)',
      '    {',
      '        max = num;',
      '    }',
      '    else',
      '    {',
      '        min = num;',
      '    }',
      '}',
      'System.out.println ("Highest: " + max + "  Lowest: " + min);',
    ),
    options: [
      'max and min should both start at 0, not at the first number',
      'The else assumes a number that is not the highest is the lowest; it needs if (num < min)',
      'The loop should run from 1 to 10 so that all 10 numbers are entered inside it',
      'The condition should be num >= max, otherwise equal numbers are lost',
    ],
    answer: 1,
    hint: 'Try the numbers 15, 8, 22, 4, 10. What is min at the end?',
    explanation: 'We cannot assume that if a number is not the highest then it must be the smallest. With 15, 8, 22, 4, 10 the last 10 overwrites min. The else part must contain a nested if (num < min).',
    skills: ['U8-S6'],
  },
  'u8-c13': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Using the LetterGrade2 switch below, type the single capital letter stored in grade for each mark.',
    code: J(
      `char grade = 'X';`,
      'markDiv10 = mark / 10;',
      'switch (markDiv10)',
      '{',
      `    case 8: case 9: case 10:`,
      `        grade = 'A';`,
      '        break;',
      '    case 7:',
      `        grade = 'B';`,
      '        break;',
      '    case 6:',
      `        grade = 'C';`,
      '        break;',
      '    case 5:',
      `        grade = 'D';`,
      '        break;',
      '    case 4:',
      `        grade = 'E';`,
      '        break;',
      '    case 3: case 2: case 1: case 0:',
      `        grade = 'F';`,
      '        break;',
      '    default:',
      '        System.out.println ("Mark incorrect, no grade applies");',
      '}',
    ),
    rows: [
      { label: 'mark = 66', answer: 'C' },
      { label: 'mark = 38', answer: 'F' },
      { label: 'mark = 105', answer: 'A' },
      { label: 'mark = 115', answer: 'X' },
    ],
    hint: 'Work out mark / 10 with integer division first, then find the matching case label.',
    explanation: '66/10 = 6 gives C and 38/10 = 3 gives F. 105/10 = 10 matches case 10, so even an invalid mark of 105 gets an A. 115/10 = 11 matches no case, so default runs and grade keeps its initial X; that is why the output statement is put in if (mark >= 0 & mark <= 100).',
    skills: ['U8-S7', 'U8-S8'],
  },
  'u8-c14': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'In the break investigation, every break has been removed. The user enters 78. What is displayed?',
    code: J(
      'markDiv10 = mark / 10;',
      'switch (markDiv10)',
      '{',
      '    case 8: case 9: case 10:',
      `        grade = 'A';`,
      '    case 7:',
      `        grade = 'B';`,
      '    case 6:',
      `        grade = 'C';`,
      '    case 5:',
      `        grade = 'D';`,
      '    case 4:',
      `        grade = 'E';`,
      '    case 3: case 2: case 1: case 0:',
      `        grade = 'F';`,
      '}',
      'JOptionPane.showMessageDialog (null, "Your mark of " + mark + " is the symbol " + grade);',
    ),
    options: [
      'Your mark of 78 is the symbol B',
      'Your mark of 78 is the symbol BCDEF',
      'Your mark of 78 is the symbol F',
      'Your mark of 78 is the symbol X',
    ],
    answer: 2,
    hint: 'Execution starts at case 7. Without break, where does it stop?',
    explanation: 'Without break statements, execution starts at the first statement after the matching label and continues to the end of the switch block. grade is assigned B, C, D, E and then F; each value overwrites the previous one, so F is displayed.',
    skills: ['U8-S8'],
  },
  'u8-c15': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'The Respond program now converts the input to uppercase. The user types x (lowercase). What is displayed?',
    code: J(
      'char ch;',
      `ch = JOptionPane.showInputDialog ("Choose from '1'-sing, '2'-cry, '3'-laugh, 'x'-finish: ").toUpperCase ().charAt (0);`,
      'switch (ch)',
      '{',
      `case '1':`,
      '    System.out.println ("La la");',
      '    break;',
      `case '2':`,
      '    System.out.println ("Boo hoo");',
      '    break;',
      `case '3':`,
      '    System.out.println ("Ha ha");',
      '    break;',
      `case 'x':`,
      '    System.out.println ("See you later");',
      '    break;',
      'default:',
      `    System.out.println ("I don't understand");`,
      '}',
    ),
    options: [
      'See you later',
      'La la',
      'Nothing is displayed',
      `I don't understand`,
    ],
    answer: 3,
    hint: 'What does the typed x become before charAt(0) takes the first character?',
    explanation: `The input is converted to 'X', but the case label is lowercase 'x', so no case matches and default runs. This is the common error the textbook warns about: if the cases use lowercase letters, use toLowerCase() instead.`,
    skills: ['U8-S8', 'U8-S2'],
  },
  'u8-c16': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'True or false: If no case label matches the value and there is no default: label, the program stops with an error.',
    answer: false,
    hint: 'Think about what the interpreter does with the switch body when nothing matches.',
    explanation: 'If there is no matching case label and no default: label, the interpreter skips the body of the switch block altogether and carries on with the rest of the program.',
    skills: ['U8-S8'],
  },
  'u8-c17': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: `In LetterGrade2, what does this part of the switch mean?`,
    code: J(
      'case 8: case 9: case 10:',
      `    grade = 'A';`,
      '    break;',
    ),
    options: [
      `If markDiv10 is 8, 9 or 10, grade becomes 'A'`,
      'Only 10 gives an A; case 8 and case 9 have no statements so nothing happens',
      `markDiv10 must be 8, then 9, then 10 in turn before 'A' is assigned`,
      'It is a compile error; each case must have its own statements and break',
    ],
    answer: 0,
    hint: 'What happens after case 8: when there is no statement and no break before the next label?',
    explanation: `case 8 and case 9 have no statements and no break, so execution follows on to the statements of case 10. When several cases give the same action, each value gets the word case and a colon.`,
    skills: ['U8-S7'],
  },
  'u8-c18': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Exercise 3: Rewrite the Greet program so that it uses a switch statement instead of if statements. Add a Sotho option and a default for invalid options.',
    criteria: J(
      'Class must be called Greet with a main method.',
      'Shows a menu with JOptionPane.showMessageDialog listing A. Afrikaans, E. English, Z. Zulu, S. Sotho and X. Exit.',
      'Reads the choice with JOptionPane.showInputDialog, converts it with toUpperCase() BEFORE charAt(0), and stores it in a char variable called option.',
      'Uses switch (option) with case labels in single quotes: \'A\', \'E\', \'Z\', \'S\', \'X\'. No if statements are used to choose the message.',
      'Messages exactly: A -> "Goeie Dag", E -> "Good Day", Z -> "Sawubona", S -> "Dumela", X -> "Click Close to end".',
      'Every case clause ends with break.',
      'A default clause sets the message to "Invalid option entered".',
      'The message is displayed with JOptionPane.showMessageDialog after the switch.',
    ),
    starter: J(
      'import javax.swing.*;',
      '',
      'public class Greet',
      '{',
      '  public static void main (String [] args)',
      '  {',
      '    char option;',
      '    String message = "";',
      '    // your code here',
      '  } // main method',
      '} // Greet class',
    ),
    explanation: 'Converting to uppercase first means only the capital letters need case labels. Each case must end with break so that only one message is assigned, and default catches any letter other than A, E, Z, S or X.',
    skills: ['U8-S7', 'U8-S8', 'U8-S2'],
  },
  'u8-c19': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'Check Point 2, question 4.2: What causes the compilation error in this switch statement?',
    code: J(
      'switch (ans)',
      '{',
      'case <0 : System.out.println("negative");',
      'case 0: System.out.println("zero");',
      'case >0: System.out.println("positive");',
      '}',
    ),
    options: [
      'A switch must always end with a default clause',
      'ans must be declared as a char for a switch to work',
      'Relational operators cannot be used in case labels, so case <0 and case >0 are not allowed',
      'The case labels must be listed in ascending order',
    ],
    answer: 2,
    hint: 'What may follow the word case?',
    explanation: 'Each case label must be one unique value; relational operators such as < and > may not be used. To test ranges you must change to an if statement. (The missing break statements would also cause fall-through, but that is a logic error, not a compile error.)',
    skills: ['U8-S9'],
  },
  'u8-c20': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'The user enters 10. What is the complete output? (Lines are separated by /.)',
    code: J(
      'switch (num)',
      '{',
      '   case 1: case 3: case 5: case 7: case 9:',
      '      System.out.println ("odd");',
      '      break;',
      '   case -1:',
      '      System.out.println ("Too low to go!");',
      '      break;',
      '   case 2:',
      '   {',
      '      System.out.println ("Even no");',
      '      System.out.println ("Prime no too!");',
      '      break;',
      '   }',
      '   case 0:',
      '      System.out.println ("zilch!");',
      '      break;',
      '   case 10:',
      '      System.out.println ("Too high");',
      '   case 11:',
      '      System.out.println ("More than 10");',
      '      break;',
      '   default:',
      '      System.out.println ("Any other value");',
      '}',
      'System.out.println ("Case is closed");',
    ),
    options: [
      'Too high / Case is closed',
      'Too high / More than 10 / Case is closed',
      'Too high / More than 10 / Any other value / Case is closed',
      'Too high / More than 10',
    ],
    answer: 1,
    hint: 'Look for the break that is missing, and remember which line is outside the switch block.',
    explanation: 'case 10 has no break, so execution falls through to case 11 and prints More than 10 before reaching a break. Case is closed is outside the switch, so it is displayed every time.',
    skills: ['U8-S8', 'U8-S9'],
  },
  'u8-c21': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Exercise 5, question 2: type true or false for the value stored in each boolean variable.',
    code: J(
      'boolean ans1, evenTot, over45, isTheSame, similar;',
      'ans1 = (3 + 4 == 4 + 3);',
      'evenTot = ((13 + 16 + 19 + 21) % 2 == 0);',
      'over45 = (35/9*11+7 > 45);',
      'isTheSame = (200/5/2 == 200/10);',
      'similar = ("0800".equals("800"));',
    ),
    rows: [
      { label: 'ans1', answer: 'true' },
      { label: 'evenTot', answer: 'false' },
      { label: 'over45', answer: 'false' },
      { label: 'isTheSame', answer: 'true' },
      { label: 'similar', answer: 'false' },
    ],
    hint: 'Remember that dividing two ints gives an int (35/9 is 3), and that equals compares every character.',
    explanation: '7 == 7 is true. 13 + 16 + 19 + 21 = 69 and 69 % 2 = 1, so false. 35/9 = 3, 3*11 + 7 = 40, and 40 > 45 is false. 200/5/2 = 20 and 200/10 = 20, so true. "0800" and "800" have different characters, so false.',
    skills: ['U8-S10', 'U8-S11'],
  },
  'u8-c22': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'Exercise 5, question 4: name = "Bongani", age = 16, inLove = true, soccerTeam = "Mamelodi Sundowns", music = "RAP". What does the last line below print?',
    code: J(
      'if (soccerTeam.length () > age)',
      '{',
      '    music = "jazz";',
      '}',
      'if (music == "RAP")',
      '{',
      '    soccerTeam = "Chiefs";',
      '}',
      'System.out.print ("He supports " + soccerTeam );',
      'System.out.println (" and he loves " + music + " music");',
    ),
    options: [
      'He supports Chiefs and he loves RAP music',
      'He supports Chiefs and he loves jazz music',
      'He supports Mamelodi Sundowns and he loves RAP music',
      'He supports Mamelodi Sundowns and he loves jazz music',
    ],
    answer: 3,
    hint: 'Count every character of "Mamelodi Sundowns", including the space.',
    explanation: '"Mamelodi Sundowns" has 17 characters (8 + space + 8), and 17 > 16, so music becomes "jazz". music is no longer "RAP", so soccerTeam is not changed. (Comparing Strings with == is also poor practice; use equals.)',
    skills: ['U8-S1', 'U8-S11'],
  },
  'u8-c23': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'RockPaperScissors (Exercise 4): 0 = paper, 1 = scissors, 2 = rock, and result = computer - user. Type the result and the exact output for each game.',
    code: J(
      'int result = computer - user;',
      'switch (result)',
      '{',
      '    case 1: case -2:',
      '        System.out.println ("Computer wins");',
      '        break;',
      '    case -1: case 2:',
      '        System.out.println ("You win");',
      '        break;',
      '    default:',
      '        System.out.println ("Draw");',
      '}',
    ),
    rows: [
      { label: 'computer = 2 (rock), user = 0 (paper): result', answer: '2' },
      { label: 'computer = 2 (rock), user = 0 (paper): output', answer: 'You win' },
      { label: 'computer = 0 (paper), user = 2 (rock): result', answer: '-2' },
      { label: 'computer = 0 (paper), user = 2 (rock): output', answer: 'Computer wins' },
    ],
    hint: 'Subtract the user\'s option from the computer\'s option, then find the case label with that value.',
    explanation: '2 - 0 = 2 matches case 2, so the user wins (paper wraps rock). 0 - 2 = -2 matches case -2, so the computer wins. Case labels can be negative int values, but each label must be a single value.',
    skills: ['U8-S9', 'U8-S7'],
  },
  'u8-c24': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Exercise 2: Write a program RandomMaxMinAve that randomly generates 100 numbers between 1 and 200, then determines and displays the highest, the lowest and the average.',
    criteria: J(
      'Class must be called RandomMaxMinAve with a main method.',
      'Each random number is generated with (int) (Math.random() * 200) + 1 so that it is between 1 and 200 inclusive.',
      'Follows the textbook MaxMin algorithm: the FIRST number is generated before the loop and is used to set max, min and the running total.',
      'A for loop runs 99 more times (e.g. for (i = 2; i <= 100; i++)), generating the next number and adding it to the total.',
      'Inside the loop uses a nested if: if (num > max) max = num; else if (num < min) min = num;',
      'The average is calculated as a double without integer division (e.g. total / 100.0 or a double total).',
      'Displays the three results with System.out.println using the labels "Highest: ", "Lowest: " and "Average: ".',
    ),
    starter: J(
      'public class RandomMaxMinAve',
      '{',
      '  public static void main (String [] args)',
      '  {',
      '    int num, max, min, total, i;',
      '    double average;',
      '    // your code here',
      '  } // main method',
      '} // RandomMaxMinAve class',
    ),
    explanation: 'Setting max and min to the first value means every later number is compared with a real value. The else if (num < min) is needed because a number that is not the highest is not necessarily the lowest, and dividing by 100.0 keeps the decimal part of the average.',
    skills: ['U8-S6'],
  },
  'u8-c25': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Exercise 4: Write a program ValidDate. Input the day, month and year into separate int variables. Use a switch on the month to find the number of days in that month, using a boolean variable to check for a leap year in February. Display whether the date is valid.',
    criteria: J(
      'Class must be called ValidDate with a main method.',
      'Inputs day, month and year with JOptionPane.showInputDialog and Integer.parseInt into three separate int variables.',
      'Declares boolean leap and assigns it with the Boolean expression leap = year % 4 == 0; (the textbook rule), not with an if statement.',
      'Uses switch (month): case 4: case 6: case 9: case 11: give 30 days; case 1: case 3: case 5: case 7: case 8: case 10: case 12: give 31 days; case 2: gives 29 days if leap, otherwise 28. Each group ends with break.',
      'A default clause handles an invalid month (e.g. sets the days in the month to 0) so that the date is reported as invalid.',
      'Stores the final check in a boolean variable, e.g. valid = (day >= 1 & day <= daysInMonth);',
      'Displays exactly "Valid date" or "Invalid date" with JOptionPane.showMessageDialog using if (valid).',
      'Correct results: 29/2/2028 Valid date, 29/2/2026 Invalid date, 31/4/2026 Invalid date, 31/12/2026 Valid date, 15/13/2026 Invalid date.',
    ),
    starter: J(
      'import javax.swing.*;',
      '',
      'public class ValidDate',
      '{',
      '  public static void main (String [] args)',
      '  {',
      '    int day, month, year;',
      '    int daysInMonth = 0;',
      '    boolean leap, valid;',
      '    // your code here',
      '  } // main method',
      '} // ValidDate class',
    ),
    explanation: 'Thirty days hath September, April, June and November: these four months share one group of case labels, and the months with 31 days share another. Storing the leap year test and the final range test in boolean variables keeps the if statements short and readable.',
    skills: ['U8-S9', 'U8-S10'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Learn to compare Strings correctly, use switch and case instead of long nested ifs, trace programs with if statements and store conditions in boolean variables.',
  outcomes: [
    'By the end you can compare Strings with equals and equalsIgnoreCase and explain why == must not be used.',
    'By the end you can change Strings to uppercase or lowercase with toUpperCase and toLowerCase.',
    'By the end you can explain how Strings are compared using Unicode values and use compareTo to test alphabetic order.',
    'By the end you can draw a trace table for a program with if statements and use it to find logic errors.',
    'By the end you can decompose and code the algorithm that finds the largest and smallest of a set of values.',
    'By the end you can rewrite multiple if statements as a switch statement with break and default.',
    'By the end you can predict the output of a switch statement, including fall-through when break is missing.',
    'By the end you can state the rules for switch/case and know when an if statement must be used instead.',
    'By the end you can declare boolean variables and rewrite if statements as Boolean expressions.',
  ],
  topics: [
    {
      id: 'U8-T1',
      title: 'Comparing Strings: equals and equalsIgnoreCase',
      sections: ['8.1', '8.1.1'],
      skills: ['U8-S1'],
      explanation: [
        'Variables of type String are objects created from the String class. String name = "Sue"; is a shortened way of writing String name = new String("Sue"); and is allowed because Strings are used so often.',
        'String is not a primitive data type, so methods of the String class must be used with String objects, instead of the operators used with integers, real numbers or characters.',
        'When two Strings are compared, the double equals (==) cannot be used. The equals method must be used instead: if (stg1.equals (stg2)). The equals method takes the second String as a parameter.',
        'Using == with Strings does not produce an error message, but it often gives incorrect output. In Activity 1, typing HELLO with if (stg1 == stg2) still displays The strings are NOT equal.',
        'Capital letters are different to their lowercase equivalents because they have different Unicode code values, so "HELLO".equals("hello") is false.',
        'equalsIgnoreCase ignores the difference between capitals and small letters, so it is useful when you do not want to worry about the case in which the user has entered the data.',
      ],
      vocabulary: [
        { term: 'String object', definition: 'A variable of type String, created from the String class; not a primitive data type.' },
        { term: 'equals', definition: 'String method that returns true if two Strings contain exactly the same characters, including case.' },
        { term: 'equalsIgnoreCase', definition: 'String method that returns true if two Strings are the same when the case of the letters is ignored.' },
      ],
      workedExamples: [
        {
          code: J(
            'String stg1, stg2, message = "";',
            'stg1 = "HELLO";',
            'stg2 = JOptionPane.showInputDialog ("Type in any word and <Enter>");',
            'if (stg1.equals (stg2))',
            '{',
            '    message = "The strings are equal";',
            '}',
            'else',
            '{',
            '    message = "The strings are NOT equal";',
            '}',
            'JOptionPane.showMessageDialog (null, message);',
          ),
          explanation: 'Activity 1 (CompareStrings): typing hello gives NOT equal because h and H have different Unicode values; typing HELLO gives equal.',
        },
      ],
      misconceptions: [
        'Thinking == compares the letters of two Strings. It does not; it often gives the wrong answer, so always use equals.',
        'Thinking the compiler will warn you if you use == with Strings. It compiles without an error message, which makes the bug hard to spot.',
      ],
      questions: [
        {
          id: 'U8-T1-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'Why can two Strings not be compared with == in Java?',
          options: [
            'String is not a primitive type; Strings are objects, so a String method such as equals must be used',
            '== only works with whole numbers and cannot be used with char or double values',
            '== is the assignment operator in Java, so it would change the value of the String',
            'Strings are compared by their length, so == would only check the number of characters',
          ],
          answer: 0,
          hint: 'Think about where String variables come from.',
          explanation: 'Strings are objects created from the String class, not primitive types. Methods of the String class (equals, equalsIgnoreCase) must be used instead of operators.',
          skills: ['U8-S1'],
        },
        {
          id: 'U8-T1-Q2',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: Using == to compare two Strings gives a compile error, so the program will not run.',
          answer: false,
          hint: 'Read the NOTE after Activity 1 again.',
          explanation: 'Using == with Strings does not produce an error message, but it often gives incorrect output (or no output at all in some cases).',
          skills: ['U8-S1'],
        },
        {
          id: 'U8-T1-Q3',
          type: 'mc',
          category: 'predict',
          prompt: 'CompareStrings now uses equalsIgnoreCase. The user types hElLo. What is displayed?',
          code: J(
            'stg1 = "HELLO";',
            'stg2 = JOptionPane.showInputDialog ("Type in any word and <Enter>");',
            'if (stg1.equalsIgnoreCase(stg2))',
            '{',
            '    message = "The strings are equal";',
            '}',
            'else',
            '{',
            '    message = "The strings are NOT equal";',
            '}',
            'JOptionPane.showMessageDialog (null, message);',
          ),
          options: [
            'The strings are NOT equal',
            'hElLo',
            'The strings are equal',
            'HELLO',
          ],
          answer: 2,
          hint: 'Which differences does equalsIgnoreCase ignore?',
          explanation: 'equalsIgnoreCase treats capitals and small letters as the same, so hElLo matches HELLO and message is The strings are equal.',
          skills: ['U8-S1'],
        },
      ],
    },
    {
      id: 'U8-T2',
      title: 'toLowerCase and toUpperCase',
      sections: ['8.1.2'],
      skills: ['U8-S2', 'U8-S1'],
      explanation: [
        'Instead of using equalsIgnoreCase, you can change both Strings to uppercase or both to lowercase before comparing them with equals.',
        'The String class provides toLowerCase() and toUpperCase() to change all the characters in a String. If a character is not a letter, it remains the same.',
        'The method can be applied straight after showInputDialog, e.g. JOptionPane.showInputDialog("Type in any word and <Enter>").toLowerCase(), or to a String variable: stg1 = stg1.toLowerCase();',
        'toUpperCase() is a String method, so it must be used on the String BEFORE converting to a char with charAt(): ...showInputDialog(...).toUpperCase().charAt(0).',
        'If you convert the input to uppercase, the cases or conditions you check must use capital letters. Converting to uppercase but checking for lowercase is a common error.',
        'Exercise 1 question 2: day.equals("Monday") is false if the user types MONDAY. Using day.equalsIgnoreCase("Monday") lets the day be typed in any case.',
      ],
      vocabulary: [
        { term: 'toLowerCase()', definition: 'String method that returns the String with all letters changed to lowercase; other characters stay the same.' },
        { term: 'toUpperCase()', definition: 'String method that returns the String with all letters changed to uppercase; other characters stay the same.' },
      ],
      workedExamples: [
        {
          code: J(
            'String stg1, stg2;',
            'stg1 = "HELLO";',
            'stg2 = JOptionPane.showInputDialog',
            '     ("Type in any word and <Enter>").toLowerCase();',
            'stg1 = stg1.toLowerCase();',
            'if (stg1.equals (stg2)) ...',
          ),
          explanation: 'Activity 2: both Strings are lowercase before equals is used, so hello, HELLO and HeLlo are all equal.',
        },
        {
          code: J(
            `String input = JOptionPane.showInputDialog ("Choose from '1'-sing, '2'-cry, '3'-laugh, 'x'-finish: ");`,
            'input = input.toUpperCase ();',
            'ch = input.charAt (0);',
          ),
          explanation: 'The same input statement written in separate lines: convert the String first, then take the first character.',
        },
      ],
      misconceptions: [
        'Thinking toUpperCase can be called on a char after charAt(0). It is a String method, so it must come before charAt(0).',
        'Thinking toUpperCase changes digits or symbols. Characters that are not letters remain the same.',
      ],
      questions: [
        {
          id: 'U8-T2-Q1',
          type: 'mc',
          category: 'predict',
          prompt: 'What is stored in code after this statement?',
          code: 'String code = "Grade 10a".toUpperCase();',
          options: [
            'Grade 10A',
            'GRADE 10A',
            'GRADE 10a',
            'grade 10a',
          ],
          answer: 1,
          hint: 'Every letter changes; anything that is not a letter stays the same.',
          explanation: 'toUpperCase changes every letter to a capital (including the a at the end) and leaves the space and digits unchanged: GRADE 10A.',
          skills: ['U8-S2'],
        },
        {
          id: 'U8-T2-Q2',
          type: 'mc',
          category: 'apply',
          prompt: 'In Exercise 1 question 2 the user types MONDAY and then y. What happens?',
          code: J(
            'if (publicHol == \'Y\' | publicHol == \'y\' &&',
            '    (day.equals ("Monday") | day.equals ("Friday")))',
            '{',
            '     longWeekend = \'Y\';',
            '}',
          ),
          options: [
            `longWeekend becomes 'Y', because MONDAY is a Monday`,
            'A compile error occurs, because MONDAY is typed in capitals',
            'The program crashes, because equals cannot handle capital letters',
            `day.equals("Monday") is false, so longWeekend is not set; equalsIgnoreCase fixes this`,
          ],
          answer: 3,
          hint: 'Does equals treat MONDAY and Monday as the same?',
          explanation: 'equals compares the case of every letter, so MONDAY is not equal to Monday and the day check is false. Using day.equalsIgnoreCase("Monday") and day.equalsIgnoreCase("Friday") lets the day be typed in any case.',
          skills: ['U8-S2', 'U8-S1'],
        },
        {
          id: 'U8-T2-Q3',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: JOptionPane.showInputDialog("Choice").charAt(0).toUpperCase() is a correct way to convert the first character of the input to a capital.',
          answer: false,
          hint: 'Which data type does toUpperCase() work with?',
          explanation: 'toUpperCase() is a String method, so it must be used on the String before charAt(0) converts it to a char: showInputDialog("Choice").toUpperCase().charAt(0).',
          skills: ['U8-S2'],
        },
      ],
    },
    {
      id: 'U8-T3',
      title: 'How Strings are compared and compareTo',
      sections: ['8.1.3', '8.1.4'],
      skills: ['U8-S3', 'U8-S4'],
      explanation: [
        'When the computer compares Strings it looks at each character individually. Each character has a numerical code value in the Unicode table, so the computer is really comparing numbers.',
        'If the words are not the same length, the textbook explains that spaces are added to the end of the shorter word before comparing. For "HELLO" and "hello" the first characters H (72) and h (104) are not equal, so the Strings are not equal.',
        'For similar Strings such as "Garth" and "Gareth" the computer compares the first letters, then the second letters and so on until the Unicode values differ. The fourth letters are t (116) and e (101); 101 is less than 116, so "Gareth" is less than "Garth".',
        'In the Unicode table the digits 0-9 come before the capitals, and then come the small letters, so "GARTH" < "Garth" < "garth". A space (32) comes before all of them.',
        'word1.compareTo(word2) subtracts the Unicode values of the first characters that differ. A result < 0 means word1 comes first alphabetically; 0 means the Strings are equal; a positive result means word2 comes first.',
        '"carrots".compareTo("broccoli") is 99 - 98 = 1, which is NOT < 0, so broccoli comes before carrots. "Sugar".compareTo("Super") compares g and p: 103 - 112 = -9, which IS < 0, so Sugar comes before Super.',
        'compareTo can also test equality: if (wrd1.compareTo(wrd2) == 0) is true when both words are the same (Activity 4).',
      ],
      vocabulary: [
        { term: 'Unicode code value', definition: 'The number that represents a character in the Unicode table, e.g. A = 65, a = 97, 0 = 48, space = 32.' },
        { term: 'compareTo', definition: 'String method that compares two Strings character by character and returns the difference in Unicode values of the first characters that differ.' },
        { term: 'Alphabetic order', definition: 'The order Java gives Strings by comparing their Unicode values; capitals come before small letters.' },
      ],
      workedExamples: [
        {
          code: J(
            'String word1, word2;',
            'word1 = "carrots";',
            'word2 = "broccoli";',
            'System.out.println("ALPHABETIC ORDER");',
            'if ( word1.compareTo(word2) < 0 )',
            '{',
            '    System.out.print (word1 + " comes before " + word2);',
            '}',
            'else',
            '{',
            '    System.out.print ( word2 + " comes before " + word1);',
            '}',
          ),
          explanation: 'Activity 3 (AlphOrder): c - b = 99 - 98 = 1, which is not < 0, so it prints broccoli comes before carrots.',
        },
        {
          code: J(
            'String wrd1 = "cool";',
            'String wrd2 = "cool";',
            'if (wrd1.compareTo(wrd2) == 0)',
            '{ System.out.println( wrd1 + " equals " + wrd2); }',
            'else',
            '{ System.out.println( wrd1 + " does not equal " + wrd2); }',
          ),
          explanation: 'Activity 4: compareTo returns 0 when the Strings are equal; the else clause displays a message when they are not.',
        },
      ],
      misconceptions: [
        'Thinking the longer word always comes last. "singer" comes after "sing softly" because e (101) is greater than a space (32).',
        'Thinking compareTo returns true or false. It returns an int; you test whether it is < 0, == 0 or > 0.',
        'Thinking "14" > "99" because 14 is a smaller number. As Strings, the first characters 1 and 9 are compared, so "14" comes first.',
      ],
      questions: [
        {
          id: 'U8-T3-Q1',
          type: 'tf',
          category: 'calculate',
          prompt: 'True or false (Check Point 1): As Strings, "Andy" > "Andrew", so "Andy".compareTo("Andrew") is positive.',
          answer: true,
          hint: 'The first three letters match. Compare y (121) with r (114).',
          explanation: 'The first different characters are y (121) and r (114). 121 - 114 = 7, which is positive, so "Andy" comes after "Andrew".',
          skills: ['U8-S3', 'U8-S4'],
        },
        {
          id: 'U8-T3-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'When "Gareth" is compared with "Garth", which characters decide the result?',
          options: [
            'e (101) and t (116), so "Gareth" is less than "Garth"',
            'h (104) and a space (32), so "Garth" is less than "Gareth"',
            'G (71) and G (71), so the two Strings are equal',
            'The lengths 6 and 5, so "Garth" is less than "Gareth"',
          ],
          answer: 0,
          hint: 'Compare letter by letter until the first difference.',
          explanation: 'G, a and r are the same. The fourth letters are e (101) and t (116); 101 is less than 116, so "Gareth" is less than "Garth". The rest of the word is not checked.',
          skills: ['U8-S3'],
        },
        {
          id: 'U8-T3-Q3',
          type: 'order',
          category: 'sequence',
          prompt: 'Arrange these Strings in the order Java puts them, from smallest to largest.',
          items: ['"Garth"', '"14"', '"garth"', '"GARTH"', '"99"'],
          answer: [1, 4, 3, 0, 2],
          hint: 'Digits come before capitals, which come before small letters. Compare the first character first.',
          explanation: 'Digits (48-57) come before capitals (65-90), which come before small letters (97-122). "14" < "99" (1 before 9), then "GARTH" < "Garth" (A 65 is less than a 97), then "garth".',
          skills: ['U8-S3', 'U8-S4'],
        },
      ],
    },
    {
      id: 'U8-T4',
      title: 'Trace tables with the if statement',
      sections: ['8.2'],
      skills: ['U8-S5'],
      explanation: [
        'A trace table helps you find logic errors by working through a program line by line with test data, the way the computer would.',
        'Use a column for every variable and a column for every condition. A line number column is useful but not essential. Remember to show the screen output.',
        'Earrings example: the first four pairs cost R30 each and the rest cost 85% of the full price of R50. With 6 pairs the program calculates 4*30 + 6*50*85/100 = 120 + 255 = 375, but the customer correctly says she owes R205.00.',
        'The fix is to charge only the extra pairs at 85%: price = 4*30 + (qty - 4)*50*85/100; which gives 120 + 85 = 205. Test again with 6 and with 3 (3 pairs: 3*30 = 90).',
        'Exercise 1 (Candles): sal = 600.0, a bonus of 10% of sal is paid if tot > 5000, and a further R400 if ave > 1200. With sales of 1200, 1345, 1842 and 1903: tot = 6290.0, ave = 1572.5 and bonus = 60.0 + 400 = 460.0.',
        'The Candles program also has errors to correct: it uses message1 and message2 instead of msg1 and msg2, uses showInputDialog instead of showMessageDialog, and congratulates the seller even when the bonus is R0.0.',
      ],
      vocabulary: [
        { term: 'Trace table', definition: 'A table with a column for every variable and condition, used to follow the values in a program line by line and find errors.' },
        { term: 'Logic error', definition: 'An error that lets the program run but produces incorrect output, such as charging every pair of earrings at 85%.' },
      ],
      workedExamples: [
        {
          code: J(
            'Line  qty  price  qty <= 4?',
            '1     6',
            '2               false',
            '4          375.0',
            '5     OUTPUT: You owe R375.0',
          ),
          explanation: 'Trace table for the earrings program with 6 as data, showing why the customer was overcharged.',
        },
        {
          code: J(
            'int qty;',
            'double price;',
            'qty = Integer.parseInt (JOptionPane.showInputDialog ("How many pairs?"));',
            'if (qty <= 4)',
            '{',
            '    price = qty * 30;',
            '}',
            'else',
            '{',
            '    price = 4*30 + (qty - 4)*50*85/100;',
            '}',
            'System.out.println ("You owe R" + price);',
          ),
          explanation: 'The corrected program: with 6 pairs it displays You owe R205.0.',
        },
      ],
      misconceptions: [
        'Thinking a program that runs without error messages must be correct. Logic errors only show up when you check the output with test data, e.g. in a trace table.',
        'Thinking a trace table only needs columns for the variables. You also need a column for every condition so you can see which branch is taken.',
      ],
      questions: [
        {
          id: 'U8-T4-Q1',
          type: 'trace',
          category: 'calculate',
          prompt: 'Trace the Candles calculation with sales of R1200, R1345, R1842 and R1903. Type doubles the way Java prints them (e.g. 12.0).',
          code: J(
            'int sales1 = 1200, sales2 = 1345, sales3 = 1842, sales4 = 1903;',
            'double tot, ave, bonus;',
            'double sal = 600.0;',
            'bonus = 0;',
            'tot = sales1 + sales2 + sales3 + sales4;',
            'ave = tot / 4;',
            'if (tot > 5000)',
            '{',
            '     bonus = sal * 10 / 100;',
            '}',
            'if (ave > 1200)',
            '{',
            '     bonus = bonus + 400;',
            '}',
          ),
          rows: [
            { label: 'tot', answer: '6290.0' },
            { label: 'ave', answer: '1572.5' },
            { label: 'bonus after the first if', answer: '60.0' },
            { label: 'bonus at the end', answer: '460.0' },
          ],
          hint: 'tot is a double, so tot / 4 keeps the decimal part.',
          explanation: '1200 + 1345 + 1842 + 1903 = 6290, stored as 6290.0. 6290.0 / 4 = 1572.5. tot > 5000 so bonus = 600.0 * 10 / 100 = 60.0, and ave > 1200 so bonus = 460.0.',
          skills: ['U8-S5'],
        },
        {
          id: 'U8-T4-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'Candles is run with sales of R800, R1000, R986 and R1500 (tot = 4286.0, ave = 1071.5). What is strange about the output and how should it be fixed?',
          options: [
            'The salary is shown as R0.0; sal must be declared as an int',
            'The average is wrong, because tot / 4 uses integer division',
            'It still says Congratulations! Your bonus is R0.0; the bonus message should only be shown if bonus > 0',
            'Nothing is strange; a bonus of R400 is correctly paid',
          ],
          answer: 2,
          hint: 'Neither condition is true. What does msg2 still say?',
          explanation: 'Neither tot > 5000 nor ave > 1200 is true, so bonus stays 0.0, but msg2 is always displayed. The program should only display the bonus message if a bonus was earned.',
          skills: ['U8-S5'],
        },
        {
          id: 'U8-T4-Q3',
          type: 'mc',
          category: 'identify',
          prompt: 'The last statement of Candles is shown below. What must be corrected?',
          code: J(
            'String msg1 = "Your salary cheque for R "+ sal',
            '      +" has been mailed to you.\\n";',
            'String msg2 = "Congratulations! Your bonus is R" + bonus;',
            'JOptionPane.showInputDialog (null, message1 + message2);',
          ),
          options: [
            'The word null must be removed from showInputDialog',
            'The variables are msg1 and msg2, not message1 and message2, and showMessageDialog should be used',
            'The \\n inside msg1 is not allowed in a String',
            'A String cannot be joined to a double with +',
          ],
          answer: 1,
          hint: 'Compare the variable names that were declared with the ones that are used.',
          explanation: 'message1 and message2 were never declared, which is a compile error. The program also needs to display output, so showMessageDialog(null, msg1 + msg2) is the correct method.',
          skills: ['U8-S5'],
        },
      ],
    },
    {
      id: 'U8-T5',
      title: 'Determining the largest and smallest',
      sections: ['8.3', '8.3.1'],
      skills: ['U8-S6'],
      explanation: [
        'A common programming problem is to find the largest and smallest of a set of values, e.g. 10 numbers entered by the user.',
        'Input the first number and use it to set both the highest and lowest variables. Each later number is compared to the highest and lowest: if it is higher it replaces the highest; if it is lower it replaces the lowest.',
        'IPO is not suitable for decomposing this problem, because values are input inside the loop, blurring the input and processing tasks. Instead the problem is broken into three main tasks: Task 1 input the first number and set max and min, Task 2 repeat for the remaining 9 numbers (repetition), Task 3 display the result.',
        'Zooming into Task 2 (abstraction) decomposes it further: repeat 9 times, input the next number, determine if it is the largest or smallest (Task 4). Zooming into Task 4 gives the nested if.',
        'Algorithm: input num, max = num, min = num; for i = 2 to 10: input num; if num > max then max = num else if num < min then min = num; end for; display max, min.',
        'The second if must check num < min. We cannot assume that if a number is not the highest then it must be the smallest!',
        'Exercise 2 extends MaxMin to calculate the average, and RandomMaxMinAve randomly generates 100 numbers between 1 and 200 with (int) (Math.random() * 200) + 1.',
      ],
      vocabulary: [
        { term: 'Decomposition', definition: 'Breaking a problem into smaller tasks, e.g. the three main tasks of the MaxMin problem.' },
        { term: 'Abstraction', definition: 'Zooming into one task to work out its details while ignoring the rest, e.g. zooming into Task 2 and Task 4.' },
        { term: 'Repetition', definition: 'Repeating a set of steps in a loop, e.g. inputting and comparing the remaining 9 numbers.' },
      ],
      workedExamples: [
        {
          code: J(
            'begin',
            '   input num',
            '   max <- num',
            '   min <- num',
            '   for i <- 2 to 10; inc i by 1',
            '      input num',
            '      if num > max',
            '         then max <- num',
            '         else',
            '            if num < min',
            '               then min <- num',
            '      end if',
            '   end for',
            '   display max, min',
            'end',
          ),
          explanation: 'The combined pseudocode for Tasks 1 to 4; Activity 5 codes it as the Java program MaxMin.',
        },
      ],
      misconceptions: [
        'Thinking max and min should start at 0. If all the numbers are positive, min would stay 0; the first number must set both.',
        'Thinking a number that is not the largest must be the smallest. An extra check (num < min) is needed.',
      ],
      questions: [
        {
          id: 'U8-T5-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'Why is IPO not suitable for decomposing the largest-and-smallest problem?',
          options: [
            'There is no output in this problem',
            'IPO can only be used for problems that have a single input',
            'The problem has no processing, only comparisons',
            'Values are input inside the loop, which blurs the input and processing tasks',
          ],
          answer: 3,
          hint: 'Where do the inputs happen in this algorithm?',
          explanation: 'Because numbers are input inside the loop, input and processing are mixed. The problem is rather broken into three main tasks.',
          skills: ['U8-S6'],
        },
        {
          id: 'U8-T5-Q2',
          type: 'trace',
          category: 'predict',
          prompt: 'The user enters 8, 22, 4 and 10 (in that order) inside the loop. Fill in the values.',
          code: J(
            'int num, max, min, i;',
            'num = 15;',
            'max = num;',
            'min = num;',
            'for (i = 2; i <= 5; i++)',
            '{',
            '    num = Integer.parseInt (JOptionPane.showInputDialog ("Next number"));',
            '    if (num > max)',
            '    { max = num; }',
            '    else',
            '    if (num < min)',
            '    { min = num; }',
            '}',
          ),
          rows: [
            { label: 'min after 8 is entered', answer: '8' },
            { label: 'max after 22 is entered', answer: '22' },
            { label: 'min at the end', answer: '4' },
            { label: 'Number of times min changes in the loop', answer: '2' },
          ],
          hint: 'Check num > max first; only if that is false, check num < min.',
          explanation: '8 is not > 15 but is < 15, so min = 8. 22 > 15, so max = 22. 4 < 8, so min = 4. 10 is neither, so nothing changes. min changed twice (8 and 4).',
          skills: ['U8-S6'],
        },
        {
          id: 'U8-T5-Q3',
          type: 'tf',
          category: 'classify',
          prompt: 'True or false: Zooming into Task 2 to decompose it into smaller steps is an example of abstraction.',
          answer: true,
          hint: 'The textbook puts a word in brackets next to "zoom into".',
          explanation: 'The textbook says "We can zoom into (abstraction) Task 2". Zooming into one task lets you focus on its details.',
          skills: ['U8-S6'],
        },
      ],
    },
    {
      id: 'U8-T6',
      title: 'Using a switch instead of multiple ifs',
      sections: ['8.4'],
      skills: ['U8-S7'],
      explanation: [
        'Instead of using several if ... else statements, it is sometimes easier and neater to use switch and case.',
        'In LetterGrade2 the value of markDiv10 = mark / 10 is placed in brackets after switch, and each possible value has a case label followed by a colon.',
        'The statements in each case clause are not enclosed in curly brackets (although they can be). The break statement at the end of each case clause makes the program exit the switch statement.',
        'When several cases result in the same action, each value gets its own case label: case 8: case 9: case 10: is equivalent to having no statements in the case 8 and case 9 clauses, so all three carry out the statements of the case 10 clause.',
        'It is usual to include a default alternative in case a value does not fit any case category, e.g. default: System.out.println("Mark incorrect, no grade applies");',
        'Testing with 80, 38, 51, 90, 66 and 70 gives A, F, D, A, C and B. Because grade starts as X, the output statement is put in if (mark >= 0 & mark <= 100) so a grade is only displayed for a valid mark.',
      ],
      vocabulary: [
        { term: 'switch', definition: 'A statement that chooses which block of code to run by matching the value in brackets to a case label.' },
        { term: 'case label', definition: 'A value followed by a colon inside a switch, e.g. case 7:, marking where execution starts for that value.' },
        { term: 'default', definition: 'The optional switch alternative that runs when no case label matches the value.' },
      ],
      workedExamples: [
        {
          code: J(
            'markDiv10 = mark / 10;',
            'switch (markDiv10)',
            '{',
            '   case 8: case 9: case 10:',
            `      grade = 'A';`,
            '      break;',
            '   case 7:',
            `      grade = 'B';`,
            '      break;',
            '   case 6:',
            `      grade = 'C';`,
            '      break;',
            '   case 5:',
            `      grade = 'D';`,
            '      break;',
            '   case 4:',
            `      grade = 'E';`,
            '      break;',
            '   case 3: case 2: case 1: case 0:',
            `      grade = 'F';`,
            '      break;',
            '   default:',
            '      System.out.println ("Mark incorrect, no grade applies");',
            '} // end switch',
          ),
          explanation: 'Activity 6 (LetterGrade2): the nested if from Unit 7 rewritten as a switch with a default.',
        },
      ],
      misconceptions: [
        'Thinking the statements in each case must be in curly brackets. They can be, but it is not necessary.',
        'Thinking you can write case 8, 9, 10: for several values. Each value needs the word case in front of it and a colon after it.',
      ],
      questions: [
        {
          id: 'U8-T6-Q1',
          type: 'mc',
          category: 'apply',
          prompt: 'Using the LetterGrade2 switch, which of these marks displays the symbol B?',
          options: ['69', '70', '80', '100'],
          answer: 1,
          hint: 'Work out mark / 10 with integer division for each option.',
          explanation: '70 / 10 = 7, which matches case 7 and gives B. 69 / 10 = 6 gives C, and 80 and 100 give A.',
          skills: ['U8-S7'],
        },
        {
          id: 'U8-T6-Q2',
          type: 'tf',
          category: 'identify',
          prompt: 'True or false: In a switch statement the statements in each case clause must be enclosed in curly brackets.',
          answer: false,
          hint: 'Look at how LetterGrade2 is laid out.',
          explanation: 'The statements in each case clause are not enclosed in curly brackets, although they can be. The break statement marks the end of each case clause.',
          skills: ['U8-S7'],
        },
      ],
    },
    {
      id: 'U8-T7',
      title: 'How a switch statement works and the break statement',
      sections: ['8.4.1', '8.4.1.1'],
      skills: ['U8-S8'],
      explanation: [
        'When a switch statement executes, the interpreter computes the value of the expression in brackets after switch, then looks for a case label that matches that value.',
        'If it finds a match, it starts executing at the first statement following the matching case label. If there is no match it starts at the first statement after default:. If there is no default: label, it skips the body of the switch altogether and carries on with the rest of the program.',
        'The matching case label is only the starting point. The cases are not independent blocks of code and have no implicit ending point, so the end of each case clause must be specified with a break statement.',
        'Investigation of break: with every break commented out and 78 entered, execution starts at grade = \'B\' and continues to the end of the switch, assigning C, D, E and then F. The final grade is F because each value overwrites the previous one.',
        'Activity 7 (Respond): the values tested can be single characters, which must then be in single quotes, e.g. case \'1\':. Typing 2 displays Boo hoo; 4 or a capital X displays I don\'t understand, because they match no case label.',
        'No break is needed after the default clause because it is the last clause; the switch ends there anyway.',
        'Exercise 3: the Greet program (Afrikaans, English, Zulu, plus a Sotho option displaying Dumela for \'S\') is rewritten with switch and case and a default for invalid options.',
      ],
      vocabulary: [
        { term: 'break', definition: 'A statement that causes the interpreter to exit the switch block after the statements of a case clause.' },
        { term: 'Fall-through', definition: 'When break is left out, execution continues into the statements of the following case clauses until a break or the end of the switch.' },
      ],
      workedExamples: [
        {
          code: J(
            'char ch;',
            `ch = JOptionPane.showInputDialog ("Choose from '1'-sing, '2'-cry, '3'-laugh,'x'-finish:").charAt(0);`,
            'switch (ch)',
            '{',
            `case '1':`,
            '    System.out.println ("La la");',
            '    break;',
            `case '2':`,
            '    System.out.println ("Boo hoo");',
            '    break;',
            `case '3':`,
            '    System.out.println ("Ha ha");',
            '    break;',
            `case 'x':`,
            '    System.out.println ("See you later");',
            '    break;',
            'default:',
            `    System.out.println ("I don't understand");`,
            '} // end switch',
          ),
          explanation: `Activity 7 (Respond): char case labels in single quotes. To accept a capital X as well, add case 'X': directly before case 'x':.`,
        },
      ],
      misconceptions: [
        'Thinking each case is a separate block that stops by itself. Without break, execution continues into the next cases.',
        `Thinking case 'x' also matches 'X'. Capital and small letters have different Unicode values, so they are different chars.`,
      ],
      questions: [
        {
          id: 'U8-T7-Q1',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps of how a switch statement executes (when a matching case is found) in order.',
          items: [
            'Exit the switch block and carry on with the rest of the program',
            'Compute the value of the expression in brackets after switch',
            'Keep executing statements until a break statement is reached',
            'Look for a case label that matches the value',
            'Start executing at the first statement after the matching case label',
          ],
          answer: [1, 3, 4, 2, 0],
          hint: 'The value has to be known before it can be matched.',
          explanation: 'The interpreter computes the value, finds the matching case label, starts at the statement after it, continues until a break, and then exits the switch.',
          skills: ['U8-S8'],
        },
        {
          id: 'U8-T7-Q2',
          type: 'mc',
          category: 'predict',
          prompt: `In the Respond program (Activity 7, without toUpperCase), the user types 4. What is displayed?`,
          options: [
            `I don't understand`,
            'Ha ha',
            'Nothing, because the program skips the switch',
            'See you later',
          ],
          answer: 0,
          hint: `The case labels are '1', '2', '3' and 'x'.`,
          explanation: `No case label matches '4', so execution starts at the first statement after default: and I don't understand is displayed.`,
          skills: ['U8-S8'],
        },
        {
          id: 'U8-T7-Q3',
          type: 'mc',
          category: 'explain',
          prompt: 'Why is there no break; after the output statement in the default clause of Respond?',
          options: [
            'break is not allowed after default',
            'Without break, the program loops back to the first case',
            'default is the last clause, so the switch ends there anyway',
            'default always runs, so it does not need to exit',
          ],
          answer: 2,
          hint: 'What comes after the default clause in this switch?',
          explanation: 'The default clause is the last part of the switch block, so after its statement the switch ends anyway. A break there is allowed but not needed.',
          skills: ['U8-S8'],
        },
      ],
    },
    {
      id: 'U8-T8',
      title: 'Important points on the switch/case statement',
      sections: ['8.4.2'],
      skills: ['U8-S9'],
      explanation: [
        'The logic of switch/case is similar to a nested if statement: only one of the options is executed, if break is used at the end of each case section. Line up the case labels and the colons.',
        'The int or char type variable whose value is tested is put in brackets after the word switch. If a char variable is used, the case labels must be in single quote marks.',
        'Each case label can have only one unique value. No ranges such as 0..9 can be used; you must list case 0: case 1: ... case 9:. Relational operators such as num > 0 may not be used; then you must use an if statement instead.',
        'If more than one value has the same output, each value needs the word case in front and a colon after. Statements for a case may be put in curly brackets, but they are not essential.',
        'If break is left out (e.g. after case 10:), the next case output statements are also carried out until a break: entering 10 prints Too high and More than 10. A statement after the switch is displayed every time.',
        'All switch statements can be written as nested if statements, but not the reverse: if (a > b) ... if (b < 10) cannot be a switch because it uses relational operators.',
        'Exercise 4 uses switch for an Arithmetic menu, ValidDate (days in each month; February 29 days in a leap year), SportingEvents (Olympics in a leap year, cricket world cup two years after, rugby world cup three years after) and RockPaperScissors (computer option minus user option: 1 or -2 computer wins, -1 or 2 user wins, 0 draw).',
      ],
      vocabulary: [
        { term: 'Unique case value', definition: 'Each case label holds exactly one value, and the same value may not appear in two case labels.' },
        { term: 'Switch expression', definition: 'The int or char value in brackets after switch that is matched against the case labels.' },
      ],
      workedExamples: [
        {
          code: J(
            'switch (year % 4)',
            '{',
            '   case 0:',
            '      System.out.println ("Olympics");',
            '      break;',
            '   case 2:',
            '      System.out.println ("Cricket world cup");',
            '      break;',
            '   case 3:',
            '      System.out.println ("Rugby world cup");',
            '      break;',
            '   default:',
            '      System.out.println ("No event this year");',
            '}',
          ),
          explanation: 'SportingEvents: a leap year has year % 4 == 0, so the remainder tells how many years after a leap year it is. 2027 % 4 = 3 gives the rugby world cup.',
        },
      ],
      misconceptions: [
        'Thinking a switch can test a range such as case 0..9 or a condition such as case > 0. Each case is one fixed value.',
        'Thinking a switch can test a double such as a pH value. The textbook uses int or char values only; ranges of real numbers need an if.',
      ],
      questions: [
        {
          id: 'U8-T8-Q1',
          type: 'mc',
          category: 'classify',
          prompt: 'According to the textbook, which of these can be put in the brackets after switch?',
          options: [
            'double pH',
            'boolean leap',
            'a condition such as num > 0',
            'char option',
          ],
          answer: 3,
          hint: 'The textbook names two types that may be used.',
          explanation: 'The value tested by a switch is an int or char variable. A double, a boolean or a relational condition cannot be used; use an if statement instead.',
          skills: ['U8-S9'],
        },
        {
          id: 'U8-T8-Q2',
          type: 'tf',
          category: 'define',
          prompt: 'True or false: Each case label can have only one unique value, and ranges such as 0..9 cannot be used.',
          answer: true,
          hint: 'How does the textbook say you must handle the values 0 to 9?',
          explanation: 'Each case label has one unique value. To handle 0 to 9 you must list case 0: case 1: ... case 9:.',
          skills: ['U8-S9'],
        },
        {
          id: 'U8-T8-Q3',
          type: 'mc',
          category: 'explain',
          prompt: 'Check Point 2, question 6: Why can this nested if not be converted to a switch statement?',
          code: J(
            'if (a > b)',
            '    if (b < 10){a = b * 2;}',
            '        else { a = b * b; }',
          ),
          options: [
            'It compares variables with relational operators (a > b, b < 10), but case labels can only be single fixed values',
            'A switch cannot contain assignment statements such as a = b * 2',
            'A nested if with an else cannot be written as a switch, because switch has no default',
            'switch can only test char variables, and a and b are int',
          ],
          answer: 0,
          hint: 'What is not allowed after the word case?',
          explanation: 'Relational operators may not be used in case labels, and a > b compares two variables rather than matching one value. A switch only matches exact values.',
          skills: ['U8-S9'],
        },
        {
          id: 'U8-T8-Q4',
          type: 'mc',
          category: 'identify',
          prompt: 'Check Point 2, question 4.3: Which answer lists the compilation errors in this switch?',
          code: J(
            'switch opt',
            'case 1: case 2: case 3:',
            '    System.out.println("options 1,2,3");',
            'default :',
            '    System.out.println("none of the above");',
            'case 4: 5: 6:',
            '    System.out.println("the rest");',
          ),
          options: [
            'default must be the very last clause, otherwise it is a compile error',
            'opt needs brackets, the body needs curly brackets, and 5 and 6 each need the word case',
            'The case labels must be in single quotes because opt is a menu option',
            'Only the missing break statements are errors',
          ],
          answer: 1,
          hint: 'Compare it with the layout of a correct switch: switch (num) { case 1: ... }.',
          explanation: 'The expression must be in brackets, switch (opt), the body needs { }, and every value needs the word case: case 4: case 5: case 6:. Missing breaks cause fall-through, which is a logic problem rather than a compile error.',
          skills: ['U8-S9'],
        },
      ],
    },
    {
      id: 'U8-T9',
      title: 'Boolean variables',
      sections: ['8.5'],
      skills: ['U8-S10'],
      explanation: [
        'The name Boolean comes from the 19th-century computer pioneer George Boole, an English logician and mathematician.',
        'In if (option == \'A\') the condition is option == \'A\'. Its result is not stored in memory; the computer simply checks it and displays a message.',
        'When we want to store the result of a condition we use a boolean variable, which can only hold true or false.',
        'In Activity 8 (Boole1), leap = year % 4 == 0; Java finds year % 4 and checks if the answer is 0. If it is 0, leap gets the value true, otherwise false.',
        'It is not necessary to write if (leap == true); if (leap) does the same job.',
      ],
      vocabulary: [
        { term: 'boolean', definition: 'A Java data type whose variables can only store true or false, the result of a condition.' },
        { term: 'George Boole', definition: '19th-century English logician and mathematician after whom Boolean values are named.' },
      ],
      workedExamples: [
        {
          code: J(
            'int year;',
            'boolean leap;',
            'year = Integer.parseInt(JOptionPane.showInputDialog ("Enter the year"));',
            'leap = year % 4 == 0;',
            'if (leap)',
            '{',
            '    System.out.println("leap year");',
            '}',
            'else',
            '{',
            '    System.out.println("not a leap year");',
            '}',
          ),
          explanation: 'Activity 8 (Boole1): the result of year % 4 == 0 is stored in leap and then used as the if condition.',
        },
      ],
      misconceptions: [
        'Thinking a boolean must be compared with true in an if, as in if (leap == true). The variable itself is already true or false.',
        'Thinking the result of a condition is always stored somewhere. In a plain if statement it is only checked, not stored.',
      ],
      questions: [
        {
          id: 'U8-T9-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'Who is the boolean data type named after?',
          options: [
            'Alan Turing, the British computer scientist',
            'Charles Babbage, inventor of the Analytical Engine',
            'George Boole, a 19th-century English logician and mathematician',
            'Ada Lovelace, often called the first programmer',
          ],
          answer: 2,
          hint: 'Listen to the sound of the word Boolean.',
          explanation: 'The name Boolean comes from George Boole, a 19th-century English logician and mathematician.',
          skills: ['U8-S10'],
        },
        {
          id: 'U8-T9-Q2',
          type: 'trace',
          category: 'predict',
          prompt: 'Run Boole1 with each year. Type true or false for leap, and the exact output.',
          code: J(
            'leap = year % 4 == 0;',
            'if (leap)',
            '{',
            '    System.out.println("leap year");',
            '}',
            'else',
            '{',
            '    System.out.println("not a leap year");',
            '}',
          ),
          rows: [
            { label: 'year = 2028: leap', answer: 'true' },
            { label: 'year = 2028: output', answer: 'leap year' },
            { label: 'year = 2026: leap', answer: 'false' },
            { label: 'year = 2026: output', answer: 'not a leap year' },
          ],
          hint: 'Work out the remainder when the year is divided by 4.',
          explanation: '2028 % 4 = 0, so leap is true and leap year is displayed. 2026 % 4 = 2, so leap is false and not a leap year is displayed.',
          skills: ['U8-S10'],
        },
        {
          id: 'U8-T9-Q3',
          type: 'tf',
          category: 'distinguish',
          prompt: 'True or false: if (leap) does exactly the same as if (leap == true) when leap is a boolean variable.',
          answer: true,
          hint: 'What value does leap already hold?',
          explanation: 'leap already holds true or false, so it can be used directly as the condition. The textbook notes that it is not necessary to say if (leap == true).',
          skills: ['U8-S10'],
        },
      ],
    },
    {
      id: 'U8-T10',
      title: 'Important points on Boolean expressions',
      sections: ['8.5.1'],
      skills: ['U8-S11', 'U8-S10'],
      explanation: [
        'Boolean variables can only store the results of Boolean expressions, i.e. expressions that test a condition. They only have two values: true and false (in Java we can think of false = 0 and true = 1).',
        'A Boolean variable always gets a value when an assignment such as even_no = (num % 2 == 0); is completed. With if (num % 2 == 0) {even_no = true;} it gets no value when num is odd.',
        'Any condition in an if statement can be rewritten as a Boolean expression and vice versa. The results are not Strings, so do not put true or false in quote marks.',
        'Many programmers think it is better to use a boolean variable than a long expression in an if, e.g. teenager = (age > 12 & age < 20); if (teenager) { ... }. Boolean variables are often used with AND, OR and NOT.',
        'Code of the form if (condition) { var = true; } else { var = false; } can be rewritten as var = condition; e.g. hot = temp >= 35;',
        'Exercise 5: even = mynumber % 2; gives an int (0 or 1), while even = mynumber % 2 == 0; gives a boolean. A Boolean rewrite of an if can also be shortened, e.g. cheapPhoneCall = (dialCode.equals("0860") | time < 7.0 | time > 19.0);',
        'Exercise 5 question 5: acidic = (pH >= 1 & pH < 7); can replace the pH condition. A switch cannot be used because pH is a double and the test is a range.',
      ],
      vocabulary: [
        { term: 'Boolean expression', definition: 'An expression that tests a condition and gives the value true or false.' },
        { term: 'Logical operators', definition: 'AND (&), OR (|) and NOT (!), often used to build Boolean expressions.' },
      ],
      workedExamples: [
        {
          code: J(
            'boolean hot;',
            'if (temp >= 35)',
            '{',
            '    hot = true;',
            '}',
            'else',
            '{',
            '    hot = false;',
            '}',
            '',
            'hot = temp >= 35;',
          ),
          explanation: 'The if ... else at the top can be rewritten as the single Boolean assignment at the bottom.',
        },
        {
          code: J(
            'boolean vowel;',
            `vowel = (let=='a' | let=='e' | let=='i' | let=='o' | let=='u');`,
            'if (vowel)',
            '   { System.out.println ("The letter is a vowel"); }',
          ),
          explanation: 'A long condition is stored in a boolean variable so that the if statement is short and readable.',
        },
      ],
      misconceptions: [
        'Thinking true and false are Strings, as in hot = "true";. They are Boolean values and are never put in quote marks.',
        'Thinking if (a > b) {big_a = true;} and big_a = (a > b); are identical. The if version leaves big_a without a value when a <= b.',
      ],
      questions: [
        {
          id: 'U8-T10-Q1',
          type: 'mc',
          category: 'distinguish',
          prompt: 'Exercise 5, question 1.2: What is the difference between these two statements?',
          code: J(
            'if (a > b) {big_a = true;}',
            'big_a = (a > b);',
          ),
          options: [
            'There is no difference; both always give big_a a value',
            'big_a = (a > b); stores the text "true" or "false" in big_a',
            'The if version is wrong because true must be written in quotes',
            'The if version gives big_a no value when a <= b; big_a = (a > b); always gives it true or false',
          ],
          answer: 3,
          hint: 'What happens to big_a in the if version when the condition is false?',
          explanation: 'A Boolean expression always gives the variable a value. The if version only assigns true, so big_a gets no value if a is not greater than b.',
          skills: ['U8-S11'],
        },
        {
          id: 'U8-T10-Q2',
          type: 'trace',
          category: 'calculate',
          prompt: 'Type true or false for each variable after the code has run.',
          code: J(
            'int age = 20;',
            'double temp = 35;',
            'boolean teenager, hot, ans1, similar, isTheSame;',
            'teenager = (age > 12 & age < 20);',
            'hot = temp >= 35;',
            'ans1 = (3 + 4 == 4 + 3);',
            'similar = ("0800".equals("800"));',
            'isTheSame = (200/5/2 == 200/10);',
            'isTheSame = (!(similar) & (ans1 | isTheSame));',
          ),
          rows: [
            { label: 'teenager', answer: 'false' },
            { label: 'hot', answer: 'true' },
            { label: 'isTheSame (final value)', answer: 'true' },
          ],
          hint: 'Is 20 < 20? Is 35 >= 35? Work out similar and ans1 before the last line.',
          explanation: '20 < 20 is false, so teenager is false. 35 >= 35 is true. similar is false and ans1 is true, so !(false) & (true | true) = true & true = true.',
          skills: ['U8-S11', 'U8-S10'],
        },
        {
          id: 'U8-T10-Q3',
          type: 'mc',
          category: 'predict',
          prompt: `Exercise 5, question 3.1: What value does validAns get when ans is 'Y'?`,
          code: J(
            `if (ans != 'Y' | ans != 'y' | ans != 'N' | ans != 'n')`,
            '{',
            '    validAns = false;',
            '}',
            'else',
            '{',
            '    validAns = true;',
            '}',
          ),
          options: [
            `false, because ans != 'y' is true, so the OR condition is true for every possible ans`,
            `true, because 'Y' is one of the valid answers`,
            `true, because ans != 'Y' is false`,
            'It does not compile, because != cannot be used with char',
          ],
          answer: 0,
          hint: `With OR, only one part needs to be true. Check ans != 'y'.`,
          explanation: `Any character is different from at least one of Y, y, N and n, so this condition is always true and validAns is always false. The intended Boolean version is validAns = (ans == 'Y' | ans == 'y' | ans == 'N' | ans == 'n');`,
          skills: ['U8-S11'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 'u8-runaway-switchyard',
    unitId: UNIT.id,
    title: 'Runaway at the Switchyard',
    icon: 'alert',
    summary: 'Fix the switch statements routing trains through the yard.',
    briefing: 'A goods train is rolling into the Germiston switchyard and the routing program is sending it down the wrong tracks. Someone deleted the break statements and hard-coded ranges into case labels. Repair the switch logic and the boolean safety checks before the train reaches the platform.',
    tickerMessages: [
      'Switchyard control reports trains taking unexpected routes.',
      'Engineers suspect missing break statements in the routing code.',
      'Track 7 signal shows every case firing at once.',
      'Safety flag variable stuck on false; brakes not engaging.',
      'Goods train two minutes from the passenger platform.',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['U8-S7', 'U8-S8', 'U8-S9', 'U8-S10', 'U8-S11'],
    victoryMessage: 'Every case now ends with break and the safety flag works. The train glides into the siding and the yard master buys you a pie.',
    failMessage: 'The train fell through every case in the switch and ended up on the wrong platform. Check your breaks and case rules, then try again.',
  },
  {
    id: 'u8-alphabet-vault',
    unitId: UNIT.id,
    title: 'The Alphabet Vault',
    icon: 'vault',
    summary: 'Crack a vault whose lock compares Strings by Unicode value.',
    briefing: 'The Reserve Bank vault in Pretoria will only open for a password that is checked with equals, and the guard list must be sorted with compareTo. A careless programmer used == and mixed up capitals and small letters. Compare the Strings correctly and trace the checks before the time lock seals the vault for the weekend.',
    tickerMessages: [
      'Vault password check rejects even the correct password.',
      'Investigators find == used to compare Strings in the lock code.',
      'Guard list sorted wrongly: capitals and small letters mixed up.',
      'Time lock engages in under four minutes.',
      'Bank manager on the phone asking for answers now.',
      'Final compareTo check is all that stands between you and the vault.',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['U8-S1', 'U8-S2', 'U8-S3', 'U8-S4', 'U8-S5'],
    victoryMessage: 'equals, equalsIgnoreCase and compareTo did their job. The vault door swings open with seconds to spare.',
    failMessage: 'The time lock sealed the vault. Remember: Strings are objects, compare them with equals, and capitals come before small letters.',
  },
];
