// Java Learning Unit 9: While Loops and Do Loops (Exploring IT: Java Programming Grade 10, 3rd ed)
import { RefreshCw } from 'lucide-react';

export const UNIT = { id: 'U9', number: 9, name: 'While Loops and Do Loops', worldId: 'while-loops' };

export const SKILLS = {
  'U9-S1': {
    unit: 'U9',
    name: 'The need for a while loop',
    description: 'Explain why a while loop is used when the number of repetitions is not known, and how it differs from an if statement.',
    sections: ['9.1'],
  },
  'U9-S2': {
    unit: 'U9',
    name: 'While loop structure and flow',
    description: 'Describe the general structure of a while loop and how the condition is tested at the beginning of every pass.',
    sections: ['9.2', '9.3.3'],
  },
  'U9-S3': {
    unit: 'U9',
    name: 'Planning a loop solution',
    description: 'Solve a loop problem using IPO, a data structure, an algorithm, code, testing and evaluation (the Mult3 example).',
    sections: ['9.3', '9.3.1', '9.3.2', '9.3.3', '9.3.4', '9.3.5', '9.3.6'],
  },
  'U9-S4': {
    unit: 'U9',
    name: 'SITC',
    description: 'Apply Select, Initialise, Test and Change to design a while loop that terminates correctly.',
    sections: ['9.2', '9.4'],
  },
  'U9-S5': {
    unit: 'U9',
    name: 'Investigating SITC',
    description: 'Diagnose what goes wrong when the S, I, T or C part of a while loop is missing or incorrect.',
    sections: ['9.4.1', '9.4.1.1', '9.4.1.2', '9.4.1.3', '9.4.1.4'],
  },
  'U9-S6': {
    unit: 'U9',
    name: 'Tracing while loops',
    description: 'Use trace tables to find the values of loop variables, the number of passes and the output of a while loop.',
    sections: ['9.3.3', '9.4.1.4', '9.6'],
  },
  'U9-S7': {
    unit: 'U9',
    name: 'Rogue (terminating) values',
    description: 'Input data until a given terminating value is entered, without using that value in any calculation.',
    sections: ['9.5'],
  },
  'U9-S8': {
    unit: 'U9',
    name: 'Errors in while loops',
    description: 'Find and fix infinite loops, wrong conditions, a semicolon after the while header and OR/AND mistakes.',
    sections: ['9.6'],
  },
  'U9-S9': {
    unit: 'U9',
    name: 'Do while loops',
    description: 'Write and compare do...while loops with while loops, including SICT, menus and input validation.',
    sections: ['9.7', '9.7.1', '9.7.1.1'],
  },
  'U9-S10': {
    unit: 'U9',
    name: 'Choosing a looping structure',
    description: 'Choose between for, while and do while loops and rewrite one type of loop as another.',
    sections: ['9.8'],
  },
  'U9-S11': {
    unit: 'U9',
    name: 'Counters, totals and sequences',
    description: 'Use counters, running totals, sequences and series inside while loops to count, add, average or find a maximum.',
    sections: ['9.3.6', '9.4.1', '9.5', '9.6'],
  },
};

export const SKILL_HINTS = {
  'U9-S1': 'for loop when repetitions are known; while loop repeats while a condition is true when repetitions are unknown; if checks once, while repeats (CheckInput age 0-120 needs input inside the loop)',
  'U9-S2': 'while (condition) { body } tests the condition at the beginning; true runs the body, false skips to the first statement after the loop; body may run 0 times; flow chart similar to a for loop',
  'U9-S3': 'Mult3: IPO (no input, generate multiples of 3, output multiples), single int num, num = 3, while (num <= 8000), display then num = num + 3; last shown 7998; 10 per line with count % 10 == 0',
  'U9-S4': 'SITC: Select the test variable, Initialise it before the loop, Test the condition in the while heading, Change it just before the end of the loop',
  'U9-S5': 'Missing S/I: compile error (day or sum not initialised); wrong T: BlastOff num = 10, while (num < 10) never runs; missing C: Sale2 day never changes so infinite loop',
  'U9-S6': 'Trace tables with loop variable, condition true/false and OUTPUT columns; count passes, final values, e.g. sum of 1+2+3... while sum < 20 ends at 15 shown, sum 21',
  'U9-S7': 'Rogue/dummy/terminating value (e.g. -1 for marks, -99, 0 for prices, * for names) is used only in the condition, never added or counted; input before the loop and again at the end',
  'U9-S8': 'Infinite loop when the test variable is not changed; ; after while header gives empty body; (ch != \'X\' || ch != \'x\') is always true, use && for not-equal; check SITC then trace table',
  'U9-S9': 'do { ... } while (condition); runs at least once, tests at the end, semicolon after condition, uses SICT; used for menus and input validation (CheckInput2)',
  'U9-S10': 'for when iterations are known, while when not known, do while when at least one pass is needed; any loop can be rewritten as another; for loop has ITC built in',
  'U9-S11': 'Counter = counter + 1, total = total + value, average = total / counter (int division truncates), max/min tracking, sequences with a step, series sums such as 1+2+...+100 = 5050',
};

export const WORLD = {
  id: UNIT.worldId,
  name: 'Whirlpool Wharf',
  subtitle: 'Unit 9 \u00b7 While and Do Loops',
  color: 'orange',
  glow: 'ja-glow-orange',
  bg: 'ja-w-while-loops',
  icon: RefreshCw,
  blurb: 'Loops that keep spinning as long as a condition is true. Master SITC, rogue values and do while loops before the whirlpool drags you into an infinite loop.',
};

export const LEVELS = [
  {
    id: 'u9-l1',
    name: 'Enter the Whirlpool',
    subtitle: 'Why while loops, their structure and the Mult3 example',
    challengeIds: ['u9-c1', 'u9-c2', 'u9-c3', 'u9-c4', 'u9-c5', 'u9-c6'],
  },
  {
    id: 'u9-l2',
    name: 'SITC Workshop',
    subtitle: 'Select, Initialise, Test, Change and what breaks without them',
    challengeIds: ['u9-c7', 'u9-c8', 'u9-c9', 'u9-c10', 'u9-c11', 'u9-c12'],
  },
  {
    id: 'u9-l3',
    name: 'Rogue Waves and Bugs',
    subtitle: 'Terminating values and errors in while loops',
    challengeIds: ['u9-c13', 'u9-c14', 'u9-c15', 'u9-c16', 'u9-c17', 'u9-c18'],
    hasCoding: true,
  },
  {
    id: 'u9-l4',
    name: 'Boss: The Maelstrom',
    subtitle: 'Do while loops, choosing loops and mixed review',
    challengeIds: ['u9-c19', 'u9-c20', 'u9-c21', 'u9-c22', 'u9-c23', 'u9-c24', 'u9-c25'],
    hasCoding: true,
  },
];

export const CHALLENGES = {
  'u9-c1': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'In Activity 1 (CheckInput) an if statement displays "The age is an incorrect value" when 130 is entered. Why does the program need a while loop instead?',
    options: [
      'An if statement checks the age only once, and the user may make more than one mistake, so input must repeat until it is valid',
      'An if statement cannot use the || operator, so the condition age < 0 || age > 120 must be placed in a while loop',
      'A while loop runs faster than an if statement when the value comes from JOptionPane.showInputDialog',
      'An if statement can only test an int variable once it has been converted with Integer.parseInt',
    ],
    answer: 0,
    hint: 'Think about what happens after the error message is shown. Can the user try again?',
    explanation: 'An if statement tests its condition once. A while loop keeps repeating (with a new input inside the loop) as long as the age is incorrect, so the user can correct any number of mistakes.',
    skills: ['U9-S1'],
  },
  'u9-c2': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'In Activity 1, if you only change the reserved word if to while (and add nothing else), entering 130 causes an infinite loop.',
    answer: true,
    hint: 'Is there any statement inside the loop that can change age?',
    explanation: 'True. age is never changed inside the loop, so age > 120 stays true forever. The fix is a second input statement for age inside the loop.',
    skills: ['U9-S1', 'U9-S8'],
  },
  'u9-c3': {
    type: 'order',
    world: UNIT.worldId,
    prompt: 'Put the parts of the general structure of a while loop (section 9.2) in the order they appear in a program.',
    items: [
      'Change the value of the test variable',
      'Select a variable to control the loop',
      '... statements in loop ...',
      'while (a condition using the test variable is true)',
      'Initialise the test variable',
    ],
    answer: [1, 4, 3, 2, 0],
    hint: 'S, I, T, C. The change goes at the very end of the loop body.',
    explanation: 'Select and initialise the test variable before the loop, test it in the while heading, carry out the statements, and change the test variable as the last line of the loop.',
    skills: ['U9-S2', 'U9-S4'],
  },
  'u9-c4': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'This is Algorithm 2 from section 9.3.3, coded in Java with the limit changed to 20. What does it display?',
    code: 'int num = 3;\nwhile (num <= 20)\n{\n    num = num + 3;\n    System.out.print(num + " ");\n}',
    options: ['3 6 9 12 15 18', '6 9 12 15 18', '6 9 12 15 18 21', '3 6 9 12 15 18 21'],
    answer: 2,
    hint: 'num is changed before it is displayed. What happens on the pass where num starts at 18?',
    explanation: 'Because num is increased before it is displayed, 3 is never shown, and when num is 18 the test 18 <= 20 is true, so 21 is displayed even though it is past the limit. That is why the C should be the last line of the loop (Algorithm 1).',
    skills: ['U9-S3', 'U9-S6'],
  },
  'u9-c5': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Run Mult3 (Activity 3) in your head. Fill in each value as a whole number.',
    code: 'System.out.println("MULTIPLES OF 3 BETWEEN 1 and 8000");\nint num = 3;\nwhile (num <= 8000)\n{\n    System.out.print(num + " ");\n    num = num + 3;\n}// end while loop\nSystem.out.println();',
    rows: [
      { label: 'Last number displayed', answer: '7998' },
      { label: 'Value of num after the loop ends', answer: '8001' },
      { label: 'How many numbers are displayed', answer: '2666' },
    ],
    hint: '8000 is not a multiple of 3. Find the largest multiple of 3 that is not more than 8000.',
    explanation: '7998 = 3 x 2666 is the last multiple of 3 not above 8000. After it is displayed num becomes 8001, the test 8001 <= 8000 is false and the loop ends. The numbers 3, 6, ..., 7998 are 2666 numbers.',
    skills: ['U9-S3', 'U9-S6'],
  },
  'u9-c6': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each planning step to its content for Activity 2: display all the multiples of 3 between 1 and 8000.',
    pairs: [
      { left: 'Input', right: 'None: the numbers are generated by the program' },
      { left: 'Processing', right: 'Generate multiples of 3 starting at 3, stopping when the numbers are greater than 8000' },
      { left: 'Output', right: 'The multiples of 3, across the screen with one space between each' },
      { left: 'Data structure', right: 'A single integer variable num that is overwritten with each new number' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Nothing is typed in by the user in this problem.',
    explanation: 'IPO splits the problem into input (none), processing (generate multiples of 3) and output (the multiples). Only one integer variable is needed because each number is displayed and then overwritten.',
    skills: ['U9-S3'],
  },
  'u9-c7': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each letter of SITC to what the textbook says it means.',
    pairs: [
      { left: 'S', right: 'Select the test variable(s) to use in the condition' },
      { left: 'I', right: 'Give the test variable(s) an initial value' },
      { left: 'T', right: 'Test the condition in the while heading' },
      { left: 'C', right: 'Change the value of the test variable(s) just before the end of the loop' },
    ],
    answer: [0, 1, 2, 3],
    hint: 'Two of the steps happen before the loop starts.',
    explanation: 'S and I happen before the loop, T is in the while heading and C is the last step inside the loop. Always use SITC when you design a while loop so that it works properly.',
    skills: ['U9-S4'],
  },
  'u9-c8': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'Sale1 (section 9.4.1.1) should display the reduced price for each of the 5 sale days. Which SITC step went wrong?',
    code: 'int price = 200;\nint day;\nwhile (day <= 5)\n{\n    price = price - 10;\n    System.out.println("Sale Day " + day + " Price R " + price);\n    day = day + 1;\n}',
    options: [
      'T: the condition should be day < 5 so that the loop runs exactly five times',
      'C: day = day + 1 must be the first statement inside the loop',
      'Nothing: the loop correctly displays Sale Day 1 to Sale Day 5',
      'S: price was set up before the loop, but the test variable in the condition is day, which was never given a value',
    ],
    answer: 3,
    hint: 'Which variable does the condition actually test, and what value does it have before the loop?',
    explanation: 'The condition tests day, so day must be selected as the test variable and initialised (day = 1) before the loop. As written, Java reports that day might not have been initialised.',
    skills: ['U9-S5', 'U9-S4'],
  },
  'u9-c9': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Sum20 (section 9.4.1.2) after it was corrected by initialising sum to 1. Fill in the values.',
    code: 'int num = 1;\nint sum = 1;\nwhile (sum < 20)\n{\n    System.out.println("The sum of " + num + " natural numbers is " + sum);\n    num = num + 1;\n    sum = sum + num;\n}',
    rows: [
      { label: 'Number of lines displayed', answer: '5' },
      { label: 'sum shown in the last line displayed', answer: '15' },
      { label: 'num after the loop', answer: '6' },
      { label: 'sum after the loop', answer: '21' },
    ],
    hint: 'Track sum: 1, 3, 6, 10, ... A line is displayed only when sum < 20 is true.',
    explanation: 'The lines show sums 1, 3, 6, 10 and 15. Then num becomes 6 and sum becomes 21, so 21 < 20 is false and the loop ends. 15 is the sum that is just less than 20.',
    skills: ['U9-S5', 'U9-S6'],
  },
  'u9-c10': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'BlastOff (section 9.4.1.3) was meant to count down from 10 to 0. What does it actually display?',
    code: 'System.out.println("Count Down");\nint num = 10;\nwhile (num < 10)\n{\n    System.out.print(num + ". . .");\n    num = num - 1;\n}\nSystem.out.println("BLAST OFF!");',
    options: [
      'Count Down, then 10. . .9. . . all the way down to 0. . . and BLAST OFF!',
      'Count Down, then BLAST OFF! on the next line, with no numbers at all',
      'Count Down, then numbers counting down forever in an infinite loop',
      'Count Down, then 10. . . followed by BLAST OFF! on the same line',
    ],
    answer: 1,
    hint: 'Test the condition with the initial value of num before the first pass.',
    explanation: 'num starts at 10, so 10 < 10 is false the first time it is tested and the body is skipped. The test should be num >= 0 to display 10 down to 0.',
    skills: ['U9-S5', 'U9-S2'],
  },
  'u9-c11': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'Trace Sale2 (section 9.4.1.4). For the last row type a whole number, or the word infinite.',
    code: 'int price = 200;\nint day = 1;\nwhile (day <= 5)\n{\n    price = price - 10;\n    System.out.println("Sale Day " + day + " Price R " + price);\n}',
    rows: [
      { label: 'price after pass 1', answer: '190' },
      { label: 'price after pass 3', answer: '170' },
      { label: 'day after pass 3', answer: '1' },
      { label: 'Number of times the loop runs', answer: 'infinite' },
    ],
    hint: 'Look for the C in SITC. Does anything inside the loop change day?',
    explanation: 'day is never changed, so day <= 5 is always true and the loop never ends, displaying "Sale Day 1" with an ever lower price. Adding day = day + 1 as the last line of the loop fixes it.',
    skills: ['U9-S5', 'U9-S6', 'U9-S8'],
  },
  'u9-c12': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'WhileSum (Exercise 2) adds 1 + 2 + 3 + 4 + ... until the sum is just greater than 5000. How many integers are added, and what is the final sum?',
    options: ['99 integers, sum 4950', '100 integers, sum 5050', '101 integers, sum 5151', '98 integers, sum 4851'],
    answer: 1,
    hint: 'The sum of 1 to n is n x (n + 1) / 2. The loop keeps going while the sum is not yet greater than 5000.',
    explanation: 'After 99 integers the sum is 4950, which is not greater than 5000. Adding 100 gives 5050, so the counter ends at 100.',
    skills: ['U9-S11', 'U9-S3'],
  },
  'u9-c13': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which statement best describes a rogue (terminating or dummy) value, as used in section 9.5?',
    options: [
      'A value typed in to stop the input; it is used in the loop condition but must not be used in any calculations',
      'The first value typed in, which is used to initialise the total before the loop starts',
      'A value that causes a run-time error on purpose so that the program stops running',
      'The largest valid data value, which is added to the total as the last item of data',
    ],
    answer: 0,
    hint: 'In AvgMarks the rogue value is -1. Should -1 affect the average?',
    explanation: 'The rogue value only tells the loop when to stop. It must not be added to totals or counted, otherwise results such as the average will be wrong.',
    skills: ['U9-S7'],
  },
  'u9-c14': {
    type: 'trace',
    world: UNIT.worldId,
    prompt: 'AvgMarks (Activity 5) coded with int variables. The user types 45, 48, 43 and then -1. Fill in the values.',
    code: 'int total = 0;\nint counter = 0;\nint mark = Integer.parseInt(JOptionPane.showInputDialog("Input mark (-1 to stop)"));\nwhile (mark != -1)\n{\n    total = total + mark;\n    counter = counter + 1;\n    mark = Integer.parseInt(JOptionPane.showInputDialog("Input mark (-1 to stop)"));\n}\nint average = total / counter;\nSystem.out.println(average + " " + counter);',
    rows: [
      { label: 'total after the loop', answer: '136' },
      { label: 'counter after the loop', answer: '3' },
      { label: 'average (int division)', answer: '45' },
      { label: 'Times the condition mark != -1 is tested', answer: '4' },
    ],
    hint: 'The -1 is tested by the condition but never added. int / int truncates.',
    explanation: '45 + 48 + 43 = 136 over 3 marks. 136 / 3 with int division is 45 (the real average is 45.33). The condition is tested for 45, 48, 43 and -1, which is 4 times.',
    skills: ['U9-S7', 'U9-S6', 'U9-S11'],
  },
  'u9-c15': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'While_Error_One (Activity 6) should add non-zero integers until 0 is entered. The user types 7 first. What goes wrong?',
    code: 'int number, sum = 0;\nnumber = Integer.parseInt(JOptionPane.showInputDialog("Enter an integer"));\nwhile (number == 0)\n{\n    sum = sum + number;\n    number = Integer.parseInt(JOptionPane.showInputDialog("Enter an integer"));\n}\nSystem.out.println("The sum of the integers is " + sum);',
    options: [
      'The loop never ends because number is never changed inside the loop',
      'Java reports a syntax error because sum is declared on the same line as number',
      'The test is wrong: 7 == 0 is false, so the loop is skipped and "The sum of the integers is 0" is displayed',
      'The 7 is added twice, so "The sum of the integers is 14" is displayed',
    ],
    answer: 2,
    hint: 'Evaluate the condition with number = 7 before the first pass.',
    explanation: 'The T in SITC is wrong. The loop should continue while number != 0. With that fix and the data 7, -5, 2, 0 the sum displayed is 4.',
    skills: ['U9-S8', 'U9-S4'],
  },
  'u9-c16': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'OtherLoopErrors (Exercise 4): you type a and the program keeps running, but nothing else happens. Why?',
    code: 'char ch;\nch = JOptionPane.showInputDialog("Input any character (x to stop)").charAt(0);\nwhile (ch != \'X\' || ch != \'x\');\n{\n    System.out.println();\n    System.out.println("You typed in " + ch);\n    ch = JOptionPane.showInputDialog("Input any character (x to stop)").charAt(0);\n}\nSystem.out.println("End of program");',
    options: [
      'charAt(0) returns a String, so it cannot be compared with a char and the program waits',
      'The input statement inside the braces runs first and waits for a second character',
      'ch was declared without a value, so the condition cannot be tested at all',
      'The semicolon after the while header is an empty loop body, so the condition is tested forever and ch never changes',
    ],
    answer: 3,
    hint: 'Look very carefully at the end of the while header line.',
    explanation: 'The ; ends the while statement, so the loop body is empty and the block in braces is not part of the loop. The condition is true and nothing changes ch, so the loop is infinite. One small semicolon makes a huge difference.',
    skills: ['U9-S8'],
  },
  'u9-c17': {
    type: 'tf',
    world: UNIT.worldId,
    prompt: 'After the semicolon is removed, this loop correctly stops when the user types x or X.',
    code: 'while (ch != \'X\' || ch != \'x\')\n{\n    System.out.println("You typed in " + ch);\n    ch = JOptionPane.showInputDialog("Input any character (x to stop)").charAt(0);\n}',
    answer: false,
    hint: 'Try ch = \'x\'. Is ch != \'X\' true or false?',
    explanation: 'False. Every character is not equal to at least one of X and x, so the || condition is always true. When checking that an item is not equal to more than one value, use AND: (ch != \'X\' && ch != \'x\').',
    skills: ['U9-S8'],
  },
  'u9-c18': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Code a class called Prices (Exercise 3, question 2). Display a heading with a supermarket name you make up. Input the price of each of an unknown quantity of goods, ending with the rogue value 0. Display each price as it is entered. After the loop, display the total amount the customer must pay, rounded to 2 decimal places.',
    criteria: `- Class named Prices with a main method; javax.swing.* (or JOptionPane) is imported.
- A heading with a made-up supermarket name is displayed before any input.
- A while loop follows SITC: price is the test variable; it gets its initial value from an input statement BEFORE the loop; the condition tests price != 0 (or price > 0); a second input statement is the LAST statement inside the loop.
- Input uses JOptionPane.showInputDialog converted with Double.parseDouble; price and total are declared as double.
- total is initialised to 0 before the loop, and each price is added to total inside the loop.
- Each valid price is displayed inside the loop. The rogue value 0 is never displayed as a price and never added to total.
- After the loop the total is displayed with a clear message, rounded to 2 decimal places (for example Math.round(total * 100) / 100.0).
- No semicolon after the while header; the statements inside the loop are indented.
- With test data 78.99, 231.56, 19.05, 5.75, 67.12, 43.88, 1.90, 3.22, 6.75, 0 the total displayed is 458.22.`,
    starter: 'import javax.swing.*;\n\npublic class Prices\n{\n    public static void main(String[] args)\n    {\n        // your code here\n    }\n}',
    explanation: 'This is the generic rogue value algorithm from Activity 5: initialise the total, input before the loop, test for the rogue value, process, and input again as the last statement so that 0 is tested before it can be used.',
    skills: ['U9-S7', 'U9-S4', 'U9-S11'],
  },
  'u9-c19': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'CheckInput2 (Activity 7). The user types 150, then 200, then -2, then 4. How many times is the input dialog box displayed?',
    code: 'int age;\ndo\n{\n    age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120"));\n}\nwhile (age < 0 || age > 120);// end do',
    options: ['1', '3', '4', '5'],
    answer: 2,
    hint: 'The body runs first, then the condition is tested. Which of the inputs make the condition false?',
    explanation: 'A do loop always runs at least once. 150, 200 and -2 make the condition true, so the loop repeats; 4 makes it false. That is 4 dialog boxes.',
    skills: ['U9-S9'],
  },
  'u9-c20': {
    type: 'match',
    world: UNIT.worldId,
    prompt: 'Match each problem to the loop the textbook recommends (section 9.8).',
    pairs: [
      { left: 'Display "Hi there" exactly 6 times', right: 'for loop: the number of iterations is known beforehand' },
      { left: 'Input marks until -1 is entered', right: 'while loop: the number of iterations is not known beforehand' },
      { left: 'Display a colour menu until Q is chosen', right: 'do while loop: at least one pass through the loop must be made' },
    ],
    answer: [0, 1, 2],
    hint: 'Ask: do I know the count? Must it run at least once?',
    explanation: 'Use a for loop when the number of iterations is known, a while loop when it is not known, and a do while loop when at least one pass must be made, such as displaying a menu.',
    skills: ['U9-S10', 'U9-S9'],
  },
  'u9-c21': {
    type: 'mc',
    world: UNIT.worldId,
    prompt: 'Which statement about the do...while loop is correct, according to section 9.7.1?',
    options: [
      'It may not be executed at all if the condition is false at the start',
      'It has its condition tested at the beginning of the loop statements',
      'It has no semicolon after the condition, just like a while loop',
      'It has a semicolon after the condition, because that is the end of the loop',
    ],
    answer: 3,
    hint: 'Where is the while keyword placed in a do loop?',
    explanation: 'In a do...while loop, while (condition); comes after the body and ends the loop, so it needs a semicolon. The body is always carried out at least once and the test is at the end.',
    skills: ['U9-S9'],
  },
  'u9-c22': {
    type: 'error-spot',
    world: UNIT.worldId,
    prompt: 'This menu loop follows the ColSquare algorithm in Activity 8 word for word. What is wrong with it?',
    code: 'char choice;\ndo\n{\n    System.out.println("COLOUR MENU");\n    System.out.println("B  Blue");\n    System.out.println("R  Red");\n    System.out.println("G  Green");\n    System.out.println("Q  Quit");\n    choice = JOptionPane.showInputDialog("Enter your choice").charAt(0);\n    // check choice and draw a square in the colour chosen\n}\nwhile (choice != \'Q\' || choice != \'q\');',
    options: [
      'The condition is always true, so Q never ends the program; the two != tests must be joined with && instead of ||',
      'A do...while loop cannot be used for a menu, because the menu might never need to be displayed',
      'The semicolon after the while condition makes the loop body empty, so the menu is shown only once',
      'choice must be given a value before the do keyword, otherwise the condition cannot be tested',
    ],
    answer: 0,
    hint: 'Use the rule from section 9.6 about checking that an item is not equal to more than one value.',
    explanation: 'Any character is not equal to at least one of Q and q, so the || condition never becomes false. It must be (choice != \'Q\' && choice != \'q\'). The semicolon is required in a do...while loop.',
    skills: ['U9-S9', 'U9-S8'],
  },
  'u9-c23': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Code a class called Dice (Exercise 3, questions 5.4 to 5.8). Generate random integers from 1 to 6 (inclusive) and display them across the screen with one space between each, until a 6 is generated. The 6 must NOT be displayed: instead display THE END on the same line. Count how many numbers were displayed, then leave a blank line and display the count with a suitable message.',
    criteria: `- Class named Dice with a main method.
- Random integers in the range 1 to 6 inclusive are generated with (int) (Math.random() * 6) + 1.
- A while loop (not a for loop) follows SITC: the first number is generated BEFORE the loop; the condition tests that the number is not 6 (e.g. dice != 6); a new number is generated as the LAST statement inside the loop.
- Inside the loop each number is displayed with System.out.print followed by one space, so all the numbers are on one line, and a counter (initialised to 0 before the loop) is increased by 1.
- The 6 is never displayed. After the loop, THE END is displayed on the same line as the numbers.
- A blank line is then displayed, followed by a message with the count, e.g. "Numbers generated before a 6: 4".
- If the very first number is a 6, the output is only THE END and the count is 0 (this is correct, see question 5.7).
- No semicolon after the while header; the code is indented.`,
    starter: 'public class Dice\n{\n    public static void main(String[] args)\n    {\n        // your code here\n    }\n}',
    explanation: 'Generating a number before the loop and again at the end of the loop means each new number is tested before it can be displayed, so the 6 stops the loop without being shown. The number of passes is unknown, so a while loop is the right choice.',
    skills: ['U9-S4', 'U9-S11', 'U9-S10'],
  },
  'u9-c24': {
    type: 'code-write',
    world: UNIT.worldId,
    prompt: 'Code a class called CheckInt (Exercise 6, question 1). Input one integer (positive or negative). Then use a do...while loop to display the menu below repeatedly and carry out the chosen check on the integer, until 5 is chosen.\nCHECKS TO BE PERFORMED ON THE INTEGER:\n1 Check if it is positive\n2 Check if it is even\n3 Check if it is a perfect square\n4 Check if it is a multiple of 7\n5 Quit',
    criteria: `- Class named CheckInt with a main method; the integer is input once, before the loop, with JOptionPane.showInputDialog and Integer.parseInt.
- Uses a do...while loop of the form do { ... } while (choice != 5); with a semicolon after the condition, so the menu is displayed at least once.
- Inside the loop: the heading CHECKS TO BE PERFORMED ON THE INTEGER: and the 5 numbered options are displayed, then the choice is input and converted to an int.
- An if...else if structure or a switch statement carries out the option:
  1: positive when number > 0 (0 is not positive);
  2: even when number % 2 == 0 (this also works for negative numbers);
  3: perfect square when number >= 0 and (int) Math.sqrt(number) * (int) Math.sqrt(number) == number (negative numbers are not perfect squares);
  4: multiple of 7 when number % 7 == 0;
  5: a goodbye message is displayed and the loop ends.
- Each check displays a clear message with the integer and the result, e.g. "49 is a perfect square" or "-14 is not positive".
- A choice outside 1 to 5 displays an error message and the menu appears again.
- Expected results: 49 is positive, not even, a perfect square and a multiple of 7; -14 is not positive, even, not a perfect square and a multiple of 7.`,
    starter: 'import javax.swing.*;\n\npublic class CheckInt\n{\n    public static void main(String[] args)\n    {\n        // your code here\n    }\n}',
    explanation: 'A menu must always be displayed at least once, so a do...while loop fits: the choice is input inside the loop and tested at the end. Selection (if or switch) inside the loop carries out each option.',
    skills: ['U9-S9', 'U9-S10'],
  },
  'u9-c25': {
    type: 'code-read',
    world: UNIT.worldId,
    prompt: 'Check Point 2, question 4: which while loop does exactly the same as this for loop?',
    code: 'for (int i = 0; i <= 5; i++)\n    System.out.println("Hi there");',
    options: [
      'int i = 0; while (i < 5) { System.out.println("Hi there"); i++; }',
      'int i = 0; while (i <= 5) { System.out.println("Hi there"); i++; }',
      'int i = 0; while (i <= 5) { i++; } System.out.println("Hi there");',
      'while (int i = 0; i <= 5) { System.out.println("Hi there"); i++; }',
    ],
    answer: 1,
    hint: 'A for loop has I, T and C built into its header. Where does each part go in a while loop?',
    explanation: 'I (int i = 0) moves before the loop, T (i <= 5) stays in the heading and C (i++) becomes the last statement in the body. Both display Hi there 6 times, for i = 0 to 5.',
    skills: ['U9-S10', 'U9-S2'],
  },
};

export const THEORY = {
  unitId: UNIT.id,
  title: UNIT.name,
  purpose: 'Learn to repeat statements while a condition is true using while and do...while loops designed with SITC, and to choose the best loop for a problem.',
  outcomes: [
    'By the end you can explain when a while loop is needed instead of a for loop or an if statement.',
    'By the end you can describe the general structure of a while loop and how its condition is tested.',
    'By the end you can plan a loop solution with IPO, a data structure, an algorithm, code, testing and evaluation.',
    'By the end you can state what S, I, T and C stand for and why none of them can be left out.',
    'By the end you can trace while loops to find variable values, the number of passes and the output.',
    'By the end you can input data until a rogue (terminating) value is entered without using it in calculations.',
    'By the end you can find and fix common errors in while loops, including infinite loops.',
    'By the end you can write do...while loops for menus and input validation and compare them with while loops.',
    'By the end you can choose an appropriate looping structure and rewrite a for loop as a while loop.',
  ],
  topics: [
    {
      id: 'U9-T1',
      title: 'The Need for a While Loop',
      sections: ['9.1'],
      skills: ['U9-S1', 'U9-S2'],
      explanation: [
        'A for loop is usually used when the number of times one or more statements must be repeated is known. Sometimes the number of repetitions is not known. Instead, a block of statements is repeated while a condition is true, or until a value changes.',
        'In Activity 1 (CheckInput) the user enters an age with JOptionPane and an if statement displays "The age is an incorrect value" when the age is less than 0 or greater than 120. If 130 is entered, the program reports the error but does not let the user enter a correct age. The user could make more than one mistake, so a loop is needed.',
        'Changing the reserved word if to while on its own creates an infinite loop, because age never changes inside the loop. A second input statement for age must be added inside the loop.',
        'The word while means "as long as". If the age entered is correct, the condition is false and the loop is bypassed. If the age is incorrect, the condition is true: the error message is displayed and the user enters a new age. The loop only terminates when the condition is false.',
        'All the code between the curly brackets of the while loop is repeated, so indent it to show clearly what is inside the loop.',
      ],
      vocabulary: [
        { term: 'while loop', definition: 'A loop that repeats a block of statements as long as (while) its condition is true.' },
        { term: 'infinite loop', definition: 'A loop that never terminates because its condition never becomes false.' },
        { term: 'condition', definition: 'A Boolean expression, such as age < 0 || age > 120, that is tested to decide whether the loop body is carried out.' },
      ],
      workedExamples: [
        {
          code: 'int age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120"));\nwhile (age < 0 || age > 120)\n{\n    System.out.println("The age is an incorrect value");\n    age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120"));\n}// end while',
          explanation: 'CheckInput with a while loop. The first input happens before the loop, and the second input inside the loop lets the user try again until the age is valid.',
        },
      ],
      misconceptions: [
        'Changing if to while is enough to fix CheckInput. Wrong: without a new input inside the loop, age never changes and the loop is infinite.',
        'A while loop always runs at least once. Wrong: if the first age is valid, the condition is false and the body is skipped completely.',
      ],
      questions: [
        {
          id: 'U9-T1-Q1',
          type: 'mc',
          category: 'distinguish',
          prompt: 'According to the textbook, when is a for loop usually used and when is a while loop used?',
          options: [
            'A for loop is used when the condition involves a String; a while loop when it involves numbers',
            'A for loop is used to validate input; a while loop is used only to count from 1 to 10',
            'A for loop when the number of repetitions is known; a while loop repeats while a condition is true when it is not known',
            'A for loop repeats while a condition is false; a while loop repeats while a condition is true',
          ],
          answer: 2,
          hint: 'Think about whether you know in advance how many times the statements must repeat.',
          explanation: 'A for loop suits a known number of repetitions. A while loop repeats while a condition is true, when the number of repetitions is not known.',
          skills: ['U9-S1'],
        },
        {
          id: 'U9-T1-Q2',
          type: 'tf',
          category: 'define',
          prompt: 'The textbook explains that the word while in a while loop means "as long as".',
          answer: true,
          hint: 'Read the heading while (age < 0 || age > 120) aloud.',
          explanation: 'True. The loop repeats as long as the condition is true.',
          skills: ['U9-S1', 'U9-S2'],
        },
        {
          id: 'U9-T1-Q3',
          type: 'trace',
          category: 'predict',
          prompt: 'The user types 130, then -5, then 45 into CheckInput. Fill in the values.',
          code: 'int age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120"));\nwhile (age < 0 || age > 120)\n{\n    System.out.println("The age is an incorrect value");\n    age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120"));\n}',
          rows: [
            { label: 'Times "The age is an incorrect value" is displayed', answer: '2' },
            { label: 'Times the input dialog appears', answer: '3' },
            { label: 'Final value of age', answer: '45' },
          ],
          hint: 'Test the condition for each age typed in.',
          explanation: '130 and -5 make the condition true, so the message is shown twice. 45 makes it false and the loop ends after 3 inputs.',
          skills: ['U9-S2', 'U9-S1'],
        },
      ],
    },
    {
      id: 'U9-T2',
      title: 'General Structure and Planning a While Loop',
      sections: ['9.2', '9.3', '9.3.1', '9.3.2', '9.3.3'],
      skills: ['U9-S2', 'U9-S3', 'U9-S4', 'U9-S6'],
      explanation: [
        'General structure: select a variable to control the loop (S), initialise the test variable (I), while (a condition using the test variable is true) (T), the statements in the loop, and change the value of the test variable (C) at the end of the loop.',
        'At the beginning of the loop the condition is tested. If it is true, the statements in the loop are carried out. As soon as it is false, the body of the loop is skipped and the first statement after the loop is executed. A while loop has a similar flow chart to a for loop.',
        'Activity 2: display all the multiples of 3 between 1 and 8000 across the screen, with one space between each. IPO: Input - none, the numbers are generated; Processing - generate multiples of 3 starting at 3 and stopping when the numbers are greater than 8000; Output - multiples of 3.',
        'Data structure: a single integer variable num stores each number and is overwritten by the next one.',
        'Algorithm: we do not know how many times the loop will execute, so the textbook uses a while loop with a condition that stops it. Select num, Initialise num <- 3, Test num <= 8000, Change num <- num + 3.',
        'Algorithm 1 (display num, then num <- num + 3) produces 3, 6, 9, 12, ... Algorithm 2 (num <- num + 3, then display num) produces 6, 9, 12, ... Starting Algorithm 2 at 0 would display a number above 8000 on the last pass. So the C should be the last line of the while loop: the loop control variable is changed and then tested.',
        'When the end of the loop is reached, the condition at the beginning is tested again. If it is true the loop executes again; if it is false the loop terminates and the statement after the loop executes.',
      ],
      vocabulary: [
        { term: 'test variable (loop control variable)', definition: 'The variable used in the condition that controls whether the loop repeats, e.g. age or num.' },
        { term: 'IPO', definition: 'Decomposing a problem into Input, Processing and Output.' },
        { term: 'trace table', definition: 'A table that records the value of each variable, the result of each condition and the output, line by line, as an algorithm is executed by hand.' },
      ],
      workedExamples: [
        {
          code: 'begin\n    num <- 3\n    while (num <= 8000)\n        display num\n        num <- num + 3\n    end while\nend',
          explanation: 'Algorithm 1. The change is the last line of the loop, so each new value of num is tested before it is displayed.',
        },
        {
          code: 'Line  num  num <= 8000?  OUTPUT\n1     3\n2          true\n3                        3\n4     6\n2          true\n3                        6\n4     9',
          explanation: 'The start of the trace table for Algorithm 1. After line 4 control returns to the test on line 2.',
        },
      ],
      misconceptions: [
        'The order of "display" and "change" inside the loop does not matter. Wrong: changing first (Algorithm 2) skips the first value and can display a value past the limit.',
        'The condition of a while loop is tested only once, at the start. Wrong: it is tested again every time the end of the loop is reached.',
      ],
      questions: [
        {
          id: 'U9-T2-Q1',
          type: 'order',
          category: 'sequence',
          prompt: 'Put the steps used to solve the multiples of 3 problem in sections 9.3.1 to 9.3.6 in order.',
          items: [
            'Code the algorithm',
            'Decompose the problem in terms of IPO',
            'Evaluate the solution',
            'Design the algorithm',
            'Choose a data structure',
            'Test the code',
          ],
          answer: [1, 4, 3, 0, 5, 2],
          hint: 'Understand the problem first, improve the program last.',
          explanation: 'IPO, data structure, algorithm, code, test and evaluate is the problem-solving sequence used in section 9.3.',
          skills: ['U9-S3'],
        },
        {
          id: 'U9-T2-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'Why is Algorithm 1 (display num, then num <- num + 3) the correct solution for displaying the multiples of 3 up to 8000?',
          options: [
            'The change is the last line of the loop, so num is tested before it is displayed and nothing above 8000 is shown',
            'It uses fewer variables than Algorithm 2, so it executes faster and uses less memory',
            'It displays num after the loop has ended, so only the final multiple of 3 is shown',
            'It starts num at 0, so the first multiple of 3 is displayed correctly on the first pass',
          ],
          answer: 0,
          hint: 'Compare when num is tested and when it is displayed in each algorithm.',
          explanation: 'With the change as the last line, every new value of num is tested by the condition before it can be displayed.',
          skills: ['U9-S2', 'U9-S4'],
        },
        {
          id: 'U9-T2-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'The textbook says a for loop is not suitable for Activity 2 because we do not know how many times the loop will execute.',
          answer: true,
          hint: 'Section 9.3.3 explains why a condition is needed to stop the loop.',
          explanation: 'True. The textbook argues that because we do not know how many times the loop executes, we need a while loop with a condition that stops it.',
          skills: ['U9-S3'],
        },
        {
          id: 'U9-T2-Q4',
          type: 'trace',
          category: 'calculate',
          prompt: 'This is Algorithm 2 started at 0, as the textbook suggests, with the limit changed to 20. Fill in the values.',
          code: 'int num = 0;\nwhile (num <= 20)\n{\n    num = num + 3;\n    System.out.print(num + " ");\n}',
          rows: [
            { label: 'First number displayed', answer: '3' },
            { label: 'Last number displayed', answer: '21' },
            { label: 'How many numbers are displayed', answer: '7' },
          ],
          hint: 'The last pass starts when num is 18.',
          explanation: 'It displays 3, 6, 9, 12, 15, 18, 21. On the last pass 18 <= 20 is true, so 21 is displayed, going over the limit. That is why Algorithm 1 is preferred.',
          skills: ['U9-S6', 'U9-S2'],
        },
      ],
    },
    {
      id: 'U9-T3',
      title: 'Coding, Testing and Evaluating Mult3',
      sections: ['9.3.4', '9.3.5', '9.3.6'],
      skills: ['U9-S3', 'U9-S11', 'U9-S6'],
      explanation: [
        'Activity 3 codes Algorithm 1 as Mult3: display the heading MULTIPLES OF 3 BETWEEN 1 and 8000, set num = 3, and while (num <= 8000) display num followed by a space and add 3 to num. After the loop, System.out.println() moves to a new line.',
        'Testing: check that multiples of 3 are displayed across the screen, ending with a number less than 8000 (the last is 7998). The program needs no input, so no test data can be used. Changing the condition to num < 8000 makes no difference here because 8000 is not a multiple of 3, but it could for other data.',
        'Evaluating: the output can be improved by displaying 10 numbers on a line, calling System.out.println() every 10th number. Algorithm 3 uses a counter (count <- count + 1, and if count % 10 == 0 go to the next line). Algorithm 4 goes to the next line when num is a multiple of 30.',
        'The textbook argues Algorithm 4 is better because it uses fewer variables, but both are less efficient than Algorithm 1 because the if statement is checked every time the loop executes, while it is only true every 10th time. There is always a trade-off: better output costs more execution time.',
        'Be careful: Algorithm 4 as printed adds 3 before displaying num, the same pattern rejected in Algorithm 2, so it starts at 6 and would display 8001. Keep "display" before "change".',
        'Exercise 1 (WhileEx): display all integers from -10 to 50 with two spaces between each, adapt it for -20 to 100, then input the starting and ending values and display the multiples of 4 between them.',
      ],
      vocabulary: [
        { term: 'counter', definition: 'A variable that is increased by 1 (count = count + 1) each time something happens, used to count passes or items.' },
        { term: 'trade-off', definition: 'Gaining one advantage (such as neater output) at the cost of another (such as more execution time).' },
        { term: 'test data', definition: 'Values entered to check that a program produces the correct results; Mult3 needs none because it has no input.' },
      ],
      workedExamples: [
        {
          code: 'int num = 3;\nint count = 0;\nwhile (num <= 8000)\n{\n    System.out.print(num + " ");\n    count = count + 1;\n    if (count % 10 == 0)\n    {\n        System.out.println();\n    }\n    num = num + 3;\n}',
          explanation: 'Algorithm 3 in Java: 10 multiples of 3 per line. The change num = num + 3 stays the last line of the loop.',
        },
        {
          code: 'int num = -10;\nwhile (num <= 50)\n{\n    System.out.print(num + "  ");\n    num = num + 1;\n}',
          explanation: 'Exercise 1 (WhileEx): integers from -10 to 50 with two spaces between each.',
        },
      ],
      misconceptions: [
        'A program with no input cannot be tested. Wrong: you still check the output, for example that the last number is below 8000.',
        'Adding an if statement inside the loop has no cost. Wrong: it is checked on every pass, which costs execution time.',
      ],
      questions: [
        {
          id: 'U9-T3-Q1',
          type: 'tf',
          category: 'predict',
          prompt: 'Changing the Mult3 condition from num <= 8000 to num < 8000 changes the numbers that are displayed.',
          answer: false,
          hint: 'Is 8000 itself a multiple of 3?',
          explanation: 'False. num only takes multiples of 3, and 8000 is not one, so both conditions stop after 7998.',
          skills: ['U9-S3'],
        },
        {
          id: 'U9-T3-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'Algorithms 3 and 4 display 10 numbers per line. What trade-off does the textbook describe?',
          options: [
            'They use less memory than Algorithm 1 because the if statement replaces part of the loop',
            'They run faster than Algorithm 1 because fewer numbers are displayed on each line',
            'They need test data, whereas Algorithm 1 cannot be tested in any way at all',
            'The output is improved, but the if is checked every pass while true only every 10th pass, costing execution time',
          ],
          answer: 3,
          hint: 'How often is the if statement checked, and how often is it true?',
          explanation: 'The if statement improves the output but must be checked on every pass, so execution time increases. A programmer must decide which is best for the problem.',
          skills: ['U9-S3', 'U9-S11'],
        },
        {
          id: 'U9-T3-Q3',
          type: 'trace',
          category: 'calculate',
          prompt: 'A small version of Algorithm 3 with 5 numbers per line. Fill in the values.',
          code: 'int num = 3;\nint count = 0;\nwhile (num <= 30)\n{\n    System.out.print(num + " ");\n    count = count + 1;\n    if (count % 5 == 0)\n    {\n        System.out.println();\n    }\n    num = num + 3;\n}',
          rows: [
            { label: 'Numbers displayed on the first line', answer: '5' },
            { label: 'count after the loop', answer: '10' },
            { label: 'num after the loop', answer: '33' },
          ],
          hint: 'List the values of num that pass the test: 3, 6, 9, ...',
          explanation: '3 to 30 in steps of 3 is 10 numbers, split 5 per line. After 30 is displayed num becomes 33 and the test fails.',
          skills: ['U9-S11', 'U9-S6'],
        },
      ],
    },
    {
      id: 'U9-T4',
      title: 'SITC for While Loops',
      sections: ['9.4'],
      skills: ['U9-S4'],
      explanation: [
        'Every while loop must have the same structure so that it will work correctly. You must identify a condition that will allow you to use a while loop in the same way as you do with an if statement. This condition will involve one or more variables.',
        'S - Select the test variable(s) to use in the condition, e.g. ans or num.',
        'I - Give the test variable(s) an initial value, e.g. by an input statement such as ans = JOptionPane.showInputDialog(...).charAt(0); or num = 3;',
        'T - Test the condition in the while heading, e.g. while (ans == \'Y\' | ans == \'y\') or while (num < 80).',
        'C - Change the value of the test variable(s) just before the end of the loop, e.g. input ans again, or num = num + 3;',
        'Select and initialise the test variable(s) BEFORE the start of the while loop. Change the value of the test variable JUST BEFORE THE END of the while loop. ALWAYS use SITC when you design a while loop, so that it will work properly.',
      ],
      vocabulary: [
        { term: 'S (Select)', definition: 'Select the test variable(s) to use in the condition.' },
        { term: 'I (Initialise)', definition: 'Give the test variable(s) an initial value.' },
        { term: 'T (Test)', definition: 'Test the condition in the while heading.' },
        { term: 'C (Change)', definition: 'Change the value of the test variable(s) just before the end of the loop.' },
      ],
      workedExamples: [
        {
          code: 'SELECT and INITIALISE the variable(s) to be tested in the condition\nwhile (TEST condition is true)\n    ... statement(s) in the loop\n    CHANGE the test variable at the end of the loop\nend while\n... statement(s) after the loop',
          explanation: 'The SITC pattern in pseudocode, as given in section 9.4.',
        },
      ],
      misconceptions: [
        'The test variable should be initialised inside the loop. Wrong: it must get its value before the loop so that the condition can be tested the first time.',
        'SITC only works with number variables. Wrong: the test variable can be a char answer such as ans, initialised and changed by input statements.',
      ],
      questions: [
        {
          id: 'U9-T4-Q1',
          type: 'mc',
          category: 'define',
          prompt: 'In SITC, what does I stand for?',
          options: [
            'Increment the test variable by 1 every time the loop runs',
            'Give the test variable(s) an initial value before the loop',
            'Input a new value at the start of every pass of the loop',
            'Indent all the statements between the curly brackets',
          ],
          answer: 1,
          hint: 'It happens before the while heading.',
          explanation: 'I means Initialise: give the test variable(s) an initial value before the loop starts.',
          skills: ['U9-S4'],
        },
        {
          id: 'U9-T4-Q2',
          type: 'tf',
          category: 'apply',
          prompt: 'Following SITC, the test variable should be changed as the first statement inside the loop.',
          answer: false,
          hint: 'Where does the textbook say C belongs?',
          explanation: 'False. The change should be just before the end of the loop, so that the new value is tested before it is used.',
          skills: ['U9-S4'],
        },
        {
          id: 'U9-T4-Q3',
          type: 'mc',
          category: 'identify',
          prompt: 'Which statement is the C (Change) in this loop?',
          code: 'int num = 3;\nwhile (num <= 8000)\n{\n    System.out.print(num + " ");\n    num = num + 3;\n}',
          options: ['int num = 3;', 'while (num <= 8000)', 'num = num + 3;', 'System.out.print(num + " ");'],
          answer: 2,
          hint: 'Which statement gives the test variable a new value inside the loop?',
          explanation: 'num = num + 3; changes the test variable just before the end of the loop. int num = 3; is S and I, and the while heading is T.',
          skills: ['U9-S4'],
        },
      ],
    },
    {
      id: 'U9-T5',
      title: 'Investigating SITC',
      sections: ['9.4.1', '9.4.1.1', '9.4.1.2', '9.4.1.3', '9.4.1.4'],
      skills: ['U9-S5', 'U9-S6', 'U9-S4', 'U9-S11'],
      explanation: [
        'Activity 4 shows why none of the SITC parts can be left out of a while loop.',
        'S is important (Sale1): an article costs R200 and drops by R10 on each of 5 sale days. price is initialised to 200, yet day <= 5 is the condition. day must be selected and initialised to 1 before the loop. The fixed program displays Sale Day 1 Price R 190 down to Sale Day 5 Price R 150.',
        'I is important (Sum20): add consecutive positive integers from 1 while their sum is less than 20. With int sum; and no initial value, Java gives the error "variable sum might not have been initialized". Initialising sum to 1 fixes it, and the last line displayed is "The sum of 5 natural numbers is 15".',
        'T is important (BlastOff): with num = 10 and while (num < 10) the condition is false at once, so only Count Down and BLAST OFF! are displayed. The correct test is num >= 0. (num == 10) runs the body once; (num > 0 && num < 0) can never be true; (num > 0 && num < 10) is false at the start because num is 10.',
        'C is important (Sale2): day = 1 but day is never changed, so day <= 5 is always true. The loop is infinite and keeps displaying Sale Day 1 with a price that keeps dropping, even below R0. Add day = day + 1 as the last line of the loop.',
        'Exercise 2 practises SITC with sequences and series. A sequence is a set of numbers with a relationship, e.g. the even numbers 2, 4, 6, ... have a step of 2 (EvenNums: 2 to 500, 5 per line with a counter; EvenNums2 does the same with a for loop). A series is a sequence added together: WhileSum adds 1 + 2 + 3 + ... until the sum is just greater than 5000, which needs 100 integers (sum 5050).',
      ],
      vocabulary: [
        { term: 'sequence', definition: 'A set of numbers that usually have some relationship between them, e.g. 2, 4, 6, 8, 10.' },
        { term: 'step', definition: 'The difference from one number in a sequence to the next, e.g. 2 for the even numbers.' },
        { term: 'series', definition: 'A sequence of numbers added together, e.g. 1 + 4 + 7 + 10.' },
      ],
      workedExamples: [
        {
          code: 'int num = 1;\nint sum = 1;\nwhile (sum < 20)\n{\n    System.out.println("The sum of " + num + " natural numbers is " + sum);\n    num = num + 1;\n    sum = sum + num;\n}',
          explanation: 'Sum20 corrected. It displays the sums 1, 3, 6, 10 and 15, then stops when sum becomes 21.',
        },
        {
          code: 'System.out.println("Count Down");\nint num = 10;\nwhile (num >= 0)\n{\n    System.out.print(num + ". . .");\n    num = num - 1;\n}\nSystem.out.println("BLAST OFF!");',
          explanation: 'BlastOff with the correct test. It displays 10 down to 0 and then BLAST OFF!',
        },
      ],
      misconceptions: [
        'Java automatically sets a new int variable to 0. Wrong for variables declared in main: using sum before giving it a value is a compile error.',
        'If a program compiles and runs, its condition must be right. Wrong: BlastOff runs without errors but displays no numbers, which is a logical error.',
      ],
      questions: [
        {
          id: 'U9-T5-Q1',
          type: 'mc',
          category: 'identify',
          prompt: 'Sum20 declares int sum; without a value and then tests while (sum < 20). What happens?',
          options: [
            'It does not compile: Java reports that the variable sum might not have been initialized',
            'It runs and displays the sums starting from 0, because Java sets sum to 0 automatically',
            'It compiles, but the loop is infinite because sum has no value that can change',
            'It runs but displays nothing, because the condition is false at the start of the loop',
          ],
          answer: 0,
          hint: 'This is the "I is important" example.',
          explanation: 'Java will not let you use a local variable before it has a value, so the I step is essential.',
          skills: ['U9-S5', 'U9-S4'],
        },
        {
          id: 'U9-T5-Q2',
          type: 'trace',
          category: 'predict',
          prompt: 'BlastOff with the condition changed to (num == 10). Fill in the values.',
          code: 'int num = 10;\nwhile (num == 10)\n{\n    System.out.print(num + ". . .");\n    num = num - 1;\n}\nSystem.out.println("BLAST OFF!");',
          rows: [
            { label: 'Times the loop body runs', answer: '1' },
            { label: 'num after the loop', answer: '9' },
          ],
          hint: 'What is num after the first pass, and is it still equal to 10?',
          explanation: 'The first test is true, 10. . . is displayed and num becomes 9. Then 9 == 10 is false, so the output is 10. . .BLAST OFF!',
          skills: ['U9-S5', 'U9-S6'],
        },
        {
          id: 'U9-T5-Q3',
          type: 'tf',
          category: 'explain',
          prompt: 'With the condition (num > 0 && num < 0), the BlastOff loop body is never carried out, whatever the value of num.',
          answer: true,
          hint: 'Can a number be greater than 0 and less than 0 at the same time?',
          explanation: 'True. No number is both greater than 0 and less than 0, so the condition is always false.',
          skills: ['U9-S5'],
        },
        {
          id: 'U9-T5-Q4',
          type: 'mc',
          category: 'classify',
          prompt: 'Sale2 sets day = 1, tests while (day <= 5), and inside the loop only reduces and displays the price. Which SITC step is missing?',
          options: [
            'S: the wrong variable was selected as the test variable',
            'I: day was never given an initial value',
            'T: the condition day <= 5 is the wrong test',
            'C: day is never changed inside the loop',
          ],
          answer: 3,
          hint: 'The loop never ends. Which step makes a condition eventually become false?',
          explanation: 'Without day = day + 1 at the end of the loop, day stays 1 and the loop is infinite.',
          skills: ['U9-S5', 'U9-S4'],
        },
      ],
    },
    {
      id: 'U9-T6',
      title: 'While Loops with a Given Terminating Value',
      sections: ['9.5'],
      skills: ['U9-S7', 'U9-S11'],
      explanation: [
        'Sometimes you are told to input data until a terminating (dummy or rogue) value is typed in. This rogue value must be used in the condition to test whether input must continue. The rogue value must not be used in any calculations involving the data.',
        'Activity 5 (AvgMarks) inputs an unknown quantity of IT test marks, ending with -1, and displays the average. Marks are 0 or more, so -1 can never be a real mark; the condition is mark != -1. A while loop is used rather than a for loop so that it works for any number of students.',
        'Pseudocode: total <- 0, counter <- 0, input mark; while (mark != -1): total <- total + mark, counter <- counter + 1, input mark; end while; average <- total / counter; display average and counter. Learn this algorithm: it is a generic solution that can be adapted for similar problems.',
        'Test results: 45, 48, 43, -1 gives total 136, counter 3 and average 45.33 (45 with int division). The first set of 14 marks totals 899 (average 64.21) and the second set of 16 marks totals 389 (average 24.31).',
        'Choose a rogue value that can never be real data. AddInts adds any integers until -99 is entered, but -99 could be a genuine integer, so it is not an ideal rogue value. For surnames, a value such as * or XXX works.',
        'Exercise 3 also practises: Prices (rogue value 0, total R458.22 to 2 decimal places), Sale3 (R200 reduced by R8 a day until just below R100: 13 days, R96), DivideNums (48 24 12 6 3 by halving), Dice (random 1 to 6 until a 6, then THE END; if the first number is 6 only THE END appears) and Random99 (0 to 99 until 0, with a counter).',
        'Check Point 2: while loops are necessary when the number of repetitions is not known. "For loops are like while loops, the ITC is built in": the for header contains the initialise, test and change parts.',
      ],
      vocabulary: [
        { term: 'rogue value', definition: 'A terminating (dummy) value typed in to stop input; it is used in the condition but not in any calculations.' },
        { term: 'terminating value', definition: 'Another name for the rogue value that ends the input, e.g. -1 for marks.' },
        { term: 'total', definition: 'A variable initialised to 0 before the loop, to which each data value is added inside the loop.' },
      ],
      workedExamples: [
        {
          code: 'int total = 0;\nint counter = 0;\nint mark = Integer.parseInt(JOptionPane.showInputDialog("Input mark (-1 to stop)"));\nwhile (mark != -1)\n{\n    total = total + mark;\n    counter = counter + 1;\n    mark = Integer.parseInt(JOptionPane.showInputDialog("Input mark (-1 to stop)"));\n}\ndouble average = (double) total / counter;\nSystem.out.println("Average: " + average + " for " + counter + " marks");',
          explanation: 'AvgMarks. The -1 is tested but never added or counted. Casting to double avoids int division.',
        },
        {
          code: 'int num = 48;\nwhile (num > 1)\n{\n    System.out.print(num + " ");\n    num = num / 2;\n}',
          explanation: 'DivideNums: displays 48 24 12 6 3. After 3, num / 2 is 1 (int division), so the loop ends.',
        },
      ],
      misconceptions: [
        'The rogue value can be counted like the other data. Wrong: counting or adding -1 makes the total and the average incorrect.',
        'total / counter always gives a decimal answer. Wrong: if both are int, Java truncates the result, e.g. 136 / 3 is 45.',
      ],
      questions: [
        {
          id: 'U9-T6-Q1',
          type: 'tf',
          category: 'apply',
          prompt: 'In AvgMarks, the rogue value -1 is added to total and counted before the loop stops.',
          answer: false,
          hint: 'Where is the new mark tested in relation to where it is added?',
          explanation: 'False. The new mark is input as the last statement of the loop and tested immediately, so -1 ends the loop before it can be added or counted.',
          skills: ['U9-S7'],
        },
        {
          id: 'U9-T6-Q2',
          type: 'mc',
          category: 'explain',
          prompt: 'AddInts adds an unknown quantity of any integers and stops when -99 is entered. Is -99 a good rogue value?',
          options: [
            'Yes, because negative integers are never entered when integers are added together',
            'Not really, because any integer may be entered, so -99 could be genuine data the user wants to add',
            'Yes, because the rogue value must always be added to the sum to end the loop',
            'No, because a rogue value must always be 0 so that it does not change the sum',
          ],
          answer: 1,
          hint: 'The test data for AddInts includes negative numbers such as -19.',
          explanation: 'A rogue value should be a value that can never be real data. Since any integer could be entered, -99 might be a genuine value.',
          skills: ['U9-S7'],
        },
        {
          id: 'U9-T6-Q3',
          type: 'trace',
          category: 'calculate',
          prompt: 'AddInts: the user types 8, 45, -19, 77, 50, 12, -4, -6, 13, 0 and then -99. Fill in the values.',
          code: 'int sum = 0;\nint num = Integer.parseInt(JOptionPane.showInputDialog("Enter an integer (-99 to stop)"));\nwhile (num != -99)\n{\n    sum = sum + num;\n    num = Integer.parseInt(JOptionPane.showInputDialog("Enter an integer (-99 to stop)"));\n}\nSystem.out.println("The sum is " + sum);',
          rows: [
            { label: 'sum after the loop', answer: '176' },
            { label: 'Times the loop body runs', answer: '10' },
          ],
          hint: 'Add the ten values carefully, including the negatives and the 0. Do not add -99.',
          explanation: '8 + 45 - 19 + 77 + 50 + 12 - 4 - 6 + 13 + 0 = 176. The body runs once for each of the 10 values; -99 is only tested.',
          skills: ['U9-S11', 'U9-S7'],
        },
      ],
    },
    {
      id: 'U9-T7',
      title: 'Errors in While Loops',
      sections: ['9.6'],
      skills: ['U9-S8', 'U9-S6', 'U9-S11'],
      explanation: [
        'While_Error_One (Activity 6) should add non-zero integers until 0 is entered, but tests while (number == 0). If the first number is not 0, the loop is skipped and the sum 0 is displayed. The correct test is number != 0; with test data 7, -5, 2, 0 the sum is 4.',
        'While_Error_Two has no C: there is no input inside the loop, so number never changes. With 7 as input the loop is infinite, sum keeps growing and nothing is displayed. Fix it by inserting number = Integer.parseInt(JOptionPane.showInputDialog("Enter an integer ")); as the last statement in the loop, after sum = sum + number;',
        'EvenNumbers should display the positive even numbers up to and including 10, but starts at 0 and tests even < 10, so it displays 0, 2, 4, 6, 8. Start at 2 and test even <= 10.',
        'OtherLoopErrors: a ; at the end of the while header makes the loop infinite, because the empty statement before the ; is the whole loop body. After removing it, (ch != \'X\' || ch != \'x\') is still always true. When checking if more than one item is equal, use OR (||). When checking if more than one item is not equal, use AND (&&).',
        'If you have a logical error in a while loop, check SITC first, because most errors result from these four steps. If that does not solve the problem, use a trace table.',
        'Exercise 5 practises loops with counters, totals, maximums and minimums: StarStop (count characters before *), AvgGirlsNames (average of name.length(), rounded), Heights (tallest and shortest), Rainfall (total, average, maximum and its day), HowMany1 (2 + 5 + 8 + ... just greater than 610 needs 21 numbers, sum 672), HowMany2 (1 + 1/2 + 1/3 + ... just greater than 6 needs 227 numbers; use 1.0/number to avoid int division), ExamAvgs, ThreeLetterWords and HiLoAveWhile (stop at 999).',
      ],
      vocabulary: [
        { term: 'infinite loop', definition: 'A loop whose condition never becomes false, usually because the test variable is not changed inside the loop.' },
        { term: 'logical error', definition: 'An error where the program runs but does not do what was intended, e.g. a wrong condition.' },
        { term: 'AND rule for not equal', definition: 'When checking that an item is not equal to more than one value, join the tests with && (use || for equal).' },
      ],
      workedExamples: [
        {
          code: 'int number, sum = 0;\nnumber = Integer.parseInt(JOptionPane.showInputDialog("Enter an integer "));\nwhile (number != 0)\n{\n    sum = sum + number;\n    number = Integer.parseInt(JOptionPane.showInputDialog("Enter an integer "));\n}\nSystem.out.println("The sum of the integers is " + sum);',
          explanation: 'While_Error_Two fixed by adding the C: a new input as the last statement in the loop.',
        },
        {
          code: 'while (ch != \'X\' && ch != \'x\')\n{\n    System.out.println("You typed in " + ch);\n    ch = JOptionPane.showInputDialog("Input any character (x to stop)").charAt(0);\n}',
          explanation: 'OtherLoopErrors fixed: no semicolon after the header, and && because both tests are "not equal".',
        },
      ],
      misconceptions: [
        'A semicolon after a while header is harmless, like extra spaces. Wrong: it becomes an empty loop body and usually an infinite loop.',
        'To stop on x or X you write ch != \'X\' || ch != \'x\'. Wrong: this is always true; use &&.',
      ],
      questions: [
        {
          id: 'U9-T7-Q1',
          type: 'mc',
          category: 'explain',
          prompt: 'What is the most common cause of infinite loops in while loops?',
          options: [
            'The test variable is not changed inside the loop, so the condition stays true',
            'The test variable is initialised before the loop instead of inside the loop',
            'The loop body contains more than one statement between the curly brackets',
            'The condition uses the != operator instead of a relational operator such as <',
          ],
          answer: 0,
          hint: 'Which SITC step makes the condition eventually become false?',
          explanation: 'If C is missing, nothing changes the test variable, so a condition that starts true stays true forever.',
          skills: ['U9-S8'],
        },
        {
          id: 'U9-T7-Q2',
          type: 'trace',
          category: 'predict',
          prompt: 'EvenNumbers should display positive even numbers up to and including 10. Fill in what it actually does.',
          code: 'int even = 0;\nwhile (even < 10)\n{\n    System.out.println(even);\n    even = even + 2;\n}',
          rows: [
            { label: 'First value displayed', answer: '0' },
            { label: 'Last value displayed', answer: '8' },
            { label: 'How many values are displayed', answer: '5' },
          ],
          hint: 'When even reaches 10, is 10 < 10 true?',
          explanation: 'It displays 0, 2, 4, 6, 8. 0 is not positive and 10 is missing; start at 2 and use even <= 10.',
          skills: ['U9-S6', 'U9-S8'],
        },
        {
          id: 'U9-T7-Q3',
          type: 'tf',
          category: 'apply',
          prompt: 'When checking that a variable is not equal to more than one value, the textbook says to join the tests with AND (&&).',
          answer: true,
          hint: 'Let ch be x. Which of ch != \'X\' and ch != \'x\' is true, and which joining operator makes the loop stop?',
          explanation: 'True. Equal tests are joined with OR (||) and not-equal tests with AND (&&).',
          skills: ['U9-S8', 'U9-S11'],
        },
      ],
    },
    {
      id: 'U9-T8',
      title: 'Do While Loops',
      sections: ['9.7', '9.7.1', '9.7.1.1'],
      skills: ['U9-S9'],
      explanation: [
        'CheckInput can be written as a do loop (CheckInput2): do { age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120")); } while (age < 0 || age > 120); Testing with 30 accepts it at once; testing with 150, 200, -2 and 4 asks again until 4 is entered.',
        'The while loop has only the keyword while to mark the beginning of the loop, has no semicolon after the condition, may not be executed at all (if the initial value of the test variable makes the condition false), has its condition tested at the beginning of the loop statements, and uses SITC.',
        'The do...while loop has the keyword do at the beginning of the loop and while at the end (before the condition), has a semicolon after the condition because that is the end of the loop, is always carried out at least once, has its condition tested at the end of the loop statements, and uses SICT.',
        'Flow charts: in a while loop the decision (condition) comes before the loop body; in a do...while loop the body comes first and the decision is at the bottom. Both loops are carried out if the condition is true, or until the condition becomes false.',
        'The do...while loop is used much less often than the while loop because you are usually not sure that the loop must be carried out at least once. Menus can use do...while because a menu must always be displayed once, and do loops are useful to validate input.',
        'Activity 8 (ColSquare) displays a COLOUR MENU (B Blue, R Red, G Green, Q Quit) and uses the Gogga to draw in the chosen colour until Q or q is chosen. Exercise 6 adds CheckInt (a 5-option menu on an integer), QuantityPosInts (consecutive integers until the sum is just greater than 20: 6 integers, sum 21, with while and then do...while) and a greeting loop that ends when QUIT is typed, extended with equalsIgnoreCase().',
      ],
      vocabulary: [
        { term: 'do...while loop', definition: 'A loop that carries out its body first and tests its condition at the end, so it is always carried out at least once.' },
        { term: 'SICT', definition: 'The order used by a do...while loop: Select, Initialise, Change, then Test at the end.' },
        { term: 'validate input', definition: 'Make sure the user cannot proceed in the program until they have entered acceptable data.' },
      ],
      workedExamples: [
        {
          code: 'int age;\ndo\n{\n    age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120"));\n}\nwhile (age < 0 || age > 120);// end do',
          explanation: 'CheckInput2. Only one input statement is needed because the body always runs at least once.',
        },
        {
          code: 'String input;\ndo\n{\n    input = JOptionPane.showInputDialog("Type in any greeting - Type QUIT to stop");\n    if (input.equalsIgnoreCase("Hi"))\n    {\n        System.out.println("Hi to you too");\n    }\n    else if (input.equalsIgnoreCase("Hello"))\n    {\n        System.out.println("How are you?");\n    }\n    else\n    {\n        System.out.println(input + " yourself!");\n    }\n}\nwhile (!input.equals("QUIT"));\nSystem.out.println("Bye!");',
          explanation: 'The Exercise 6 greeting loop using equalsIgnoreCase(). input is declared before do so that the while condition can use it.',
        },
      ],
      misconceptions: [
        'A do...while loop needs no semicolon, just like a while loop. Wrong: the ; after the condition ends the do loop.',
        'A do...while loop tests its condition before running. Wrong: it runs the body first and tests at the end.',
      ],
      questions: [
        {
          id: 'U9-T8-Q1',
          type: 'mc',
          category: 'distinguish',
          prompt: 'How do SITC and SICT relate to the two kinds of loop?',
          options: [
            'The while loop uses SICT and the do...while loop uses SITC',
            'Both loops use SITC, because the test is always in the while heading',
            'The while loop uses SITC and the do...while loop uses SICT, because its test is at the end',
            'Neither loop uses a test variable; only a for loop has one',
          ],
          answer: 2,
          hint: 'Where is the Test placed in each loop?',
          explanation: 'A while loop tests at the beginning (SITC). A do...while loop changes the test variable inside the body and tests at the end (SICT).',
          skills: ['U9-S9'],
        },
        {
          id: 'U9-T8-Q2',
          type: 'tf',
          category: 'distinguish',
          prompt: 'A do...while loop may not be executed at all if its condition is false.',
          answer: false,
          hint: 'When is the condition of a do loop tested for the first time?',
          explanation: 'False. A do...while loop is always carried out at least once. It is the while loop that may not be executed at all.',
          skills: ['U9-S9'],
        },
        {
          id: 'U9-T8-Q3',
          type: 'order',
          category: 'sequence',
          prompt: 'Arrange the lines of CheckInput2 in the correct order.',
          items: [
            'while (age < 0 || age > 120);',
            'int age;',
            '{',
            'do',
            'age = Integer.parseInt(JOptionPane.showInputDialog("Enter your age from 0 to 120"));',
            '}',
          ],
          answer: [1, 3, 2, 4, 5, 0],
          hint: 'Declare first; the condition is the very last line.',
          explanation: 'Declare age, then do, the body in braces, and finally while (condition); with its semicolon.',
          skills: ['U9-S9'],
        },
        {
          id: 'U9-T8-Q4',
          type: 'mc',
          category: 'predict',
          prompt: 'The user types Hello and then QUIT. What is displayed?',
          code: 'String input;\ndo\n{\n    input = JOptionPane.showInputDialog("Type in any greeting e.g. Hi, Hello, etc - Type QUIT to stop");\n    if (input.equals("Hi"))\n    {\n        System.out.println("Hi to you too");\n    }\n    else if (input.equals("Hello"))\n    {\n        System.out.println("How are you?");\n    }\n    else\n    {\n        System.out.println(input + " yourself!");\n    }\n}\nwhile (!input.equals("QUIT"));\nSystem.out.println("Bye!");',
          options: [
            'How are you? then Bye!',
            'How are you? then QUIT yourself!',
            'Hello yourself! then QUIT yourself! then Bye!',
            'How are you? then QUIT yourself! then Bye!',
          ],
          answer: 3,
          hint: 'QUIT goes through the if statements before the condition at the end is tested.',
          explanation: 'QUIT is not Hi or Hello, so "QUIT yourself!" is displayed before the test at the end stops the loop, then Bye! is displayed.',
          skills: ['U9-S9'],
        },
      ],
    },
    {
      id: 'U9-T9',
      title: 'Choosing an Appropriate Looping Structure',
      sections: ['9.8'],
      skills: ['U9-S10'],
      explanation: [
        'There are three looping structures in Java: the for loop, the while loop and the do loop. Any one of the loops can be used in place of any one of the other loops, but it is often more appropriate to use one type of loop in a particular situation.',
        'The flea market example counts items sold: itemCount starts at 0, ans is input (Y/N), and while (ans == \'Y\' | ans == \'y\') itemCount is increased and ans is input again.',
        'The same code can be written with a for loop, because a for loop has three parts: initialise a variable, test a condition and change the loop variable. It gives the correct output, but the textbook does not recommend it: when the number of iterations is not known beforehand, a while loop is more intuitive and readable.',
        'A problem coded with a for loop can always be rewritten with a while loop or a do-while loop and vice versa. The choice of loop is an issue of code readability, rather than what is possible.',
        'Recommendations: use a for loop when the number of iterations is known beforehand; use a while loop when it is not known beforehand; use a do while loop where at least one pass through the loop must be made.',
      ],
      vocabulary: [
        { term: 'iteration', definition: 'One pass through the body of a loop.' },
        { term: 'readability', definition: 'How easily a person can read and understand code; the main reason for choosing one loop over another.' },
      ],
      workedExamples: [
        {
          code: 'int itemCount = 0;\nchar ans = JOptionPane.showInputDialog("Has an item been sold? (Y/N)").charAt(0);\nwhile (ans == \'Y\' | ans == \'y\')\n{\n    itemCount = itemCount + 1;\n    ans = JOptionPane.showInputDialog("Has an item been sold? (Y/N)").charAt(0);\n}\nSystem.out.println("The total number of items sold is " + itemCount);',
          explanation: 'The flea market count with a while loop, following SITC with ans as the test variable.',
        },
        {
          code: 'int i = 0;\nwhile (i <= 5)\n{\n    System.out.println("Hi there");\n    i++;\n}',
          explanation: 'The for loop for (int i = 0; i <= 5; i++) rewritten as a while loop (Check Point 2).',
        },
      ],
      misconceptions: [
        'Some problems can only be solved with a while loop. Wrong: any loop can be rewritten as another type; the choice is about readability.',
        'A for loop is always the best loop because it is shortest. Wrong: when the number of iterations is unknown, a while loop is clearer.',
      ],
      questions: [
        {
          id: 'U9-T9-Q1',
          type: 'mc',
          category: 'apply',
          prompt: 'Which loop does the textbook recommend for inputting supermarket prices until the rogue value 0 is entered?',
          options: [
            'A for loop, because every price that is entered is counted',
            'A while loop, because the number of iterations is not known beforehand',
            'A do while loop, because the rogue value must be added at least once',
            'No loop at all, because an if statement can check every price',
          ],
          answer: 1,
          hint: 'Do you know how many prices there will be?',
          explanation: 'The number of prices is unknown and there may be none at all, so a while loop is recommended.',
          skills: ['U9-S10'],
        },
        {
          id: 'U9-T9-Q2',
          type: 'tf',
          category: 'explain',
          prompt: 'According to section 9.8, the decision of which loop to use is about code readability rather than what is possible.',
          answer: true,
          hint: 'Can a for loop always be rewritten as a while loop?',
          explanation: 'True. Any loop can be rewritten as another type, so you choose the loop that makes the code most readable.',
          skills: ['U9-S10'],
        },
        {
          id: 'U9-T9-Q3',
          type: 'trace',
          category: 'calculate',
          prompt: 'In the flea market program the user types Y, then y, then N. Fill in the values.',
          code: 'int itemCount = 0;\nchar ans = JOptionPane.showInputDialog("Has an item been sold? (Y/N)").charAt(0);\nwhile (ans == \'Y\' | ans == \'y\')\n{\n    itemCount = itemCount + 1;\n    ans = JOptionPane.showInputDialog("Has an item been sold? (Y/N)").charAt(0);\n}\nSystem.out.println("The total number of items sold is " + itemCount);',
          rows: [
            { label: 'itemCount after the loop', answer: '2' },
            { label: 'Times the condition is tested', answer: '3' },
          ],
          hint: 'The condition accepts both uppercase and lowercase Y.',
          explanation: 'Y and y are both counted; N makes the condition false. The condition is tested for Y, y and N.',
          skills: ['U9-S10', 'U9-S6'],
        },
      ],
    },
  ],
};

export const SCENARIOS = [
  {
    id: 'u9-launch-countdown',
    unitId: UNIT.id,
    title: 'Countdown Control',
    icon: 'rocket',
    summary: 'A launch countdown loop is broken and the window is closing.',
    briefing: 'A weather rocket on the Overberg test range is fuelled and waiting, but the countdown program never reaches BLAST OFF. Somewhere a while loop has a missing initial value, a wrong test or a change that never happens. Trace the loops and repair SITC before the launch window closes.',
    tickerMessages: [
      'Overberg range: countdown display stuck on "Count Down"',
      'Engineers suspect the loop condition is false from the start',
      'Second screen now printing the same line over and over',
      'Fuel pressure rising while the infinite loop keeps running',
      'Range control: fix the loop or the launch is scrubbed',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['U9-S2', 'U9-S4', 'U9-S5', 'U9-S6', 'U9-S8'],
    victoryMessage: 'Every loop selects, initialises, tests and changes correctly. 10... 9... 8... BLAST OFF! The rocket clears the range.',
    failMessage: 'The countdown spun forever and the launch window closed. Check SITC first, then trace the loop.',
  },
  {
    id: 'u9-till-meltdown',
    unitId: UNIT.id,
    title: 'Black Friday Till Meltdown',
    icon: 'alert',
    summary: 'Supermarket tills are adding rogue values and freezing in menus.',
    briefing: 'It is Black Friday at a busy Johannesburg supermarket and the tills have gone haywire: the rogue value 0 is being added to totals, averages are wrong and the till menu never lets cashiers quit. Choose the right loops, fix the terminating values and get the queues moving before the store descends into chaos.',
    tickerMessages: [
      'Till 4 total includes a price of R0.00 after every customer',
      'Average spend report shows impossible figures',
      'Cashier menu will not accept Q to quit',
      'Queues now stretch to the parking lot',
      'Head office: fix the loops in the next four minutes or close the store',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['U9-S1', 'U9-S7', 'U9-S9', 'U9-S10', 'U9-S11'],
    victoryMessage: 'Totals are correct, the rogue value stays out of the maths and every menu quits on Q. The queues are flowing again.',
    failMessage: 'The tills are still looping and the store has closed. Keep rogue values out of calculations and use the right loop for the job.',
  },
];
