/*
 * One-line skill hints sent to the Do or Die question generator.
 */
export const SKILL_HINTS = {
  // Unit 2
  'U2-S1': 'a variable is a box in memory with three characteristics: identifier, data type and value',
  'U2-S2': 'JOptionPane.showInputDialog("prompt") (import javax.swing.*) returns the typed text as a String',
  'U2-S3': 'choose int for whole numbers, double for real numbers, String for text such as phone numbers and postal codes',
  'U2-S4': 'Integer.parseInt and Double.parseDouble convert input Strings; letters cause a NumberFormatException run time error',
  'U2-S5': 'arithmetic with + - * / % on int and double variables',
  'U2-S6': 'int / int drops the remainder (12 / 5 is 2), % gives the remainder (25 % 7 is 4), double ans = 5 / 2 stores 2.0',
  'U2-S7': 'assignment and overwriting, num++ / num--, compound operators += -= *= /= %=, sum =+ x is a mistake',
  'U2-S8': 'identifier rules: no starting digit, no spaces, no special characters, no reserved words; camel case convention',
  'U2-S9': '+ joins Strings: "The sum is " + 4 + 5 prints The sum is 45, but "The sum is " + (4 + 5) prints The sum is 9',
  'U2-S10': 'primitive types boolean, char, byte, short, int (32 bits), long, float, double (64 bits); range 2^(n-1) - 1; String is not primitive',
  'U2-S11': 'declare a variable once, initialise it before use (else a compile error), declare at the start of a method or when first used',
  'U2-S12': 'order of operations: brackets, then * / %, then + -, left to right; 4 + 5 * 3 - 12 % 5 is 17',
  // Unit 3
  'U3-S1': "char holds one character in single quotes ('a'); String holds many characters in double quotes",
  'U3-S2': "characters are Unicode integers: 'A' is 65, 'a' is 97; ch++ on 'a' gives 'b'; (char) 66 is 'B'",
  'U3-S3': "escape sequences \\n new line, \\t tab (not in showMessageDialog), \\\\ backslash, \\' and \\\" quotes",
  'U3-S4': 'length() counts all characters including spaces; charAt(i) starts at position 0; last character is at length() - 1',
  'U3-S5': 'widening (int to double) is automatic; narrowing needs a cast and (int) truncates; (double) 15 / 2 is 7.5 but 15 / 2 is 7',
  'U3-S6': 'conversions: parseInt / parseDouble from String, (int) and (char) casts, "" + num to make a String, str.charAt(0) to get a char',
  'U3-S7': 'Math.pow(2, 5) is 32.0, Math.sqrt(25) is 5.0, Math.sqrt(-16) is NaN, Math.round(2.6) is 3, Math.abs(-16) is 16, Math.PI is a constant',
  'U3-S8': 'JOptionPane.showMessageDialog(null, message) shows output in a dialog; null means no parent component; \\n works but \\t does not',
  'U3-S9': 'round to 2 decimal places: Math.round(num * 100) / 100.0, e.g. 5.6983 becomes 5.7',
  // Unit 4
  'U4-S1': 'the four computational thinking techniques: decomposition, pattern recognition, abstraction, algorithms',
  'U4-S2': 'understand the problem (read, underline what must be done, restate, list facts) then break it into smaller tasks',
  'U4-S3': 'IPO: input from the keyboard into variables in RAM, processing by the CPU and ALU, output to the monitor',
  'U4-S4': 'pattern recognition reuses existing programs, methods and generic algorithms; abstraction ignores irrelevant detail',
  'U4-S5': 'an algorithm is a step-by-step solution written as a flow chart or pseudocode; order matters',
  'U4-S6': 'pseudocode rules: begin/end, indent, left arrow for assignment, no semicolons, no declarations, input and display',
  'U4-S7': 'flow chart symbols: start/end, statement, input/output, decision diamond, connecting arrows',
  'U4-S8': 'user-friendly programs use clear prompts and meaningful, well laid out output; combine dialog output with \\n',
  'U4-S9': 'readability: descriptive names, one statement per line, indentation, comments, blank lines, conventions',
  'U4-S10': 'syntax error (compiler), run time error (program halts, e.g. 5.3 typed for an int), logical error (wrong result)',
  'U4-S11': 'test data for 1 to 10: standard 2 to 9, extreme 1 and 10 (correct) and 0 and 11 (incorrect), abnormal p, F7, -3',
  'U4-S12': 'trace tables: a column per variable plus screen output, filled in line by line',
  'U4-S13': 'data structure: the main variables and their types (double for money); temp variables are not part of it',
  'U4-S14': 'test with someone other than the programmer; acceptance testing checks the original criteria with the client; evaluate and optimise',
  'U4-S15': 'swop two values: temp = num1; num1 = num2; num2 = temp',
  'U4-S16': 'trace in the IDE: compile, set a breakpoint, debug, step line by line and watch variable values',
  'U4-S17': 'worked examples: CalcPrice (5% discount, 15% VAT on the discounted price) and TempConversion f = (9 * c) / 5 + 32',
  // Unit 5
  'U5-S1': 'a for loop is a counting loop that repeats code a set number of times',
  'U5-S2': 'for (int i = 1; i <= 5; i++): initialiser, condition, increment; the loop control variable only exists inside the loop',
  'U5-S3': 'count passes: for (int count = 10; count <= 20; count++) runs 11 times',
  'U5-S4': 'predict output of loop body and statements after the loop',
  'U5-S5': 'infinite loops (no condition, no increment, wrong direction), never-runs, runs-once, semicolon after the header',
  'U5-S6': 'backward loops: for (int loop = 10; loop > 5; loop--) runs 5 times',
  'U5-S7': "a char loop control variable: for (char ch = 'A'; ch <= 'E'; ch++) uses Unicode values",
  'U5-S8': 'step size other than 1: num = num + 2 for even numbers, x = x + 3 for dashed lines',
  'U5-S9': 'sum = 0 before the loop, sum = sum + num inside, average = sum / count after; num is overwritten each pass',
  'U5-S10': 'trace loop control variable, condition result and accumulators on every pass',
  'U5-S11': 'pseudocode: for loop from 1 to 10; inc by 1 ... end for, with indented statements',
  'U5-S12': 'flow chart of a for loop: initialise before, diamond test, True exit into body, arrow back to the diamond, False exit bypasses',
  'U5-S13': 'decompose loop problems into what happens before the loop, inside the loop and after the loop',
  'U5-S14': 'sum of a series 11 + 12 + 13 + ...: sum = sum + term; term = term + 1 inside the loop',
  'U5-S15': 'Gogga with loops: repeat move/turnLeft to draw shapes; use the loop variable in setPosition(x, 5)',
  // Unit 6
  'U6-S1': 'five Gogga constructors; overloading means same name, different parameters; method resolution picks the matching signature',
  'U6-S2': 'state diagram: field values (xPos, yPos, direction, color, trailWidth, showTrail, label) at a point in the program',
  'U6-S3': 'new Color(red, green, blue) with each value 0 to 255; built-in Color.blue; change an existing Gogga with setColor',
  'U6-S4': 'Gogga bug = new Gogga(); new creates an instance; default values xPos 7, yPos 5, UP, red, trail width 5',
  'U6-S5': 'an object variable stores the address of the object (null before new); int variables store their own value',
  'U6-S6': 'many independent objects from one class; bug.move() only changes bug',
  'U6-S7': 'API documentation: Constructor Summary, Field Summary, method signature (name plus parameter list), final constants',
  'U6-S8': 'Math.random() gives 0 <= r < 1; (int) (Math.random() * (B - A + 1)) + A gives a whole number from A to B',
  'U6-S9': 'random colour: (int) (Math.random() * 256) for each of red, green and blue, then new Color(red, green, blue)',
  // Unit 7
  'U7-S1': 'if (condition) { ... } else { ... }: one branch when true, the other when false',
  'U7-S2': 'relational operators == != < <= > >= and English equivalents (at least 21 means age >= 21)',
  'U7-S3': 'predict output of if / else for given inputs',
  'U7-S4': 'curly brackets group statements; layout and indentation aid reading',
  'U7-S5': 'opposite conditions: > is the opposite of <=, == is the opposite of !=',
  'U7-S6': 'nested if: an if in the else part of another if, so later conditions are skipped once one is true',
  'U7-S7': 'use else only when one condition can be true; independent tests need separate if statements',
  'U7-S8': 'AND & / &&, OR | / ||, NOT !; each part must be a full condition (age > 25 & age < 38)',
  'U7-S9': 'apply conditions in word problems (ticket prices, driving age, discount, divisibility)',
  'U7-S10': 'if...else is one statement; else is optional; use == not =; no semicolon after the condition; do not compare Strings with ==',
  'U7-S11': 'the ALU evaluates conditions; order is brackets, NOT, AND, OR, left to right',
  'U7-S12': '&& and || are conditional (skip the second part when the answer is known); & and | evaluate both parts',
  'U7-S13': 'negate a condition with ! and swop the then and else parts to keep the meaning',
  'U7-S14': "De Morgan's law: !(a > b & b < 10) becomes a <= b | b >= 10",
  'U7-S15': 'a variable only assigned inside if statements must be initialised first: int 0, String "", char such as \'X\'',
  'U7-S16': 'pseudocode if ... then ... else ... endif with indentation; decision diamond in a flow chart',
};
