import {
  Hash, ScrollText, Workflow, Repeat, Boxes, GitBranch, Binary,
} from 'lucide-react';

export const WORLDS = [
  {
    id: 'variables',
    name: 'Variables Lab',
    subtitle: 'Unit 2 · Types, arithmetic & input',
    color: 'cyan',
    glow: 'ja-glow-cyan',
    bg: 'ja-w-variables',
    icon: Hash,
    blurb: 'Where every value finds its slot. Pick the right type, predict the maths, master modulus.',
  },
  {
    id: 'strings',
    name: 'String Cave',
    subtitle: 'Unit 3 · Chars, strings & Math',
    color: 'magenta',
    glow: 'ja-glow-magenta',
    bg: 'ja-w-strings',
    icon: ScrollText,
    blurb: 'Single quotes vs double quotes. charAt zero. Escapes. The Math class. All in here.',
  },
  {
    id: 'algorithms',
    name: 'Algorithm Tower',
    subtitle: 'Unit 4 · Computational thinking',
    color: 'coral',
    glow: 'ja-glow-coral',
    bg: 'ja-w-algorithms',
    icon: Workflow,
    blurb: 'Decompose. Spot patterns. Abstract away noise. Flowcharts, pseudocode, errors, traces — the toolkit behind every program.',
  },
  {
    id: 'loops',
    name: 'Loop Mountain',
    subtitle: 'Unit 5 · for loops & repetition',
    color: 'amber',
    glow: 'ja-glow-amber',
    bg: 'ja-w-loops',
    icon: Repeat,
    blurb: 'Count up. Count down. Sum, average, never-runs, runs-forever. Climb every iteration.',
  },
  {
    id: 'objects',
    name: 'Object Forge',
    subtitle: 'Unit 6 · More about objects',
    color: 'indigo',
    glow: 'ja-glow-indigo',
    bg: 'ja-w-objects',
    icon: Boxes,
    blurb: 'Constructors, overloading, state diagrams, the Color class, random numbers. Where Gogga objects come from.',
  },
  {
    id: 'logic',
    name: 'Logic Base',
    subtitle: 'Unit 7 · if statements & decisions',
    color: 'emerald',
    glow: 'ja-glow-emerald',
    bg: 'ja-w-logic',
    icon: GitBranch,
    blurb: 'True or false. If, else, nested. AND, OR, NOT. Every branch leads somewhere.',
  },
  {
    id: 'binary',
    name: 'Binary Matrix',
    subtitle: 'Binary · calculations & conversions',
    color: 'lime',
    glow: 'ja-glow-lime',
    bg: 'ja-w-binary',
    icon: Binary,
    blurb: 'Ones and zeros. Convert, add, subtract. Bits, bytes, and the language every computer speaks.',
  },
];
