/*
 * Business Studies Do Or Die scenarios — timed missions per unit.
 */

export const SCENARIOS = [
  {
    id: 'b1-board-countdown',
    unitId: 'B1',
    title: 'Board Meeting Countdown',
    icon: 'briefcase',
    summary: 'Assemble the report before the board arrives.',
    briefing: 'The board meets in minutes. They need a structured business report on Green Harvest Farms. Answer questions on report sections, formal tone, and recommendations under time pressure.',
    tickerMessages: [
      'BOARD SECRETARY: Meeting moved forward — 4 minutes remaining.',
      'CHAIR: We need proper findings headings, not an essay.',
      'INVESTOR: Where are the recommendations?',
      'COMPLIANCE: Formal tone only — no slang.',
      'FINAL CALL: Submit the report structure now.',
    ],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS1-S1', 'BS1-S2', 'BS1-S3', 'BS1-S4'],
    victoryMessage: 'Report structure approved. The board is satisfied.',
    failMessage: 'Report rejected. Restructure and try again.',
  },
  {
    id: 'b1-deadline-report',
    unitId: 'B1',
    title: 'Deadline Report',
    icon: 'briefcase',
    summary: 'Write the report sections correctly before time runs out.',
    briefing: 'Your manager needs a business report on ownership options by end of day. Prove you know title, procedure, findings, conclusion, and recommendations.',
    tickerMessages: [
      'MANAGER: First draft due in 5 minutes.',
      'CLIENT: Is this a report or an essay?',
      'EDITOR: Add justified recommendations.',
      'BOSS: Link theory to the scenario.',
      'URGENT: Hand in now or miss the deadline.',
    ],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['BS1-S1', 'BS1-S3', 'BS1-S4'],
    victoryMessage: 'Report submitted on time. Excellent structure.',
    failMessage: 'Missed the deadline. Try again.',
  },
  {
    id: 'b2-vocab-vault',
    unitId: 'B2',
    title: 'Vocabulary Vault',
    icon: 'vault',
    summary: 'Unlock definitions before the exam locks.',
    briefing: 'The concept vault is sealing shut. Define capital, liability, legal personality, MOI, and CIPC correctly to escape with full marks.',
    tickerMessages: ['VAULT: 4 minutes to define key terms.', 'EXAMINER: Use correct business language.', 'ALARM: Vague answers detected.', 'LOCKDOWN: Final definitions required.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS2-S1', 'BS2-S2', 'BS2-S3', 'BS2-S4'],
    victoryMessage: 'Vault unlocked. Definitions mastered.',
    failMessage: 'Vault sealed. Study the definitions again.',
  },
  {
    id: 'b3-ownership-choice',
    unitId: 'B3',
    title: 'The Big Decision',
    icon: 'scale',
    summary: 'Seven factors. One correct ownership form.',
    briefing: 'An entrepreneur waits for your advice. Apply the seven factors — legal persona, liability, tax, continuity, management, capital, formation — before they sign the wrong structure.',
    tickerMessages: ['ENTREPRENEUR: Which form limits my personal risk?', 'LAWYER: Consider liability first.', 'ACCOUNTANT: Tax implications matter.', 'CIPC: Registration requirements vary.', 'DECISION DUE: Choose now.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS3-S1', 'BS3-S2'],
    victoryMessage: 'Correct form chosen. Risk minimised.',
    failMessage: 'Wrong structure chosen. Lawsuit incoming.',
  },
  {
    id: 'b4-supplier-crisis',
    unitId: 'B4',
    title: 'Supplier Crisis',
    icon: 'alert',
    summary: 'Thabo cannot pay suppliers. Unlimited liability strikes.',
    briefing: 'Thabo\'s car-wash owes suppliers but has no business cash. His personal assets may be at risk. Answer sole trader and partnership questions before creditors seize property.',
    tickerMessages: ['SUPPLIER: Payment overdue — legal action threatened.', 'THABO: I thought the business debts were separate.', 'LAWYER: Unlimited liability applies.', 'BANK: Personal assets may be sold.', 'FINAL NOTICE: Answer correctly or lose everything.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS4-S1', 'BS4-S2', 'BS4-S3'],
    victoryMessage: 'Crisis managed. Thabo understands his liability.',
    failMessage: 'Creditors win. Personal assets seized.',
  },
  {
    id: 'b4-bakery-dispute',
    unitId: 'B4',
    title: 'Bakery Dispute',
    icon: 'alert',
    summary: 'Partners clash — no agreement in writing.',
    briefing: 'Two bakery partners fight over profit sharing. They never wrote a partnership agreement. Answer questions on partnership clauses before the business collapses.',
    tickerMessages: ['PARTNER A: I contributed more capital!', 'PARTNER B: We never agreed on profit share.', 'MEDIATOR: A written agreement would have prevented this.', 'LAWYER: Partnership agreement clauses matter.', 'COURT: Final questions — now.'],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['BS4-S3', 'BS4-S4'],
    victoryMessage: 'Dispute resolved. Agreement drafted.',
    failMessage: 'Partnership dissolved. Business closed.',
  },
  {
    id: 'b5-investor-pitch',
    unitId: 'B5',
    title: 'Investor Pitch',
    icon: 'building',
    summary: 'Pty Ltd or partnership? Investors are waiting.',
    briefing: 'A tech start-up needs private investors but not public share sales. Convince the room why Pty Ltd beats partnership before funding walks out.',
    tickerMessages: ['INVESTOR: Why not a simple partnership?', 'FOUNDER: We need limited liability.', 'CIPC: Registration requirements for Pty Ltd.', 'BOARD: MOI and directors required.', 'FUNDING WINDOW CLOSING.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS5-S1', 'BS5-S3'],
    victoryMessage: 'Funding secured. Pty Ltd registered.',
    failMessage: 'Investors leave. Wrong structure chosen.',
  },
  {
    id: 'b5-jse-listing',
    unitId: 'B5',
    title: 'JSE Listing Rush',
    icon: 'building',
    summary: 'Public company requirements under the clock.',
    briefing: 'Green Harvest needs billions for international expansion. The JSE listing team needs answers on Ltd companies, public shares, and strict legal requirements — fast.',
    tickerMessages: ['JSE: Listing application deadline approaching.', 'REGULATOR: Financial statements must be public.', 'SHAREHOLDERS: Many owners, strict governance.', 'COMPLIANCE: Companies Act requirements.', 'LISTING DECISION: Now or never.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS5-S2', 'BS5-S3'],
    victoryMessage: 'Listed on JSE. Capital raised.',
    failMessage: 'Listing rejected. Requirements not met.',
  },
  {
    id: 'b6-public-service',
    unitId: 'B6',
    title: 'Public Service Emergency',
    icon: 'landmark',
    summary: 'SOE or company? Government needs an answer.',
    briefing: 'Commuter rail is failing. Government must decide between SOE structure and alternatives. Answer SOE and NPO questions before service shuts down.',
    tickerMessages: ['MINISTER: Essential service cannot stop.', 'COMMUTERS: We need reliable transport.', 'TREASURY: Government funding model?', 'NPO: Community food parcels also need structure.', 'PARLIAMENT: Decision required.'],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['BS6-S1', 'BS6-S2'],
    victoryMessage: 'Correct structure chosen. Service continues.',
    failMessage: 'Wrong model. Public service disrupted.',
  },
  {
    id: 'b7-green-harvest',
    unitId: 'B7',
    title: 'Green Harvest Expansion',
    icon: 'farm',
    summary: 'Guide the farm through every ownership stage.',
    briefing: 'Green Harvest Farms grows from market stall to national supplier. At each stage — sole trader, partnership, Pty Ltd, Ltd — recommend the right form before expansion fails.',
    tickerMessages: ['STAGE 1: Small market stall — sole trader?', 'STAGE 2: Partner brings equipment.', 'STAGE 3: Supermarket contracts — need Pty Ltd?', 'STAGE 4: International expansion — JSE?', 'HARVEST CRITICAL: Choose ownership now.'],
    timeLimitSeconds: 270,
    questionCount: 6,
    skills: ['BS7-S1', 'BS7-S2', 'BS7-S3'],
    victoryMessage: 'Green Harvest thrives at every stage.',
    failMessage: 'Expansion failed. Wrong ownership at each turn.',
  },
  {
    id: 'b7-compare-table',
    unitId: 'B7',
    title: 'Comparison Table Crisis',
    icon: 'farm',
    summary: 'Complete the ownership comparison before the exam.',
    briefing: 'The comparison table is blank and the exam starts soon. Fill in liability, capital, continuity, and management for each form of ownership under time pressure.',
    tickerMessages: ['EXAM: 5 minutes to seating.', 'TEACHER: Know sole vs partnership vs company.', 'STUDENT: NPO vs company profit difference?', 'CLOCK: Comparison table due.', 'BELL RINGS SOON.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS7-S1', 'BS7-S3'],
    victoryMessage: 'Table complete. Comparison mastered.',
    failMessage: 'Blank table handed in. Study again.',
  },
  {
    id: 'b8-reputation-meltdown',
    unitId: 'B8',
    title: 'Reputation Meltdown',
    icon: 'shield',
    summary: 'Stop unethical marketing before the story breaks.',
    briefing: 'A clothing store advertised 50% off everything but only discounted old stock and hid extra charges. Identify unethical practices and recommend fixes before media exposure.',
    tickerMessages: ['CUSTOMER: This sale is a scam!', 'JOURNALIST: Investigative story incoming.', 'CEO: Is our marketing ethical?', 'REGULATOR: False advertising investigation.', 'REPUTATION CRISIS: Act now.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS8-S3', 'BS8-S4'],
    victoryMessage: 'Ethics restored. Reputation saved.',
    failMessage: 'Scandal breaks. Customers leave.',
  },
  {
    id: 'b8-brighttech',
    unitId: 'B8',
    title: 'BrightTech Ethics Audit',
    icon: 'shield',
    summary: 'Fix culture and ethics before clients leave.',
    briefing: 'BrightTech Pty Ltd faces complaints: poor communication, late meetings, staff misusing computers, exaggerated advertising. Identify issues and recommend ethical solutions.',
    tickerMessages: ['EMPLOYEE: Managers never communicate clearly.', 'CUSTOMER: Your ads lie about product benefits.', 'IT: Staff doing personal projects on company time.', 'HR: Organisational culture is toxic.', 'CLIENT CONTRACTS AT RISK.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS8-S1', 'BS8-S2', 'BS8-S3'],
    victoryMessage: 'Ethics audit passed. Culture improving.',
    failMessage: 'Clients cancel contracts. Ethics failure.',
  },
  {
    id: 'b9-citizen-complaint',
    unitId: 'B9',
    title: 'Citizen Complaint',
    icon: 'users',
    summary: 'Rights violated — respond before legal action.',
    briefing: 'A business ignored employee dignity and community environmental rights. Answer citizenship and responsibility questions before lawsuits and boycotts spread.',
    tickerMessages: ['COMMUNITY: Our rights are ignored.', 'EMPLOYEE: Dignity violated at work.', 'LAWYER: Legal consequences incoming.', 'MEDIA: Business vs society headline.', 'RESPOND NOW.'],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['BS9-S1', 'BS9-S2'],
    victoryMessage: 'Rights respected. Crisis averted.',
    failMessage: 'Boycott and lawsuits. Reputation destroyed.',
  },
  {
    id: 'b10-contract-breach',
    unitId: 'B10',
    title: 'Contract Breach Alert',
    icon: 'scroll',
    summary: 'Laptop instalment contract breached — legal team waiting.',
    briefing: 'A customer signed a 12-month laptop instalment contract but stopped paying after 3 months. Prove you understand breach, valid contracts, and contract types.',
    tickerMessages: ['RETAILER: Customer stopped paying instalments.', 'LAWYER: Is this breach of contract?', 'CUSTOMER: I cannot afford payments.', 'COURT: Valid contract requirements?', 'JUDGMENT PENDING.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS10-S1', 'BS10-S2', 'BS10-S3'],
    victoryMessage: 'Contract law applied correctly.',
    failMessage: 'Case lost. Contract misunderstood.',
  },
  {
    id: 'b11-deadline-disaster',
    unitId: 'B11',
    title: 'Deadline Disaster',
    icon: 'brain',
    summary: 'Manager drowning in work — delegate or fail.',
    briefing: 'A manager misses deadlines, arrives late, refuses to delegate, and is burning out. Apply time management and delegation theory before the project collapses.',
    tickerMessages: ['PROJECT: Deadline in 2 hours.', 'MANAGER: I am doing everything myself.', 'TEAM: Waiting for delegated tasks.', 'STRESS: Burnout levels critical.', 'PROJECT FAILURE IMMINENT.'],
    timeLimitSeconds: 240,
    questionCount: 6,
    skills: ['BS11-S1', 'BS11-S2', 'BS11-S3'],
    victoryMessage: 'Tasks delegated. Deadlines met.',
    failMessage: 'Project failed. Manager collapsed.',
  },
  {
    id: 'b11-communication-breakdown',
    unitId: 'B11',
    title: 'Communication Breakdown',
    icon: 'brain',
    summary: 'Fix communication before the team quits.',
    briefing: 'Meetings start late, messages are unclear, and assertiveness is lacking. Answer communication and self-management questions to save team morale.',
    tickerMessages: ['TEAM: We never know what is happening.', 'MEETING: Started 30 minutes late again.', 'HR: Communication complaints filed.', 'BOSS: Assertiveness training needed?', 'TEAM RESIGNATIONS POSSIBLE.'],
    timeLimitSeconds: 210,
    questionCount: 6,
    skills: ['BS11-S4', 'BS11-S5'],
    victoryMessage: 'Communication restored. Team retained.',
    failMessage: 'Mass resignations. Communication failed.',
  },
];

export function getScenariosForUnit(unitId) {
  return SCENARIOS.filter((s) => s.unitId === unitId);
}
