import {
  FileText, BookOpen, Scale, Handshake, Building2, Landmark, Heart,
  GitCompare, Shield, Users, ScrollText, Brain, Trophy,
} from 'lucide-react';

export const WORLDS = [
  {
    id: 'report',
    name: 'Report Writing',
    subtitle: 'B1 · Business report structure',
    color: 'gold',
    glow: 'ja-glow-gold',
    bg: 'ja-w-report',
    icon: FileText,
    blurb: 'Title, findings, conclusions, recommendations. Write like a professional, not an essay.',
  },
  {
    id: 'concepts',
    name: 'Concept Vault',
    subtitle: 'B2 · Key definitions',
    color: 'teal',
    glow: 'ja-glow-teal',
    bg: 'ja-w-concepts',
    icon: BookOpen,
    blurb: 'Capital, liability, legal persona, continuity, MOI, CIPC. The vocabulary every mark depends on.',
  },
  {
    id: 'factors',
    name: 'Ownership Factors',
    subtitle: 'B3 · Choosing the right form',
    color: 'sky',
    glow: 'ja-glow-sky',
    bg: 'ja-w-factors',
    icon: Scale,
    blurb: 'Seven factors: legal persona, liability, tax, continuity, management, capital, formation.',
  },
  {
    id: 'sole-partner',
    name: 'Sole & Partner Alley',
    subtitle: 'B4 · Sole trader & partnership',
    color: 'orange',
    glow: 'ja-glow-orange',
    bg: 'ja-w-sole-partner',
    icon: Handshake,
    blurb: 'One owner or a team. Unlimited liability, partnership agreements, when each form suits.',
  },
  {
    id: 'companies',
    name: 'Company Tower',
    subtitle: 'B5 · Pty Ltd & Ltd',
    color: 'violet',
    glow: 'ja-glow-violet',
    bg: 'ja-w-companies',
    icon: Building2,
    blurb: 'Private and public companies. Limited liability, CIPC, MOI, directors, shareholders.',
  },
  {
    id: 'public-sector',
    name: 'Public Sector',
    subtitle: 'B6 · SOE & NPO',
    color: 'rose',
    glow: 'ja-glow-rose',
    bg: 'ja-w-public-sector',
    icon: Landmark,
    blurb: 'Government enterprises and non-profits. Service focus vs profit motive.',
  },
  {
    id: 'compare',
    name: 'Compare & Grow',
    subtitle: 'B7 · Comparison & growth',
    color: 'lime',
    glow: 'ja-glow-lime',
    bg: 'ja-w-compare',
    icon: GitCompare,
    blurb: 'Comparison tables, Green Harvest growth stages, scenario recommendations.',
  },
  {
    id: 'ethics',
    name: 'Ethics Wing',
    subtitle: 'B8 · Culture & marketing ethics',
    color: 'emerald',
    glow: 'ja-glow-emerald',
    bg: 'ja-w-ethics',
    icon: Shield,
    blurb: 'Organisational culture, ethical vs unethical behaviour, honest marketing.',
  },
  {
    id: 'citizenship',
    name: 'Citizen Plaza',
    subtitle: 'B9 · Rights & responsibilities',
    color: 'cyan',
    glow: 'ja-glow-cyan',
    bg: 'ja-w-citizenship',
    icon: Users,
    blurb: 'Citizen rights, business responsibilities, operating ethically in society.',
  },
  {
    id: 'contracts',
    name: 'Contracts Court',
    subtitle: 'B10 · Contracts & breach',
    color: 'coral',
    glow: 'ja-glow-coral',
    bg: 'ja-w-contracts',
    icon: ScrollText,
    blurb: 'Valid contracts, breach, contract types. Rights and obligations in agreements.',
  },
  {
    id: 'self-mgmt',
    name: 'Self-Management Suite',
    subtitle: 'B11 · Time, delegation, communication',
    color: 'magenta',
    glow: 'ja-glow-magenta',
    bg: 'ja-w-self-mgmt',
    icon: Brain,
    blurb: 'Time management, delegation, stress, communication, assertiveness, skills development.',
  },
  {
    id: 'exam',
    name: 'Exam Arena',
    subtitle: 'B12 · Test preparation',
    color: 'amber',
    glow: 'ja-glow-amber',
    bg: 'ja-w-exam',
    icon: Trophy,
    blurb: 'Integrated drills, exam structure, quick revision. Launch your business report practice test here.',
    isExamHub: true,
  },
];
